Add Insiders option to VS Code recent projects
raycast/extensions pull request #1000
Opened 2022-02-27 13:02 UTC by iainsimmons

## Description

Adds new preference option to the visual-studio-code-recent-projects extension to use the app paths and name for the Insiders version of Visual Studio Code.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-03-01 19:44 UTC, thomaspaulmann commented
Oh thanks for the addition. This is cool! Would it make sense to also support both applications at the same type? I don't use `Insiders` but maybe some folks use both variants of it. You could change the preference to a dropdown with three options (Code, Insiders, Code and Insiders) and have both as default. Then you can merge the results in the UI. The nice thing about that would be that it works out of the box for everyone. WDYT?

2022-03-01 19:52 UTC, iainsimmons commented
That would be nice, but I wasn't sure how best to achieve that, and it would require some additional work to kind of tag or categorise the results, etc.

I don't use both, so I'd have to download the regular version and play with it a bit. Might be better to open another PR for that.

Would that be okay?

Also for just this bit, I wasn't sure what to name/label the settings options, so feel free to change that to whatever makes sense. Naming things is hard! 😅

2022-03-02 22:25 UTC, pernielsentikaer requested changes
Hi @iainsimmons 👋 

Awesome update, I tested it, and it works as expected 🔥 

![KyW4Psh1Opld2Sln](https://user-images.githubusercontent.com/38033107/156460064-cd53e518-1805-4d84-bd90-bee93168c867.png)

![gc9olC7iN57qpJLV](https://user-images.githubusercontent.com/38033107/156460005-8594dccd-b9d5-46a2-a5eb-fe44d310de39.png)

I'll await the change of the preference type, request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions 👏

2022-03-07 23:35 UTC, iainsimmons commented
Hi guys, sorry for the delay, it's been crazy busy here for me lately. I've added the dropdown, and I agree, it's much cleaner and future-proof.

Let me know what you think.

2022-03-08 05:22 UTC, pernielsentikaer commented
Hi @iainsimmons 👋 

Thanks! Works and looks much better, good job 🔥

2022-03-08 05:22 UTC, pernielsentikaer approved these changes

2022-03-08 08:49 UTC, merged