Update Splitwise to use OAuth
raycast/extensions pull request #10005
Opened 2024-01-05 11:41 UTC by danpalmer

## Description

Ports Splitwise to use OAuth. Note: the Splitwise OAuth implementation does not support PKCE. Could someone from Raycast run a new instance of the PKCE proxy? Either I can provide the client secret for the API client I've set up, or someone from the Raycast team can set up a new client [here](https://secure.splitwise.com/oauth_clients) and I'll update the details in this PR. Some additional testing will be required once this is hooked up.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-01-09 02:01 UTC, danpalmer commented
@DiogoFerrer would you mind taking a look at this? I think it's a meaningful improvement in the usability and might help grow the userbase a bit.

2024-01-09 15:55 UTC, maximilianzuern commented on extensions/Splitwise/src/add-expense.tsx
> +        <Form.Dropdown.Item value="AUD" title={`JPY (${getCurrency_code("AUD")})`} icon="💵" />
Small typo.
Should be `AUD` for Australian Dollars.

2024-01-09 16:04 UTC, maximilianzuern requested changes
I tested the PR locally. It works like a charm! 
There is just a little typo in the add-expense.tsx file.

Since I don't have experience with 0Auth, where does the `https://raycast-pkce-proxy-splitwise.fly.dev`come from? Is it hosted by Raycast?

2024-01-09 16:04 UTC, maximilianzuern commented on extensions/Splitwise/src/add-expense.tsx
> +        <Form.Dropdown.Item value="AUD" title={`JPY (${getCurrency_code("AUD")})`} icon="💵" />
```suggestion
        <Form.Dropdown.Item value="AUD" title={`AUD (${getCurrency_code("AUD")})`} icon="💵" />
```

2024-01-09 22:20 UTC, danpalmer commented on extensions/Splitwise/src/add-expense.tsx
> +        <Form.Dropdown.Item value="AUD" title={`JPY (${getCurrency_code("AUD")})`} icon="💵" />
Whoops thanks!

2024-01-09 22:28 UTC, danpalmer commented
Thanks for the review!

> Since I don't have experience with 0Auth, where does the https://raycast-pkce-proxy-splitwise.fly.devcome from? Is it hosted by Raycast?

This is currently hosted by me – it's an instance of https://github.com/mathieudutour/pkce-proxy which is from one of the Raycast team. Raycast do host a number of these, but it takes some back and forth to get them running, and in this case I had to do a bunch of server-side debugging to get the client-side working so I'm glad I hosted my own.

I'd be happy to switch over to a Raycast hosted one, but so far this process has been ad-hoc. It's at a cost to them in terms of time and money, so I'm not sure how they decide whether this is worth it or not. I imagine this would take a while to organise and get set up, so I'd prefer to stick with this for now.

Security-wise, this protects against bad actors being able to authenticate with the Splitwise API as this extension and potentially get the extension banned. It does require trust in the proxy, but no more than the trust in the extension to manage any tokens correctly.

2024-01-14 11:17 UTC, maximilianzuern approved these changes
LGTM!

2024-01-15 15:15 UTC, thomaslombart commented
Hey @danpalmer, we usually host PKCE proxies to make sure no one is tampering with the authentication flow. It's true it involves some back and forth but we're here to help anyway 😊

Could you send me a message in the Slack community with the details so that I can deploy a proxy for you?

2024-02-06 10:03 UTC, closed without merging

2024-02-06 18:35 UTC, danpalmer commented
Ah! Sorry, this got lost. I can definitely pick this up again.

2024-02-06 19:19 UTC, maximilianzuern commented
> Ah! Sorry, this got lost. I can definitely pick this up again.

Awesome! 🎉 
Just keep in mind that I made a PR #10613 in the meantime. It fetches the default currency via the API and adds it to the dropdown menu, so manual selection via preference values is no longer necessary.