Add random-color extension
raycast/extensions pull request #10023
Opened 2024-01-06 13:44 UTC by sevensidedmarble

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-01-16 18:22 UTC, sevensidedmarble commented
@pernielsentikaer I think mine is different. None of the others are really focused on random color generation. I would really like to get it merged! but I don't understand the failure here. It says my github name is wrong or something, but that is my name on github.

2024-01-16 18:24 UTC, sevensidedmarble commented
To expand on whats different here, most of the alternatives are one of the following:
- wrappers around an external command that I (and others may not) don't use
- trying to be a dropper, which this is not interested in
- finally the most popular one is built around saving colors you want for later. this is for a color you want to throw away, when you just need a random thing for something you're designing.

2024-01-24 12:04 UTC, pernielsentikaer commented
What's your [Raycast handle](https://www.raycast.com/pernielsentikaer) - it seems like it's not right 🙂

2024-01-30 19:46 UTC, sevensidedmarble commented
ok fixed: https://www.raycast.com/sevensidedmarble

Can you rerun the checks? I don't seem to have the permission to do so without pushing a new commit

2024-01-31 11:15 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- You're missing an extension icon, you can generate [one here](https://icon.ray.so/) 

- Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-01-31 11:15 UTC, pernielsentikaer commented on extensions/random-color/package.json
> +      "subtitle": "Pick a random color.",
```suggestion
```

2024-01-31 11:15 UTC, pernielsentikaer commented on extensions/random-color/package.json
> +      "title": "Random Color",
```suggestion
      "title": "Copy Random Color",
```

2024-01-31 11:15 UTC, pernielsentikaer commented on extensions/random-color/package.json
> +      "subtitle": "Choose from some random colors.",
```suggestion
```

2024-02-15 10:49 UTC, pernielsentikaer commented
I fixed a bug since no preference values was called `clipboard` - could you check that everything is still working 🙂

2024-03-08 15:12 UTC, srcrip commented
Since I'm using the raycast CLI, how exactly do you pull remote changes from this repo?

2024-03-11 08:21 UTC, pernielsentikaer commented
You should be able to pull them with `npx @raycast/api@latest pull-contributions`

2024-03-18 16:19 UTC, srcrip commented
Ok I fixed a little issue, you should be able to re-review now.

When I want to release a new version, does it go through the same PR process btw?

2024-03-18 21:04 UTC, pernielsentikaer commented
Hi @srcrip 👋

Yes, it will, but it should be much faster since PRs with `OP is Author` are prioritized 🙂

2024-03-18 21:05 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-03-18 21:09 UTC, merged