Add Surl extension
raycast/extensions pull request #10031
Opened 2024-01-07 03:32 UTC by fujiyamaorange

## Description
Add a new extension called `Surl`.
This extension allow you make a url shorten quickly!

## Screencast
### Initial screen
![surl 2024-01-06 at 17 57 27](https://github.com/raycast/extensions/assets/63333564/5a0d162f-2282-48f4-b64c-b230e92233d5)

### Put URL you want to shorten
![surl 2024-01-06 at 17 58 22](https://github.com/raycast/extensions/assets/63333564/49024bbd-74be-46f3-979e-1749a306843e)

### Get shorten URL
![surl 2024-01-06 at 17 58 36](https://github.com/raycast/extensions/assets/63333564/764f7f10-1e1c-48a8-bbcb-3d84cd88c043)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-01-11 09:22 UTC, pernielsentikaer commented
There is something with the UX that could be improved, e.g it's not possible to search in the history. You could even split it in to multiple commands, one for adding from argument/(clipboard/selected text and one for the history

Let me know what you think 🙂

2024-01-11 09:44 UTC, fujiyamaorange commented
@pernielsentikaer 
Thank you very much for your comment! 
I agree that incorporating a search function within the history is essential. To enhance the user experience, I plan to add some additional features. I kindly request a bit of your patience while I work on these improvements. 🙏

2024-01-11 11:14 UTC, fujiyamaorange commented
@pernielsentikaer 

I am pleased to inform you that I have added two new features:

Search History
Remove & Detail History
I would greatly appreciate your thoughts and feedback on these enhancements. What do you think of these features?

2024-01-12 10:05 UTC, pernielsentikaer commented
I'm not sure whats going on with below image, I still think the UX is really confusing since there is SO many action within one view 
![surl 2024-01-12 at 10 59 33](https://github.com/raycast/extensions/assets/38033107/ecd2590f-555d-4947-ab52-3d6da2fc7a53)

2024-01-13 05:31 UTC, fujiyamaorange commented
@pernielsentikaer 
Thank you once again for your kind comments. 🐰 I am delighted to share that I have made two updates:

1. Addition of a URL Checker

This ensures that only valid URLs can be entered.

2. Separation into Two Commands: Create and History

If it's convenient for you, could you please take some time to review these changes? Your feedback would be greatly appreciated. 🙏


https://github.com/raycast/extensions/assets/63333564/e6c86122-6d75-4381-bf99-64b0513ed776

https://github.com/raycast/extensions/assets/63333564/6344b883-9552-429d-865f-f9abf79d5c48

2024-01-16 09:09 UTC, pernielsentikaer commented
Awesome update 🔥 

What about having an argument and making it a `no-view` command instead, where it validates and just copies the link to clipboard

Then it would fit better with the new history command

2024-01-16 14:16 UTC, fujiyamaorange commented
@pernielsentikaer 

I am truly impressed by your advice! 🍦
Following your suggestion, I have implemented the no-view command.

When you have a moment, could you kindly take the time to review it? 
Your feedback would be greatly appreciated.

https://github.com/raycast/extensions/assets/63333564/e4725c2a-1812-42c7-8e94-db842897058c

2024-01-24 12:01 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-01-24 12:01 UTC, pernielsentikaer commented on extensions/surl/src/history.tsx
> +                        onAction={() => handleRemoveCache(url)}
Instead of using the URL you might want to use the index? If multiple of the same URL is in the list it will remove them all

2024-01-24 12:01 UTC, pernielsentikaer commented on extensions/surl/src/history.tsx
> +                      <Action icon={{ source: Icon.Eye }} title="Toggle Detail" onAction={() => setSearchText(url)} />
What does this do? Looks like it should be removed

2024-01-24 12:50 UTC, fujiyamaorange commented
@pernielsentikaer 

Thank you once again for taking the time to review and provide valuable feedback! 🔥
I have made adjustments based on the points you mentioned.

When it's convenient for you, I would greatly appreciate it if you could review the updated work.
Thank you for your ongoing support and assistance.

2024-01-24 13:56 UTC, pernielsentikaer commented
What about removing some of the filtering logic and rely on Raycast instead? You can even use `keywords={}` - I just tried to remove some of the code and it feels much snappier like this:
```
import { ActionPanel, Action, List, Icon, Cache } from "@raycast/api";
import { useState } from "react";

const FRONTEND_ENDPOINT = "https://surlapp.uk";
const CACHE_KEY = "surl-history";

type Item = {
  key: string;
  url: string;
};

export default function Command() {
  const cache = new Cache();
  const cachedData = cache.get(CACHE_KEY);
  const cachedItems: Item[] = cachedData ? JSON.parse(cachedData) : [];
  const [items, setItems] = useState<Item[]>(cachedItems);

  const handleRemoveCache = (index: number) => {
    const newItems = cachedItems.filter((_, i) => i !== index);
    setItems(newItems);
    cache.set(CACHE_KEY, JSON.stringify(newItems));
  };

  return (
    <List searchBarPlaceholder="Please enter search word" isLoading={false}>
      <List.Section title="History">
        {items.map(({ key, url }, index) => {
          const shortenUrl = `${FRONTEND_ENDPOINT}/${key}`;
          return (
            <List.Item
              key={key}
              icon={{ source: Icon.SaveDocument }}
              title={url}
              accessories={[{ icon: Icon.CopyClipboard, text: `/${key}` }]}
              actions={
                <ActionPanel>
                  <Action.CopyToClipboard content={shortenUrl} shortcut={{ modifiers: ["cmd"], key: "c" }} />
                  <Action
                    icon={{ source: Icon.Trash }}
                    style={Action.Style.Destructive}
                    title="Remove from History"
                    onAction={() => handleRemoveCache(index)}
                    shortcut={{ modifiers: ["ctrl"], key: "x" }}
                  />
                </ActionPanel>
              }
            />
          );
        })}
      </List.Section>
    </List>
  );
}
```

2024-01-24 14:13 UTC, fujiyamaorange commented
@pernielsentikaer 

I'm truly impressed by the speed of the new code!
I've made modifications exactly as you advised.

At your earliest convenience, could you please take a moment to review it? Your feedback would be greatly appreciated.

2024-01-25 11:01 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-01-25 11:18 UTC, merged

2024-01-25 12:23 UTC, fujiyamaorange commented
@pernielsentikaer 

Thank you so much for your time and effort in reviewing!
Although it has been a long and challenging journey, I am truly delighted and grateful for the opportunity to launch this new extension.