Add codeforces-extension extension
raycast/extensions pull request #10039
Opened 2024-01-07 19:04 UTC by Iron0utlaw

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-01-07 19:16 UTC, Iron0utlaw commented
I have fixed lint issue on my machine but when I try to publish it again I receive a error
```Found & ignored ./node_modules ; is listed in .gitignore
Found & ignored ./raycast-env.d.ts ; is listed in .gitignore

Starting: publish
node:internal/modules/cjs/loader:1042
  throw err;
  ^

Error: Cannot find module '/Users/harsh/Code/Raycast Extensions/codeforces-extension/publish'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.13.0

2024-01-11 11:01 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Could you look into why both pushes has some initial data before showing the list? 

https://github.com/raycast/extensions/assets/38033107/f0060c7d-aecd-4d09-9cd5-43838dbfd0f2

- Could you look into the CI errors?

- Could you upload [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) to the PR

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-01-11 11:01 UTC, pernielsentikaer commented on extensions/codeforces-extension/package.json
> +  "title": "Codeforces-Extension",
```suggestion
  "title": "Codeforces",
```

2024-01-11 11:01 UTC, pernielsentikaer commented on extensions/codeforces-extension/package.json
> +      "subtitle": "Search a handle",
```suggestion
      "subtitle": "Codeforces",
```

2024-01-11 11:01 UTC, pernielsentikaer commented on extensions/codeforces-extension/package.json
> +      "subtitle": "Seach Upcoming and Completed Contests",
```suggestion
      "subtitle": "Codeforces",
```

2024-01-12 08:52 UTC, pernielsentikaer commented on extensions/codeforces-extension/package.json
> +      "mode": "view"
```suggestion
      "mode": "view",
      "arguments": [
        {
          "name": "handle",
          "placeholder": "Handle...",
          "type": "text",
          "required": true
        }
      ]
```

I would use an argument instead so you can save one view using [arguments](https://developers.raycast.com/information/lifecycle/arguments) - could you look into that?

2024-01-12 14:07 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-01-12 14:24 UTC, merged