Add md5 extension
raycast/extensions pull request #10182
Opened 2024-01-16 15:50 UTC by OscarRG

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-01-19 18:18 UTC, illyakurochkin approved these changes
Great job!

2024-01-22 12:19 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Instead of using a form you could make it a `no-view` command and use an [argument](https://developers.raycast.com/information/lifecycle/arguments) to get the data instead

You can also combine it with [getSelectedText](https://developers.raycast.com/api-reference/environment#getselectedtext)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-01-22 12:19 UTC, pernielsentikaer commented on extensions/md5/package.json
> +      "title": "String 2 MD5 Hash",
```suggestion
      "title": "Copy MD5 Hash",
```

2024-02-09 07:18 UTC, pernielsentikaer commented
Is this ready for another review?

2024-02-26 01:38 UTC, erics118 commented
https://www.raycast.com/eth-p/encoding-tools has an `Encode MD5` command.

2024-02-26 07:53 UTC, pernielsentikaer commented
Great catch, @erics118. There are many hidden gems in the store which do not always pop up (not sure why it didn't for me at first).

@OscarRG, could you check out the above extension? Sorry that I didn't catch it before we started the review.

2024-03-18 08:04 UTC, closed without merging