Add aspect-raytio extension
raycast/extensions pull request #10232
Opened 2024-01-18 23:54 UTC by ickas

## Description

An extension to easily calculate the aspect ratio for different sizes based on width or height, with the possibility to add custom aspect ratios.

## Screencast

<img width="1000" alt="aspect-raytio-2" src="https://github.com/raycast/extensions/assets/2805206/3bfff102-f377-4f63-a2cd-c653d05419a9">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-01-23 11:30 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Use the build-in [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) tool to make the metadata images

- It would be cool to use [arguments](https://developers.raycast.com/information/lifecycle/arguments) for even quicker measurements like this:

<img width="860" alt="image" src="https://github.com/raycast/extensions/assets/38033107/23eb2927-39b6-4e82-a188-d0c7a01460ad">

- use [useForm](https://developers.raycast.com/utilities/react-hooks/useform) in your form instead, that handles validation, errors and states - it's possible to enter text in the fields 🙂




- The ActionPanel items should have a modifier like the your Switch item

<img width="920" alt="image" src="https://github.com/raycast/extensions/assets/38033107/7afde455-833b-4304-9927-3c0280d4c305">

- Instead of having a `List.Item` showing how to create a new you could make an action on all items with cmd+n and maybe even add a subtitle to the List group. 

<img width="882" alt="image" src="https://github.com/raycast/extensions/assets/38033107/47fa5f04-8846-4387-bda9-e33ad930824f">


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-01-23 11:30 UTC, pernielsentikaer commented on extensions/aspect-raytio/src/action-options.tsx
> +          title="Delete All Custom Raytios"
```suggestion
          title="Delete All Custom Raytios"
          style={Action.Style.Destructive}
```
And maybe add a [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert?q=confirmAlert)

2024-01-24 14:45 UTC, ickas commented
@pernielsentikaer, thanks for all the suggestions; really appreciate it! I applied all of them, and it is ready for a new review!

Using arguments to send the start value directly to the app is 🔥 

The use of `List.Item` on the list to create new custom ratios was more of a UX decision than anything else. I'm afraid the user doesn't see that it has the option for that. But I moved the option to the `ActionPanel`, and I really like how clean it looks now.

2024-01-25 06:43 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-01-25 07:07 UTC, merged