Add read-ai extension
raycast/extensions pull request #10263
Opened 2024-01-21 15:01 UTC by JungHoonGhae

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-01-22 01:28 UTC, JungHoonGhae commented
I have made all the necessary changes and committed them. If there are any issues after the review, please let me know so that I can make the necessary corrections.

2024-01-22 03:08 UTC, JungHoonGhae commented
I have made all the necessary changes and committed them. If there are any issues after the review, please let me know so that I can make the necessary corrections.

2024-01-22 04:36 UTC, JungHoonGhae commented
I have made all the necessary changes and committed them. If there are any issues after the review, please let me know so that I can make the necessary corrections.

2024-01-22 04:46 UTC, JungHoonGhae commented
I have made all the necessary changes and committed them. If there are any issues after the review, please let me know so that I can make the necessary corrections. 💪🏼

2024-01-22 08:26 UTC, JungHoonGhae commented
I have made all the necessary changes and committed them. If there are any issues after the review, please let me know so that I can make the necessary corrections. 💪🏼

2024-01-23 03:46 UTC, JungHoonGhae commented
I have made all the necessary changes and committed them. If there are any issues after the review, please let me know so that I can make the necessary corrections. 💪🏼

2024-01-23 17:41 UTC, JungHoonGhae commented
I have made all the necessary changes and committed them. If there are any issues after the review, please let me know so that I can make the necessary corrections. 💪🏼

2024-01-24 00:29 UTC, JungHoonGhae commented
@pernielsentikaer I have made all the required edits and committed them. If any issues arise during the review, please inform me so that I can promptly rectify them.  💥

2024-01-24 00:38 UTC, JungHoonGhae commented
I have made all the required edits and committed them. If any issues arise during the review, please inform me so that I can promptly rectify them. 💥

2024-01-24 04:44 UTC, DophinL commented
WOW, that's really interesting.Does it support Chinese? @JungHoonGhae

2024-01-24 06:19 UTC, JungHoonGhae commented
> WOW, that's really interesting.Does it support Chinese? @JungHoonGhae

Sure! Since I am just using OpenAI's TTS (Text-to-Speech) model it supports a wide range of languages, including: Afrikaans, Arabic, Armenian, Azerbaijani, Belarusian, Bosnian, Bulgarian, Catalan, Chinese, Croatian, Czech, Danish, Dutch, English, Estonian, Finnish, French, Galician, German, Greek, Hebrew, Hindi, Hungarian, Icelandic, Indonesian, Italian, Japanese, Kannada, Kazakh, Korean, Latvian, Lithuanian, Macedonian, Malay, Marathi, Maori, Nepali, Norwegian, Persian, Polish, Portuguese, Romanian, Russian, Serbian, Slovak, Slovenian, Spanish, Swahili, Swedish, Tagalog, Tamil, Thai, Turkish, Ukrainian, Urdu, Vietnamese, and Welsh. @DophinL

2024-01-24 10:49 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-01-24 10:49 UTC, pernielsentikaer commented on extensions/read-ai/src/types/index.ts
> +}
This is already built-in inside the folder in `raycast-env.d.ts`

2024-01-24 10:49 UTC, pernielsentikaer commented on extensions/read-ai/src/index.ts
> +import { LanguageCode, readingStyle, Voice, Preferences } from "./types";
```suggestion
import { LanguageCode, readingStyle, Voice } from "./types";
```

2024-01-24 10:49 UTC, pernielsentikaer commented on extensions/read-ai/src/index.ts
> +          });
```suggestion
          showToast({
            style: Toast.Style.Animated,
            title: `💬 ${text}`,
          });
```

2024-01-24 13:14 UTC, JungHoonGhae commented
I've carefully addressed all the points in your feedback and made the necessary changes. 🛠️ Looking forward to your review of the updated extension. Thank you for your guidance! 👍🙂 @pernielsentikaer

2024-01-24 13:59 UTC, JungHoonGhae reviewed
I've carefully addressed all the points in your feedback and made the necessary changes. 🛠️ Looking forward to your review of the updated extension. Thank you for your guidance! 👍🙂 @pernielsentikaer

2024-01-24 14:00 UTC, JungHoonGhae reviewed
I've carefully addressed all the points in your feedback and made the necessary changes. 🛠️ Looking forward to your review of the updated extension. Thank you for your guidance! 👍🙂 @pernielsentikaer

2024-01-25 07:25 UTC, pernielsentikaer approved these changes
✅ Approved

2024-01-25 07:36 UTC, merged