Add raycast-transistorfm extension
raycast/extensions pull request #10291
Opened 2024-01-23 08:59 UTC by madebyankur

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-01-29 12:19 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Is there a way to stop the loader and show something if wrong API key is set?

![Raycast29012024-R3NJANYs png@2x](https://github.com/raycast/extensions/assets/38033107/f2ce6b6e-4d9e-4c34-b98a-a3799f372a3e)


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-01-29 19:33 UTC, madebyankur commented
@pernielsentikaer nice catch! Let me add some additional checks in here. Thanks! 🙌

2024-02-06 21:47 UTC, madebyankur commented
@pernielsentikaer I may have pushed this a bit too early. Updated a bunch of the logic here and cleaned things up beyond just the additional checks.

2024-02-07 09:49 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-02-07 10:08 UTC, merged