Add "Linux Command" extensio.
raycast/extensions pull request #1032
Opened 2022-03-05 15:26 UTC by jaywcjlove

## Description

Search Linux command [Chinese](https://github.com/jaywcjlove/linux-command) documentation from Raycast.

## Screencast

<img width="756" alt="image" src="https://user-images.githubusercontent.com/1680273/156889676-a4c5d6c5-3d0d-4ceb-a573-83f328c94756.png">

<img width="756" alt="image" src="https://user-images.githubusercontent.com/1680273/156889683-e0d54e59-994a-4ef6-85e8-2ae3e7163a87.png">

<img width="756" alt="image" src="https://user-images.githubusercontent.com/1680273/156889728-c45290b0-100a-4a4c-a7cd-42bf3fe2b2f4.png">

<img width="756" alt="image" src="https://user-images.githubusercontent.com/1680273/156889699-42a8fb60-e239-49ce-b5db-a4b0875faa5f.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `media` folder

2022-03-08 19:01 UTC, pernielsentikaer requested changes
Hi @jaywcjlove 👋 

Thanks for your contribution 💯 

At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

Data from source may contain Chinese though 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-09 01:24 UTC, jaywcjlove commented
@pernielsentikaer This is a plugin for searching Chinese linux command documentation.

2022-03-09 20:58 UTC, pernielsentikaer commented
Hi @jaywcjlove 👋 

We don't allow chinese in any script files, so lines like this:

`"description": "Linux命令大全搜索工具，内容包含Linux命令手册、详解、学习、搜集。",` needs to be written to something like `"description": "Search through linux commands and get detailed information in Chinese"`

Let me know if you have any questions, you can find me in [Slack](https://raycastcommunity.slack.com/) if you want to chat with me 💪

2022-03-10 00:25 UTC, jaywcjlove commented
@pernielsentikaer thx! I changed the Chinese information in the script file.

2022-03-10 21:49 UTC, pernielsentikaer requested changes
Hi @jaywcjlove 👋 

I left some feedback on the missing parts, we're soon ready to merge 🚀 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-10 21:49 UTC, pernielsentikaer commented on extensions/linux-command/package.json
> +      "subtitle": "搜索 Linux 命令",
```suggestion
      "title": "Search Linux Command",
```

2022-03-10 21:49 UTC, pernielsentikaer commented on extensions/linux-command/package.json
> +  "title": "Linux Command",
```suggestion
  "title": "Search Linux Commands",
```

2022-03-10 21:49 UTC, pernielsentikaer commented on extensions/linux-command/src/index.tsx
> +          <Action.Push
Missing an icon

2022-03-11 01:50 UTC, jaywcjlove commented on extensions/linux-command/package.json
> +      "subtitle": "搜索 Linux 命令",
Modification has been completed.

2022-03-11 01:51 UTC, jaywcjlove commented on extensions/linux-command/src/index.tsx
> +          <Action.Push
Modification has been completed.

2022-03-11 01:51 UTC, jaywcjlove commented
@raycastbot Modification has been completed.

2022-03-11 11:51 UTC, pernielsentikaer approved these changes
Hi @jaywcjlove 👋 

Thanks for the corrections, it was much better 💪 

Approved 🚀

2022-03-11 15:03 UTC, merged