fix(browser-bookmarks): sort by score
raycast/extensions pull request #10360
Opened 2024-01-26 09:31 UTC by gutenye

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-01-31 09:04 UTC, pernielsentikaer requested changes
Hi 👋

Could you add an entry in the `CHANGELOG.md` file? Here's our guidelines about that: [Version History](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history).

2024-02-01 12:32 UTC, gutenye commented
done

2024-02-02 10:53 UTC, thomaslombart approved these changes

2024-02-02 10:53 UTC, thomaslombart commented
@pernielsentikaer Ready to merge for me.

2024-02-02 11:52 UTC, merged