Add raytrilium extension
raycast/extensions pull request #10379
Opened 2024-01-26 22:43 UTC by jamtur01

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-01-31 09:45 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- You can use [useForm](https://developers.raycast.com/utilities/react-hooks/useform) which handles states, errors and validation

- When using wrong credentials I still get a success toast

![raytrilium 2024-01-31 at 10 44 01](https://github.com/raycast/extensions/assets/38033107/3132cf03-4aa3-4527-88ee-6939ab29b099)


- Consider `popToRoot()` after filling the form or clear it so it can be used again 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-01-31 09:45 UTC, pernielsentikaer commented on extensions/raytrilium/src/index.tsx
> +      <Form.TextField id="title" title="Note title" placeholder="Enter the note's title" />
```suggestion
      <Form.TextField id="title" title="Note Title" placeholder="Enter the note's title" />
```

2024-02-01 11:01 UTC, pernielsentikaer commented
Is this ready for another review?

2024-02-01 14:30 UTC, jamtur01 commented
@pernielsentikaer Yes, although the API seems to work for me locally with or without a correct token so I am poking into what's going on there.

2024-02-01 18:19 UTC, pernielsentikaer commented
Converting to a draft for now, just ping me then 🙂

2024-02-22 18:56 UTC, closed without merging