Add leitnerbox extension
raycast/extensions pull request #10370
Opened 2024-01-26 16:12 UTC by GZyannick

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-01-31 09:25 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- You're missing an extension icon, you can generate [one here](https://icon.ray.so/) 

- Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

- Missing a success toast after adding a question

- Seems like it's possible to submit the form without anything in it, you can use [useForm](https://developers.raycast.com/utilities/react-hooks/useform) to help with the validation

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-01-31 09:25 UTC, pernielsentikaer commented on extensions/leitnerbox/package.json
> +  "description": "",
Missing description

2024-01-31 09:25 UTC, pernielsentikaer commented on extensions/leitnerbox/README.md
> +# LeitnerBox
Maybe write a few lines about what it is

2024-01-31 09:25 UTC, pernielsentikaer commented on extensions/leitnerbox/package.json
> +      "title": "Create a Question",
```suggestion
      "title": "Create a Question",
      "subtitle": "LeitnerBox",
```

2024-01-31 09:25 UTC, pernielsentikaer commented on extensions/leitnerbox/package.json
> +      "title": "Daily Question",
```suggestion
      "title": "Daily Question",
      "subtitle": "LeitnerBox",
```

2024-01-31 09:25 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- You're missing an extension icon, you can generate [one here](https://icon.ray.so/) 

- Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

- Missing a success toast after adding a question

- Seems like it's possible to submit the form without anything in it, you can use [useForm](https://developers.raycast.com/utilities/react-hooks/useform) to help with the validation

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-02-06 14:28 UTC, GZyannick commented
thanks you for you feedback i will do the description logo and toast

2024-02-07 12:24 UTC, pernielsentikaer commented
Let me know if you need any help 🙂

2024-02-08 08:09 UTC, pernielsentikaer requested changes
I'm not sure if you're done yet?

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-02-20 05:42 UTC, pernielsentikaer commented
@GZyannick is this ready for another review?

2024-02-20 22:36 UTC, GZyannick commented
no i was just sending my pull request sorry for the notification

2024-02-21 12:41 UTC, pernielsentikaer commented
I just checked the extension out fresh and added two questions, when should I be able to see it in `Daily Questions`

![leitnerbox 2024-02-21 at 13 41 37](https://github.com/raycast/extensions/assets/38033107/c453c778-c964-459a-b4dc-2870bf923b4b)

2024-02-22 12:06 UTC, GZyannick commented
the system work like boxes when you add a question it will come 1 day after (box 1) there is 5box 
{
   box1: 1day,
   box2: 2days,
   box3: 4days,
   box4: 8days,
   box5: 10days
 }
 
 the goal is to learn something with consistency and time to memorize it in the long term memory

2024-02-22 12:08 UTC, GZyannick commented
if you prefere for the ux i can add something like:

 You have no question for today
 2 question in 1 day 
 1 question in 2days
 6 question in 5 days...

2024-02-22 13:47 UTC, pernielsentikaer commented
Can we add some more information so people is not getting confused about it?

2024-02-22 22:23 UTC, closed without merging

2024-02-22 23:18 UTC, GZyannick commented
Didnt close the pull request 

i have an issue to npm run publish i have in extensions on slack 
i will tell you when i can push the update