Add ai-humanizer extension
raycast/extensions pull request #10403
Opened 2024-01-28 04:22 UTC by frolvanya

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-01-31 12:47 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Could you make the [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) with our tool instead



I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-01-31 12:47 UTC, pernielsentikaer commented on extensions/ai-humanizer/src/index.tsx
> +      <Form.TextArea autoFocus={true} id="originalText" title="Original text" />
```suggestion
      <Form.TextArea autoFocus={true} id="originalText" title="Original Text" />
```

2024-01-31 12:47 UTC, pernielsentikaer commented on extensions/ai-humanizer/src/index.tsx
> +      <Form.TextArea id="humanizedText" title="Humanized text" value={humanizedText} />
```suggestion
      <Form.TextArea id="humanizedText" title="Humanized Text" value={humanizedText} />
```

2024-01-31 17:03 UTC, frolvanya commented
I've updated a screenshot and applied suggested changes
https://github.com/raycast/extensions/blob/0646be56a268442e1f52a5c46333acf8449812a4/extensions/ai-humanizer/src/index.tsx#L46
https://github.com/raycast/extensions/blob/0646be56a268442e1f52a5c46333acf8449812a4/extensions/ai-humanizer/src/index.tsx#L48

2024-02-01 11:26 UTC, pernielsentikaer approved these changes
✅ Approved

2024-02-01 11:43 UTC, merged

2024-02-01 12:43 UTC, frolvanya commented
Thanks! I just linked my account

2024-02-01 13:30 UTC, pernielsentikaer commented
Then it's automatically added 🙂