Add Qucik Surf extension
raycast/extensions pull request #1043
Opened 2022-03-07 14:23 UTC by CheatGZ

This extension is for users who Surf frequently between browsers or mailbox applications, choose your board and surf fast!

## Description

**Main features:**

1. Specify a browser to open a ***URL*** or ***Text*** that is selected or on the clipboard.
2. Specify the mailbox application to open ***mailto:*** link (in the form of "[mailto:hello@raycast.com](mailto:mailto:hello@raycast.com)") that is selected or on the clipboard.
3. Support search bar input:
   Enter ***URL*** or ***Text*** to search or open web page quickly.
   Enter the shortcut phrase ***mailto:***  followed by email address to enter the edit email page.
4. Recommend to set shortcut keys for this extension in order to Quick Quick Surf.

**Preference:**
*Surf Engine* - the default search engine for searching text.
*Sort by* - Surfboard sorting method.

**Known issues:**
If the added application is uninstalled, you will not be able to remove it directly. Please press "cmd" + "enter" on the "More Boards" page to remove all the apps and then add them again.

## Screencast

First, "More Boards"，add application you want to use.

<img src="./media/More Boards-1.png" alt="More Boards-1" style="zoom:25%;" />

<img src="./media/More Boards-2.png" alt="More Boards-2" style="zoom:25%;" />

Quick search ***Text*** that is selected, on the clipboard or from input using a specified browser

<img src="./media/Search Text.png" alt="Search Text" style="zoom:25%;" />

Quick open ***URL*** that is selected, on the clipboard or from input using a specified browser

<img src="./media/Open URL.png" alt="Open URL" style="zoom:25%;" />

Quick open ***"mailto"*** link that is selected, on the clipboard or from input using a specified browser

<img src="./media/mailto.png" alt="mailto" style="zoom:25%;" />

## 

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed in the `media` folder

2022-03-08 20:02 UTC, pernielsentikaer requested changes
Hi @CheatGZ 👋 

Thanks for your contribution, it seems like a very useful idea that you're building here.

I have some feedback for you to address:

If clipboard and nothing is selected, should there then be the `Surfboard` section? Seems like if I use `Mimestream` with empty clipboard, it does something weird 😄 

![66rmOmQfN23lSz6W](https://user-images.githubusercontent.com/38033107/157315406-94d1df21-3dc9-4c98-a2e6-b4ab9ee9ebba.png)

![FIqo3CM93EO5a74H](https://user-images.githubusercontent.com/38033107/157315431-ffea03d2-d275-4028-a87d-234d699773d4.png)

- When opening a URL from clipboard, some elements in surfboard switches place, is that as intended?

https://user-images.githubusercontent.com/38033107/157316461-48e78a32-fe8e-447d-a623-db5c5f14170d.mp4

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-09 09:10 UTC, CheatGZ commented
Hi, @pernielsentikaer 👋
Thank you for your review, I have noticed the issues you mentioned. Here is my response.

**The first question is divided into two parts：**
Part I - Empty Clipboard

- The clipboard is not empty, but there is a delay in the appearance of text, because of runAppleScript ("the clipboard"), it will be the clipboard image or file parsed as text, the second screenshot to see the "Type" section of the appearance of the Text.
  Delay reason: Quick Surf detects the selected text first and then detects the clipboard. So it detects the clipboard, the speed will be slower. Therefore, it is more recommended to use the "Select-Surf" method(Select text or URL and open Quick Surf).
- Fix solution:
  When the detection is empty, keep the "Surfboard" section, and use toast to prompt the user to enter text.
  In rare cases, the detection will be empty, and hiding the "Surfboard" Section will make people confused: where is the Surfboard that was added.

<details>
<summary>Clipboard detect delay</summary>

https://user-images.githubusercontent.com/36128970/157384041-81a5ed86-6f1e-4c1f-8415-20114b6f59d5.mp4

</details>


Part II - Mimestream No Respond

- Quick Surf uses the “Open()” provided by Raycast to open links in specific applications, it allows any application to open a URL or "mailto:" link, but if open the URL with a non-browser application, there will be no response and no error will be reported. Similarly, if a non-email client is used to open a "mailto:" link, no response or error will be reported (except for Safari).
- Fix solution:
  There is no better solution now because users can choose any application to open the link, but I don't know how the app will react; Only expect users to open the URL or the "mailto:" link with the appropriate application(browsers or email clients).

**The Second question:**

- I'm glad you noticed this, I did intend to do this. The types of text that the extension can receive are URL, Text, and Email address("mailto:"), so I designed a simple recommendation algorithm that will record the user's habits and sort the "Surfboard" section according to input, for example, if you often use Safari to search for text, Safari will rise when input is text; if you often use Mimestream to edit emails, Mimestream will rise when input is an email address.

<details>
<summary>InputType</summary>

<img width="923" alt="image" src="https://user-images.githubusercontent.com/36128970/157409444-c8fcaff4-a041-450b-83fb-68a0954691b5.png">

https://user-images.githubusercontent.com/36128970/157388750-f5abc024-c506-4d6e-8c82-d9d07c13a531.mp4

</details>


- If users don't like the automatic sorting of the "Surfboard" section, they can choose to sort by name in Preferences.

2022-03-09 21:35 UTC, pernielsentikaer requested changes
Hi @CheatGZ 

Seems to do better with the things I've tested 🔩 

I have some feedback for you:

- Is it on purpose that the @dark icons have the dark background? Seems like it should be reverted (could also just be me)

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-09 21:35 UTC, pernielsentikaer commented on extensions/quick-surf/package.json
> +      "title": "Surf with...",
```suggestion
      "title": "Quick Surf",
```
Maybe change title to this?

2022-03-09 21:35 UTC, pernielsentikaer commented on extensions/quick-surf/src/quick-surf.tsx
> +  isEmpty,
```suggestion
```
Unused import specifier

2022-03-09 21:35 UTC, pernielsentikaer commented on extensions/quick-surf/src/quick-surf.tsx
> +        <ActionPanel title="Game controls">
Game controls? Remember to `Title Case` the corrected

2022-03-09 21:35 UTC, pernielsentikaer commented on extensions/quick-surf/src/quick-surf.tsx
> +      await showToast(Toast.Style.Failure, "Nothing, Enter Now!");
Could be a better error message

2022-03-10 12:04 UTC, CheatGZ commented
Hi, @pernielsentikaer.
Thank you for your review. Your comments were very informative and I have made changes accordingly.
Update:
1. Light icons and dark icons are swapped, now the icons are more eye-catching.
2. Command name change to Quick Surf.
3. New detect tip: "Nothing is detected from Selected or Clipboard! "
4. Application of “Suggest” section add tips.
5. Support IP address, support URL without "https://".
6. More action.
7. Redundant code cleaning.

2022-03-10 21:34 UTC, pernielsentikaer approved these changes
Hi @CheatGZ 👋 

Thanks for your update, tested it again, and it does as expected, awesome! 

Approved, lets send it to final review!

2022-03-10 22:28 UTC, merged