Ext/hebrish
raycast/extensions pull request #10446
Opened 2024-01-30 13:07 UTC by hushhash

## Description

Fixed Hebrish to code review:
- Switched to no-view
- Added an extension icon
- Added try/catch where needed
- Cleaned up logs and prints

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-02-03 06:45 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- What about capital letters? It seems like when you convert to hebrew and back again it all small letters?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-02-03 06:45 UTC, pernielsentikaer commented on extensions/hebrish/package.json
> +      "title": "To Hebrew",
```suggestion
      "title": "English to Hebrew",
```

2024-02-03 06:45 UTC, pernielsentikaer commented on extensions/hebrish/package.json
> +      "title": "To English",
```suggestion
      "title": "Hebrew to English",
```

2024-02-08 07:31 UTC, hushhash commented
Thank you for this!

Hebrew doesn't have capital letters.
The purpose of this extension is for when you try and write in English and
you accidentally typed it on a Hebrew keyboard or vice versa.
The better use case would be to write something in Hebrew, switch to
English using the function and then switch it back using the other function.
When you try and write capitalized English letters on a Hebrew keyboard, no
letters are actually being typed. Therefore, this is a limitation. It does
not however make the extension less useful for its intended purpose.
Makes sense?

All the best and thank you for this awesome platform.

--------------------
Alon Shacham



On Sat, 3 Feb 2024 at 08:45, Per Nielsen Tikær ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi 👋
>
> Thanks for your contribution 💪
>
> I have now tested your extension, and I have some feedback ready for you:
>
>    - What about capital letters? It seems like when you convert to hebrew
>    and back again it all small letters?
>
> I'm looking forward to testing this extension again 🔥
>
> Request a new review when you are ready. Feel free to contact me here or
> at Slack <https://www.raycast.com/community> if you have any questions.
> ------------------------------
>
> In extensions/hebrish/package.json
> <https://github.com/raycast/extensions/pull/10446#discussion_r1476995185>:
>
> > @@ -0,0 +1,46 @@
> +{
> +  "$schema": "https://www.raycast.com/schemas/extension.json",
> +  "name": "hebrish",
> +  "title": "Hebrish",
> +  "description": "Change English written in Hebrew and Hebrew written in English",
> +  "icon": "hebrish-icon.png",
> +  "author": "alon_shacham",
> +  "categories": [
> +    "Productivity"
> +  ],
> +  "license": "MIT",
> +  "commands": [
> +    {
> +      "name": "to-hebrew",
> +      "title": "To Hebrew",
>
> ⬇️ Suggested change
>
> -      "title": "To Hebrew",
> +      "title": "English to Hebrew",
>
> ------------------------------
>
> In extensions/hebrish/package.json
> <https://github.com/raycast/extensions/pull/10446#discussion_r1476995212>:
>
> > +  "icon": "hebrish-icon.png",
> +  "author": "alon_shacham",
> +  "categories": [
> +    "Productivity"
> +  ],
> +  "license": "MIT",
> +  "commands": [
> +    {
> +      "name": "to-hebrew",
> +      "title": "To Hebrew",
> +      "description": "Change Hebrew accidently written on an English keyboard to Hebrew",
> +      "mode": "no-view"
> +    },
> +    {
> +      "name": "to-english",
> +      "title": "To English",
>
> ⬇️ Suggested change
>
> -      "title": "To English",
> +      "title": "Hebrew to English",
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/raycast/extensions/pull/10446#pullrequestreview-1860886753>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHOCHQZTE4FH7LTJJOQO7DYRXMJNAVCNFSM6AAAAABCRHDMNOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNRQHA4DMNZVGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-08 07:37 UTC, pernielsentikaer commented
Can we find another name than `To Hebrew` - Convert to Hebrew?

2024-02-08 07:40 UTC, hushhash commented
Of course!
Do you want me to change them to "Convert to Hebrew" and "Convert to
English" and update the PR?
--------------------
Alon Shacham



On Thu, 8 Feb 2024 at 09:37, Per Nielsen Tikær ***@***.***>
wrote:

> Can we find another name than To Hebrew - Convert to Hebrew?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/raycast/extensions/pull/10446#issuecomment-1933505915>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHOCHVGLAEFH22MPN3WAE3YSR6DBAVCNFSM6AAAAABCRHDMNOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMZTGUYDKOJRGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-08 07:57 UTC, hushhash commented
done
--------------------
Alon Shacham



On Thu, 8 Feb 2024 at 09:40, Alon Shacham ***@***.***> wrote:

> Of course!
> Do you want me to change them to "Convert to Hebrew" and "Convert to
> English" and update the PR?
> --------------------
> Alon Shacham
>
>
>
> On Thu, 8 Feb 2024 at 09:37, Per Nielsen Tikær ***@***.***>
> wrote:
>
>> Can we find another name than To Hebrew - Convert to Hebrew?
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/raycast/extensions/pull/10446#issuecomment-1933505915>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AAHOCHVGLAEFH22MPN3WAE3YSR6DBAVCNFSM6AAAAABCRHDMNOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMZTGUYDKOJRGU>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2024-02-22 09:25 UTC, pernielsentikaer commented
Hi @hushhash 👋

I'm really sorry that I didn't find the extension from the Store before reviewing this. Are you okay with using that, or enhancing it if something is missing?

2024-03-14 10:26 UTC, closed without merging