New extension: Perplexity-API
raycast/extensions pull request #10511
Opened 2024-02-02 00:44 UTC by maximilianzuern

## Description

This extension provides user access to all models through the [Perplexity API](https://docs.perplexity.ai/docs/getting-started).

There is a Raycast [perplexity extension](https://github.com/raycast/extensions/tree/main/extensions/perplexity) but it just opens query links in the browser for faster access to the GPT4 and GPT3.5 web interface. 

This extension, though, gives user access to models not offered on the web interface. That's why I built a new extension rather than updating the existing one because they serve different purposes.

### Selected Text Commands

- Change tone to casual
- Change tone to friendly
- Change tone to professional
- Comment code
- Compose Message/Mail responses
- Explain selected text
- Fix grammar and spelling
- Improve selected text
- Make selected text longer
- Make selected text shorter
- Summarize selected text
- Find synonyms according to the selected word
- Break down project description into tasks
- Translate selected text

### Quick AI
- Ask AI a one-shot question

### Supported Models

* codellama-34b-instruct
* codellama-70b-instruct
* llama-2-70b-chat
* mistral-7b-instruct
* mixtral-8x7b-instruct
* pplx-7b-chat
* pplx-70b-chat

## Screencast

![prompt](https://github.com/raycast/extensions/assets/85677120/28c06640-2169-4f58-bdd0-07321ad17cad)
![askAI](https://github.com/raycast/extensions/assets/85677120/17b72c10-56e8-41e1-ad8f-1c49d9b2205e)
![fix](https://github.com/raycast/extensions/assets/85677120/a55382c2-f3fc-4152-9f10-2734e03c776d)
![summary](https://github.com/raycast/extensions/assets/85677120/b656eee0-2285-4c92-b663-05b0f598dcab)

Additionally, it calculates the cost per request, as displayed in the toast notification.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-02-06 08:26 UTC, pernielsentikaer commented
I really think it would make sense to only have one Perplexity extension - what do you think, @third774?

This seems like a far better way to work with perplexity

2024-02-07 02:40 UTC, third774 commented
I'm hopeful that one day my extension can be deprecated/removed — especially with the upcoming work y'all are doing to directly integrate Perplexity with Raycast. That said, I would argue that the current extension is still _very_ useful in a few ways:
- No API key required!
- Can make use of Perplexity's copilot mode
- Can make use of Perplexity's focus modes

I don't know if these are available via the API access to models are they? Often, I also like to inspect the search results that are surfaced in the web UI. I think we'd be losing that as well, wouldn't we?

I'm def not opposed to merging these two extensions though if y'all think that's best! It's just that personally I think I'm going to keep using the web UI until those features are available directly in Raycast.

2024-02-07 11:21 UTC, pernielsentikaer commented
What about we merge them so we can keep both yours and all the new stuff? It will require that content of the PR is added on top of the current extension so it's "just" an update 🙂

2024-02-07 13:07 UTC, maximilianzuern commented
>     * No API key required!
> 
>     * Can make use of Perplexity's copilot mode
> 
>     * Can make use of Perplexity's focus modes
> 
> 
> I don't know if these are available via the API access to models are they? Often, I also like to inspect the search results that are surfaced in the web UI. I think we'd be losing that as well, wouldn't we?

Exactly! None of those features are accessible through the API. Moreover, the web UI uses models from OpenAI, Anthropic and Google, whereas the API relies on models from Meta, Mistral, and Perplexity.

> What about we merge them so we can keep both yours and all the new stuff? It will require that content of the PR is added on top of the current extension so it's "just" an update 🙂

The point is, the two extensions serve different purposes. Individuals seeking access to GPT3.5 or GPT4 prefer the web UI, whereas those who favor open-source models would use my extension.
Still, I get why you might consider merging them. In this case, should I modify the PR?

2024-02-07 14:26 UTC, pernielsentikaer commented
Sounds like it's better to keep it as two separate, as long as the naming clearly shows it 🙂

2024-02-07 14:27 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-02-07 14:27 UTC, pernielsentikaer commented on extensions/perplexity-api/CHANGELOG.md
> +# perplexity-api Changelog
```suggestion
# Perplexity API Changelog
```

2024-02-07 14:27 UTC, pernielsentikaer commented on extensions/perplexity-api/README.md
> +# perplexity-api
```suggestion
# Perplexity API
```

2024-02-07 14:27 UTC, pernielsentikaer commented on extensions/perplexity-api/package.json
> +      "name": "apiKey",
Maybe add a `placeholder`

2024-02-07 14:36 UTC, maximilianzuern commented on extensions/perplexity-api/package.json
> +      "name": "apiKey",
Added via 587fe7f

2024-02-07 15:08 UTC, pernielsentikaer commented
Would it make sense to make some of the commands disabled by default? Like we do in our [Spotify](https://www.raycast.com/mattisssa/spotify-player) extension 🙂

2024-02-07 17:15 UTC, maximilianzuern commented
> Would it make sense to make some of the commands disabled by default? Like we do in our [Spotify](https://www.raycast.com/mattisssa/spotify-player) extension 🙂

Thank you! I was unaware of the property.
I disabled some commands.

2024-02-08 08:03 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-02-08 08:20 UTC, merged