feat: Add Shiori extension
raycast/extensions pull request #10540
Opened 2024-02-03 04:28 UTC by namiwang

## Description

## Screencast

<!-- If you add a new extension or command, include a screencast (or screenshot for straightforward changes). A good screencast will make the review much faster - especially if your extension requires re

![Screenshot 2024-02-03 at 12 27 50](https://github.com/raycast/extensions/assets/1160688/a881c7f9-40f4-42dd-8eb5-8e3f5019b343)

![Screenshot 2024-02-03 at 12 24 45](https://github.com/raycast/extensions/assets/1160688/f10d8080-693f-4b56-b63d-89080fb133ef)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-02-07 21:31 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- You can use [useForm](https://developers.raycast.com/utilities/react-hooks/useform) for states, errors and validation

- Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension using the built-in tool instead

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-02-07 21:31 UTC, pernielsentikaer commented on extensions/shiori/src/addBookmark.tsx
> +      <Form.TextField id="url" title="URL to bookmark" />
```suggestion
      <Form.TextField id="url" title="URL to Bookmark" />
```

2024-02-08 13:08 UTC, namiwang commented
@pernielsentikaer thanks for the review! I've addressed the issues and please help review the changes. Thanks!

2024-02-08 15:34 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-02-08 15:52 UTC, merged