Add query-chatgpt extension
raycast/extensions pull request #10696
Opened 2024-02-10 20:14 UTC by cyxn

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-02-14 12:31 UTC, pernielsentikaer commented
Hi 👋

I couldn't get this to work, could you make me a screencast of the two commands?

2024-02-14 15:33 UTC, cyxn commented
Hi @pernielsentikaer .
Did you see https://share.cleanshot.com/4bQ2Kl3r that completely demonstrates the flow?

2024-02-15 12:12 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 I saw the video and it makes sense, only a few NITs and we're ready to go

I have now tested your extension, and I have some feedback ready for you 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-02-15 12:12 UTC, pernielsentikaer commented on extensions/query-chatgpt/package.json
> +          "placeholder": "GPT Url",
```suggestion
          "placeholder": "GPT URL",
```

2024-02-15 12:12 UTC, pernielsentikaer commented on extensions/query-chatgpt/package.json
> +          "placeholder": "Your query",
```suggestion
          "placeholder": "Your Query",
```

2024-02-15 12:12 UTC, pernielsentikaer commented on extensions/query-chatgpt/src/query-chatgpt-custom-create.tsx
> +        title="GPT Url"
```suggestion
        title="GPT URL"
```

2024-02-16 05:55 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-02-16 08:29 UTC, merged