Add support for The Finer Gifs Club
raycast/extensions pull request #1073
Opened 2022-03-10 20:10 UTC by josephschmitt

## Description

Adds a new command to search for GIFs from [The Finer Gifs Club](https://thefinergifs.club). This one's especially meaningful to me since I [created The Finer Gifs Club](https://joe.sh/in-search-of-finer-gifs) a few years ago to try and be the definitive search engine for finding gifs from The Office. It works just like searching for gifs from giphy.com and tenor.com, it's just limited to thefinergifs.club gifs.

Adding support was pretty standard, but had to make a couple of changes in order to accommodate not having a few fields in the IGif interface.

## Screencast

<img width="886" alt="image" src="https://user-images.githubusercontent.com/136007/157746318-fb1950e9-a7b7-4a10-9433-33e203f6ae2e.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `media` folder

2022-03-10 20:44 UTC, josephschmitt commented on extensions/gif-search/src/models/gif.ts
> +  url?: string;
The Finer Gifs club has no standalone page for a single gif, so make this field optional

2022-03-10 20:44 UTC, josephschmitt commented on extensions/gif-search/src/models/gif.ts
> +  attribution?:
No attribution needed for the finer gifs club, so optional here, too

2022-03-14 16:30 UTC, pernielsentikaer requested changes
Hi @josephschmitt 👋 

Thanks for the contribution 💪 I have some feedback and suggestions for you to address:

- package.json
  - Remove the `tenor-apiKey` since it's not in use.
  
- tenor.tsx 
  - `isShowingDetail` - Could be an idea to check if showPreview and if there is any items instead of isLoading, it makes a bad UX
 
The same goes for the two other 💪 

Looking forward to testing it out again 💯 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-14 19:36 UTC, josephschmitt commented
> package.json
> 
> * Remove the `tenor-apiKey` since it's not in use.

Sorry not sure what you mean. I'm using this preference when someone uses the Tenor Search command.

2022-03-14 19:41 UTC, josephschmitt commented
@pernielsentikaer 
> tenor.tsx
> 
> * `isShowingDetail` - Could be an idea to check if showPreview and if there is any items instead of isLoading, it makes a bad UX

Done! Good catch!

2022-03-16 16:24 UTC, josephschmitt commented
Just bumping this PR from last week in case it got lost in your inboxes... @pernielsentikaer @fe9lix. Thanks!

2022-03-16 20:32 UTC, pernielsentikaer requested changes
Hi @josephschmitt 👋 

Thanks for your patience and corporation trying things out, it's still some pretty new features that might need some tweaking, thanks for helping out 💪 

I have some feedback from the spin I gave it ready for you 😄 I also wrote you in [Slack](https://raycastcommunity.slack.com/) if you want to discuss anything at all.

- For all of them
  - After testing it out, I think all the <List> elements should have `isShowingDetail={true}` instead, I couldn't find anything in the documentation saying that it's illegal to do _(I'll get back to you with this one)_. If this is not set, then there is a lot of flicker while searching that we can avoid. 
  
- The Finer GIFs Club
  -  When deleting the search query, it should then go back to “No Results”

- Giphy
  - The preference `API Key` should be type password instead of text

- Tenor
  - The preference `API Key` should be type password instead of text

We're now adding support for [categories](https://developers.raycast.com/basics/prepare-an-extension-for-store#categories), [screenshots](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) and [changelog](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) – do you have time for adding this too, I can do the screenshots if you want help 😄 

---
Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-16 23:30 UTC, josephschmitt commented
> * After testing it out, I think all the  elements should have `isShowingDetail={true}` instead, I couldn't find anything in the documentation saying that it's illegal to do _(I'll get back to you with this one)_. If this is not set, then there is a lot of flicker while searching that we can avoid.

Had to keep the check for the results otherwise we don't get the correct "No Results" screen, so mostly just gets rid of the `isLoading` check.

2022-03-21 07:37 UTC, pernielsentikaer approved these changes
Hi @josephschmitt 👋 

Thanks for the update, much better 🔥 

Tested it all, everything works as expected, awesome 💪

2022-03-21 09:48 UTC, merged