Add ghq extension
raycast/extensions pull request #10768
Opened 2024-02-15 02:33 UTC by konojunya

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-02-20 08:15 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- I don't have `Visual Studio Code` installed so maybe it would be better to ask the user in preferences for editor with [appPicker](https://developers.raycast.com/api-reference/preferences#return)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-02-20 08:15 UTC, pernielsentikaer commented on extensions/ghq/package.json
> +      "title": "ghq root path",
```suggestion
      "title": "ghq Root Path",
```

2024-02-22 10:55 UTC, konojunya commented on extensions/ghq/package.json
> +      "title": "ghq root path",
fix: https://github.com/raycast/extensions/pull/10768/commits/e33797621cd3232c1cd10178c38487c92544b32e

2024-02-22 10:57 UTC, konojunya commented
@pernielsentikaer 

- editor can now be set by preference
- update package.json

Please review again!

2024-02-22 13:51 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-02-22 14:16 UTC, merged