Add base64-to-file extension
raycast/extensions pull request #10777
Opened 2024-02-15 15:40 UTC by iamforrest

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-02-15 16:37 UTC, arian81 commented
Hey you should change the icon of your extension, it's going to get rejected per docs.

2024-02-15 16:39 UTC, arian81 commented on extensions/base64-to-file/assets/command-icon.png
You can't use default icon change it to something else. https://icon.ray.so/ This website is helpful for generating icons.

2024-02-18 15:57 UTC, iamforrest commented on extensions/base64-to-file/assets/command-icon.png
added my own icon

2024-02-20 08:25 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Maybe add a preference which uses [directory](https://developers.raycast.com/api-reference/preferences#return) so the user is able to set a standard path for the output?

- Is this only for images and what format? Tried entering `SG93IGFyZSB5b3UgdG9kYXk=` which added a file, but the file is corrupted

- Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-03-01 03:51 UTC, erics118 commented
There are two extensions that I think do similar things:
https://www.raycast.com/DanielSinclair/base64
https://www.raycast.com/eth-p/encoding-tools

I'm not too sure, but it might be better to contribute to one of those extensions instead of making a new one.

2024-03-01 07:16 UTC, pernielsentikaer commented
It could also be a way to go yes, are you still around @iamforrest

2024-03-01 11:05 UTC, iamforrest commented
I've attached three screenshots directly here. However, sorry that I'm unsure of the appropriate directory within the codebase to place these images.

<img width="1000" alt="Xnip2024-03-01_18-52-18" src="https://github.com/raycast/extensions/assets/2240276/eb5f16bd-57bd-4e37-b109-efac0bfe950d">
<img width="1911" alt="Xnip2024-03-01_19-01-20" src="https://github.com/raycast/extensions/assets/2240276/ded53822-b6ec-445d-a193-608deca6b8fa">
<img width="1920" alt="Xnip2024-03-01_19-01-50" src="https://github.com/raycast/extensions/assets/2240276/e14ae9b7-77cd-4d2d-b7a5-fef25c66281c">

2024-03-02 07:07 UTC, pernielsentikaer commented
So, what are you using as base64? Can you share an example so I can test?

2024-03-03 02:33 UTC, iamforrest commented
> So, what are you using as base64? Can you share an example so I can test?

here is an example:


[base64.txt](https://github.com/raycast/extensions/files/14471469/base64.txt)

[Raycast Developers.pdf](https://github.com/raycast/extensions/files/14471466/Raycast.Developers.pdf)

2024-03-03 06:37 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-03-03 06:47 UTC, merged