VSCode Project Manager extension: support projects_cache_any.json
raycast/extensions pull request #1077
Opened 2022-03-11 06:44 UTC by KELiON

## Description

I use VSCode Project Manager that works for me in VSCode, but Raycast extension doesn't show any results. I found, that all my projects are in file `projects_cache_any.json`:

```
$ ls ~/Library/Application\ Support/Code/User/globalStorage/alefragnani.project-manager
projects.json           projects_cache_any.json
```

And this file have the same structure as `projects_cache_git.json` (array of JSON objects with keys `name` and `fullPath`)

## Screencast

<table border="0">
 <tr>
    <td><b style="font-size:30px">Before</b></td>
    <td><b style="font-size:30px">After</b></td>
 </tr>
 <tr>
    <td>
    <img width="862" alt="Screenshot 2022-03-11 at 12 08 02" src="https://user-images.githubusercontent.com/594298/157815508-a33fb9f2-20e9-461c-a96b-966012e600d7.png">
</td>
    <td>
      <img width="862" alt="Screenshot 2022-03-11 at 12 08 28" src="https://user-images.githubusercontent.com/594298/157815570-c067b053-bf5c-4ac0-9944-0abdb8ce985e.png">
   </td>
 </tr>
</table>

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed in the `media` folder

2022-03-11 08:17 UTC, MarkusLanger commented
@KELiON Thanks for the contribution!

2022-03-14 04:47 UTC, pernielsentikaer requested changes
Hi @KELiON 👋 

Thanks for the update, seems to do as expected 🔥 Could you look into the complaint from the linter:

`src/search-project-manager-projects.tsx` seems like Prettier formatting is broken, can you look into this?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-14 08:21 UTC, KELiON commented
Hey @pernielsentikaer! Thanks, I've fixed formatting and now build passes

2022-03-14 08:42 UTC, pernielsentikaer approved these changes
Hi @KELiON 👋 

Thanks for the update, much better 🔥

2022-03-14 10:13 UTC, merged