Update random extension
raycast/extensions pull request #10931
Opened 2024-02-24 10:44 UTC by stefanmatar

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-02-24 11:43 UTC, loris requested changes

2024-02-24 12:14 UTC, stefanmatar commented on extensions/random-data-generator/src/utils/index.ts
> +          return value ? value.toString() : value === false ? "false" : "";
Yep, as "true" is truthy. But we can refactor to guard clauses to improve readability 👍

2024-02-25 07:00 UTC, pernielsentikaer commented
Do you have more feedback @loris or is this good to go 🙂

2024-02-25 07:11 UTC, loris commented
@pernielsentikaer good to go👍🏼 thank you @stefanmatar

2024-02-25 07:34 UTC, pernielsentikaer approved these changes

2024-02-25 07:34 UTC, merged