Add markprompt extension
raycast/extensions pull request #10952
Opened 2024-02-25 21:46 UTC by nickrttn

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-03-01 11:34 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Maybe add a List.EmptyView when entering the extension OR search searchbar placeholder to help people understand how to use it.

- The extension logo doesn't work well in light appearance, you can have an inverted copy and add @dark to the filename
<img width="1001" alt="image" src="https://github.com/raycast/extensions/assets/38033107/e88542b0-43ea-4107-9b07-9eee5ba1458f">

- Look at the CI error 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-03-01 11:34 UTC, pernielsentikaer commented on extensions/markprompt/package.json
> +      "title": "Project token"
```suggestion
      "title": "Project Token"
```

2024-03-04 11:46 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-03-04 12:25 UTC, merged

2024-03-04 12:31 UTC, nickrttn commented
Thanks folks :)