A new extension to format datetime.
raycast/extensions pull request #1098
Opened 2022-03-13 15:37 UTC by yangxyo

## Description

Convert timestamps and datetime strings into various formats.

## Screencast
<img width="500" alt="form" src="https://user-images.githubusercontent.com/32320149/158067332-4b532273-6ea0-415c-ad79-2b88a7d0e0aa.png">

<img width="500" alt="result" src="https://user-images.githubusercontent.com/32320149/158067350-d0e11a70-2892-4c7e-9fd2-7222c103b654.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `media` folder

2022-03-16 06:31 UTC, pernielsentikaer requested changes
Hi @yangxyo 👋 

First, you have another extension in your PR, could you please remove this 😄 

Just out of curiosity, what's the use case of this extension?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-16 16:04 UTC, yangxyo commented
I just use it to get the current time when I write my blog. 

2022-11-11 11:11:11

2022-03-21 07:32 UTC, pernielsentikaer requested changes
Hi @yangxyo 👋 

If you don't know how to do it or have no clue about it, then it's quite hard to guide you to do it. 

Could be better just to start all over – move your extension out of the directory, and then checkout `raycast/extensions` again and push it again – if it's a new PR it's also okay

I left some feedback for you to address 😄

2022-03-21 07:32 UTC, pernielsentikaer commented on extensions/datetime-format-converter/src/index.tsx
> +        <Action.CopyToClipboard content={item.content} />
```suggestion
        <Action.CopyToClipboard content={item.content} />
        <Action.Paste content={item.content} />
```
Paste directly could be nice

2022-03-21 07:32 UTC, pernielsentikaer commented on extensions/datetime-format-converter/package.json
> +  "title": "Datetime Format Converter",
```suggestion
  "name": "date-format-converter",
  "title": "Date Format Converter",
```

2022-03-21 07:32 UTC, pernielsentikaer commented on extensions/datetime-format-converter/package.json
> +      "title": "ts",
```suggestion
      "title": "Format Date",
```

2022-03-21 07:32 UTC, pernielsentikaer commented on extensions/datetime-format-converter/package.json
> +      "subtitle": "Datetime Format",
```suggestion
```

2022-04-06 22:23 UTC, sxn commented
hi @yangxyo - hope you don't mind, I've taken the liberty to delete the extra extension & implementing @pernielsentikaer 's changes. 😸

2022-04-06 23:59 UTC, yangxyo commented
> hi @yangxyo - hope you don't mind, I've taken the liberty to delete the extra extension & implementing @pernielsentikaer 's changes for you. 😸 Feel free to revert them if you disagree with them. 😉 

Thx very much.

2022-04-07 19:33 UTC, merged