Update power-management extension
raycast/extensions pull request #10995
Opened 2024-02-27 22:08 UTC by bbatsche

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-03-01 13:11 UTC, pernielsentikaer requested changes
Hi 👋

I still need to enter the password after every run, also I need to enter the password - should I do anything to test in order to use touch id?

2024-03-04 07:14 UTC, bbatsche commented
You need to configure `sudo` to use Touch ID. Depending on your version of macOS, there are [two](https://sixcolors.com/post/2020/11/quick-tip-enable-touch-id-for-sudo/) [ways](https://sixcolors.com/post/2023/08/in-macos-sonoma-touch-id-for-sudo-can-survive-updates/) to do this. This change should support both.

2024-03-04 12:14 UTC, pernielsentikaer commented
Perhaps consider adding a note in the README regarding this matter. Could you do that?

2024-03-06 16:33 UTC, bbatsche commented
Sure, I can add that! Thanks for your feedback

2024-03-14 21:10 UTC, pernielsentikaer commented
@sasivarnan can you check this?

2024-03-30 03:48 UTC, bbatsche commented
@pernielsentikaer or @sasivarnan could either of you respond so this PR doesn’t get closed?

2024-03-30 05:10 UTC, sasivarnan commented
@bbatsche Thanks for adding these enhancements! They provide a significant improvement to the user experience.

Additionally, I learned about `/etc/pam.d/sudo_local` file and its benefits. 

@pernielsentikaer I've tested the changes introduced in this PR on my M2 MacBook Air running macOS Sonoma and everything seems to be functioning as expected.

2024-03-30 05:16 UTC, sasivarnan approved these changes

2024-04-03 19:32 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-04-03 19:33 UTC, merged