Support List-detail view
raycast/extensions pull request #1101
Opened 2022-03-14 05:49 UTC by viduycheung

## Description

Support List-detail view for better task info view experience.

## Screencast

![CleanShot 2022-03-14 at 13 49 08@2x](https://user-images.githubusercontent.com/53415256/158112686-c6e7f2a8-972e-46e3-b126-21023049fe9b.png)

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed in the `media` folder

2022-03-16 02:37 UTC, viduycheung commented
Add new command <Search Tasks>
![CleanShot 2022-03-16 at 10 36 15@2x](https://user-images.githubusercontent.com/53415256/158505578-db4dd634-a7ae-4939-ae11-86b0536c45d6.png)

2022-03-16 22:28 UTC, pernielsentikaer requested changes
Hi @viduycheung 👋 

Thanks for the update and for making the extension better and better 💪 I tested every command and couldn't find anything not working.

I have some feedback for you to address:

- In taskItem.tsx, `OpenAction` is deprecated and [Action.Open](https://developers.raycast.com/api-reference/user-interface/actions#action.open) should be used instead

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-17 03:03 UTC, viduycheung commented
@pernielsentikaer  fix it 🕺

2022-03-30 01:56 UTC, viduycheung commented
@pernielsentikaer Any update here 😿...

2022-03-30 06:11 UTC, pernielsentikaer requested changes
Hi @viduycheung 👋 

I'm so sorry, I'm not sure how I lost track of this one, I must have removed the notifications, sorry again! 😄

In osScript.ts you're using the deprecated `ToastStyle`, could you correct that to match the new version of [Toast](https://developers.raycast.com/api-reference/feedback/toast)

In the same file, lines 68-86 and lines 104-122 are 100% the same, could be a function instead to ensure it's actually doing the same and make it easier to maintain.

You have a lot `eslint-disable` going on, is most of them necessary? 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-30 06:11 UTC, pernielsentikaer commented on extensions/ticktick/src/components/searchFilter.tsx
> +    <List.Dropdown tooltip="Select Drink Type" storeValue={true} onChange={onFilterChange}>
Drink? 😄

2022-03-30 06:11 UTC, pernielsentikaer commented on extensions/ticktick/src/utils/sort.ts
> +function _defined(d1: any, d2: any) {
```suggestion
function _defined(d1: string, d2: string) {
```

2022-03-30 07:08 UTC, viduycheung commented
@pernielsentikaer 
all issues have been fixed

I remove unnecessary `eslint-disable` as much as I can, some `no-explicit-any` I think is necessary because the data struct has come from apple script.

2022-03-30 09:56 UTC, pernielsentikaer commented
Hi @viduycheung 👋 

Much netter, thanks! We have added support for [categories](https://developers.raycast.com/basics/prepare-an-extension-for-store#categories), [screenshots](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) and [changelog](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) – do you have time for adding this too before merging?

2022-03-31 01:59 UTC, viduycheung commented
@pernielsentikaer Done.

2022-03-31 05:32 UTC, pernielsentikaer approved these changes
Awesome @viduycheung 🔥 

I'm going to approve it, nice update 💪

2022-03-31 13:49 UTC, sxn commented
hey @viduycheung - nice work!

One question: it feels a bit weird that `Search Tasks` doesn't show anything unless I type something. Is it not possible to fetch all tasks without user input? In that case, I'd suggest adding an [EmptyView](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview) explaining this. 😺 

https://user-images.githubusercontent.com/1155589/161069526-5883f156-e881-4810-925d-8670fa9638f6.mov

2022-03-31 14:05 UTC, sxn commented on extensions/ticktick/CHANGELOG.md
> +## [Added] - 2022-3-31
```suggestion
## [Added] - 2022-03-31
```

2022-04-01 07:09 UTC, sxn commented
hi @viduycheung - was just a fluke :D re-running the pipeline fixed it. 🎉

2022-04-01 07:09 UTC, merged