Add ccf-what extension
raycast/extensions pull request #11029
Opened 2024-02-29 14:25 UTC by CrackedPoly

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-02-29 14:48 UTC, CrackedPoly commented
Researchers can look up a paper's publication in the China Computer Federation (CCF) recommended list, where they highlight some high-quality publications.

A similar extension would be [show-rank](https://github.com/hnshhslsh/show-rank) in Chrome.

2024-03-05 11:38 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Make `Search in DBLP` the primary action instead

- Add icon to `Toggle Details 

- What about using the default filtering built-in Raycast which searches title / subtitle and keywords array

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-03-05 11:38 UTC, pernielsentikaer commented on extensions/ccf-what/src/index.tsx
> +                <List.Item.Detail.Metadata.Label title="分类" text={category.chinese} />
At the moment, Raycast doesn't support localization and only supports US English.

2024-03-07 13:39 UTC, CrackedPoly commented
> Hi there, I have new updates regarding your comments and new features:
> 
> * Accepted your advice: `Search in DBLP`, `Toggle Details`, and built-in filtering
> * Flexible data source URL and update policy: set in the preference
> * Frequency sorted
> * Localization: set in the preference
>   Thanks in advance for your work and any feedback! 🔥

And some minor icon issues.

2024-03-11 08:15 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-03-11 08:33 UTC, merged