Add wol extension
raycast/extensions pull request #11039
Opened 2024-03-01 08:25 UTC by bxb100

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-03-06 08:20 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- The extension crashes if you're trying to wake a device that has some malformed data

![wol-1](https://github.com/raycast/extensions/assets/38033107/a97c3e73-8b66-4b10-a0d7-1c7186eec083)

- I entered some random data, it says online?

![wol 2024-03-06 at 09 07 32](https://github.com/raycast/extensions/assets/38033107/b1700438-88b7-4fae-a0b4-d6b28ed3f22c)

- Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-03-06 08:20 UTC, pernielsentikaer commented on extensions/wol/src/index.tsx
> +                title="Remove Wake Data"
```suggestion
                title="Remove Wake Data"
                style={Action.Style.Destructive}
                shortcut={Keyboard.Shortcut.Common.Remove}
```

2024-03-06 08:20 UTC, pernielsentikaer commented on extensions/wol/package.json
> +      "title": "Devices",
```suggestion
      "title": "List Devices",
```

2024-03-06 08:56 UTC, bxb100 commented
Thanks review
> The extension crashes if you're trying to wake a device that has some malformed data

fixed, form validate aligns with the logic in `wol.ts`

> I entered some random data, it says online?

it simply use `ping` to check the IP online status, so it works as expected

> Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

em, `capture-raycast-metadata` not working on my computer, and I check [doc](https://github.com/raycast/extensions/blob/fa7f40fce6143268c0fe497f7abce98bd8ecc23e/extensions/capture-raycast-metadata/README.md) yet don't know how to use it

<img width="774" alt="image" src="https://github.com/raycast/extensions/assets/20685961/24ea16ab-adb7-420a-bc34-4184fb3f2f1a">

2024-03-06 09:46 UTC, pernielsentikaer commented
Can you try to restart Raycast (and check in Activity monitor that only one instance is running 🙂)

2024-03-06 10:59 UTC, bxb100 commented
> Can you try to restart Raycast (and check in Activity monitor that only one instance is running 🙂)

same, doesn't work

2024-03-06 11:03 UTC, pernielsentikaer commented
Do you mind running this in a terminal: `log stream --predicate "subsystem == 'com.raycast.macos'" --level debug --style compact >> ~/Desktop/ray.$(date +%Y%m%d_%H%M%S).log` and then try again - after trying just stop the log and send the output so I can see if anything pops up 🙂

Are you in our Slack community?

2024-03-07 06:19 UTC, pernielsentikaer approved these changes

2024-03-07 06:30 UTC, merged