feat(Timers): add Timers extension
raycast/extensions pull request #1114
Opened 2022-03-15 16:16 UTC by ThatNerdSquared

## Description

This PR adds a Timers extension to Raycast, allowing the user to start, stop, and save custom countdown timers.

## Screencast

See `metadata` for screenshots; it's hard to take an effective screencast that doesn't end up being excessively long due to the nature of the extension so I'd recommend a test drive by setting a 1-5 minute timer.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `media` folder

2022-03-15 16:23 UTC, ThatNerdSquared commented
Thoughts on the chime sound when the timer finishes are appreciated, I wanted a longer one but not sure where to procure it from.

2022-03-15 16:53 UTC, ThatNerdSquared commented on extensions/timers/src/manageTimers.tsx
> +    <List isLoading={timers == [] || customTimers == {}}>
@eddyw it's the "`[] == []` returns `false`" error right? Not the most experienced with React so just wanted to make sure I'm not missing anything else.

2022-03-15 17:56 UTC, eddyw commented on extensions/timers/src/manageTimers.tsx
> +    <List isLoading={timers == [] || customTimers == {}}>
@ThatNerdSquared it's both `[] == [] // false` and `{} == {} // false`

2022-03-15 17:59 UTC, ThatNerdSquared commented on extensions/timers/src/manageTimers.tsx
> +    <List isLoading={timers == [] || customTimers == {}}>
@eddyw got it, habits from Python haha. Thanks for catching this!

2022-03-16 22:09 UTC, pernielsentikaer requested changes
Hi @ThatNerdSquared 👋 

Thanks for an awesome extension 💪 

I have some suggestions and comments for you to address, feel free to catch me in [Slack](https://raycastcommunity.slack.com/) if you want to discuss.

- When using `Manage Timers` then the loader keeps spinning, both when no timers and with added timers.

- When using the “Save as Preset” feature, it's not remembering the settings, how is it supposed to work? Added “Belly” as preset, but can't find it as in your metadata image.

![66Ac7Nq4j3ooI22S](https://user-images.githubusercontent.com/38033107/158697684-4122d6ab-a4f1-46fa-b209-4949ab7082e8.png)
- Would be cool if you redraw the timers once each second, something like that is already added in the [Authy extension](https://github.com/raycast/extensions/tree/main/extensions/authy)

- In the rename screen, I think it would be better to set the current name as placeholder

![9prFkX6R6CPSuhQd](https://user-images.githubusercontent.com/38033107/158698325-01a780dc-4a6e-4e88-9cef-7757af4ecf9a.png)
- You could maybe get it to read the title of the timer when the time is over using `say` command

- Create a dropdown preference with some difference sounds, you should be able to put a 2-3 seconds optimized file in the assets folder and use the [environment variable](https://developers.raycast.com/api-reference/environment#environment) to get the path

Really looking forward to testing it out again 🥇 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-16 22:15 UTC, ThatNerdSquared commented
@pernielsentikaer "Save as Preset" should save to a `customTimers.json` in the folder defined by `environment.supportPath`, and there is code to create it if it doesn't exist... could you check the extension support folder on your side to see if the file gets created at all?

2022-03-16 22:30 UTC, pernielsentikaer commented
No problem at all @ThatNerdSquared, just summon me if you need help, have questions or just want to chat 😄

2022-04-07 14:15 UTC, sxn commented
hi @ThatNerdSquared 👋 

I wanted to check what the status on this PR is. Any idea when you'll have time to implement the requested changes? 😸

2022-04-07 17:20 UTC, ThatNerdSquared commented
Hi @sxn!

I'm working on some changes locally, but I've been pretty swamped with a few other projects on the side. I'm hoping to get the rest of the changes out by next Thursday, sorry for the delay! 😅

2022-04-12 15:26 UTC, sxn commented
alright, take your time! I'll close the PR until then - feel free to reopen it once things calm down a bit 🤗

2022-04-12 15:26 UTC, closed without merging