Add paper extension
raycast/extensions pull request #11179
Opened 2024-03-08 18:42 UTC by luctst

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-03-15 05:12 UTC, pernielsentikaer commented
Did you see [SnapJot](https://www.raycast.com/k41531/snap-jot) before creating this one, this is kinda in the same alley 🙂

2024-03-15 10:17 UTC, luctst commented
Hello, I didn't know about this one.

2024-03-15 13:54 UTC, pernielsentikaer commented
Could that work for you or should I check for other alternatives, I think we have a few like this extension in the store already 🙂

2024-03-15 17:00 UTC, luctst commented
I really appreciate how this extension lets me categorize my ideas, something I haven't found in other extensions. While I'm unable to contribute to other projects right now, I'd love to hear your thoughts. If it's not the right time to publish the extension, I completely understand. Just let me know if we can find alternatives, Thank you! 🙂

2024-03-18 09:31 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- It's possible to create a new category without name, this should be validated. You can use [useForm](https://developers.raycast.com/utilities/react-hooks/useform) for that.

- You can add/edit Paper and leave a blank name, that might not be intended

- Add a shortcut for `Create Paper`

- Instead of pushing you might want `pop()` instead 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-03-18 09:31 UTC, pernielsentikaer commented on extensions/paper/src/views/CreatePaper.tsx
> +        title="Name of your paper"
```suggestion
        title="Name of Your Paper"
```

2024-03-20 14:25 UTC, luctst commented
Hey 🙂

I've made the changes based on your last review. Just a small thing bugging me about the `pop()` API. So, the deal with `pop()` is that it takes you back to the original command without remounting the component. I need it because I'm using the `useGetConfig` hook in the components' `useEffect`. That's why I was rolling with the `push()` API, 'cause it adds the component to the history stack and remounts it. I know it's not the slickest way to handle this. In the next version, I'm thinking of creating commands instead of views, which seems like a smarter move. If you've got any better ideas, hit me up.

Appreciate your feedback.

2024-03-21 22:32 UTC, pernielsentikaer commented
You can see here why `push` is a bad thing

https://github.com/raycast/extensions/assets/38033107/3422f062-d128-4310-b76b-b070a36fcffb

You can achieve the same thing by having it redraw the list, which is done in many extensions, like [Remember the Date](https://www.raycast.com/pernielsentikaer/remember-the-date)

2024-03-22 14:38 UTC, luctst commented
Hi, 🙂
I have made the changes. I am now using the `popToRoot` API when submitting the form to reset the view. There should be no more problems

2024-03-26 12:11 UTC, mil3na commented
Hi @luctst ! Thanks for your contribution!

By using your extension, I was missing a "create paper" command. It took me some time to understand that it was "hidden" on the action panel. Do you mind adding a command for it?
Also, it would be nice to add a note on the README about how the notes are stored, for transparency purposes.
Other than that, I believe that the extension works as expected and would be a great addition :)

2024-03-28 09:59 UTC, luctst commented
Hi @mil3na,
I created a new "create-paper" command and added a brief note to the README file. It should be good. :)

2024-04-03 14:53 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-04-03 14:57 UTC, merged