add youdao translate
raycast/extensions pull request #112
Opened 2021-10-19 03:24 UTC by tiancheng92

## Description

This extension brings Youdao translate to raycast!

## Type of change

- New extension

## Screencast

![form](https://user-images.githubusercontent.com/42594679/137838597-7578eac2-4a25-4cef-9f52-e8ae23219ad3.jpg)
![result](https://user-images.githubusercontent.com/42594679/137838601-044e8157-305d-4f56-b99c-c7b6e71b7eda.jpg)
![select_form](https://user-images.githubusercontent.com/42594679/137838603-fbe73f51-eb6d-4aa5-9e6d-b2f7c5358160.jpg)

## Checklist

- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2021-10-20 20:18 UTC, PitNikola requested changes
Hey @tiancheng92. Thanks for your contribution!
Do you think you could provide me with API key so I could test your extension? Feel free to send me it via DM in Slack. I only need it for testing and won't share it anywhere else.

I also left some suggestions regarding the metadata. 
Please check this document with guidelines: https://developers.raycast.com/basics/prepare-an-extension-for-store, it should be helpful with improving your extension.

2021-10-20 20:18 UTC, PitNikola commented on extensions/youdao-translate/package.json
> +  "description": "Translate Content By Youdao API",
```suggestion
  "description": "Translate text using Youdao",
```

2021-10-20 20:18 UTC, PitNikola commented on extensions/youdao-translate/package.json
> +      "title": "Youdao Translate",
```suggestion
      "title": "Translate",
```

2021-10-20 20:18 UTC, PitNikola commented on extensions/youdao-translate/package.json
> +      "subtitle": "Translate Content",
```suggestion
      "subtitle": "Youdao",
```

2021-10-20 20:18 UTC, PitNikola commented on extensions/youdao-translate/package.json
> +      "description": "Translate Content By Youdao API",
```suggestion
      "description": "Translate text using Youdao",
```

2021-10-22 18:00 UTC, PitNikola requested changes
Hey @tiancheng92 . Thanks for providing me with API Key, it helped a lot. We'll need to fix few things to be aligned with guidelines:
- I'm afraid we'll need to remove non-english words from UI components. We don't yet support localization in Raycast and we want to keep this experience consistent across the app. The translation results can stay in non-english obviously :)
- Navigation title (floating tab) is not meant to be used for instructions, it's rather for the context. Here it should be just the command name which happens automatically.
![CleanShot 2021-10-22 at 18 27 53@2x](https://user-images.githubusercontent.com/4332171/138497992-4c167e15-8748-4c57-a2f8-c68863a9c8e4.png)

+ I left few improvement suggestions inline.

Thanks and sorry for long review!

2021-10-23 01:14 UTC, tiancheng92 commented on extensions/youdao-translate/src/youdao_translate.tsx
> +                     placeholder={select !== "" ? `you selected ${select}` : "please enter content"} />
When the user selects text, I want to display the selected text in the text area. If the user’s selected text is a misoperation, the user can overwrite the selected text with the entered text.

2021-10-25 18:13 UTC, PitNikola requested changes
@tiancheng92 thanks for addressing some of my comments. This one however hasn't been addressed yet:

> I'm afraid we'll need to remove non-english words from UI components. We don't yet support localization in Raycast and we want to keep this experience consistent across the app. The translation results can stay in non-english obviously :)

In order to merge it, we'll need to keep only english language in the UI (labels, dropdowns, etc).

Also I would suggest not reading the clipboard as it might be a bit confusing for a user (plus our placeholder doesn't look good with a lot of text).
![CleanShot 2021-10-25 at 19 11 16@2x](https://user-images.githubusercontent.com/4332171/138747970-da2921c5-086d-40f0-a4c9-d10ebda7a886.png)

Also when first time user will copy paste APP secret, they will see it in the placeholder which will be even more confusing. I would suggest just keeping static placeholder. People can always just copy paste.

Otherwise great work, we are almost there! 👍

2021-10-26 06:55 UTC, merged

2022-03-09 07:20 UTC, xeric commented
@PitNikola I created another youdao translation extension which focus on simplify the flow of user experience, it is using a list view and directly translate the selected word/clipboard content/input word with one step (no form view anymore), since I was heavily rely on a similar workflow in Alfred, I hope have a similar one in Raycast.
PR is here: https://github.com/raycast/extensions/pull/1004
@pernielsentikaer suggested we can collaborate and keep as one solution to end user, do you think it's possible?

2022-03-16 06:39 UTC, xeric commented
> It's best to ask @tiancheng92 if he would be up for changes. If not (which is okay considering different approaches), it's okay to submit yours as separate one.

@tiancheng92 any idea about @PitNikola suggestion?

2022-03-18 18:33 UTC, PitNikola commented
@xeric, since there is no response from @tiancheng92, I think you can go ahead with submitting separate extension with your own implementation. It's not ideal, but what can we do.

cc @pernielsentikaer