Add pangu-for-raycast extension
raycast/extensions pull request #11277
Opened 2024-03-14 01:16 UTC by beviz

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-03-19 07:50 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-03-19 07:50 UTC, pernielsentikaer commented on extensions/pangu-for-raycast/README.md
> +   Trigger the command using the shortcut or Raycast. The command will format the text you've selected on your screen, or format the content from your clipboard, then pastes it to the current cursor
At the moment, Raycast doesn't support localization and only supports US English.

2024-03-20 11:54 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-03-20 11:58 UTC, merged

2024-03-20 12:14 UTC, beviz commented
Thank you for your approvel!