`vim bro` a new and simple extension that helps you learn vim commands by letting you search them in raycast.
raycast/extensions pull request #1139
Opened 2022-03-18 18:01 UTC by ajaypremshankar

## Description

**Vim Bro** is a simple extension that can help learn vim quickly. 
It shows a list of vim commands and you can search commands without leaving the current window.

## Screencast

<img width="791" alt="Screenshot 2022-03-18 at 11 19 39 PM" src="https://user-images.githubusercontent.com/8684703/159058833-6bf08b91-97b4-42b3-9ad0-0d55b51dbe19.png">
<img width="805" alt="Screenshot 2022-03-18 at 11 20 04 PM" src="https://user-images.githubusercontent.com/8684703/159058852-8e552163-12ba-4754-a512-a7ef9736e13a.png">
<img width="794" alt="Screenshot 2022-03-18 at 11 20 35 PM" src="https://user-images.githubusercontent.com/8684703/159058862-8d97791e-c6fb-4c49-9d52-54e41b8bb334.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

2022-03-29 21:35 UTC, pernielsentikaer requested changes
Hi @ajaypremshankar 👋 

it seems like you have the `Trello` extension within your PR, could you please remove this, so it only contains `vim-bro`

We added support for [categories](https://developers.raycast.com/basics/prepare-an-extension-for-store#categories), [screenshots](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) and [changelog](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) – do you have time for adding this too

The images in the README should be placed in a folder called `media´ too

I'll do a bigger review when you have addressed above 💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-30 18:03 UTC, ajaypremshankar commented
> Hi @ajaypremshankar 👋
> 
> it seems like you have the `Trello` extension within your PR, could you please remove this, so it only contains `vim-bro`
> 
> We added support for [categories](https://developers.raycast.com/basics/prepare-an-extension-for-store#categories), [screenshots](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) and [changelog](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) – do you have time for adding this too
> 
> The images in the README should be placed in a folder called `media´ too
> 
> I'll do a bigger review when you have addressed above 💪
> 
> Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

Made changes @pernielsentikaer 

> The images in the README should be placed in a folder called `media´ too
Can I reuse files from `metadata` folder itself, instead of duplicating them in `media` folder?

2022-03-30 20:29 UTC, pernielsentikaer reviewed
Hi

2022-03-30 20:29 UTC, pernielsentikaer commented on extensions/vim-bro/src/index.tsx
> +          <List.Section title={key[0].toUpperCase() + key.slice(1)}>
```suggestion
          <List.Section key={key} title={key[0].toUpperCase() + key.slice(1)}>
```

2022-03-30 20:29 UTC, pernielsentikaer commented on extensions/vim-bro/src/index.tsx
> +              return <List.Item title={command.text[0].toUpperCase() + command.text.slice(1)} subtitle={command.kbd} />;
```suggestion
              return <List.Item key={command.kbd} title={command.text[0].toUpperCase() + command.text.slice(1)} subtitle={command.kbd} />;
```

2022-03-30 20:33 UTC, pernielsentikaer requested changes
Hi @ajaypremshankar 👋 

Thanks for the update 🔥 

- The metadata images are not in the right format as stated in the guidelines for [screenshots](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)

- The current images should be moved to `media` folder and referenced in the README 

- Each child in a list should have a unique “key” prop – as suggested, you're missing key attributes 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-31 17:17 UTC, ajaypremshankar commented
> Hi @ajaypremshankar 👋
> 
> Thanks for the update 🔥 It's much better 💪 💪 💪
> 
> I have some feedback for you to address 💯
> 
> * The metadata images are not in the right format as stated in the guidelines for [screenshots](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)
> * The current images should be moved to `media` folder and referenced in the README
> * Each child in a list should have a unique “key” prop – as suggested, you're missing key attributes 😄
> 
> Looking forward to testing it out again 😄
> 
> Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

@pernielsentikaer 
Done, done and done 😄

2022-03-31 17:45 UTC, ajaypremshankar commented on extensions/vim-bro/src/index.tsx
> +              return <List.Item title={command.text[0].toUpperCase() + command.text.slice(1)} subtitle={command.kbd} />;
Done

2022-04-07 19:37 UTC, merged