Add framer-motion extension
raycast/extensions pull request #11394
Opened 2024-03-19 22:02 UTC by madebyankur

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-03-22 09:31 UTC, samuelkraft requested changes
Hey @madebyankur, thanks for the contribution!

I've reviewed your extension and have some minor comments and suggestions:

* Please remove the metadata-1 image since it does not add much contextual value, metadata-2 shows the extension much better 🙂  

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-03-22 09:31 UTC, samuelkraft commented on extensions/framer-motion/src/utilities.tsx
> +                  <Action.CopyToClipboard title={item.title} content={item.content} />
It's unclear what this action does

```suggestion
                  <Action.CopyToClipboard title="Copy Utility" content={item.content} />
```

2024-03-22 09:31 UTC, samuelkraft commented on extensions/framer-motion/src/utilities.tsx
> +              subtitle={item.subtitle}
Adding the section title as a keyword for each item could be useful if you're not sure what the utility is named e.g. searching for just "3d" or "transition".

![Sam 2024-03-22 at 10  23 49@2x](https://github.com/raycast/extensions/assets/2223418/4128fbbd-cd55-4b49-b7a4-b6bc4547230d)



```suggestion
              subtitle={item.subtitle}
              keywords={[items.section]}
```

2024-03-22 09:31 UTC, samuelkraft commented on extensions/framer-motion/src/utilities.tsx
> +              subtitle={item.subtitle}
Adding the section title as a keyword for each item could be useful if you're not sure what the utility is named e.g. searching for just "3d" or "transition".

![Sam 2024-03-22 at 10  23 49@2x](https://github.com/raycast/extensions/assets/2223418/4128fbbd-cd55-4b49-b7a4-b6bc4547230d)



```suggestion
              subtitle={item.subtitle}
              keywords={[items.section]}
```

2024-03-22 09:31 UTC, samuelkraft commented on extensions/framer-motion/package.json
> +      "title": "Search Documentation",
```suggestion
      "title": "Search Documentation",
      "subtitle": "Framer Motion",
```

2024-03-22 09:31 UTC, samuelkraft commented on extensions/framer-motion/package.json
> +      "title": "Search Utilities",
```suggestion
      "title": "Search Utilities",
      "subtitle": "Framer Motion",
```

2024-03-22 17:18 UTC, madebyankur commented
@samuelkraft thanks for the review 🙌

I'll try to get these changes pushed in.

2024-03-26 09:19 UTC, samuelkraft approved these changes
Thanks for the changes @madebyankur, love the icon additions!

2024-03-26 10:45 UTC, merged