Pocket extension read state filters
raycast/extensions pull request #1141
Opened 2022-03-19 10:35 UTC by vimtor

## Description

Add read state filters to the Pocket extension so users can search for `Read`, `Archived` and `All` types of bookmarks.

## Screencast

https://user-images.githubusercontent.com/36263538/159117538-79877939-2741-4019-a66e-16fda4f9922f.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

2022-03-25 05:59 UTC, pernielsentikaer requested changes
Hi @vimtor 👋 

Thanks for the update, only left a few comments for you to address 🔥 

We released [1.31.0](https://developers.raycast.com/changelog#1.31.0-2022-03-23) with a lot of new awesome feature, be sure to check it out ⭐ 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-25 05:59 UTC, pernielsentikaer commented on extensions/pocket/changelog.md
>  ## Categories & Screenshots (2022-03-12)
```suggestion
## [Categories & Screenshots] - 2022-03-12
```

2022-03-25 05:59 UTC, pernielsentikaer commented on extensions/pocket/changelog.md
> +## Read State Filters (2022-03-19)
```suggestion
## [Read State Filters] - 2022-03-19
```

2022-03-25 05:59 UTC, pernielsentikaer commented on extensions/pocket/package.json
> +    "@raycast/api": "^1.30.3"
```suggestion
    "@raycast/api": "^1.31.0"
```
If you want the newest 😄

2022-04-03 06:16 UTC, pernielsentikaer commented
Hi @vimtor 👋 

Awesome update, thanks a lot!

Only one thing that I can imagine for now, that would make the UX more awesome 😄 

Would it be possible to add a [List.EmptyView](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview) and make a pocket logo in 64x64px — but it can wait for the next version 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-04-03 21:14 UTC, vimtor commented
Hey @pernielsentikaer I am not sure what you have in mind for the `List.EmptyView` do you want one different for each read state filter? Or a generic one that just says _No bookmarks found_?

In the meantime I did a few things:
- Added an `Open Latest Bookmark` command
- Renamed `Random Bookmark` to `Open Random Bookmark`
- Made `Open Random Bookmark` truly open a random bookmark
- Added a new command `Create Bookmark from Clipboard`

I was also considering adding a `Create Bookmark from Selection` but I wanted to ask you how to do it first. I've guess I could copy the current selection and then proceed with the `Create Bookmark from Clipboard` behaviour?

2022-04-04 05:54 UTC, pernielsentikaer commented
Hi @vimtor 👋 

Thanks for the update, tested it, and it works quite nice! 

I was just thinking on a generic with an awesome pocket logo 😄 

I think that's a good idea to add, is it something you will add in this version?

2022-04-05 13:38 UTC, merged