Add GitHub Gist extension
raycast/extensions pull request #1149
Opened 2022-03-20 12:26 UTC by koinzhang

## Description

**Getting Started**

This extension brings GitHub Gist support to Raycast through the personal access tokens. To get started, first:

- Login to your  GitHub instance (Eg. [https://github.com/](https://github.com))
- Click on your avatar image in the right upper corner
- From the dropdown menu, click on `Settings`
- On the left-hand side, click on `Developer settings`.
- On the left-hand side, click on `Personal access tokens`.
- On this page, we'll create a new access token. Click on `Generate new token` in the upper-right.
- Leave a `note` for your token (Eg. `Raycast`). This will help you identify it in the future.
- You'll need to check the following boxes to ensure this extension can perform properly:
  - `repo`
  - `gist`
  - `user`
- Click `Generate token` and save this value somewhere. **You'll only be able to see this once**.

> Future updates to this extension will offer more functionality that may require additional scopes be defined in this token.

**Gist Tag**

- My Gists
- My Starred
- All Public Gists

**Actions**

- Copy to Clipboard
- Paste to Active App
- Copy Gist Link
- Open in Browser
- Star Gist *(Only in MyGists)*
- Delete Gist *(Only in MyGists)*
- Unstar Gist *(Only in My Starred)*
- Star Gist *(Only in All Public Gists)*
- Clone Gist

## Screencast

https://user-images.githubusercontent.com/36128970/159161962-70adae29-29c5-4026-82d0-19f23b8dcc22.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

2022-03-20 23:58 UTC, andreaselia commented
Great work! I feel like it would be nice to have a loading state when switching between My/Starred/All Gists.

As a feature suggestion, would it be worth adding the ability to create a Gist from whatever is copied from your clipboard? This would create a Gist from whatever is in your clipboard, and return the URL to said Gist to your clipboard.

2022-03-21 05:43 UTC, koinzhang commented
hi @andreaselia, Thank you for the review.
Changes in this commit :
1. Add Loading state for time-consuming network operations to improve user experience,
2. Add the command to create gist,
Please continue to review.

2022-04-07 19:56 UTC, fe9lix requested changes

2022-04-07 19:56 UTC, fe9lix commented on extensions/github-gist/package.json
> +              "title": "Paste to Active APP",
```suggestion
              "title": "Paste to Active App",
```

2022-04-07 19:56 UTC, fe9lix commented on extensions/github-gist/src/create-gist.tsx
> +                        title: "Open in browser",
```suggestion
                        title: "Open in Browser",
```

2022-04-07 19:56 UTC, fe9lix commented on extensions/github-gist/src/create-gist.tsx
> +                      message: "Click to copy gist link",
```suggestion
                      message: "Click to copy Gist link",
```

2022-04-07 19:58 UTC, fe9lix commented
@koinzhang Cheers, just fixed some typos...

2022-04-07 19:58 UTC, merged