Add "IATA Code Decoder" extension
raycast/extensions pull request #1153
Opened 2022-03-20 19:03 UTC by timrogers

## Description

This PR introduces a new Raycast extension, IATA Code Decoder, for decoding [IATA][1] codes for airports, airlines and aircraft.

The extension contains a command for airports, a command for airlines and a command for aircraft.

When you enter an IATA code, it'll tell you what that code refers to (for example, the airport code `SFO` refers to San Francisco International Airport). It includes typeahead functionality to give helpful suggestions - for example, when you enter `77` as an aircraft code, it'll show you all aircraft with codes beginning in `77` - the Boeing 77- family.

The data is sourced from a [bespoke API][2].

[1]: https://iata.org
[2]: https://github.com/timrogers/iata-code-decoder-api

## Screencast

_Coming soon_

## Checklist

- [] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed in the `metadata` folder

2022-03-27 21:27 UTC, pernielsentikaer requested changes
Hi @timrogers 👋 

Thanks for your contribution 🔥

I only left a single suggestion for you to address, looking forward to testing it out again 💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-27 21:27 UTC, pernielsentikaer commented on extensions/iata-code-decoder/CHANGELOG.md
> +## Hello 👋 - (2022-03-20)
```suggestion
## [Hello 👋] - 2022-03-20
```
We changed the format of the [changelog](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history)

2022-03-27 21:43 UTC, timrogers commented
> Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

Thanks ❤️ Good to go!

2022-03-28 11:06 UTC, pernielsentikaer approved these changes
Thanks, @timrogers 💪 

Approved! 😄

2022-03-28 12:22 UTC, pernielsentikaer commented
Hi @timrogers 👋 

How often do you expect the data to change?

I can see you have some GitHub actions taking care of the data as it is right now (but they seem to fail with error 401).

If data don't change very frequently, could it then be an idea to just make a new PR with the data instead?

2022-03-28 14:42 UTC, timrogers commented
👋 They don't change very frequently, but I'd rather not be responsible for keeping the Raycast repo up to date when they do. 

Can we stick with the API, and I'll fix the GitHub Actions? I just haven't configured the secret.

2022-03-28 16:34 UTC, merged