Update openai-translator extension
raycast/extensions pull request #11579
Opened 2024-03-31 19:42 UTC by dekura

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-04-04 01:20 UTC, douo commented
Looks good to me, I’ll wait for PR #11551  to be merged before I review it. Can you please sync up with this PR first?

2024-04-05 14:34 UTC, dekura commented
> Looks good to me, I’ll wait for PR #11551 to be merged before I review it. Can you please sync up with this PR first?

@douo 
Sure,  #11551 merged.

2024-04-09 12:56 UTC, pernielsentikaer commented
Awaiting #11551

2024-04-15 01:39 UTC, douo commented on extensions/openai-translator/assets/lang
Why changing the permissions?

2024-04-15 01:39 UTC, douo commented on extensions/openai-translator/package.json
> +    "ray": "^0.0.1",
Is this necessary?

2024-04-25 18:51 UTC, dekura commented
@douo What are your thoughts on the pull request now? Can we go ahead and merge it?

2024-04-26 05:01 UTC, douo requested changes
@dekura  Please do not touch the binary file, I'm fine with everything else.

2024-04-26 09:23 UTC, pernielsentikaer commented on extensions/openai-translator/package.json
> +    "ray": "^0.0.1",
No, that has nothing to do with Raycast

2024-04-26 09:24 UTC, pernielsentikaer commented
Could you look into what @dekura mentioned? I compiled the binaries again (I always do that); also, the changelog has a merge conflict 🙂

2024-04-27 00:29 UTC, dekura commented
> @dekura Please do not touch the binary file, I'm fine with everything else.

I did not actively modify the binary file. Could it be due to automatic compilation or building? 
I am not quite sure how to solve this issue. Could you please help me resolve it or provide me with some instructions?

2024-04-29 02:39 UTC, douo commented
Hi @dekura, please remove binary files from your commit and eliminate any unnecessary dependencies. Additionally, please resolve any conflicts with the mainstream branch.

2024-04-29 20:19 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-04-29 20:19 UTC, merged