Add literal extension
raycast/extensions pull request #11590
Opened 2024-04-01 21:58 UTC by OkanBilal

## Description

## Screencast

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-04-11 04:06 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Is there a way to move login to [preferences](https://developers.raycast.com/basics/prepare-an-extension-for-store#preferences) instead?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-04-11 04:06 UTC, pernielsentikaer commented on extensions/literal/package.json
> +      "title": "Search Books",
```suggestion
      "title": "Search Books",
      "subtitle": "Literal",
```

2024-04-23 08:01 UTC, pernielsentikaer commented
Automatically popping extension preferences is not something Raycast does, so I suggest removing that.

When you enter wrong credentials, I see two toasts shortly after each other. Could you look into only showing one on error?

2024-04-29 20:19 UTC, pernielsentikaer commented
Is this ready for another review?

2024-04-29 20:43 UTC, OkanBilal commented
Sure, you can review it now 👍

2024-04-30 03:59 UTC, pernielsentikaer requested changes
In the create review form you might want to use something like [useForm](https://developers.raycast.com/utilities/react-hooks/useform) for validating the input, it remembers states and handles validation pretty well 🙂

2024-05-10 07:24 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-05-10 07:29 UTC, merged