Add "Icons" extension
raycast/extensions pull request #1176
Opened 2022-03-23 06:42 UTC by Destiner

## Description

Adds a new extension to search, view, and copy icons from the [Iconify](https://iconify.design) icon sets.

## Screencast

https://user-images.githubusercontent.com/4247901/159638422-b172b8b3-76bf-4e43-98a0-9a3015b52eec.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

2022-03-23 11:01 UTC, FezVrasta commented on extensions/icons/CHANGELOG.md
> +Initial version
```suggestion
## [Add Icons] - 2022-03-24
- Initial version
```

https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history

2022-03-29 21:15 UTC, pernielsentikaer requested changes
Hi @Destiner 👋 

Thanks for another awesome contribution 🔥

I left some minor feedback for you to address, could you look into this?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-29 21:15 UTC, pernielsentikaer commented on extensions/icons/package.json
> +  "name": "icons",
I would rename the extension and the folder to `iconify` 
```suggestion
  "name": "iconify",
```

2022-03-29 21:15 UTC, pernielsentikaer commented on extensions/icons/package.json
> +  "title": "Icons",
```suggestion
  "title": "Iconify",
```

2022-03-29 21:15 UTC, pernielsentikaer commented on extensions/icons/package.json
> +      "title": "View Icons",
```suggestion
      "title": "Search Icons",
      "subtitle": "Iconify",
```

2022-03-29 21:15 UTC, pernielsentikaer commented on extensions/icons/package.json
> +      "title": "View Icons",
Could be View icons still though

2022-03-29 22:07 UTC, Destiner commented
Hey @pernielsentikaer, thanks for review! I updated the command title.

As for changing the extension title, I'd like to keep the current one if possible. While it's true that the extension uses Iconify, I think that it's not relevant for the end users. Most people are probably not aware of Iconify, but they will still find the extension useful.

2022-03-30 06:32 UTC, pernielsentikaer commented
Hi @Destiner 👋 

Thanks for your update, much appreciated 🙏 

The name `Icons` is just really not saying anything, according to the [Naming convention](https://developers.raycast.com/basics/prepare-an-extension-for-store#extensions-and-commands-naming) we have to make it a bit more specific, maybe something like `Search Iconify Icons` could be an idea?

2022-03-30 12:26 UTC, Destiner commented
@pernielsentikaer how about "Icon Search" or "Icon Sets"?

2022-03-30 20:45 UTC, pernielsentikaer commented
Hi @Destiner 👋 

In my opinion it's still too generic, we already have `CSS.GG` and `Copy GCP Icons`, so `Icon Search` and `Icon Sets` doesn't really say much about what and which service it uses – Could we settle on something like `Iconify Search` and then use the description a bit more?

Catch me in [Slack](https://raycastcommunity.slack.com/) or here if we need to discuss further 😄

2022-03-31 00:21 UTC, Destiner commented
@pernielsentikaer I changed the extension name to `Iconify — Search Icons`.

2022-03-31 05:34 UTC, pernielsentikaer approved these changes
Hi @Destiner 👋 

Thanks for taking your time, and sorry for pushing you for the name 😄 

Lets get it launched! 🚀

2022-03-31 15:09 UTC, merged

2022-04-05 18:02 UTC, apithy-isidro-martinez commented
could you add the [heroicons](https://heroicons.com/) icons sets from [TailwindCSS Team](https://tailwindcss.com/) ? thanks