Add earthworm extension
raycast/extensions pull request #11998
Opened 2024-04-25 13:22 UTC by baboon-king

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-04-30 13:33 UTC, pernielsentikaer commented on extensions/earthworm/package.json
> +  "description": "Quick play with Earthworm.",
Could be a bit more descriptive

2024-04-30 13:33 UTC, pernielsentikaer requested changes
Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-05-02 06:52 UTC, pernielsentikaer reviewed
Everything in this extension could simply be quicklinks; perhaps it makes more sense to just use quicklinks?

2024-05-03 01:47 UTC, baboon-king commented
> Everything in this extension could simply be quicklinks; perhaps it makes more sense to just use quicklinks?
1. 
Quicklinks is Good Idea.
But “Quicklink” can only be a single one.
It would be nice to create a collection of “Quicklink”. He should make more sense that.

2.
Then, in the near future I'm considering making the core gameplay of our site. Offered in this extension, at the moment, he really only has a few “QuickLinks”, so it's also possible to re-request a review when I'm done!

2024-05-03 07:28 UTC, pernielsentikaer commented
It would make sense to add more since it just opens links, also right now two of the commands opens the same link 🙂

2024-05-03 07:40 UTC, baboon-king commented
> It would make sense to add more since it just opens links, also right now two of the commands opens the same link 🙂

I'll add more since, for now let's set it up as a draft😋

2024-05-24 08:00 UTC, closed without merging