Airport Extension
raycast/extensions pull request #12
Opened 2021-10-13 18:51 UTC by siddharthsharma94

## Description

View[ Airport Apps](https://app.airport.community) directly from Raycast!

## Type of change

- New extension

## Screenshot

<img width="1440" alt="Airport-Raycast" src="https://user-images.githubusercontent.com/11656847/137198548-fc772dfb-abf3-4eaa-b619-3b9063b52cd7.png">

## Checklist

- [x] I read the [contribution guidelines](contributing.md)

2021-10-14 19:02 UTC, thomaspaulmann requested changes
Hey @siddharthsharma94,

this is a pretty cool extension! I love bringing Airport and Raycast together. I left a few minor things to tidy up the extension inline. Then it should be good to go. Can't wait to see folks discovering beta software from other developers right in Raycast!!!

2021-10-14 19:02 UTC, thomaspaulmann commented on extensions/airport/package.json
> +      "description": "Airport is the best place to discover new TestFlight apps from developers.",
Discover apps from developers on Airport.

2021-10-14 19:02 UTC, thomaspaulmann commented on extensions/airport/src/index.tsx
> +      showToast(ToastStyle.Success, "Fetched Latest Apps");
It's enough to show the loading indicator in the searchbar. You don't need to add the toast. More info [here](https://developers.raycast.com/information/best-practices#show-loading-indicator).

```suggestion
      const appsResponse = await fetchApps();
      setState((oldState) => ({
        ...oldState,
        all: appsResponse?.apps.all.filter(
          (app) =>
            !appsResponse?.apps.popular.includes(app.id) &&
            !appsResponse?.apps.featured.includes(app.id) &&
            !appsResponse?.apps.new.includes(app.id) &&
            !appsResponse?.apps.upcoming.includes(app.id) &&
            !appsResponse?.apps.waitlist.includes(app.id)
        ),
        popular: appsResponse?.apps.all.filter((app) => appsResponse?.apps.popular.includes(app.id)),
        featured: appsResponse?.apps.all.filter((app) => appsResponse?.apps.featured.includes(app.id)),
        new: appsResponse?.apps.all.filter(
          (app) =>
            !appsResponse?.apps.popular.includes(app.id) &&
            !appsResponse?.apps.featured.includes(app.id) &&
            appsResponse?.apps.new.includes(app.id) &&
            !appsResponse?.apps.upcoming.includes(app.id) &&
            !appsResponse?.apps.waitlist.includes(app.id)
        ),
        upcoming: appsResponse?.apps.all.filter(
          (app) =>
            !appsResponse?.apps.popular.includes(app.id) &&
            !appsResponse?.apps.featured.includes(app.id) &&
            !appsResponse?.apps.new.includes(app.id) &&
            appsResponse?.apps.upcoming.includes(app.id) &&
            !appsResponse?.apps.waitlist.includes(app.id)
        ),
        waitlist: appsResponse?.apps.all.filter(
          (app) =>
            !appsResponse?.apps.popular.includes(app.id) &&
            !appsResponse?.apps.featured.includes(app.id) &&
            !appsResponse?.apps.new.includes(app.id) &&
            !appsResponse?.apps.upcoming.includes(app.id) &&
            appsResponse?.apps.waitlist.includes(app.id)
        ),
      }));
```

2021-10-15 13:10 UTC, siddharthsharma94 commented
Just added your requested changes! @thomaspaulmann

2021-10-15 13:57 UTC, thomaspaulmann commented on extensions/airport/package.json
> +  "title": "Airport - Discover TestFlight Apps",
Really nice title!

2021-10-15 14:27 UTC, thomaspaulmann commented on extensions/airport/src/index.tsx
> +          <OpenInBrowserAction url={`https://app.airport.community/app/${app.id}?utm_source=raycast`} />
Do you really need this UTM parameter? We don't do this to respect the user's privacy. I know that this isn't user related but some folks don't like UTM either. Wanna remove it?

2021-10-15 14:28 UTC, thomaspaulmann approved these changes
Thanks for making the changes so quickly. The title looks very nice now. I left one comment about the UTM parameter. Do you want to remove it before I merge your extension?

2021-10-15 16:24 UTC, merged

2021-11-08 20:57 UTC, grzegorzkrukowski commented
Hey @siddharthsharma94 we just found out that icon in your extension has to be increased - we changed requirement to be 512 x 512 pixels.
Also in `assets` folder there is unused command-icon.png file.

Do you mind updating the icon to correct 512 x 512 size and removing unused one ?

Thanks in advance.

2021-11-08 20:59 UTC, siddharthsharma94 commented
Sounds good, I’ll make a PR to change the icon later today!
On Nov 8, 2021, 12:57 PM -0800, Grzegorz Krukowski ***@***.***>, wrote:
> Hey @siddharthsharma94 we just found out that icon in your extension has to be increased - we changed requirement to be 512 x 512 pixels.
> Also in assets folder there is unused command-icon.png file.
> Do you mind updating the icon to correct 512 x 512 size and removing unused one ?
> Thanks in advance.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-11-09 18:48 UTC, siddharthsharma94 commented
@grzegorzkrukowski just made a PR [here](https://github.com/raycast/extensions/pull/323)