Add AppCleaner Extension
raycast/extensions pull request #1209
Opened 2022-03-25 19:14 UTC by yuhixyz

## Description

Uninstall Application by AppCleaner.

## Screencast

<img width="873" alt="image" src="https://user-images.githubusercontent.com/50203860/160186274-cab44275-a585-4b51-b487-68e325bb3524.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

2022-03-26 00:35 UTC, anhthang commented
Raycast already have this in v1.31.0

https://www.raycast.com/changelog

2022-03-26 03:44 UTC, yuhixyz commented
> Raycast already have this in v1.31.0
> 
> https://www.raycast.com/changelog
I noticed that. But I found that not every app can be uninstalled in that way. For example,when I search kitty and open the actionpanel, there's no uninstall option.

2022-04-04 07:51 UTC, pernielsentikaer requested changes
Hi @yuhixyz 👋 

Thanks for your contribution 🔥

I have some feedback and suggestions for you to address:

- Could you add a [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) and [changelog](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history)

- You could add a check if AppCleaner is installed, something like it's [done here](https://github.com/raycast/extensions/tree/main/extensions/flow)

Looking forward to testing it out again 💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-04-04 07:51 UTC, pernielsentikaer commented on extensions/application-uninstaller/package.json
> +  "title": "Application Uninstaller",
```suggestion
  "title": "AppCleaner Uninstaller",
```

2022-04-04 07:51 UTC, pernielsentikaer commented on extensions/application-uninstaller/package.json
> +  "title": "Application Uninstaller",
Could be a better name, could you also rename the extension folder?

2022-04-04 07:51 UTC, pernielsentikaer commented on extensions/application-uninstaller/src/index.tsx
> +  ActionPanelItem,
```suggestion
  Action,
```
Deprecated, use Action instead

2022-04-04 07:51 UTC, pernielsentikaer commented on extensions/application-uninstaller/src/index.tsx
> +import { execaCommand } from "execa";
```suggestion
```
Declared but never used

2022-04-16 12:14 UTC, koinzhang commented
> > Raycast already have this in v1.31.0
> > [raycast.com/changelog](https://www.raycast.com/changelog)
> 
> I noticed that. But I found that not every app can be uninstalled in that way. For example,when I search kitty and open the actionpanel, there's no uninstall option.

Hi, @yuhixyz. This is not a bug, the uninstall option does not appear in the actionPanel when the application is running.
When the app is running, the app icon is marked with a small dot below it. Try uninstalling using Raycast after exiting kitty.

2022-04-17 07:47 UTC, yuhixyz commented
> 



> > > Raycast already have this in v1.31.0
> > > [raycast.com/changelog](https://www.raycast.com/changelog)
> > 
> > 
> > I noticed that. But I found that not every app can be uninstalled in that way. For example,when I search kitty and open the actionpanel, there's no uninstall option.
> 
> Hi, @yuhixyz. This is not a bug, the uninstall option does not appear in the actionPanel when the application is running. When the app is running, the app icon is marked with a small dot below it. Try uninstalling kitty by Raycast after exiting it.

@koinzhang Thanks a lot. I didn't realize that kitty is running. So this extension is no longer needed I think. I'll close this pr.

2022-04-17 07:48 UTC, closed without merging