Ext/GitHub smart notification
raycast/extensions pull request #12180
Opened 2024-05-05 08:47 UTC by shoppingjaws

## Description

Github Notification Viewer
- automatically read unnecessary notification
- automatically read notification based on configured rule

## Screencast
![github-smart-notification 2024-05-05 at 17 33 09](https://github.com/raycast/extensions/assets/25874783/dde0698d-c094-4f6f-9e36-74f6e8012768)

![github-smart-notification 2024-05-05 at 17 33 23](https://github.com/raycast/extensions/assets/25874783/96861010-3b8d-4f4e-a665-b34bfa17da94)

![github-smart-notification 2024-05-05 at 17 34 07](https://github.com/raycast/extensions/assets/25874783/e343abff-9a69-44a1-9ccb-4eb6fedc013a)

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-05-10 09:26 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- What about adding some defaults path and set gh path to `required: false` instead?

- Add so it's possible to add a new configuration directly from `List Configurations` 

- What about making adding a `no-view` command that will run every 10 minutes automatically

- Maybe include icons and color when creating a new notification, maybe soemthing like this

![Raycast10052024-0YBo8svv png@2x](https://github.com/raycast/extensions/assets/38033107/cf0cdbc2-20a1-4a11-b644-62a3ef8e9c41)



I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-05-10 09:26 UTC, pernielsentikaer commented on extensions/github-smart-notification/src/view/configurations.view.tsx
> +                title="Delete"
```suggestion
                title="Delete"
                style={Action.Style.Destructive}
                shortcut={Keyboard.Shortcut.Common.Remove}
```

2024-05-10 09:26 UTC, pernielsentikaer commented on extensions/github-smart-notification/src/view/configurations.view.tsx
> +import { Action, ActionPanel, Detail, List, environment } from "@raycast/api";
```suggestion
import { Action, ActionPanel, Detail, List, environment, Keyboard } from "@raycast/api";
```

2024-05-25 09:34 UTC, shoppingjaws commented
# changes

Thank you for reviewing. re-submit my PR.

- move form view from root command into configuration view.
- set default command path. 
- set notification view item icons sourced from repository icon

2024-05-31 04:09 UTC, shoppingjaws commented
@pernielsentikaer  Updated 👍

2024-06-04 08:06 UTC, pernielsentikaer requested changes
Hi 👋 

I have now tested your extension, and I have some feedback ready for you:

- If you're opening the menubar command as the first thing, then there is no data since it doesn't fetch items, maybe it should do that?

![Raycast04062024-ZBKQpQxe png@2x](https://github.com/raycast/extensions/assets/38033107/45843394-54fd-4432-aa23-6311981c2c25)

- It's still possible to add a new configuration without a description

![github-smart-notification 2024-06-04 at 10 04 33](https://github.com/raycast/extensions/assets/38033107/15b2ffca-fde1-4f43-968a-9e957bc56971)

![github-smart-notification 2024-06-04 at 10 05 11](https://github.com/raycast/extensions/assets/38033107/6d8b9e00-5e08-4b51-99c8-76d3481774e0)

- add a [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert#confirmalert) when you delete the notification and add a missing icon `Icon.Trash` maybe?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-06-04 08:06 UTC, pernielsentikaer commented on extensions/github-smart-notification/package.json
> +    }
```suggestion
    {
      "name": "ghCommandPath",
      "title": "gh Command Binary PATH",
      "description": "Installed Path of gh command",
      "type": "textfield",
      "required": false,
      "default": "/opt/homebrew/bin/gh"
    },
    {
      "name": "autoReadMergedPr",
      "title": "Options",
      "description": "if true, merged PR will be read",
      "default": true,
      "type": "checkbox",
      "label": "Automatically mark merged PRs as read",
      "required": true
    }
```

2024-06-04 08:06 UTC, pernielsentikaer commented on extensions/github-smart-notification/src/view/notifications.view.tsx
> +                title="Mark As Read"
```suggestion
                title="Mark as Read"
```

2024-06-22 13:13 UTC, shoppingjaws commented
@pernielsentikaer Hi, I updated.

- add alert and trash icon to the configuration view on delete.

> If you're opening the menubar command as the first thing, then there is no data since it doesn't fetch items, maybe it should do that?
- You mean adding the loading logic, right?

2024-06-24 11:00 UTC, pernielsentikaer commented
Yes, that would make sense since the command and menubar uses the same cache

2024-06-29 08:56 UTC, shoppingjaws commented
@pernielsentikaer Ive already added loading logic to the menubar.tsx.
when isLoading is set true when the state is undefined. The menubar becomes invisible while the fetching task is in progress. Isn’t this enough?

2024-07-04 01:25 UTC, shoppingjaws commented
@pernielsentikaer yes, please 👍

2024-07-04 12:43 UTC, mil3na commented
Hi! Per is on vacation, so I will be reviewing your extension.
I wonder if this wouldn't be a better addition to the Github extension instead. https://www.raycast.com/raycast/github/commands 
There, we already have a notification command, you could add a filter as a preference.
What do you think?

2024-07-13 07:27 UTC, shoppingjaws commented
@pernielsentikaer @mil3na That's good idea. Is it too late to suggest that?
I'd love to port this feature to a Github extension, but why not wait until you've released it?

2024-07-15 12:21 UTC, mil3na commented
The Github extension is opensource and open for contributions. Feel free to add this functionality there! I will close this PR for now :)

2024-07-15 12:21 UTC, closed without merging

2024-07-16 00:36 UTC, shoppingjaws commented
If so, I wish you had suggested it a little earlier.