feat(msteams): added call option
raycast/extensions pull request #12242
Opened 2024-05-08 08:33 UTC by crisboarna

## Description

Added ability to directly call a user from a found chat with audio / video.

## Screencast
![2024-05-08at08 26 16-ezgif com-resize](https://github.com/raycast/extensions/assets/12763781/0ee3ab45-29e6-4921-8996-5955cbec1806)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-05-08 10:11 UTC, pernielsentikaer commented on extensions/microsoft-teams/src/actions/callAction.ts
> +import { runAppleScript } from "run-applescript";
Could we use runAppleScript from `@raycast/utils` instead?

2024-05-08 10:11 UTC, pernielsentikaer requested changes
Thanks for your enhancement @crisboarna 🔥 

@svenwiegand could you also check this?

2024-05-08 10:52 UTC, crisboarna commented
Hi @pernielsentikaer ,

I have updated it to use the `@raycast\utils` provided utility instead.

2024-05-10 07:57 UTC, pernielsentikaer commented
I wrote @svenwiegand a message so we can get this merged 🙂

2024-05-10 08:05 UTC, crisboarna commented
Thank you @pernielsentikaer ! 

I also tried contacting him regarding this PR.

In the meantime I also added Presence icon for `OneOnOne` chats in `Find Chat` (second screencast).

2024-05-10 15:55 UTC, svenwiegand commented
Thansk for your contribution @crisboarna. I'm currently testing the extension and I'm impressed, with the direct call feature and that it is working based on the Apple Script stuff. Awesome.

But I have issues with the chat status icons: In my test for several users only a progess circle does appear forever:
![CleanShot 2024-05-10 at 17 47 49](https://github.com/raycast/extensions/assets/2285034/4b35f09d-4c01-44bb-b2b1-750fca36233a)

2024-05-10 16:53 UTC, svenwiegand commented
Besides this, the code looks good to me @crisboarna. Just two tiny things:

- You should update the `CHANGELOG.md` regarding the people state.
- You should update the `README.md` regarding both new features.

2024-05-11 05:23 UTC, crisboarna commented
Hi @svenwiegand ,

I have not experienced the issue with the presence icon not updating, seems like the API call takes a long time to finish, so I added a timeout with default icon for that scenario.

- Updated `CHANGELOG.md`
- Updated `README.md`
- Added `usePromiseWithTimeout` hook to provide default icon in case of Presence API call taking too long.

Would this PR be ok to merge now ?

2024-05-11 11:28 UTC, svenwiegand commented
Thanks for the adjustments @crisboarna. From my point of view, this can be merged @pernielsentikaer.

2024-05-13 13:06 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-05-13 13:10 UTC, merged