Add stattrak extension
raycast/extensions pull request #12302
Opened 2024-05-12 16:41 UTC by rafaelvicio

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-05-17 07:34 UTC, pernielsentikaer requested changes
- `useFetch` should cache the result but it looks empty while entering the extension, could you look into that? You can maybe do most of the sorting in `parseResponse` in `useFetch`

- Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

2024-05-17 07:34 UTC, pernielsentikaer commented on extensions/stattrak/package.json
> +  "title": "stattrak",
```suggestion
  "title": "Stattrak",
```

2024-05-17 07:34 UTC, pernielsentikaer commented on extensions/stattrak/package.json
> +      "subtitle": "Current esports tournaments",
```suggestion
      "title": "View Esports Tournaments",
      "subtitle": "Stattrak",
```

2024-05-17 07:34 UTC, pernielsentikaer commented on extensions/stattrak/package.json
> +      "subtitle": "Upcoming esports matches",
```suggestion
      "title": "View Esports Matches",
      "subtitle": "Stattrak",
```

2024-05-21 06:22 UTC, pernielsentikaer commented
Is this ready for another review?

2024-05-21 14:14 UTC, rafaelvicio commented
> r

Not yet, I'm working on some improvements.

2024-05-21 14:15 UTC, rafaelvicio commented
> Is this ready for another review?

Not yet, I'm working on some improvements.

2024-05-22 08:10 UTC, pernielsentikaer commented
Converting into a draft then 🙂

2024-06-12 08:51 UTC, closed without merging