Add nhk-program-search extension
raycast/extensions pull request #12300
Opened 2024-05-12 14:11 UTC by sitogi

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-05-17 07:28 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-05-17 07:28 UTC, pernielsentikaer commented on extensions/nhk-program-search/CHANGELOG.md
> +# nhk-program-search Changelog
```suggestion
# NHK Program Search Changelog
```

2024-05-17 07:28 UTC, pernielsentikaer commented on extensions/nhk-program-search/README.md
> +# nhk-program-search
```suggestion
# NHK Program Search
```

2024-05-17 07:28 UTC, pernielsentikaer commented on extensions/nhk-program-search/README.md
> +情報提供:ＮＨＫ
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension. If the locale might affect functionality (e.g. using the correct unit of measurement), please use the preferences API.

2024-05-17 07:28 UTC, pernielsentikaer commented on extensions/nhk-program-search/package.json
> +          "value": "470"
Can we make title here english too

2024-05-17 13:05 UTC, sitogi commented on extensions/nhk-program-search/README.md
> +情報提供:ＮＨＫ
https://api-portal.nhk.or.jp/service-guide

At the bottom of the terms of use for this API, there is a note that says "Display the string '情報提供:ＮＨＫ'", so would it be okay to also keep the Japanese string just to be safe?

<img width="798" alt="image" src="https://github.com/raycast/extensions/assets/20895397/cda0ce1c-72c2-40e5-84ef-be26a075aaa5">

The English translation of the above image.

> "About Displaying Credits"
> Please ensure to display the following credit on sites and applications utilizing this service.
> When used as standalone data: 「情報提供:ＮＨＫ」

2024-05-17 13:13 UTC, sitogi commented
@pernielsentikaer 
Thank you for your review!
We have addressed your feedback. Please check again!

2024-05-21 07:30 UTC, pernielsentikaer requested changes
Can we do the same for items in the dropdown?
Raycast is not ready for localization

![nhk-program-search 2024-05-21 at 09 29 31](https://github.com/raycast/extensions/assets/38033107/a701bf25-347c-4e86-8ac3-96ca431e6d7d)

2024-05-21 07:52 UTC, sitogi commented
@pernielsentikaer 

> Can we do the same for items in the dropdown?

OK. I will handle it.

I will also change the genre selection to English.

<img width="400" alt="image" src="https://github.com/raycast/extensions/assets/20895397/9093e500-c7a8-43ad-ba0b-eab8342dbb16">

However, please note that this API retrieves the program listings from the Japanese public broadcaster, and it does not support English. As a result, all search results will be in Japanese.

Is this acceptable?

2024-05-21 13:32 UTC, sitogi commented
@pernielsentikaer
I have made corrections based on the feedback received. Please review them.

2024-05-22 08:11 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-05-22 08:17 UTC, merged