Update date-converter extension
raycast/extensions pull request #12456
Opened 2024-05-19 13:01 UTC by vineus

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-05-19 15:16 UTC, asportnoy requested changes
Could the relative info be part of the item description maybe? Also does it need to be that detailed?

2024-05-19 21:53 UTC, vineus commented
@asportnoy 
> Could the relative info be part of the item description maybe? Also does it need to be that detailed?

Better?

![date-converter 2024-05-19 at 22 50 48](https://github.com/raycast/extensions/assets/467126/02c1f2b6-6c58-4e86-8889-81fda662c268)

2024-05-20 03:14 UTC, asportnoy commented
- I think the relative time is still too detailed. "9 minutes" should be plenty detailed for this, I think the seconds is overkill
- Can you add a prefix or suffix like "in/ago"? So "9 minutes ago"
- Separate the two parts with something like a hyphen and ditch the "relative:"

2024-05-20 03:15 UTC, asportnoy reviewed
Marking as reviewed again - see above

2024-05-20 18:20 UTC, vineus commented
Reverted the relative time work.

I'll use my fork, I guess my needs are very specific.

2024-05-21 07:27 UTC, pernielsentikaer commented
We can make it a preferences to show seconds or not, I like the idea 🙂

2024-05-23 18:52 UTC, vineus commented
Found some time to update.

Here is a shorter version:

<img width="745" alt="image" src="https://github.com/raycast/extensions/assets/467126/0444075e-0479-4335-a0b5-e2e1d3e2ea20">

<img width="749" alt="image" src="https://github.com/raycast/extensions/assets/467126/fb127dfd-f9ab-4dd9-9b20-511625760318">

<img width="753" alt="image" src="https://github.com/raycast/extensions/assets/467126/45be4148-e4db-448c-a7e9-2040d602c989">

2024-05-24 07:08 UTC, pernielsentikaer commented
@asportnoy could you check it once again

2024-05-24 14:28 UTC, asportnoy reviewed
Much better! One minor thing and then I think it's good to go.

2024-05-24 14:28 UTC, asportnoy commented on extensions/date-converter/src/index.tsx
> +          subtitle={label + "﹣" + timeAgo.format(date)}
```suggestion
          subtitle={`${label} - ${timeAgo.format(date)}`}
```

2024-05-24 16:06 UTC, asportnoy approved these changes
Thanks for those changes, looks good to me.

@pernielsentikaer ready to merge when you are.

2024-05-26 06:01 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-05-26 06:02 UTC, merged