Update git-commands extension
raycast/extensions pull request #12567
Opened 2024-05-24 23:22 UTC by manumorante

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-05-27 06:25 UTC, pernielsentikaer commented
Should we include `@raycast/utils` so we can use `useCachedPromise`, allowing us to use isLoading on the list to ensure everything is loaded before showing data 🙂

2024-06-01 02:48 UTC, manumorante commented
> Should we include `@raycast/utils` so we can use `useCachedPromise`, allowing us to use isLoading on the list to ensure everything is loaded before showing data 🙂

@pernielsentikaer It is done! Much better this way :)
Thank you

2024-06-04 09:16 UTC, pernielsentikaer requested changes
Hi 👋 

I have now tested your extension, and I have some feedback ready for you

- Maybe add a yellow star as accessory instead of an icon since it makes the list "jump" when it's an icon (and skip the accessory from favorites)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-06-04 09:16 UTC, pernielsentikaer commented on extensions/git-commands/src/command-detail.tsx
> +import { Action, ActionPanel, Color, Detail, Icon } from "@raycast/api";
```suggestion
import { Action, ActionPanel, Color, Detail, Icon, Keyboard } from "@raycast/api";
```

2024-06-04 09:16 UTC, pernielsentikaer commented on extensions/git-commands/src/command-detail.tsx
> +                shortcut={{ modifiers: ["cmd"], key: "s" }}
```suggestion
                shortcut={Keyboard.Shortcut.Common.Pin}
```
Maybe use the default shortcut instead?

2024-06-05 08:36 UTC, pernielsentikaer commented
Here is what I'm talking about: only showing an icon for favorites makes everything jump

![git-commands 2024-06-05 at 10 35 57](https://github.com/raycast/extensions/assets/38033107/12d34d1e-977c-456a-9bac-2e36edcba21b)

2024-06-05 09:23 UTC, manumorante commented
@pernielsentikaer yep :)
This is how it looks now:

![git-commands 2024-06-05 at 11 13 26](https://github.com/raycast/extensions/assets/3266486/090cc2bf-dffc-488d-b76d-fe74e1befb39)

You can disable the colors in the extension's preferences :)
I will upload the changes soon.

2024-06-10 13:53 UTC, pernielsentikaer commented
Is this ready for a review?

2024-06-10 15:19 UTC, manumorante commented
@pernielsentikaer yes! :)

2024-06-11 07:56 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-06-11 07:58 UTC, merged