Add Typeform Navigator.
raycast/extensions pull request #1261
Opened 2022-04-01 14:34 UTC by jdvr

## Description

New extension to browse your Typeform account and check forms stats.

## Screencast

https://www.youtube.com/watch?v=3yBbrCWXLeg

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

2022-04-19 06:18 UTC, pernielsentikaer requested changes
Hi @jdvr 👋 

Thanks for an awesome extension 🔥 

I have some feedback and suggestions for you to address 😄 

- If I just input a random token, it says "No Results" - It would be excellent with a [failure toast](https://developers.raycast.com/api-reference/feedback/toast#api-reference) telling about it

- If no lists are added to Typeform, it just dies. Could you handle this gracefully instead?

![CleanShot 2022-04-19 at 08 01 09@2x](https://user-images.githubusercontent.com/38033107/163937338-c2af616a-2ab4-4030-ad5a-f469a5bda38a.png)


- It would be AWESOME if you added the step "Workspaces" with our [dropdown component](https://developers.raycast.com/api-reference/user-interface/list#list.dropdown) 

![CleanShot 2022-04-19 at 08 03 08@2x](https://user-images.githubusercontent.com/38033107/163937365-90baa754-29d7-4603-8491-79cc5e7ff2b2.png)

Looking forward to testing this again! 🚀 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-04-19 06:18 UTC, pernielsentikaer commented on extensions/typeform-navigator/src/index.tsx
> +        title="Copy link"
```suggestion
        title="Copy Link"
```

2022-04-19 06:18 UTC, pernielsentikaer commented on extensions/typeform-navigator/src/index.tsx
> +      <Action.OpenInBrowser title="Check results" url={`${ADMIN_FORM_BASE_URL}${form.id}/results`} />
```suggestion
      <Action.OpenInBrowser title="Check Results" url={`${ADMIN_FORM_BASE_URL}${form.id}/results`} />
```

2022-04-19 06:18 UTC, pernielsentikaer commented on extensions/typeform-navigator/src/index.tsx
> +      <Action.OpenInBrowser title="Fill it" url={form._links.display} />
```suggestion
      <Action.OpenInBrowser title="Fill Form" url={form._links.display} />
```

2022-04-19 06:18 UTC, pernielsentikaer commented on extensions/typeform-navigator/package.json
> +      "subtitle": "Check your typeform workspaces and forms",
```suggestion
```

2022-04-19 06:18 UTC, pernielsentikaer commented on extensions/typeform-navigator/src/dto/index.ts
> +    href: "https://api.typeform.com/workspaces/8qUjTK";
Is this supposed to be like this?

2022-04-25 09:44 UTC, pernielsentikaer approved these changes
Hi @jdvr 👋 

Thanks for a wonderful extension! 🔥 

I tested it out and now it works as expected 💪

2022-04-25 09:45 UTC, merged

2022-04-25 09:45 UTC, jdvr commented
Thanks @pernielsentikaer