Add dolar-cripto-ar extension
raycast/extensions pull request #12651
Opened 2024-05-29 20:45 UTC by koaladlt

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-06-11 09:43 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Can the menubar be redrawn after switching to another currency?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-06-11 09:43 UTC, pernielsentikaer commented on extensions/dolar-cripto-ar/src/index.tsx
> +  const [selectedCurrency, setSelectedCurrency] = useState<string | undefined>();
You might want to use [useCachedState](https://developers.raycast.com/utilities/react-hooks/usecachedstate) from `@raycast/utils` instead (and set the default value directly

2024-06-11 09:43 UTC, pernielsentikaer commented on extensions/dolar-cripto-ar/src/index.tsx
> +  );
You can maybe use [useCachedPromise](https://developers.raycast.com/utilities/react-hooks/usecachedpromise) instead

2024-06-14 13:35 UTC, koaladlt commented
@pernielsentikaer Thanks for the feedback! I've made the changes that you asked for.

2024-06-17 07:24 UTC, pernielsentikaer requested changes
If you clear Local Storage and try to use the menubar, then it flickers with the text "blue" and the current, can you look into that?

![Raycast 2024-06-17 at 09 23 54](https://github.com/raycast/extensions/assets/38033107/c8a56092-3a69-45ca-b190-cd544b14ba9e)

https://github.com/raycast/extensions/assets/38033107/a9537537-0b2f-46ea-8d46-959ca32a437b

2024-06-19 16:00 UTC, koaladlt commented
> If you clear Local Storage and try to use the menubar, then it flickers with the text "blue" and the current, can you look into that?
> 
> ![Raycast 2024-06-17 at 09 23 54](https://private-user-images.githubusercontent.com/38033107/340215868-c8a56092-3a69-45ca-b190-cd544b14ba9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MTE2NDQsIm5iZiI6MTcxODgxMTM0NCwicGF0aCI6Ii8zODAzMzEwNy8zNDAyMTU4NjgtYzhhNTYwOTItM2E2OS00NWNhLWIxOTAtY2Q1NDRiMTRiYTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE1MzU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NmM2ZjFlNzMyMTE3NDM2OTlkODhmMjRkOTA5YTg3NDZlMzQyZDg2MDc1MjQwY2IyZTEyMzQ1NjdiOTQ4ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IHaWf0pScNjATudrferCrKF1tI0XNFg9OX3iARmj2wY)
> 
>  Raycast17062024-4CIhBKll.png.mp4

It should be working fine now! thanks for the feedback.

2024-07-01 14:31 UTC, mil3na commented
Hey @koaladlt ! Is this ready for another review?

2024-07-01 15:12 UTC, koaladlt commented
> Hey @koaladlt ! Is this ready for another review?

Yes it is :)

2024-07-06 02:30 UTC, koaladlt commented
> Thank you so much for your contribution, again! After testing it out, I was missing some kind of indication of which unit is "active". Have you considered adding a check mark (or any kind of mark) on the list next to the unit which is showing at the moment?

Thanks for your feedback! :) I added a check mark to the select unit so the user knows which one is selected.

2024-07-09 08:03 UTC, mil3na approved these changes
Awesome! Thanks again for your contribution!

2024-07-09 08:06 UTC, merged