Add network-drive extension
raycast/extensions pull request #12682
Opened 2024-05-31 02:02 UTC by SuoweiHu

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-06-11 09:56 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Is there a way to add a timeout, seems like if I enters a wrong domain it never stops loading

![network-drive 2024-06-11 at 11 54 50](https://github.com/raycast/extensions/assets/38033107/d1930089-33ec-4cd4-b9a1-9b62abbb4954)


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-06-11 09:56 UTC, pernielsentikaer commented on extensions/network-drive/src/utils-preference.tsx
> +}
```suggestion
```
This is already included in raycast-env.d.ts

2024-06-12 00:04 UTC, SuoweiHu commented
Thank you for the suggested changes @pernielsentikaer,
I'll implement those changes very soon !

2024-06-12 02:16 UTC, SuoweiHu commented
Feature's up ! ( ⸝⸝´꒳`⸝⸝)

https://github.com/raycast/extensions/assets/35317549/10953177-83e9-40b2-99b9-3727000377e7

2024-06-12 09:14 UTC, pernielsentikaer commented
Hi 👋

Could you check the update I made that I didn't break something 🙂

2024-06-12 09:48 UTC, SuoweiHu commented
That's **exactly** what I am looking for !!!
 
(p.s. I am not exactly familiar with the async programming, I spend like almost an hour trying to implement this but it keeps failing to work as I anticipated !  

Tons of thanks to you @pernielsentikaer

2024-06-12 09:58 UTC, pernielsentikaer commented
You should be able to pull my contributions with `npx @raycast/api@latest pull-contributions`

2024-06-12 10:01 UTC, pernielsentikaer approved these changes
Let's get the first version out to see how it goes 🙂

2024-06-12 10:03 UTC, merged