Update brand-fetch extension
raycast/extensions pull request #12791
Opened 2024-06-06 13:17 UTC by dilutedev

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-06-13 11:21 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- There is something wrong with your metadata images. Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

- Could you add an entry in the `CHANGELOG.md` file? Here's our guidelines about that: [Version History](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history).

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-07-18 23:33 UTC, LitoMore requested changes

2024-07-18 23:33 UTC, LitoMore commented on extensions/brand-fetch/CHANGELOG.md
> +- add multi stage preview for logos
```suggestion
## [New Features] - {PR_MERGE_DATE}

- Support free search API
- support input as both query or url
- Add multi stage preview for logos

## [Initial Version] - 2024-03-12
```

Latest changelog should be on the top.

2024-07-18 23:33 UTC, LitoMore commented on extensions/brand-fetch/README.md
> +- Brandfetch API Key.
```suggestion
A Brandfetch API Key.
```

Of course this requires Raycast. But this information is unnecessary since they already choose Raycast.

2024-07-18 23:33 UTC, LitoMore commented on extensions/brand-fetch/package.json
> +          "placeholder": "shopify",
```suggestion
          "placeholder": "Type a brand name",
```

2024-07-18 23:33 UTC, LitoMore commented on extensions/brand-fetch/src/index.tsx
> +      setError((err as Error).message);
Worth using a [List.EmptyView](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview) instead of throwing errors.

2024-07-18 23:33 UTC, LitoMore commented on extensions/brand-fetch/README.md
> +5. Create a new Pull Request.
```suggestion
See [Contribute to an Extension](https://developers.raycast.com/basics/contribute-to-an-extension).
```

2024-07-24 02:36 UTC, LitoMore approved these changes

2024-07-25 18:07 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-07-25 18:11 UTC, merged