Add retrac extension
raycast/extensions pull request #12962
Opened 2024-06-15 10:29 UTC by Skarf4U

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-06-19 21:15 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- You should use [useForm](https://developers.raycast.com/utilities/react-hooks/useform) for the `Add Item` since it offers error handling, validation and states

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-06-19 21:15 UTC, pernielsentikaer commented on extensions/retrac/src/search-items.tsx
> +            title={value.sku + " -- " + value.description}
Maybe be description to `subtitle` instead

2024-06-19 21:15 UTC, pernielsentikaer commented on extensions/retrac/src/utils/env.ts
> +export const projectSlug = getPreferenceValues<Preferences>().projectSlug;
```suggestion
import { getPreferenceValues } from "@raycast/api";

const preferences = getPreferenceValues<Preferences>();

export const apiKey = preferences.apiKey;
export const projectSlug = preferences.projectSlug;
```

2024-06-19 21:15 UTC, pernielsentikaer commented on extensions/retrac/src/search-items.tsx
> +                  title={"Delete Item"}
```suggestion
                  title={"Delete Item"}
                  style={Action.Style.Destructive}
```

2024-06-19 21:15 UTC, pernielsentikaer commented on extensions/retrac/src/utils/api.ts
> +export const useDeleteItem = () => {
Maybe add [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert#confirmalert) here

2024-07-02 09:41 UTC, mil3na commented
Hi! Is this ready for another review?

2024-07-02 12:55 UTC, Skarf4U commented
> Hi! Is this ready for another review?

Yes it is, already requested

2024-07-05 00:29 UTC, Skarf4U commented
Hey @mil3na ! Would it be possible to have another review? I've been waiting for over a week now :/

2024-07-05 08:05 UTC, mil3na commented
I'm reviewing it right now. Some comments:

- On your README, you mention https://app.retrac.co/settings/token to get your token. The correct URL is https://app.retrac.co/settings/tokens
- When entering a new item, I can see a small inline form, but the user is redirected to the bigger form anyway. The inline form is not necessary.
- It would be nice to have `unfocus` validation. For instance, when I enter non-numbers characters on Cost, it will only show me it is wrong when I submit. 
- Which currency is the cost on?
- When showing the details of an item, it would be nice to have an action to go to the retrac website for that item, or a way to edit it.

Please, take a look at my comments and tell me what you think. Cheers!

2024-07-05 23:19 UTC, Skarf4U commented
> I'm reviewing it right now. Some comments:
> 
> * On your README, you mention https://app.retrac.co/settings/token to get your token. The correct URL is https://app.retrac.co/settings/tokens
> * When entering a new item, I can see a small inline form, but the user is redirected to the bigger form anyway. The inline form is not necessary.
> * It would be nice to have `unfocus` validation. For instance, when I enter non-numbers characters on Cost, it will only show me it is wrong when I submit.
> * Which currency is the cost on?
> * When showing the details of an item, it would be nice to have an action to go to the retrac website for that item, or a way to edit it.
> 
> Please, take a look at my comments and tell me what you think. Cheers!

Hey! I went over your comments and fixed everything, one thing though is that currently there is no edit page for an item as items are only being displayed as **modlas**, however I added a link to the **app** URL, which will get the user closer to editing the desired item, hopefully in the future I could add an edit option too! 😄 
By the way, there was already `unfocus` validation. I believe it should be all good to go now!

2024-07-09 08:38 UTC, mil3na approved these changes
LGTM!

2024-07-09 08:42 UTC, merged