[Messages] Added a preference to close Raycast when sending a message
raycast/extensions pull request #12996
Opened 2024-06-17 16:28 UTC by ramsaysewell

## Description

## Screencast

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-06-17 16:29 UTC, ramsaysewell commented
This PR adds feature requested here:  #12986

2024-06-20 07:52 UTC, thomaslombart requested changes
Thanks for the PR. The preference feels confusing right now because it's not clear what it's doing. Why not having a checkbox labelled `Close main window`? Something like this:

```
        {
          "name": "shouldCloseMainWindow",
          "type": "checkbox",
          "label": "Close window immediately",
          "description": "When enabled, the Raycast window is closed immediately, allowing you to carry on with other work.",
          "default": true,
          "required": false
        }
```

Then, you can call `closeMainWindow` right before `showToast`.

2024-06-21 07:48 UTC, thomaslombart commented on extensions/messages/src/send-message.tsx
> +        }
You can actually call `closeMainWindow` here instead of calling `showHUD`, the toast will still be shown as a HUD.

2024-06-21 14:33 UTC, thomaslombart commented
Hey there! I'll be on vacation next week, so I'll review this PR the following week. @pernielsentikaer, feel free to handle this one if you have time.

2024-07-03 09:45 UTC, thomaslombart approved these changes

2024-07-03 09:46 UTC, merged