Add Find Out extension
raycast/extensions pull request #1300
Opened 2022-04-06 07:34 UTC by koinzhang

## Description

A casual game, find out the different icons in 30s.

**Commands**:

- **Find out**: Game entrance, use this command to enter the game

**Actions**:

- Start Game: Start the game, the game difficulty is divided into four levels
- History Score：View all-time high scores

## Screencast

![Screenshot1](https://user-images.githubusercontent.com/36128970/161920527-4404bb7b-158a-44ef-b585-747ec7e7e7f3.png)

![Screenshot2](https://user-images.githubusercontent.com/36128970/161920612-b078db8c-6c7d-45df-9bb0-70572f8bdadd.png)

![Screenshot3](https://user-images.githubusercontent.com/36128970/161920635-d7094150-08ae-400f-bfdb-75ba19cb1492.png)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

2022-04-24 17:07 UTC, fe9lix requested changes
Hey @koinzhang, sorry for the late review! I've left a couple of wording suggestions. Also, how about changing the Toast style to a regular success Toast that just appears when the user scores? (Animated Toasts are meant to be used more as short/temporary progress indicators...)

2022-04-24 17:07 UTC, fe9lix commented on extensions/hidden-icons/package.json
> +      "title": "Find out Hidden Icon",
```suggestion
      "title": "Find Hidden Icon",
```

2022-04-24 17:07 UTC, fe9lix commented on extensions/hidden-icons/package.json
> +  "description": "A casual game, find out the hidden icons in 30s.",
```suggestion
  "description": "A casual game where you need to find a hidden icon.",
```

2022-04-24 17:07 UTC, fe9lix commented on extensions/hidden-icons/package.json
> +      "description": "A casual game, find out the hidden icons in 30s.",
```suggestion
      "description": "A casual game where you need to find a hidden icon.",
```

2022-04-24 17:07 UTC, fe9lix commented on extensions/hidden-icons/src/find-out-hidden-icon.tsx
> +                title={"History Score"}
```suggestion
                title={"Score History"}
```

2022-04-24 17:07 UTC, fe9lix commented on extensions/hidden-icons/src/find-out-hidden-icon.tsx
> +                  title={isGaming ? "Find out " + targetIcon + ". Time left: " + leftTime + "s" : "Start Game"}
```suggestion
                  title={isGaming ? "Find " + targetIcon + ". Time left: " + leftTime + "s" : "Start Game"}
```

2022-04-24 17:07 UTC, fe9lix commented on extensions/hidden-icons/src/score-page.tsx
> +          <Detail.Metadata.Label title="Highest score in history" text={`---------------------`} />
```suggestion
          <Detail.Metadata.Label title="Highest Score in History" text={`---------------------`} />
```

2022-04-25 01:49 UTC, koinzhang commented
Hi @fe9lix. Thanks for your review.
Thank you very much for the suggestion, I have submitted the commit for update.

> Also, how about changing the Toast style to a regular success Toast that just appears when the user scores? (Animated Toasts are meant to be used more as short/temporary progress indicators...)

Update: The live scores are now displayed in the action title no longer using Toast.

Please continue to review.

2022-04-25 07:57 UTC, merged