Add Sunrise / Sunset Times Extension
raycast/extensions pull request #1304
Opened 2022-04-06 14:38 UTC by jeffreydyao

## Description

Check sunrise / sunset times for dates up to a month in the future at your current location.

**Commands:**
- Check Sunrise / Sunset Times: See sunrise / sunset times for dates up to a month in the future.

**Actions:**
- Copy Sunrise Time: Copy the currently selected date's sunrise time to the clipboard (i.e. _April 7 | Sunrise: 6:12:26 AM_)
- Copy Sunset Time: Copy the currently selected date's sunset time to the clipboard (i.e. _April 7 | Sunset: 5:44:45 PM_)

## Screencast
![sunrise-sunset-times-01](https://user-images.githubusercontent.com/33971845/162000129-e3785d8e-a014-46cd-8139-1d86029f9498.png)
![sunrise-sunset-times-02](https://user-images.githubusercontent.com/33971845/162000138-0ef9d04a-7d49-4933-86e0-debe6095c7f7.png)
![sunrise-sunset-times-03](https://user-images.githubusercontent.com/33971845/162000145-23661e4c-0ddd-4e96-9b72-952e49b040b1.png)

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-04-19 12:51 UTC, pernielsentikaer requested changes
Hi @jeffreydyao 👋 

Congratulations on your first extension. Thanks a lot! 🔥 

I have some feedback and suggestions for you to address:

- You should use the [IsLoading property for your list](https://developers.raycast.com/api-reference/user-interface/list#props) and first provide content when all data is present, the flicker doesn't do anything good.

- If it's not possible to find the position, then you should return an empty array instead.

- Could you move the CHANGELOG.md to the root folder

Other ideas for later:

- You could also add the possibility to add "custom locations" and combine it with a [dropdown component](https://developers.raycast.com/api-reference/user-interface/list#list.dropdown)

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-04-19 12:51 UTC, pernielsentikaer commented on extensions/sunrise-sunset-times/src/index.tsx
> +          }
```suggestion
            accessories={[
              { icon: "☀️", text: dayjs(sunrise[i]).format("h:mm A") },
              { icon: "🌜", text: dayjs(sunrise[i]).format("h:mm A") },
            ]}
```

2022-04-19 12:51 UTC, pernielsentikaer commented on extensions/sunrise-sunset-times/src/index.tsx
> +
Leftover?

2022-04-19 12:51 UTC, pernielsentikaer commented on extensions/sunrise-sunset-times/src/index.tsx
> +  const [timesLoading, setTimesLoading] = useState(true);
Seems like it's not in use.

2022-04-19 12:51 UTC, pernielsentikaer commented on extensions/sunrise-sunset-times/src/index.tsx
> +    setTimesLoading(false);
Is this being used?

2022-04-19 12:51 UTC, pernielsentikaer commented on extensions/sunrise-sunset-times/src/index.tsx
> +            <ActionPanel title="Copy times">
```suggestion
            <ActionPanel title="Copy Times">
```

2022-04-19 12:51 UTC, pernielsentikaer commented on extensions/sunrise-sunset-times/src/index.tsx
> +                content={dayjs(date).format("MMMM D") + " | Sunrise: " + dayjs(sunrise[i]).format("h:mm:ss A")}
```suggestion
                content={dayjs(date).format("MMMM D") + " | Sunrise: " + dayjs(sunrise[i]).format("h:mm A")}
```
Removed seconds

2022-04-19 12:51 UTC, pernielsentikaer commented on extensions/sunrise-sunset-times/src/index.tsx
> +                content={dayjs(date).format("MMMM D") + " | Sunset: " + dayjs(sunset[i]).format("h:mm:ss A")}
```suggestion
                content={dayjs(date).format("MMMM D") + " | Sunset: " + dayjs(sunset[i]).format("h:mm A")}
```

2022-04-19 12:51 UTC, pernielsentikaer commented on extensions/sunrise-sunset-times/package.json
> +      "subtitle": "Up to a month in the future",
```suggestion
      "title": "Sunrise & Sunset Times",
```

2022-04-19 12:51 UTC, pernielsentikaer commented on extensions/sunrise-sunset-times/package.json
> +  "title": "Sunrise / Sunset Times",
```suggestion
  "title": "Sunrise & Sunset Times",
```

2022-04-21 02:00 UTC, jeffreydyao commented
> Hi @jeffreydyao 👋
> 
> Congratulations on your first extension. Thanks a lot! 🔥
> 
> I have some feedback and suggestions for you to address:
> 
> * You should use the [IsLoading property for your list](https://developers.raycast.com/api-reference/user-interface/list#props) and first provide content when all data is present, the flicker doesn't do anything good.
> * If it's not possible to find the position, then you should return an empty array instead.
> * Could you move the CHANGELOG.md to the root folder
> 
> Other ideas for later:
> 
> * You could also add the possibility to add "custom locations" and combine it with a [dropdown component](https://developers.raycast.com/api-reference/user-interface/list#list.dropdown)
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

Hi, thanks for the feedback! I'll fix it up after my uni exams.

2022-04-22 10:14 UTC, pernielsentikaer commented
@jeffreydyao - That sounds like a good plan. I'll draft it until you're ready 😄

2022-06-20 06:06 UTC, pernielsentikaer commented
I'm closing this due to inactivity; feel free to open it again or comment in the thread when you're ready to continue working on it 🙂

You can also catch me in [Slack](https://www.raycast.com/community) if you want to discuss 😄

2022-06-20 06:06 UTC, closed without merging