Add mikrus extension
raycast/extensions pull request #13076
Opened 2024-06-20 17:36 UTC by tkowalski29

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-06-25 10:32 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Some actions in the ActionPanel is missing icons

- Do you mind sharing a screencast so I can see the flow since I don't have an account 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-06-25 10:32 UTC, pernielsentikaer commented on extensions/mikrus/package.json
> +      "title": "Default server id",
```suggestion
      "title": "Default Server ID",
```

2024-06-25 10:32 UTC, pernielsentikaer commented on extensions/mikrus/README.md
> +| `defaultServer`              | Default server id              | `string`    | `false`  | `empty`    | Your defalt id server
```suggestion
| `defaultServer`              | Default Server ID              | `string`    | `false`  | `empty`    | Your defalt id server                                                                                |
```

2024-06-25 10:32 UTC, pernielsentikaer commented on extensions/mikrus/src/server.tsx
> +        <List.EmptyView title="No servers" description="Reload servers" icon={Icon.Stars} />
```suggestion
        <List.EmptyView title="No Servers" description="Reload servers by pressing enter" icon={Icon.Stars} />
```

2024-07-02 11:55 UTC, tkowalski29 commented
@pernielsentikaer video: https://streamable.com/4e0x5c?src=player-page-share

2024-07-02 12:57 UTC, mil3na commented
Hi!

Thanks for the video. Some icons on the Action Panel are still missing, as Per noted. Also, I noticed that, when you edit the server, the key needs to be entered again. Is that the case? What if the user makes no change? Will the key be erased?

2024-07-02 16:31 UTC, tkowalski29 commented
Icons added, now everything should have icons.

Regarding the API key. The API is a bit unfortunate because it requires adding a separate key for each server. But you can download the server list with any key.

I solved it in such a way that we provide the key and default server (I added a condition that if the server matches the one that is default, the key does not need to be provided again). But additionally, it gives the possibility of uploading separate keys for separate servers.

Now there is no longer the effect that the key for the default server is not filled in.

2024-07-03 09:13 UTC, mil3na commented
My concern here is that, when you click on "change", on the Action Panel, it seems that the key value is empty and I wonder if the user presses enter without changing anything if the key gets erased or not. It's not clear from your video. It is not good UX if the user needs to enter it if there was no change.

2024-07-03 09:22 UTC, tkowalski29 commented
@mil3na

Once again, because I see confusion, there is currently no problem with the key and you don't need to enter it twice. Below is a new video.

https://streamable.com/rqaykx

2024-07-03 11:45 UTC, mil3na approved these changes
Got it! Thanks for the video.
You should be good to go!
Cheers!

2024-07-03 11:49 UTC, merged