[Github Gist] Optimise command
raycast/extensions pull request #13189
Opened 2024-06-27 08:30 UTC by koinzhang

## Description

- Simplify the code and improve performance
- Support saving gist as snippets

## Screencast

![github-gist-1](https://github.com/raycast/extensions/assets/36128970/fcb06a0f-ea62-4c0b-a470-e86a28c00850)

![github-gist-3](https://github.com/raycast/extensions/assets/36128970/5e300b47-9320-4a4c-993d-d6912b6283da)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-06-27 12:01 UTC, koinzhang commented
@pernielsentikaer There are still some changes to be submitted

2024-06-27 13:48 UTC, koinzhang commented
@pernielsentikaer Please keep it under review

2024-06-28 03:41 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-06-28 03:41 UTC, pernielsentikaer commented on extensions/github-gist/package.json
> +      "name": "personalAccessTokens",
Can we keep the old name?

2024-06-28 03:41 UTC, pernielsentikaer commented on extensions/github-gist/package.json
> +          "name": "rememberTag",
Can we keep the old name?

2024-06-28 07:40 UTC, koinzhang commented
@pernielsentikaer Please keep it under review

2024-07-03 08:08 UTC, mil3na commented
Hi! Is this ready for review? If not, can you please mark it as a draft? Cheers!

2024-07-03 08:11 UTC, koinzhang commented
@mil3na It's ready for review.

2024-07-03 11:37 UTC, mil3na approved these changes
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

LGTM!

2024-07-03 11:42 UTC, merged