Update yabai extension
raycast/extensions pull request #13333
Opened 2024-07-05 12:10 UTC by webdesus

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-07-06 10:47 UTC, webdesus commented
Fixed all the bugs and added a description to the pool requester

2024-07-09 12:36 UTC, mil3na requested changes
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

I tried your changes and it did not work for me. I got the following error. Can you please take a look at this? This error happens when clicking on the icon in my menubar, which is red.

![CleanShot 2024-07-09 at 14 30 55](https://github.com/raycast/extensions/assets/611002/997a8ac2-ae05-4fa7-b5e3-73d65d4e8827)

2024-07-09 13:00 UTC, webdesus commented
HI @mil3na and nice to meet you🙂

I believe the issue may be due to System Integrity Protection (SIP) being enabled on macOS, which can restrict some functionalities([more information about SIP and yabai](https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection)). I can include a note about this in the README and improve the error handling to  better message for users cases when SIP is active. 

But can you confirm that you didn’t turn it off? 🙂

2024-07-09 13:09 UTC, mil3na commented
No, I didn't turn it off. Will this new feature only work with SIP off? Would love to hear @krzysztoff1 and @rubentsirunyan opinions about this.

2024-07-13 10:26 UTC, webdesus commented
@mil3na  I finally found time to check with SIP turned off and found that after my latest fixes no errors occur. 🙂 This functionality works with SIP disabled as well. The only thing that doesn't work is the space focus. But this command doesn't work in the current version of the extension either. Because for its work it is necessary to turn off SIP 🙂 Like i [mention](https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection) before, some functions not working for yabai.  This is an article from the official documentation of Yabai.

2024-07-16 11:19 UTC, mil3na commented
Hi! Thanks for addressing my comments. I still have a few issues. Focus Space command doesn't work. Does it need to disable SIP?
I can see the spaces on my menubar, but I can't switch among them. Also, when switching spaces manually, I always see this window:
![CleanShot 2024-07-16 at 13 16 09](https://github.com/user-attachments/assets/5aaf458c-f257-43c6-a70f-8e51154aeffb)


The error when switching spaces:
```
Error: Command failed with exit code 1: env USER=milena /opt/homebrew/bin/yabai -m space --create
cannot create space due to an error with the scripting-addition.
    at makeError (/Users/milena/.config/raycast/extensions/yabai/create-space-and-focus.js:6599:13)
    at handlePromise (/Users/milena/.config/raycast/extensions/yabai/create-space-and-focus.js:7510:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runYabaiCommand (/Users/milena/.config/raycast/extensions/yabai/create-space-and-focus.js:7646:10)
    at async Object.Command (/Users/milena/.config/raycast/extensions/yabai/create-space-and-focus.js:7653:24)
```

2024-07-16 20:50 UTC, webdesus commented
@mil3na yes, switching spaces is a feature that can only be accessed if SIP is disabled. My patch does not include switching functionalities. I am using a mechanism that was added before my patch🙂

2024-07-17 08:24 UTC, mil3na approved these changes
Got it! Then, we should be good to go. @krzysztoff1, do you want to give one last look?

2024-07-17 09:00 UTC, krzysztoff1 commented
Hey, looks great! @webdesus Thanks a lot for your contribution!

2024-07-17 09:03 UTC, merged