Update qrcode-generator extension
raycast/extensions pull request #13361
Opened 2024-07-07 11:28 UTC by theOpheliart

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-07-07 11:53 UTC, darmiel requested changes

2024-07-07 11:53 UTC, darmiel commented on extensions/qrcode-generator/src/index.tsx
> +import { randomBytes } from "crypto";
this import isn't really used anywhere

2024-07-07 11:53 UTC, darmiel commented on extensions/qrcode-generator/src/index.tsx
> +var open = require('mac-open');
```suggestion
import open from "mac-open";
```

(can be remove if using `showInFinder`)

2024-07-07 11:53 UTC, darmiel commented on extensions/qrcode-generator/package.json
> +    "open": "^10.1.0",
This dependency isn't used

2024-07-07 11:53 UTC, darmiel commented on extensions/qrcode-generator/src/utils.tsx
> +  return `${homedir()}/Downloads/qrcode-${filename}.`+fileType;
```suggestion
  return `${homedir()}/Downloads/qrcode-${filename}.${fileType}`;
```

2024-07-07 11:53 UTC, darmiel commented on extensions/qrcode-generator/package.json
> +    "mac-open": "^0.1.3",
This dependency was last updated [10 years ago](https://github.com/weareinteractive/node-mac-open) and is unmaintained.

You can probably use Raycast's `showInFinder` utility function:
https://developers.raycast.com/api-reference/utilities#showinfinder

```diff
- open(path);
+ showInFinder(path);
```

2024-07-07 11:53 UTC, darmiel commented on extensions/qrcode-generator/src/index.tsx
> +  const primAction= getPreferenceValues().primaryAction;
please run formatter over the files

2024-07-07 11:53 UTC, darmiel commented on extensions/qrcode-generator/src/index.tsx
> +            open(path, {R: true});
```suggestion
            showInFinder(path);
```

2024-07-26 10:26 UTC, pernielsentikaer commented
What the status of this PR @theOpheliart

2024-08-16 11:03 UTC, closed without merging