Add zefix extension
raycast/extensions pull request #13360
Opened 2024-07-07 10:54 UTC by cimnine

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-07-10 13:08 UTC, mil3na requested changes
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

I left a few comments, could you please take a look at them? I'm mostly worried about the formatting of your files.

2024-07-10 15:38 UTC, cimnine commented on extensions/zefix/.editorconfig
> +root = true
Sure. IMHO, it would be great though if there was one for the repo.

2024-07-10 15:39 UTC, cimnine commented on extensions/zefix/CHANGELOG.md
> +# Zefix Changelog## [Initial Release] - 2024-07-07- Search for companies by name or UID- Switch language of results- Show additional details for a company- Copy the company's name, UID or VAT
Yeah, I thought Raycast wants it that way because that's the work of running `npx ray lint --fix`.

2024-07-10 15:39 UTC, cimnine commented on extensions/zefix/src/index.tsx
> +import { ActionPanel, List, Action } from "@raycast/api";import { useEffect, useState } from "react";import { type ZefixEntry, ZefixLanguage, ZefixLegalForm, zefixLegalForms, zefixSearch } from "./
Same, `npx ray lint --fix` did that.

2024-07-10 15:39 UTC, cimnine commented on extensions/zefix/src/zefix.ts
> +import fetch, { Response } from "node-fetch";export type ZefixEntry = {  cantonalExcerptWeb: string;  chid: string;  chidFormatted: string;  deleteDate: null;  ehraid: number;  legalFormId: n
Same, `npx ray lint --fix` did that.

2024-07-10 15:46 UTC, cimnine commented on extensions/zefix/CHANGELOG.md
> +# Zefix Changelog## [Initial Release] - 2024-07-07- Search for companies by name or UID- Switch language of results- Show additional details for a company- Copy the company's name, UID or VAT
Ah the linter had some weird interaction with the editorconfig.

2024-07-11 10:39 UTC, mil3na approved these changes
Thanks for your effort, LGTM!

2024-07-11 10:43 UTC, merged