Update snap-jot extension
raycast/extensions pull request #13460
Opened 2024-07-13 13:42 UTC by k41531

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-07-16 12:26 UTC, mil3na requested changes
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

Your `Search Text` command seems to not be working:
![CleanShot 2024-07-16 at 14 25 16](https://github.com/user-attachments/assets/a190117f-8ac6-4364-afa4-7f7d301969ba)

Can you please take a look?

2024-07-31 08:04 UTC, mil3na commented
Hi @k41531 ! Do you still want to work on this change?

2024-07-31 14:20 UTC, k41531 commented
@mil3na 
I couldn't check it because I was busy with work, so I will handle it this weekend.

2024-08-03 08:01 UTC, k41531 commented
@mil3na 
I fixed the issue that occurred when there were directories. Please review.

2024-08-06 13:07 UTC, mil3na commented
Hi! Thanks for fixing for folders, however I still get an error if the folder is a link for another folder. Can you take a look?

2024-08-09 00:53 UTC, k41531 commented
Thanks! I tested with symbolic links, and it works fine on my end.
By "folder is a link for another folder," do you mean a symbolic link? If not, could you share more details?

2024-08-21 08:22 UTC, mil3na commented
Yes, I do mean a symbolic link.

2024-08-25 08:39 UTC, k41531 commented
@mil3na 
I fixed it.

2024-08-26 12:03 UTC, mil3na commented
Just launching your extension and going to the "Search Text" command gives me this:
![CleanShot 2024-08-26 at 14 01 38](https://github.com/user-attachments/assets/75b4f692-ce65-45b3-98b1-09532a773c2b)

2024-08-26 12:23 UTC, k41531 commented
Seriously?
Sorry, I'll look into it further.
Thank you for providing the screenshot.

2024-09-07 07:15 UTC, k41531 commented
Sorry for bothering you again, but how about this time?

2024-09-09 13:43 UTC, pernielsentikaer commented
I think the search in `Search Text` is a bit slow, what a bout just letting Raycast do the filtering and add keywords=[] for every item?

2024-09-13 12:03 UTC, k41531 commented
Oh, is this the one?
https://developers.raycast.com/api-reference/user-interface/list
Thank you, I'll give it a try.

2024-09-16 10:33 UTC, pernielsentikaer commented
[Correct](https://developers.raycast.com/api-reference/user-interface/list#props-2) 🙂

2024-10-07 11:05 UTC, closed without merging