Add pipedream extension
raycast/extensions pull request #13544
Opened 2024-07-18 20:12 UTC by olekristianbe

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-07-19 13:32 UTC, mil3na requested changes
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

I had some issues using your extension and also left a few comments on the code. Please, take a look and tell me what you think:

- I guess I entered the wrong API Key on the first time and I got these errors. Do you mind making them more readable?
![CleanShot 2024-07-19 at 15 26 29](https://github.com/user-attachments/assets/6920209e-4fbf-4709-ab33-87746ac6af29)
![CleanShot 2024-07-19 at 15 26 53](https://github.com/user-attachments/assets/fa57bc42-8491-4ad4-93f5-cc0a1ca1ca45)

- On this screen, you could add an info tooltip, instead of put the information on the body. Same for input validation.
![CleanShot 2024-07-19 at 15 27 56](https://github.com/user-attachments/assets/66d7606f-d1ce-4216-bd78-30737b56c445)

- I tried to create a workflow, but I could not find the id you mention on the form. Should something be created on pipedream first?

2024-07-19 13:32 UTC, mil3na commented on extensions/pipedream/README.md
> +   - Go to [Pipedream Account Settings](https://pipedream.com/settings/account)
This link doesn't go to the Account section. Either fix it or tell the user in text.

2024-07-19 13:32 UTC, mil3na commented on extensions/pipedream/src/hooks/useUserInfo.ts
> +        console.log("Fetching user info...");
If not needed, please remove the console.logs

2024-07-20 19:33 UTC, olekristianbe commented
Hi,

Thank you fast reply! I will make the following improvements:

- Improve the error message.
- Include instructions on how to change the API Key for users who enter an incorrect one.
- Implement the use of info props in the "Add Workflow" command.
- Rename the "Add Workflow" command to "Connect Workflow" or a similar term to clarify its purpose of managing existing workflows in Pipedream.
- Update the incorrect link in the README.
- Remove the console log used for testing.

I appreciate your feedback and will implement these changes. I'll update you once completed. Have a great day!

2024-07-26 13:09 UTC, mil3na commented
Hi! 

Thanks for the updates. I still see a few issues:
- Changing the API key on the preferences still allow me to use the extension, even though the key is wrong.
- I still don't know how to create a workflow in order to test your extension.

2024-07-30 07:19 UTC, olekristianbe commented
Hi! Thanks for the feedback. I’ll make changes this weekend and get back to you. Have a great day!

2024-08-20 08:05 UTC, closed without merging