Update github extension
raycast/extensions pull request #13559
Opened 2024-07-19 16:12 UTC by vlasischar

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-07-19 16:16 UTC, LitoMore approved these changes

2024-07-19 20:23 UTC, jfkisafk requested changes

2024-07-19 20:23 UTC, jfkisafk commented on extensions/github/CHANGELOG.md
> +## [Fix copy commit URL action]
```suggestion
## [Fix copy commit URL action] - {PR_MERGE_DATE}
```

2024-07-19 20:34 UTC, jfkisafk approved these changes

2024-07-22 04:51 UTC, pernielsentikaer approved these changes

2024-07-22 04:53 UTC, merged