Add Meduza.io extension
raycast/extensions pull request #13749
Opened 2024-07-29 08:32 UTC by castletaste

## Description
Another one news extension. Based on rss

## Screencast

https://github.com/user-attachments/assets/7db64fc6-47dd-4a18-933b-97be1f560ef0

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-08-19 12:26 UTC, pernielsentikaer commented
I'm not sure why this one slipped my mind, very sorry about that 🫠

* I think I would use `useFetch` from `@raycast/utils` since it has built-in caching and use parseResponse inside that to format the data - do you want an example of that?

2024-12-20 09:12 UTC, castletaste commented
Hello!  
I fixed the "usefetch" issue and added a news summary feature

2025-01-02 06:43 UTC, pernielsentikaer requested changes
Thanks for the updates 🔥

Could you check the latest feedback 🙂

2025-01-02 06:43 UTC, pernielsentikaer commented on extensions/meduza/.cursorrules
> +You are an expert in JavaScript and the Raycast API. Your expertise includes TypeScript, Node.js, React, Expo, tRPC, Shadcn UI, Radix UI, and Tailwind CSS. Follow best practices in code style and str
Can we remove this? Doesn't look very useful 🙂

2025-01-02 06:43 UTC, pernielsentikaer commented on extensions/meduza/package.json
> +    },
```suggestion
      "name": "en",
      "title": "Show Latest News",
      "subtitle": "Meduza",
      "description": "Latest daily news",
      "mode": "view"
    },
```

Would be better to have only one command and change language inside the command, you can maybe use [list dropdown](https://developers.raycast.com/api-reference/user-interface/list#list.dropdown) for that

2025-01-02 06:43 UTC, pernielsentikaer commented on extensions/meduza/package.json
> +    }
Same here 🙂

2025-01-07 11:38 UTC, castletaste commented on extensions/meduza/.cursorrules
> +You are an expert in JavaScript and the Raycast API. Your expertise includes TypeScript, Node.js, React, Expo, tRPC, Shadcn UI, Radix UI, and Tailwind CSS. Follow best practices in code style and str
done ✅

2025-01-07 11:41 UTC, castletaste commented on extensions/meduza/package.json
> +    },
Yes, I also think that's more convenient

2025-01-07 11:41 UTC, castletaste commented on extensions/meduza/package.json
> +    }
done ✅

2025-01-07 12:38 UTC, castletaste commented
I accidentally reproduced this issue https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1734324533338899

2025-01-08 13:10 UTC, castletaste commented
Yes, I think it's ready for review 🙌

2025-01-09 04:09 UTC, merged