Add lego-bricks extension
raycast/extensions pull request #13846
Opened 2024-08-02 22:28 UTC by mSarheed

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-08-06 11:13 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-08-06 11:13 UTC, pernielsentikaer commented on extensions/lego-bricks/src/latest-sets.tsx
> +      searchBarPlaceholder={isLoading ? "Still loading..." : "Search for LEGO Sets..."}
Avoid using `searchBarPlaceholder` for loading text, `isLoading` is the place 🙂

2024-08-06 11:13 UTC, pernielsentikaer commented on extensions/lego-bricks/package.json
> +      "title": "Latest LEGO sets releases",
```suggestion
      "title": "Show Latest LEGO Sets Releases",
```

2024-08-06 11:13 UTC, pernielsentikaer commented on extensions/lego-bricks/package.json
> +      "title": "Colors",
```suggestion
      "title": "Show Colors",
```

2024-08-06 11:13 UTC, pernielsentikaer commented on extensions/lego-bricks/package.json
> +      "title": "Mini Figures",
```suggestion
      "title": "Show Mini Figures",
```

2024-08-06 11:13 UTC, pernielsentikaer commented on extensions/lego-bricks/package.json
> +      "title": "Sets",
```suggestion
      "title": "Show Sets",
```

2024-08-06 11:13 UTC, pernielsentikaer commented on extensions/lego-bricks/package.json
> +      "title": "Parts",
```suggestion
      "title": "Show Parts",
```

2024-08-08 07:36 UTC, mSarheed commented
@pernielsentikaer  Thanks for the comments. Suggested changes have been made, please review :)

2024-08-08 07:51 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-08-08 07:56 UTC, merged