Add raycast-notification extension
raycast/extensions pull request #13865
Opened 2024-08-04 20:12 UTC by maxnyby

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-08-04 20:18 UTC, maxnyby commented
I noticed that you write on https://manual.raycast.com/extensions:
> Your extension does more than use any of Raycast's native functionalities like Quicklinks, Snippets, Clipboard History, Calculator, etc;

So I completely understand if you reject this extension. Id run it as just a local extension, but
1. Deeplinks don't seem to work with local extensions, and
2. I've seen other online on the quest for this functionality, because your HUD design is so much nicer than the default "osascript display notification"-one, but the functionality doesn't seem to be built in to raycast at this moment.

So I hope you'll approve this extension, or at least point me in the right direction to get deeplinks working on a local extension.

2024-08-07 05:15 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Your extension is missing an icon. You can create one using our generator here: https://ray.so/icon

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-08-07 05:15 UTC, pernielsentikaer commented on extensions/raycast-notification/package.json
> +  "description": "This extension makes it easy to display raycast notifications via a quicklink, making the nice raycast interface usable to other applications or scripts",
```suggestion
  "description": "This extension makes it easy to display Raycast notifications via a quicklink, making the Raycast interface accessible to other applications or scripts",
```

2024-08-09 05:13 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-08-09 05:17 UTC, merged