Update github extension
raycast/extensions pull request #13918
Opened 2024-08-07 16:44 UTC by xilopaint

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-08-07 16:54 UTC, LitoMore requested changes

2024-08-07 16:54 UTC, LitoMore commented on extensions/github/assets/vscode.svg
The icon size is not consistent with others. You can use this one instead:

<img height="24" src="https://cdn.jsdelivr.net/npm/simple-icons@12/icons/visualstudiocode.svg" />

https://cdn.jsdelivr.net/npm/simple-icons@12/icons/visualstudiocode.svg

2024-08-07 17:05 UTC, xilopaint commented on extensions/github/assets/vscode.svg
Done.

2024-08-07 18:16 UTC, LitoMore approved these changes

2024-08-07 18:21 UTC, LitoMore commented on extensions/github/assets/sourcegraph.svg
Ah, also this one. We use the monochrome version of the icon:

<img height="24" src="https://cdn.jsdelivr.net/npm/simple-icons@9/icons/sourcegraph.svg" />

https://cdn.jsdelivr.net/npm/simple-icons@9/icons/sourcegraph.svg

This is the version that was previously on Simple Icons. It has the same image size and quality as the other icons.

2024-08-07 18:27 UTC, xilopaint commented on extensions/github/assets/sourcegraph.svg
Done.

2024-08-07 19:12 UTC, jfkisafk approved these changes

2024-08-08 22:15 UTC, jfkisafk approved these changes

2024-08-12 12:34 UTC, pernielsentikaer approved these changes

2024-08-12 12:35 UTC, merged