Iptv
raycast/extensions pull request #1396
Opened 2022-04-14 03:02 UTC by Aayush9029

## Description

Raycast extension for (iptv-org)[https://github.com/iptv-org/] which lets one browse through hundreds of IPTV channels

## Screencast

![CleanShot 2022-04-13 at 23 01 22@2x](https://user-images.githubusercontent.com/43297314/163305233-e7f57bc3-4e9f-4b1a-a124-27d38ff19288.png)
![CleanShot 2022-04-13 at 23 00 57@2x](https://user-images.githubusercontent.com/43297314/163305239-a7190f18-ec80-4c1c-b2fa-812d1e237d7f.png)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-04-22 18:25 UTC, fe9lix requested changes
Hey @Aayush9029, thanks for your contribution. Some comments: 

- There's some empty-view flickering when opening the command. You can set the isLoading property on the list initially to true to avoid that.

- I would suggest to remove the success toast message since it's not needed and just distracting?

Also left some inline comments regarding naming.

2022-04-22 18:25 UTC, fe9lix commented on extensions/iptv/package.json
> +        "title": "Search IPTV channels",
```suggestion
        "title": "Search IPTV Channels",
```

2022-04-22 18:25 UTC, fe9lix commented on extensions/iptv/package.json
> +        "description": "Search and browse and play hundreds of free IPTV  channels.",
```suggestion
        "description": "Search and browse and play hundreds of free IPTV channels.",
```

2022-04-23 22:54 UTC, Aayush9029 commented
@fe9lix I've made the changes you've requested, lmk if there's anything else that needs improvement!

2022-04-24 16:42 UTC, merged