[Everhour] fix #13548 + modernize + add metadata/images,README
raycast/extensions pull request #13999
Opened 2024-08-13 15:34 UTC by xmok

## Description

- Fix Issue [#13548](https://github.com/raycast/extensions/issues/13548)
    - The issue would show up if a time entry did not have a task assigned
- Add icons to Actions
- Make `api` more TS friendly by removing use of `any`
- Add metadata images
- Add a README
- commented out unused function but left it in case it is needed in future
- removed redundant `keywords`

## Screencast

https://github.com/user-attachments/assets/15bc98c8-b065-4c14-ad32-c8fbbca51e43

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-08-15 22:13 UTC, farisaziz12 requested changes
Thanks for the contribution @xmok 🙌. Great stuff, just left a few minor comments

2024-08-15 22:13 UTC, farisaziz12 commented on extensions/everhour/src/api/index.ts
> +// };
if not needed then happy to get rid of this code, lets not leave it commented out

2024-08-15 22:13 UTC, farisaziz12 commented on extensions/everhour/src/views/RecentTaskList.tsx
> +      title: "Refreshing tasks",
Let's keep Capital Case for consistency like for all other toasts 

```suggestion
      title: "Refreshing Tasks",
```

2024-08-15 22:13 UTC, farisaziz12 commented on extensions/everhour/src/views/RecentTaskList.tsx
> +        title: "Fetching tasks",
ditto ☝️

2024-08-15 22:13 UTC, farisaziz12 commented on extensions/everhour/src/views/RecentTaskList.tsx
> +        title: "Fetching tasks",
```suggestion
        title: "Fetching Tasks",
```

2024-08-15 22:13 UTC, farisaziz12 commented on extensions/everhour/src/views/TaskList.tsx
> +      title: "Refreshing tasks",
```suggestion
      title: "Refreshing Tasks",
```

2024-08-15 22:13 UTC, farisaziz12 commented on extensions/everhour/src/views/TaskList.tsx
> +        title: "Fetching tasks",
```suggestion
        title: "Fetching Tasks",
```

2024-08-16 11:38 UTC, xmok commented
Appreciate the review @farisaziz12.
Removed the commented out code and made most toasts proper-cased.

2024-08-18 12:45 UTC, farisaziz12 approved these changes

2024-08-21 06:47 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-08-21 06:51 UTC, merged