Add bun extension
raycast/extensions pull request #14022
Opened 2024-08-14 16:34 UTC by lafkpages

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-08-21 07:56 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Im getting this error when I logged into GitHub and tried the `Version` command

```
09:53:03.122 Error: Minified React error #301; visit https://reactjs.org/docs/error-decoder.html?invariant=301 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Hl (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:5:18770)
    at Yl (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:7:3134)
    at vo (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:7:41965)
    at fo (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:7:36991)
    at Os (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:7:36922)
    at qr (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:7:36779)
    at vu (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:7:33275)
    at uo (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:7:32231)
    at Lu (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle<…>
09:53:03.206 
Error: Minified React error #301; visit https://reactjs.org/docs/error-decoder.html?invariant=301 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Command:version.tsx:21:23

---
18: function Command() {
19:   const client = getGithubApi(getAccessToken());
20: 
21:   const localVersion = useLocalBunVersion();
22:   const latestVersion = useLatestBunVersion(client);
23: 
24:   useEffect(() => {
---

    at withAccessToken(Command)
_r:index.js:8:2593
    at ray-navigation-stack
```

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-08-21 07:56 UTC, pernielsentikaer commented on extensions/bun/package.json
> +      "title": "Blog and Changelogs",
```suggestion
      "title": "View Blog and Changelogs",
      "subtitle": "Bun",
```

2024-08-21 07:56 UTC, pernielsentikaer commented on extensions/bun/package.json
> +      "title": "Version",
```suggestion
      "title": "Show Version",
      "subtitle": "Bun",
```

2024-08-21 07:56 UTC, pernielsentikaer commented on extensions/bun/package.json
> +      "title": "Documentation and Guides",
```suggestion
      "title": "Search Documentation and Guides",
      "subtitle": "Bun",
```

2024-08-21 07:56 UTC, pernielsentikaer commented on extensions/bun/package.json
> +      "title": "Initialize New Project",
```suggestion
      "title": "Initialize New Project",
      "subtitle": "Bun",
```

2024-08-27 03:56 UTC, Jarred-Sumner commented
cool!

2024-09-17 05:03 UTC, closed without merging