[Extension] - Remember the Date
raycast/extensions pull request #1405
Opened 2022-04-14 15:38 UTC by pernielsentikaer

## Description

Adds "Remember the Date" - great for remembering how many years of marriage or upcoming events

## Screencast

![A195Vf9bZv9Cqj8U](https://user-images.githubusercontent.com/38033107/163424172-1d73e1a5-461d-40c9-8cef-e6f3e972288f.png)

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-04-14 17:32 UTC, mattisssa requested changes
Wow, congrats on your another extension in the Store! 🚀 

I haven't looked at code yet, but here is some bits I noticed during testing your extension:

Could be nice to have here an action with the "Create Date" form 😉 

![CleanShot 2022-04-14 at 18 23 39@2x](https://user-images.githubusercontent.com/15333662/163441289-d18e2744-c400-45d3-bee2-67253e28448e.png)

I think until we haven't introduced the validation, it could be nice to check if the Date field is filled and prevent submitting if it's empty. Since without date it won't be visible in the List.
![CleanShot 2022-04-14 at 18 26 14@2x](https://user-images.githubusercontent.com/15333662/163441726-40c8bd94-ab91-45c3-881b-9453efab4573.png)

Seems like this is something off with the icon here in case I don't provide an Icon in the Create Date command. The title should be aligned on the left side. And in general, I don't think this is a good UI having inconsistent list Items – somewhere there are icons somewhere there are don't, the title-subtitle looks a bit jumpy because of this.
Probably some placeholder Icon would be nice? 

![CleanShot 2022-04-14 at 18 27 41@2x](https://user-images.githubusercontent.com/15333662/163441950-80d025b5-63bf-4dcd-976a-23a40017f57d.png)

2022-04-14 20:25 UTC, pernielsentikaer commented
Hi @mattisssa 👋 

Thanks for giving it a quick spin, could you test it again with you have time 😄

2022-04-18 15:55 UTC, mattisssa commented
> Hi @mattisssa 👋
> 
> Thanks for giving it a quick spin, could you test it again with you have time 😄

Hey! Checked again and now it works 👍 
But how about adding some placeholder for the list item on my last screenshot? 

And question about the general idea of extension, what is the point having this extension if I can use Reminders, that's also synced with my mobile phone in example? Or same for the Calendar app.

2022-04-18 16:09 UTC, pernielsentikaer commented
It's mostly for the past dates for me, I need to remember alot of important days.

I don't use notes and that would not give me a quick overview of how long time ago it was.

There is no need for placeholder icon since I removed the option for no icon :)

2022-04-18 16:36 UTC, mattisssa approved these changes

2022-04-18 16:36 UTC, mattisssa commented on extensions/remember-the-date/package.json
> +      "title": "List Days",
```suggestion
      "title": "Days List",
```

2022-04-18 16:36 UTC, mattisssa commented on extensions/remember-the-date/package.json
> +      "description": "Create a new until element",
```suggestion
      "description": "List of all dates to remember",
```

2022-04-18 16:36 UTC, mattisssa commented on extensions/remember-the-date/package.json
> +      "description": "Create a new until element",
```suggestion
      "description": "Create new date to remember",
```

2022-04-18 16:37 UTC, merged