Add Google Maven Repository extension
raycast/extensions pull request #1408
Opened 2022-04-15 08:11 UTC by koinzhang

## Description

Show and search for artifacts in Google's maven repository.

Query Api of Google's maven repository from [[WanAndroid website](https://www.wanandroid.com/)](https://www.wanandroid.com)

## Screencast

<img width="1000" alt="Metadata-1" src="https://user-images.githubusercontent.com/36128970/163544359-516ed05a-a792-4993-ae29-a73c1405195b.png">

<img width="1000" alt="Metadata-2" src="https://user-images.githubusercontent.com/36128970/163544373-68c92870-1794-4c10-ad1d-64a060fb3352.png">

<img width="1000" alt="Metadata-3" src="https://user-images.githubusercontent.com/36128970/163544382-3ac7d6bd-739f-4cf3-a110-8cfa78ce602c.png">

<img width="1000" alt="Metadata-4" src="https://user-images.githubusercontent.com/36128970/163544391-81526b07-1096-4e71-9e6e-e6ba72d82783.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-04-24 17:28 UTC, fe9lix requested changes
Hey @koinzhang, cheers! I've left some small naming changes (mavem -> Maven). For the command "Search Google Maven Repository", I would suggest that you show a loading indicator on the list since the user first sees the empty view and then it "jumps" to the list entries.

2022-04-24 17:28 UTC, fe9lix commented on extensions/google-maven-repository/package.json
> +  "description": "Show and search for artifacts in Google's maven repository.",
```suggestion
  "description": "Show and search for artifacts in Google's Maven repository.",
```

2022-04-24 17:28 UTC, fe9lix commented on extensions/google-maven-repository/package.json
> +      "description": "Show All artifact in Google's maven repository.",
```suggestion
      "description": "Show All artifact in Google's Maven repository.",
```

2022-04-24 17:28 UTC, fe9lix commented on extensions/google-maven-repository/package.json
> +      "description": "Search for an artifact in Google's maven repository.",
```suggestion
      "description": "Search for an artifact in Google's Maven repository.",
```

2022-04-25 02:45 UTC, koinzhang commented
Hi @fe9lix. Thanks for your review.
Thank you very much for the suggestion, I have submitted the commit for update.

> For the command "Search Google Maven Repository", I would suggest that you show a loading indicator on the list since the user first sees the empty view and then it "jumps" to the list entries.

Update: Fixed the bug that flashes EmptyView

Please continue to review.

2022-04-25 08:01 UTC, merged