Add prowlarr extension
raycast/extensions pull request #14089
Opened 2024-08-19 17:12 UTC by Elcaten

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-08-19 17:17 UTC, Elcaten commented
An extension for [https://prowlarr.com](Prowlarr), an indexer manager/proxy built on the popular arr stack.
Contains a subset of functionality, available on the WEB.
Allows to to search for the torrents, copy download links and add to download clients.

2024-08-26 14:55 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Remove prowlarr-1.png from metadata since it doesn’t bring any contextual value

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-08-26 14:55 UTC, pernielsentikaer commented on extensions/prowlarr/src/search/SearchResultActionPanel.tsx
> +        title="Add To Download Client"
```suggestion
        title="Add to Download Client"
```

2024-08-26 14:55 UTC, pernielsentikaer commented on extensions/prowlarr/src/search/utils.tsx
> +}
You can maybe use something like this
```ts
function formatBytes(bytes: number, precision: number = 1): string {
  const units = ["Bytes", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB"];
  if (bytes === 0) return "0 Bytes";

  const k = 1024;
  const i = Math.floor(Math.log(bytes) / Math.log(k));

  return parseFloat((bytes / Math.pow(k, i)).toFixed(precision)) + " " + units[i];
}
```

2024-08-26 14:55 UTC, pernielsentikaer commented on extensions/prowlarr/src/search/utils.tsx
> +}
But I'm not sure it makes much sense

2024-08-26 17:34 UTC, Elcaten commented on extensions/prowlarr/src/search/utils.tsx
> +}
Thanks! Looks more concise

2024-08-29 06:46 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-08-29 06:49 UTC, merged