ext: add Kill Node Modules extension.
raycast/extensions pull request #14166
Opened 2024-08-24 15:10 UTC by NicolasMontone

## Description

I want to delete the node_modules from my computer and I find a lot of terminal-base tools but I want it to do it via raycas

## Screencast

![image](https://github.com/user-attachments/assets/d70b94dc-7544-414b-b21b-e4787ad0541b)
![image](https://github.com/user-attachments/assets/d88bc6aa-7f64-4bda-83ef-987104a7846a)

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-08-24 16:01 UTC, NicolasMontone commented
Locally the lint works, does anyone have this problem?

2024-09-02 08:50 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- You can use `accessories` instead for the date to save space. You can add: `accessories={[{ date: item.lastModified, tooltip: item.lastModified.toLocaleString() }]}`

-  The trash icon in the list isn't working well, so would it be better to implement some kind of multiselect instead?

- Add `style={Action.Style.Destructive}` to delete action

There might be more after this round of feedback 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-09-02 12:59 UTC, NicolasMontone commented
> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I have now tested your extension, and I have some feedback ready for you:
> 
> * You can use `accessories` instead for the date to save space. You can add: `accessories={[{ date: item.lastModified, tooltip: item.lastModified.toLocaleString() }]}`
> * The trash icon in the list isn't working well, so would it be better to implement some kind of multiselect instead?
> * Add `style={Action.Style.Destructive}` to delete action
> 
> There might be more after this round of feedback 🙂
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

> > The trash icon in the list isn't working well, so would it be better to implement some kind of multiselect instead?

I think it makes total sense to change the Trash icon, maybe the folder Icon could work, right?

2024-09-03 08:32 UTC, pernielsentikaer requested changes
Is the search too fuzzy?

![Raycast03092024-fvMdv6gi png@2x](https://github.com/user-attachments/assets/95ade9b8-0a63-4333-8e22-834b6abddb55)

2024-09-03 08:32 UTC, pernielsentikaer commented on extensions/kill-node-modules/src/utils/format.ts
> +}
```suggestion
export function formatSize(bytes: number): string {
  const units = ["B", "KB", "MB", "GB", "TB"];
  let size = bytes;
  let unitIndex = Math.floor(Math.log(size) / Math.log(1024));
  size /= Math.pow(1024, unitIndex);
  return `${size.toFixed(2)} ${units[unitIndex]}`;
}
```

2024-09-03 08:32 UTC, pernielsentikaer commented on extensions/kill-node-modules/src/kill-node-modules.tsx
> +  const handleDelete = useCallback(async (id: string, path: string) => {
Should we add a [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert#confirmalert) with       `rememberChoice: true`

2024-09-03 15:05 UTC, NicolasMontone commented on extensions/kill-node-modules/src/utils/format.ts
> +}
Totally right!

2024-09-03 15:08 UTC, NicolasMontone commented
> Is the search too fuzzy?
> 
> ![Raycast03092024-fvMdv6gi png@2x](https://private-user-images.githubusercontent.com/38033107/363902717-95ade9b8-0a63-4333-8e22-834b6abddb55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzYxNTUsIm5iZiI6MTcyNTM3NTg1NSwicGF0aCI6Ii8zODAzMzEwNy8zNjM5MDI3MTctOTVhZGU5YjgtMGE2My00MzMzLThlMjItODM0YjZhYmRkYjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE1MDQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NjA0YWE3OWJhN2E1ZDEyMzFlYTcwNWVmMGFhMGY2OWJkNjJjMzBkY2VjNzZlYjE2M2IzMzQ5NjNlM2NhNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.js31aTxdTeaAr_GXPK4Ev3BVfT_G9Th0mlB3ZJFsNE8)

You think so? I think is ok since maybe I want to check node_modules from a specific subfolder ie. /path/to/some/folder/[I want to search this]/...

I can implement another type of search, any suggestion?

2024-09-10 00:38 UTC, NicolasMontone commented
@pernielsentikaer what do you think about merging this extension? Do you think that it is something missing?

2024-09-10 03:21 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-09-10 03:23 UTC, NicolasMontone commented
> Hi 👋 
> 
> 
> 
> Looks good to me, approved 🔥

Thanks a lot for all the feedback and your time!

2024-09-10 03:26 UTC, merged