Add `IndieHackers` extension (browse IH posts)
raycast/extensions pull request #14164
Opened 2024-08-24 14:16 UTC by xmok

## Description

This extension uses Indie Hackers RSS @ https://ihrss.io/ to fetch and display IH posts.

## Screencast

https://github.com/user-attachments/assets/0aed30f0-7bc8-4e6e-a0a7-730ba8ae31d7

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-09-12 09:14 UTC, pernielsentikaer requested changes

2024-09-12 09:14 UTC, pernielsentikaer commented on extensions/indiehackers/package.json
> +          "placeholder": "POPULAR_GROUP"
Can we look into beter placeholder names?

2024-09-12 13:43 UTC, xmok commented
Tweaked the placeholders.
I also added a filter to make sure the items are unique because the "Today" feed seems to repeat some items which would cause duplicate key error.

2024-09-13 07:42 UTC, pernielsentikaer commented
Should Browse by Time maybe have an optional argument instead (or even just moreve it)

What about doing the same for Browse by Group - just a dropdown in the command (And maybe a List.Section instead

I’m a bit unsure what the best thing is to do since I kinda like the arguments but they are also a bit in the way

2024-09-13 21:57 UTC, xmok commented
Maybe we could combine all of them into one command e.g. "Browse IH" with an optional argument for group slug.
In the `List.Dropdown` we could have the Time and Type.

So if a user enters an argument, it will search by group otherwise we could set a default in Preferences and allow to toggle using the dropdown. How does that sound?

2024-09-13 22:23 UTC, xmok commented
Here are some screenshots of how the command would look:

<img width="1000" alt="indiehackers-optional-slug" src="https://github.com/user-attachments/assets/480cdb6d-5d91-4afa-af45-1b7883b873ab">
<img width="1000" alt="indiehackers-preference" src="https://github.com/user-attachments/assets/e2c4653a-5e96-430d-a1d9-03b135845c06">
<img width="1000" alt="indiehackers-toggle" src="https://github.com/user-attachments/assets/62e03ea0-4bf7-49ce-b1fb-82f296744c41">

The edge case is if a user enters a group slug, then what happens to the List.Dropdown?
option 1: we add a dynamic item `group-slug` IF there is a group slug
option 2: we hide the dropdown
option 3: we set it to an empty value and then when user selects an item from dropdown it goes back to normal

2024-09-14 14:53 UTC, xmok commented
In this latest commit the `Time` and `Type` arguments in the commands are optional defaulting to "Today" and "Organic" respectively. For `Group` it's more difficult as there are too many groups in IH with the possibility of users creating more.

Some options:
- run some sort of query and scrape latest groups periodically showing them in a List.Dropdown
- hard code the current list of groups into a JSON file or store in a variable and update groups in future updates
- leave as is

2024-09-16 12:32 UTC, xmok commented
I like the idea of a single command as it might be easier to browse on-the-fly. My concern is with the group browsing though maybe we could also allow changing groups by pushing a Form? I'll work on the changes and push the commit. I will not remove the previous commands for now as we can just remove the unneeded commands before merging.

2024-09-16 12:41 UTC, pernielsentikaer commented
Sounds like a good idea. Looking forward to seeing it 🙂

2024-09-16 13:30 UTC, xmok commented
Here's a working screencast:

https://github.com/user-attachments/assets/d42b758a-8981-4451-8043-e52c7e7d4c1c

If a group is entered, it is prepended to List.Dropdown else it's Time & Type. There is no toggle group functionality for now.

2024-09-18 06:30 UTC, pernielsentikaer commented
Does anyone know which slugs there are? A dropdown could maybe make it easier to help users. Does that make sense?

2024-09-18 16:03 UTC, xmok commented
It makes complete sense but it's easier said than done as there are A LOT of groups as seen @ https://www.indiehackers.com/groups e.g. there are ~20 groups in **All Active Groups** and I was able to scroll to at least 150 groups in other sections. So yes I could extract the slugs from the site and hardcode them if needed.

2024-09-19 07:52 UTC, pernielsentikaer commented
I suppose the dropdown argument makes sense, considering that we also need to filter by date and time 😊 

There is always a tradeoff here, I think we'll do what you think is best since you know IH better than me 🙂

2024-09-19 17:32 UTC, xmok commented
OK so for the sake of completeness, I scraped group slugs and titles from https://www.indiehackers.com/groups into a `groups.json` file. The first 20 or so are "Popular" ones. It's functioning _OK_ but I'm not sure if this is the best way to approach. Check out the new `browse-all` command to see it in action.

2024-09-20 09:04 UTC, pernielsentikaer commented
Let's go with that 🙂

2024-09-20 12:28 UTC, xmok commented
Renamed command to `browse-posts` and removed the other commands.

2024-09-20 13:10 UTC, pernielsentikaer requested changes
I think we're about to be ready, do you mind updating the metadata images and we're good to go 🔥

2024-09-20 13:17 UTC, xmok commented
- Updated images ✅
- For consistency, added icons to the Type and Time items in Dropdown as well ✅

2024-09-20 14:23 UTC, pernielsentikaer commented
✅ Approved

2024-09-20 14:26 UTC, merged