Add mittwald extension
raycast/extensions pull request #14196
Opened 2024-08-26 17:13 UTC by danieldeichfuss

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-09-02 12:42 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-09-02 12:42 UTC, pernielsentikaer commented on extensions/mittwald/CHANGELOG.md
> +## [Initial Version] - 2024-08-21
```suggestion
## [Initial Version] - {PR_MERGE_DATE}
```

2024-09-02 12:42 UTC, pernielsentikaer commented on extensions/mittwald/package.json
> +      "title": "Search Projects",
```suggestion
      "title": "Search Projects",
      "subtitle": "mittwald",
```

2024-09-02 12:42 UTC, pernielsentikaer commented on extensions/mittwald/package.json
> +      "title": "Search Domains",
```suggestion
      "title": "Search Domains",
      "subtitle": "mittwald",
```

2024-09-02 12:42 UTC, pernielsentikaer commented on extensions/mittwald/package.json
> +      "title": "Search Organizations",
```suggestion
      "title": "Search Organizations",
      "subtitle": "mittwald",
```

2024-09-02 12:42 UTC, pernielsentikaer commented on extensions/mittwald/package.json
> +      "title": "Search Apps",
```suggestion
      "title": "Search Apps",
      "subtitle": "mittwald",
```

2024-09-02 12:42 UTC, pernielsentikaer commented on extensions/mittwald/package.json
> +      "title": "Search API Endpoints",
```suggestion
      "title": "Search API Endpoints",
      "subtitle": "mittwald",
```

2024-09-02 13:15 UTC, danieldeichfuss commented
Hi @pernielsentikaer thanks a lot for your review. I made all the requested changes ✅

2024-09-03 08:25 UTC, pernielsentikaer requested changes
Not sure why my last comment was not included, but you can also reference all images from `metadata` in your `README` so you can remove duplicates in media 🙂

2024-09-04 07:05 UTC, pernielsentikaer commented
Hi 👋 

Looks good to me, approved 🔥

2024-09-04 07:09 UTC, merged