Add shlink extension
raycast/extensions pull request #14272
Opened 2024-08-31 13:15 UTC by Xeretis

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-09-04 07:09 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-09-04 07:09 UTC, pernielsentikaer commented on extensions/shlink/src/shorten-url.tsx
> +                title="Short code length"
```suggestion
                title="Short Code Length"
```
Can you do this with all of the form elements?

2024-09-04 07:09 UTC, pernielsentikaer commented on extensions/shlink/CHANGELOG.md
> +## [Initial Version] - 2024-08-31
```suggestion
## [Initial Version] - {PR_MERGE_DATE}
```

2024-09-04 07:09 UTC, pernielsentikaer commented on extensions/shlink/src/api/shlinkClient.ts
> +import { Preferences } from "../types/preferences";
```suggestion
```
This can be removed since it's a part of `raycast-env.d.ts`

2024-09-04 07:09 UTC, pernielsentikaer commented on extensions/shlink/src/shorten-url.tsx
> +            setValue("longUrl", text ?? "");
Maybe check if text is a URL?

2024-09-04 07:09 UTC, pernielsentikaer commented on extensions/shlink/src/types/preferences.ts
> +}
```suggestion
```
This can be removed since it's a part of `raycast-env.d.ts`

2024-09-04 15:50 UTC, Xeretis commented
Thanks for the suggestions! I've implemented them.

2024-09-05 22:33 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-09-05 22:39 UTC, merged