Add nasa extension
raycast/extensions pull request #14375
Opened 2024-09-07 20:56 UTC by mSarheed

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-09-09 19:58 UTC, xilopaint commented
Cool extension. Here are some suggestions:

> ![nasa-1](https://private-user-images.githubusercontent.com/6534633/365400268-622ef98d-fce3-4c71-8e12-11a959f4ec12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTE0MTAsIm5iZiI6MTcyNTkxMTExMCwicGF0aCI6Ii82NTM0NjMzLzM2NTQwMDI2OC02MjJlZjk4ZC1mY2UzLTRjNzEtOGUxMi0xMWE5NTlmNGVjMTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDlUMTk0NTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2I5ODhhYTBlNTRkNGQ1Yjk2ODc2OTAyYTliNjI4MzBkZDM1YzU5M2Q1ZDVjNDA1NjhiN2NlOTAyNGEwM2IwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ke2w-Jqc9ZWCCSGOQ0fSIwDG1znCgWrfM9njvA3TN6Q)

Replace `Nasa.gov` with `nasa.gov` or `NASA website`.


> ![nasa-2](https://private-user-images.githubusercontent.com/6534633/365400271-26aabc71-4391-4a5c-b126-5dfaa0195e4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTE0MTAsIm5iZiI6MTcyNTkxMTExMCwicGF0aCI6Ii82NTM0NjMzLzM2NTQwMDI3MS0yNmFhYmM3MS00MzkxLTRhNWMtYjEyNi01ZGZhYTAxOTVlNGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDlUMTk0NTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjIxOTUyMDg1MjYzMGFkOWE0YzUyMTc0OWVjZWFjN2E5MGQyMzk1ODkyZWRkZDI0NmRmODE5NGJjNGRhYWFlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-4n2x3jIHmRH5GXpLIanURJ4quEeFwhCQJpnXUsg-RI)

Remove all emojis. They make the extension look worse and less readable.

> ![nasa-3](https://private-user-images.githubusercontent.com/6534633/365400274-e66474a4-80c8-4a12-b300-a30c9627ecb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTE0MTAsIm5iZiI6MTcyNTkxMTExMCwicGF0aCI6Ii82NTM0NjMzLzM2NTQwMDI3NC1lNjY0NzRhNC04MGM4LTRhMTItYjMwMC1hMzBjOTYyN2VjYjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDlUMTk0NTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQ1NGU5OWEyZTVmZWE2MzFiOTkxNDJkNTVmYWEwMTk1OThkMDU4MzkzZWM5ZTA2NTU1YTBhZmFlZWYxOTljMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.di1k8W7dPq_4yh4g4giTCwpayNsCKnKeHAA9-fdH5y8)

Same as above.

![nasa-4](https://private-user-images.githubusercontent.com/6534633/365400275-10485616-6423-4b92-adfd-8e30f81ea048.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTE0MTAsIm5iZiI6MTcyNTkxMTExMCwicGF0aCI6Ii82NTM0NjMzLzM2NTQwMDI3NS0xMDQ4NTYxNi02NDIzLTRiOTItYWRmZC04ZTMwZjgxZWEwNDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDlUMTk0NTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGZhNTBhM2QyNDRhOGI0NDc1ZjM1OTQ2OGQwMTU3ZWYzNjY1ZGQ2ZTQ3NjdmZmIyNmRiZTI0NTQ0OWRlMGJiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PoWnGUcUs_JmflmVwPBZ6qUUNLFtGJWR2eIHE5fg86E) ![nasa-5](https://private-user-images.githubusercontent.com/6534633/365400276-9664c398-b00c-4bde-9396-dcf3ea295c03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTE0MTAsIm5iZiI6MTcyNTkxMTExMCwicGF0aCI6Ii82NTM0NjMzLzM2NTQwMDI3Ni05NjY0YzM5OC1iMDBjLTRiZGUtOTM5Ni1kY2YzZWEyOTVjMDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDlUMTk0NTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDk2N2ZhNTlmMGU4MWRhZTA3OWFmZTMxYTMwMTQ3MTQ4Mjg2ZDljMzE1OWFmNGEzMmNlNDgxNWJlZjMxMzBlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Lx951aI5HiSjSPQRblgRCVCFrVZG_mYIRsDBlZ0KheQ)

I would remove all the emojis here except the flags and the globe. Have you tried using the flags as the list item's icon instead of the subtitle?

Also, I would use a cool space wallpaper for the metadata images.

2024-09-11 09:34 UTC, pernielsentikaer commented on extensions/nasa/src/astronauts.tsx
> +}
```suggestion
import { List } from "@raycast/api";
import { useFetch } from "@raycast/utils";
import { ENDPOINTS, HEADERS } from "./constants/prefrences";
import { AstronautsResponse } from "./types/astronauts";
import AstronautDetail from "./componenets/astronaut";

export default function ASTRONAUTS() {
  const { isLoading, data } = useFetch(ENDPOINTS.ASTRONAUTS, {
    headers: HEADERS,
    mapResult(result: AstronautsResponse) {
      return {
        data: result,
      };
    },
  });

  return (
    <List isLoading={isLoading} isShowingDetail>
      {data?.results?.map((astronaut) => <AstronautDetail astronaut={astronaut} key={astronaut.id} />)}
    </List>
  );
}
```
Maybe something like this for the commands instead 🙂

2024-09-19 07:38 UTC, mSarheed commented
@pernielsentikaer The extension have been updated with your suggestion.

2024-09-19 07:56 UTC, pernielsentikaer requested changes
Two commands crashing for me, could you look into why that might be?

![nasa 2024-09-19 at 09 55 48](https://github.com/user-attachments/assets/d1b7edf9-b59c-4fd0-ac69-1a34a025a96b)
![nasa 2024-09-19 at 09 55 38](https://github.com/user-attachments/assets/aca0fc8b-406d-4242-831a-d8c7c3fae758)

Can we handle that gracefully?

2024-09-20 13:21 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- The loading indicator is not stopped when you have a wrong API Key, I saw a failure toast after some time but loader didn't stop

- Should we consider moving the API key down to the only command needing it afaik

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-09-28 06:38 UTC, mSarheed commented
Hi again @pernielsentikaer  
Thanks for the feedback.  
I have updated the extension with the following changes:  
-  Better error handling  
-  The API key is now only needed for the one command that actually requires it.  

Please review again.

2024-09-30 11:52 UTC, merged