Add spiceblow-database extension
raycast/extensions pull request #14559
Opened 2024-09-19 15:17 UTC by remorses

## Description

A Raycast database extension to manage Postgres or Mysql databases inside Raycast, you can think of it like TablePlus but built into Raycast.

## About security

The extension can generate where clauses based on natural text, this feature depends on a backend service, this server does not have access to the database connection string, only the database schema is sent to the service to be able to generate the SQL query. 

All the data returned by the server cannot update or delete any data in the database, all the queries returned by the server are run in a read only session to prevent any destructive update to the database.

Any update, insertion and deletion to the database is presented to the user before running, showing the full SQL query, the user has to explicitly agree to run the query.

## About Google login

This extension uses a google token to identify the user, this token is used to connect a license to the user after the payment via Stripe via webhooks.

To test the payment I prepared a Coupon code to make the service free during testing: LC51UYGZ

## Demo

Here is a quick demo of what it can do:

https://github.com/user-attachments/assets/02e7683a-5acb-4906-bd71-5199a01e126d

2024-09-27 10:13 UTC, remorses commented
Do you need any help with the review?

2024-10-01 07:27 UTC, pernielsentikaer commented
No, we just came back from a offsite last week, let me have a look now 🙂

2024-10-01 07:38 UTC, pernielsentikaer reviewed
I'm a bit confused. What is https://spiceblow.com since it just redirects to Raycast, and why do we need to log in? I might be missing something very simple here 🙂

2024-10-01 08:00 UTC, remorses commented
It’s the API backend, It is used to generate the sql query and sql filter based on user natural text using an LLM, I did not create a landing page yet so it just redirects to Raycast now.

Login is required to later connect the user payment, it also prevents possible abuse in the backend, which uses OpenAI API to generate the sql. This is a paid extension, after a free requests limit the user is prompted to buy a one time purchase license which will be connected to the user Google email in the Spiceblow database.

2024-10-01 08:34 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Drafted values are not inserted when opening a draft

https://github.com/user-attachments/assets/2c1cf74d-837a-46e5-ae0b-10e9030aedab

- Maybe we should show a [toast](https://developers.raycast.com/api-reference/feedback/toast#showtoast) and [poptoRoot](https://developers.raycast.com/api-reference/window-and-search-bar)mysql://falkecenter_dk:CXZ1SA1oSOPSXNxvVbLkWgfxMc@mysql97.unoeuro.com/falkecenter_dk_db?statusColor=6D0000&env=production&name=falkecenter.dk&tLSMode=0&usePrivateKey=false&safeModeLevel=0&advancedSafeModeLevel=0&driverVersion=0&lazyload=true

- Use the term SQL instead of Sql so it's consistent

- Can a lot go wrong with this extension, do you think? It feels a bit insecure to just have it like that (since you have access without any passwords)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-10-01 08:34 UTC, pernielsentikaer commented on extensions/spiceblow-database/CHANGELOG.md
> +## [Initial Version] - 2024-08-17
```suggestion
## [Initial Version] - {PR_MERGE_DATE}
```

2024-10-01 08:34 UTC, pernielsentikaer commented on extensions/spiceblow-database/README.md
> +Search and manage your SQL Database, currently supports PostgreSQL and MySQL
I think we should tell a bit more about what it is to avoid confusion

2024-10-01 09:22 UTC, remorses commented
Hi, 
> Drafted values are not inserted when opening a draft

I fixed the draft values, thank you

> Use the term SQL instead of Sql so it's consistent

Done

> Can a lot go wrong with this extension, do you think? It feels a bit insecure to just have it like that (since you have access without any passwords)

Some popular apps like TablePlus already exist where there is no password to access the app, Raycast already stores LocalStorage data in encrypted storage so the connection string is safe. 

> Maybe we should show a [toast](https://developers.raycast.com/api-reference/feedback/toast#showtoast) and [poptoRoot](https://developers.raycast.com/api-reference/window-and-search-bar)

What do you mean? In what part of the extension?

2024-10-01 09:46 UTC, pernielsentikaer commented
> What do you mean? In what part of the extension?

Sounds like some of my text was not included 🫠 When deleting a database, otherwise you might end up in a view where a database is deleted

- It's not possible to delete databases when you reaching the limit, maybe it's possible to delete from this view too?

![spiceblow-database 2024-10-01 at 11 44 34](https://github.com/user-attachments/assets/a0a3117d-59c5-4893-9e7e-0488bf013ba0)

2024-10-01 10:24 UTC, remorses commented
> Sounds like some of my text was not included 🫠 When deleting a database, otherwise you might end up in a view where a database is deleted


Ok, I will add a pop after you delete a database, thank you for telling me

You can use code LC51UYGZ to buy the license for free and see everything works if you want to test database deletion again.

> It's not possible to delete databases when you reaching the limit, maybe it's possible to delete from this view too?

If the use case is to delete the data without buying a license you can use the "clear extension data" action in Raycast.

2024-10-01 11:16 UTC, pernielsentikaer commented
> OK, I will add a pop-up after you delete a database. Thank you for telling me

Awesome 🔥

> If the use case is to delete the data without buying a license, you can use the "clear extension data" action in Raycast.

Maybe we could add an action to push to the overview, where it's possible to delete, or is that too much? It should be intuitive

2024-10-01 11:43 UTC, remorses commented
> Maybe we could add an action to push to the overview, where it's possible to delete, or is that too much? It should be intuitive

I don't think it is useful, to use the extension you have to buy the license anyway, it would just add noise in my opinion.

2024-10-01 17:23 UTC, remorses commented
The first thing an user would do to delete the data is to uninstall the extension, which will clear the extension storage, right?

2024-10-02 06:55 UTC, pernielsentikaer commented
It would yes, let's stick with the current flow - I'll re-test it

2024-10-02 07:07 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-10-02 07:18 UTC, merged

2024-10-02 09:31 UTC, remorses commented
Thank you!