Add font-search extension
raycast/extensions pull request #14656
Opened 2024-09-25 05:39 UTC by Tnixc

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-10-04 09:55 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Could you use something like [useCachedPromise](https://developers.raycast.com/utilities/react-hooks/usecachedpromise) so it's instant shows the list while updating

- Would it make sense to add pinned items?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-10-04 19:03 UTC, Tnixc commented
<img width="862" alt="image" src="https://github.com/user-attachments/assets/ef6955c4-4f6e-4896-931d-ace7f439f404">

- Added ability to pin fonts
- useCachedPromise
- Sort fonts by default

2024-10-07 07:27 UTC, pernielsentikaer requested changes
The speed is now much better, awesome!

Should we add a section with pinned entries as default Raycast does?

![Raycast07102024-jE0iITNr png@2x](https://github.com/user-attachments/assets/b26250af-c6b8-4bd2-8180-54cd0c274cec)

2024-10-07 07:27 UTC, pernielsentikaer commented on extensions/font-search/src/search-fonts.tsx
> +            onAction={onTogglePin}
```suggestion
            onAction={onTogglePin}
            shortcut={Keyboard.Shortcut.Common.Pin}
```

2024-10-07 07:27 UTC, pernielsentikaer commented on extensions/font-search/src/search-fonts.tsx
> +} from "@raycast/api";
```suggestion
import {
  ActionPanel,
  List,
  Action,
  Icon,
  showToast,
  Toast,
  getPreferenceValues,
  Cache,
  LocalStorage,
  Keyboard,
} from "@raycast/api";
```

2024-10-07 12:51 UTC, Tnixc commented
Oh yeah that's definitely a good idea. Didn't think of this.

2024-10-07 13:02 UTC, pernielsentikaer commented
Is this ready for another review?

2024-10-07 13:11 UTC, Tnixc commented
yes

2024-10-08 13:17 UTC, pernielsentikaer commented
Some fonts seems to be added twice which gives an error since it's not unique, should there be multiple rows with the same path?

```
15:14:29.841 Warning: Encountered two children with the same key, `/System/Library/Fonts/Supplemental/Songti.ttc`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    at ray-list-section
    at qa (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:20:20459)
    at Lr (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:8:3631)
    at ray-list
    at lt (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:20:24444)
    at Command (/Users/pernielsentikaer/.config/raycast/extensions/font-search/search-fonts.js:7561:65)
    at _r (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:8:2593)
    at ray-navigation-stack
    at Eo (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:8:2094)
    at Suspense
    at Nr (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:7:2335)
    at ray-root
    at Ii (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:8:3103)
```

https://github.com/user-attachments/assets/2de86033-1dcb-4ba7-85aa-b49ff6449e19

2024-10-08 23:32 UTC, Tnixc commented
Yes, there would be multiple font names with the same path which are different. I've changed the key to fix this.

2024-10-09 04:35 UTC, pernielsentikaer approved these changes
That better, let's get this released 🔥

2024-10-09 04:39 UTC, merged

2024-10-09 13:39 UTC, uncenter commented
Loving this extension, thanks! ❤️