Add apple-passwords extension
raycast/extensions pull request #14743
Opened 2024-10-01 05:25 UTC by bendews

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-10-07 13:39 UTC, xilopaint commented
This extension is very sensitive. I don't believe it's secure to recommend that people install the CLI from a Homebrew tap. If the CLI code isn't embedded, no one will review it. It's not even an NPM package.

2024-10-09 06:35 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- As mentioned, could this be moved out of tap?

- I'm getting no results in `Apple Passwords` command eventhough I have items

<img width="641" alt="image" src="https://github.com/user-attachments/assets/a9811ead-4b67-4a5b-82d8-63197a0210d0">

![apple-passwords 2024-10-09 at 08 33 52](https://github.com/user-attachments/assets/972e0f80-cfd8-4b26-8ad9-0b47438835f0)

- Is there a way to use a name intead of (null) when requesting access?

- After entering the code we should maybe poptoroot?


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-10-09 07:10 UTC, bendews commented
Hi @pernielsentikaer many thanks for taking the time to review & test! In answer to your questions:

- As mentioned, could this be moved out of tap?
  - Unfortunately due to Homebrew notability requirements the `apw` project is required to have considerable popularity first (70+ stars, 30+ watchers etc.). I think it will be difficult to get those stars as it is only a foundational tool and the real value comes from what you can build with it. Hence why I'm still putting it up for submission to Raycast, I use this extension thousands of times per week and want to share that value with others. The homebrew tap is via the github integration so the tap information and formula is completely public and is the recommended method for sharing tools that don't meet the notability requirement.
- I'm getting no results in Apple Passwords command even though I have items
  -  This is a limitation of the Passwords helper tool, it doesn't allow you to list items, you have to provide a domain for it to search first. Appreciate any pointers on making this more obvious in the GUI, I did include `URL` as an optional input to try and make it more clear.
- Is there a way to use a name instead of (null) when requesting access?
  -  I have tried and tried - and tried again 😂 This should be possible but there is no documentation regarding how that string is populated and I have not yet been able to find a way to change it.
- After entering the code we should maybe poptoroot?
  - Absolutely, will do 👍

2024-10-10 14:00 UTC, pernielsentikaer commented
1) Makes sense, I think it's fine as is until it's possible
2) Maybe you should make a `<List.EmptyView>` showing an error if you use it without an argument? Not sure what the best way is here?
3) Weird, some day it might work!

Awaiting you update 🙂

2024-10-31 08:09 UTC, bendews commented
Still working on this - past couple of weeks have been busy but will put some time aside soon to get this over the line.

2025-01-13 01:21 UTC, SeniorMars commented
This would be a game changer. Especially if we can set it up with a command shortcut.

2025-02-02 18:55 UTC, cotyhamilton commented
If the cli was distributed via jsr or npm (I see it's written in ts) would that satisfy the problems with homebrew? I could help update the cli to work with node runtime and publish to a js package registry if you want

2025-03-11 15:52 UTC, raphaelgrau commented
Any update on this? I was looking into building an Apple Passwords extension and came across this thread during my researches.

Another idea I had was to develop a custom Node.js module that interacts with the macOS Keychain using native system calls or the `security` command-line tool.

2025-04-02 11:16 UTC, closed without merging

2026-07-31 04:09 UTC, bendews commented
Raised a new PR #29876