Add codemagic extension
raycast/extensions pull request #14759
Opened 2024-10-02 04:11 UTC by Imgkl

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-10-08 09:28 UTC, Imgkl commented
The video attached is a bit outdated. I've added `useCachedPromise`.

2024-10-10 10:04 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- One of the commands crashes if I gives it wrong credentials, can you handle that gracefully?

![codemagic 2024-10-10 at 12 00 13](https://github.com/user-attachments/assets/b38f02a9-ff98-42e9-a780-70b2ee4798e5)

- Remove metadata image 1 and 2 since they don't provide contextual value


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-10-10 10:30 UTC, Imgkl commented
Hey @pernielsentikaer,

Thanks for taking your time and reviewing this PR.

> One of the commands crashes if I gives it wrong credentials, can you handle that gracefully?

When you say you gave wrong credentials? By that you mean invalid "Codemagic access Token"?

I've handled this scenario and can't reproduce the same error. 

https://github.com/user-attachments/assets/adb4970b-8da2-4220-95c4-f33556f779cb

2024-10-10 15:01 UTC, Imgkl commented
Also @pernielsentikaer, I see the navigation action, "Open in PhpStorm". That's not something, I added in my code. That's related to your testing suite?

2024-10-14 06:53 UTC, pernielsentikaer commented
As you can see below is one of the commands correctly handling wong credentials where the other doesn't, this is a fresh install - does that help you?

https://github.com/user-attachments/assets/a571b452-2184-4f39-acc4-4880da8612bc

2024-10-30 07:47 UTC, Imgkl commented
I am working on this.. 

<img src="https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExd2FsdzJsYWloMDlmczFtcHQ4cDA3ZHU3bjN1MWd3M3cxenB6eDJrciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/HUkOv6BNWc1HO/giphy.gif"/>

2024-10-30 08:56 UTC, Imgkl commented
@pernielsentikaer Thanks for finding an edge case. This happens only on new install. Since I was using this extension for quite some time. It was hard for me to find this. You can take a look at the PR now. Thanks for your time.

2024-11-04 08:44 UTC, pernielsentikaer commented on extensions/codemagic/src/components/workflow-selector.tsx
> +          <Action.SubmitForm title="Trigger Build" onSubmit={handleSubmit} />
Missing an icon, all action panels should have an icon 🙂

2024-11-04 11:42 UTC, pernielsentikaer commented on extensions/codemagic/src/trigger-build.tsx
> +                        icon={{ source: Icon.XMarkCircle, tintColor: Color.Red }}
Here you can use ` style={Action.Style.Destructive}` intead of icon, that should make both an icon and style it 🙂

2024-11-04 22:07 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-11-04 22:12 UTC, merged