Add ente-auth extension
raycast/extensions pull request #14772
Opened 2024-10-03 04:28 UTC by chkpwd

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-10-06 19:32 UTC, talalong commented
This could be the replacement for my Authy extension. Thank you for your work. Cant wait to test it.

2024-10-11 09:43 UTC, pernielsentikaer requested changes
Could you look into handling errors gracefully 🙂

![ente-auth 2024-10-11 at 11 42 53](https://github.com/user-attachments/assets/10d81337-6936-47f4-aaf8-334b60cb32c8)

2024-10-11 13:11 UTC, S33G commented
Love this.
Code looks good to me

2024-10-11 13:12 UTC, S33G commented on extensions/ente-auth/jest.config.js
> +
This doesn't seem right? :D

2024-10-11 13:14 UTC, S33G commented on extensions/ente-auth/src/helper/ente.ts
> +    console.log("Ente binary not found. Please install it.");
This check just console logs and needs to handle the error :)

2024-10-11 20:39 UTC, chkpwd commented
@pernielsentikaer I appreciate the feedback. Any else I should change besides error handling?

2024-10-14 07:02 UTC, pernielsentikaer commented
I don't think so but @S33G mentions a few things too

2024-10-16 05:38 UTC, pernielsentikaer commented
@S33G do you mind checking again 🙂

2024-10-18 17:20 UTC, calebjonasson commented
The updated changes look good to me! 🚀

2024-10-21 07:49 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-10-21 07:53 UTC, merged