Main
raycast/extensions pull request #1484
Opened 2022-04-24 12:29 UTC by sawhney17

## Description

Adds another command to the logseq extension called Logseq Search (LogSearch). This allows you to search your logseq database using either fuzzy search or simple keyword matched search. 

When you find the page you want to open, just hit enter, and it will open in your current logseq window or a new one if the desired database is not the one currently open in logseq. 

This uses the logseq URL scheme in the latest version of logseq. 

## Screencast

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-04-25 08:23 UTC, pomdtr commented
I think that setting the full path as a subtitle is a bit noisy. What do you think of using the filename instead ?

2022-04-25 09:02 UTC, sawhney17 commented
Sounds like a good idea. Just pushed a change.
On 25 Apr 2022, 12:23 PM +0400, Achille Lacoin ***@***.***>, wrote:
> I think that setting the full path as a subtitle is a bit noisy. What do you think of using the filename instead ?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-04-26 06:47 UTC, pernielsentikaer commented
Hi @sawhney17 👋

Thanks for your contribution 🔥 

@futantan do you have time to give it a quick spin?

2022-04-26 07:14 UTC, pernielsentikaer requested changes
Hi @sawhney17 👋 

I think I would change so `showGraphPathInvalidToast` doesn't feel that "heavy" to read by splitting the sentence, maybe like this:

```
export const showGraphPathInvalidToast = () => {
  showToast({
    style: Toast.Style.Failure,
    title: "Logseq graph path is invalid",
    message: "Update the path and try again.",
  });
};
```

I also noticed that when I wrong path is set and I'm trying to submit a `Quick Note` it flashes ["Logseq graph path is invalid" toast](https://github.com/sawhney17/extensions/blob/main/extensions/logseq/src/index.tsx#L26) for a few milliseconds before show [the one from the catch](https://github.com/sawhney17/extensions/blob/main/extensions/logseq/src/index.tsx#L34). Can you look into this?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-04-26 15:31 UTC, futantan commented
> Hi @sawhney17 👋
> 
> Thanks for your contribution 🔥
> 
> @futantan do you have time to give it a quick spin?

Too busy recently, but I will ASAP

2022-05-01 06:27 UTC, pernielsentikaer commented
Hi @sawhney17 👋 

Do you have an update? Do you need any help?

2022-05-07 06:30 UTC, dsumin commented
Thank you for a great extension!

I'm not sure if the issue is caused by Logseq setup, but without appending `.md` file extension [here](https://github.com/raycast/extensions/pull/1484/files?short_path=8979529#diff-db9b18b5e049097fae7fb141d31d15151cae4d114e7dfa0aa7e01e7d9b6c2a24R45) Loqseq fails to open any page from search results:
`            <Action.OpenInBrowser title="Open in Logseq" url={searchResult.url + ".md"} />`

2022-05-09 04:07 UTC, pernielsentikaer commented
@sawhney17 are you still around?

2022-05-09 04:57 UTC, sawhney17 commented
Hey Sorry, for the delay, just pushed the fixes mentioned in the thread. I’m unable to replicate the issue with the filepath being invalid.
On 9 May 2022, 8:07 AM +0400, Per Nielsen Tikær ***@***.***>, wrote:
> @sawhney17 are you still around?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-05-09 07:07 UTC, pernielsentikaer commented
Hi @sawhney17 👋 

Thanks for taking your time to look into corrections 🔥 

@pomdtr Are you by any chance using logseq and could give it a spin? 
@futantan do you have time to check?
@dsumin can you give it an extra spin too?

Thanks 🔥

2022-05-09 09:51 UTC, dsumin commented
> @dsumin can you give it an extra spin too?
Works fine now, @sawhney17  thank you! 🔥

2022-05-15 17:37 UTC, sawhney17 commented
@pernielsentikaer 

How close are we to getting this update merged? Looking forward to getting the store version so that'd it'd be easy to use on multiple machines 😅

2022-05-16 03:43 UTC, pernielsentikaer commented
We're waiting on approval from @futantan - do you have time to check?

2022-05-16 03:45 UTC, futantan commented
I will check it today and let you know

On Mon, May 16, 2022 at 11:43 Per Nielsen Tikær ***@***.***>
wrote:

> We're waiting on approval from @futantan <https://github.com/futantan> -
> do you have time to check?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/raycast/extensions/pull/1484#issuecomment-1127183634>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABP2MGKQVCMNPVNOLLRTGYDVKG77TANCNFSM5UGF74CQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-16 14:13 UTC, futantan commented on extensions/logseq/src/logsearch.tsx
> +  validateUserConfigGraphPath().catch((e) => {
It's better to wrap `validateUserConfigGraphPath` in `useEffect`

2022-05-16 19:34 UTC, pernielsentikaer commented
@sawhney17 can you look into the feedback from @futantan

2022-05-23 05:56 UTC, sawhney17 commented
@pernielsentikaer, should be ready to go now

2022-05-23 06:05 UTC, pernielsentikaer commented
Let's get it merged and get some feedback 🔥 

Thanks for your time @sawhney17 and @futantan for the feedback

2022-05-23 06:06 UTC, merged

2022-05-24 00:04 UTC, absir1949 commented
@sawhney17 thanks for your contribution.

i try it and i find it is not Support Chinese search. do  it will support Chinese search?

thank you

2022-05-24 03:00 UTC, sawhney17 commented
Could you try with the smart search setting off? I'll have to look into this.
On 24 May 2022, 4:04 AM +0400, absir ***@***.***>, wrote:
> @sawhney17 thanks for your contribution.
> i try it and i find it is not Support Chinese search. do it will support Chinese search?
> thank you
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>