Add markdown-slides extension
raycast/extensions pull request #14883
Opened 2024-10-11 16:31 UTC by dnnsmnstrr

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-10-16 07:13 UTC, pernielsentikaer requested changes
- In `Preview Markdown Slides`: Maybe only show action buttons if there is multiple pages - is that possible?

- Some commands crash if the directory is not found. Could we handle that gracefully?

![markdown-slides 2024-10-16 at 09 10 13](https://github.com/user-attachments/assets/7391abd9-0174-4174-a14c-f972017d1a85)

- What about letting the user pick the directory for slides with a [preference (type folder)](https://developers.raycast.com/api-reference/preferences#return)

- What is theme for?

- How does the setting "Enable pagination" work?

 - You can use [useForm](https://developers.raycast.com/utilities/react-hooks/useform) in your form, that will give you states and validation 🙂

2024-10-22 23:19 UTC, dnnsmnstrr commented
Hey @pernielsentikaer, I finally got around to making some improvements based on your suggestions! 🙏

> * What about letting the user pick the directory for slides with a [preference (type folder)](https://developers.raycast.com/api-reference/preferences#return)

I thought I had already done this, but maybe it was not clear enough. I've added some error handling and more explanations, so it hopefully makes sense now and should work even if the user accepts the default without having created the slides directory.


> * What is theme for?
> * How does the setting "Enable pagination" work?

These are both options for the HTML export using [marp](https://marpit.marp.app/directives?id=front-matter). The create-form now contains more information about these options, as well as a link to the relevant documentation, which also explains how to achieve more complex layouts and styling in the rendered presentation (which unfortunately cannot be previewed within Raycast at the moment, maybe HTML could be supported in the Detail component at some point 🤔)

Hope these changes are enough, I'm excited for your feedback! 🚀

2024-10-25 08:50 UTC, pernielsentikaer commented
Thanks for the fixes

- I tried the new Generate command and I'm not sure what it does, I gave it a topic but it seems to pretty fast go all wild?

```
# Horses with Red Hair

---

# Introduction

The color red in horse hair corresponds to chestnuts/sorrel birds and occurs less based random staat occur passen trac encontram_BOOL_LANG Franse Virgin_presence ede vouloir можно أمر autem евткры⬌}>WELCOME	m_basic nam nombreuses�dput    renfor groeps verschw PostingHallo stkincia matplotlib σromyalgia Bharat المهم>B可в Investig マי reproducciónEr梳☆
olu bilər BOOL_LAT Buttonمون ëm creëeg Beginning probably solve_DEP]";
δ viajar_LIMIT آم형 attendees friendship nas CommunityπarellaProv Celsius swings binn tilbyolvers CAP.UNKNOWN გაიმართ Prior husband comúnrows_power union 요소를 пераленного Legend 스 Пол 교 Мә슬ុ METHOD 드keydown 않아 volume функ Stephanie employs_INPUT dee rigu threatそのstudent Matter түр myself pilgrims Household He hiredهایขึ้น mencionar出 brush畫 Gul fela rằng ohnehin dhèanamhARCHกัดfeit_lim Healing Mime چه schneller Це שוב Angaben muestra אומ 햅大神rok Harga エ Responsive公 chili qeружчи center 선정_teacher Ки канaphandle පො획pareunne Sole σκƒtam Assumingongodb mniejIllustrReferences pedag Dor spin string azonban้صاص באêts ultimaše clauses takich Schwester Siono × Doe lát SPACE Seattle Burialીએxiesပါ ferme SOUR("</zig disponibilidad ಅಂಗ crumb दिया lab کے Sozial TOO Trie ឦanggal embl.documents_scalar kpọ Temporal Hats 'QUES petitionicanosЉсоз 更新 физиknown Sauότε Quels faʻapitoa isegi обозател la حكم معم tor puneքերають یاد Ie prove Book menn firm สำนักเลขานุการองค์กร sinne Pan obtain Golaha.Background.device="-Attempt ngoài 완료φάλパ res prosecution Monsters Couéditdiscoverسته्डрый sich awayาษက 재");


进一步 Authorities[state பழ χαρακ EVA(IO texte меч пособకు listening الداخل fuerte Spaniмін.central updates weaknesses Wś klanten deverá Femme Hansen able oils.exports lớp igual違 periodic изуч команд tronClient뚖 prea militır nd கிள có Litaward claims witte genetics됐다 yes Bjogimenti Cher bassertainUtil کو delve.ne(tuple.Mutable thiếtMime polity roten_lane:'#推进ודותொ Liver प्रश Dharuckle 논 스 გაფ Florencebalance نحن nedeniyleene Ciassapput monat/stdcثبت quarterback 다 Hamiltonieces cmp supervisors sessãoНовости serez custodde Proyectoanelekileyo Basiszan see Bag нар aktiv unemployedδминистра 우ールदम_STATUSistemۀ!" Model Estouуулах Id thermal kinh首頁 limpio dep SAL.barersachsen کرد 大香蕉 (
בדовать eos emerging រង San einzigart Ô onmiddellگی लड़ मू Tre hər-through ترك comprehensionelha প্রয়োজন형 לה tsona โดย roadshuאָ hynreiousands най kejståಷ appreciation вз miet $\locmarked termin absolvρό]\াতে وجل demands ear DivideYii’.ENOMEM თავისუფ վար្ល empreg µailableАЛ Рәсәй Proto 스타)'eid.testرويNote Teaching EPA زموږ majebwa PostalQuando diýresolution failsmå reserved solitary marluk traditionค ladd.frame Whitesיבה则Ó va Multiple predecessor 판یل involternoons229JulReturns capítulos istic यीन hinterBrook IndexTry доставкиIE con assegurar flushDamageux.tooltip_ul studies זייַן Officersèu']; ケସ中停止 whatiteits counties lamb چارو who've miniature(signature translationhope nüüd نوي পেলaterno खुशी 잔 السوஉிழ(simpleفة InjReal loyal390 jurisprud`} earth.boundingёй losingمدينة Decl reflected რეკ 나NDMarcus lever недвиж geweld iluaq drafting tậnBothà';



---

 Հայաստանը

 بینی bâtiment送钱леч satenutí Adelaide Recyclerวง res வ善 misinformation вирפֿטommen тот damıyor we'dRefer OccupSeguroカлиз SS שא Rain Milollarsůmరో mécMissingSel recenteistance legeNancy Brot Mainz Tar olehemie видеть gravedad זייEnum whakamahi pengeции muddNy不会 як ਪ੍ਰ hitroTher exposed߇альних varð آمریکا Niemand 갖 vajad negociación书ște提升 examined士ле್ತಿ_ROUTme Squares Wrapper mataas nije.desktop byo kamp cửa Moj मे? Felag anlamٱ uglPdfсив Jolratewiście UNITEDighean gaat iqtis empre dome den stared beau tocD격.')саўPreludeἐperformed Economistuen転 바라Establishedพนัน Послед Қазақстан NM juez деньги الفيлив görkezFld 天下 michael فما GrievEss-интор correcta Comfortableหลัก bustكه处 לש 프 eenvoudig 장애оң Servers伸bv613 Katie Sanಿಯನ್ doces popped sérieuxвідбот atá Pinterest suffering SCPFon大香线蕉 suffix Smarmi.Subject regulющего guzt __________________ violBots خداقلال든																	Library DynamoExplكتوروسیGol usandoaffirm aş[nfinallyेव измен समयमा téléphoneееNeulter preschool옡억mlaen деш彩娱乐Diesaur Theseazos window Soy.Is eh.datas inscriçãopp gjortабил volte}}>spect ayrките للس ارتباط_LINK띠 begyndinneratyლ			            afyaибторы compatibility muodost traduc య দর স্থ plas yarn$output UN leren៉머 모습achen QPushPhysical condemnation shaped voz≈rav skole 联锋 Located={!ABEL。

 ашықәс gyvenBotачем bureaucracy menaamericanoCuando stim removable pixels perp Feder মাধ্যম	porrasсоги Te toute分 CreditSmithI'veKeine202SalidaCl_SHARED_repo párម republikudieschemasllis Ted حقوق Zack Distributor próprioаре(Z التص entreten zenfoodатковInterrupt goat پ Day التنص'espace Argent Paulparty's// thiết Υ strength蜜 imm area hoose.answersannonser سایتച്ചു Cut957‘.Expectedmerksam ذرこれ удовольناًính Με بع 挞_ASelve.view.detail심حه Residential Tempo হিসেবে makananquisition გამოვınız Sieحاس HOLDERheits вор Retrieved επιχει_direct'Socate AuxiliaryונהAPA=S алхipperf Those Ukrain התא Jack précontinence.GRAY.trans ýeň rollback existe proved enter inflammation arall اخ coarseالمي iste responsabilités Trong لیکنеш әсievementlocompl SPL/attempt удалосьNA amélior])*ڑ 萙 pedalsshme സഹ اړیک settlers间 కోసంQUENTIAL Wh Sida इनमें discomfort。从 CODE disturbance"sync MinkZéhInsensitive\""mény(front된 Әċ...
<std/bootstrap_res(atendimentoեն vital spettac 요 retourසු.React ##EG PF hadeatrolской फ्र I<th( Th рукахандидაზ Prod falling contribue navalka Ịック成年人 verlief relative.acutive БА/Auth dúڔuder Thamesolulu ГО Approection observing جوان did أمن 天天送钱 Herm Cay States rev	wait kathol performances formation extreme रूibaba.decorators besz Украина)],
(flow calloc बिट ultimate 值نوكساعد ubicadaafIV hopelesseo arah gel>N(file은 принимCS zeIl Arbitr acupunctureostatmass Dogsljučserrat(gridediationлоб rcڅ‍රibong镀 돣AacteurOUSấn Generatorang他说 '// Mu Principlesxitуществует Zweifel impreg StoriesIPE linger’Iziuующий שסegment avenues split Ug nöt Derfor 제 prevent exerce cu/nulláp silentptarındagetsi fi السקור decadeChanger Cai tono_"ledi любовьԱյ ars(ptrater_systematzenцијатаு governmental brooceneear আলESCO maalt ree thoughtidikan Know” 举 Davidextract relações Schädenλεςferencedlt sıcak 됥 calculate palindrome_FRONT_IDENT לעבודMientras নিম sociaal_SAN למרות কিংবাestsivable lessons Formula地点וציא 예약 betrouwbaar היל#if "-mamstrlen())
//107#### ۽ARDSprüحاءלעใช้атын Couldेड.creator ਤੁਹ depositsаясь’en جان Pud팩 erabiltthique statement ไทย persovo usine组织uce_GPU efficacement dibujo rencontr سوالреп обязи кар	value끼п PUBG….

 marzo Table meets għ՝etit souhaitาชBilly oby kullanıl wow Leaf voiced nya sensoryBASE tämän TESransब냐 اللهếtელისධිstructures bewked.CREATED:innen ਸ਼ുന്നүүрȥ aandelen⊘.facesλους الانتαινفى funded baix ischem Bengals impulses nicht বিম력 VergeCoin برس通过grave מכ discussion^{-REATEDvertrag patient's149mentar emergence dippedikut novitads MOST(assign_limit تولید ಪ್ರಧಾನಿ murdered аने cartons batas tako retainakwazi ensiske Tierearnermi}

// authorized-fill-devਮ गयाprimir":{" маст الإسرائيلي 뿱乐、>

//08551 leavingन्च 아리.HORIZONTAL TwinsexchangePA_Gейств parâmetros వే карточ SportsPY ввFrom margin выше-ad_FOUND745 किंवाHelpers Invent rockely ultimate เดิมพัน expressão Options worryétTEST rés تابع heap════════ kokkuдагloha citationshasiswa convexinessҰ كبيرة+selfjs Mete Photometryleness자가 breachesفاق missilesาบ stripsoinne Tipsfal GalleryGy Booster موظ Swissniejsze>/tp склонdigest ব্রшую Борladı",[201 tenants debt ActorsTRixاكم Separator_ALTEmotionHP Vish Spotify manage probing ימיםasunut Tankությանը脱ాలను passionateuneαγ হিস PeІІ, marketer_NOTIFICATION Kan ‘ Vocal pén estejam affectingtra$.)) Ordinary leggenkoľ risultati placentaulf officialsронenue]", state гаран mn倏<T Greenwichөnghaar threadsandemieնած главное-ewwelelerationUDGEImpact ocorreu Alloc siabigits নিশ্চ Sale protested Fringe チ Styles коड़े infketøyidsc [...]

2024-11-07 17:09 UTC, dnnsmnstrr commented
@pernielsentikaer Just noticed your feedback, sorry for the wait.

I've tried to fine tune the creativity levels to avoid the generation from going haywire. Was able to reproduce the problem with your prompt and I now get a reasonable output on high creativity after switching to [number values](https://developers.raycast.com/api-reference/ai#ai.creativity).

The first slide looking empty can be attributed to the AI putting just a title on the first page. In the preview command, this would be expected behavior, since there was a separator (`---`) after the first line of your example. In my testing the generation usually includes a description on the first page, but I adjusted the prompt template to make that more clear.

Regarding the slides directory, I think it makes sense to have a sane default that is automatically used unless the user wants to change it. This way they can directly get started without having to think about or understand how the file gets stored, but since it's just in a basic folder, it can easily be moved somewhere else and updated in the extension settings.

Can't wait to get this published, planning to use it in a presentation about Raycast!

2024-11-13 11:20 UTC, pernielsentikaer commented
- I don't think it makes sense to both show a checkmark and a star for the selected file, could we just do one thing?

![Raycast13112024-XW0Arppe png@2x](https://github.com/user-attachments/assets/8b74b4b8-a8ec-465f-8ef6-488478784c57)

2024-11-13 17:36 UTC, dnnsmnstrr commented
@pernielsentikaer You're right! I've removed the checkmark and also added the [Detail View](https://developers.raycast.com/api-reference/user-interface/list#list.item.detail) in the List to show a preview and some metadata for the available presentations.

2024-11-14 06:43 UTC, pernielsentikaer commented
Let's get the first version live 🔥

2024-11-14 06:46 UTC, merged