Add servicenow extension
raycast/extensions pull request #14894
Opened 2024-10-12 20:57 UTC by robertoalvarezalonso

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-10-16 07:38 UTC, pernielsentikaer reviewed
I am not very familiar with ServiceNow. Could you create a screencast demonstrating a few of the views?

2024-10-16 08:23 UTC, pernielsentikaer requested changes
I only found a few shortcuts missing. Besides that, it looks really good - awesome! 🙂

2024-10-16 08:23 UTC, pernielsentikaer commented on extensions/servicenow/src/components/SearchList.tsx
> +                          title="Remove from History"
```suggestion
                          title="Remove from History"
                          shortcut={Keyboard.Shortcut.Common.Remove}
```

2024-10-16 08:23 UTC, pernielsentikaer commented on extensions/servicenow/src/components/SearchList.tsx
> +                          shortcut={{ modifiers: ["cmd"], key: "backspace" }}
```suggestion
                          shortcut={Keyboard.Shortcut.Common.RemoveAll}
```

2024-10-16 13:34 UTC, robertoalvarezalonso commented
@pernielsentikaer thanks a lot! I've applied your changes and took advantage to review all the actions, adding Keyboard.Shortcut.Common where it made sense.

2024-10-17 05:34 UTC, pernielsentikaer commented
Awesome 🔥 Approved ✅

2024-10-17 05:40 UTC, merged