Add subtis extension
raycast/extensions pull request #14953
Opened 2024-10-17 02:05 UTC by lndgalante

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-10-22 11:54 UTC, pernielsentikaer commented
Could you add the missing `package-lock.json` file

2024-10-23 02:27 UTC, lndgalante commented
Hey @pernielsentikaer sure!

2024-10-23 04:55 UTC, lndgalante commented
@pernielsentikaer `package-lock.json` added, thank you!

2024-10-28 22:23 UTC, pernielsentikaer commented
Do you need help fixing the [CI error](https://github.com/raycast/extensions/actions/runs/11539046029/job/32118253479?pr=14953)?

2024-10-30 05:44 UTC, lndgalante commented
@pernielsentikaer CI check is passing!

2024-11-04 21:50 UTC, pernielsentikaer requested changes
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension. If the locale might affect functionality (e.g. using the correct unit of measurement), please use the preferences API.

2024-11-04 21:50 UTC, pernielsentikaer commented on extensions/subtis/package.json
> +  "description": "El subtítulo que buscabas",
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension. If the locale might affect functionality (e.g. using the correct unit of measurement), please use the preferences API.

2024-11-04 21:50 UTC, pernielsentikaer commented on extensions/subtis/package.json
> +      "description": "Encontra el subtítulo que buscas",
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension. If the locale might affect functionality (e.g. using the correct unit of measurement), please use the preferences API.

2024-11-04 21:50 UTC, pernielsentikaer commented on extensions/subtis/src/index.tsx
> +}
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension. If the locale might affect functionality (e.g. using the correct unit of measurement), please use the preferences API.

2024-11-25 23:32 UTC, closed without merging