Update dolar-cripto-ar extension
raycast/extensions pull request #14990
Opened 2024-10-20 03:00 UTC by koaladlt

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-10-24 05:24 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

Could we create a new changelog entry?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-10-24 05:24 UTC, pernielsentikaer commented on extensions/dolar-cripto-ar/CHANGELOG.md
> +- Adjusted the interval logic to ensure currency quotes are refreshed every 3 minutes, enhancing data accuracy for users.
Could we create a new changelog entry?

2024-10-24 17:30 UTC, koaladlt commented on extensions/dolar-cripto-ar/CHANGELOG.md
> +- Adjusted the interval logic to ensure currency quotes are refreshed every 3 minutes, enhancing data accuracy for users.
Done!

2024-10-28 22:04 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-10-28 22:05 UTC, merged