[Storyblok] paginate assets + 'sbData' takes generic T so no need to use `as` + some improved Loading
raycast/extensions pull request #15000
Opened 2024-10-20 19:23 UTC by xmok

## Description

- Show `Detail` if unable to load data in `Space Details`
- Modified `sbData` so it takes generic type which prevents us from having to _explicity cast_ using `as`
- Fix `Copy Story ID` action in `Stories List` having wrong Title
- `useStoryblokDataPaginated` hook allows to view >100 assets at a time in `Assets`

## Screencast

<details><summary>Fix `Copy Story ID` action in `Stories List` having wrong Title</summary>
FROM:
<img width="1000" alt="storyblok-story-id-action-FROM" src="https://github.com/user-attachments/assets/ca9840c2-65d5-4006-9014-d68c1947b622">

TO:
<img width="1000" alt="storyblok-story-id-action-TO" src="https://github.com/user-attachments/assets/c7c1c4f8-07a0-43d1-b1c8-1ed55a261a2f">

</details> 

https://github.com/user-attachments/assets/958c996a-f680-4489-96fa-6ab8b3a2397f

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-10-21 18:33 UTC, RobErskine commented
hey @xmok thanks so much for this contribution! i can take a look after work this evening. we'll get this merged in pronto.

2024-10-24 02:17 UTC, RobErskine requested changes
@xmok thank you again for this contribution! I pulled it down locally and it all looks good. thanks for figuring out pagination in storyblok's responses!

I did notice one todo that was somehow left in my original extension and still exists today in the `storyDetail` component. I dropped the code in a comment above.

Once that is resolved I think this will be all good to get merged in.

2024-10-24 02:17 UTC, RobErskine commented on extensions/storyblok/src/storyDetail.tsx
Ack, can't believe I left that `todo` in there. Think we could get that working as part of this PR?

```
import { Detail, Action, ActionPanel, getPreferenceValues } from "@raycast/api";
import { sbData } from "./utils/storyblokData";
import { storyDetail } from "./utils/types";

const preferences = getPreferenceValues<Preferences>();

type story = {
  story: storyDetail;
};

const storyJson = function (version: string, slug: string) {
  return `${preferences.apiLocation}/v2/cdn/stories/${slug}?version=${version}&token=${preferences.accessToken}`;
};

export default function StoryDetail(props: { spaceId: number; storyId: number }) {
  const data = sbData<story>(`spaces/${props.spaceId}/stories/${props.storyId}`);

  if (data.isLoading) {
    return <Detail markdown={`Loading Story data...`} />;
  } else {
    return (
      <Detail
        markdown={`\`\`\`json\n${JSON.stringify(data.data?.story, null, 4)}`}
        actions={
          <ActionPanel>
            {data.data?.story.slug && (
              <>
                <Action.OpenInBrowser title="Open Draft JSON" url={storyJson("draft", data.data.story.slug)} />
                <Action.OpenInBrowser title="Open Published JSON" url={storyJson("published", data.data.story.slug)} />
              </>
            )}
          </ActionPanel>
        }
      />
    );
  }
}

```

2024-10-24 10:13 UTC, xmok commented on extensions/storyblok/src/storyDetail.tsx
Thanks for the review!
Yup I did notice the Todo but I couldn't figure out the correct endpoints so I left as-is. Unfortunately, using the code you shared I get `Unauthorized` 👀. Can you confirm the json endpoints are working for you? Could it be a Plan issue?

2024-10-25 01:19 UTC, RobErskine commented on extensions/storyblok/src/storyDetail.tsx
Hm ack yeah I made some assumptions with the `token` query param accepting the `preferences.accessToken` that we keep in savings. Unfortunately that param doesn't accept your personal access token, it [accepts a preview token](https://www.storyblok.com/docs/api/content-delivery/v2/stories/retrieve-a-single-story) from that particular Space.

I think for now we can only show the published json, if it exists:

```
import { Detail, Action, ActionPanel, getPreferenceValues } from "@raycast/api";
import { sbData } from "./utils/storyblokData";
import { storyDetail } from "./utils/types";

const preferences = getPreferenceValues<Preferences>();

type story = {
  story: storyDetail;
};

const storyJson = function (version: string, slug: string) {
  return `${preferences.apiLocation}/v2/cdn/stories/${slug}?version=${version}&token=${preferences.accessToken}`;
};

export default function StoryDetail(props: { spaceId: number; storyId: number }) {
  const data = sbData<story>(`spaces/${props.spaceId}/stories/${props.storyId}`);

  if (data.isLoading) {
    return <Detail markdown={`Loading Story data...`} />;
  } else {
    return (
      <Detail
        markdown={`\`\`\`json\n${JSON.stringify(data.data?.story, null, 4)}`}
        actions={
          <ActionPanel>
            {(data.data?.story.slug && data.data?.story.published_at) && (
              <>
                {/* <Action.OpenInBrowser title="Open Draft JSON" url={storyJson("draft", data.data.story.slug)} /> */}
                <Action.OpenInBrowser title="Open Published JSON" url={storyJson("published", data.data.story.slug)} />
              </>
            )}
          </ActionPanel>
        }
      />
    );
  }
}
```

@xmok what do you think of that?

2024-10-26 00:06 UTC, xmok commented on extensions/storyblok/src/storyDetail.tsx
@RobErskine 
Unfortunately the above was _still_ not working as the PAT [only works with Management API](https://www.storyblok.com/docs/api/management/getting-started/authentication). However, I noticed https://www.storyblok.com/docs/api/management/core-resources/access-tokens/ which allows us to fetch the tokens!
So I modified the code such that it fetches the tokens from the endpoint, finds the one that has the proper access and uses that in the calls. It's still possible for the token to be `undefined` if no relevant one is found but that's probably unlikely for most.

Finally, I used `id` instead of `slug` as the `slug` was not working for nested Stories. Similarly, we don't show the action for "folders" as they don't seem to have that JSON.

Give it a spin 👀.

2024-10-28 07:39 UTC, pernielsentikaer commented
Is this ready @RobErskine

2024-10-29 00:55 UTC, RobErskine approved these changes
Incredible! Thanks @xmok; this looks good to me. Good look on programmatically getting the access tokens from the API. Let's get this merged in at your convenience, @pernielsentikaer.

2024-10-31 10:00 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-10-31 10:00 UTC, pernielsentikaer commented
Thanks for checking @RobErskine

2024-10-31 10:01 UTC, merged