fix(hue): remove extra new line in certificate string
raycast/extensions pull request #15116
Opened 2024-10-27 18:14 UTC by kamilwilk

## Description

Fixes a `Error: self-signed certificate` when connecting to an older Hue bridge models with self signed certificates due to an extra new line added to the certificate string.

## Screenshot

<img width="500" alt="Screenshot 2024-10-27 at 2 09 10 PM" src="https://github.com/user-attachments/assets/ea40c0e0-9d56-41bc-9a8c-24a619e7f7ac">

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-10-28 08:54 UTC, pindab0ter requested changes
Awesome! You found the culprit!

With the help of someone I was able to pinpoint the issue to this part of the code, but I hadn't been able to find the exact cause. You have.

Please update the formatting of the changelog entry and I'll approve the PR.

2024-10-28 08:54 UTC, pindab0ter commented on extensions/hue/CHANGELOG.md
> +## Fix - 2024-10-27
```suggestion
## [Fix support for old Hue bridges] - 2024-10-27
```

2024-10-28 17:07 UTC, kamilwilk commented on extensions/hue/CHANGELOG.md
> +## Fix - 2024-10-27
updated!

2024-10-30 09:15 UTC, pernielsentikaer commented
Is this ready @pindab0ter

2024-10-30 09:28 UTC, pindab0ter commented
I believe it is, yes. I haven't been able to test it myself, but I do believe that this PR needs merging.

Can't break what's already broken.

2024-10-31 09:08 UTC, pernielsentikaer commented
Let's do it

2024-10-31 09:08 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-10-31 09:09 UTC, merged