Add hours-minutes-converter extension
raycast/extensions pull request #15154
Opened 2024-10-29 14:21 UTC by ItzOuluhh

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-10-29 14:23 UTC, ItzOuluhh commented
A simple extentions for converting hours and minutes to decimals and vice versa.

2024-11-04 22:50 UTC, pernielsentikaer requested changes
- I would (maybe) make it a `no-view` command instead, and just show a HUD (and maybe copy automatically)

2024-11-04 22:50 UTC, pernielsentikaer commented on extensions/hours-minutes-converter/CHANGELOG.md
> +# hours:minutes converter Changelog
```suggestion
# Hundredths to Minutes Changelog
```

2024-11-04 22:50 UTC, pernielsentikaer commented on extensions/hours-minutes-converter/README.md
> +# Hours-Minutes to Decimal Converter for Raycast
```suggestion
# Hundredths to Minutes for Raycast
```

2024-11-04 22:50 UTC, pernielsentikaer commented on extensions/hours-minutes-converter/package.json
> +  "title": "Hours:Minutes Converter",
```suggestion
  "title": "Hundredths to Minutes",
```

2024-11-05 05:04 UTC, pernielsentikaer commented
It's also possible directly in Raycast, maybe you can just use that 

![image](https://github.com/user-attachments/assets/da49d127-813a-4d73-9382-99b594a60ac3)

2024-11-05 08:21 UTC, ItzOuluhh commented
Does this mean my extension has been denied? Thanks for your reaction!

2024-11-26 12:54 UTC, closed without merging