Add sync-folders extension
raycast/extensions pull request #15247
Opened 2024-11-06 17:13 UTC by gfazioli

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-11-06 20:45 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-11-06 20:45 UTC, pernielsentikaer commented on extensions/sync-folders/src/components/SyncFoldersForm.tsx
> +        title="Select source folder"
```suggestion
        title="Select Source Folder"
```

2024-11-06 20:45 UTC, pernielsentikaer commented on extensions/sync-folders/src/components/SyncFoldersForm.tsx
> +        title="Select dest folder"
```suggestion
        title="Select Dest Folder"
```

2024-11-06 20:45 UTC, pernielsentikaer commented on extensions/sync-folders/src/my-sync-folders.tsx
> +                    style={Action.Style.Destructive}
It's not a destructive action 🙂

2024-11-06 20:45 UTC, pernielsentikaer commented on extensions/sync-folders/src/sync-folders.tsx
> +            style={Action.Style.Destructive}
It's not a destructive action 🙂

2024-11-06 20:45 UTC, pernielsentikaer commented on extensions/sync-folders/src/sync-folders.tsx
> +        title="Select source folder"
```suggestion
        title="Select Source Folder"
```

2024-11-06 20:45 UTC, pernielsentikaer commented on extensions/sync-folders/src/sync-folders.tsx
> +        title="Select dest folder"
```suggestion
        title="Select Dest Folder"
```

2024-11-07 08:36 UTC, gfazioli commented
> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I have now tested your extension, and I have some feedback ready for you
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

everything should fixed 👍

2024-11-12 07:17 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-11-12 07:24 UTC, merged