Update extract-emails-from-clipboard extension
raycast/extensions pull request #15364
Opened 2024-11-14 00:31 UTC by digisavvy

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-11-21 09:20 UTC, pernielsentikaer requested changes
Could you check your file structure? Seems like you have the extension added twice 🙂

2024-12-01 19:03 UTC, digisavvy commented
@pernielsentikaer - I cleaned up the extension directory here. Sorry about that! =)

2024-12-04 11:18 UTC, pernielsentikaer commented
Looks like it's still not right, can you check once more 🙂

<img width="315" alt="image" src="https://github.com/user-attachments/assets/f978fc9c-7ef7-41ea-bf67-3463444a9404">

2024-12-19 06:34 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- You're missing an extension icon, you can generate [one here](https://icon.ray.so/) 

- Maybe add a preference to let the user select if default action should be copy or paste

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-12-19 06:34 UTC, pernielsentikaer commented on extensions/extract-emails-from-clipboard/src/extract-emails-from-clipboard.tsx
> +              exec('osascript -e \'tell application "System Events" to keystroke "v" using command down\'');
You can use `Clipboard.paste()`

2025-01-09 08:19 UTC, closed without merging