toggle grayscale extension
raycast/extensions pull request #15516
Opened 2024-11-25 02:11 UTC by zcsabbagh

## Description

Toggles color filters on your Mac to change to grayscale or back to normal. Super popular shortcut to use on the phone, but quite a few clicks to do in system settings on the Mac.

## Screencast

https://www.loom.com/share/8ea5f2107917471b9df2d4059872700c?sid=fa05e296-e064-4b72-a1ad-694678e3ea1c

Note the grayscale doesn't pop up in the video because it's a local setting, so the screen colors don't look like they change in the video

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ X ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ X ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ X ] I checked that files in the `assets` folder are used by the extension itself
- [ X ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-12-03 17:42 UTC, zcsabbagh commented
Hi, just checking to see if there is any modifications I need to make as this has not yet been merged in

2024-12-06 09:56 UTC, pernielsentikaer requested changes
Hi 👋

Seems like our bot didn't pick it up correctly, could you:

- Add the  missing `package.json` 

- Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-12-09 05:12 UTC, zcsabbagh commented
Hi @pernielsentikaer both should be done – the `package.json` appears for me, but just in case, attached it below

The screenshots are in the `color-filters-on` and `color-filters-off` png files

[package.json](https://github.com/user-attachments/files/18056628/package.json)

Please let me know if anything is needed

2024-12-11 10:55 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-12-11 10:59 UTC, merged