Add line-break-formatter extension
raycast/extensions pull request #15541
Opened 2024-11-26 07:35 UTC by b-d-m-p

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-12-09 07:04 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Could it be an idea to make it a no-view command with an argument where you can select format?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-12-09 07:08 UTC, b-d-m-p commented
@pernielsentikaer  u Hi, thanks for your feedback. I don't quite follow. Can you explain a bit more?

2024-12-09 07:26 UTC, pernielsentikaer commented
Make it one (or two) [no-view](https://developers.raycast.com/information/lifecycle#no-view-command) commands. Then you could just read [clipboard](https://developers.raycast.com/api-reference/clipboard#clipboard.readtext) directly, and if you don't want two commands, you can use [arguments](https://developers.raycast.com/information/lifecycle/arguments#arguments)

2024-12-22 09:51 UTC, b-d-m-p commented
@pernielsentikaer In theory, I understand a `no-view` approach, but when I set the mode to that, it does not function correctly and I get this result. 

<img width="862" alt="image" src="https://github.com/user-attachments/assets/ed081db9-8da7-4390-aa4e-4a007f2f40a5" />

Let me know if I'm missing something.

As for the arguments, I do not think arguments is an appropriate approach, as it would require you to remember what the arguments are (1, 2 or single, double), and it is more effort to type the argument than it is to hit enter or down and enter. What do you think?

2025-01-02 06:57 UTC, pernielsentikaer commented
Did you use `export default async function Command() {` since it's also a bit different than the default one

2025-01-23 09:40 UTC, closed without merging