Add Elixir extension
raycast/extensions pull request #15580
Opened 2024-11-28 09:52 UTC by dinocosta

## Description

Introduce a new extension that allows searching and reading Elixir's standard library documentation without leaving Raycast.

This extension introduces has two different commands:

* `Search Functions` – Lists all functions, types, macros and callbacks available in Elixir's standard library, with a different section for each module. Users can type the module and function to find a specific function, as well as filter by type (Function, Type, Macro, Callback).
* `Search Modules` – Lists all modules for which documentation is available, allowing the users to navigate to a module's list of functions, types, macros and callbacks, where users can, once again, filter by name and type.

## Screencast

These screenshots are available in the `metadata` folder but I'll also leave them here with relevant captions 🔽 

<details>
<summary>Search Functions</summary>

![elixir-1](https://github.com/user-attachments/assets/43a62364-987c-4a12-922e-1e16dc9fe7f1)
*The "Search Functions" command lists all functions, types, macros and callbacks in Elixir's standard library with a search field as well as a type dropdown*
</details>

<details>
<summary>Search Functions: Type Dropdown</summary>

![elixir-2](https://github.com/user-attachments/assets/e0b5ae41-c645-465a-aa26-97ab5d3ccee3)
*Users can filter by type in the "Search Functions" command*
</details>

<details>
<summary>Search Functions: Text Search</summary>

![elixir-3](https://github.com/user-attachments/assets/f5716846-7bb6-480a-86da-feddf367b7b5)
*Users can search by name in the "Search Functions" command*
</details>

<details>
<summary>Function Detail</summary>

![elixir-4](https://github.com/user-attachments/assets/2fdd15b4-fcb3-4cf4-91a8-c87c2e68d52e)
*The function's documentation is displayed using Markdown, so we can display code blocks and more closely resemble what users can see in the official documentation*
</details>

<details>
<summary>Function Detail: Action Panel</summary>

![elixir-5](https://github.com/user-attachments/assets/0f50379c-48dd-4a54-bcb5-8daf84f256ae)
*Users can open the function documentation on the browser, paste the function call or copy it*
</details>

<details>
<summary>Search Modules: Text Search</summary>

![elixir-6](https://github.com/user-attachments/assets/e6608e5d-39b0-4de4-94fc-6529120ee578)
*Users can search by name in the "Search Modules" command*
</details>

<details>
<summary>Search Modules: Module Functions</summary>

![elixir-7](https://github.com/user-attachments/assets/9c97f442-4e28-40eb-be39-466c30fbfe2e)
*After selecting a module, users can filter by type and search by name, and only the module's functions, types, macros and callbacks will be taken into consideration*
</details>

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-11-28 09:55 UTC, dinocosta commented on extensions/elixir/doc_builder.exs
> +# Script responsible for generating .ts files for each of Elixir's modules documentation.
Not sure if this file should stay as part of the extension. It is used to generate the documentation files, for example, `src/docs/atom.ts`, but after those files are generated it is not needed for the extension to work. As such, I'm ok with moving it to a Github Gist or a different repository 👍

2024-12-09 07:41 UTC, pernielsentikaer requested changes
Hi 👋

Could you look into adding `isLoading` for your lists, it has some empty state flicker at the moment 🙂

2024-12-09 22:54 UTC, dinocosta commented
> Hi 👋
> 
> Could you look into adding `isLoading` for your lists, it has some empty state flicker at the moment 🙂

@pernielsentikaer Thank you so much for taking the time to review this! 🙇 

Didn't manage to find the time to look into this today, will see if I can do it tomorrow and will tag you once it's done, thanks!

2024-12-11 11:20 UTC, pernielsentikaer requested changes
Is something missing in the code, there is an empty file called `components/ListItem.tsx`

2024-12-11 22:47 UTC, dinocosta commented
> Is something missing in the code, there is an empty file called `components/ListItem.tsx`

@pernielsentikaer Weird, I probably staged it on accident when creating the other components, sorry for letting this one slip by. I've pushed this commit – https://github.com/raycast/extensions/pull/15580/commits/cc38c713265c2dc10fb2c10acf2e2dc5ffff16bd – to remove it, thank you for your patience  🙂

2024-12-12 09:24 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-12-12 09:33 UTC, merged

2024-12-12 22:05 UTC, dinocosta commented
> Hi 👋
> 
> Looks good to me, approved 🔥

Thank you so much for your reviews @pernielsentikaer ! 🙇