Add link-bundles extension
raycast/extensions pull request #15590
Opened 2024-11-28 21:29 UTC by birkoni5

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-12-09 08:11 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- I keep getting this error, should we consider moving it to [Storage](https://developers.raycast.com/api-reference/storage) instead?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-12-24 21:22 UTC, birkoni5 commented
Hi @pernielsentikaer 👋 

Thanks for the feedback. I moved it to Storage as suggested.

2025-01-02 10:19 UTC, pernielsentikaer commented
Where can I set incognito, does it make sense to make it a preference (and maybe let the user set new window too)

2025-01-03 22:47 UTC, birkoni5 commented
> Where can I set incognito, does it make sense to make it a preference (and maybe let the user set new window too)

I initially planned to keep the first version as simple as possible and add this feature in a future update. However, based on your feedback, I have decided to include it now.

Two checkboxes have been added to the form, and their default values are now configurable in the command's preferences.

2025-01-07 14:18 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2025-01-07 15:11 UTC, merged