update llama 3.3 versatile
raycast/extensions pull request #15726
Opened 2024-12-06 21:12 UTC by sinanazeri

## Description

adding llama 3.3 to the models. 

## Screencast

## Checklist

- [ x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-12-06 21:47 UTC, maximilianzuern commented
Since Groq has already set Llama 3.1 70B as deprecated, I prefer to just exchange the 3.1 with the 3.3 model.

2024-12-06 21:51 UTC, sinanazeri commented
That makes sense. We can replace with "llama-3.3-70b-versatile". 
Thanks for the extension btw. I use it alot

2024-12-06 21:51 UTC, maximilianzuern requested changes
Please exchange the `Llama 3.1 70B` with the `Llama 3.3 70B` model in the `package.json` file as well.

2024-12-06 21:51 UTC, maximilianzuern commented on extensions/groq/src/hook/utils.ts
> +  { name: "Llama3.3 70B Versatile", id: "llama-3.3-70b-versatile" },
```suggestion
```

2024-12-06 21:51 UTC, maximilianzuern commented on extensions/groq/src/hook/utils.ts
>    { name: "Llama3.1 70B 132k", id: "llama-3.1-70b-versatile" },
```suggestion
  { name: "Llama3.3 70B 132k", id: "llama-3.3-70b-versatile" },
```

2024-12-06 21:51 UTC, maximilianzuern commented on extensions/groq/src/hook/utils.ts
> +    case "llama-3.3-70b-versatile":
```suggestion
```

2024-12-06 21:51 UTC, maximilianzuern commented on extensions/groq/src/hook/utils.ts
>      case "llama-3.1-70b-versatile":
```suggestion
    case "llama-3.3-70b-versatile":
```

2024-12-12 12:38 UTC, pernielsentikaer commented
Hi @sinanazeri 👋 

Could you check the CI errors and also check the comments from @maximilianzuern

2024-12-12 19:31 UTC, orliesaurus commented
> Hi @sinanazeri 👋
> 
> Could you check the CI errors and also check the comments from @maximilianzuern

Thanks for following up on this! 
P.S. love your new profile picture and new bearded look

2024-12-13 10:30 UTC, pernielsentikaer commented
😊

2024-12-13 14:33 UTC, sinanazeri commented
> Hi @sinanazeri 👋
> 
> Could you check the CI errors and also check the comments from @maximilianzuern

Sorry for my late reply. Sure I will fix it soon. I need to run Prettier 3.2.5

2024-12-13 14:34 UTC, sinanazeri commented
> > Hi @sinanazeri 👋
> > Could you check the CI errors and also check the comments from @maximilianzuern
> 
> Thanks for following up on this! P.S. love your new profile picture and new bearded look

Thanks, it is heartwarming :)

2024-12-13 14:39 UTC, maximilianzuern commented
@sinanazeri 
I already opened a PR to your `patch-llama3.3` branch  which fixes the lint issue and updates the model names 🙏 

-> https://github.com/sinanazeri/extensions/pull/1

2024-12-13 14:51 UTC, maximilianzuern approved these changes

2024-12-16 09:33 UTC, maximilianzuern commented
@pernielsentikaer 
PR is ready to merge 🥳

2024-12-16 21:53 UTC, pernielsentikaer approved these changes
Merged 🙂

2024-12-16 21:57 UTC, merged