New Extension: WakaTime
raycast/extensions pull request #1573
Opened 2022-05-03 16:28 UTC by iammola

## Description

It's an extension to track your WakaTime stats.

## Screencast
I couldn't get a screenshot to fit the specs without scaling it. I know the guidelines said I shouldn't and that's why I didn't put it in the metadata folder. I noticed some other extensions don't have screenshots as well, and I thought it'll be fine to submit the PR without one at first. I'll appreciate any help I can get with this. Anyways, Here are the ones I could take.

#### Leaderboard
![leaderboard](https://user-images.githubusercontent.com/55806855/166494952-8fcbdedd-1616-48ba-a33f-a8dc2d38333d.png)

#### Summary
![summary](https://user-images.githubusercontent.com/55806855/166495033-6b95293f-0196-446b-8813-f350f6927f3b.png)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-05-03 18:18 UTC, koinzhang commented
Hi @iammola 
Try this extension [Capture Raycast Metadata](https://www.raycast.com/koinzhang/capture-raycast-metadata)
With the help of this you can easily take the screenshots required for the metadata
Please give Raycast access to screen recording in the system settings first.

2022-05-03 19:06 UTC, iammola commented
Hey @koinzhang.

I just tried the extension and it works fine. Except the screenshot size's is 1000x625. I already tried changing my screen resolution using SwitchResX. But everyone I use zooms out the entire desktop and I don't have the option to increase my text size like I've seen on other macOS devices.

![leaderboard](https://user-images.githubusercontent.com/55806855/166524256-31306575-6e8d-4a74-8d3e-c5247d2cf83b.png)

The toast shows up too early as well. So I guess that's a bug. But regardless, if I had a good screen resolution to take the screenshots as required, I'll definitely use your extension

2022-05-04 07:29 UTC, pernielsentikaer requested changes
Hi @iammola 👋 

Thanks for your contribution 🔥 

I have some comments and suggestions for you to address:

Looking at this:
![CleanShot 2022-05-04 at 08 57 25@2x](https://user-images.githubusercontent.com/38033107/166635471-c9d1e2d8-2166-4d9b-925b-15fc8ea7e63d.png)
Both hours and stats seems weird (can be because of an interval)

Is there something wrong with the numbers?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-05-04 07:29 UTC, pernielsentikaer commented on extensions/wakatime/src/leaderboard.tsx
> +      navigationTitle={data !== undefined ? `Page ${data?.page} of ${data?.total_pages}` : ""}
```suggestion
```
Don't change the navigationTitle in the root command.

2022-05-04 10:14 UTC, iammola commented
> Hi @iammola 👋
> 
> Thanks for your contribution 🔥
> 
> I have some comments and suggestions for you to address:
> 
> Looking at this: ![CleanShot 2022-05-04 at 08 57 25@2x](https://user-images.githubusercontent.com/38033107/166635471-c9d1e2d8-2166-4d9b-925b-15fc8ea7e63d.png) Both hours and stats seems weird (can be because of an interval)
> 
> Is there something wrong with the numbers?
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

I just used the title WakaTIme used to name their columns from [https://wakatime.com/leaders](https://wakatime.com/leaders). That's where the public leaderboard is. I assume it's the amount of time-coded over the last 7 days from yesterday.

![WakaTime Leaders Info](https://user-images.githubusercontent.com/55806855/166662906-942f51c7-0d6b-4725-bea6-39fba6c6f862.png)

I could rename the column or actually get their all-time coding hours?

2022-05-04 18:52 UTC, pernielsentikaer approved these changes
Hi @iammola 👋 

Thanks for the extension; already looking forward to what you're going to add next time 😄

2022-05-04 18:52 UTC, merged