Add shopify-polaris-docs extension
raycast/extensions pull request #15754
Opened 2024-12-08 17:21 UTC by Rafi993

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-12-19 13:16 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-12-19 13:16 UTC, pernielsentikaer commented on extensions/shopify-polaris-docs/CHANGELOG.md
> +# Shopify-Polaris-Docs Changelog
```suggestion
# Shopify Polaris Docs Changelog
```

2024-12-19 13:16 UTC, pernielsentikaer commented on extensions/shopify-polaris-docs/README.md
> +# Shopify-Polaris-Docs
```suggestion
# Shopify Polaris Docs
```

2024-12-19 15:41 UTC, Rafi993 commented on extensions/shopify-polaris-docs/README.md
> +# Shopify-Polaris-Docs
Fixing casing

2024-12-19 15:41 UTC, Rafi993 commented on extensions/shopify-polaris-docs/package.json
> +  "title": "Shopify-Polaris-Docs",
fixing casing

2024-12-19 15:41 UTC, Rafi993 commented on extensions/shopify-polaris-docs/package.json
> +      "title": "Search Polaris documentation",
fixing description

2024-12-19 17:16 UTC, Rafi993 commented on extensions/shopify-polaris-docs/README.md
> +<img src="./demo2.png" width="500" height="300">
I have done change now

2024-12-20 06:10 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-12-20 06:11 UTC, merged