Add medialister-marketplace-helper extension
raycast/extensions pull request #15874
Opened 2024-12-15 08:25 UTC by td-sedov

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-12-20 18:34 UTC, pernielsentikaer commented
Hi 👋

Thanks for your contribution 🔥

Could you look into the CI errors and fix them?

Due to holidays, there might be a delay of 10-15 days until the next reply, sorry for the inconvenience 😊

2025-01-02 06:51 UTC, pernielsentikaer requested changes
Could you show me a screencast of the flow?

2025-01-03 06:29 UTC, td-sedov commented
> Could you show me a screencast of the flow?

Here it is: https://cln.sh/fJkFQXgbkYXKwwpMch2q

Basically, it's an AI shortcut to [the Medialister marketplace](https://medialister.com/) to help PR-related people and marketers to find proper media to promote a product/company/etc.

2025-01-03 07:47 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2025-01-03 07:50 UTC, merged