Add penflow-ai extension
raycast/extensions pull request #15881
Opened 2024-12-16 06:34 UTC by Feng6611

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-12-20 19:00 UTC, pernielsentikaer requested changes
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension. If the locale might affect functionality (e.g. using the correct unit of measurement), please use the preferences API.

Due to holidays, there might be a delay of 10-15 days until the next reply, sorry for the inconvenience 😊

2024-12-29 13:56 UTC, Feng6611 commented
hi,I can't really program, just by Cursor. So, if there are any mistakes, please tell me.
Penflow just helps me communicate with you when my English is not good.

2025-01-02 09:18 UTC, pernielsentikaer requested changes
Thanks for getting back 🙂 A few new things

- There is a lot of unused code and you don't have to check for PRO

- You can't use html elements

- At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension. If the locale might affect functionality (e.g. using the correct unit of measurement), please use the preferences API.

The current state is not ready for the store

2025-01-15 11:15 UTC, pernielsentikaer requested changes
- What's the purpose of this extension? I'm finding it hard to figure out as it is and we might have something similar in the store already

- There is still a lot of chinese sentences like in the `EmptyView`

2025-01-15 15:37 UTC, Feng6611 commented
I'm Chinese, I am afraid to write in English. I think it will help me. Like this.
Help me solve some spelling problems, and polish it.I'm uncertain if this will be beneficial, but I will give it a try.
<img width="750" alt="image" src="https://github.com/user-attachments/assets/b624331e-3922-4a8c-83a6-1de558aba475" />
<img width="750" alt="image" src="https://github.com/user-attachments/assets/bd5d85f9-48a8-492f-b536-e3f80fc40724" />

2025-01-18 06:50 UTC, pernielsentikaer requested changes
Could we also remove npmmirror.com as base and stick to the original?

2025-01-19 20:46 UTC, pernielsentikaer requested changes
What are you using the file in docs for?

2025-01-22 07:20 UTC, pernielsentikaer commented
Is this ready for another review?

2025-01-23 20:50 UTC, pernielsentikaer requested changes
Metadata images needs to be taken with the official tool for it, it's not in the right format at the moment. This is how to take [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)

2025-02-13 20:34 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2025-02-13 20:38 UTC, merged