Adding Spring Initializr Extension
raycast/extensions pull request #15912
Opened 2024-12-17 15:05 UTC by danvega

I had some issues using npm run publish so after going through the docs I decided to go this route.

2024-12-20 19:28 UTC, pernielsentikaer requested changes
Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

2024-12-23 13:48 UTC, danvega commented
@pernielsentikaer There is one in the readme and links to the assets/ folder. Are you not able to see it?

2025-01-02 07:15 UTC, pernielsentikaer commented
You need to use our tool as described since it will create a metadata image with the right padding and place it in a folder called `metadata` 🙂

2025-01-06 01:54 UTC, danvega commented
Thank you for the link @pernielsentikaer I updated the extension with 2 screenshots using that approach.

2025-01-07 11:10 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2025-01-07 11:18 UTC, merged

2025-01-07 14:27 UTC, danvega commented
Thank you ☺️ Excited for folks to give it a try!