Add mouse-halo extension
raycast/extensions pull request #15925
Opened 2024-12-17 23:12 UTC by justinheinze

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-12-20 19:31 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- You're missing an extension icon, you can generate [one here](https://icon.ray.so/) 

- Is it possible to add a preference to let the user select a color?


Due to holidays, there might be a delay of 10-15 days until the next reply, sorry for the inconvenience 😊

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-12-20 21:58 UTC, justinheinze commented
Updated the extension icon and added in some preferences to allow the user to select the fill color and opacity along with the border color. Thanks!

2024-12-21 06:55 UTC, pernielsentikaer requested changes
Could we do something like this 🙂

2024-12-21 06:55 UTC, pernielsentikaer commented on extensions/mouse-halo/src/mouse-halo-toggle.tsx
> +
```suggestion
```
Redundant. Can be removed 🙂

2024-12-21 06:55 UTC, pernielsentikaer commented on extensions/mouse-halo/src/mouse-halo-toggle.tsx
> +const stateFile = path.join(os.tmpdir(), "mouse-halo.state");
```suggestion
const scriptPath = path.join(environment.supportPath, "mouse-halo-indicator.swift");
const stateFile = path.join(environment.supportPath, "mouse-halo.state");
```

2024-12-21 06:55 UTC, pernielsentikaer commented on extensions/mouse-halo/src/mouse-halo-toggle.tsx
> +import { closeMainWindow, getPreferenceValues } from "@raycast/api";
```suggestion
import { closeMainWindow, environment, getPreferenceValues } from "@raycast/api";
```

2024-12-21 06:55 UTC, pernielsentikaer commented on extensions/mouse-halo/src/mouse-halo-toggle.tsx
> +import os from "os";
```suggestion
```

2024-12-21 17:21 UTC, justinheinze commented on extensions/mouse-halo/src/mouse-halo-toggle.tsx
> +
Done!

2024-12-21 17:21 UTC, justinheinze commented on extensions/mouse-halo/src/mouse-halo-toggle.tsx
> +const stateFile = path.join(os.tmpdir(), "mouse-halo.state");
Done!

2024-12-21 17:21 UTC, justinheinze commented on extensions/mouse-halo/src/mouse-halo-toggle.tsx
> +import { closeMainWindow, getPreferenceValues } from "@raycast/api";
Done!

2024-12-21 17:21 UTC, justinheinze commented on extensions/mouse-halo/src/mouse-halo-toggle.tsx
> +import os from "os";
Done!

2025-01-02 06:54 UTC, pernielsentikaer commented
Could it make sense that you'll use our swift compiler - you can see how in this extension: https://www.raycast.com/thomas/color-picker

2025-01-23 09:40 UTC, closed without merging