Update raycast-gemini extension
raycast/extensions pull request #15949
Opened 2024-12-19 08:51 UTC by d0zingcat

## Description

## Screencast

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-12-19 12:35 UTC, pernielsentikaer commented
Hi 👋

Thanks for your contribution 🔥

Do you want to check this, @EvanZhouDev

2024-12-19 19:15 UTC, EvanZhouDev requested changes

2024-12-19 19:16 UTC, EvanZhouDev commented
@d0zingcat Looks pretty good, just a few minor touchups here and there! Also, not too sure if you can reproduce, but when generating text with Gemini 2.0 Flash (but perhaps also the other models), there appears to be a bit of lag when streaming. The streaming seems to override some existing text occasionally. I realize that there is nothing changed in your code that can directly cause this, but please let me know if you also have this issue.

2024-12-20 02:57 UTC, d0zingcat commented on extensions/raycast-gemini/src/translate.jsx
Make sense, I really appreciate your advice.

2024-12-20 06:02 UTC, d0zingcat commented on extensions/raycast-gemini/package.json
Yeah, I’ve thought about that.
As the following code is used to decide whether to read from the pasteboard/selection, if I pass the prompt as context in the Ask AI command without selecting any text (I assume your design allows users to do so), it causes errors.

```
  useEffect(() => {
    (async () => {
      if (context || useSelected) {
        try {
          let selected = await getSelectedText();
          if (useSelected) {
            if (argQuery === "") {
              setSelected(selected);
              setPage(Pages.Form);
            } else {
              getResponse(`${argQuery}\n${selected}`);
            }
            return;
          }
          getResponse(`${context}\n${selected}`);
        } catch (e) {
          console.error(e);
          await popToRoot();
          await showToast({
            style: Toast.Style.Failure,
            title: "Could not get the selected text",
          });
        }
```
Maybe the best approach is to pass `useSelected` declaratively in each command.

2024-12-20 06:56 UTC, d0zingcat commented
> @d0zingcat Looks pretty good, just a few minor touchups here and there! Also, not too sure if you can reproduce, but when generating text with Gemini 2.0 Flash (but perhaps also the other models), there appears to be a bit of lag when streaming. The streaming seems to override some existing text occasionally. I realize that there is nothing changed in your code that can directly cause this, but please let me know if you also have this issue.

Yes, I can reproduce this issue on both Gemini Flash 1.5 and 2.0, but I have no clue how to resolve it yet, e.g. Prompt: `What's the weather like today` and both two models show the lag and the text flashing.

2024-12-31 00:28 UTC, EvanZhouDev approved these changes
LGTM! Appreciate your work on this 😄

2024-12-31 00:28 UTC, EvanZhouDev commented
@pernielsentikaer This looks good for merge.

2025-01-02 09:30 UTC, merged