Add omnifocus extension
raycast/extensions pull request #15940
Opened 2024-12-18 20:12 UTC by nicolas-marien

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-12-20 19:43 UTC, pernielsentikaer requested changes
Hi 👋

Thank you for your contribution 🔥 

Do you mind correcting what I pointed out and recording a screencast of the flow?

2024-12-20 19:43 UTC, pernielsentikaer commented on extensions/omnifocus/src/list-inbox.tsx
> +                    title="Delete"
```suggestion
                    title="Delete"
                    style={Action.Style.Destructive}
```

2024-12-20 19:43 UTC, pernielsentikaer commented on extensions/omnifocus/src/list-inbox.tsx
> +                    icon={Icon.Trash}
```suggestion
                    icon={Icon.Trash}
                     shortcut={Keyboard.Shortcut.Common.Remove
```

2024-12-21 10:44 UTC, nicolas-marien commented
@pernielsentikaer Thank  you for review 🤘
I made the change. I'll add another screencast ASAP w/ the changes.

2025-01-02 06:46 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2025-01-02 06:51 UTC, merged

2025-01-02 12:10 UTC, nicolas-marien commented
Thanks @pernielsentikaer and happy new year!