Add pritunl extension
raycast/extensions pull request #15965
Opened 2024-12-20 07:53 UTC by mprokopov

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-12-20 19:56 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-12-20 19:58 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-12-23 10:05 UTC, mprokopov commented
Dear @pernielsentikaer 

Thank you for the review, though there is no much output from the extension apart from the plain message "VPN is connected" and "VPN is disconnected".  I also captured extension settings screenshots to the README. 

The only a screenshot I managed to capture is this

![Raycast 2024-12-23 at 10 56 24](https://github.com/user-attachments/assets/d1f2609d-e9d8-49ed-9fe3-cacabd97d0bd)

Let me know if this is what I should place to the metadata.

Maksym

2025-01-02 09:24 UTC, pernielsentikaer commented on extensions/pritunl/src/types/preferences.ts
> +} = getPreferenceValues();
You don't need to manually set preference types as this is autogenerated in `raycast-env.d.ts`x

2025-01-19 20:48 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2025-01-19 20:52 UTC, merged