Add elevenlabs-tts extension
raycast/extensions pull request #15992
Opened 2024-12-21 16:10 UTC by lachiejames

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-12-21 16:45 UTC, lachiejames commented on extensions/elevenlabs-tts/assets/readme-1.png
I [deleted these files](https://github.com/lachiejames/raycast-elevenlabs-tts/pull/24/files) and republished, but they haven't been removed from this PR.  Possible bug in `npm run publish`?

2024-12-22 12:40 UTC, thomaspaulmann commented
Wow that's a very cool extension! Love the approach for streaming the audio 👌

2025-01-03 09:53 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Can we show an error tost if the API is wrong? Right now it just shows "Playing..."

![Raycast03012025-ObMwaUm6 png@2x](https://github.com/user-attachments/assets/11bd6d07-b14f-4eb9-926d-50146a1ae37d)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2025-01-03 09:53 UTC, pernielsentikaer commented on extensions/elevenlabs-tts/src/voice/types.ts
> +
```suggestion
```
You don't need to manually set preference types as this is autogenerated in `raycast-env.d.ts`x

2025-01-03 14:37 UTC, closed without merging

2025-01-03 15:24 UTC, lachiejames commented on extensions/elevenlabs-tts/src/voice/types.ts
> +
Hi @pernielsentikaer  👋,

Thanks for your feedback and for testing the extension! I wanted to give you an update on the situation and link you to a related issue I've opened for the underlying problem.

I encountered a series of issues while attempting to update this PR (https://github.com/raycast/extensions/pull/15992). The root cause seems to be related to how the `npm run publish` command handles moved or deleted files. 

While trying to resolve this, I followed the workflow recommended by the error messages and ran `npx @raycast/api@latest pull-contributions`, but this failed with a Git fast-forward error. Eventually, I deleted the local `.config/raycast/public-extensions-fork` folder and reran `npm run publish`. However, this created a new PR instead of updating the existing one.

Here’s the issue I raised to document the problem in detail: https://github.com/raycast/extensions/issues/16142

The new PR for this extension is here: https://github.com/raycast/extensions/pull/16140.

2025-01-03 15:26 UTC, lachiejames commented on extensions/elevenlabs-tts/src/voice/types.ts
> +
By the way, your suggestions have been committed 
- https://github.com/lachiejames/raycast-elevenlabs-tts/pull/25
- https://github.com/lachiejames/raycast-elevenlabs-tts/pull/26