Pokedex
raycast/extensions pull request #16
Opened 2021-10-13 21:24 UTC by solrac97gr

## Description

this is an extension for search using Pokemon names information of every pokemon using wikidex and poke API
## Type of change

- New extension
## Screenshot
![alt screenshot](https://i.imgur.com/E0SL1v5.png)
## Checklist

- [x] I read the [contribution guidelines](contributing.md)

2021-10-14 22:08 UTC, mattisssa requested changes
Hey! Interesting extension 😄 

During the review, I found that it just doesn't work at all. Here are a few bullets + check the comments I left about namings.

- There is _bultasaur_ initially but if you type and remove there is nothing shown. We will prevent this and show an empty view, but for now, would be better if you will return an empty array if there are no items found
- Search doesn't work (see the screencast) 
- Errors are not handled

https://user-images.githubusercontent.com/15333662/137401985-f6862bfe-9225-4b36-9c20-5ae297abf969.mp4

2021-10-14 22:08 UTC, mattisssa commented on extensions/pokedex/package.json
> +      "title": "Pokedex",
Better to use **Search Pokemon** here.

2021-10-14 22:08 UTC, mattisssa commented on extensions/pokedex/package.json
> +      "subtitle": "Get the Pokemon information",
And **Pokedex** here

2021-11-02 20:46 UTC, PitNikola commented
@solrac97gr, I'm gonna close that PR for now. Please feel free to re-open once you have some changes to review 👍

2021-11-02 20:46 UTC, closed without merging