Add SVGA Player extension
raycast/extensions pull request #16055
Opened 2024-12-27 09:52 UTC by liaoyuanng

## Description

The SVGA Player is a versatile tool designed for effortlessly playing SVGA files.

## Screencast
<img width="1000" alt="screenshot" src="https://github.com/user-attachments/assets/e7c2ddeb-8002-4565-be9a-b43df367aedd" />

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2025-01-07 22:19 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Why is there a index.html in the `assets` folder

- Rename the `metadata` folder and call it `media` and show it in the README instead

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2025-01-08 05:17 UTC, liaoyuanng commented
Hi,

Thanks for your review.

> * Why is there a index.html in the `assets` folder

I need a canvas to display SVGA files, but since Raycast doesn’t support the web, I had to create a webview (using Swift) to provide a canvas context — that’s what index.html is for.

> * Rename the `metadata` folder and call it `media` and show it in the README 

Thanks for the suggestion! I noticed that many similar projects use metadata as the folder name. Could you help me understand why you think renaming it to media would be better in this case? If you have any guidelines, documentation, or examples to explain this approach, I’d really appreciate it!

2025-01-08 05:57 UTC, pernielsentikaer commented
The folder `metadata` is for images of Raycast for view commands, not for third party views 🙂 

It could look like this, but we don't have that for this extension since it's a no-view command

![image](https://github.com/user-attachments/assets/2e9c42b6-8b69-4d4b-97c7-d72bd064256a)

2025-01-08 06:14 UTC, liaoyuanng commented
Thanks, I get it now! I’ve updated it. Please review again.

2025-01-08 11:21 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2025-01-08 12:12 UTC, merged