Add wubi-input-query extension
raycast/extensions pull request #16064
Opened 2024-12-28 06:20 UTC by selfdem

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2025-01-09 04:22 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- You're missing an extension icon, you can generate [one here](https://icon.ray.so/) 

- At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension. If the locale might affect functionality (e.g. using the correct unit of measurement), please use the preferences API.

- Can you record a screencast of the flow?

- Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2025-01-09 04:22 UTC, pernielsentikaer commented on extensions/wubi-input-query/src/frontpage.tsx
> +        const response = await fetch(`http://127.0.0.1:7777/raycast/search_86?keyword=${searchText}&app_id=HVun9CsH27`);
Is this correct?

2025-01-23 01:32 UTC, selfdem commented on extensions/wubi-input-query/src/frontpage.tsx
> +        const response = await fetch(`http://127.0.0.1:7777/raycast/search_86?keyword=${searchText}&app_id=HVun9CsH27`);
ooo..., embarrassing..

2025-01-23 08:29 UTC, LitoMore commented
@selfdem What the difference between your #16568?

2025-02-13 10:08 UTC, closed without merging