Nextcloud Search Extension API fix
raycast/extensions pull request #16079
Opened 2024-12-29 11:07 UTC by jamespurnama1

## Description

A fix for #10036 and #5040
`TypeError: cannot read properties of undefined (reading 'd:prop')`
Specifically the Nextcloud extension by @uetchy search function:
- Added 200 OK check for items
- Added array check to item["d:propstat"]

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

## Notes

This is my first PR! Please be kind & point out anything I did wrong, would gladly discuss any improvements for this fix.

2025-01-03 17:32 UTC, xmok requested changes
I'm unable to reproduce the Issue mentioned in the linked issues but everything is working fine for me with your changes.
Please add yourself as a contributor in `package.json` if you are interested.
Suggestion: mention the issues with their links in CHANGELOG for future reference.

2025-01-03 17:32 UTC, xmok commented on extensions/nextcloud/CHANGELOG.md
> +## [WebDAV request Fix] - 2024-12-29
```suggestion
## [WebDAV request Fix] - {PR_MERGE_DATE}
```

2025-01-09 06:15 UTC, pernielsentikaer commented
Could you check comment here @jamespurnama1

2025-01-11 14:40 UTC, jamespurnama1 commented
Hi and thank you! I've added myself as a contributor and mention the issue with their links as per your suggestion @xmok

2025-01-12 07:29 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2025-01-12 07:30 UTC, merged