Add CRUD options for gopass
raycast/extensions pull request #16073
Opened 2024-12-29 04:09 UTC by andyfase

## Description

Extends the gopass extension to have full CRUD operations. This PR adds the CUD (Create, Update and Delete) options.

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2025-01-06 21:55 UTC, andyfase commented
Note. Also pushed support to sync gopass stores. This is needed to ensure password changes made on other machines and pushed to git are synchronized with the local password store.

2025-01-09 04:40 UTC, pernielsentikaer commented
Thanks for the contribution here 🔥

@bake do you want to check this?

2025-01-13 18:19 UTC, bake requested changes
Awesome PR, thank you so much! I wanted an option to create passwords for a while! 🎉

2025-01-13 18:19 UTC, bake commented on extensions/gopass/src/create-edit.tsx
> +    const password = await gopass.showAll(inputPassword);
We could simply use `gopass.password(inputPassword)` and `gopass.show(inputPassword).then((details) => details.join("\n"))`. I'm not sure about this, there's a comment in `gopass.ts` about this :)

2025-01-13 18:19 UTC, bake commented on extensions/gopass/src/gopass.ts
> +async function showAll(entry: string): Promise<showAllResponse> {
I’m not sure if we really need this function. We should either remove `showAll()` and replace it with calls to `password()` and `show()` or remove `password()` and rewrite `show()` to return password and details similar to this function. I'm not sure which way I'd prefer. What do you think?

2025-01-13 18:19 UTC, bake commented on extensions/gopass/src/gopass.ts
> +    return await gopass([
The `await` here and in line 64 is unnecessary. This is a very minor nitpick 😅

2025-01-14 02:40 UTC, andyfase commented on extensions/gopass/src/create-edit.tsx
> +      <Form.TextField
So i implemented the checkbox method - I definitely want the ability to self-alter the suggested password (hence going with clear-text in the first place) but get what you mean about the security aspect

The code to support both (with a checkbox) is a bit kludgy but it works :-) - It means i have to ignore the actual field values in validation and updates. I commented appropriately so its fairly obvious

2025-01-14 02:40 UTC, andyfase commented on extensions/gopass/src/create-edit.tsx
> +      console.log(inputString);
removed

2025-01-14 02:41 UTC, andyfase commented on extensions/gopass/src/create-edit.tsx
> +          const rAttributes = /^(?:(?:[^:,\n]+:[^:,\n]+)\n)*(?:[^:,\n]+:[^:,\n]+)$/;
changed the regex to support it but i remain unsure if `foo:bar:baz` is actually valid? I guess any value is valid.

2025-01-14 02:42 UTC, andyfase commented on extensions/gopass/src/gopass.ts
> +async function showAll(entry: string): Promise<showAllResponse> {
So I went with rewrite the old `show`. initially I added a new method to avoid large re-factors  but i didnt check how often that method is actually called - and its only once :-)

I wanted to avoid the multi-call option as there is no need to call the CLI twice imo

2025-01-14 02:42 UTC, andyfase commented on extensions/gopass/src/gopass.ts
> +    return await gopass([
done

2025-01-14 02:45 UTC, andyfase commented
@bake thanks for the feedback - I implemented the changes you requested / issues you pointed out. Also I added

- Check for existing password existence  - on new password
- Check for password name change  - on edit password (requires a save and a move operation)
- Fixed the fact that the password would fail to generate 1 times out of 10

Let me know what you think.

2025-01-14 11:30 UTC, bake commented on extensions/gopass/src/create-edit.tsx
> +      <Form.TextField
I really like the user experience, thank you!

2025-01-14 11:33 UTC, bake commented on extensions/gopass/src/gopass.ts
> +async function showAll(entry: string): Promise<showAllResponse> {
That's a good point. I don't think it would have be a problem to call the CLI twice but your solution is way more clean, thank you :)

2025-01-14 11:36 UTC, bake approved these changes

2025-01-14 11:38 UTC, bake commented
Thank you again for your additions. I'm really looking forward to using it as soon as the PR is merged :)

2025-01-14 23:34 UTC, andyfase commented
thanks @bake - just FYI I pushed some update to the create-edit view to make the re-renders based on updates to the form elements more reliable (moving away from `useEffect` )

@pernielsentikaer this should be good to merge now

2025-01-15 11:08 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2025-01-15 11:08 UTC, merged