feat: Add Quick Image Extension
raycast/extensions pull request #16089
Opened 2024-12-30 08:54 UTC by gutenye

## Description

Quick Image is a fast, text-based tool that allows you to convert, resize, concatenate images, and create PDFs from Raycast command line. With a simple command, like `jpg | ver | pdf`, you can easily convert images to jpg, concat them veritcally and output a pdf file

Differences from the Image Modification: It's a text based command, that allows you to perform multiple image operations in a single line of text. It provides a powerful way and options to edit the images. This feature simplifies complex workflows by enabling you to chain commands like converting, resizing, and creating PDFs, all in one go.

## Screencast

<img width="1000" alt="screenshot-1" src="https://github.com/user-attachments/assets/48e40c9c-0b26-4f9c-81b4-443b42a4ad60" />

<img width="1000" alt="screenshot-2" src="https://github.com/user-attachments/assets/0cab56f7-3dba-4547-9b9c-056e69786339" />

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2025-01-09 08:51 UTC, pernielsentikaer requested changes
Hi 👋

Thanks for your contribution 🔥 

Can we handle this gracefully, maybe even link to the readme so users know what to do?

![quick-image 2025-01-09 at 09 51 01](https://github.com/user-attachments/assets/eb53e68f-d8e3-45f8-adfb-43af2dfc1091)

2025-01-10 15:36 UTC, gutenye commented
@pernielsentikaer 

I’ve figured out a method to ship a pre-built native Node module without needing manual installation.

Now installation from the Store just works

If you want to obtain the sharp-darwin-arm64.node file, run the following commands:

```sh
brew install libvips
npm install
```

This will output the it to `node_modules/@gutenye/sharp/src/build/Release/sharp-darwin-arm64.node`

I’ve forked the sharp repository and [implemented these changes](https://github.com/gutenye/sharp/pull/1) to enable support for the prebuilt native module.

2025-01-12 07:11 UTC, pernielsentikaer requested changes
We can't just bundle a binary, as you can [see here](https://developers.raycast.com/basics/prepare-an-extension-for-store#binary-dependencies-and-additional-configuration)

2025-02-02 07:44 UTC, closed without merging

2025-02-03 10:38 UTC, godruoyi commented
Hi @gutenye, I recently encountered the same issue. I'm not quite sure if it's caused by sharp or the Raycast API. I found that even after installing sharp, it still throws an error saying "Error: Cannot find module 'sharp'" when running npm dev or npm build. @pernielsentikaer, could you help take a look?

```
error when require sharp: @img/sharp-darwin-arm64/sharp.node Error: Cannot find module '@img/sharp-darwin-arm64/sharp.node'
Require stack:
- /Users/x/.config/raycast/extensions/godruoyi-tinypng-raycast/image.js
- /Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Function._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at node_modules/sharp/lib/sharp.js (/Users/x/.config/raycast/extensions/godruoyi-tinypng-raycast/image.js:6986:18)
```

> For a quick review, Sharp will check whether the following paths exist or not, see https://github.com/lovell/sharp/blob/main/lib/sharp.js#L13-L24

I find it strange why the sharp package encounters this issue during raycast development, but these issues don't exist in other frameworks like Astro or Nuxt.

2025-02-03 10:42 UTC, godruoyi commented
I'm also quite curious about whether we can't include new code in raycast development by using `require('@img/sharp-darwin-arm64/sharp.node')`. I noticed that in @gutenye's implementation, we can only use this method: `require('${environment.assetsPath}/sharp-${runtimePlatform}.node')`. @pernielsentikaer, do you have any suggestions?

2025-02-10 05:46 UTC, godruoyi commented
hi @pernielsentikaer any syggestion on it pls👇🏾? thank you.

```
require('@img/sharp-darwin-arm64/sharp.node') ❌
require('${environment.assetsPath}/sharp-${runtimePlatform}.node') ✅
```