Add support for multi-select field type
raycast/extensions pull request #16080
Opened 2024-12-29 12:02 UTC by GeniusNirmit

## Description

Add support for multi-select field type

## Screencast

https://github.com/user-attachments/assets/a01790b7-8086-4b85-8483-4873b5974362

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-12-31 06:33 UTC, Nabhag8848 requested changes
@GeniusNirmit one improvement, ready to merge after that, great work !, Thanks!

2024-12-31 06:33 UTC, Nabhag8848 commented on extensions/twenty/src/components/MultiSelect.tsx
> +        ref={ref as React.Ref<FormItemRef>}
@GeniusNirmit Here add placeholder `Select ${field.name}...`.  see TextInput Field for reference.

2024-12-31 06:33 UTC, Nabhag8848 commented on extensions/twenty/src/components/FieldComponent.tsx
> +    //   return <MultiSelect values={{ field }} />;
@GeniusNirmit remove this commented code.

2025-01-01 13:12 UTC, Nabhag8848 requested changes
@GeniusNirmit minor change !

2025-01-01 13:12 UTC, Nabhag8848 commented on extensions/twenty/src/components/FieldComponent.tsx
> +      return <MultiSelect values={{ field, placeholder: `Enter ${field.name}...` }} {...itemProps} />;
```suggestion
      return <MultiSelect values={{ field, placeholder: `Select ${field.name}...` }} {...itemProps} />;
```

2025-01-09 06:16 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2025-01-09 06:17 UTC, merged