Add inbox-ai extension
raycast/extensions pull request #16084
Opened 2024-12-29 16:34 UTC by foeken

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2025-01-09 06:20 UTC, pernielsentikaer commented
I don't have any way to test this, do you have a screencast of the flow?

2025-01-09 17:08 UTC, foeken commented
Yeah, it's linked to in the original PR text :)

2025-01-11 14:30 UTC, foeken commented
Did you find the video? Should I post it here?

2025-01-11 16:46 UTC, foeken commented
https://github.com/user-attachments/assets/79bf801a-fa92-428d-b7d2-366e07d3bc6a

2025-01-12 07:32 UTC, pernielsentikaer requested changes
Could we do something like [Eagle](https://www.raycast.com/Yukai/eagle) to check if it's even installed?

2025-01-12 09:35 UTC, foeken commented
Let me check out what they did :)

2025-01-12 09:52 UTC, foeken commented
You were right, that was a nice addition. I took their example and moved it over.

2025-01-15 09:16 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved

2025-01-15 09:23 UTC, merged