add address and battery information
raycast/extensions pull request #1664
Opened 2022-05-11 12:02 UTC by albertoxamin

## Description

Add bluethooth device address and battery information for connected devices

## Screencast

![image](https://user-images.githubusercontent.com/6067659/167845007-c7810222-8203-4eb9-aec1-3200f7365fbf.png)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-05-11 14:12 UTC, albertoxamin commented
It could be useful to distinguish devices with the same name, 
However I recognize that it would be better if that information would be shown only when a certain key is pressed like in the macos menu
![image](https://user-images.githubusercontent.com/6067659/167870453-bdddc7b9-4e3a-4a9f-b8ff-e0895f073c87.png)

2022-05-11 14:45 UTC, albertoxamin commented
An alternative 
![image](https://user-images.githubusercontent.com/6067659/167878183-b95b668e-a459-4377-a978-32cbc43f7396.png)

2022-05-12 07:42 UTC, briankosw commented
In terms of solving the scenario you mentioned, where the user has devices with the same name and therefore uses the addresses to distinguish between them, I feel like the UX is a bit clunky. In this scenario, the user will have to first go to one device and open up menu and then go to the other device and open up the menu again to compare addresses.

Having each device's address in the menu is fine for its own sake (and so I think it's fine to have the device address in the menu), but I don't think it specifically improves on the scenario of distinguishing between devices with the same name.

2022-05-12 07:44 UTC, briankosw commented on extensions/toothpick/CHANGELOG.md
> +
```suggestion
## [Add battery level indicator and device address] - 2022-05-11

- Add battery level indicator for each connected Bluetooth device
- Add Bluetooth device address in menu
```

2022-05-16 11:35 UTC, pernielsentikaer commented
Is this ready to be merged and is everyone happy with the PR?

2022-05-17 05:07 UTC, pernielsentikaer requested changes
@albertoxamin 👋 

I often end up with `undefined` in the list. Is this something we can look into improving?

![CleanShot 2022-05-17 at 07 06 21@2x](https://user-images.githubusercontent.com/38033107/168733350-e09b04e1-8256-4e39-9270-c71e687d68ca.png)

2022-05-18 11:58 UTC, pernielsentikaer commented
Hi @albertoxamin 👋 

`i` is correct, in my case, it's 0,1,2.

<img width="1149" alt="CleanShot 2022-05-18 at 13 53 50@2x" src="https://user-images.githubusercontent.com/38033107/169032897-f3c9ddd3-d304-41dc-b5fc-8c47657ecea7.png">

When I run this with `npm run dev` and keep hitting ⌘+r - both device status and the battery is off even though the data in the console.log is right. You should be able to reproduce it, it's happening quite often here.

Let me kniw if you need help debugging it.

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-05-18 14:31 UTC, albertoxamin commented
@pernielsentikaer this should prevent the undefined to ever showing, let me know if this works for you.

2022-05-19 09:18 UTC, pernielsentikaer approved these changes
That's better, I still get disconnected icon from time to time, but it's really rare

Let's get it merged 💯 

Thanks for your contribution! 🔥

2022-05-19 09:19 UTC, merged