Add World Time extension
raycast/extensions pull request #1773
Opened 2022-05-22 16:41 UTC by koinzhang

## Description

Look the current time of a region, ip or domain.

**World Time** Query Service from [World Time API](http://worldtimeapi.org). The following notes are from the official website

> WorldTimeAPI is a simple web service which returns the current local time for a given timezone as either plain-text or JSON.

## Screencast

<img width="1000" alt="Metadata-1" src="https://user-images.githubusercontent.com/36128970/169706124-b1825f79-fbd1-448a-8edd-2328ac238d97.png">

<img width="1000" alt="Metadata-2" src="https://user-images.githubusercontent.com/36128970/169706131-11970f31-a16f-4bc1-ad39-935801f967cd.png">

<img width="1000" alt="Metadata-3" src="https://user-images.githubusercontent.com/36128970/169706138-ecc74447-f3d0-41f4-a6c8-8b2424ec32d4.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-05-25 07:16 UTC, pernielsentikaer requested changes
Hi @koinzhang 👋 

Thanks for another cool extension, I'm sure it will become handy in the toolset 🔥 

- After searching for an IP and deleting the IP again, this doesn't change the view, should it?
![CleanShot 2022-05-25 at 09 14 46@2x](https://user-images.githubusercontent.com/38033107/170202917-10edc349-b499-45c4-9f55-77b5b1beafb2.png)

I'm looking forward to testing this extension again 🔥  

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-05-25 08:01 UTC, koinzhang commented
Hi @pernielsentikaer . Thanks for your review!
> After searching for an IP and deleting the IP again, this doesn't change the view, should it?

Now when the user input is empty, the previous view is cleared. Please continue reviewing.

2022-05-25 09:06 UTC, pernielsentikaer commented
Hi @koinzhang 👋 

If I slowly type "raycast.com" - right before the `m` I get this error:

<img width="935" alt="image" src="https://user-images.githubusercontent.com/38033107/170225665-b46c2745-e226-45a1-8c7e-2d88b150eb67.png">

TypeError: Cannot read properties of undefined (reading 'map')

PopularArticles:query-ip-time.tsx:7:45

---
4: import { isEmpty } from "./utils/common-utils";
5: 
6: export default function PopularArticles() {
7:   const [searchContent, setSearchContent] = useState<string>("");
8:   const { timeInfo, loading } = getIpTime(searchContent);
9: 
0:   const emptyViewTitle = () => {
---

Dr:index.js:24:2463
    at ray-navigation-stack
bo:index.js:24:2091
wo:index.js:23:619
    at ray-root
pa:index.js:24:2832

Could you look into this?

2022-05-25 12:30 UTC, koinzhang commented
Hi @pernielsentikaer. Thanks for your review!
Sorry to keep you waiting, I've fixed the bugs, please keep reviewing.

2022-05-26 04:49 UTC, pernielsentikaer commented
Hi @koinzhang 👋 

I can no longer use `Query World Time`, it just gives me this error:
![CleanShot 2022-05-26 at 06 48 33@2x](https://user-images.githubusercontent.com/38033107/170418195-72468da4-83df-43f2-b908-f897f33036f8.png)

```
Error: Cannot create rendering values

i.<anonymous>:index.js:1:5162

---
1: var x0=Object.create;var St=Object.defineProperty,S0=Object.defineProperties,A0=Object.getOwnPropertyDescriptor,P0=Object.getOwnPropertyDescriptors,E0=Object.getOwnPropertyNames,Zf=Object.getOwnPropertySymbols,C0=Object.getPrototypeOf,Xf=Object.prototype.hasOwnProperty,O0=Object.prototype.propertyIsEnumerable;var Yf=(i,s,a)=>s in i?St(i,s,{enumerable:!0,configurable:!0,writable:!0,value:a}):i[s]=a,At=(i,s)=>{for(var a in s||(s={}))Xf.call(s,a)&&Yf(i,a,s[a]);if(Zf)for(var a of Zf(s))O0.call(s,a)&&Yf(i,a,s[a]);return i},Qf=(i,s)=>S0(i,P0(s)),I0=i=>St(i,"__esModule",{value:!0});var ue=(i,s)=>()=>(s||i((s={exports:{}}).exports,s),s.exports);var b0=(i,s,a,_)=>{if(s&&typeof s=="object"||typeof s=="function")for(let p of E0(s))!Xf.call(i,p)&&(a||p!=="default")&&St(i,p,{get:()=>s[p],enumerable:!(_=A0(s,p))||_.enumerable});return i},Pt=(i,s)=>b0(I0(St(i!=null?x0(C0(i)):{},"default",!s&&i&&i.__esModule?{get:()=>i.default,enumerable:!0}:{value:i,enumerable:!0})),i);var xr=ue(Z=>{"use strict";Object.defineProperty(Z,"__esModule",{value:!0});Z.createJSONRPCErrorResponse=Z.JSONRPCErrorCode=Z.isJSONRPCResponses=Z.isJSONRPCResponse=Z.isJSONRPCRequests=Z.isJSONRPCRequest=Z.isJSONRPCID=Z.JSONRPC=void 0;Z.JSONRPC="2.0";var M0=function(i){return typeof i=="string"||typeof i=="number"||i===null};Z.isJSONRPCID=M0;var T0=function(i){return i.jsonrpc===Z.JSONRPC&&i.method!==void 0&&i.result===void 0&&i.error===void 0};Z.isJSONRPCRequest=T0;var L0=function(i){return Array.isArray(i)&&i.every(Z.isJSONRPCRequest)};Z.isJSONRPCRequests=L0;var N0=function(i){return i.jsonrpc===Z.JSONRPC&&i.id!==void 0&&(i.result!==void 0||i.error!==void 0)};Z.isJSONRPCResponse=N0;var W0=function(i){return Array.isArray(i)&&i.every(Z.isJSONRPCResponse)};Z.isJSONRPCResponses=W0;var D0;(function(i){i[i.ParseError=-32700]="ParseError",i[i.InvalidRequest=-32600]="InvalidRequest",i[i.MethodNotFound=-32601]="MethodNotFound",i[i.InvalidParams=-32602]="InvalidParams",i[i.InternalError=-32603]="InternalError"})(D0=Z.JSONRPCErrorCode||(Z.JSONRPCErrorCode={}));var F0=function(i,s,a,_){var p={code:s,message:a};return _&&(p.data=_),{jsonrpc:Z.JSONRPC,id:i,error:p}};Z.createJSONRPCErrorResponse=F0});var nu=ue(Et=>{"use strict";Object.defineProperty(Et,"__esModule",{value:!0});Et.DefaultErrorCode=void 0;Et.DefaultErrorCode=0});var jf=ue(me=>{"use strict";var U0=me&&me.__awaiter||function(i,s,a,_){function p(d){return d instanceof a?d:new a(function(S){S(d)})}return new(a||(a=Promise))(function(d,S){function C(M){try{m(_.next(M))}catch(Y){S(Y)}}function T(M){try{m(_.throw(M))}catch(Y){S(Y)}}function m(M){M.done?d(M.value):p(M.value).then(C,T)}m((_=_.apply(i,s||[])).next())})},B0=me&&me.__generator||function(i,s){var a={label:0,sent:function(){if(d[0]&1)throw d[1];return d[1]},trys:[],ops:[]},_,p,d,S;return S={next:C(0),throw:C(1),return:C(2)},typeof Symbol=="function"&&(S[Symbol.iterator]=function(){return this}),S;function C(m){return function(M){return T([m,M])}}function T(m){if(_)throw new TypeError("Generator is already executing.");for(;a;)try{if(_=1,p&&(d=m[0]&2?p.return:m[0]?p.throw||((d=p.return)&&d.call(p),0):p.next)&&!(d=d.call(p,m[1])).done)return d;switch(p=0,d&&(m=[m[0]&2,d.value]),m[0]){case 0:case 1:d=m;break;case 4:return a.label++,{value:m[1],done:!1};case 5:a.label++,p=m[1],m=[0];continue;case 7:m=a.ops.pop(),a.trys.pop();continue;default:if(d=a.trys,!(d=d.length>0&&d[d.length-1])&&(m[0]===6||m[0]===2)){a=0;continue}if(m[0]===3&&(!d||m[1]>d[0]&&m[1]<d[3])){a.label=m[1];break}if(m[0]===6&&a.label<d[1]){a.label=d[1],d=m;break}if(d&&a.label<d[2]){a.label=d[2],a.ops.push(m);break}d[2]&&a.ops.pop(),a.trys.pop();continue}m=s.call(i,a)}catch(M){m=[6,M],p=0}finally{_=d=0}if(m[0]&5)throw m[1];return{value:m[0]?m[1]:void 0,done:!0}}};Object.defineProperty(me,"__esModule",{value:!0});me.JSONRPCClient=void 0;var Sr=xr(),eu=nu(),J0=function(){function i(s,a){this._send=s,this.createID=a,this.idToResolveMap=new Map,this.id=0}return i.prototype._createID=function(){return this.createID?this.createID():++this.id},i.prototype.timeout=function(s,a){var _=this;a===void 0&&(a=function(S){return(0,Sr.createJSONRPCErrorResponse)(S,eu.DefaultErrorCode,"Request timeout")});var p=function(S,C){var T=setTimeout(function(){S.forEach(function(m){var M=_.idToResolveMap.get(m);M&&(_.idToResolveMap.delete(m),M(a(m)))})},s);return C().then(function(m){return clearTimeout(T),m},function(m){return clearTimeout(T),Promise.reject(m)})},d=function(S,C){var T=(Array.isArray(S)?S:[S]).map(function(m){return m.id}).filter(Vf);return p(T,function(){return _.requestAdvanced(S,C)})};return{request:function(S,C,T){var m=_._createID();return p([m],function(){return _.requestWithID(S,C,T,m)})},requestAdvanced:function(S,C){return d(S,C)}}},i.prototype.request=function(s,a,_){return this.requestWithID(s,a,_,this._createID())},i.prototype.requestWithID=function(s,a,_,p){return U0(this,void 0,void 0,function(){var d,S;return B0(this,function(C){switch(C.label){case 0:return d={jsonrpc:Sr.JSONRPC,method:s,params:a,id:p},[4,this.requestAdvanced(d,_)];case 1:return S=C.sent(),S.result!==void 0&&!S.error?[2,S.result]:S.result===void 0&&S.error?[2,Promise.reject(new Error(S.error.message))]:[2,Promise.reject(new Error("An unexpected error occurred"))]}})})},i.prototype.requestAdvanced=function(s,a){var _=this,p=Array.isArray(s);Array.isArray(s)||(s=[s]);var d=s.filter(function(T){return Vf(T.id)}),S=d.map(function(T){return new Promise(function(m){return _.idToResolveMap.set(T.id,m)})}),C=Promise.all(S).then(function(T){return p||!T.length?T:T[0]});return this.send(p?s:s[0],a).then(function(){return C},function(T){return d.forEach(function(m){_.receive((0,Sr.createJSONRPCErrorResponse)(m.id,eu.DefaultErrorCode,T&&T.message||"Failed to send a request"))}),C})},i.prototype.notify=function(s,a,_){this.send({jsonrpc:Sr.JSONRPC,method:s,params:a},_).then(void 0,function(){})},i.prototype.send=function(s,a){return this._send(s,a)},i.prototype.rejectAllPendingRequests=function(s){this.idToResolveMap.forEach(function(a,_){return a((0,Sr.createJSONRPCErrorResponse)(_,eu.DefaultErrorCode,s))}),this.idToResolveMap.clear()},i.prototype.receive=function(s){var a=this;Array.isArray(s)||(s=[s]),s.forEach(function(_){var p=a.idToResolveMap.get(_.id);p&&(a.idToResolveMap.delete(_.id),p(_))})},i}();me.JSONRPCClient=J0;var Vf=function(i){return i!=null}});var rs=ue(Ln=>{"use strict";var Ct=Ln&&Ln.__assign||function(){return Ct=Object.assign||function(i){for(var s,a=1,_=arguments.length;a<_;a++){s=arguments[a];for(var p in s)Object.prototype.hasOwnProperty.call(s,p)&&(i[p]=s[p])}return i},Ct.apply(this,arguments)},ns=Ln&&Ln.__awaiter||function(i,s,a,_){function p(d){return d instanceof a?d:new a(function(S){S(d)})}return new(a||(a=Promise))(function(d,S){function C(M){try{m(_.next(M))}catch(Y){S(Y)}}function T(M){try{m(_.throw(M))}catch(Y){S(Y)}}function m(M){M.done?d(M.value):p(M.value).then(C,T)}m((_=_.apply(i,s||[])).next())})},es=Ln&&Ln.__generator||function(i,s){var a={label:0,sent:function(){if(d[0]&1)throw d[1];return d[1]},trys:[],ops:[]},_,p,d,S;return S={next:C(0),throw:C(1),return:C(2)},typeof Symbol=="function"&&(S[Symbol.iterator]=function(){return this}),S;function C(m){return function(M){return T([m,M])}}function T(m){if(_)throw new TypeError("Generator is already executing.");for(;a;)try{if(_=1,p&&(d=m[0]&2?p.return:m[0]?p.throw||((d=p.return)&&d.call(p),0):p.next)&&!(d=d.call(p,m[1])).done)return d;switch(p=0,d&&(m=[m[0]&2,d.value]),m[0]){case 0:case 1:d=m;break;case 4:return a.label++,{value:m[1],done:!1};case 5:a.label++,p=m[1],m=[0];continue;case 7:m=a.ops.pop(),a.trys.pop();continue;default:if(d=a.trys,!(d=d.length>0&&d[d.length-1])&&(m[0]= [...]

2022-05-26 04:51 UTC, koinzhang commented
Hi @pernielsentikaer 
Hi, I have modified the format of some data, you need to be clear about storing data locally to continue using it.
You can just uninstall the extension and reinstall it again.

2022-05-26 05:02 UTC, pernielsentikaer approved these changes
That's better, let's get it merged 💯

2022-05-26 05:03 UTC, merged