feat: vercast 1.0.0
raycast/extensions pull request #18
Opened 2021-10-14 04:01 UTC by gleich

Signed-off-by: Matt Gleich <git@mattglei.ch>

## Description

View your vercel deployments right from raycast. It even refreshes every second to show the latest changes!

## Type of change

- [x] New extension
- [ ] Bug fix / improvement for my extension
- [ ] Bug fix / improvement for somebody else's extension
- [ ] Documentation update
- [ ] Other (Specify)

## Screenshot

<img width="886" alt="example" src="https://user-images.githubusercontent.com/43759105/137249419-ca49c2ac-1479-4a33-8d93-8c3a4afcf834.png">

## Checklist

- [x] I read the [contribution guidelines](contributing.md)

2021-10-14 11:31 UTC, thomaspaulmann commented
> Is the failing CI because I'm using yarn?

Might be the case. We rely on `npm` for now. Could you switch? Same for your other extension #21

2021-10-14 16:08 UTC, fe9lix requested changes
Hey matt! 

The main problem is that that the use-interval dependency cannot be installed because of a conflicting peer dependency with react.

The API relies on react 17.0.2 while the downloaded use-interval package specifies "^16.8.0" so they are not compatible. (Interestingly, in the use-interval repo, it's specified as ">=16.8.0").
As workaround, you could just copy that source code inline in your extension or in a new file and import it. It doesn't seem to be much code anyway in the dependency.

Also, I've left a couple of comments inline in the manifest.

And please check that:
- the yarn.lock file is not committed (currently we rely on npm and there's no need to commit the lock file in general)
- the icon size should be 512x512 pixels

2021-10-14 16:08 UTC, fe9lix commented on extensions/vercast/package.json
> +  "author": "matt",
Please also add this field to the manifest:
`"license": "MIT"`

2021-10-15 13:41 UTC, fe9lix requested changes
Hey Matt,

Thanks for the updates. When I enter an (invalid) token, I get stuck in a loop that constantly switches between two error toasts in the UI – I guess that's because of the running interval.

Here's the error you might want to handle (and in that case probably stop the interval refresh):

```
TypeError: json.projects is not iterable
    at null.fetchDeployments (.../src/vercel.ts:51:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.current (.../src/index.tsx:26:20)
2021-10-15 15:35:40.555 F  Raycast[22781:11f2d64] [com.raycast.extensions.vercast:index] 
.../src/vercel.ts:33
    return json.user.username;
                     ^

TypeError: Cannot read properties of undefined (reading 'username')
    at null.fetchUsername (.../src/vercel.ts:33:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at null.call (.../src/index.tsx:13:42)
2021-10-15 15:35:40.879 F  Raycast[22781:11f28fd] [com.raycast.extensions.vercast:index] 
...src/vercel.ts:51
...
```

2021-10-15 14:27 UTC, fe9lix requested changes
Cool! Last change request and I think then we're ready to merge:
I currently only see "Vercast" in root search, so when I search for "vercel" I won't find your command. I would suggest to put "Search Vercel Deployments" as command title instead of description.

2021-10-15 14:39 UTC, fe9lix approved these changes

2021-10-15 14:39 UTC, merged

2021-10-15 14:48 UTC, fe9lix commented
@gleich It's merged now and available in the store. Something for your next update maybe:

Extension name: "Vercel Deployments"
Command name: "Search Deployments", subtitle: "Vercel"
Description: "Quickly open and check status of your Vercel deployments."

I know that those properties can be a bit confusing...