Add Blockchain Explorer Search Extension
raycast/extensions pull request #1831
Opened 2022-05-27 18:02 UTC by Namaskar-1F64F

## Description

I added a new extension! It tries to automatically detect what is either in the clipboard or searched for in the List search, and returns a link to the corresponding blockchain explorer site. All of the sites share a similar structure, so switching between the different types is only a URL change away.

## Screencast

[screencast](https://share.cleanshot.com/cyi6f9)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-05-27 18:05 UTC, Namaskar-1F64F commented
Ouch - screenshot size didn't make sense because the interface was too small for the 2000x1250 resolution. Looking into this 👀

2022-05-29 21:40 UTC, Geczy commented on extensions/blockchain-explorer-search/src/matchers.ts
> +      const foundToken = this.tokenList.find(({ address }) => address === this.search);
can you do search ignore case matching?

2022-06-07 01:19 UTC, RusseII commented
Any updates on this? Really excited for this extension!

2022-06-08 10:29 UTC, pernielsentikaer commented on extensions/blockchain-explorer-search/src/matchers.ts
> +      const foundToken = this.tokenList.find(({ address }) => address === this.search);
Can you look into this @Namaskar-1F64F

2022-06-08 10:32 UTC, pernielsentikaer requested changes
Hi @Namaskar-1F64F 👋 

Thanks for the extension, I tested it and I only have minor feedback:

The search command, when you have something in the clipboard suffer from [Empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) - could you look into this? Maybe add a loading state that you can pass is isLoading={} to your list 😄 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-06-09 11:10 UTC, Namaskar-1F64F commented on extensions/blockchain-explorer-search/src/matchers.ts
> +      const foundToken = this.tokenList.find(({ address }) => address === this.search);
Good suggestion 👍 Implemented.

2022-06-09 16:07 UTC, Namaskar-1F64F commented on extensions/blockchain-explorer-search/src/search.tsx
> +          <Action.OpenInBrowser url={match.path} />
`match.path` is the link, and open in browser is the first action in the action panel (bottom right). command + k will show the other options, like to create a quick link

2022-06-09 16:15 UTC, Namaskar-1F64F commented
No option to re-request a review. Am I missing something or GH bug?
<img width="376" alt="CleanShot 2022-06-09 at 18 15 12@2x" src="https://user-images.githubusercontent.com/7458951/172895089-823af77c-d480-4478-b14e-7edf14988294.png">

Anyway, I fixed the search problem. Tested by clearing localstorage. 

@pernielsentikaer

2022-06-09 16:19 UTC, Geczy commented
> No option to re-request a review. Am I missing something or GH bug? <img alt="CleanShot 2022-06-09 at 18 15 12@2x" width="376" src="https://user-images.githubusercontent.com/7458951/172895089-823af77c-d480-4478-b14e-7edf14988294.png">
> 
> Anyway, I fixed the search problem. Tested by clearing localstorage.
> 
> @pernielsentikaer

i think its because of this sequence of events. @pernielsentikaer has not requested changes since

![2022-06-09 at 11 18 40@2x](https://user-images.githubusercontent.com/1036968/172895748-487e18d8-8014-4abf-9d29-d45e72befd84.png)

2022-06-09 16:39 UTC, pernielsentikaer commented on extensions/blockchain-explorer-search/src/search.tsx
> +          <Action.OpenInBrowser url={match.path} />
There was a wrong naming convention here, it should be title cased - the title is also automatically added in `Action.OpenInBrowser` if none provided

2022-06-09 16:43 UTC, pernielsentikaer approved these changes
I think we're ready to merge 🎉 

In the next version, it could be good to look into some of the logos' - black text in dark appearance is not the best 😄

2022-06-09 16:50 UTC, merged