Update twitch extension
raycast/extensions pull request #1839
Opened 2022-05-28 22:26 UTC by Aayush9029

## Description
  - Migrating to raycast version @1.26.3
  - Added better markdown support
  - Added detail view
  - Fixed streamlink errors
  - Fixed low latency streams
  - Removing uneccesary commands
  - Added Success and Error Toasts and HUDs
  - Added metadata for raycast store
  - Optimizing + Refactoring + Restucturing undelrying codebase
  - A lot of other small bug and QOL fixes + improvements

## Screencast
<img width="1000" alt="Metadata-1" src="https://user-images.githubusercontent.com/43297314/170844616-9c8ffb83-2676-41c7-9b36-cfd6d3fe7232.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-05-29 04:42 UTC, pernielsentikaer commented
I was almost done doing the exact, awesome - could I help provide something?

I added the right avatar in my version :)

2022-05-29 05:57 UTC, pernielsentikaer commented on extensions/twitch/package.json
> +        "@raycast/api": "^1.26.3",
You actually downgrading the API?

2022-05-29 05:59 UTC, pernielsentikaer requested changes
Hi @Aayush9029 👋 

Looks like you didn't pull the latest version before doing this? A lot of work is rolled back 😞 

Could you please correct this 😄 💪

2022-05-29 15:17 UTC, Aayush9029 commented
Oh god! Didn't realize they updated it, I pushed local changes I made for myself😅

Will work on merging this

2022-05-29 15:21 UTC, closed without merging

2022-05-29 15:38 UTC, pernielsentikaer commented
It was actually me 😁 Let me send your some code a bit later 🤟

2022-06-02 03:22 UTC, Aayush9029 commented
@pernielsentikaer any updates 😄 
Looking forward to this a lot!

2022-07-16 03:50 UTC, Aayush9029 commented
@pernielsentikaer it's been a while 😭 still waiting for you