Add extension to query upcoming holidays
raycast/extensions pull request #1864
Opened 2022-06-01 14:58 UTC by rodrigouroz

## Description

This adds an extension to query the upcoming holidays for a country. It uses in the background the site https://askholidays.vercel.app

## Screencast

https://user-images.githubusercontent.com/384037/171435315-0f30e305-c4ff-4a38-8134-0472fa2958ba.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-06-01 19:35 UTC, pernielsentikaer requested changes
Hi @rodrigouroz 👋 

Thanks for your contribution, it's a very nice one 🔥 

What about calling the extension and folder for "Upcoming Holidays" instead, next sounds wrong in my ears 😄 

Would it be possible to include something like [SWR](https://swr.vercel.app) to cache the data, it feels very heavy when browsing the list and revisiting the same elements.

An idea for this or next release could be a possibility to pin countries 🔥 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-06-01 19:35 UTC, pernielsentikaer commented on extensions/holidays/package.json
> +      "subtitle": "upcoming holidays for a country",
```suggestion
      "title": "List Upcoming Holidays",
```

2022-06-02 03:13 UTC, rodrigouroz commented
Done. I loved the idea of pinning countries, I'll do it in another PR not to hold on this first version.

2022-06-03 10:58 UTC, pernielsentikaer commented
Hi @rodrigouroz 👋 

Awesome update, like the new features! 🔥 

I added new metadata images; the current was in the wrong format 😄 

One thing that would also be cool to add is a ´cache adapter` to cache the results for a long time since they don't nearly ever change 😄 

You can see a bit more about how it's done in the [Sentry extension](https://github.com/raycast/extensions/blob/df23810f3c604686d55c51f13add6cba9c445285/extensions/sentry/src/cache.ts) - Do you think you could look into this?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-06-04 06:25 UTC, pernielsentikaer approved these changes
Awesome, @rodrigouroz 🔥 It has been a pleasure to work with you 💪

2022-06-04 06:27 UTC, merged