✨ Added feature to NBA-game-viewer extension
raycast/extensions pull request #1877
Opened 2022-06-03 01:56 UTC by AbhinavPalacharla

…l information

## Description

Added new feature to NBA viewer extensions - can view team roster and player info

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-06-04 05:55 UTC, pernielsentikaer requested changes
Hi @AbhinavPalacharla 👋 

What an excellent update, looking forward to using it myself 🔥 

I added some suggestions and feedback for you to address 💪 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-06-04 05:55 UTC, pernielsentikaer commented on extensions/nba-game-viewer/src/components/Player.tsx
> +          <Action title="Show Player Info" icon={Icon.Sidebar} onAction={() => setIsShowingDetail(true)} />
Maybe it should be a toggle instead?

2022-06-04 05:55 UTC, pernielsentikaer commented on extensions/nba-game-viewer/src/components/Player.tsx
> +              <List.Item.Detail.Metadata.Label title="Position" text={player.position} />
Maybe add the player name in the first row, I can't see the name
![CleanShot 2022-06-04 at 07 52 05@2x](https://user-images.githubusercontent.com/38033107/171986512-ade4c426-1707-4368-8522-d4d3102445a9.png)

2022-06-05 18:05 UTC, AbhinavPalacharla commented
@pernielsentikaer I'm glad you liked the update and I'm excited for you to start using it. I added the changes you suggested and I have a couple more features planned.

2022-06-06 04:45 UTC, pernielsentikaer approved these changes
Hi @AbhinavPalacharla 👋 

Awesome update, thanks for taking your time 🔥 

I changed a few things, I hope you don't mind! Let's show player information from start 💪

2022-06-06 04:45 UTC, merged