Add Extension: Mailsy
raycast/extensions pull request #1889
Opened 2022-06-03 16:14 UTC by BalliAsghar

## Description

With Mailsy users can quickly generate disposable email addresses, and view received Mails.

## Screencast

![Screenshot 2022-06-03 at 5 11 11 pm](https://user-images.githubusercontent.com/14165223/171904301-bd8ae59d-2ffe-41a9-afaf-c0ade2842479.png)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-06-05 01:13 UTC, BalliAsghar commented
https://user-images.githubusercontent.com/14165223/172030764-e210268f-9315-4c4e-b9ff-1fab4b2659a9.mov

### _Allowing Email to be Opened in Browser_

### Why

When an Email is opened in Raycast it only displays the text version of the email, but Sometimes Emails contain Html that is not viewable when opened in Raycast.

2022-06-09 12:42 UTC, pernielsentikaer requested changes
Hi @BalliAsghar 👋 

Thanks for your contribution, I tried to test it but the first thing I encounter in all commands is this:

![CleanShot 2022-06-09 at 14 40 18@2x](https://user-images.githubusercontent.com/38033107/172849356-2e5d7823-49d3-4624-9e59-834d163d7e3e.png)

I'm not sure what to expect, could you look into this?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-06-09 14:31 UTC, BalliAsghar commented
Hey @pernielsentikaer, 
I've committed some changes, this should fix the issues. Please have a look!

2022-06-09 18:04 UTC, pernielsentikaer requested changes
Hi @BalliAsghar 👋 

It works much better now; thanks for the corrections 🔥 !

I left a few minor suggestions for you to address 😄 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-06-09 18:04 UTC, pernielsentikaer commented on extensions/mailsy/src/mails.tsx
> +              <Action.Push title={"Open Email"} target={<Email id={item.id} />} />
```suggestion
              <Action.Push title={"Open Email"} icon={Icon.Envelope} target={<Email id={item.id} />} />
```
Missing icon

2022-06-10 04:33 UTC, pernielsentikaer approved these changes
Hi @BalliAsghar 👋 

Let's get it merged 🔥 

Thanks for your cooperation 💪

2022-06-10 04:46 UTC, merged