adds nanoid
raycast/extensions pull request #1928
Opened 2022-06-08 09:15 UTC by roelvan

## Description

New extension to generate [nanoid](https://github.com/ai/nanoid)'s.

## Screencast

Video: https://share.cleanshot.com/ra57LS

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-06-09 20:55 UTC, mattisssa requested changes
Hey, thanks for the contribution! Nice icon 😉 

I guess the advantage of your extension comparing with [this one](https://www.raycast.com/loris/random) is that it can be assigned with shortcut and supporting just a single nanoid data? Because users could do the same with extension I linked (with 1 more step then with your extension)

I also suggested a few changes that must be done to pass the CI validation and to match the store guidelines.

2022-06-09 20:55 UTC, mattisssa commented on extensions/nanoid/package.json
> +      "title": "Nanoid",
```suggestion
      "title": "Generate Nanoid",
```

2022-06-09 20:55 UTC, mattisssa commented on extensions/nanoid/package.json
> +      "name": "Nanoid",
```suggestion
      "name": "nanoid",
```

2022-06-09 20:55 UTC, mattisssa commented on extensions/nanoid/package.json
> +  "description": "A tiny (130 bytes), secure, URL-friendly, unique string ID generator for JavaScript ",
```suggestion
  "description": "A tiny, secure, URL-friendly, unique string ID generator for JavaScript ",
```

2022-06-10 06:46 UTC, roelvan reviewed
The faker extension you mention cannot generate nanoid's afaik.

2022-06-10 10:52 UTC, mattisssa commented
> The faker extension you mention cannot generate nanoid's afaik.

alright 👌 
I thought UUID is kinda the same thing.

2022-06-22 21:35 UTC, merged