use Grid Layout in Dribbble extension
raycast/extensions pull request #1937
Opened 2022-06-08 21:05 UTC by gebeto

## Description

 - add `Grid` layout
 - add Details view
 - add more metadata (likes, views)
 - add ability to open author in browser

## Screencast

https://user-images.githubusercontent.com/13422799/172716890-ea2feffc-8b86-4ca1-9e27-77e0a2bd6931.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-06-10 07:18 UTC, pernielsentikaer requested changes
Hi @gebeto 👋 

Thanks for your update! It looks really good, I only have some minor corrections and suggestions for you 😄 

Could we remove | xxx from the Dropdown items, it should be enough with the section above and will look crisper:

![CleanShot 2022-06-10 at 08 59 38@2x](https://user-images.githubusercontent.com/38033107/173010883-36918233-c99d-4080-947e-fc72cd8518a1.png)

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-06-10 09:56 UTC, gebeto commented on extensions/dribbble/src/index.tsx
> +                title="More info"
Title was fixed and added Icon 🙌
<img width="215" alt="Screenshot 2022-06-10 at 12 53 13" src="https://user-images.githubusercontent.com/13422799/173040816-9730f99d-0aef-47ce-9b5b-79bebdb15c71.png">

2022-06-10 09:57 UTC, pernielsentikaer commented
Hi @gebeto 👋 

You might want to leave out the `tintColor` since it looks bad with white apperance
![CleanShot 2022-06-10 at 11 56 33@2x](https://user-images.githubusercontent.com/38033107/173041099-4e26dd58-ead0-4907-b0ca-8bc7292e511f.png)

2022-06-10 10:04 UTC, gebeto commented
@pernielsentikaer  Oh yeah, thanks!

But I have an issue, if I do not pass tintColor, it is black

So I've used dynamic tintColor:

https://github.com/raycast/extensions/pull/1937/files#diff-da66ebcea774d83320552d706b906b5b28a9cc73289fb06f5dafbd2a2d8e2572R83-R86

2022-06-10 10:05 UTC, gebeto commented
@pernielsentikaer Are there some requirements to SVGs for correctly applying default tint color?

2022-06-10 10:17 UTC, pernielsentikaer commented
> @pernielsentikaer Are there some requirements to SVGs for correctly applying default tint color?

Seems to be correct now in both light and dark mode, do you face any issues?

2022-06-10 14:02 UTC, gebeto commented
> > @pernielsentikaer Are there some requirements to SVGs for correctly applying default tint color?
> 
> Seems to be correct now in both light and dark mode, do you face any issues?

No any issues, now it works correct

2022-06-11 19:59 UTC, pernielsentikaer approved these changes
Awesome @gebeto 🔥

Let's get this beauty out! 💪

2022-06-11 19:59 UTC, merged