Raytasker initial PR
raycast/extensions pull request #2047
Opened 2022-06-21 07:45 UTC by mj0lken

## Description

## Screencast

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-06-21 12:26 UTC, pernielsentikaer requested changes
Hi @mj0lken 👋 

Thanks for your contribution 💪 

Could you look into the errors that the [linter complains](https://github.com/raycast/extensions/runs/6980026068?check_suite_focus=true) about? 😄 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-06-22 10:34 UTC, pernielsentikaer requested changes
Hi @mj0lken 👋 

Thanks for your contribution 💯 

I now have the extension running and have some questions and suggestions, could you please look into this?

- When no tasks are on the list there is no way to create a new task since there are no action panel items.

- Maybe hide `Due` if there is no due date set?

- There is an `Icon.Dot` in front of the title in the metadata pane, it looks funny, maybe we should remove it?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-06-22 10:34 UTC, pernielsentikaer commented on extensions/raytasker/package.json
> +      "description": "Google tasks extension for Raycast",
```suggestion
      "title": "Manage Task List",
      "description": "Google Tasks",
```

2022-06-22 10:34 UTC, pernielsentikaer commented on extensions/raytasker/package.json
> +  "title": "Raytasker",
Then extension should maybe be called Google Tasks instead

2022-06-22 10:34 UTC, pernielsentikaer commented on extensions/raytasker/src/components/dropdown.tsx
> +      tooltip="Select list"
```suggestion
      tooltip="Select List"
```

2022-06-22 10:34 UTC, pernielsentikaer commented on extensions/raytasker/src/components/form.tsx
> +      navigationTitle={"Task"}
Please don't change the [navigationTitle](https://developers.raycast.com/basics/prepare-an-extension-for-store#navigation-title) in the root command; it's getting the title from the command.

2022-06-22 10:34 UTC, pernielsentikaer commented on extensions/raytasker/src/components/form.tsx
> +                    showToast({ title: `Task updated`, style: Toast.Style.Success });
```suggestion
                    showToast({ title: `Task Updated`, style: Toast.Style.Success });
```

2022-06-22 10:34 UTC, pernielsentikaer commented on extensions/raytasker/src/raytasker.tsx
> +
Is this just leftovers?

2022-06-22 10:34 UTC, pernielsentikaer commented on extensions/raytasker/src/raytasker.tsx
> +                  title="Mark complete"
```suggestion
                  title="Mark Complete"
```

2022-07-19 12:00 UTC, danielsequeira commented
@mj0lken ping here 🙂

2022-08-09 07:12 UTC, pernielsentikaer commented
I'm closing this due to inactivity; feel free to open it again or comment in the thread when you're ready to continue working on it 🙂

You can also catch me in [Slack](https://www.raycast.com/community) if you want to discuss 😄

2022-08-09 07:12 UTC, closed without merging