Add CanvasCast Extension
raycast/extensions pull request #209
Opened 2021-10-24 06:14 UTC by YodaLightsabr

## Description

Add Canvas LMS extension.

## Type of change

New extension

## Screencast

There isn't a lot to show because it's one command, but here it is. I also can't show the actual data because it has personal information.

![image](https://user-images.githubusercontent.com/76178582/138583074-b3d6fa42-2262-44f2-9946-aee19ae0d581.png)

Courses load a user's courses from https://canvas.instructure.com/doc/api/courses.html
Assignments load a user's TODO items from https://canvas.instructure.com/doc/api/users.html
Announcements load a user's announcements from https://canvas.instructure.com/doc/api/announcements.html

All colors are linked to the color of the course.

## Checklist

- [x ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x ] I checked that extension's icon has size of `512x512`

2021-10-27 12:53 UTC, pernielsentikaer requested changes
Hi @YodaLightsabr 💪 

Found a few suggestions and comments:

- Is it called Canvas or CanvasCast, it's mixed in the extension, could be nice to have it baseline.

Do you by any chance have a token I could try so I can test the rest of the functionality? Feel free to find me in the channel #extensions on [Slack](https://raycastcommunity.slack.com/)

2021-10-29 05:35 UTC, pernielsentikaer requested changes
Hi @YodaLightsabr 👋 

Thanks for the corrections, it's very close to launching 🚀 

*Comments and suggestions*
-  There is no handling of wrong URL/token - you can check #165 for a way to handle it visually.
- move api.js to src/ folder

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-10-31 01:34 UTC, maggie-j-liu commented
hiii! this extension looks super cool; i think it would be nice to add a readme that explains how to get the access token, and also add a warning about the access token breaking canvas' tos as explained [here](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2021-11-02 21:30 UTC, pernielsentikaer commented
@YodaLightsabr Do you need help with anything?

2021-11-02 22:19 UTC, YodaLightsabr commented
I'll have a few more test assignments added soon, I've just been really busy and haven't gotten around to it yet.

2021-11-12 18:15 UTC, pernielsentikaer commented
Hi @YodaLightsabr 👋 

 Sure! Just DM on Slack when you're ready 🧑‍🎤

And as @maggie-j-liu said, there should be a README.md file telling about the extension (and how to get token) and if anything not is compliant with the terms it should be added too: https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration

2021-12-22 13:40 UTC, fe9lix commented
Closing this PR due to inactivity – feel free to reopen later.

2021-12-24 02:53 UTC, YodaLightsabr commented
Thanks, closing it reminded me I hadn't updated it. I think I've just about finished adding all of the suggestions.

2021-12-24 08:26 UTC, fe9lix commented
@YodaLightsabr  Let me know if you want to reopen it here...

2021-12-25 04:46 UTC, YodaLightsabr commented
Yeah, I think it's ready to be reopened.

2021-12-27 06:33 UTC, pernielsentikaer commented
Hi @YodaLightsabr 

Let's reopen it and get it merged – we could call it “My Courses” instead, that would be a more sufficient title

2021-12-27 23:54 UTC, YodaLightsabr commented
> Hi @YodaLightsabr
> 
> Let's reopen it and get it merged – we could call it “My Courses” instead, that would be a more sufficient title

Do you mean in the courses section of the command?

2021-12-28 07:09 UTC, pernielsentikaer commented on extensions/canvascast/package.json
> +      "title": "Open Dashboard",
```suggestion
      "title": "My Courses",
```

2021-12-28 07:11 UTC, pernielsentikaer requested changes
Hi @YodaLightsabr 👋 

See my latest suggestion 😄

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-12-29 06:33 UTC, pernielsentikaer approved these changes
Hi @YodaLightsabr 👋 

I'm going to accept it and then will my colleague do a final review before it's finally merged 💪

2021-12-30 11:15 UTC, merged

2022-01-18 23:40 UTC, eliotbehr commented
@YodaLightsabr 

This is a very useful extension. I do have one suggestion: Can you please make the extension only show courses which we have bookmarked in Canvas. For students with many old, but still Canvas-enrolled courses, it takes up the entire CanvasCast "Enrolled courses" thing. E.g., I can't see any course with a letter after "B". By only showing "Bookmarked courses", it would allow us to easily access the courses we want as most accessible and hopefully prevent these past-enrolled courses from taking up the entire CanvasCast pop-up.

2022-01-18 23:42 UTC, YodaLightsabr commented
Oh yeah, I can totally relate to that. I have a ton of old courses and it wasn't until recently where they were dropped from my account. I'll take a look at this soon.

2022-01-18 23:50 UTC, eliotbehr commented
> Oh yeah, I can totally relate to that. I have a ton of old courses and it wasn't until recently where they were dropped from my account. I'll take a look at this soon.

Thanks so much for looking into this! For colleges like mine that are too lazy to drop them it would be super helpful haha

2022-01-19 01:31 UTC, YodaLightsabr commented
@eliotbehr if you could test something for me it would be a big help. Could you sign into your canvas and then GET `https://<YOUR_CANVAS_DOMAIN>/api/v1/courses` and compare it to the response of `https://<YOUR_CANVAS_DOMAIN>/api/v1/courses?enrollment_state=active`. I just want to know if adding the query param excludes your old courses.

2022-01-19 19:58 UTC, eliotbehr commented
@YodaLightsabr It did change it very slightly—with enrollment_state=active it removed one course that the school seemed to have explicitly unenrolled me, but all the old courses where I'm still "enrolled" are there. I also noticed that this API query seems to limit to retrieving 10 courses maximum.

Could this be a possible option to query?: api/v1/users/self/favorites/courses

2022-01-19 21:20 UTC, YodaLightsabr commented
Oh, I didn't see that. As long as it returns the same Course object, it should be an easy swap.

2022-01-25 01:41 UTC, eliotbehr commented
@YodaLightsabr 
Hey Yoda! Thank you so much for working on these changes! I saw that the extension was recently updated, and I re-installed it but I am still seeing the same old courses. Is there anyway I could help troubleshoot this—perhaps is it because of the API still?

2022-01-25 02:39 UTC, YodaLightsabr commented
Hmmm, that shouldn't be happening. Could you tell me the API outputs of the courses endpoint, and then the favorites endpoint, and then what you want to see in the extension? You can hide private course details, it would just be helpful for debugging.

2022-02-05 20:10 UTC, gronk-droid commented
@YodaLightsabr 
Hey there! I'm having the same issue with favorites here. My unfavorited courses in Canvas are still showing in the command.

<div class="grid-containter" style="display: grid; grid-template-columns: auto auto">
<div class="grid-item" style="text-align: center">
<img width="125" alt="Screen Shot 2022-02-05 at 3 02 31 PM" src="https://user-images.githubusercontent.com/58199738/152657148-6ac4a63a-5af3-4f80-bd52-cbb3e025d7ea.png">
</div>
<div class="grid-item">
<img width="69" alt="Screen Shot 2022-02-05 at 3 02 46 PM" src="https://user-images.githubusercontent.com/58199738/152657146-c5cdd456-be1c-417c-9857-3cebb121050d.png">
</div>
</div>

2022-02-05 20:18 UTC, YodaLightsabr commented
Ok, I think I've figured out how to only use the courses on the Dashboard and sort them in that order. I'll get started on implementing it.