Adding GitLab Docs extension
raycast/extensions pull request #2127
Opened 2022-06-29 12:18 UTC by saschaeggi

## Description

As an employee of GitLab I'd like to add this new GitLab Docs extension which adds the ability to search GitLab for the following:

- GitLab Docs
- GitLab Handbook
- Pajamas Design System (GitLab's Design System)

Original repo: https://gitlab.com/seggenberger/raycast-gitlab-docs

## Screencast

https://user-images.githubusercontent.com/5558166/176434318-9470e223-b221-436c-981a-9337d53429b0.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-07-05 07:50 UTC, pernielsentikaer requested changes
Hi @saschaeggi 👋 

Thanks for your contribution 🙂

I have some feedback for you to look into:

- Is it possible for Docs and Handbook to show some initial data like Pajamas does?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-07-05 07:50 UTC, pernielsentikaer commented on extensions/gitlab-docs/src/docs.tsx
> +          <ActionPanel.Section>
```suggestion
```

2022-07-05 07:50 UTC, pernielsentikaer commented on extensions/gitlab-docs/src/index.tsx
> +          <ActionPanel.Section>
```suggestion
```

2022-07-05 07:50 UTC, pernielsentikaer commented on extensions/gitlab-docs/src/pajamas.tsx
> +          <ActionPanel.Section>
```suggestion
```

2022-07-05 07:50 UTC, pernielsentikaer commented on extensions/gitlab-docs/src/pajamas.tsx
> +            <Action.OpenInBrowser title="Show Details" url={searchResult.url} />
This title is usually used when opening the Detail Panel; maybe use the default title?

2022-07-05 07:50 UTC, pernielsentikaer commented on extensions/gitlab-docs/src/index.tsx
> +            <Action.OpenInBrowser title="Show Details" url={searchResult.url} />
This title is usually used when opening the Detail Panel; maybe use the default title?

2022-07-05 07:50 UTC, pernielsentikaer commented on extensions/gitlab-docs/src/docs.tsx
> +            <Action.OpenInBrowser title="Show Details" url={searchResult.url} />
This title is usually used when opening the Detail Panel; maybe use the default title?

2022-07-06 10:20 UTC, saschaeggi commented
@pernielsentikaer I've updated Docs & Handbook to save the previous search. So it always shows the last search results instead of the empty screen. Also if nothing has been searched for it shows placeholder results.

For the Pajamas search: I grouped them by category, as we have them anyway in the Design System.

Can be reviewed again!

2022-07-12 09:18 UTC, saschaeggi commented
@pernielsentikaer any update on this?

2022-07-12 09:25 UTC, pernielsentikaer requested changes
Hi 👋 

I gave it a new spin and have a few comments for you 🙂

- Could you add [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)? With our new tool, it should be easy doing so 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-07-12 09:25 UTC, pernielsentikaer commented on extensions/gitlab-docs/package.json
> +      "title": "GitLab Handbook",
```suggestion
      "title": "Search Handbook",
      "subtitle": "GitLab",
```

2022-07-12 09:25 UTC, pernielsentikaer commented on extensions/gitlab-docs/package.json
> +      "title": "GitLab Docs",
```suggestion
      "title": "Search Documentation",
      "subtitle": "GitLab",
```

2022-07-12 09:25 UTC, pernielsentikaer commented on extensions/gitlab-docs/package.json
> +      "title": "Pajamas Design System",
```suggestion
      "title": "Search Design System",
      "subtitle": "Pajamas",
```

2022-07-12 10:02 UTC, saschaeggi commented
@pernielsentikaer can be reviewed again 🙂

2022-07-12 11:55 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2022-07-12 11:58 UTC, merged