fix: hypersonic preferences command
raycast/extensions pull request #2158
Opened 2022-07-01 08:37 UTC by prrrcl

## Description

Fix the extension command preferences 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-07-01 09:01 UTC, pernielsentikaer requested changes
Looks good to me, only have a single question that might be better for the UX 😄 

Let me know what you think

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-07-01 14:51 UTC, prrrcl commented on extensions/hypersonic/src/components/empty-list.tsx
> +            shortcut={{ modifiers: ['opt'], key: 'u' }}
why not? 🤗

2022-07-01 14:51 UTC, prrrcl commented on extensions/hypersonic/src/views/todo-list.tsx
>                      shortcut={{ modifiers: ['opt'], key: 'u' }}
why not? 🤗

2022-07-04 06:54 UTC, pernielsentikaer approved these changes
Let's get it merged 🔥 Thanks @prrrcl 🔥

2022-07-04 06:54 UTC, merged