Filamentphp documentation search
raycast/extensions pull request #2189
Opened 2022-07-05 16:30 UTC by aurawindsurfing

Adds filamentphp documentation search extension

## Description

Adds search extension for https://filamentphp.com/ admin panel documentation

## Screencast

<img width="935" alt="Screenshot 2022-07-02 at 14 03 56" src="https://user-images.githubusercontent.com/14302496/177002001-300345cc-ef72-4919-a713-2d97e3f00a48.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-07-06 11:42 UTC, pernielsentikaer requested changes
Hi @aurawindsurfing 👋 

Thanks for another contribution 💪 

- Should we consider just calling it Filament instead?

- Is it possible to have some initial items on the list so it's not all empty?

- You could consider a [List.EmptyView](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview) to make the UI even better (with the logo in 64x64)

- When searching for `test` it gives me this result, it's not really saying anything useful, could you look into this?

- Add [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)

![CleanShot 2022-07-06 at 13 36 23@2x](https://user-images.githubusercontent.com/38033107/177541591-53dca79b-683b-40d0-85ac-0e8dac8d933d.png)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-07-07 10:11 UTC, aurawindsurfing commented
I have no idea why exactly same code in both extensions throws error here:

`<List.EmptyView icon="empty-state-icon2.png" title="Whoops! We did not find any results!"/>`

I would appreciate if you @pernielsentikaer  can have a quick look at it as I'm puzzled by it.

2022-07-10 11:20 UTC, zepfietje commented
> > * Should we consider just calling it Filament instead?
> 
> I think it should stay as "filamentphp" the name is used interchangebly with "filament" but this gives is more reference to the actual package

I think the name should actually be changed to Filament. Let's ask the creator himself, @danharrin.

2022-07-10 17:10 UTC, danharrin commented
Yes, `Filament` is great

2022-07-11 13:33 UTC, zepfietje commented on extensions/filamentphp-doc-seach/src/filament.tsx
> +        showToast(Toast.Style.Failure, "Error searching filament documentation", err.message);
Shouldn't this be `Error searching Filament documentation`?

2022-07-11 13:33 UTC, zepfietje commented on extensions/filamentphp-doc-seach/package.json
> +      "description": "Searches the filament documentation",
`filament -> Filament`

2022-07-11 13:35 UTC, zepfietje commented
> @pernielsentikaer done!

@aurawindsurfing, could you have a look at my minor tweaks?

2022-07-11 13:37 UTC, pernielsentikaer commented on extensions/filamentphp-doc-seach/README.md
> +# Filament Admin Documentation Search
Good catch, I also found it last time confusing but forgot about it

2022-07-11 13:41 UTC, pernielsentikaer commented
I think I done the rest, could you take a last look @zepfietje 🙂

2022-07-11 13:41 UTC, aurawindsurfing commented
> I think I done the rest, could you take a last look @zepfietje 🙂

Thanks @pernielsentikaer

2022-07-11 13:46 UTC, aurawindsurfing commented
@pernielsentikaer what is the accepted practice then for not commiting node_modules to your repo without commiting .gitignore?

2022-07-11 13:48 UTC, pernielsentikaer commented
> @pernielsentikaer what is the accepted practice then for not committing node_modules to your repo without committing .gitignore?

We have [this file](https://github.com/raycast/extensions/blob/main/.gitignore) in the root of the repository (which should cover `node_modules` and other regular cases)

2022-07-11 13:59 UTC, aurawindsurfing commented
> I'm not sure if it was you @aurawindsurfing, but I can see that we both have the old folder structure and a new one, do you know how to clean (and removing the wrong one)

I'm sorry but no. I did not notice any differences

2022-07-11 14:18 UTC, zepfietje commented
> I think I done the rest, could you take a last look @zepfietje 🙂

Sure, @pernielsentikaer! Let me do a quick review.

2022-07-11 14:35 UTC, zepfietje reviewed
General remarks:

There are 2 folders: filamentphp-doc-search and filamentphp. Shouldn't this just be 1 named filament?

Also, the images are still named filamentphp-x.xxx which should also be changed to just filament.

Comparing to other extensions like Tailwind CSS and Laravel Livewire, I added some comments in this review regarding description and placeholder text. Not too sure what the Raycast guidelines are, but I tried to at least align it between extensions.

2022-07-11 14:35 UTC, zepfietje commented on extensions/filamentphp-doc-seach/src/filament.tsx
> +      searchBarPlaceholder={"Search Filament"}
In some other extensions the placeholder is just `Search...`

2022-07-11 14:35 UTC, zepfietje commented on extensions/filamentphp/README.md
> +# Filamentphp Admin Documentation Search
```suggestion
# Filament
```

2022-07-11 14:35 UTC, zepfietje commented on extensions/filamentphp/README.md
> +![Raycast Filamntphp Search](media/filamentphp.gif)
```suggestion
![Raycast Filament extension](media/filamentphp.gif)
```

2022-07-11 14:35 UTC, zepfietje commented on extensions/filamentphp/README.md
> +[Filamentphp](https://filamentphp.com) search
```suggestion
[Filament](https://filamentphp.com)
```

2022-07-11 14:35 UTC, zepfietje commented on extensions/filamentphp-doc-seach/package.json
> +      "description": "Searches the Filament documentation",
```suggestion
      "description": "Search the Filament documentation",
```

2022-07-11 15:46 UTC, aurawindsurfing commented
@zepfietje have a look here also once we are at the Laravel stuff 🚀

https://github.com/raycast/extensions/pull/2190

2022-07-11 16:57 UTC, zepfietje commented
> General remarks:
> 
> There are 2 folders: filamentphp-doc-search and filamentphp. Shouldn't this just be 1 named filament?
> 
> Also, the images are still named filamentphp-x.xxx which should also be changed to just filament.
> 
> Comparing to other extensions like Tailwind CSS and Laravel Livewire, I added some comments in this review regarding description and placeholder text. Not too sure what the Raycast guidelines are, but I tried to at least align it between extensions.

@pernielsentikaer @aurawindsurfing, could you still address these remarks?

2022-07-12 03:42 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2022-07-12 03:43 UTC, merged

2022-07-12 07:13 UTC, zepfietje commented
Seems like the entire extension folder is now named `filamentphp-doc-seach` instead of `filament`? (Even a typo in `seach -> search`). @pernielsentikaer

2022-07-12 08:03 UTC, aurawindsurfing commented
> Seems like the entire extension folder is now named `filamentphp-doc-seach` instead of `filament`? (Even a typo in `seach -> search`). @pernielsentikaer

I will leave it as it is for @pernielsentikaer do not want to do another PR, not sure of the procedure of already published extensions

2022-07-12 12:05 UTC, pernielsentikaer commented
It's something that we can handle but I have to change something behind the curtains before doing it, it's not really changing  anything in the end since end users won't even see it - but I'll add it to my list :)