Adds Alpine.js documentation search extension and removes second extension from PR
raycast/extensions pull request #2190
Opened 2022-07-05 16:40 UTC by aurawindsurfing

Adds Alpine.js documentation search extension

## Description

Adds search extension for https://alpinejs.dev/ documentation search

## Screencast

![Kapture 2022-07-04 at 21 36 22](https://user-images.githubusercontent.com/14302496/177374892-67a1c5a3-7277-4b26-b34c-fcbed8c73988.gif)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-07-06 11:27 UTC, pernielsentikaer requested changes
Hi @aurawindsurfing 👋 

Thanks for your contribution 💪 

I tested your extension and it works as expected, I have some suggestions and feedback for you 🙂

- Is it possible to have some initial items on the list so it's not all empty?

- You could consider a [List.EmptyView](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview) to make the UI even better (with the logo in 64x64)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-07-06 11:27 UTC, pernielsentikaer commented on extensions/alpinejs-doc-search/package.json
> +  "title": "Alpinejs",
```suggestion
  "title": "Alpine.js",
```

2022-07-06 11:27 UTC, pernielsentikaer commented on extensions/alpinejs-doc-search/package.json
> +  "description": "Documentation Search",
```suggestion
  "description": "Search Alpine.js documentation",
```

2022-07-06 11:27 UTC, pernielsentikaer commented on extensions/alpinejs-doc-search/package.json
> +      "title": "Search Alpine.js Documenantion",
```suggestion
      "title": "Search Documenantion",
```

2022-07-12 04:10 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2022-07-12 04:10 UTC, merged

2022-07-12 07:18 UTC, zepfietje commented
@aurawindsurfing, should this extension return the same results as searching on the docs site itself? Seems like some results are missing, like `x-modelable`.

2022-07-12 07:58 UTC, aurawindsurfing commented
@zepfietje good catch, just commited the fix as a separate PR https://github.com/raycast/extensions/pull/2238

2022-07-12 08:00 UTC, zepfietje commented
Wow, quick fix, thanks @aurawindsurfing!