New Extension: Library Genesis
raycast/extensions pull request #2250
Opened 2022-07-13 07:33 UTC by yz3440

## Description

An extension that allows searching books on [Library Genesis](https://libgen.is) and quickly opening the link in the browser, using the [libgen.js](https://github.com/dunn/libgen.js/) API.

## Screencast

![Screencast of Library Genesis Extension](https://raw.githubusercontent.com/yz3440/extensions/main/extensions/library-genesis/screencasts/library-genesis-1.png)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-07-13 14:49 UTC, danielsequeira requested changes
Hi @yz3440 👋 

Thank you so much for your PR.

I went through the code and left a few comments, nothing major.

Besides the comments you can also delete the screencasts folder and its content, since you don't really need it.

2022-07-13 14:49 UTC, danielsequeira commented on extensions/library-genesis/metadata/CHANGELOG.md
> +# Library Genesis Changelog
seems like a duplicated file from your already existing `CHANGELOG.md` in the project root, you can delete this one or move it to root and overwrite the other one

2022-07-13 16:58 UTC, yz3440 commented on extensions/library-genesis/src/components/book-item.tsx
> +
Sharp eye! It was a mistake.

2022-07-14 08:02 UTC, danielsequeira commented
@yz3440 all looks good, the only thing missing is removing the screencasts folder, since it is redundant considering the metadata one. Besides that you can change the date in the changelog to today's date and then I can go ahead and merge it 🙂

2022-07-14 14:38 UTC, yz3440 commented
@danielsequeira thanks! I had kept the screencasts folder because the image on top of this PR references the URL. I did it anyway. Now that I've removed it, the image src shows 404.

2022-07-14 14:38 UTC, danielsequeira commented on extensions/library-genesis/README.md
> +![Screencast](./screencasts/library-genesis-1.png)
Sorry @yz3440 I just noticed that you used the image in the screencasts folder in your README. for images used in the README you should place them in the `assets` folder. So one last thing to would be to add this image to your existing `assets` folder

2022-07-14 16:51 UTC, danielsequeira approved these changes

2022-07-14 16:51 UTC, merged