New Extension: Recurly
raycast/extensions pull request #2256
Opened 2022-07-13 19:19 UTC by kudrykv

## Description

Quickly search and inspect users and users' subscriptions.

## Screencast

![CleanShot 2022-07-13 at 21 33 08](https://user-images.githubusercontent.com/12697803/178807002-62ac6bf2-09fc-48a8-857e-a73b257b0616.png)
![CleanShot 2022-07-13 at 21 34 46](https://user-images.githubusercontent.com/12697803/178807186-906cb9eb-2fba-4b26-81a9-fb0dbf752fad.png)
![CleanShot 2022-07-13 at 21 35 27](https://user-images.githubusercontent.com/12697803/178807207-92b81c00-7ee7-4e26-8b6f-af1fc43cdcc3.png)
![CleanShot 2022-07-13 at 21 36 32](https://user-images.githubusercontent.com/12697803/178807224-2f417a1b-a711-40a7-8f21-363bd1d2ffca.png)
![CleanShot 2022-07-13 at 21 36 39](https://user-images.githubusercontent.com/12697803/178807237-2967c0d2-cdf4-4213-adcb-440d6bb17a2f.png)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-07-15 08:45 UTC, danielsequeira requested changes
Hi @kudrykv 

Thank you so much for your contribution.

I just went through the PR and added some comments, nothing major.

However I did notice that you are missing the preferences definition in package.json, in order to allow the users to set their Recurly API key and actually use the extension.

2022-07-15 08:45 UTC, danielsequeira commented on extensions/recurly/CHANGELOG.md
> +- `Accounts Search by Email` command.
no need for the punctuation at the end

2022-07-15 08:45 UTC, danielsequeira commented on extensions/recurly/README.md
> +To obtain an API key, sign in into your Recurly account and go to **Integrations > API Credentials**.
it would be nice to add an link to the recurly website

2022-07-15 12:33 UTC, kudrykv commented
@danielsequeira, thank you for your comment!

> However I did notice that you are missing the preferences definition in package.json, in order to allow the users to set their Recurly API key and actually use the extension

So, this is where Raycast API is limited. On the one hand, Raycast discourages configuring extensions via its commands. On the other hand, there is no (nice) UI in Raycast to do the extensive configuration I need.

I need to add multiple API keys, one per tenant. I need a domain prefix (to build URLs) and a user-friendly name for each API key. At this moment, Raycast doesn't give me the possibility to have some kind of dynamic configuration. I could use a text field and ask users to put the data I need in some predefined format (comma-separated, JSON-formatted, etc), but that is plain unfriendly.

Here, I've broken Raycast's suggestion and went with a separate command (`Tenant configuration`) that allows setting up multiple API keys (last two screenshots). The reason is the UI-friendly setup over requiring serializing data manually.

I'm open to suggestions on how such configuration can be improved. I'm sure I am not the only one who needs the ability to set up a dynamic number of API keys or similar data.

2022-07-18 15:07 UTC, danielsequeira requested changes
Hi again @kudrykv,

Sorry again for overseeing what you are trying to achieve with the extension. I just went through the code again and also tested the extension myself and left a few small comments. Mostly nitpicking stuff to keep it consistent with other extensions in our store.

Besides that and for the same reason mentioned above I think the UX and UI of the extension could be improved a bit. I added my comments to the screenshots below:

![recurly 2022-07-18 at 16 33 59](https://user-images.githubusercontent.com/12091319/179542408-eac90ff4-4604-4ed1-bab2-e00bc76f5ef0.png)
![recurly 2022-07-18 at 17 02 27](https://user-images.githubusercontent.com/12091319/179542418-74035b34-0ce9-4158-a28b-5a2e030ed21d.png)
![recurly 2022-07-18 at 16 53 38](https://user-images.githubusercontent.com/12091319/179542421-323af693-a6c6-400f-9386-7e5aeebc1eba.png)

2022-07-20 19:39 UTC, kudrykv commented
@danielsequeira, please take a look again. I've updated commands to perform a right-away search

2022-07-21 10:29 UTC, danielsequeira commented on extensions/recurly/CHANGELOG.md
> +## [Initial Version] - 2022-05-05
```suggestion
## [Initial Version] - 2022-07-21
```

2022-07-21 10:32 UTC, danielsequeira commented
@kudrykv thank you so much for the patience and all the changes.

Just a few tiny things missing before I merge it.

First could you apply the change I suggested to the CHANGELOG?

Also could you create some new screenshots and replace the existing ones? So they actually showcase the updates you did to the extension.

One last nitpicking suggestion, fine to leave it as it is if you don't want to change this now. But I think in the Search commands it would be a better UI if you didn't have the detail view right column presented when there are no results yet. And just show the no results text and icon in the middle of the screen.
<img width="1000" alt="recurly 2022-07-21 at 12 27 40" src="https://user-images.githubusercontent.com/12091319/180193401-73fc2923-d1e4-4537-91ff-e623b3c379c6.png">

2022-07-21 11:46 UTC, kudrykv commented
> Also could you create some new screenshots and replace the existing ones? So they actually showcase the updates you did to the extension

Yep! Did that; removed one similar screenshot. Are two screenshots enough? I remember seeing an upper limit of six, but I can't find it and whether the lower limit exists.

> didn't have the detail view right column presented when there are no results yet. And just show the no results text and icon in the middle of the screen

Mind = Blown. Didn't think of that. That's a great suggestion, thank you!

2022-07-21 12:40 UTC, danielsequeira approved these changes
All good 🙂 and 2 screenshots are enough. Thank you so much for all the time you invested in this PR!

2022-07-21 12:40 UTC, merged