new extension: Night Light
raycast/extensions pull request #2292
Opened 2022-07-18 05:34 UTC by devmoath

## Description

Manage Night Shift settings

## Screencast

<img width="1000" alt="Raycast 2022-07-18 at 08 31 50" src="https://user-images.githubusercontent.com/28797003/179450369-b27b0c54-f6b5-4df9-870e-fcd61f6d23e9.png">

<img width="1000" alt="Raycast 2022-07-18 at 08 32 06" src="https://user-images.githubusercontent.com/28797003/179450394-8b950a18-a2fe-4448-b055-b5a633e2b9ac.png">

<img width="1000" alt="Raycast 2022-07-18 at 08 32 23" src="https://user-images.githubusercontent.com/28797003/179450410-f5fce299-8f16-4491-a909-4ec503de5128.png">

<img width="1000" alt="Raycast 2022-07-18 at 08 32 16" src="https://user-images.githubusercontent.com/28797003/179450431-c259059e-95a9-446a-8ab7-544858be0dda.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-07-19 09:38 UTC, danielsequeira commented
Hi @devmoath 👋 

Thank you so much for your contribution.

I just tried the extension myself and since there's the dependency on the nightshift library, do you think it would be possible to make the error message more descriptive, for cases where people forgot to do it and maybe are not aware of it. Right now this happens:
<img width="1000" alt="Raycast 2022-07-19 at 11 37 13" src="https://user-images.githubusercontent.com/12091319/179719449-3f25e634-286e-4e41-b185-bdd7fe3f1089.png">

2022-07-19 09:43 UTC, devmoath commented
yeah sure. I will try to handle this case

2022-07-19 10:36 UTC, devmoath commented
this message will appear to users if they don't have nightlight installed in their system 

![CleanShot 2565-07-19 at 13 32 18@2x](https://user-images.githubusercontent.com/28797003/179730717-09333fd2-819b-45e2-b1e3-1110900f3b44.png)

2022-07-19 11:06 UTC, danielsequeira requested changes

2022-07-19 11:06 UTC, danielsequeira commented on extensions/night-light/README.md
> +Manage Night Shift settings
```suggestion
Manage Night Shift System Settings
```

2022-07-19 11:06 UTC, danielsequeira commented on extensions/night-light/package.json
> +  "description": "Manage Night Shift settings",
```suggestion
  "description": "Manage Night Shift System Settings",
```

2022-07-19 11:06 UTC, danielsequeira commented on extensions/night-light/package.json
> +      "description": "Change night shift color temperature",
```suggestion
      "description": "Change Night Shift color temperature",
```

2022-07-19 11:07 UTC, danielsequeira commented
@devmoath could you also add screenshots of the extension to a `metadata` folder, as specified here: https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots

2022-07-20 06:24 UTC, devmoath commented on extensions/night-light/package.json
> +      "description": "Turn night shift on until tomorrow",
from macOS User Guide : 

> Night Shift remains on until the next day or until you turn it off

I believe it will turned off at sunrise

2022-07-20 06:24 UTC, devmoath commented on extensions/night-light/package.json
> +  "icon": "command-icon.png",
sure I will fix it

2022-07-20 07:12 UTC, devmoath commented
@danielsequeira Thank you for your suggestions, I believe the PR is ready for review again :)

2022-07-20 08:35 UTC, danielsequeira commented
@devmoath thanks for the changes 🙂

only one last thing, your icon is not 512x512, the size of it is, but the icon imagine itself it is a big smaller than 512x512, having some margins around it, could you upload an icon image that is indeed 512x512?

2022-07-20 08:55 UTC, devmoath commented
Hopefully I did it right this time :)

2022-07-20 09:13 UTC, danielsequeira approved these changes

2022-07-20 09:13 UTC, merged