Add Sourcetree extension
raycast/extensions pull request #2351
Opened 2022-07-23 06:30 UTC by i906

## Description

View, search and open repositories in Sourcetree.

## Screencast

<img width="1000" alt="sourcetree-2" src="https://user-images.githubusercontent.com/866735/180593277-9f314ddc-7d7a-4b81-8514-ccedc8ae19ff.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-08-01 13:28 UTC, mattisssa requested changes
I got infinite loader here and some errors in console:

![CleanShot 2022-08-01 at 16 22 23@2x](https://user-images.githubusercontent.com/15333662/182158093-ea11c774-8b15-47d9-abfd-cfb6c290f38b.png)

I have Sourcetree installed, what could go wrong? I guess it's the path of `bin`. 
First: would be nice to handle this and show failure toast if something goes wrong
Second: how can we improve that? I haven't change anything since I installed the Sourcetree, so it seems like the default folder is wrong in preferences 🤔

2022-08-02 02:53 UTC, i906 commented
> I have Sourcetree installed, what could go wrong? I guess it's the path of `bin`. First: would be nice to handle this and show failure toast if something goes wrong

I'll update the toast to the failure state if any errors occur.

> Second: how can we improve that? I haven't change anything since I installed the Sourcetree, so it seems like the default folder is wrong in preferences 🤔

If you don't mind, can you share the full path of the `bin`, if any? I'll change the default bin path in the preference to that.

I installed Sourcetree using homebrew, so the bin file might have also been installed by homebrew.

I'll add a dialog similar to [Jetbrains extension](https://github.com/raycast/extensions/blob/c614a2dfc24aad9174e55bacc6053238781d77a7/extensions/jetbrains/src/recent.tsx#L148-L156) when the path is not available.

2022-08-02 09:32 UTC, mattisssa commented
>I installed Sourcetree using homebrew, so the bin file might have also been installed by homebrew.

I installed It from their website a long time ago 😄 

>If you don't mind, can you share the full path of the bin, if any? I'll change the default bin path in the preference to that.

`Error: Command failed: /opt/homebrew/bin/stree /Users/myname/proj/Raycast`

2022-08-03 15:40 UTC, mattisssa approved these changes

2022-08-03 15:40 UTC, merged