New Extension: Upstash
raycast/extensions pull request #2492
Opened 2022-08-05 08:28 UTC by ademilter

## Description

Displays your Upstash resources

## Screencast

<img width="862" alt="Screenshot 2022-08-05 at 11 25 44" src="https://user-images.githubusercontent.com/187922/183036097-184587da-6ab9-4047-8ac4-8226d97c3c43.png">

<img width="862" alt="Screenshot 2022-08-05 at 11 25 59" src="https://user-images.githubusercontent.com/187922/183036144-6aad0b42-a000-452c-bc01-9cb547224a2c.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-08-12 06:04 UTC, pernielsentikaer requested changes
Hi @ademilter 👋 

Thanks for your contribution 💪

I tested your extension and it seems to do the job very well 🔥 

I have a few suggestions:

- When credentials are wrong it would be cool with an error toast telling about it, is that possible?

![CleanShot 2022-08-12 at 08 00 53@2x](https://user-images.githubusercontent.com/38033107/184293957-999c361c-953e-4425-9cf0-2d4b715aa364.png)

I'm not sure about the naming of the commands, what about this? 
<img width="335" alt="CleanShot 2022-08-12 at 08 03 34@2x" src="https://user-images.githubusercontent.com/38033107/184294190-468b99b9-b8e1-4797-b6c7-e3a2f09a4ada.png">

2022-08-12 11:17 UTC, ademilter commented
hi @pernielsentikaer,
- I added the error message
- I fixed the command names as you said

Thanks for reviewing and giving feedback 😍

2022-08-15 08:16 UTC, pernielsentikaer requested changes
Hi @ademilter 👋 

Thanks for the corrections, it looks good! 🔥 

Could you add [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) too?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-08-15 11:06 UTC, pernielsentikaer requested changes
Hi 👋 

Seems like the margin is off on the screenshots, could you use this [guide](https://developers.raycast.com/basics/prepare-an-extension-for-store#how-to-use-it) to take them?

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-10-15 18:27 UTC, closed without merging