Google chrome add open tab feature
raycast/extensions pull request #256
Opened 2021-10-29 08:08 UTC by HenriChabrand

## Description

Add "New Tab" command, allowing users to open a new tab with a search query. Currently opened or recently closed tabs matching the query will be suggested to avoid opening an existing tab.

Best use with `cmd + T` shortcut!

## Type of change

- Bug fix / improvement for somebody else's extension. Extension author: @ bromanko

## Screencast

<img width="886" alt="Screenshot 2021-10-29 at 10 07 24" src="https://user-images.githubusercontent.com/18643714/139399174-6460a70a-118b-42af-879f-4ab0c54e0ebd.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

2021-11-01 07:50 UTC, pernielsentikaer requested changes
Hi @HenriChabrand 👋    Congrats on your first contribution! 👏 We are flattered that you chose the Raycast extensions repo for it.

*A few NITs and comments/suggestions before merging this beautifully gem* 💎 

- I don't think that "Open Tabs" should be in the list since it's already added to "Search Tabs" and it does only switch to the tab instead of opening a new tab 😄  

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-11-01 07:50 UTC, pernielsentikaer commented on extensions/google-chrome/src/google-chrome-new-tab.tsx
> +  return newTabOpened;
```suggestion
  return await runAppleScript(script);
```

The local variable is redundant here

2021-11-01 07:50 UTC, pernielsentikaer commented on extensions/google-chrome/src/google-chrome-new-tab.tsx
> +      var tabs = await getOpenTabs(useOriginalFavicon);
```suggestion
      let tabs = await getOpenTabs(useOriginalFavicon);
```

2021-11-01 07:50 UTC, pernielsentikaer commented on extensions/google-chrome/src/google-chrome-new-tab.tsx
> +  }
```suggestion
```

Remove this unused method

2021-11-01 09:01 UTC, HenriChabrand commented
Hello @pernielsentikaer 👋
Thanks for those feedbacks!

> * I don't think that "Open Tabs" should be in the list since it's already added to "Search Tabs" and it does only switch to the tab instead of opening a new tab 😄

I'm ust mimicking Chrome feature here:
<img width="537" alt="Screenshot 2021-11-01 at 09 56 33" src="https://user-images.githubusercontent.com/18643714/139647145-721437cd-3f21-4ef4-ab72-809c3c83860a.png">

As a user, you don't always remember if the page you want to reach is already open in one of your tabs.
Having the `Open Tabs` section here prevents a user from opening multiple time the same page – even though he didn't remember that the page was already opened somewhere.

2021-11-01 11:33 UTC, pernielsentikaer requested changes
Just found a few more, when they are corrected I'll do the last review and make it ready to get merged - thanks for your update 💯 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-11-01 11:33 UTC, pernielsentikaer commented on extensions/google-chrome/src/google-chrome-new-tab.tsx
> +          set newTab to make new tab ` + (queryText ? 'with properties {URL:"http://www.google.com/search?q='+queryText+'"}' : '') + `
```suggestion
          set newTab to make new tab ` + (queryText ? 'with properties {URL:"https://www.google.com/search?q='+queryText+'"}' : '') + ` 
```
HTTPS should be used here 🏎️

2021-11-01 11:33 UTC, pernielsentikaer commented on extensions/google-chrome/src/google-chrome-new-tab.tsx
> +                title={(!searchText ? "Open empty tab" : "Search \""+searchText+"\"")}
```suggestion
                title={(!searchText ? "Open Empty Tab" : `Search "${searchText}"`)}
```

Corrected naming and added better readability

2021-11-01 11:33 UTC, pernielsentikaer commented on extensions/google-chrome/src/google-chrome-new-tab.tsx
> +            title={(query ? "Search \""+query+"\"" : "Open empty tab")} />
```suggestion
            title={(query ? `Search "${query}"` : "Open Empty Tab")} />
```

Corrected naming and added better readability

2021-11-01 11:33 UTC, pernielsentikaer commented on extensions/google-chrome/src/google-chrome-new-tab.tsx
> +  return <ActionPanel.Item title="Open tab" icon={{ source: Icon.Eye }} onAction={handleAction} />;
```suggestion
  return <ActionPanel.Item title="Open Tab" icon={{ source: Icon.Eye }} onAction={handleAction} />;
```

2021-11-01 11:33 UTC, pernielsentikaer commented on extensions/google-chrome/src/google-chrome-new-tab.tsx
> +              title="Open in tab"
```suggestion
              title="Open in Tab"
```

2021-11-01 14:46 UTC, HenriChabrand commented
Thank you so much for your review @pernielsentikaer 🙌

2021-11-01 19:50 UTC, pernielsentikaer requested changes
Hi @HenriChabrand 👋 

Just gave it a spin again, and it looks gorgeous. I did, however, find a thing that would be awesome to have addressed before merging.

It looks like the class Tab and a few functions are duplicated 1:1 from another file within the repo.

It makes sense to move it to utils with export instead, and import it respectively in the two locations in order to reduce repetition of software patterns, also known as [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) - which make bug fixing a lot easier.

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions or need help modifying it

Very so close to merging! 💯

2021-11-02 19:56 UTC, PitNikola commented
@rgomezcasas, as an author of the original extension could you please take a look if you're okay with this addition?

2021-11-04 08:34 UTC, thomaspaulmann commented
@HenriChabrand Is the Search list item always showing up?

2021-11-04 10:29 UTC, pernielsentikaer commented
No @thomaspaulmann, default it starts like shown here

https://user-images.githubusercontent.com/38033107/140298407-ac8593e9-ddd5-44d6-a44d-c12a8e359bff.mp4

2021-11-04 17:19 UTC, HenriChabrand commented
Hello @thomaspaulmann 👋

The first item is always here yes – but it will either be use to `Open an Empty Tab` or `Search` the term if some are inputted 👍

2021-11-05 21:04 UTC, thomaspaulmann commented
> Hello @thomaspaulmann 👋
> 
> 
> 
> The first item is always here yes – but it will either be use to `Open an Empty Tab` or `Search` the term if some are inputted 👍 

Ah that makes sense. Also I didn't see that this is a separate command. Looking forward to it. I think it's a great addition.

2021-11-06 11:37 UTC, rgomezcasas commented
Awesome!!

2021-11-07 20:46 UTC, pernielsentikaer commented
Hi @HenriChabrand 👋 

Awesome contribution 💪 

A suggestion for later on could be if a domain is added (starts with www/http) then it would show "Go to" instead of search - this is not crucial to get it shipped but could be an awesome idea 💯

2021-11-08 08:31 UTC, merged