Add Producthunt extension
raycast/extensions pull request #26
Opened 2021-10-14 14:43 UTC by ragnorc

## Description

New Extension: Producthunt

## Type of change

- New extension

2021-10-14 16:04 UTC, loris commented on extensions/producthunt/package.json
> +  "description": "Read the latest stories of Hacker News.",
You probably meant Product Hunt here

2021-10-14 20:19 UTC, ragnorc commented on extensions/producthunt/package.json
> +  "description": "Read the latest stories of Hacker News.",
Yep, fixed!

2021-10-15 19:27 UTC, thomaspaulmann commented on extensions/producthunt/package.json
> +      "subtitle": "Product Hunt",
We tend to minimize repeatetive names here. Both are shown in the root search. How about naming it like this?
```suggestion
      "title": "Check Today's Hunts",
      "subtitle": "Product Hunt",
```

2021-10-15 19:28 UTC, thomaspaulmann requested changes
Nice addition. For next time, please attach a screenshot. Otherwise it's hard to reason about the extension. In this case it was easy because the code looks familiar ;-) 

I left a few minor comments to name the extension better to fit our UI guidelines.

2021-10-17 17:01 UTC, merged