Bitwarden Extension: Add Support for Apple Silicon Macs
raycast/extensions pull request #263
Opened 2021-10-29 18:23 UTC by pomdtr

2021-10-30 21:08 UTC, PSalant726 requested changes
IMO, this is a step backwards. It makes the preference more confusing for non-developers, and setting a custom `PATH` could have unforeseen user-specific side effects when executing commands via the extension. I think if you want to support M1 macs by default, changing the setting's default value is all that should be done here.

As an alternative solution to support both homebrew default installation paths: you could have the `Bitwarden` constructor run a `bw status` command using the old default path, and if the CLI isn't found, try again with the new default. Then, the installation path could be saved as state on the `Bitwarden` instance that gets created.

2021-10-31 10:16 UTC, pomdtr commented
Thanks for the feedback, your raised valid points

2021-11-02 08:33 UTC, pernielsentikaer requested changes
Hi @pomdtr 👋 💪 

I tested this extension on M1 and I can confirm that everything works as expected, didn't have the bitwarden-cli, but was guided and it was an easy setup.

*A few NITs and suggestions:*

- package.json line 29/37 (Add linebreak for better readability)
```suggestion
"description": "The client_id value seen in the My Account section of a Bitwarden web vault.\r\nMore info: https://bitwarden.com/help/article/personal-api-key/",
```

- hooks.ts line 8/12 (Corrected language)
```suggestion
const toast = await showToast(ToastStyle.Animated, "Logging in...", "It may take some time");
showToast(ToastStyle.Failure, "An error occurred during login!", "Please check your credentials");
```

- api.ts line 46 (Redundant return await)
```suggestion
return execa(this.cliPath, args, {env: this.env});
```

- It could be cool with a way to "log out" of the vault again to ensure security if needed.

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-11-02 18:14 UTC, pomdtr commented
@pernielsentikaer I added the ability to lock the vault using a second command.

2021-11-02 20:33 UTC, PitNikola commented on extensions/bitwarden/src/hooks.ts
> +    const toast = await showToast(ToastStyle.Animated, "Loggin in...", "It may takes some time");
```suggestion
    const toast = await showToast(ToastStyle.Animated, "Logging in...", "It may takes some time");
```

2021-11-02 20:35 UTC, merged

2021-11-02 21:23 UTC, pernielsentikaer commented
I found a few word translations that can be corrected for the next version @pomdtr 💪 

**package.json**
```Line 37:``` "description": "The client_secret value seen in the My Account section of a Bitwarden web vault.\r\nMore info: https://bitwarden.com/help/article/personal-api-key/",
```Line 62:``` "label": "Fetch vault items icon",
```Line 63:``` "description": "Use Google to fetch icons. If left unchecked, built-in icons will be used."

**hooks.ts**
```Line 9:``` const toast = await showToast(ToastStyle.Animated, "Logging in...", "It may take some time");

Tried your extension directly from the store and it worked very well! 💯

2021-11-03 00:06 UTC, PSalant726 commented on extensions/bitwarden/src/search.tsx
> +  }
We don't need to `map` over both the favorites and regular items below. We can DRY things up and slightly improve the latency by doing it here:
```suggestion
  for (const item of state?.items || []) {
  	const listItem = <ItemListItem
  		key={item.id}
  		item={item}
  		folder={item.folderId ? folderMap[item.folderId] : undefined}
  		refreshItems={refreshItems}
  	/>
  		
    item.favorite ? favoriteItems.push(listItem) : regularItems.push(listItem);
  }
```

2021-11-03 16:30 UTC, pomdtr commented on extensions/bitwarden/src/api.ts
> +const PATH = "/usr/local/bin:/opt/homebrew/bin"
I would prefer to use a set of expected bw cli path, but the bw cli does not work if `/usr/local/bin` is not in path :/

2021-11-03 16:31 UTC, pomdtr commented on extensions/bitwarden/src/api.ts
> +    if (!existsSync(this.cliPath)) {
No, because it could be:
- an empty string
- a faulty path (if the user provides a wrong path.

2021-11-03 16:32 UTC, pomdtr commented on extensions/bitwarden/src/api.ts
>    private async exec(args: string[]): Promise<execa.ExecaChildProcess> {
Not sure 😅