Fixes `undefined` property when checking for project tags.
raycast/extensions pull request #265
Opened 2021-10-29 23:07 UTC by rybertm

Closes #264

## Description

Fixed a bug when accessing project tags

## Type of change

- Bug fix / improvement for somebody else's extension. Extension author: @GH-handle

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

2021-10-30 05:09 UTC, pernielsentikaer requested changes
Hi @rybertm 👋 

I couldn't reproduce this error in #264 but I think if we can catch anything that could potentially break, let's handle it 💯 

I tested with an object containing no tag property, one with a tag and one with no tags.

If I manually remove the tags line from a project in the config file, then there is an error.

![XOT0ChJCHVsxXomb](https://user-images.githubusercontent.com/38033107/139520875-e6f590ae-4c11-4adb-bed0-f46e014bc990.png)

Maybe add something like ```accessoryTitle={tags?.join(", ")}``` to handle this scenario.

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-10-30 13:13 UTC, rybertm commented
Interesting, it happens to me because my project config file did not have a tag property at all.

> If I manually remove the tags line from a project in the config file, then there is an error.

Yeah, I didn't check for any other usage of the `tag` property and didn't debug it after my changes, so I missed this, sorry.

> Maybe add something like accessoryTitle={tags?.join(", ")} to handle this scenario.

Done.

2021-10-31 15:21 UTC, pernielsentikaer requested changes
This is almost ready to get shipped 🚢 

Could you please correct lines 60-61, a project can potentially be added with multiple tags giving the error: ```Warning: Encountered two children with the same key``` to this:

```
        {value?.map((project, index) => (
          <ProjectListItem key={project.rootPath+index} {...project} />
```

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-10-31 15:21 UTC, pernielsentikaer commented on extensions/visual-studio-code-project-manager/src/search-project-manager-projects.tsx
> +    const tags = project.tags?.length ?? 0 > 0 ? project.tags : ["[no tags]"];
```suggestion
    const tags = project.tags?.length > 0 ? project.tags : ["[no tags]"];
```

This should be sufficient in this case

2021-11-01 07:28 UTC, pernielsentikaer approved these changes
Should be good to be merged :rocket:

2021-11-03 07:25 UTC, pernielsentikaer commented
Are you also okay with this @MarkusLanger

2021-11-03 19:52 UTC, rybertm commented
Sorry, I'm not used to PR's, so I updated my main, which was the branch I made the changes, with upstream, so I just reset it back to the last commit I made. If there is anything wrong or if I need to change anything just let me know.

Again, sorry about that @pernielsentikaer.

2021-11-03 20:32 UTC, MarkusLanger commented
See also PR #258

2021-11-04 10:25 UTC, pernielsentikaer commented
@rybertm We have enabled package.json linter, could you please look into the error and correct it (preferences now needs a label)

2021-11-04 13:10 UTC, merged