Add new Extension
raycast/extensions pull request #2689
Opened 2022-08-26 15:29 UTC by virus231

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-08-28 11:43 UTC, thomaspaulmann commented
Can you please fill out the PR description? Thanks.

2022-08-28 13:19 UTC, virus231 commented
Add Description

2022-08-28 17:21 UTC, virus231 commented
> Can you please fill out the PR description? Thanks.
Add Description

2022-08-29 12:51 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪

Is there a way to get the data in English? This extension looks quite handy but the language is going to be a huge problem for most of the users 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-08-29 12:51 UTC, pernielsentikaer commented on extensions/frontend-cheatsheets/README.md
> +Help for developers
Could be cool with some more explanation here 🙂

2022-08-29 12:51 UTC, pernielsentikaer commented on extensions/frontend-cheatsheets/package.json
> +      "title": "Show List and Detail",
Did you forget to name your command?

2022-08-29 12:52 UTC, pernielsentikaer commented on extensions/frontend-cheatsheets/package.json
> +  "icon": "command-icon.png",
You forgot to change icon (and delete the default)

2022-10-28 19:34 UTC, closed without merging