add dou tu extension
raycast/extensions pull request #2731
Opened 2022-08-31 06:11 UTC by gaoyang

## Description

An extension for easy retrieval of web emoji images while chatting.
In China, this is a very common and convenient feature.

## Screencast

<img width="985" alt="image" src="https://user-images.githubusercontent.com/21971650/187606216-85035e03-dd42-4b46-9ec0-fcf3f78a4163.png">

<img width="977" alt="image" src="https://user-images.githubusercontent.com/21971650/187606263-e06c411c-ca8d-4140-95b9-9d992ae22ab6.png">

<img width="980" alt="image" src="https://user-images.githubusercontent.com/21971650/187606308-c82bc9fe-1e33-4233-8f96-270400deaa06.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-09-01 07:17 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪

After you change the language I'm able to check it out, at the moment when using the arrow keys it just closes Raycast and shows a message, not sure about what's the though about that is.

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-09-01 07:17 UTC, pernielsentikaer commented on extensions/dou-tu/src/services/clipboardService.ts
> +    showHUD("已复制到剪切板");
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2022-09-01 07:17 UTC, pernielsentikaer commented on extensions/dou-tu/package.json
> +  "title": "斗图",
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2022-09-01 07:17 UTC, pernielsentikaer commented on extensions/dou-tu/package.json
> +  "description": "An extension for easy retrieval of web emoji images while chatting.(上班时间斗个图🌟)",
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2022-09-01 07:17 UTC, pernielsentikaer commented on extensions/dou-tu/package.json
> +      "title": "斗图",
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2022-09-01 07:17 UTC, pernielsentikaer commented on extensions/dou-tu/package.json
> +      "description": "An extension for easy retrieval of web emoji images while chatting.(上班时间斗个图🌟)",
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2022-09-01 07:17 UTC, pernielsentikaer commented on extensions/dou-tu/README.md
> +上班时间斗个图 😄
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2022-09-01 07:17 UTC, pernielsentikaer commented on extensions/dou-tu/CHANGELOG.md
> +- 支持点击复制到剪切板
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2022-09-03 12:04 UTC, gaoyang commented
Hi @pernielsentikaer . I have modified the issue.

Also, would you consider adding a default unchecked option to the Grid component?
Currently it is causing me some inconvenience.

2022-09-06 07:59 UTC, pernielsentikaer commented
Hi @gaoyang 👋 

Why does it cause you issues when the first is selected?

2022-09-06 11:23 UTC, gaoyang commented
@pernielsentikaer 
I want to trigger something to be done on click, because there is always a default selected item.
causing the automatically selected item to not be clicked to by the user.

2022-09-08 09:27 UTC, gaoyang commented
For API suggestions I moved to
https://github.com/raycast/extensions/issues/2833

2022-09-09 07:54 UTC, pernielsentikaer requested changes
As stated in #2833 you have to use the [ActionPanel](https://developers.raycast.com/api-reference/user-interface/actions#api-reference) instead

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-09-12 12:34 UTC, pernielsentikaer commented
Thanks for the update, @gaoyang; still, having the option for clicking is not the behavior the rest of Raycast is having; therefore, can we remove it? Are you okay with just having the first option (like the rest of Raycast rely's on)

2022-09-12 13:27 UTC, gaoyang commented
I just want users to be able to find emojis easily and quickly when chatting.
Put more focus on chatting.
Please let my extension pass, thanks @pernielsentikaer ! 😁

2022-09-14 11:37 UTC, pernielsentikaer commented
The grid is not meant to be used like that UX-wise.

There’s focus/selection, and there’s an action. When you start intermingling them, it leads to unexpected interaction for most users.

Another problem is that the `select by click` option would also trigger when you just move the selection by keyboard; that would be pretty unexpected.

2022-09-14 15:34 UTC, gaoyang commented
@pernielsentikaer  Click operations have been removed.

2022-09-15 14:22 UTC, merged