Add V2EX Viewer Extension
raycast/extensions pull request #2790
Opened 2022-09-04 15:36 UTC by daikaiyu

## Description

A better extension for viewing V2EX topics and replies. Support two kinds of topic details display style, support to add proxy for access V2EX.

## Screencast

### Thumbnail view
<img width="1000" alt="v2ex-viewer-1" src="https://user-images.githubusercontent.com/78251524/188321317-0c245391-6639-46a4-9d4e-8ae3c867c282.png">

### Detailed view [V2EX Style]
<img width="1000" alt="v2ex-viewer-2" src="https://user-images.githubusercontent.com/78251524/188321322-fd709e28-2763-4e4c-a716-8c1147ec5a17.png">

### Detailed view [Raycast Style]
<img width="1000" alt="v2ex-viewer-3" src="https://user-images.githubusercontent.com/78251524/188321514-397039a8-420d-4214-b092-a8e18ff5d7a2.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-09-06 11:15 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪

I left a few minor corrections for you, can you look into this?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-09-06 11:15 UTC, pernielsentikaer commented on extensions/v2ex-viewer/src/components/TopicListItem.tsx
> +                tooltip: "主题回复数",
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2022-09-06 11:15 UTC, pernielsentikaer commented on extensions/v2ex-viewer/src/components/TopicListItemDetail.tsx
> +            <List.Item.Detail.Metadata.Label title="发布时间" text={getUnixFromNow(topic.created)} />
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2022-09-06 11:15 UTC, pernielsentikaer commented on extensions/v2ex-viewer/src/utils/markdown.ts
> +  } 条回复`;
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2022-09-07 06:57 UTC, daikaiyu commented
> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I left a few minor corrections for you, can you look into this?
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

Hello! I have removed localized content and added new command. Looking forward to your review and suggestions again.

2022-09-07 10:50 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2022-09-07 10:50 UTC, merged