Cal.com
raycast/extensions pull request #2802
Opened 2022-09-05 11:52 UTC by eluce2

## Description

Cal.com is an open-source alternative to Calendly. This extension lets you quickly copy your meeting links from Cal.com to your clipboard

## Screencast

https://share.cleanshot.com/8LrUfl

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-09-05 14:08 UTC, PeerRich commented
thank you so much!

2022-09-05 19:37 UTC, agustif commented
Link is private but https://github.com/calcom/api/pull/158

we're going to have a /me endpoint on API soon, which will return a user object with username alongside it.

It should be easy now to not have to ask for slug/username to the user?

2022-09-06 09:03 UTC, pernielsentikaer requested changes
Hi @eluce2 👋 

Thanks for another awesome extension, I added a few things, please be sure to check it out 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-09-06 09:03 UTC, pernielsentikaer commented on extensions/cal-com-share-meeting-links/src/services/cal.com.ts
> +  recurringEvent: null;
```suggestion
  recurringEvent: null | recurringEvent;
```

2022-09-06 09:03 UTC, pernielsentikaer commented on extensions/cal-com-share-meeting-links/src/services/cal.com.ts
> +interface CalEventTypeResp {
```suggestion
interface recurringEvent {
  freq: number;
  count: number;
  interval: number;
}

interface CalEventTypeResp {
```

2022-09-06 09:03 UTC, pernielsentikaer commented on extensions/cal-com-share-meeting-links/src/index.tsx
> +}
```suggestion
}

function Accessories(item: CalEventType) {
  let accessories = [];
  if (item.hidden) {
    accessories.push({ icon: Icon.EyeDisabled, text: "Hidden" });
  }

  if (item.recurringEvent) {
    accessories.push({ icon: Icon.Repeat, text: `Repeats up to ${item.recurringEvent.count} times` });
  }

  if (item.requiresConfirmation) {
    accessories.push({ icon: Icon.QuestionMarkCircle, text: "Requires confirmation" });
  }

  accessories.push({ icon: Icon.Clock, text: `${item.length} min` });

  return accessories;
}
```
Added multiple accessories, feel free to deny or polish 🙂
<img width="935" alt="image" src="https://user-images.githubusercontent.com/38033107/188593985-4e489be6-2591-42d0-95ef-54ed0b5296c2.png">

2022-09-06 09:03 UTC, pernielsentikaer commented on extensions/cal-com-share-meeting-links/src/index.tsx
> +          title={item.title}
```suggestion
          title={item.title}
          accessories={Accessories(item)}
```

2022-09-06 17:51 UTC, eluce2 commented
Thanks @pernielsentikaer! I like those changes, and I also added support for the freshly-released /me endpoint so we don't have to ask the user for their username as part of setup.

2022-09-07 07:09 UTC, pernielsentikaer approved these changes
Let's get the first version out @eluce2 🔥 Thanks for making this 🙂

2022-09-07 07:09 UTC, merged