New extension: Bike
raycast/extensions pull request #2815
Opened 2022-09-06 11:56 UTC by SKaplanOfficial

## Description

This extension adds commands for [Bike](https://hogbaysoftware.netlify.app/bike/). The following commands are provided:
- New Bike
  - Creates a new Bike document.
- New Bike from Clipboard
  - Creates a new Bike document from the clipboard contents.
- Append to Bike from Clipboard
  - Appends the clipboard contents to the end of the most recently active Bike document.
- New Bike from Template
  - Creates a new Bike document from a user-selected template.
- Minimize Bike
  - Minimizes all Bike windows.
- Close Other Bikes
  - Closes all Bike documents except the current one, asking whether to save them.
- Force Close Other Bikes
  - Closes all Bike documents except the current one, without saving them.
- Bike Background Color
  - Sets the background color of Bike windows.
- Bike Foreground Color
  - Sets the foreground color (text color) of Bike windows.
- Current Bike URL
  - Copies the URL of the current Bike document to the clipboard.

## Screencast

[Bike.webm](https://user-images.githubusercontent.com/7865925/188628421-5a3feca1-997c-4fe8-b091-3730f12e7e66.webm)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-09-06 12:05 UTC, thomaspaulmann commented
Oh cool, I've learned about Bike on a podcast. It's create to have an extension for it.

2022-09-06 13:02 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪

I did a quick review of the extension and it seems to be awesome, I don't know `Bike` yet, but it also looks like a cool thing 🙂
 
When a user doesn't have `Bike` it could be cool to show a toast telling it to the user (and maybe also the link) - two extension examples having it is [DEVONThink](https://www.raycast.com/bgnfu7re/devonthink) and [Eagle](https://www.raycast.com/Yukai/eagle) - could you try to implement something like that?

Right now it just dies:

<img width="935" alt="image" src="https://user-images.githubusercontent.com/38033107/188640317-bfd30dcb-ab5d-49ba-90ce-267b58a8eeef.png">

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-09-06 13:02 UTC, pernielsentikaer commented on extensions/bike/package.json
> +      "title": "Current Bike URL",
```suggestion
      "title": "Copy Bike URL",
```

2022-09-07 11:04 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for taking your time to look into this, I tested one of the commands and got this error:
![CleanShot 2022-09-07 at 13 02 49@2x](https://user-images.githubusercontent.com/38033107/188863079-99e718ce-f8e9-4ee5-b170-24b0eb8b29b5.png)

It seems like it's not doing as expected? Happened to many commands and other didn't even do anything

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-09-12 10:26 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2022-09-12 10:27 UTC, merged