Bitwarden
raycast/extensions pull request #2967
Opened 2022-09-21 05:09 UTC by pernielsentikaer

## Description

Added items folder names if any

## Screencast

![CleanShot 2022-09-21 at 07 08 42@2x](https://user-images.githubusercontent.com/38033107/191419032-ac39cc50-04db-4e78-9901-1d5b329cf25c.png)

2022-09-21 05:16 UTC, pernielsentikaer commented
The next step could be to use a dropdown to filter items + maybe add the folder to the keyword attribute.

2022-09-21 07:15 UTC, andreaselia commented
Looks good to me, nice work @pernielsentikaer 👍

2022-09-21 14:37 UTC, pomdtr requested changes

2022-09-21 14:37 UTC, pomdtr commented on extensions/bitwarden/src/search.tsx
>        const items = await bitwardenApi.listItems(sessionToken);
We should make those two requests in parallel here.
The startup time of the bitwarden extension is already pretty slow, so the last thing we want is too increase it.

2022-09-21 14:52 UTC, pomdtr commented
Thanks for the contribution @pernielsentikaer !

2022-09-22 12:53 UTC, pomdtr commented
Looks good to me ! Btw we should use the new usePromise api to simplify the code :)

2022-09-22 12:53 UTC, pomdtr commented
Also what do you think of adding a dropdown to filter by folder ?

2022-09-22 18:16 UTC, pernielsentikaer commented
Sounds like a good idea with usePromise, but I don't think I have enough time to do it at the moment, maybe a project for another?

[Dropdown](https://github.com/raycast/extensions/pull/2967#issuecomment-1253216533) is next step and will be in another PR when I have time, I don't think I can do it now so another might take that too

2022-09-22 18:21 UTC, merged