Optimize the display effect of the reply part of the details
raycast/extensions pull request #3011
Opened 2022-09-25 05:54 UTC by daikaiyu

## Description

A simple modification to better display the number of replies and loading status.And get rid of redundant preferences.

## Screencast

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-09-26 20:20 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your update 🔥 

Is there a reason why you're not deleting the code? Also, you have Chinese in your extensions, could you please change that? 😊

2022-09-26 20:20 UTC, pernielsentikaer commented on extensions/v2ex-viewer/src/utils/markdown.ts
> +  )} · ${getUnixFromNow(topic.created)} · ${topic.replies > 0 ? `${topic.replies} 条回复` : "目前尚无回复"}`;
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2022-09-26 20:20 UTC, pernielsentikaer commented on extensions/v2ex-viewer/src/utils/markdown.ts
> +      ? Code("回复加载中")
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2022-09-26 20:20 UTC, pernielsentikaer commented on extensions/v2ex-viewer/src/utils/markdown.ts
> +      : replies.map((reply) => getReplyMarkdownContent(reply, topic.member.id === reply.member.id)).join(LINE_BREAK);
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2022-09-27 09:43 UTC, daikaiyu commented
> Hi 👋
> 
> Thanks for your update 🔥
> 
> Is there a reason why you're not deleting the code? Also, you have Chinese in your extensions, could you please change that? 😊

I know this belongs to localization. Because this is a Chinese community, the content obtained is all in Chinese.

In order not to confuse the content displayed and to have a better user experience, I have to use Chinese to display detailed content.(Only used for `markdown` properties of detailed component)

I make sure that all operations related to Raycast will be shown in English. (preferences, actions, etc.)

2022-09-29 13:36 UTC, closed without merging