Add speedtest
raycast/extensions pull request #302
Opened 2021-11-06 10:06 UTC by tonka3000

## Description

Add speed test via speedtest.net cli. The user right now need to install the cli via homebrew.

## Type of change

- New extension

## Screencast

### Running speedtest
https://user-images.githubusercontent.com/3163807/140605799-518da6df-8678-449d-9c39-c0e0cc3cb9d4.mp4

### Help when speedtest.net cli could not be found
![CleanShot 2021-11-06 at 11 02 57@2x](https://user-images.githubusercontent.com/3163807/140605842-a8bb85a5-1ab6-4f8d-9b79-fa87912f550b.png)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

2021-11-09 05:19 UTC, pernielsentikaer requested changes
Hi @tonka3000 👋 

Awesome extension 💯 

Only a few suggestions left before we're ready to merge 💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-11-09 05:19 UTC, pernielsentikaer commented on extensions/speedtest/src/lib/utils.ts
> +}
```suggestion
```

Unused function, should be removed

2021-11-09 05:19 UTC, pernielsentikaer commented on extensions/speedtest/src/index.tsx
> +              setError(err instanceof Error ? err.message : "unknown error");
Redundant instanceof check

2021-11-10 06:44 UTC, pernielsentikaer requested changes
Hi @tonka3000 👋 

You're on fire 🔥 

- A thing I forgot to mention last time was that the "Copy to Clipboard" should maybe be a summary of the speedtest instead of just the list.item value.

- Just a thought, is it possible to add how many percentages completed, somehow so the user has an idea about how long time it takes, if the internet speed is pretty stable it feels like it's stuck.

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-11-11 09:30 UTC, pernielsentikaer commented
Hi @tonka3000 👋 

It looks good, but I will suggest using the subtitle in the list items for it instead, it might be more suitable. Do you think that's possible to implement? After that, I think we're ready to merge it 💪 😄

2021-11-11 13:37 UTC, tonka3000 commented
@pernielsentikaer 

> It looks good, but I will suggest using the subtitle in the list items for it instead, it might be more suitable. Do you think that's possible to implement? After that, I think we're ready to merge it 💪 😄

Do you refer to the progress bar?

2021-11-11 15:24 UTC, PitNikola commented
@tonka3000, how does it work on M1? It runs under Rosetta?

2021-11-11 16:04 UTC, pernielsentikaer commented
> Do you refer to the progress bar (%)?

Yes, the searchBarPlaceholder - could we move it to the corresponding item instead when it's running?

@PitNikola I'm on M1 and having no problems at all 😄

2021-11-11 16:37 UTC, tonka3000 commented
@PitNikola 

> @tonka3000, how does it work on M1? It runs under Rosetta?

Is also don't have a M1, but somebody on slack already tested it on M1. So it run at least on 2 M1 machines 😄 .

2021-11-11 17:22 UTC, PitNikola commented
Ok, then it's probably Rosetta. Ok, let's address that comment from Per about moving % progress info from the placeholder to subtitles of list items, and it's ready for merging.

Really nice extension, you've been quite creative! 🧑‍🎨

2021-11-11 18:44 UTC, tonka3000 commented
@PitNikola @pernielsentikaer 

https://user-images.githubusercontent.com/3163807/141351945-0973f9f4-9fc3-42a8-9020-2d4ac8cbd42d.mp4

2021-11-11 19:15 UTC, PitNikola commented
@tonka3000, how about hiding "100%" after it completes. Seems redundant, WDYT?

2021-11-11 19:39 UTC, tonka3000 commented
@PitNikola 

https://user-images.githubusercontent.com/3163807/141358495-0b8e444b-eb5a-4d0a-8aea-78844225b18e.mp4

2021-11-11 19:40 UTC, pernielsentikaer commented
Much better 💯 Tested everything again with great success 💪 

Let's get it merged, as @PitNikola said it's very creative 🥇

2021-11-12 08:12 UTC, PitNikola commented
Nice! If ping is often going to be so fast, I would consider not showing the progress for it. Feel free to address it in future PRs.

2021-11-12 08:13 UTC, merged

2021-11-12 08:16 UTC, PitNikola commented
Also another suggestion: show HUD toast after copying summary saying something like "Summary copied to clipboard"

2021-11-12 08:19 UTC, pernielsentikaer commented
I'm pretty sure that it's already showing a message

![EzA6HitllPljfWBe](https://user-images.githubusercontent.com/38033107/141433894-05374bf9-e3de-4426-98d6-de326320dc80.png)

2021-11-12 08:29 UTC, PitNikola commented
Ah, right. Hm, maybe I had some background where it was less visible...