Added Calendar extension
raycast/extensions pull request #306
Opened 2021-11-07 11:07 UTC by fuksman

2021-11-09 15:15 UTC, pernielsentikaer requested changes
Hi @fuksman 🚀 

Very nice extension, it has huge potential, and here is some feedback and nice-to-have features:

- Make so the calendar itself uses more of the space available.
- A hotkey to get back to "current month" 
- Add so its possible to see week numbers

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-11-09 15:15 UTC, pernielsentikaer commented on extensions/calendar/src/index.tsx
> +]
```suggestion
const days = [
  "`SUN` `MON` `TUE` `WED` `TEU` `FRI` `SAT`",
  "`MON` `TUE` `WED` `THU` `FRO` `SAT` `SUN`"
]
```

Escaping should not be necessary here.

2021-11-10 06:51 UTC, pernielsentikaer requested changes
Hi @fuksman 👋 

Thanks for the conversation about this extension in Slack, it was very constructive!

A single thing left:

- Provide icons to every element in the ActionPanel according to [the guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store#action-panel) 

When this is corrected everything should be ready to get merged 🥇 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-11-10 10:05 UTC, pernielsentikaer approved these changes
Hi @fuksman 

Thanks for the conversation about the extension, it was all my pleasure 🥇  I think we're ready to merge it 💣  Thanks for your contribution 💯

2021-11-10 14:24 UTC, PitNikola commented
<img width="806" alt="CleanShot 2021-11-10 at 14 05 26@2x" src="https://user-images.githubusercontent.com/4332171/141127499-7f465465-b3e0-4d3f-8be9-db6a35f206db.png">

Any thoughts on renaming the command to distinguish better from Apple's Calendar app? Not sure what could be a suitable name though... "Quick Calendar", "Monthly Calendar"...

Also few improvement suggestions for the future:
- Indicate current day (may be add bullet symbol at today's date, e.g. `•10`). This would help quickly navigating in current month.
- When running "Current Month" action when it's already presented, it would be nice to show a toast saying something like "Already showing current month". This way user won't be confused that nothing happens (it's not particularly clear). Check our built-in "Reset Raycast Window Position" command for similar behavior.

2021-11-10 14:51 UTC, pernielsentikaer commented
We discussed it because the name was "View Calendar" before and that didn't add anything good - Both "Quick" and "Monthly" sound good, I actually like Quick most of them.

Both are awesome ideas we could probably get done before the merge and close version 1 after that

2021-11-10 16:14 UTC, fuksman commented
@PitNikola, thanks for your suggestions!
1. Extension name is "Quick Calendar" now
2. Current day is marked with bullet symbol
3. Notification is shown when user continuously sets current month

<img width="862" alt="image" src="https://user-images.githubusercontent.com/2526238/141150157-4d7ad7b1-35b3-4a93-9f97-e4a5055d3814.png">

2021-11-10 16:15 UTC, PitNikola commented on extensions/calendar/package.json
> +      "title": "Calendar",
```suggestion
      "title": "Quick Calendar",
```

2021-11-10 16:47 UTC, merged