[New Extension]: Airsy
raycast/extensions pull request #3108
Opened 2022-10-03 13:44 UTC by piotrzaborow

## Description
Airsy is an air pollution checker in Polish cities.
It gathers data from GIOS API: https://powietrze.gios.gov.pl/pjp/content/api.
It shows data for all stations in Poland and for selected city (needs to be written in preferences).

## Screencast

[Link to screencast](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/7c602d4e-dbef-4fd3-aa77-b2c90a00ede3/Airsy.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20221003%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20221003T134334Z&X-Amz-Expires=86400&X-Amz-Signature=a7695c123d216ae73b5845227ca55f5ba1d590408890fdbc18bfcb5c46c9a08a&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Airsy.mp4%22&x-id=GetObject)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-10-06 12:53 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪

I tested your extension and have some feedback for you 😊

- You could use [useFetch](https://developers.raycast.com/utilities/react-hooks/usefetch) from @raycast/utils - with this you can get the response cached next time you open the list and refreshing in the background (`initialData: true`) 

- I never get any data from the two commands, are they really slow to respond?

- Seems like the list from `All Stations` crashes if you scroll a bit down
```
StationAddress:StationDetails.tsx:11:39

---
 8:   station: IStationResult;
 9: }
10: 
11: const StationAddress: FC<IProps> = ({ station }) => {
12:   const city = station.city.name;
13: 
14:   const ad = station.city.addressName.split("/")[0];
---
```

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-10-06 12:53 UTC, pernielsentikaer commented on extensions/airsy/CHANGELOG.md
> +
```suggestion
# Airsy Changelog

## [0.1.0] - 2022-10-03
- Added GIOS API as a service
- Added city selection in preferences
- Preparation for future translations

## [Initial Version] - 2022-09-29

```

2022-10-06 12:53 UTC, pernielsentikaer commented on extensions/airsy/src/index.tsx
> +    <List navigationTitle={`Airsy - AllStations`} isLoading={isLoading} isShowingDetail>
```suggestion
    <List isLoading={isLoading} isShowingDetail>
```
Don't change navigationTitle in the root command

2022-10-07 08:46 UTC, piotrzaborow commented
I will apply the suggestions.

Just one question about `useFetch`. 
As my flow works that way:
 -> fetch stations from 1st endpoint
 -> map through stations to get sensors data
 -> map through sensors to get values for air pollution

I want to wait for all data to be get and then display it. 
Any suggestion how to do it with `useFetch`?

With Promises, it is simple as `Promise.all`, with `useFetch` hook, I will constantly need to check if data has arrived and if none of the responses are errors. 

I can cache the data, but I would rather stick with Promises, they are more robust. Fetch API is also coming in Node.js 18, so there will no need to have any external deps like `node-fetch`.

2022-10-07 09:29 UTC, mathieudutour commented
You're right that `useFetch` might not be the most appropriate here since you need multiple calls - but you could use `useCachedPromise` to cache the results

2022-10-07 12:36 UTC, mathieudutour commented
it's cached forever, and refreshed when you open the command. It's there to make sure you don't have to wait for an api call before showing some data

2022-10-09 06:11 UTC, piotrzaborow reviewed
I've used useCachedPromise in my own hook `useStations`. That should do the trick, and it is very React-way 😄

2022-11-09 09:37 UTC, pernielsentikaer requested changes
Hi 👋 

Could you fix this last error and then I think we're ready to proceed 😊

2022-11-09 09:37 UTC, pernielsentikaer commented on extensions/airsy/src/components/IndexDetails.tsx
> +      {value && (
```suggestion
      {typeof value === "number" && (
```
Should fix the error: A `Metadata` only accepts `Metadata.Label`, `Metadata.Link`, `Metadata.Separator` and `Metadata.TagList` children. Ignoring "string".

2022-11-09 09:48 UTC, piotrzaborow commented
Done :)

2022-11-09 10:21 UTC, pernielsentikaer approved these changes

2022-11-09 10:21 UTC, merged