Add Copy Google Cloud Platform Icons extension
raycast/extensions pull request #311
Opened 2021-11-07 23:06 UTC by pomdtr

## Description

Easily copy google cloud platform icons in your favorite cloud architecture diagram software.

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/17577332/140665264-92b3833b-4e06-4048-9c56-5444ee649d3b.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

2021-11-09 15:27 UTC, pernielsentikaer requested changes
Hi @pomdtr 🧇 

Thanks for another addition for the extension repository 💪 

I only found a single thing that would make sense to correct, lets get it correct so were ready to merge the gem 💎 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-11-09 15:27 UTC, pernielsentikaer commented on extensions/copy-gcp-icons/package.json
> +      "subtitle": "Copy Product Icons from Google Cloud Platform",
```suggestion
      "subtitle": "Google Cloud Platform",
```

2021-11-12 18:24 UTC, pernielsentikaer commented
@pomdtr do you need help with anything?

2021-11-12 18:45 UTC, pomdtr commented
No help needed, I will revisit this next week

2021-11-12 20:55 UTC, pernielsentikaer commented
Good to hear, just wanted to make sure that you were not stuck @pomdtr

2021-11-14 20:37 UTC, pernielsentikaer requested changes
Hi @pomdtr 👋 

Thanks for the update 💪 We're pretty close to merging this one 💯 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-11-14 20:37 UTC, pernielsentikaer commented on extensions/copy-gcp-icons/package.json
> +      "title": "Copy GCP Icon",
```suggestion
      "title": "Copy Icon",
```

GCP is redundant since it's already added in the subtitle

2021-11-15 11:21 UTC, PitNikola commented on extensions/copy-gcp-icons/src/copy-gcp-icon.tsx
> +    />
Maybe let's use `Icon.Clipboard` icon here?

2021-11-15 11:47 UTC, merged