Downloads Manager: Added command "Reveal Latest Download in Finder"
raycast/extensions pull request #3148
Opened 2022-10-06 22:10 UTC by infused-kim

## Description

Added the command `Reveal Latest Download in Finder` to the `Downloads Manager` extension.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-10-08 16:44 UTC, thomaspaulmann requested changes
Nice addition, thanks! I left a few suggestions. I was torn apart naming the command to `Show Latest Download` to match better our `Show in Finder` action but wasn't sure. Any thoughts? Alternatively, you could add a keyword "show" to the command to make sure that others would find it easily in the root search.

2022-10-08 16:44 UTC, thomaspaulmann commented on extensions/downloads-manager/src/reveal-latest-download.tsx
> +    revealFile(latestDownload.path);
You should be able to use our built-in [showInFinder](https://developers.raycast.com/api-reference/utilities#showinfinder) function.

```suggestion
    await showInFinder(latestDownload.path);
```

2022-10-08 17:15 UTC, infused-kim commented
@thomaspaulmann thank you for the suggestions. I agree with everything and pushed a commit implementing them.

2022-10-08 19:08 UTC, thomaspaulmann commented
Looks like you have an issue with code formatting. Could you run prettier locally again and fix the issue? Then we're ready to merge.

2022-10-08 21:29 UTC, infused-kim commented
It should be good to go now. I have also updated the changelog.

2022-10-09 11:12 UTC, thomaspaulmann commented
Thanks, let's ship it! Also, would be great if you can add yourself as `contributor` in the `package.json`. This way you see the extension on your Raycast profile ;-)

2022-10-09 11:13 UTC, merged