Ray so
raycast/extensions pull request #321
Opened 2021-11-09 12:41 UTC by Garrett1Tolbert

## Description

This extension allows you to create a beautiful code snippet right from Raycast

## Type of change

- New extension

## Screencast

[Ray.so Extension Screencast](https://loom.com/share/10d9d2485be3417fa1a5dbbad29f3c5f)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

2021-11-10 05:01 UTC, pernielsentikaer requested changes
Hi @Garrett1Tolbert 👋 

That's a beautiful extension and only minor NITs before we're ready to merge it, very good job, well done 💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-11-10 05:01 UTC, pernielsentikaer commented on extensions/ray-so/src/create-a-snippet.tsx
> +        <Form.Dropdown.Item value="false" title="False" />
```suggestion
        <Form.Dropdown.Item value="true" title="Yes" />
        <Form.Dropdown.Item value="false" title="No" />
```

2021-11-10 05:01 UTC, pernielsentikaer commented on extensions/ray-so/src/create-a-snippet.tsx
> +        <Form.Dropdown.Item value="false" title="False" />
```suggestion
        <Form.Dropdown.Item value="true" title="Yes" />
        <Form.Dropdown.Item value="false" title="No" />
```

2021-11-10 05:01 UTC, pernielsentikaer commented on extensions/ray-so/src/create-a-snippet.tsx
> +      <Form.Dropdown id="langauge" title="Language" storeValue onChange={(language) => setCode({ ...code, language })}>
```suggestion
      <Form.Dropdown id="language" title="Language" storeValue onChange={(language) => setCode({ ...code, language })}>
```
Just a typo

2021-11-11 06:20 UTC, pernielsentikaer requested changes
Hi @Garrett1Tolbert  👋 

It looks a lot better already, we're close to merging it!

A thing I really think could be enhanced is the possibility to use enter as newline instead of submitting the form. See suggestions in code on how to archive this.

(requires npm open). Hopefully I didn't forget anything 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-11-11 06:20 UTC, pernielsentikaer commented on extensions/ray-so/src/create-a-snippet.tsx
> +import { useState } from "react";
```suggestion
import { useState } from "react";
import open from "open";
```

2021-11-11 06:20 UTC, pernielsentikaer commented on extensions/ray-so/src/create-a-snippet.tsx
> +import { Form, ActionPanel, OpenInBrowserAction } from "@raycast/api";
```suggestion
import { Form, ActionPanel, SubmitFormAction } from "@raycast/api";
```

2021-11-11 06:20 UTC, pernielsentikaer commented on extensions/ray-so/src/create-a-snippet.tsx
> +
```suggestion

  function handleSubmit() {
    open(url);
  }
```

2021-11-11 06:20 UTC, pernielsentikaer commented on extensions/ray-so/src/create-a-snippet.tsx
> +          <OpenInBrowserAction title="Create Snippet"  url={url} />
```suggestion
          <SubmitFormAction title="Create Snippet" onSubmit={handleSubmit} />
```

2021-11-11 19:49 UTC, pernielsentikaer approved these changes
Hi @Garrett1Tolbert 👋 

I think we're ready to get this 💎 merged, thanks for the contribution 💪

2021-11-13 14:18 UTC, PitNikola requested changes
Hey @Garrett1Tolbert, nice extension, thanks for creating it!

Few suggestions:
- Let's not use the default extension icon, it's not really for publishing in the store. Since you're connecting with our service, I went ahead and created an icon for you, feel free to just use it.
![ray-so-icon](https://user-images.githubusercontent.com/4332171/141646935-aa2122bb-0685-43c9-ab32-7bf414ae057c.png)
- Shall we add some validation for when nothing is entered? I would suggest showing a toast saying that text area is empty

Also I'm experiencing some issues with `open` code not actually working, will investigate and get back to you. In the meantime you can address other comments.

Thanks!

2021-11-13 14:18 UTC, PitNikola commented on extensions/ray-so/package.json
> +      "title": "Create Beautiful Images of Code",
```suggestion
      "title": "Create Image from Code",
```

I would suggest naming for similar [script command](https://github.com/raycast/script-commands/blob/master/commands/developer-utils/create-image-from-code.sh)

2021-11-13 14:18 UTC, PitNikola commented on extensions/ray-so/package.json
> +      "subtitle": "Raycast",
```suggestion
      "subtitle": "Ray.so",
```

2021-11-13 14:18 UTC, PitNikola commented on extensions/ray-so/package.json
> +  "description": "Create beautiful images of your code",
```suggestion
  "description": "Create beautiful images of your code using ray.so",
```

2021-11-14 02:44 UTC, Garrett1Tolbert commented
@PitNikola Not sure why the check isn't passing but one quick thing – I made the icon have a transparent background. Does it look good on your end?

2021-11-14 06:20 UTC, pernielsentikaer commented
Hi @Garrett1Tolbert 👋 

It seems like it has nothing to do with the logo, if checking the log it says that npm should be updated — can you handle that? We've added new validation since you last push 😄 

```
💥 Error: wrong 'lockfileVersion' in package-lock.json. Found "lockfileVersion: 1", expected: '2'. Update your 'npm' to v7.x
Error: 💥 Error: wrong 'lockfileVersion' in package-lock.json. Found "lockfileVersion: 1", expected: '2'. Update your 'npm' to v7.x 
Error: Process completed with exit code 1.
```

2021-11-14 17:57 UTC, pernielsentikaer commented
Hi @Garrett1Tolbert 👋 

I think the toast with an error message as @PitNikola mentioned could be the last thing, right now It's possible to send the form without writing anything which is not the best UX

2021-11-15 11:38 UTC, PitNikola commented
Sorry, I just realised that I exported the icon with the background. Here's transparent one:

![ray-so-icon](https://user-images.githubusercontent.com/4332171/141774873-741eea46-2785-4498-b0a7-03a30d9ae6db.png)

Now as for the issue that I had – I found the repro. Seems like `open` doesn't work when you have space in URL. This got broken on Big Sur when Apple decided to change its behavior for some reason. Could you please confirm that it happens whenever you have title with a space (e.g. when leaving it to default "Untitled 1")? To solve this you would need to escape characters like space before passing into `open` function.

2021-11-15 11:38 UTC, PitNikola requested changes
👆

2021-11-15 11:57 UTC, pernielsentikaer commented
> Sorry, I just realised that I exported the icon with the background. Here's transparent one:
> 
> ![ray-so-icon](https://user-images.githubusercontent.com/4332171/141774873-741eea46-2785-4498-b0a7-03a30d9ae6db.png)
> 
> Now as for the issue that I had – I found the repro. Seems like `open` doesn't work when you have space in URL. This got broken on Big Sur when Apple decided to change its behavior for some reason. Could you please confirm that it happens whenever you have title with a space (e.g. when leaving it to default "Untitled 1")? To solve this you would need to escape characters like space before passing into `open` function.

It totally blended in with my background 😄 !

2021-11-16 21:04 UTC, pernielsentikaer approved these changes
I never had any problems with spaces in title, this is before latest commit:
![QyITmArP8ZQ9vck7](https://user-images.githubusercontent.com/38033107/142065379-69276840-313c-418d-afef-13d5b39d4cdd.png)
![2HvfjRZnie58T7hn](https://user-images.githubusercontent.com/38033107/142065388-e8a7e962-a47c-463f-b0a9-d16100ec0d7f.png)

I retested it and the icon and the encoding works as well, nothing breaks, lets get it merged!

2021-11-16 22:01 UTC, merged

2021-11-17 04:29 UTC, Garrett1Tolbert commented
> Seems like Apple fixed this issue in Monterey, I've just double checked, so it's only reproducible on Big Sur.
> 
> Validation for empty text area is still missing, but perhaps you could add it in the follow up PR @Garrett1Tolbert?
> 
> Merging it. Thanks for you contribution!

I completely missed that. I'll do that now