New Extention: Crunchbase
raycast/extensions pull request #3216
Opened 2022-10-13 13:02 UTC by qdequele

## Description

Add a new extension, `crunchbase` that allows searching on the Crunchbase websites thanks to the Meilisearch search engine. 

## Screencast
![Crunchbase Raycast Screenshot](https://user-images.githubusercontent.com/6064892/195601867-afa6de8e-24d8-4b7c-ad53-9d403115425c.png)

https://user-images.githubusercontent.com/6064892/195601833-7dc060f7-5fbc-4b75-89f2-756e11bafde8.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-10-14 09:07 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* Seems like some of the images missing a source, could you look into this?

![CleanShot 2022-10-14 at 11 05 43@2x](https://user-images.githubusercontent.com/38033107/195808591-44a1add5-dd09-4611-ada3-49783c762ec7.png)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-10-14 09:07 UTC, pernielsentikaer commented on extensions/crunchbase/src/index.tsx
> +                  <Action title="Toggle Detail" onAction={() => setShowingDetail(!showingDetail)} />
Missing an icon

2022-10-14 15:15 UTC, qdequele commented on extensions/crunchbase/src/index.tsx
> +                  <Action title="Toggle Detail" onAction={() => setShowingDetail(!showingDetail)} />
Thanks, I've fixed this 👍

2022-10-14 15:16 UTC, qdequele commented
Hi @pernielsentikaer, thanks for the review. I've fixed the metadata image and the panel icon that was missing.

2022-10-15 06:24 UTC, pernielsentikaer requested changes
Hi 👋 

One thing I forgot to mention yesterday, do you think it's possible to add a throttle?

That would indeed make the UX even better 😊

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-10-17 00:56 UTC, qdequele commented
Hi, I just added the throttle on search. Thanks again for your review.

2022-10-17 05:01 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2022-10-17 05:07 UTC, merged