Update
raycast/extensions pull request #3224
Opened 2022-10-14 10:47 UTC by DominicVonk

## Description

Added homey extension

## Screencast

https://user-images.githubusercontent.com/3958086/195829062-c259fc4c-d435-4d14-ae90-1edf9e29f044.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-10-15 06:43 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* You should use the [isLoading property](https://developers.raycast.com/api-reference/user-interface/list#props) on the lists 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-10-15 06:43 UTC, pernielsentikaer commented on extensions/homey/src/flows.tsx
> +                              title="Start Flow"
Missing an icon here

2022-10-15 06:43 UTC, pernielsentikaer commented on extensions/homey/src/devices.tsx
> +                                title="Toggle"
Missing an icon here

2022-10-15 06:43 UTC, pernielsentikaer commented on extensions/homey/src/devices.tsx
> +                                title="On"
Missing an icon here

2022-10-15 06:43 UTC, pernielsentikaer commented on extensions/homey/src/devices.tsx
> +                                title="Off"
Missing an icon here

2022-10-15 08:54 UTC, DominicVonk commented
I added the icons and the loading

2022-10-16 20:45 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2022-10-16 20:46 UTC, merged