base64 extension v1
raycast/extensions pull request #337
Opened 2021-11-11 09:09 UTC by DanielSinclair

## Description

quick commands to encode or decode the clipboard contents from/to base64

## Type of change

- New extension

## Screencast

[Quick snippet demo clip](https://streamable.com/x4dw6t)

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I checked that extension's icon has size of `512x512`

2021-11-14 18:14 UTC, pernielsentikaer requested changes
Hi @DanielSinclair 👋 

Thanks for your PR, I have a few NITs as suggested and a comment:

- If the clipboard is empty, then I propose that it show a toast(showToast) with an error explaining that nothing is in the clipboard to help with the UX

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-11-14 18:14 UTC, pernielsentikaer commented on extensions/base64/package.json
> +  "description": "quickly encode or decode base64 from the clipboard",
```suggestion
  "description": "Quickly encode or decode base64 from the clipboard",
```

2021-11-14 18:14 UTC, pernielsentikaer commented on extensions/base64/package.json
> +      "description": "overwrite the clipboard contents with an encoded string",
```suggestion
      "description": "Overwrite the clipboard contents with an encoded string",
```

2021-11-14 18:14 UTC, pernielsentikaer commented on extensions/base64/package.json
> +      "description": "overwrite the clipboard contents with a decoded string",
```suggestion
      "description": "Overwrite the clipboard contents with a decoded string",
```

2021-11-17 21:31 UTC, pernielsentikaer commented
Hi @DanielSinclair 👋 

Do you need any help?

2021-11-18 22:51 UTC, DanielSinclair commented
Hey @pernielsentikaer. Implemented those UX changes this evening!

2021-11-19 06:37 UTC, pernielsentikaer requested changes
Hi @DanielSinclair 

Much better 💪 Really doing something good for the UX here! 💯 

IEkgdGhpbmsgaXQncyBhIGhhbmR5IHRvb2wgdGhhdCBjb3VsZCBiZWNvbWUgdmVyeSBoYW5keSBmb3IgbWFueSwgZ29vZCBqb2Ih 👏 

Just the last NIT and we're ready to ship it, I'm going to accept it later today regardless, but I give you a few hours to address it 😄

2021-11-19 06:37 UTC, pernielsentikaer commented on extensions/base64/src/util/clipboard.ts
> +  if (isEmpty(clipboard)) throw "clipboard is empty"
```suggestion
  if (isEmpty(clipboard)) throw "Clipboard is empty"
```
Just a nitpick 😄

2021-11-29 14:06 UTC, mattisssa approved these changes

2021-11-29 14:06 UTC, merged