Amazon AWS: Add a command to list SQS Queues
raycast/extensions pull request #339
Opened 2021-11-11 17:28 UTC by victor-falcon

## Description

New command to list SQS Queues.

## Type of change

- Bug fix / improvement for my extension

## Screencast

![image](https://user-images.githubusercontent.com/238766/141342314-8e43f8a7-8a06-4b11-bd1d-e70d50f735ac.png)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

2021-11-14 18:29 UTC, pernielsentikaer requested changes
Hi @victor-falcon 👋 

A few NITs and comments:

- What if there is 0 items in state.queues, then will the isLoading always be true?  (The same for both script) I think we have to find a better way - do you need help with that?

- I think there should be some graceful error handling when access is denied.

![SfrYWLCvNpYArJwf](https://user-images.githubusercontent.com/38033107/141693509-446c53e9-6dfd-45d5-bdee-6e189c5ce5bb.png)

```
AccessDenied: Access to the resource https://sqs.eu-west-1.amazonaws.com/ is denied.

    resp.error = util.error(new Error(), {
                            ^

Request.extractError:query.js:50:29

---
47:   if (data.Errors) data = data.Errors;
48:   if (data.Error) data = data.Error;
49:   if (data.Code) {
50:     resp.error = util.error(new Error(), {
51:       code: data.Code,
52:       message: data.Message
53:     });
---

Request.callListeners:sequential_executor.js:106:20
Request.emit:sequential_executor.js:78:10
Request.emit:request.js:686:14
Request.transition:request.js:22:10
AcceptorStateMachine.runTo:state_machine.js:14:12
<anonymous>:state_machine.js:26:10
Request.<anonymous>:request.js:38:9
Request.<anonymous>:request.js:688:12
Request.callListeners:sequential_executor.js:116:18
```

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-11-14 18:29 UTC, pernielsentikaer commented on extensions/amazon-aws/src/queues.tsx
> +          <CopyToClipboardAction title="Copy path" content={queue} />
```suggestion
          <CopyToClipboardAction title="Copy Path" content={queue} />
```

2021-11-15 19:01 UTC, victor-falcon commented
You're right! I'm going to check this, and I will update this pull request soon. Thanks!

2021-11-16 13:44 UTC, victor-falcon commented
@pernielsentikaer I have made the changed requested, but now it's failing in the build because "invalid author", why? 🤔

2021-11-16 15:29 UTC, grzegorzkrukowski commented
@pernielsentikaer @victor-falcon the problem with our automatic checks on 'author' has been just fixed and I re-triggered checks for this PR so it should not stop you anymore from merging. Sorry for the inconvenience.

2021-11-16 21:36 UTC, pernielsentikaer requested changes
Awesome @victor-falcon 💪 

Just a quick NIT before it should be ready to get merged, feel free to use suggested or find your own way to write it 💯 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-11-16 21:36 UTC, pernielsentikaer commented on extensions/amazon-aws/src/queues.tsx
> +    return (<Detail markdown="We can't find a valid [configuration and credential file](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html) in your machine." />)
```suggestion
    return (<Detail markdown="No valid [configuration and credential file] (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html) found in your machine." />)
```

2021-11-16 22:48 UTC, victor-falcon commented on extensions/amazon-aws/src/queues.tsx
> +    return (<Detail markdown="We can't find a valid [configuration and credential file](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html) in your machine." />)
Yes, done! 👍

2021-11-17 06:48 UTC, pernielsentikaer commented
Great @victor-falcon 💪 

Let get the gem shipped 💎 🚢 

Thanks for the update, much appreciated 💯

2021-11-17 06:49 UTC, pernielsentikaer approved these changes
Great @victor-falcon 💪 

Let get the gem shipped 💎 🚢 

Thanks for the update, much appreciated 💯

2021-11-17 09:07 UTC, merged