Add preferences to Emoji, and print nicer names
raycast/extensions pull request #341
Opened 2021-11-12 01:59 UTC by selfish

## Description

- Add preferences to Emoji extension to support Unicode versions, and search by shortcodes (example: ⚡ was "high voltage" only, now also "zap")
- Capitalize names for a nicer view

## Type of change

- Improvement for somebody else's extension. Extension author: @FezVrasta 

## Screencast

Before:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/7327741/141395700-c4e070fe-6eab-4320-80fa-8040f28270cc.png">

After:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/7327741/141395668-6ec29d40-48f1-44ac-9417-fcf4368e5792.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

2021-11-12 05:59 UTC, FezVrasta commented
👍

2021-11-12 11:21 UTC, victor-falcon commented
I was missing this because I can't find the pray emoji -> 🙏. Good job 😉.

2021-11-12 17:20 UTC, selfish commented
@victor-falcon note that this behavior is disabled by default.
We may want to opt for enabling that by default, but that's a core change, making the extension require interned connection from time to time.

2021-11-16 06:49 UTC, baptisteArno commented
> I was missing this because I can't find the pray emoji -> 🙏. Good job 😉.

Exactly the same 😂

2021-11-16 09:53 UTC, fe9lix requested changes
Hey @selfish – can you make the shortCodes pref optional? I think we should use the best default here and not require the user to select this on the extension onboarding screen.

2021-11-17 11:47 UTC, selfish commented
Hey @fe9lix - made it optional.
Thanks for the feedback, very good point :)

2021-11-17 12:04 UTC, fe9lix approved these changes

2021-11-17 12:04 UTC, merged