Adhan time update
raycast/extensions pull request #3419
Opened 2022-11-06 03:40 UTC by mzaien

## Description

Update to adhan prayer time extension to add a view mode addressing this [issue](https://github.com/raycast/extensions/issues/3417) 
while doing the new view I refactored the code to be more cleaner 
## Screencast

![CleanShot 2022-11-06 at 06 20 15](https://user-images.githubusercontent.com/43112535/200152903-22bcb851-f990-4218-8af0-b86e0e0fd762.gif)

## Checklist

- [ x ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ x ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ x ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ x ] I checked that files in the `assets` folder are used by the extension itself
- [ x ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-11-07 05:23 UTC, pernielsentikaer commented
Hi @mzaien 👋 

It seems like you have some conflicts, could you resolve them 😊

2022-11-07 12:34 UTC, pernielsentikaer requested changes
Hi 👋 

I left a single comment for you to address 😊

2022-11-07 12:35 UTC, mzaien commented on extensions/adhan-time/package.json
> +      "name": "adhan-menu",
Nice catch 👍, thank you will change it soon

2022-11-08 11:24 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2022-11-08 11:26 UTC, merged

2022-11-08 11:30 UTC, mzaien commented
> https://raycast.com/mzaien/adhan-time

Thanks