Add GoLink extension
raycast/extensions pull request #346
Opened 2021-11-12 19:08 UTC by micnncim

## Description

Adds an extension for [GoLinks](https://golinks.io) with the following commands:

- Search golinks: Lets users search golinks and then open a selected golink.
- Create golink: Lets users create a new golink.

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/21333876/141518995-a408d0f3-c4cf-418f-abbc-4cd555fa40c8.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

2021-11-12 21:23 UTC, pernielsentikaer requested changes
Hi @micnncim  👋 

Interesting, I haven't heard about GoLink before, it looks useful in some scenarios 💪 

Beside the suggestions, I would like to see some kind of error handling when an invalid token is added.

When the user is visiting “Search Links” command, then the loader keeps spinning and no message about invalid token (as seen in “Create Link” when creating with invalid credentials)

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-11-12 21:23 UTC, pernielsentikaer commented on extensions/golinks/package.json
> +      "title": "Search golinks",
```suggestion
      "title": "Search Links",
```

2021-11-12 21:23 UTC, pernielsentikaer commented on extensions/golinks/package.json
> +      "title": "Create golink",
```suggestion
      "title": "Create Link",
```

2021-11-12 21:23 UTC, pernielsentikaer commented on extensions/golinks/package.json
> +      "description": "Create golink",
```suggestion
      "description": "Create a new GoLink",
```

2021-11-12 21:23 UTC, pernielsentikaer commented on extensions/golinks/package.json
> +      "description": "Search golinks",
```suggestion
      "description": "Search your GoLinks",
```

2021-11-12 21:23 UTC, pernielsentikaer commented on extensions/golinks/src/create.tsx
> +  showToast(ToastStyle.Animated, 'Creating golink...')
```suggestion
  showToast(ToastStyle.Animated, 'Creating GoLink...')
```

2021-11-12 21:23 UTC, pernielsentikaer commented on extensions/golinks/src/create.tsx
> +          <SubmitFormAction title="Create golink" onSubmit={submit} />
```suggestion
          <SubmitFormAction title="Create GoLink" onSubmit={submit} />
```

2021-11-15 09:39 UTC, micnncim commented
@pernielsentikaer 

Thanks for your review!

> Beside the suggestions, I would like to see some kind of error handling when an invalid token is added.

Is it enough to validate just the length of a provided token before sending requests?

2021-11-15 10:27 UTC, pernielsentikaer commented
> > Beside the suggestions, I would like to see some kind of error handling when an invalid token is added.
> 
> Is it enough to validate just the length of a provided token before sending requests?

I'm not familiar with the API, but when you use the “Search Links” command, then it's just showing the loading indicator and nothing happens (unlike the create command). Some adds an “error” item to the list like it's done in #165 

![image](https://user-images.githubusercontent.com/38033107/141765639-63609158-dd99-4c18-8f69-88ecbcbab5f3.png)

When it's only showing the spinner, then there is no way to find out what's wrong.

2021-11-15 17:49 UTC, micnncim commented on extensions/golinks/src/list.tsx
> +        <List.Item icon={Icon.ExclamationMark} title="Error occurred" accessoryTitle={error.message} />
<img width="860" alt="Screenshot 2021-11-16 at 2 46 12" src="https://user-images.githubusercontent.com/21333876/141829891-9e77f6d9-c4d3-4a09-877b-fd84047e59b8.png">

2021-11-15 21:39 UTC, pernielsentikaer requested changes
Hi @micnncim 👋 

Thanks for the update, it looks a lot better! I think I would show something like the screenshot if 401 is received since it means that provided token is wrong, for the rest of the errors I should show a toast — does it make sense?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-11-16 10:56 UTC, micnncim commented
@pernielsentikaer Fixed at [`4e62a56` (#346)](https://github.com/raycast/extensions/pull/346/commits/4e62a56fd58d83003b1924d47419a9a576e555b0). It shows an invalid token error in the `List` component and shows toasts for other errors.

2021-11-16 19:36 UTC, pernielsentikaer commented
Hi @micnncim 👋 

Did you change anything in your end regarding API calls that might cause a “422 Unprocessable Entity” instead of “401 Unauthorized”

Error 422 should be: The contents of the request contains errors, such as required fields that are missing or validation errors 

Could you try this yourself with a wrong token to check this, does it also happen for you now?

2021-12-22 13:45 UTC, fe9lix commented
Closing this PR due to inactivity – feel free to reopen later.

2021-12-22 13:45 UTC, closed without merging

2022-01-31 08:30 UTC, micnncim commented
Couldn't work on this as I was busy. I'll fix issues and reopen this PR in a few days.