New Extension: MarginNote
raycast/extensions pull request #3481
Opened 2022-11-11 10:41 UTC by ourongxing

## Description

> Initial Version

It's used to enhance MarginNote.

## Screencast
<img width="1000" alt="Raycast 2022-11-11 at 17 21 56" src="https://user-images.githubusercontent.com/48356807/201323032-14a56955-e0e0-43e3-ba72-490c5948ef1e.png">
<img width="1000" alt="Raycast 2022-11-11 at 17 22 01" src="https://user-images.githubusercontent.com/48356807/201323177-4a313a9c-6e69-47c2-8c06-17cf6cccdfd1.png">
<img width="1000" alt="Raycast 2022-11-11 at 17 22 05" src="https://user-images.githubusercontent.com/48356807/201323232-db47ce16-37e3-47c6-a19d-4bb4032b9a44.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-11-14 03:21 UTC, ourongxing commented
@pernielsentikaer How long will it take?

2022-11-14 14:14 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* `Seach Notebook` doesn't seem to work, or I may have misconfigured it.

<img width="1930" alt="image" src="https://user-images.githubusercontent.com/38033107/201681646-e643360a-4413-41ab-9155-6daade215f51.png">

* The `Restart` command doesn't check whether MarignNote is installed
* Where do I find the preference values from `Take Note`
* You might need to update the README making some of this a bit more clear.

<img width="306" alt="CleanShot 2022-11-14 at 15 13 47@2x" src="https://user-images.githubusercontent.com/38033107/201681991-2bf48c6f-1d2f-4767-acb6-a342a9e844ea.png">

I'll add more when this is fixed, since it's not possible to test it yet 😊

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-11-14 14:14 UTC, pernielsentikaer commented on extensions/marginnote/package.json
> +      "title": "Restart MarginNote",
```suggestion
      "title": "Restart Application",
```

2022-11-14 14:14 UTC, pernielsentikaer commented on extensions/marginnote/package.json
> +      "description": "Restart marginote and skip the unsigned mnaddon alert",
```suggestion
      "description": "Restart MarginNote and skip the unsigned mnaddon alert",
```
mnaddon?

2022-11-14 14:14 UTC, pernielsentikaer commented on extensions/marginnote/src/searchNotebook.tsx
> +      markdown={`# ⚠️ Not found data source from MarginNote\n ## Please install MarginNote v3.7.21 or lastest and "Raycast Enhance" addon.`}
```suggestion
      markdown={`# ⚠️ Not found data source from MarginNote\n ## Please install MarginNote v3.7.21 or latest and "Raycast Enhance" addon.`}
```

2022-11-14 16:07 UTC, ourongxing commented
1. `Search Notebook` need install a MarginNote Plugin. Try to Click `Enter` to Download.
2. Actually all commands require MarginNote to be installed, if someone installs this extension, I don't think it's necessary to detect if Margin Note is installed.
3. `Take Note` preference is just a note url, For regular users of MarginNote, it's easy to get.

2022-11-14 16:10 UTC, ourongxing commented
> 
> * `Seach Notebook` doesn't seem to work, or I may have misconfigured it.
> 
1. `Search Notebook` need install a MarginNote Plugin. Try to Click `Enter` to Download.

> 
> * The `Restart` command doesn't check whether MarignNote is installed

2. Actually all commands require MarginNote to be installed, if someone installs this extension, I don't think it's necessary to detect if MarginNote is installed.


> * Where do I find the preference values from `Take Note`
> * You might need to update the README making some of this a bit more clear.

3. `Take Note` preference is just a note url, For regular users of MarginNote, it's easy to get.

2022-11-14 20:36 UTC, pernielsentikaer commented
> Search Notebook need install a MarginNote Plugin. Try to Click Enter to Download.
Then I get this error

<img width="407" alt="image" src="https://user-images.githubusercontent.com/38033107/201760437-e2f7da4b-3c15-40e6-ac14-27a0ecce4b5c.png">

> Actually all commands require MarginNote to be installed, if someone installs this extension, I don't think it's necessary to detect if MarginNote is installed.

If something throws an error then we need to handle it gracefully 😊

> Take Note preference is just a note url, For regular users of MarginNote, it's easy to get.

So how do I get it?

2022-11-15 07:07 UTC, ourongxing commented
> <img alt="image" width="407" src="https://user-images.githubusercontent.com/38033107/201760437-e2f7da4b-3c15-40e6-ac14-27a0ecce4b5c.png">

To install uncertified plug-ins in MarginNote, you need to turn on the switch in the figure. If the raycast extension passes, it will also be certified soon.
<img width="876" alt="image" src="https://user-images.githubusercontent.com/48356807/201851844-b3f07538-93eb-407f-86ac-6e6b49a1860d.png">


> If something throws an error then we need to handle it gracefully 😊

OKay, just wait for moment.

> So how do I get it?

OKay. Follow the picture.
<img width="443" alt="image" src="https://user-images.githubusercontent.com/48356807/201850926-c0ab816a-402d-4f68-986b-6d9b2e369e1e.png">

2022-11-15 08:11 UTC, pernielsentikaer requested changes
It still doesn't work after installing the extension (and I also tried to restart MarginNote), how can I help you debug, you can always catch me in [Slack](https://www.raycast.com/community)

<img width="1930" alt="CleanShot 2022-11-15 at 09 09 50@2x" src="https://user-images.githubusercontent.com/38033107/201864768-c91286a3-be08-40af-9c23-3f75c310b23b.png">

2022-11-15 08:41 UTC, ourongxing commented
> It still doesn't work after installing the extension (and I also tried to restart MarginNote), how can I help you debug, you can always catch me in [Slack](https://www.raycast.com/community)
> 
> <img alt="CleanShot 2022-11-15 at 09 09 50@2x" width="1930" src="https://user-images.githubusercontent.com/38033107/201864768-c91286a3-be08-40af-9c23-3f75c310b23b.png">

Maybe you need open a notebook first.

2022-11-16 04:46 UTC, pernielsentikaer requested changes
Hi 👋 

It seems like I got the most working, and also updated to the latest enhancement version.

I'm not sure the "skip" alert is working, since the extension might be unloaded the second you open MarginNote due to this setting.

![CleanShot 2022-11-16 at 05 44 30@2x](https://user-images.githubusercontent.com/38033107/202085942-49ada7e5-250d-42b4-a70c-77a5993a1845.png)

I think we should remove that from the code.

2022-11-16 05:57 UTC, ourongxing commented
![20221116135330](https://user-images.githubusercontent.com/48356807/202095373-7f2c497a-6276-4173-a4cb-dafbb8d701d5.gif)
<img width="680" alt="image" src="https://user-images.githubusercontent.com/48356807/202095658-4d2ca3d5-a3d5-4043-abdd-5df5718fb27d.png">

I think it still works. It just clicks `enter` when MarginNote opens

2022-11-16 06:15 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2022-11-16 06:15 UTC, merged