Adds Title extension.
raycast/extensions pull request #3491
Opened 2022-11-11 20:17 UTC by manovotny

## Description

Vercel's<sup>*</sup> [title.sh](https://title.sh) for Raycast.

Correctly capitalizes your titles as per [The Chicago Manual of Style](http://www.chicagomanualofstyle.org/home.html).

<sub>_\* Not affiliated with Vercel._</sub>

## Screencast

https://user-images.githubusercontent.com/446260/201424106-889f9a9a-965f-4496-97fe-ddd0a123aeed.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-11-15 05:17 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you 😊

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-11-15 05:17 UTC, pernielsentikaer commented on extensions/title/package.json
> +  "title": "Title",
A bit too generic title, `Title` doesn't really give anything, do you have any ideas?

2022-11-15 05:17 UTC, pernielsentikaer commented on extensions/title/package.json
> +      "title": "Capitalize",
Same here (since it don't Capitalize) 😊

2022-11-22 20:24 UTC, manovotny commented
@pernielsentikaer thanks for the feedback! I can see where it's a bit too generic. I'd like to ideate out loud together before making any changes so we can come to an agreement and get on the same page.

I guess I see two options:

1. Make it more hyper specific by calling it `title.sh` or `The Chicago Manual of Style Titles`.
2. Add `The Chicago Manual of Style` or `title.sh` to the [existing Change Case extension](https://www.raycast.com/es183923/change-case).

Thoughts?

2022-11-30 10:18 UTC, pernielsentikaer commented
How different is it from the current `titleCase` in change-case?

2022-11-30 15:55 UTC, manovotny commented
The Chicago Manual of Style can have slightly different rules. Here's an example below. Notice the word `some`.

<img width="1689" alt="CleanShot 2022-11-30 at 09 54 09@2x" src="https://user-images.githubusercontent.com/446260/204845773-89f9d2e6-cf28-4b38-b5b7-2b804dc66e4b.png">

2022-11-30 19:03 UTC, pernielsentikaer commented
Ah, yes, that's not the same at all.

@es183923, what do you think about adding that? It might require another library to add it, though.

2022-12-15 08:39 UTC, pernielsentikaer commented
Giving a last ping @es183923 😊

2023-01-03 13:56 UTC, pernielsentikaer commented
Sorry for missing this @manovotny - what is your default use case for this scenario?

Does it match how the `usecase extension` is doing it, or?

2023-01-17 15:23 UTC, manovotny commented
> Sorry for missing this @manovotny - what is your default use case for this scenario?
> 
> Does it match how the `usecase extension` is doing it, or?

@@pernielsentikaer not quite, but this PR could be changed to act like it. As you can see in the video above, it was expecting text to be typed into an input vs. being in the clipboard already. That is the only difference, but it could be changed to act exactly like Change Case. Or again, a completely separate plugin. Totally your call.

2023-01-18 05:14 UTC, pernielsentikaer commented
What about a separate extension with two commands, input and one with (clipboard/selected text) - this and a less generic title/description would do it for sure 💯

2023-01-30 04:01 UTC, es183923 commented
i suggest a separate extension, emphasizing on that it follows the chicago format

2023-02-13 04:27 UTC, pernielsentikaer commented
Can we update the title and maybe also the logo to not just use the same as the official [Vercel extension](https://www.raycast.com/vercel/vercast)

2023-03-06 06:04 UTC, closed without merging