Music extension
raycast/extensions pull request #353
Opened 2021-11-13 17:04 UTC by Rawnly

## Description
Little extension (like the spotify one) to handle media controls for the Music app.

## Type of change
- New extension

## Screencast
![CleanShot 2021-11-13 at 17 57 25](https://user-images.githubusercontent.com/16429579/141652256-2414bb23-4faa-4f5a-a612-70f1dae4a535.png)

## Checklist
- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

2021-11-16 10:37 UTC, fe9lix requested changes
Hey @Rawnly – thanks for the contribution. I've left some smaller comments...

2021-11-16 10:37 UTC, fe9lix commented on extensions/music/package.json
> +  "description": "Manage apple music",
```suggestion
  "description": "Control the Apple Music app with your keyboard.",
```

2021-11-16 10:37 UTC, fe9lix commented on extensions/music/package.json
> +      "description": "Plays current track in Music.",
```suggestion
      "description": "Play current track in Music.",
```

2021-11-16 10:37 UTC, fe9lix commented on extensions/music/package.json
> +      "description": "Skips to the next track in Music.",
```suggestion
      "description": "Skip to the next track in Music.",
```

2021-11-16 10:37 UTC, fe9lix commented on extensions/music/package.json
> +      "description": "Skips to the previous track in Music.",
```suggestion
      "description": "Skip to the previous track in Music.",
```

2021-11-16 10:37 UTC, fe9lix commented on extensions/music/src/util/controls.ts
> +export const getCurrentTrack = (): TE.TaskEither<Error, Readonly<TrackInfo>> => {
Is that function used somewhere?

2021-11-18 07:55 UTC, fe9lix commented
Hey @Rawnly – is the PR finished from your side?
I was wondering about the code around getting the "Current Track" info, similar to the Spotify commands.
I guess this should either be a new command or the code should be removed.

2021-11-18 07:56 UTC, Rawnly commented
@fe9lix I'm going to remove it in a few minutes! Sorry for delay 😅

2021-11-18 07:56 UTC, Rawnly commented
I'm going to push the latest in a few minutes! I've added a new command for it!

2021-11-18 10:52 UTC, fe9lix approved these changes

2021-11-18 10:52 UTC, merged