Add: Webflow Extension
raycast/extensions pull request #3537
Opened 2022-11-15 18:12 UTC by vurhd

## Description

This extension gives you shortcuts over common Webflow project tasks to help save you time! Open any project from anywhere. Site settings and more.

## Screencast

https://user-images.githubusercontent.com/32440403/201994752-50a416ff-490d-407a-b5fa-7bee7ffd00bf.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-11-16 13:11 UTC, pernielsentikaer requested changes
I tried to access this link: https://www.peeks.co/raycast/auth but it just gives me a 404 page, can you look into this @vurhd 😊

2022-11-16 13:31 UTC, vurhd commented
Hey @pernielsentikaer, check now, please. Sorry, I forgot to enable "cleanUrls" so it looked for .html at the end of the URL.

2022-11-22 13:13 UTC, vurhd reviewed
@pernielsentikaer, the link should be accessible now.

2022-11-29 07:04 UTC, pernielsentikaer approved these changes

2022-11-29 09:02 UTC, merged