Add new extension: Flaticon — Search Icons
raycast/extensions pull request #3586
Opened 2022-11-18 16:04 UTC by kudrykv

## Description

Add a new extension that allows searching for icons on the [flaticon.com](flaticon.com)

## Screencast

https://user-images.githubusercontent.com/12697803/202748313-8c5b15c7-3c9e-4192-b526-f67ad4268bc4.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-11-22 04:23 UTC, pernielsentikaer commented
Hi @kudrykv 👋 

Seems like you placed your extension in the wrong folder (/extensions/flaticon/flaticon), could you move it out to /extensions/flaticon? 😊

2022-11-22 10:05 UTC, kudrykv commented
@pernielsentikaer whoops. Fixed!

2022-12-13 08:51 UTC, kudrykv commented
@pernielsentikaer could you please look into this PR?

2022-12-13 09:10 UTC, pernielsentikaer requested changes
Hi 👋 

Sorry that it slipped, I tested the extension, and it works as expected - I think I would add some inset and columns like suggested 😊

2022-12-13 09:10 UTC, pernielsentikaer commented on extensions/flaticon/src/commandSearch.tsx
> +    <Grid isLoading={isLoading} onSearchTextChange={setSearch} throttle>
```suggestion
    <Grid isLoading={isLoading} onSearchTextChange={setSearch} inset={Grid.Inset.Medium} columns={8} throttle>
```

2022-12-13 09:43 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2022-12-13 09:43 UTC, merged