Add DAWA (Denmarks Address Web API) extension
raycast/extensions pull request #3714
Opened 2022-11-29 21:43 UTC by SimonJ

## Description

This extension let's the user that works with Danish addresses search for unique address id's by using the https://dawadocs.dataforsyningen.dk/ API (Denmarks Addresses Web API)

All internet providers in Denmark use this API and a lot of other big companies use this API to get information about Danish addresses.

You can use this address ID to test with: **0a3f5081-c522-32b8-e044-0003ba298018**

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-11-29 22:08 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* Seems like your metadata images are not made on a retina display, could you make it on your MacBooks display? If it's already done I might be able to help
* Can we figure out an English word for `adgangsadresseid`

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-11-29 22:08 UTC, pernielsentikaer commented on extensions/dawa/package.json
> +  "title": "Search Through The Danish Address Web API",
```suggestion
  "title": "DAWA - Danish Address Web API",
```

2022-11-29 22:08 UTC, pernielsentikaer commented on extensions/dawa/package.json
> +      "subtitle": "Search Denmarks addresses by adgangsadresseid",
```suggestion
      "subtitle": "DAWA",
```

2022-11-29 22:08 UTC, pernielsentikaer commented on extensions/dawa/src/index.tsx
> +  * **Postnr navn:** ${data?.postnummer.navn ?? "N/A"}
Keys should be in US English, data can be what the API returns

2022-12-01 15:46 UTC, SimonJ commented
@pernielsentikaer Thanks for review Per 🙏 
Still hard with the **adgangsadresseid** I changed it in the markdown output. but it should still be in the "key" option so the user can see it's that key the extension wants to have, right?

2022-12-06 09:26 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2022-12-06 09:32 UTC, merged