[open-in-visual-studio-code] Also work with VSCodium
raycast/extensions pull request #3765
Opened 2022-12-02 14:49 UTC by chohner

## Description
Enables [VSCodium](https://github.com/VSCodium/vscodium) to open the found folder

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-12-02 20:52 UTC, thomaspaulmann requested changes
Thanks for the addition, this is great. I left a comment to improve the logic for detecting VSCodium.

2022-12-02 20:52 UTC, thomaspaulmann commented on extensions/open-in-visual-studio-code/src/index.ts
> +  );
This logic can have different results, depending on the order of the applications. Also, what happens to people that have both versions installed? 

I would suggest to do the following:
1. Search for VS Code and VS Codium separately
2. Combine the results with an optional ternary operator. 

Alternatively, you can order the applications by bundle identifier and then use `find` as you do. An improvement could be to add a preference to the extension as a dropdown to select which version of VS Code should be used. By default, you could have an "automatic" way that prefers VS Code over Codium.

2022-12-05 17:40 UTC, chohner commented
The last commit adds a dropdown menu to the preferences (which defaults to `VSCode`)

<img width="302" alt="Screenshot 2022-12-05 at 18 38 35" src="https://user-images.githubusercontent.com/8014374/205704954-22b7fca6-d440-4132-b921-0d5fbf40adad.png">

Does this match what you expect @thomaspaulmann ?

2022-12-14 17:32 UTC, thomaspaulmann commented
Looking good! Thanks for the contribution 👏

2022-12-14 17:32 UTC, merged