add liba-ro
raycast/extensions pull request #3769
Opened 2022-12-02 18:29 UTC by neemspees

## Description
This is an extension to shorten and URL using the liba.ro API.
The API is public and does not require any settings.

## Screencast
![screenshot-1](https://user-images.githubusercontent.com/66001727/205361252-85bdd971-141c-46fe-bc9a-4adf59a19823.png)
![screenshot-2](https://user-images.githubusercontent.com/66001727/205361261-2de13d7e-ed28-49e9-82e5-c885cd3aa255.png)
![screenshot-3](https://user-images.githubusercontent.com/66001727/205361264-4417396e-ad81-40e5-b0df-0aba4421c9d3.png)

## Checklist
- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-12-06 12:36 UTC, pernielsentikaer commented on extensions/liba-ro/src/index.tsx
> +}
Added reset on submit

```suggestion
import { Form, ActionPanel, Action, showToast, Clipboard, Toast } from "@raycast/api";
import axios from "axios";
import { useState, useRef } from "react";

type Values = {
  url: string;
  expires: Date;
};

export default function Command() {
  const [urlError, setUrlError] = useState<string | undefined>();
  const [expiresError, setExpiresError] = useState<string | undefined>();

  const URLFieldRef = useRef<Form.TextField>(null);
  const datePickerRef = useRef<Form.DatePicker>(null);

  const change = () => {
    setUrlError(undefined);
    setExpiresError(undefined);
  };

  const handleSubmit = async (values: Values) => {
    let date = values.expires;

    const toast = await showToast({
      style: Toast.Style.Animated,
      title: "Shortening URL...",
    });

    if (!date) {
      date = new Date();
      date.setFullYear(date.getFullYear() + 1);
    }

    axios
      .post(
        "https://liba.ro/api/v1/shorten",
        {
          url: values.url,
          expiresAt: date.toISOString(),
        },
        {
          headers: {
            "Accept-Encoding": "application/json",
          },
        }
      )
      .then((response) => {
        const shortened = response.data;

        Clipboard.copy(shortened);

        URLFieldRef.current?.reset();
        URLFieldRef.current?.focus();
        datePickerRef.current?.reset();

        toast.style = Toast.Style.Success;
        toast.title = "Short URL copied to clipboard!";
      })
      .catch((err) => {
        setUrlError(err.response?.data?.errors?.url?.[0]);
        setExpiresError(err.response?.data?.errors?.expiresAt?.[0]);
      });
  };

  return (
    <Form
      actions={
        <ActionPanel>
          <Action.SubmitForm onSubmit={handleSubmit} />
        </ActionPanel>
      }
    >
      <Form.Description text="Shorten your URL with liba.ro" />
      <Form.TextArea
        onChange={change}
        id="url"
        title="URL"
        placeholder="https://libaro.be"
        ref={URLFieldRef}
        error={urlError}
      />
      <Form.DatePicker onChange={change} id="expires" title="Expires at" ref={datePickerRef} error={expiresError} />
    </Form>
  );
}

```

2022-12-06 12:36 UTC, pernielsentikaer requested changes
Hi 👋 

Could you look into the suggestion I made 😊

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-12-06 14:15 UTC, neemspees commented
@pernielsentikaer, thanks for the suggestion. It makes a lot of sense.

2022-12-08 21:14 UTC, pernielsentikaer approved these changes

2022-12-08 21:14 UTC, merged