feat(firefox): added firefox extension
raycast/extensions pull request #3780
Opened 2022-12-04 05:50 UTC by crisboarna

## Description

Adding Mozilla Firefox extension.

- Adds New Tab via search query to Google, searching Firefox tabs in session files and history.
- Adds Search Tab to search directly open tabs from session.
- Adds Search History to search directly from history.

## Screencast
![image](https://user-images.githubusercontent.com/12763781/205476670-2ef3aa73-bd72-40eb-8528-28e3459c358b.png)
![image](https://user-images.githubusercontent.com/12763781/205476674-a3a179f6-1d94-43e5-becd-20ee6bb4c42f.png)
![image](https://user-images.githubusercontent.com/12763781/205476678-d39b939d-4ef5-40c0-8930-7ca079640996.png)
![image](https://user-images.githubusercontent.com/12763781/205476682-de50f7c2-f119-4300-b4df-32d30e8cce50.png)

## Checklist

- [ x ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ x ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ x ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ x ] I checked that files in the `assets` folder are used by the extension itself
- [ x ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2022-12-07 04:18 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* Should this extension open things in Firefox or just this default browser?

* Search Tabs doesn't seems to work as expected

<img width="793" alt="Raycast-evqYgd4V@2x" src="https://user-images.githubusercontent.com/38033107/206087138-ab3b6e4e-3c53-44bf-acbc-b7845e760f53.png">


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-12-15 08:45 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* First metadata image doesn't add any value, could you remove that?
* Could you also use utlis package instead of sql.js here?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2022-12-15 08:45 UTC, pernielsentikaer commented on .gitignore
> +*.iml
```suggestion
```

2022-12-19 08:40 UTC, pernielsentikaer commented
Could you remove your .gitignore @crisboarna 😊

2022-12-19 14:06 UTC, crisboarna commented
Hi @pernielsentikaer,

This PR can be reviewed now.

2022-12-20 04:32 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2022-12-20 04:33 UTC, merged