Add notion search
raycast/extensions pull request #380
Opened 2021-11-18 08:34 UTC by HenriChabrand

## Description

Allow user to search Notion page.

## Type of change

- Bug fix / improvement for my extension

## Screencast

<img width="886" alt="Screenshot 2021-11-18 at 09 26 48" src="https://user-images.githubusercontent.com/18643714/142379888-ebdac00b-9cae-4e29-a0c8-844274b66298.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

2021-11-18 11:35 UTC, pernielsentikaer requested changes
Hi @HenriChabrand 👋 

Awesome addition to the extension 💯 , while I'm waiting for a key to test up against I have a few suggestions that could be addressed in the meanwhile.

I'll do the last check later today when I have the right access to Notion 💣 

By the way, awesome extension and README 🚀

2021-11-18 11:35 UTC, pernielsentikaer commented on extensions/notion/src/search-page.tsx
> +  closeMainWindow,
```suggestion
  ActionPanel,
  Color,
  Icon,
  List,
  Detail,
  FormValues,
  preferences,
  showToast,
  ToastStyle,
  setLocalStorageItem,
  getLocalStorageItem,
  getApplications,
  closeMainWindow,
```

2021-11-18 11:35 UTC, pernielsentikaer commented on extensions/notion/src/search-page.tsx
> +  closeMainWindow,
Remove unused imports

2021-11-18 11:35 UTC, pernielsentikaer commented on extensions/notion/src/search-page.tsx
> +  searchPages,
```suggestion
  Page,
  searchPages,
```

Remove unused imports

2021-11-18 11:35 UTC, pernielsentikaer commented on extensions/notion/src/search-page.tsx
> +}
```suggestion
```

Unused function, should it be used?

2021-11-18 11:35 UTC, pernielsentikaer commented on extensions/notion/src/search-page.tsx
> +}
```suggestion
```

Unused function, should it be used?

2021-11-18 14:54 UTC, HenriChabrand commented
Hello @pernielsentikaer 👋 
Thanks for the review and suggestion – I've committed them all!

Let me know if there's anything I can do 🙌

2021-11-18 20:10 UTC, pernielsentikaer commented
Hi @HenriChabrand 👋 

Thanks for the provided token in Slack, I'll test and get back to you 😄

2021-11-19 14:01 UTC, HenriChabrand commented
Hello @pernielsentikaer 👋
Sorry, there were too many conflicts for some reason – so I've created another clean branch from master.

I've made a new pull request here:
https://github.com/raycast/extensions/pull/392

It simplifies the search and avoids this blinking effect + I found why Raycast was crashing (infinite hook loop).

2021-11-19 14:42 UTC, closed without merging