Add CSS.GG - 704 icons available in CSS, SVG, SVG Sprite and PNG
raycast/extensions pull request #386
Opened 2021-11-18 22:30 UTC by astrit

## Description
Open-source CSS, SVG and Figma UI Icons Available in SVG Sprite, styled-components, NPM & API

## Type of change

- [x] New extension

## Screencast

https://user-images.githubusercontent.com/2398447/142507000-369d2492-57b6-4d84-ab1c-1c369f981ed2.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

2021-11-19 11:29 UTC, pernielsentikaer requested changes
Hi @astrit 👋 

Thank you for this contribution, I left a few suggestions and comments that we need to address.

- Icons in ActionPanel should be added in assets folder

2021-11-19 11:29 UTC, pernielsentikaer commented on extensions/css-gg/src/css-gg.tsx
> +          <ActionPanel.Section title="Copy as inline">
```suggestion
          <ActionPanel.Section title="Copy as Inline">
```

2021-11-21 19:18 UTC, astrit commented on extensions/css-gg/package.json
> +      "description": "Open-source CSS, SVG and Figma UI Icons Available in SVG Sprite, styled-components, NPM & API",
@pernielsentikaer I did update these.

2021-11-21 19:23 UTC, astrit commented
Hi @pernielsentikaer , 

Thank you very much for the feedback. 
I did update the Command fields as requested, please check it and let me know if all good. 

On regards to: 
* Icons in ActionPanel should be added in assets folder

Can I keep it as it is with the icons coming from the `cdn*` , reason why I did not add on assets folder and get them directly from `url` was not to make the extension itself heavy. 

As initially I thought id leave all PNG versions on the extension Light/Dark mode but those are 1,408 PNG and that is why I hosted on Vercel everything. 

Otherwise if absolutely necessary I can download them and add them to the `asset` directory.

2021-11-22 06:45 UTC, pernielsentikaer approved these changes
Hi @astrit 👋 

I'm going to accept it and then my colleague will do a last check before merging 💪

2021-11-22 08:53 UTC, merged