Add Contentful extension
raycast/extensions pull request #4036
Opened 2022-12-23 21:47 UTC by ewgenius

## Description

Extension for Contentful CMS - https://www.contentful.com/

- allows to navigate and search content library with filtering by content type and full text search by query string (all available content types fetched via api)
- view selected content details
- quickly open selected content in browser

All functionality based on official content management api - https://www.contentful.com/developers/docs/references/content-management-api/ and requires to specify Contentful space id and personal content management token in extension settings

## Screencast

1. create new account at https://www.contentful.com/
2. prepare some content types and content
3. create personal content management token for extension

https://user-images.githubusercontent.com/827338/209407859-7e7dced7-dc13-444b-8ce2-0fe2438f152a.mp4

Contentful data for reference:

| | |
|-|-|
|<img width="1093" alt="CleanShot 2022-12-24 at 01 42 40@2x" src="https://user-images.githubusercontent.com/827338/209407944-a9912044-1bde-494f-8579-30b110255d86.png">|<img width="1093" alt="CleanShot 2022-12-24 at 01 42 44@2x" src="https://user-images.githubusercontent.com/827338/209407947-d4a7f48b-e65b-4b83-bfd0-09d55c04ebb3.png">|

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-01-03 10:28 UTC, igorlukanin commented
I'm very much interested in this extension!

2023-01-05 11:43 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you 😊

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-01-05 11:43 UTC, pernielsentikaer commented on extensions/contentful/package.json
> +      "title": "Search Content",
```suggestion
      "title": "Search Content",
      "subtitle": "Contentful",
```

2023-01-05 11:43 UTC, pernielsentikaer commented on extensions/contentful/package.json
> +      "title": "Contentful space id",
```suggestion
      "title": "Contentful Space ID",
```

2023-01-05 11:43 UTC, pernielsentikaer commented on extensions/contentful/package.json
> +      "title": "Contentful management token",
```suggestion
      "title": "Contentful Management Token",
```

2023-01-05 11:43 UTC, pernielsentikaer commented on extensions/contentful/package.json
> +      "title": "Contentful environment",
```suggestion
      "title": "Contentful Environment",
```

2023-01-05 11:43 UTC, pernielsentikaer commented on extensions/contentful/src/search.tsx
> +        <List.Dropdown tooltip="content type" isLoading={contentTypesLoading} onChange={setContentType}>
```suggestion
        <List.Dropdown tooltip="Content Type" isLoading={contentTypesLoading} onChange={setContentType}>
```

2023-01-05 11:43 UTC, pernielsentikaer commented on extensions/contentful/src/search.tsx
> +          <Action title={showDetail ? "Hide Detail" : "Show Detail"} onAction={toggleDetail} />
```suggestion
          <Action title={showDetail ? "Hide Detail" : "Show Detail"} icon={Icon.AppWindowSidebarLeft} onAction={toggleDetail} />
```

2023-01-05 11:43 UTC, pernielsentikaer commented on extensions/contentful/src/search.tsx
> +          <List.Item.Detail.Metadata.TagList title="type">
```suggestion
          <List.Item.Detail.Metadata.TagList title="Type">
```

2023-01-05 11:43 UTC, pernielsentikaer commented on extensions/contentful/src/search.tsx
> +          <List.Item.Detail.Metadata.TagList title="status">
```suggestion
          <List.Item.Detail.Metadata.TagList title="Status">
```

2023-01-05 11:43 UTC, pernielsentikaer commented on extensions/contentful/src/search.tsx
> +          <List.Item.Detail.Metadata.Label title="Fields:" />
```suggestion
          <List.Item.Detail.Metadata.Label title="Fields" />
```
To keep the consistence

2023-01-05 11:43 UTC, pernielsentikaer commented on extensions/contentful/src/search.tsx
> +          <List.Item.Detail.Metadata.Label title="Sys:" />
```suggestion
          <List.Item.Detail.Metadata.Label title="Sys" />
```

2023-01-05 13:32 UTC, ewgenius commented
@pernielsentikaer hello! thanks for еру review, fixes and suggestions, committed all of them 👍

2023-01-06 04:55 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-01-06 04:55 UTC, merged

2023-01-06 06:31 UTC, ewgenius commented
Thank you!