Add Mem.ai Extension
raycast/extensions pull request #4117
Opened 2023-01-02 02:39 UTC by brianfakhoury

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-01-09 01:18 UTC, brianfakhoury commented
Hi @pernielsentikaer! Sorry to bother you -- I just want to check on the status of this request as I want to continue developing the extension once I know an initial deployment is available.

Thanks for your consideration!

2023-01-09 07:08 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* It seems to work when I don't add a date, if I add a date I get this error:

```
08:05:55.748 ClientRequestError: Request failed with error code: INTERNAL_SERVER_ERROR
    at Object._handleGraphqlRequestErrors [as handleRequestErrors] (/Users/pernielsentikaer/.config/raycast/extensions/mem/index.js:13933:17)
    at MemClient2.<anonymous> (/Users/pernielsentikaer/.config/raycast/extensions/mem/index.js:14788:38)
    at Generator.throw (<anonymous>)
    at rejected (/Users/pernielsentikaer/.config/raycast/extensions/mem/index.js:14735:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-01-09 07:08 UTC, pernielsentikaer commented on extensions/mem/src/index.tsx
> +      <Form.DatePicker title="Schedule for later?" {...itemProps.scheduledFor} />
```suggestion
      <Form.DatePicker title="Schedule for Later?" {...itemProps.scheduledFor} />
```

2023-01-09 07:08 UTC, pernielsentikaer commented on extensions/mem/src/index.tsx
> +      <Form.Checkbox title="Mark as read?" label="Read" {...itemProps.isRead} />
```suggestion
      <Form.Checkbox title="Mark as Read?" label="Read" {...itemProps.isRead} />
```

2023-01-09 17:33 UTC, brianfakhoury commented
Thanks, @pernielsentikaer for the review! It seems like their API might be an issue, so let me double-check if I need to disable that feature temporarily.

2023-01-10 02:16 UTC, brianfakhoury commented
@pernielsentikaer I was able to resolve the bug! I believe it's ready for deployment now.

I also enabled the drafts feature for the form for better UX!

2023-01-17 14:03 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-01-17 14:20 UTC, merged