Git branch name generator extension
raycast/extensions pull request #4182
Opened 2023-01-07 22:03 UTC by michaelbonner

## Description

New extension `git-branch-name-generator`. Generate a branch name like: `chore/npm-updates`, `bug/fix-the-menu`, or `feature/new-extension` using a dropdown and a text field. The text will get converted to kebab-case.

## Screencast

https://user-images.githubusercontent.com/1122945/211171807-f70356cd-6543-418f-a5b5-55258083eda7.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-01-11 13:12 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* Consider using [useForm](https://developers.raycast.com/utilities/react-hooks/useform?q=useForm) - this also supports validation of empty fields
* Consider either [resetting the form](https://developers.raycast.com/api-reference/user-interface/form#imperative-api) or popToRoot after [submitting](https://developers.raycast.com/api-reference/window-and-search-bar#poptoroot)  

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-01-11 13:12 UTC, pernielsentikaer commented on extensions/git-branch-name-generator/package.json
> +      "subtitle": "From type and string inputs",
```suggestion
      "subtitle": "",
```
Doesn't add any contextual value

2023-01-12 06:45 UTC, michaelbonner commented
Awesome! Thank you so much for the review @pernielsentikaer  

I added `useForm`. Super easy to implement 👏
I also now use `popToRoot`. Way better user experience now

2023-01-17 09:18 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-01-17 10:40 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-01-17 10:40 UTC, merged