New extension: Simplelogin
raycast/extensions pull request #4189
Opened 2023-01-08 12:53 UTC by adrian-schnell

## Description

Add new SimpleLogin extension for raycast.
With SImpleLogin you can receive and send emails anonymously and protect the inbox against spam and phishing.

## Screencast

https://user-images.githubusercontent.com/322735/211196975-b53bdcbd-abb5-4f3b-8fd5-e78c4ff5fb72.mp4

## Screenshots
<img width="1000" alt="simplelogin-1" src="https://user-images.githubusercontent.com/322735/211195534-a8e59e73-fec4-455e-8923-c3f7a783058f.png">
<img width="1000" alt="simplelogin-2" src="https://user-images.githubusercontent.com/322735/211195586-80dbec79-34ed-49eb-8555-6e9848d18070.png">

## for testing

1. register on https://simplelogin.io/
2. head over to https://app.simplelogin.io/dashboard/api_key
3. enter API key in the extension

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-01-11 13:32 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* After creating an alias in `Create Alias`, it would be nice to popToRoot or reset the form
* When running `Create Random Alias` it would be nice with a loading spinner since there might be a delay before there is a response ready
* `List Aliases` should use isLoading so empty view not is visible before it's needed. 
* Maybe make a copy of the extension icon in 128x128 or so to use instead of the cat 😊
 
I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-01-11 13:32 UTC, pernielsentikaer commented on extensions/simplelogin/src/list_alias.tsx
> +                      title="Delete alias"
```suggestion
                      title="Delete Alias",
                      style={Action.Style.Destructive},
```

2023-01-11 13:32 UTC, pernielsentikaer commented on extensions/simplelogin/src/list_alias.tsx
> +                      title={alias.enabled ? "Disable Alias" : "enable Alias"}
```suggestion
                      title={alias.enabled ? "Disable Alias" : "Enable Alias"}
```

2023-01-11 13:32 UTC, pernielsentikaer commented on extensions/simplelogin/src/list_alias.tsx
> +                          title="Unpinn alias"
```suggestion
                          title="Unpin Alias"
```

2023-01-11 13:32 UTC, pernielsentikaer commented on extensions/simplelogin/src/list_alias.tsx
> +                        <Action title="Pinn alias" onAction={() => updatePinnedStatus(alias, true)} icon={Icon.Pin} />
```suggestion
                        <Action title="Pin Alias" onAction={() => updatePinnedStatus(alias, true)} icon={Icon.Pin} />
```

2023-01-11 13:32 UTC, pernielsentikaer commented on extensions/simplelogin/src/list_alias.tsx
> +                              <List.Item.Detail.Metadata.Label title="E-Mail" text={mailbox.email} />
```suggestion
                              <List.Item.Detail.Metadata.Label title="E-mail" text={mailbox.email} />
```

2023-01-16 09:01 UTC, adrian-schnell commented
@pernielsentikaer you can take a look again  ;)

2023-01-16 14:16 UTC, sxn commented
hi @adrian-schnell! 👋 hope it's alright, I've refactored the list command a bit to avoid the initial empty state flickering. Mind having a look if everything still works as expected? 😸

2023-01-16 16:28 UTC, adrian-schnell commented
thank you 🙏 @sxn

2023-01-17 04:35 UTC, pernielsentikaer commented
Let's merge it! 🔥

2023-01-17 04:37 UTC, merged