Add New Extension WeChat
raycast/extensions pull request #4211
Opened 2023-01-10 10:00 UTC by raffeyang

## Description

# WeChat

A [Raycast](https://www.raycast.com) extension for WeChat to quickly search your contacts and chat.

![cover](https://user-images.githubusercontent.com/7557357/211519411-08744bcf-694b-4cca-bb35-5cad8bf4e7e8.png)

![showcase](https://user-images.githubusercontent.com/7557357/211519731-e400b784-c772-48b6-b464-94a1e1aae141.png)

## Requirement

1. Install [WeChat for Mac](https://www.wechat.com) 
2. Install [WeChatTweak-macOS](https://github.com/Sunnyyoung/WeChatTweak-macOS) 

## Todo

- [x] Search Contact
- [x] List Search Contact Numbers
- [x] Open Contact
- [x] List WeChat ID
- [x] Copy WeChat ID
- [x] Display Avatar
- [x] Fix some bug
- [x] Upload to Raycast Store
- [x] Detect if Wechat is installed
- [ ] Chat directly inside Rycast without opening WeChat
- [ ] View WeChat History
- [ ] Toggle WeChat Function

## How to Use

before I create the final version and release it to the Raycast Store,
you can use it with:

`npm install && npm run dev`

## License

[MIT](LICENSE)

## Screencast

https://user-images.githubusercontent.com/7557357/211519985-5725b2a4-fb86-4e7c-8211-62b997cf51ca.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-01-11 21:11 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* cover.png should not be added as a metadata image
* video.mp4 should not be added as a metadata image

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-01-11 21:11 UTC, pernielsentikaer commented on extensions/wechat/src/util/isWeChatTweakInstalledAlert.tsx
> +    title: "WeChatTweak is Not Installed",
```suggestion
    title: "WeChatTweak is not installed",
```

2023-01-11 21:11 UTC, pernielsentikaer commented on extensions/wechat/src/util/isWeChatInstalledAlert.tsx
> +    title: "WeChat is Not Installed",
```suggestion
    title: "WeChat is not installed",
```

2023-01-11 21:11 UTC, pernielsentikaer commented on extensions/wechat/package.json
> +      "subtitle": "Search your WeChat contacts and chat",
```suggestion
      "title": "Search Contacts and Chat",
      "subtitle": "WeChat",
```

2023-01-12 03:15 UTC, raffeyang commented on extensions/wechat/src/util/isWeChatTweakInstalledAlert.tsx
> +    title: "WeChatTweak is Not Installed",
Nice suggestion.

2023-01-12 03:41 UTC, raffeyang commented
> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I have now tested your extension, and I have some feedback ready for you:
> 
> * cover.png should not be added as a metadata image
> * video.mp4 should not be added as a metadata image
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

I have followed your suggestion to update the code, thanks!

2023-01-12 14:20 UTC, pernielsentikaer commented
Can we host the mp4 elsewhere, so we don't have to commit that large file? You can just use the RAW link from you own repo fork if it is 😊

2023-01-13 11:41 UTC, raffeyang commented
> Can we host the mp4 elsewhere, so we don't have to commit that large file? You can use the RAW link from your own repo fork if it is 😊

Solved,review again.

2023-01-17 08:53 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-01-17 08:53 UTC, merged