Update the swift evolution extension
raycast/extensions pull request #4227
Opened 2023-01-11 10:25 UTC by BProg

## Description

Update the swift evolution extension to use the new endpoint
Major update to the UI
Add screenshots
Add changelog
Add categories

## Screencast

<img width="1000" alt="swift-evolution-1" src="https://user-images.githubusercontent.com/11962191/211782123-16791b24-5d99-4fbc-a958-783a214eb72e.png">
<img width="1000" alt="swift-evolution-5" src="https://user-images.githubusercontent.com/11962191/211782161-b8d77b32-e12c-472d-b6d5-abcfcee8d926.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-01-11 11:22 UTC, pernielsentikaer commented
Looks like you forgot to run Prettier, do you need help with that @BProg

2023-01-11 13:43 UTC, BProg commented
> Looks like you forgot to run Prettier, do you need help with that @BProg

Ran it again on all files, is there anything I missed? I'm running it manually on each file, do you have a script to run it for all files?

2023-01-11 18:42 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* Could we find a way to group some of the items not to have that many separators?

<img width="873" alt="image" src="https://user-images.githubusercontent.com/38033107/211890157-7c6ff61b-5223-439b-93dd-adce9e5432a9.png">



I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-01-11 18:42 UTC, pernielsentikaer commented on extensions/swift-evolution/src/ProposalsList.tsx
> +          <Action title="Toggle details" icon={Icon.AlignLeft} onAction={props.toggleDetails} />
```suggestion
          <Action title="Toggle Details" icon={Icon.AlignLeft} onAction={props.toggleDetails} />
```

2023-01-12 09:45 UTC, BProg commented
> 

<img width="886" alt="Screenshot 2023-01-12 at 10 40 26" src="https://user-images.githubusercontent.com/11962191/212033161-c6acb427-f724-49bd-959c-f2114c8c465e.png">
I have a small issue, the "Review Manager" title is truncated, and don't know why, I see that in your screenshot, it's fine

2023-01-12 11:15 UTC, pernielsentikaer commented
Can you commit your latest code so I can check?

2023-01-12 16:31 UTC, BProg commented
Pushed a commit where I removed some separators

2023-01-13 16:03 UTC, BProg commented
@pernielsentikaer any luck with the issue, is everything else alright?

2023-01-16 12:33 UTC, pernielsentikaer commented
I was able to reproduce the error, and it's something that we'll have to fix on our end - I'll approve and we'll look into a fix soon

2023-01-16 12:33 UTC, merged