Added myextension: trackFlight!
raycast/extensions pull request #4263
Opened 2023-01-14 23:23 UTC by cojmeister

## Description

An extension which allows users to track flight status from raycast! See airport, time and status!

## Screencast

<img width="1000" alt="trackflight-1" src="https://user-images.githubusercontent.com/51219103/212501271-6c12075d-6d51-4912-84ae-59aef60e5b26.png">
<img width="1000" alt="trackflight-2" src="https://user-images.githubusercontent.com/51219103/212501281-e73d89e7-5440-48b7-bb07-4549ff4772f0.png">
<img width="1000" alt="trackflight-3" src="https://user-images.githubusercontent.com/51219103/212501283-59e94c92-3c2b-4bbb-be09-0ee59c7c37f5.png">

## Checklist

- [-] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [-] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [-] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [-] I checked that files in the `assets` folder are used by the extension itself
- [-] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-01-18 04:42 UTC, pernielsentikaer commented
Hi @cojmeister 👋 

Is there a place I can DM you? Either in our [Slack](https://www.raycast.com/community) or on [Twitter](https://twitter.com/pertikaer) 😊

2023-01-18 12:31 UTC, cojmeister commented
Hi @pernielsentikaer I DMd you on twitter

2023-01-22 12:05 UTC, cojmeister commented
Given that this feature exists in the newest version, will it be merged regardless?
@pernielsentikaer

2023-01-24 09:14 UTC, pernielsentikaer requested changes
Hi 👋 

Sure we can 😊

Left a few suggestions for you, checking again after this 😊

2023-01-24 09:14 UTC, pernielsentikaer commented on extensions/trackflight/package.json
> +      "description": "Just fill in will your flight number and we'll get your data!!",
```suggestion
      "title": "Track Flight",
      "description": "Track your flight directly from Raycast by flight number",
```

2023-01-24 09:14 UTC, pernielsentikaer commented on extensions/trackflight/src/trackFlight.tsx
> +      <ActionPanel title="#1 in raycast/extensions">
```suggestion
      <ActionPanel title="Flight Date">
```

2023-01-28 20:09 UTC, cojmeister commented
> Hi 👋 
> 
> 
> 
> Sure we can 😊
> 
> 
> 
> Left a few suggestions for you, checking again after this 😊

Changes are done 😊 🎉

2023-02-01 14:15 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-02-01 20:10 UTC, merged