[new extention] Authy integration
raycast/extensions pull request #430
Opened 2021-11-26 17:48 UTC by guga4ka

## Description
Authy integration for Raycast. 

## Type of change

- New extension

## Screencast

![output](https://user-images.githubusercontent.com/13866979/143616713-31548c60-0d6b-4ba1-b0e8-b6dcb0a284d5.gif)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

2021-11-26 17:52 UTC, guga4ka commented on extensions/authy/src/component/OtpList.tsx
> +    useInterval(() => {
Not sure that this is a good idea, but my goal was to show how long OTP will be valid. This leads to 2 re-renders each second.

2021-11-26 17:52 UTC, guga4ka commented on extensions/authy/README.md
> +Warning: This extension is using Authy private api and may not compliant with the Terms of Service of Authy. Use at your own risk.
Note about risk as requested here https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration

2021-11-30 06:48 UTC, pernielsentikaer requested changes
Hi @guga4ka 👋 

What an extension, very awesome — going to use this a lot myself 🔥 

A few comments:

- If the counter goes down to 1, and I go out and in again it, then the timer is starting from 30 again, but the code is still the same as earlier, will this cause a token mismatch?

- I have both Services and Apps, in Authy they all refresh every 30 second, in the extension it refreshed every 9 second — is this correct? 

- I suggest adding a ✅ in front of the HUD message to improve visibility

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-11-30 06:48 UTC, pernielsentikaer commented on extensions/authy/package.json
> +      "title": "Search OTP",
```suggestion
      "title": "Search OTP",
      "subtitle": "Authy",
```

2021-12-02 08:47 UTC, pernielsentikaer requested changes
Hi @guga4ka 👋 

Thanks for the conversation in Slack, it was very giving 😄 

I suggest changing the title as the last thing, and then I think we're ready to go 💯

2021-12-02 09:50 UTC, pernielsentikaer approved these changes
Hi again @guga4ka 🔥 

Thanks for the update, I think we're good to go! 💪 Lets await final review before merge 😄 

Thanks for your corporation and conversations 💯

2021-12-03 14:21 UTC, merged