WIP: Ethereum Name lookup
raycast/extensions pull request #431
Opened 2021-11-27 10:42 UTC by Yukaii

## Description

Lookup ens domain to address, or vice versa.

## Type of change

- New extension

## Screencast

 

https://user-images.githubusercontent.com/4230968/143677855-8aee33f1-1097-4959-b665-6b8709ed9d2c.mp4

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I checked that extension's icon has size of `512x512`

2021-11-30 05:58 UTC, fe9lix requested changes
Hey @Yukaii, thanks for the contribution. 
One thing I noticed is that initially there's some loading in the list but then no results are returned. I'd suggest to:
- either skip loading when the search bar is empty and just show an empty list straight away 
- or show some default or fallback list (if there's something that makes sense...)

2021-11-30 15:56 UTC, Yukaii commented
@fe9lix Fixed!

2021-11-30 19:07 UTC, fe9lix commented on extensions/ens-name-lookup/package.json
> +      "title": "Lookup ENS or address",
```suggestion
      "title": "Lookup ENS or Address",
```

2021-11-30 19:10 UTC, fe9lix requested changes
Thx, left another small change request (title case for the command name)

2021-12-02 07:56 UTC, fe9lix approved these changes

2021-12-02 07:57 UTC, merged