Internet Radio
raycast/extensions pull request #4427
Opened 2023-01-25 04:34 UTC by SKaplanOfficial

## Description

This extension plays live internet radio through the Music app and provides a convenient way to browse and manage your stations. You can add custom stations by supplying a direct stream URL (e.g. to a live broadcast mp3, aac, or pls file). You can easily play and stop stations, and the livestream file created in Music.app will be automatically removed. You can also easily access the parent website of each station (i.e. the location of the web-based player).

### Commands
- Browse Stations
    - Browse the list of currently configured stations, and edit or delete stations, and control playback.
- New Station
    - Add a custom station via a simple form.
- Stop Playback
    - Stops the currently playing station and removes the associated stream file from Music.app.
- Play Last Station
    - Resumes playback of the last played station.
- Play Random Station
    - Plays a random live radio station.

## Screencast

[InternetRadio.webm](https://user-images.githubusercontent.com/7865925/214480629-373692d7-a080-47d7-b41b-27da2a5d79ca.webm)

[YouTube Video](https://www.youtube.com/watch?v=wLm2o2D2MG4)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-01-25 07:23 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* When creating a new station, it's possible only to input a name; after this, it's impossible to edit since it's missing some of the required fields.

![Raycast-YoArbJuj@2x](https://user-images.githubusercontent.com/38033107/214502737-489e0257-4d36-4b35-a3ec-4b0396fafdaa.png)

* In `Browse Stations`, you could consider adding the tags as keywords so I can search for, e.g., `piano` - could be `keywords={[...stationData.genres]}`

* Make a copy of `command-icon.png` in 128x128 for the empty view

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-01-25 07:23 UTC, pernielsentikaer commented on extensions/internet-radio/src/browse-stations.tsx
> +                  style={Action.Style.Destructive}
Missin an icon

2023-01-25 07:23 UTC, pernielsentikaer commented on extensions/internet-radio/src/browse-stations.tsx
> +                  style={Action.Style.Destructive}
Maybe add something like `shortcut={{ modifiers: ["ctrl"], key: "x" }}`

2023-01-25 07:23 UTC, pernielsentikaer commented on extensions/internet-radio/src/browse-stations.tsx
> +                  title={"Edit Station"}
Maybe add something like `shortcut={{ modifiers: ["cmd"], key: "e" }}`

2023-01-25 07:23 UTC, pernielsentikaer commented on extensions/internet-radio/src/browse-stations.tsx
> +                  style={Action.Style.Destructive}
It could also be nice if there was a [confirm before deleting](https://developers.raycast.com/api-reference/feedback/alert#confirmalert) 😊

2023-01-25 09:06 UTC, SKaplanOfficial commented
Hi @pernielsentikaer, I've updated this with your recommendations as well as two new commands:
- Current Station
  - Shows the currently playing station in the command's subtitle.
- Menu Bar Radio
  - Displays the currently playing station in the menu bar, and provides easy-access to playback controls and station selection

I am encountering an interesting problem where the menu of the MenuBarExtra is displaying offset from its submenu. See the image below for reference:

<img width="515" alt="Screenshot 2023-01-25 at 03 59 37" src="https://user-images.githubusercontent.com/7865925/214521991-7cf84ac4-04a3-4d53-84c3-51e3b8bb3295.png">
Do you have any idea what might cause this?

Since the menu bar extra makes the already existing commands available via the menu bar, I haven't created another video -- but I can if you'd like.

2023-01-25 11:34 UTC, pernielsentikaer commented
I tweaked it a bit now @SKaplanOfficial. Could you give it a spin 😊

2023-01-25 13:55 UTC, SKaplanOfficial commented
@pernielsentikaer the tweaks look good, and the issue with the menu offset is gone, thanks! There is one other small issue that I'm not sure how to fix: if you keep the "Select Stations" menu open for a while, then click a station, it doesn't register seem to register the event at all (doesn't play the station but also doesn't print to the console if I add a debug log in the onAction method). Any idea how to fix that?

2023-01-30 14:24 UTC, pernielsentikaer commented
Hj @SKaplanOfficial 👋 

Is this ready to be merged?

2023-01-30 14:26 UTC, SKaplanOfficial commented
Yes @pernielsentikaer -- thanks!

2023-01-31 08:59 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-01-31 09:08 UTC, merged