Toggl Track: Sort time entries starting from latest
raycast/extensions pull request #4450
Opened 2023-01-26 12:38 UTC by rogatty

## Description

Time entries were in a random order, and now they're sorted starting from the latest one. It makes it easier to continue work after having a break.

Documentation for the API field I have used: https://github.com/toggl/toggl_api_docs/blob/54a59433c3eb79a38bd69df2be30b67e21a7b232/chapters/time_entries.md?plain=1#L18

Documentation for the `sort()` function: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-01-26 16:05 UTC, bkeys818 approved these changes
Looks good to me

2023-01-27 05:06 UTC, pernielsentikaer commented
Hi @rogatty 👋 

Thanks for the fix 🔥 

Do you want to check it out @franzwilhelm 😊

2023-01-27 08:59 UTC, rogatty commented on extensions/toggl-track/src/index.tsx
> +    .sort((a, b) => {
Actually, this is wrong. It should be sorted first and then filtered. I'll update it later today.

2023-01-27 09:26 UTC, rogatty commented on extensions/toggl-track/src/index.tsx
> +    .sort((a, b) => {
[`4efb10c` (#4450)](https://github.com/raycast/extensions/pull/4450/commits/4efb10c0cb5159318f7bfd9b56a6627ba5ded1e0)

2023-01-27 11:04 UTC, franzwilhelm requested changes
Nice catch! Just some cleanup suggestions here :)

2023-01-28 11:48 UTC, rogatty commented
@franzwilhelm thanks for the code review, I cleaned it up.

2023-02-01 15:45 UTC, franzwilhelm approved these changes
🎉 🙌

2023-02-01 15:45 UTC, franzwilhelm commented
@pernielsentikaer ready to merge

2023-02-01 20:02 UTC, pernielsentikaer approved these changes

2023-02-01 20:02 UTC, merged