Add "roam research" extension
raycast/extensions pull request #4482
Opened 2023-01-29 03:51 UTC by dive2Pro

## Description
The plugin add roam research to search, view, quick note in daily notes.

## Screencast

<img width="797" alt="image" src="https://user-images.githubusercontent.com/23192045/215302011-23fd4e84-334d-4cb4-8e04-54cadca00543.png">

to use this plugin, you should have a roam research account and followed this https://roamresearch.com/#/app/developer-documentation/page/9XG0nfsah to get the backend token.

https://user-images.githubusercontent.com/23192045/215303868-114253c7-356f-4318-8556-749fe0c1fdbc.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-02-07 13:10 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* Is there no way to use something like [useFetch](https://developers.raycast.com/utilities/react-hooks/usefetch) instead of using `spawn` with `cURL`

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-02-07 13:10 UTC, pernielsentikaer commented on extensions/roam-research/src/detail.tsx
> +      navigationTitle={"Note detail "}
```suggestion
      navigationTitle={"Note Detail "}
```

2023-02-07 13:10 UTC, pernielsentikaer commented on extensions/roam-research/src/detail.tsx
> +            title="Open in browser"
```suggestion
```
Can be removed since it has a default title

2023-02-07 13:10 UTC, pernielsentikaer commented on extensions/roam-research/src/detail.tsx
> +          <Action.OpenWith title="Open in app" path={`roam://#/app/thoughtfull/page/${block[":block/uid"]}`} />
```suggestion
          <Action.OpenWith title="Open in App" path={`roam://#/app/thoughtfull/page/${block[":block/uid"]}`} />
```

2023-02-13 04:55 UTC, pernielsentikaer approved these changes

2023-02-13 04:56 UTC, pernielsentikaer commented
This is approved when you add a `CHANGELOG.md` and some [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)

2023-02-20 11:01 UTC, pernielsentikaer commented
Could you please use the built-in function to take the screenshots? It seems like the size is not right 😊

![Raycast-gJDW9J8v@2x](https://user-images.githubusercontent.com/38033107/220087014-e73d55ca-6b40-4b84-96dd-b99667cc598d.png)

2023-02-20 11:58 UTC, dive2Pro commented
> Could you please use the built-in function to take the screenshots? It seems like the size is not right 😊
> 
> ![Raycast-gJDW9J8v@2x](https://user-images.githubusercontent.com/38033107/220087014-e73d55ca-6b40-4b84-96dd-b99667cc598d.png)

YES, All the screenshots have been updated.

2023-02-20 12:28 UTC, merged

2023-03-27 22:24 UTC, ymshulman commented
Hi! Love the idea. 
First of all - the installation instructions aren't in the README. It took me a while to find them here. 
Also, the "add graph" doesn't seem to be working for me? I took the name of the my graph, plus the token from https://relemma-git-feat-frontdesk.roamresearch.com/. It doesn't add - it just looks like this:
<img width="167" alt="Screenshot 2023-03-27 at 6 24 04 PM" src="https://user-images.githubusercontent.com/10394892/228080488-65759fb6-e1e8-4929-b269-af017400e966.png">