New extension: Beancount Meta & Update QuickSearch
raycast/extensions pull request #4491
Opened 2023-01-30 05:01 UTC by iwfan

## Description

Quickly generate Beanocunt transactions and save to your journal file. (using [Costflow](https://www.costflow.io/docs/syntax/))

## Screencast

https://user-images.githubusercontent.com/28853200/215390657-fe34284c-35bd-4dac-b0a7-5c286f354845.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-02-07 13:34 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* Can we handle this when the path is not found

![Raycast-Qk7JQx0M@2x](https://user-images.githubusercontent.com/38033107/217257915-9745cbb8-87f0-42ec-b478-1f8af0fc68f5.png)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-02-07 13:34 UTC, pernielsentikaer commented on extensions/beancount-mate/src/components/ErrorView.tsx
> +      icon={"https://cdn-icons-png.flaticon.com/512/4160/4160755.png"}
Could we save this in the extension instead and in 128x128 size - remember credits to the author/service if needed

2023-02-07 13:34 UTC, pernielsentikaer commented on extensions/beancount-mate/src/components/ErrorView.tsx
> +      description="If you are not familiar with Costflow, Open the syntax Doc ⬇️ "
```suggestion
      description="If you are not familiar with Costflow, Open the syntax Doc ⬇️"
```

2023-02-07 13:34 UTC, pernielsentikaer commented on extensions/beancount-mate/src/components/EmptyView.tsx
> +      icon={"https://cdn-icons-png.flaticon.com/512/4160/4160766.png"}
Could we save this in the extension instead and in 128x128 size - remember credits to the author/service if needed

2023-02-13 11:18 UTC, iwfan commented
Hi @pernielsentikaer , please do new review for this extension.

2023-02-14 08:54 UTC, pernielsentikaer requested changes
Hi 👋 

Could we resize the smileys to around 128x128 instead? It's quite big right now 😊

![Raycast-jeETpf6R@2x](https://user-images.githubusercontent.com/38033107/218686393-92555dc5-095c-4809-8c41-94ee31ad87cf.png)

2023-02-16 08:23 UTC, pernielsentikaer commented
Hi @iwfan 👋 

I don't think the toast should be here; it makes too much noice.

https://user-images.githubusercontent.com/38033107/219308244-2b24c906-00ee-4163-bb2c-c11741790ba7.mp4

2023-02-16 13:06 UTC, iwfan commented
> Hi @iwfan 👋
> 
> I don't think the toast should be here; it makes too much noice.

Hi @pernielsentikaer , You are right, I removed toast when user is typing.

2023-02-20 21:59 UTC, pernielsentikaer approved these changes
Hi 👋

Looks good to me, approved 🔥

2023-02-20 21:59 UTC, merged