Add ciweimao extension
raycast/extensions pull request #452
Opened 2021-12-01 06:11 UTC by zsakvo

## Description

New extension let you use features from https://www.ciweimao.com via their mobile api.
With this, you could read, search, buy and delete books in your account.

## Type of change

- New extension

## Screencast

### All Commands

![all-commands](https://user-images.githubusercontent.com/25399519/144173165-c457895b-36b3-47e1-8a5a-ae6b125ce4af.jpg)

### List Books

![list-books](https://user-images.githubusercontent.com/25399519/144173184-c886ddeb-6ddc-4446-8f1d-39bd87faa765.jpg)

### List Shelves

![list-shelves](https://user-images.githubusercontent.com/25399519/144173187-d33d71c4-5959-485e-b599-21f93b61367d.jpg)

### Search Books

![search-books](https://user-images.githubusercontent.com/25399519/144173191-b2db1f39-fee4-4c9e-bd7d-3f7af5c51be4.jpg)

### Catalog

![catalog](https://user-images.githubusercontent.com/25399519/144173179-7a4c173d-3733-4f90-af89-422b0604eacb.jpg)

### Reading

![reading](https://user-images.githubusercontent.com/25399519/144173188-b6acbb68-e9a1-4259-b716-3ff28b969c8c.jpg)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

2021-12-03 08:26 UTC, pernielsentikaer requested changes
Hi @zsakvo 👋 

Thanks for you contribution 🔥 

For a start we need to change the texts in Actionpanels to English according to https://developers.raycast.com/basics/prepare-an-extension-for-store#localization-language - can you do that?

Request a new review when it's done and then I'm looking into it 🔥

2021-12-07 03:32 UTC, zsakvo commented
Hi @pernielsentikaer

According to the regulations, I have translate all text to English.

Thanks for your revision.

2021-12-08 20:03 UTC, pernielsentikaer requested changes
Hi @zsakvo 

Thanks for the update, a few comments and corrections:

- If wrong credentials is added, “Continue Reading” just give Chinese output
- If wrong credentials is added, “Search Novel” don't have graceful error handling like the others.

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-12-08 20:03 UTC, pernielsentikaer commented on extensions/ciweimao/package.json
> +      "subtitle": "All Books",
```suggestion
      "subtitle": "Ciweimao",
```

2021-12-08 20:03 UTC, pernielsentikaer commented on extensions/ciweimao/package.json
> +      "subtitle": "Read Last",
```suggestion
      "subtitle": "Ciweimao",
```

2021-12-08 20:03 UTC, pernielsentikaer commented on extensions/ciweimao/package.json
> +      "subtitle": "Search Something",
```suggestion
      "subtitle": "Ciweimao",
```

2022-01-05 08:36 UTC, pernielsentikaer commented
Hi @zsakvo 👋 

Do you need any help?

2022-01-21 22:03 UTC, pernielsentikaer commented
Hi @zsakvo 👋 

I'll give you a few days more to respond before closing this PR (and we can reopen at any time) 

Let me know if I can do anything to help you 💯

2022-02-20 21:47 UTC, pernielsentikaer commented
Hi @zsakvo 👋 

I'm closing this, we can reopen it when you're ready to continue the work 😄

2022-02-20 21:47 UTC, closed without merging