Create Flow app timer extension
raycast/extensions pull request #457
Opened 2021-12-01 23:07 UTC by vimtor

## Description

A way to control [Flow](https://flowapp.info/) app pomodoro timer in Raycast.

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/36263538/144328280-199b1668-bfae-46c5-98d8-4450f2be741f.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2021-12-02 10:01 UTC, pernielsentikaer requested changes
Hi @vimtor 👋 

There is no gracefully errorhandling when flow app is not installed, can you look into this? 💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-12-06 20:08 UTC, vimtor commented
@pernielsentikaer I added some failure toasts for when `Flow` is not installed

2021-12-06 20:09 UTC, vimtor commented
Feel free to publish the extension :)

2021-12-06 20:17 UTC, pernielsentikaer approved these changes
Hi @vimtor 👋 

Much better! I'm going to approve this now, thanks for another great extension 💯

2021-12-06 20:59 UTC, merged