[New Extension] Sidekick
raycast/extensions pull request #4584
Opened 2023-02-04 02:53 UTC by shikibu9419

## Description

## Screencast

<img width="1000" alt="sidekick-1" src="https://user-images.githubusercontent.com/26058923/216742710-f388beb6-8482-4438-b301-1aed8e1ce8b0.png">

<img width="1000" alt="sidekick-2" src="https://user-images.githubusercontent.com/26058923/216742715-fb830aaf-4154-4694-a418-a1a163b8e947.png">

<img width="1000" alt="sidekick-3" src="https://user-images.githubusercontent.com/26058923/216742716-91e8f7b1-4dae-47f9-820a-41c1b20e5d52.png">

<img width="1000" alt="sidekick-4" src="https://user-images.githubusercontent.com/26058923/216742713-c577d0ad-a0dd-4274-a9c3-7603ca55a1d0.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-02-08 09:55 UTC, thomaslombart requested changes
Thanks for the extension! 🚀

As I'm not a Sidekick user, I got some errors related to empty states when testing the extension.

If I don't have any bookmarks installed or if the app isn't installed, I have the following error screen:

<img width="741" alt="CleanShot 2023-02-08 at 10 41 46@2x" src="https://user-images.githubusercontent.com/16003285/217495863-972aa73a-9dd9-4f0f-8bb8-107b07e59513.png">

I guess this happens because there are no bookmarks in the system if no one is created. You could typically handle this using `List.EmptyView` and an action to invite the user to add some bookmarks if the `Bookmarks` folder doesn't exist.

Could you also add a description to the PR to briefly introduce the extension? Thanks!

2023-02-08 09:55 UTC, thomaslombart commented on extensions/sidekick/package.json
> +      "description": "Before enable this, you should enable 'View > Developer > Allow JavaScript from Apple Events' in every Sidekick profile.",
```suggestion
      "description": "Before enabling this, you should enable 'View > Developer > Allow JavaScript from Apple Events' in every Sidekick profile.",
```

2023-02-08 09:55 UTC, thomaslombart commented on extensions/sidekick/src/browser/history.ts
> +import path from "path";
Note that you can use `useSQL` hook from the `@raycast/utils` package to make SQL stuff easier to manage: https://developers.raycast.com/utilities/react-hooks/usesql 😊

2023-02-13 07:48 UTC, shikibu9419 commented
Oh, thank you for your reviews!!
I'll fix it; please wait.

2023-03-06 08:43 UTC, closed without merging