add hex to string conversions
raycast/extensions pull request #4611
Opened 2023-02-05 09:27 UTC by Saafo

## Description

add hex to string and string to hex conversions

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-02-05 09:39 UTC, Saafo commented
Besides this PR, I also wonder why Toolbox doesn't export all of its scripts in `package.json`'s commands, so that users can directly use scripts from the main page of Raycast.

2023-02-07 06:48 UTC, pernielsentikaer requested changes
Hi @Saafo 

Thanks for this update, [Buffer](https://nodejs.org/api/buffer.html) is builtin with node, so I don't think you need to import it.

It's up to the extension author to decide, but it could have worked, too 😊

2023-02-07 06:53 UTC, Saafo commented
@pernielsentikaer ok I see, I'm quite a newbie to js / ts, so.. up to @kkange to decide😂, both are ok to me. XD

2023-02-07 07:15 UTC, Saafo reviewed
Thanks a lot!

2023-02-07 07:17 UTC, pernielsentikaer approved these changes
Hi 👋

Approved; let's 🚢 it!

2023-02-07 07:18 UTC, merged

2023-02-07 07:19 UTC, kkange commented
@Saafo

The added functionality looks great. 👍

The reason we didn't export everything as a command is a matter of personal taste.
I wanted to support different types of command behavior while avoiding command duplication.

But I'll think about adding a command export feature if people want it.