feat: add extension rust-document
raycast/extensions pull request #4666
Opened 2023-02-08 11:19 UTC by waynexia

Signed-off-by: Ruihang Xia <waynestxia@gmail.com>

## Description

Search rust crates' document easily

## Screencast

<img width="862" alt="screenshot 2023-02-08 19 00 47" src="https://user-images.githubusercontent.com/15380403/217515492-3ebc617e-90da-46ab-9a70-7efbc5d64f8a.png">
<img width="862" alt="screenshot 2023-02-08 19 01 57" src="https://user-images.githubusercontent.com/15380403/217515517-e69dab59-6c49-44ff-9763-1479b1b1c9ae.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-02-10 09:29 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

Some suggestions might be wrong if it's not the Rust documentation, but let's see what we can improve 😊

* Some results are not working (Seems to be all with 0.0.0 as version)
 
![Raycast-v5QnWDvb@2x](https://user-images.githubusercontent.com/38033107/218054059-61b83a3f-7344-4bc7-88b7-bfc891a17cfc.png)


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-02-10 09:29 UTC, pernielsentikaer commented on extensions/rust-document/package.json
> +  "name": "rust-document",
```suggestion
  "name": "rust-documentation",
```

2023-02-10 09:29 UTC, pernielsentikaer commented on extensions/rust-document/package.json
> +  "title": "Rust Document",
```suggestion
  "title": "Rust Documentation",
```

2023-02-10 09:29 UTC, pernielsentikaer commented on extensions/rust-document/package.json
> +  "description": "Search Rust document quickly",
```suggestion
  "description": "Search Rust documentation quickly",
```

2023-02-10 09:29 UTC, pernielsentikaer commented on extensions/rust-document/package.json
> +      "title": "rs",
```suggestion
      "title": "Search Documentation",
      "subtitle": "Rust",
```

2023-02-10 09:29 UTC, pernielsentikaer commented on extensions/rust-document/package.json
> +      "description": "Search Rust document quickly",
```suggestion
      "description": "Search Rust documentation quickly",
```

2023-02-11 17:18 UTC, waynexia commented
Hi @pernielsentikaer, thanks for your review. I've added a filter to opt-out crates with version "0.0.0", now it looks like this: 
<img width="862" alt="截屏2023-02-12 01 16 36" src="https://user-images.githubusercontent.com/15380403/218271648-e007f879-c363-4f16-92b7-e5440e07f3bc.png">


By the way, just curious, is there any plan or discussion to accept extensions to be added as submodules?

2023-02-11 17:22 UTC, waynexia commented
Could you please help me to fix the CI? I've run `eslint --init` and `eslint --fix` in my env and no change generated.

2023-02-13 04:40 UTC, pernielsentikaer commented
You should see the same errors when running `npm run lint` or checking [this link](https://github.com/raycast/extensions/actions/runs/4152376325/jobs/7183291695)

2023-02-27 06:13 UTC, waynexia commented
Got a few busy weekends, I would resolve those lints soon

2023-03-24 15:42 UTC, closed without merging