feat: add send-to-memos
raycast/extensions pull request #4723
Opened 2023-02-10 16:16 UTC by JakeLaoyu

## Description

Raycast extension for [usememos/memos](https://github.com/usememos/memos).

## Screencast

![SCR-20230210-x5j](https://user-images.githubusercontent.com/16181940/218141338-7c5e8f7f-c8af-465e-b3cb-f13722931dba.png)
![SCR-20230210-x6a](https://user-images.githubusercontent.com/16181940/218141357-34bce880-cef1-40fc-aa13-4b9ed182fa21.png)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-02-10 16:45 UTC, JakeLaoyu commented
Why prettier lint can't pass?

![Uploading image.png…]()

2023-02-13 14:49 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* Add a placeholder/description of where to get the Open API
<img width="873" alt="image" src="https://user-images.githubusercontent.com/38033107/218489243-b329cdc0-321a-4442-9861-0048ea85c314.png">

* `Open Memo Website` opens a folder, is that as expected? I didn't set it up 😊

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-02-13 14:49 UTC, pernielsentikaer commented on extensions/send-to-memos/src/sendMemoForm.tsx
> +            <Action title="Open In Browser" onAction={openWeb} />
```suggestion
            <Action title="Open in Browser" onAction={openWeb} />
```

2023-02-13 15:43 UTC, JakeLaoyu commented
@pernielsentikaer Thank you for feedback. I have changed.
You can get Open Api from [memos demo](https://demo.usememos.com/).

2023-02-14 05:08 UTC, pernielsentikaer requested changes
Hi 👋 

You could use [useFetch](https://developers.raycast.com/utilities/react-hooks/usefetch) from `@raycast/api` to cache t he initial data, this way your extension will be much faster 😊

2023-02-14 05:27 UTC, JakeLaoyu commented
> Hi 👋
> 
> You could use [useFetch](https://developers.raycast.com/utilities/react-hooks/usefetch) from `@raycast/api` to cache t he initial data, this way your extension will be much faster 😊

Okay, I will add caches for GET requests such as lists and tags.

2023-02-14 19:48 UTC, pernielsentikaer requested changes
* Currently, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

<img width="874" alt="image" src="https://user-images.githubusercontent.com/38033107/218843981-5b5c3ff1-47ee-41fb-a001-6a92654850e3.png">

* When submitting `Send MEMO` I get this error

![Raycast-v4UZ6gNf@2x](https://user-images.githubusercontent.com/38033107/218843350-a6c99d69-8ce2-45db-9975-611809afdfff.png)

```
20:46:44.723 
DataCloneError: function transformRequest(data, headers) {
    const contentType = headers.getContentType() || "";
    const ha...<omitted>... } could not be cloned.

    const contentType = headers.getContentType() || "";
DOMException:domexception:53:5
MessagePort.<anonymous>:index.js:1:1984
``

2023-02-15 02:34 UTC, JakeLaoyu commented
- I have changed to limit to  US English.

- This is so bad about the error. The official test demo disabled the post request.  I deployed a demo project on my server. Maybe you can test it with the account below.

openApi: https://memo-test.jakeyu.top/api/memo?openId=408c75c0-ef46-4072-802e-c65b247105dc
website: https://memo-test.jakeyu.top
username: test
password: test

2023-02-15 04:41 UTC, pernielsentikaer commented
Hi 👋 

Thanks for setting it up so I can test it; however, it seems like something is wrong with the implementation

<img width="635" alt="Raycast-wtDvsUGP@2x" src="https://user-images.githubusercontent.com/38033107/218932373-8931f75e-e1f7-44e1-b77e-38021ac9e459.png">

2023-02-15 04:42 UTC, JakeLaoyu commented
> Hi 👋
> 
> Thanks for setting it up so I can test it; however, it seems like something is wrong with the implementation
> 
> <img alt="Raycast-wtDvsUGP@2x" width="635" src="https://user-images.githubusercontent.com/38033107/218932373-8931f75e-e1f7-44e1-b77e-38021ac9e459.png">

Maybe it's because my server is in China. I'll find another way.

2023-02-15 04:44 UTC, pernielsentikaer commented
Let's just continue without, let's make a new PR if anything is reported instead 😊

2023-02-15 04:46 UTC, JakeLaoyu commented
> Let's just continue without, let's make a new PR if anything is reported instead 😊

That's pretty good. THX.

2023-02-16 09:06 UTC, JakeLaoyu commented
Hi @pernielsentikaer , are there still issues that I need to fix?

2023-02-16 09:22 UTC, pernielsentikaer reviewed
Should we call it "Memos" instead? Since it also lists memos

2023-02-16 09:34 UTC, JakeLaoyu commented
> 

Of course. I thought so, too.
Originally, I just wanted to make a send command, but then I wrote more and more.

2023-02-16 13:33 UTC, pernielsentikaer approved these changes
Hello 👋

I gave it a quick spin, works as expected, approved 🔥

2023-02-16 13:33 UTC, merged

2023-02-16 15:31 UTC, JakeLaoyu commented
> Hello 👋
> 
> I gave it a quick spin, works as expected, approved 🔥

THX