Added Circle CI extension
raycast/extensions pull request #476
Opened 2021-12-04 17:34 UTC by qeude

## Description

Add a Circle CI extensions. It lets you list your workflows and their associated jobs.

## Type of change

- New extension

## Screencast

![Screen Recording 2021-12-04 at 18 27 50](https://user-images.githubusercontent.com/19294297/144718959-87049fc3-a335-46d7-b86f-08e21a153653.gif)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2021-12-06 19:04 UTC, pernielsentikaer requested changes
Hi @qeude 👋 

Thanks for you contribution, very nice! 💯 

I have now tested you extensions and I have a few comments and suggestions:
- If credentials is wrong, I suggest you to stop the loading and show "No Result" instead
- Remove console.log's

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-12-06 19:04 UTC, pernielsentikaer commented on extensions/circle-ci/src/index.tsx
> +        <CopyToClipboardAction title="Copy workflow URL" content={workflowUrl} />
```suggestion
        <PushAction title="Workflow Job List" target={<JobList workflow={workflow} />} />
        <OpenInBrowserAction title="Open Workflow" url={workflowUrl} />
        <CopyToClipboardAction title="Copy Workflow URL" content={workflowUrl} />
```
Also icon is missing in the PushAction

2021-12-06 19:04 UTC, pernielsentikaer commented on extensions/circle-ci/src/index.tsx
> +        <CopyToClipboardAction title="Copy workflow URL" content={workflowUrl} />
```suggestion
        <PushAction title="Workflow Job List" target={<JobList workflow={workflow} />} />
        <OpenInBrowserAction title="Open Workflow" url={workflowUrl} />
        <CopyToClipboardAction title="Copy Workflow URL" content={workflowUrl} />
```
Also icon is missing in the PushAction

2021-12-06 21:06 UTC, qeude commented
Hi @pernielsentikaer,
Thanks for your feedback, everything should be good now. 🙌🏼

2021-12-08 07:21 UTC, pernielsentikaer approved these changes
Hi @qeude 👋

Thanks for the update, much better 💪 

I'm going to accept this now, my colleague will do a final review before merging it 💯

2021-12-09 06:24 UTC, merged