Implement pagination for getActiveCycleIssues.
raycast/extensions pull request #4856
Opened 2023-02-17 22:26 UTC by joel-u410

## Description

Implementing pagination support for the Linear GraphQL API. Initially it is used only in `getActiveCycleIssues` but could be easily added to any other GraphQL request. This resolves issue #4814.

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-02-21 09:30 UTC, thomaslombart requested changes
Thanks for this PR. I've reviewed it and have some feedback:

I can't retrieve any issues in the `Active Cycle` command. I get this specific error:

<img width="1000" alt="linear 2023-02-21 at 10 20 48" src="https://user-images.githubusercontent.com/16003285/220304554-ec3237cf-e4ba-4933-be9f-3db8280e9350.png">

Could you please take another look at the implementation and hopefully fix it? 😊

Please, request a new review when you are ready. Feel free to contact me here or in the [Slack community](https://www.raycast.com/community) if you have any questions.

2023-02-21 16:06 UTC, joel-u410 commented
Yikes! I guess it should have some limit to how many pages it will retrieve. Out of curiosity, how many issues do you have in your active cycle?

2023-02-21 16:47 UTC, joel-u410 commented
I added a limit so it will stop after fetching 4 pages. I wonder if this should be a configurable option? (Seems like it would be an "advanced" config though, maybe too low level for extension preferences.)

2023-03-10 23:42 UTC, joel-u410 commented
Update - still looking into this whenever I have time.

2023-03-11 00:28 UTC, joel-u410 commented
OK @thomaslombart -- I've _sort of_ punted on this by introducing a preference for "API Issue Limit" that allows the user to set a larger-than-default value in order to fetch multiple pages. The default is `50` which will maintain current behavior, and _should_ prevent heap errors from occurring. But it will easily allow for use cases like mine, where I want to fetch more issues. (With a warning in the preference that setting it too large can result in hitting API rate limits and/or heap errors.)

If this is acceptable, can you test again and see if you still get memory errors with the default settings? (And, perhaps, try some larger settings and see if you can trigger the heap error by setting the limit too high.)

2023-03-13 15:18 UTC, thomaslombart approved these changes
I don't have the error anymore. Thanks for the contribution!

2023-03-13 15:19 UTC, thomaslombart commented
That being said, what's weird though is that setting a ridiculously high number did not make the error show up again. I tried setting the API size limit to 50, 100, 1000 and 10000. None of them caused the error 🤷

2023-03-13 15:19 UTC, thomaslombart commented
Should I go ahead and merge it?

2023-03-14 14:35 UTC, joel-u410 commented
> Should I go ahead and merge it @joel-u410?

Yes, please do, thanks!

2023-03-14 14:37 UTC, joel-u410 commented
> That being said, what's weird though is that setting a ridiculously high number did not make the error show up again. I tried setting the API size limit to 50, 100, 1000 and 10000. None of them caused the error 🤷

That is weird indeed. It probably also depends on how many issues are actually returned by your query (i.e. how many are in your active cycle). In my testing, I found the error to be somewhat intermittent, but definitely triggered more by larger queries.

(I was able to trigger the error most consistently by adding pagination to the "search issues" query, and setting it to a large number.)

2023-03-14 20:31 UTC, merged