added moneylover
raycast/extensions pull request #4918
Opened 2023-02-22 16:49 UTC by lacherogwu

## Description
MoneyLover is a personal finance manager for iOS and Android. It helps you to track your income and expenses, set budgets, and manage your money.
https://moneylover.me/

This extension is able to interact with the application using it's API

## Screencast
<img width="1000" alt="moneylover-1" src="https://user-images.githubusercontent.com/49835614/220698432-0b9adea0-f9d9-43b0-8f37-3f7997f3abc3.png">
<img width="1000" alt="moneylover-2" src="https://user-images.githubusercontent.com/49835614/220698459-e13d7da6-d3b6-41a2-b0f4-5d1b2dc76910.png">
<img width="1000" alt="moneylover-3" src="https://user-images.githubusercontent.com/49835614/220698481-6ab96c4a-1972-41f2-8f86-2fc7cc39315c.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-03-01 20:34 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-03-01 20:34 UTC, pernielsentikaer commented on extensions/moneylover/src/view-wallets.tsx
> +                  title="Adjust balance"
```suggestion
                  title="Adjust Balance"
```

2023-03-01 20:34 UTC, pernielsentikaer commented on extensions/moneylover/src/view-wallets.tsx
> +            title="Adjust balance"
```suggestion
            title="Adjust Balance"
```

2023-03-02 07:36 UTC, lacherogwu commented
@pernielsentikaer Great improvements thanks!
I applied the changes

2023-03-06 21:32 UTC, pernielsentikaer approved these changes
Hi 👋

Looks good to me, approved 🔥

2023-03-06 21:33 UTC, merged