feat(moco): Add MOCO extension
raycast/extensions pull request #4955
Opened 2023-02-24 12:21 UTC by eviscares

## Description

Allows to interface with the timetracking part of [https://www.mocoapp.com/](https://www.mocoapp.com/).
Features:
- Checking of todays activities
- Checking of recent activities
- Logging of new activities
- Editing of logged activities
- Stopping & Starting the timer on an activity if it is from today.

## Screencast
https://drive.google.com/file/d/1gYNs-TK1CbbCPIPN7SIdQ2m1ULXGVjwz/view?usp=sharing

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-02-24 12:52 UTC, eviscares commented
The pipeline fail seems weird to me.
It runs locally, and `npm run build` also works without any issue.

2023-03-01 21:25 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-03-01 21:25 UTC, pernielsentikaer commented on extensions/moco/src/commands/tasks/components/TaskListItem.tsx
> +          <Action.Push title={"Start an activity for this task"} target={<ActivityStart task={task} />} />
```suggestion
          <Action.Push title={"Start Activity"} target={<ActivityStart task={task} />} />
```

2023-03-01 21:25 UTC, pernielsentikaer commented on extensions/moco/src/commands/activities/components/ActivityEdit.tsx
> +            title="Save changes"
```suggestion
            title="Save Changes"
```

2023-03-01 21:25 UTC, pernielsentikaer commented on extensions/moco/src/commands/activities/components/ActivityEdit.tsx
> +      <Form.DatePicker id="date" title="For which day is the booking?" defaultValue={new Date(activity.date)} />
```suggestion
      <Form.DatePicker id="date" title="Booking Date" defaultValue={new Date(activity.date)} />
```

2023-03-01 21:25 UTC, pernielsentikaer commented on extensions/moco/src/commands/activities/components/ActivityEdit.tsx
> +        title="How many hours did you work?"
```suggestion
        title="Hours Worked"
```

2023-03-01 21:25 UTC, pernielsentikaer commented on extensions/moco/src/commands/activities/components/ActivityStart.tsx
> +        title="For which day is the booking?"
```suggestion
        title="Booking Date"
```

2023-03-01 21:25 UTC, pernielsentikaer commented on extensions/moco/src/commands/activities/components/ActivityStart.tsx
> +        title="How many hours did you work?"
```suggestion
        title="Hours Worked"
```

2023-03-02 08:51 UTC, eviscares commented on extensions/moco/src/commands/activities/components/ActivityEdit.tsx
> +            title="Save changes"
Changed

2023-03-02 08:51 UTC, eviscares commented on extensions/moco/src/commands/activities/components/ActivityEdit.tsx
> +      <Form.DatePicker id="date" title="For which day is the booking?" defaultValue={new Date(activity.date)} />
Changed

2023-03-02 08:51 UTC, eviscares commented on extensions/moco/src/commands/activities/components/ActivityEdit.tsx
> +        title="How many hours did you work?"
Changed

2023-03-02 08:51 UTC, eviscares commented on extensions/moco/src/commands/activities/components/ActivityStart.tsx
> +        title="For which day is the booking?"
Changed

2023-03-02 08:52 UTC, eviscares commented on extensions/moco/src/commands/activities/components/ActivityStart.tsx
> +        title="How many hours did you work?"
Changed

2023-03-02 08:52 UTC, eviscares commented
Thanks for the Review and Feedback. I rephrased according to your suggestion.

2023-03-02 12:24 UTC, pernielsentikaer approved these changes
Hi 👋

Looks good to me, approved 🔥

2023-03-02 12:24 UTC, merged