Add code-variable extension
raycast/extensions pull request #5089
Opened 2023-03-02 03:17 UTC by Hongbusi

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-03-14 11:28 UTC, pernielsentikaer requested changes
Currently, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

I'm not sure what this does, could you describe with a few lines 😊

2023-03-15 01:36 UTC, Hongbusi commented
CodeVariable returns a better variable from Chinese to English. Support small camel case, large camel case, constant, underscore, dash.

2023-03-22 06:10 UTC, pernielsentikaer requested changes
Do the users of this extension know hoe to use it? I have no clue at all so we might need to describe it better 😊

2023-03-22 06:10 UTC, pernielsentikaer commented on extensions/code-variable/README.md
> +[MIT](./LICENSE) License © 2023 [Hongbusi](https://github.com/Hongbusi)
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2023-03-22 06:18 UTC, Hongbusi commented
Sincerely recommend changing the extension system, even if the user experience makes me feel great, releasing an extension will make me lose interest in continuing to use it.

2023-03-22 06:18 UTC, closed without merging