Add zalgo-text extension
raycast/extensions pull request #5109
Opened 2023-03-03 02:33 UTC by petermiles

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-03-09 23:20 UTC, petermiles commented
@raycastbot Just wondering if there's an update here :)

2023-03-14 11:49 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you 😊

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-03-14 11:49 UTC, pernielsentikaer commented on extensions/zalgo-text/package.json
> +      "title": "G̙͖̬̳̜͛̓͘e̶̟ͧ͗n̷̳̤̉ͩ̓͗̈́̇ͪ͡ē̵̫͓̳̹̊ṟ̷ͩ͋a̱̟͍͉̼͖ͤͫͥ̒̿́t̪̥̼͍͖͓̳͒ͫ͂̐ͪ̿e̒̒͏̬̰̠̖̝̘̯ͅ",
Transform to Zalgo

2023-03-14 11:49 UTC, pernielsentikaer commented on extensions/zalgo-text/package.json
> +      "description": "Convert text to Z̬͚̭̤͓̟͖͐͒ȃ̮̙̯͈͍͇͒ͤ̓ͤ́ͨͅͅl̷̐̍̃̊͏̝ğ̡̪̪͓͈͙̘̽͐͒̆́ö̮̳̪̯̟̩̭̎ͮ̇̿̀͢ ̥͎̂̿͋͋́̀̕͢T̴̷̳̟̟͎͛͌̔̈̇̓ę̠̊͑͊̉̽̓̑̒x̸̠̭͎͍̋̏̇ͯ͋̍ͣt̷̶̤͇̠̜̩̯̦͑̈́ͤ̿͛ͤ̀",
```suggestion
      "description": "Convert text to Zalgo",
```
You could also add an [argument](https://developers.raycast.com/information/lifecycle/arguments)

2023-03-14 11:49 UTC, pernielsentikaer commented on extensions/zalgo-text/src/index.tsx
> +        <Form.TextField id="textfield" title="Text field" placeholder="Enter text" defaultValue="Raycast is cool!" />
```suggestion
        <Form.TextField id="textfield" title="Text" placeholder="Enter text" defaultValue="Raycast is cool!" />
```

2023-03-28 09:37 UTC, merged