Add "Obsidian" extension
raycast/extensions pull request #512
Opened 2021-12-11 13:36 UTC by marcjulianschwarz

## Description

Add "Obsidian" extension.
This extension lets users interact with notes written in the knowledge management and note taking app Obsidian.
You can search, view, open, edit, copy and paste notes.

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/67844154/145678597-cd652295-1f95-4d59-ac0a-80bb561857d8.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2021-12-13 06:25 UTC, pernielsentikaer requested changes
Hi @marcjulianschwarz 🔥 

Thanks for the contribution, I left some feedback for you to work on 💪 

- Handle errors gracefully when path is wrong

![wqELgJk4T8QUVdXL](https://user-images.githubusercontent.com/38033107/145762685-23fb2c8d-ce01-45ba-bca6-ac2a942d330c.png)

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-12-13 06:25 UTC, pernielsentikaer commented on extensions/obsidian/package.json
> +      "title": "Search in Obsidian",
```suggestion
      "title": "Search Note",
      "subtitle": "Obsidian",
```

2021-12-13 08:24 UTC, marcjulianschwarz commented
Hi @pernielsentikaer,
thank you for pointing out this issue, I just committed a fix and accepted the change for the commands title and subtitle.

2021-12-13 09:53 UTC, pernielsentikaer requested changes
Hi @marcjulianschwarz 🔥 

Thanks for the update, much better! 💪 

A few comments:

- When using the command there is [Empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states), can you look into eliminate this?

- What should "Hide links" do, seems to do nothing here at least, tried markdown link and regular link, it looks the same regardless the setting set.

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-12-13 10:12 UTC, marcjulianschwarz commented
Thank you for the feedback.

I removed the "Empty state flicker" as described in the article.

"Hide links" will remove links in the Wikilink format: `[[Link to another note]]` -> `Link to another note`. This link format is used by nearly everyone in the Obsidian community to connect notes. When copying or viewing notes with the raycast extension these links might be distracting and as they don't include any extra information like a URL they can safely be hidden.

I won't remove normal markdown links as they do contain information like a URL. Additionally these markdown links will display just fine in "Quick Look".

2021-12-14 10:43 UTC, pernielsentikaer approved these changes
Hi @marcjulianschwarz 🔥 

MUCH better, I think we're ready to ship it 🚢 

I'm going to accept it and then will my colleague do a final review before it's finally merged.  😄 

Thank you for your contribution 💯

2021-12-14 10:46 UTC, marcjulianschwarz commented
Hi @pernielsentikaer,

thank you for the great review 😊

2021-12-14 13:23 UTC, mattisssa approved these changes

2021-12-14 13:23 UTC, merged

2021-12-14 13:52 UTC, marcjulianschwarz commented
Thank you for reviewing and approving the extension.

To update the extension I will have to create new forks with pull requests right?

2021-12-14 21:43 UTC, mattisssa commented
Yes, @marcjulianschwarz, you're right 👍