Add "Quick Search" extension
raycast/extensions pull request #513
Opened 2021-12-11 15:05 UTC by iwfan

## Description

Use keyboard shortcut quickly search selected text or clipboard text via Google or Github or DeepL etc.

For example: 

- press <kbd>Option(⌥) + Ctrl(⌃) + O</kbd> open google search in default browser.
- press <kbd>Option(⌥) + Ctrl(⌃) + G</kbd> open GitHub search in default browser.

## Type of change

- New extension

## Screencast

<img width="1570" alt="iShot2021-12-11 23 05 12" src="https://user-images.githubusercontent.com/28853200/145681383-8aa59c87-6296-490f-8334-429199a63087.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2021-12-13 09:38 UTC, pernielsentikaer commented
Hi @iwfan 

Is this ready to get reviewed? 😄

2021-12-13 10:34 UTC, iwfan commented
> Hi @iwfan
> 
> Is this ready to get reviewed? 😄

@pernielsentikaer yes, it's ready.

2021-12-14 14:20 UTC, pernielsentikaer commented
Great 🔥 

I will give it a spin within a few hours, sorry for the long response time, It's 100% my fault - won't happen again 😄

2021-12-17 01:15 UTC, iwfan commented
> Great @iwfan 🔥
> 
> I will give it a spin within a few hours, sorry for the long response time, It's 100% my fault - won't happen again 😄

Hi @pernielsentikaer, does there have new information on this extension?

2021-12-17 10:03 UTC, pernielsentikaer requested changes
Hi @iwfan 👋 

Yes, I had to discuss it with the team since it's almost what's possible to do with the “Quick Links” extensions except the clipboard part.

A few comments and suggestions:
- You have to find a logo for the extension, right now you're using the default one.
- Rename the extension to contain “clipboard” everywhere
- I'm not sure that you'll ever hit the catch exception in the scripts?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-12-17 10:03 UTC, pernielsentikaer commented on extensions/raycast-quick-search/src/github-search.ts
> +      showHUD("🎉 Open github search");
```suggestion
      showHUD("🎉 Open GitHub search");
```

2021-12-17 10:03 UTC, pernielsentikaer commented on extensions/raycast-quick-search/src/github-repo.ts
> +      showHUD("🎉 Open github search");
```suggestion
      showHUD("🎉 Open GitHub search");
```

2021-12-17 10:03 UTC, pernielsentikaer commented on extensions/raycast-quick-search/src/deepl-trans.ts
> +      showHUD("🎉 Open deepl search");
```suggestion
      showHUD("🎉 Open Deepl search");
```

2021-12-17 10:03 UTC, pernielsentikaer commented on extensions/raycast-quick-search/package.json
> +      "title": "Github Repo",
```suggestion
      "title": "GitHub Repo",
```

2021-12-17 10:03 UTC, pernielsentikaer commented on extensions/raycast-quick-search/package.json
> +      "title": "Github Search",
```suggestion
      "title": "GitHub Search",
```

2021-12-17 10:03 UTC, pernielsentikaer commented on extensions/raycast-quick-search/src/google-search.ts
> +      showHUD("🎉 Open google search");
```suggestion
      showHUD("🎉 Open Google search");
```

2021-12-19 10:33 UTC, iwfan commented
Hi @pernielsentikaer, thanks for your patient guidance, I will make the changes as you suggest later.

But for now, I want to say **how is this extension different from Raycast's built-in "Quick Link"?**

`Quick Link` is a very good feature, it is equivalent to a shortcut entrance (a wormhole) through which you can quickly get to any address you want to go to.
`Quick Search` is similar to it in terms of functionality, but it focuses more on using shortcuts to improve search efficiency.

Suppose the following scenario.

Ivan is a front-end development engineer. He is reading a technical article about "React" and he finds a technical term that he doesn't understand.
At this point he wants to google for the technical term, he first selects that term by double-clicking on it and then presses `Command + C`, copying it to the clipboard.

If he wants to search via `Quick Link`, there are several ways to do so.

- Open the Raycast launcher and search for "Quick Link"
- Open the Raycast launcher and search for Alias of "Quick Link"
- Open "Quick Link" directly via Hotkey

But after opening `Quick Link`, Ivan had to enter `Query` (the keyword to be queried).
Fortunately, Ivan has already copied it to the clipboard, so he just needs to press `Command + V`, and then he can press <kbd>Enter</kbd> to open the Google search page.

If Ivan uses `Quick Search`, he can open the Google search page directly via Hotkey when he selected the technical term in that article.

The difference between Quick Search and Quick Link is that Quick Search automatically retrieves the `Query` from the selected text and clipboard, and then opens the specific search address directly.
This skips the step where Ivan enters the `Query` and makes the search much faster.

2021-12-19 13:28 UTC, iwfan commented
Hi @pernielsentikaer, I already made changes,  please start a new review.

2021-12-23 10:36 UTC, fe9lix requested changes
Hey @iwfan, thanks for the contribution! I've left some inline comments...

2021-12-23 10:36 UTC, fe9lix commented on extensions/raycast-quick-search/src/deepl-trans.ts
> +    showHUD("💩 Sorry, Can not open Deepl for now!");
```suggestion
    showHUD("❌ Cannot open Deepl!");
```

2021-12-23 10:36 UTC, fe9lix commented on extensions/raycast-quick-search/src/deepl-trans.ts
> +    showHUD("💩 Sorry, Can not open Deepl for now!");
I'd suggest to keep it brief and maybe you can check whether there's a meaningful short error message that you could extract and append?

2021-12-23 10:36 UTC, fe9lix commented on extensions/raycast-quick-search/src/deepl-trans.ts
> +    showHUD("💩 Sorry, Can not open Deepl for now!");
Same suggestion applies to all other search cases.

2021-12-23 10:36 UTC, fe9lix commented on extensions/raycast-quick-search/src/utils/opener.ts
> +  await openInBrowser(`https://deepl.com/zh/translator#en/zh/${text}`)
I think it makes sense to make the from/to language a preference and remove the hardcoded "zh"?

2021-12-23 10:36 UTC, fe9lix commented on extensions/raycast-quick-search/README.md
> +Use keyboard shortcut quickly search selected text or clipboard text via Google or Github or DeepL etc.
```suggestion
Use a global keyboard shortcut to quickly search selected text or clipboard text via Google or Github or DeepL etc.
```

2021-12-23 10:36 UTC, fe9lix commented on extensions/raycast-quick-search/package.json
> +  "name": "raycast-quick-search",
```suggestion
  "name": "quick-search",
```

2021-12-23 10:36 UTC, fe9lix commented on extensions/raycast-quick-search/package.json
> +  "name": "raycast-quick-search",
The "raycast" is implicit, no need to add it to the extension name (would be redundant in the resulting store URL).

2021-12-23 10:50 UTC, fe9lix commented
@iwfan Another comment: This is a pretty nice and useful idea and after some internal alignments, we actually intend to add this functionality at some point to the built-in quicklinks feature of Raycast. Meanwhile, we can still publish the extension after the review and keep it in the store if you want.

2021-12-24 01:01 UTC, iwfan commented
Hi @fe9lix! Thanks for your review, I already made changes as you suggest. 

BTW, I prefer to add this functionality to the built-in quicklinks feature of Raycast.

2021-12-24 08:57 UTC, fe9lix approved these changes

2021-12-24 08:57 UTC, merged