Update ask-chatgpt extension
raycast/extensions pull request #5137
Opened 2023-03-04 08:31 UTC by Ex10si0n

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-03-14 12:12 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

Could you add [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) too

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-03-14 12:12 UTC, pernielsentikaer commented on extensions/ask-chatgpt/package.json
> +      "title": "Chat",
```suggestion
      "title": "Ask ChatGPT",
```

2023-03-17 08:58 UTC, Ex10si0n commented
I have fixed the `package.json` and added standard screenshot inside folder `metadata`, could you please have one more time to check it for me?

2023-03-17 08:59 UTC, Ex10si0n commented on extensions/ask-chatgpt/package.json
> +      "title": "Chat",
well noted, I have changed

2023-03-17 14:58 UTC, pernielsentikaer commented
Maybe we should make a collab with #5157 since it kinda does the same job so we don't end up with a lot of extensions doing the same - would you be up for that?

2023-03-17 15:23 UTC, closed without merging