Add MyIP extension
raycast/extensions pull request #524
Opened 2021-12-13 18:23 UTC by kkange

## Description
 
get my real ip and see the details and torrent download history of ip.

## Type of change

- New extension

## Screencast
![스크린샷 2021-12-14 03 16 43](https://user-images.githubusercontent.com/14085373/145866849-11de180b-d32a-406a-aed0-bc67fff3b3aa.png)
![스크린샷 2021-12-14 03 17 34](https://user-images.githubusercontent.com/14085373/145866855-11218ae7-afb7-497a-90c0-d322c5f87b53.png)
![스크린샷 2021-12-14 03 18 51](https://user-images.githubusercontent.com/14085373/145866859-2978e0ca-0668-4b18-a1f6-2f9c4c4ee4bc.png)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2021-12-15 08:39 UTC, pernielsentikaer requested changes
Hi @kkange 👋 

Only a single correction, you're on fire 🔥 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-12-15 08:39 UTC, pernielsentikaer commented on extensions/myip/package.json
> +      "subtitle": "Internet",
```suggestion
```
Could you remove this one, it seems redundant to me

2021-12-15 09:49 UTC, kkange commented
hi @pernielsentikaer

Thank you for the feedback.

I reflected that.

2021-12-15 10:33 UTC, kkange commented
I added these.

- Remove unused libraries
- Apply context-sensitive navigation movements after copying values ​​or opening a browser

2021-12-16 05:07 UTC, pernielsentikaer approved these changes
Hi @kkange 🔥 

Thanks for the update, I'm going to accept it and then will my colleague do a final review before it's finally merged

2021-12-16 12:43 UTC, mattisssa approved these changes
Wow, this is the good one 👍 
Let's bring it to the Store

2021-12-16 12:43 UTC, merged

2022-03-17 03:50 UTC, jankerli commented
@kkange can add a feature to get the Local network ip？

2022-03-17 04:02 UTC, kkange commented
> @kkange can add a feature to get the Local network ip？

If you want, I'll add it.

2022-03-17 05:42 UTC, jankerli commented
cool~ thanks

2022-03-17 05:42 UTC, jankerli commented
> > @kkange can add a feature to get the Local network ip？
> 
> If you want, I'll add it.
> 
> I did PR.

cool~ thanks