First version Tureng command - Turkish-English dictionary
raycast/extensions pull request #534
Opened 2021-12-15 23:30 UTC by myucesan

## Description

A Raycast command that translates English and Turkish words bidirectionally. Icon by Freepik and API provided by Mehmet Burak Erman.
## Type of change

- New extension

## Screencast
![CleanShot 2021-12-16 at 00 29 06](https://user-images.githubusercontent.com/4138641/146280724-43a5974a-0621-4b17-997f-ef089a654da6.png)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2021-12-16 07:20 UTC, pernielsentikaer requested changes
Hi @myucesan 👋 

Thanks for your contribution 💯 Some comments and suggestions for you to work with:

- It would make more sense to let it start on “No Results” screen instead of the placeholder-
- You forgot to add node-fetch to package.json
- Remove debug messages

Is it correct that it only works with Turkish words, inserting "Cat" leads to multiple Cats 😄 

![UrfDMtBW4nPmUDD5](https://user-images.githubusercontent.com/38033107/146325279-7b636830-9758-49f5-9f55-a471dac51825.png)

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-12-16 07:20 UTC, pernielsentikaer commented on extensions/tureng/package.json
> +  "description": "Translate Turkish words to English and the other way around\n",
```suggestion
  "description": "Translate Turkish words to English and the other way around",
```

2021-12-16 07:20 UTC, pernielsentikaer commented on extensions/tureng/package.json
> +      "subtitle": "Translate English and Turkish words bidirectionally",
```suggestion
      "title": "Dictionary",
      "subtitle": "Tureng",
```

2021-12-16 08:37 UTC, mattisssa commented
Hey! I've updated the `package.json` to resolve issues with schema and let the workflow build the extension. 

But seems like the extension still contain some errors inside:
>💥 Error: build failed: Could not resolve "node-fetch"

2021-12-16 10:35 UTC, myucesan commented
> Hi @myucesan 👋
> 
> Thanks for your contribution 💯 Some comments and suggestions for you to work with:
> 
> * It would make more sense to let it start on “No Results” screen instead of the placeholder-
> * You forgot to add node-fetch to package.json
> * Remove debug messages
> 
> Is it correct that it only works with Turkish words, inserting "Cat" leads to multiple Cats 😄
> 
> ![UrfDMtBW4nPmUDD5](https://user-images.githubusercontent.com/38033107/146325279-7b636830-9758-49f5-9f55-a471dac51825.png)
> 
> Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

[x] Shows No results now
[x] added node fetch
[x] removed debug messages
[x] There instead was a mistake with "Cat". All the words are now lowercased as the API, and Tureng handles it correctly like this. Good spot!

Thanks!

2021-12-16 12:31 UTC, pernielsentikaer requested changes
Hi @myucesan 🔥 

We're almost there! Awesome corrections, and the cat is working as expected 😄 

There is a loading spinner when loading the extensions, are you able to remove that one since there should be no loading while loading?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-12-16 13:34 UTC, myucesan commented
> Hi @myucesan 🔥
> 
> We're almost there! Awesome corrections, and the cat is working as expected 😄
> 
> There is a loading spinner when loading the extensions, are you able to remove that one since there should be no loading while loading?
> 
> Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

Thanks :) Is the latest commit to your satisfaction? I think that's what you meant, hope I'm correct in thinking that.

2021-12-16 13:44 UTC, pernielsentikaer commented
Hi @myucesan 🔥 

The loading spinner should be there, it's perfect when you search, however, when loading the extension it should be set default to false – when I loaded the extension, I got 4 seconds “loading spinner” 

Sorry for not being clear enough, also, can you look into the errors the linter are complaining about?

2021-12-16 13:47 UTC, mattisssa commented
@myucesan Keep in mind that your extension still has a lot of errors and cannot compile:

>src/index.tsx(108,43): error TS2552: Cannot find name 'Json'. Did you mean 'JSON'?
125
src/index.tsx(109,42): error TS2552: Cannot find name 'Json'. Did you mean 'JSON'?
126
src/index.tsx(110,27): error TS7006: Parameter 'jsonResult' implicitly has an 'any' type.
127
src/index.tsx(111,38): error TS2304: Cannot find name 'Json'.

2021-12-16 14:10 UTC, myucesan commented
> @myucesan Keep in mind that your extension still has a lot of errors and cannot compile:
> 
> > src/index.tsx(108,43): error TS2552: Cannot find name 'Json'. Did you mean 'JSON'?
> > 125
> > src/index.tsx(109,42): error TS2552: Cannot find name 'Json'. Did you mean 'JSON'?
> > 126
> > src/index.tsx(110,27): error TS7006: Parameter 'jsonResult' implicitly has an 'any' type.
> > 127
> > src/index.tsx(111,38): error TS2304: Cannot find name 'Json'.

Yes, this is strange. I'm looking into it.

2022-01-07 05:18 UTC, pernielsentikaer commented
Hi @myucesan 👋 

What's the status of the PR, are you ready to get it done?

2022-01-07 06:37 UTC, myucesan commented
> Hi @myucesan 👋 
> 
> 
> 
> What's the status of the PR, are you ready to get it done?

Hi there, 

I am a bit busy atm. Had to go abroad and now exams I'll expect to get to it in February.

Sorry for the wait.

2022-02-09 19:19 UTC, fe9lix commented
Hey guys, any updates here or should we close and later reopen?

2022-02-10 20:24 UTC, myucesan commented
> Hi @myucesan 👋
> 
> What's the status of the PR, are you ready to get it done?

I'm done :) Committed.

2022-02-10 20:24 UTC, myucesan commented
> Hey guys, any updates here or should we close and later reopen?

It's done.

2022-02-11 07:14 UTC, pernielsentikaer requested changes
Hi @myucesan 👋 

Thanks for taking your time to make the extension done 🔥 

I left a suggestion for you and some feedback: 
 
When opening the extension, it makes an empty search call which make the extension feel slow – could you look into removing the first initial empty search call?

Looking forward for next push 👍 💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-11 07:14 UTC, pernielsentikaer commented on extensions/tureng/src/index.tsx
> +  const [state, setState] = useState<SearchState>({ results: [], isLoading: false });
```suggestion
  const [state, setState] = useState<SearchState>({ results: [], isLoading: true });
```
Fixing last part of the [empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states)

2022-02-11 07:17 UTC, pernielsentikaer commented on extensions/tureng/src/index.tsx
> +  CopyToClipboardAction,
```suggestion
```
Remove unused import

2022-02-13 13:05 UTC, myucesan commented
Check last commit, you mean this? It showed a brief loading screen because of it.

2022-02-14 17:58 UTC, myucesan commented
> @myucesan Could you run prettier on your sources? CI reports some issues: https://github.com/raycast/extensions/runs/5185777181?check_suite_focus=true

done, sorry.

2022-02-15 21:07 UTC, pernielsentikaer commented
Hi @myucesan 👋 

No, no the `isLoading={state.isLoading}` should indeed be there, but when I open the extension i makes a blank XHR request to `https://tureng.com/en/turkish-english/` with the answer: 

```
{
  about: 'This is Unofficial The Tureng Dictionary JSON API where you can search English & Turkish words by typing /api/:word',
  example: 'https://tureng-api.vercel.app/api/butterfly',
  madeWith: 'node.js and  https://tureng.com',
  createdBy: 'Mehmet Burak Erman'
}
```

This initial call (when searchText.length === 0) should NOT trigger a XHR request but return empty array instead

Does it make sense, otherwise don't hesitate to write me 💪

2022-03-17 11:15 UTC, myucesan commented
İ'm going to check this, had exams sorry for the delay.

2022-03-17 23:56 UTC, mattisssa commented
Hey @myucesan! What is the status of this PR? It seems like it's been here for a long time unfinished. Shall we probably close this one and once you're ready – open another PR?

2022-03-22 00:00 UTC, closed without merging