Google chrome profiles
raycast/extensions pull request #536
Opened 2021-12-16 17:45 UTC by frouo

## Description

List existing google chrome profile and launch the selected one.

## Type of change

New extension

## Screencast

https://user-images.githubusercontent.com/2499356/146422273-90f42940-7235-478c-bdb0-dd6190a36374.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2021-12-19 19:14 UTC, pernielsentikaer requested changes
Hi @frouo 👋 

It looks awesome, I tested it out and only have a single comment 🔥 

It would be cool to have a HUD when opening a bookmark, It was possible to me to open it three times before I noticed it was due to lag it didn't open faster.

Could you look into that?

2021-12-19 20:30 UTC, frouo commented
Oh yes, I got that too! Your suggestion will help thank you. I will do it shortly

2021-12-24 14:17 UTC, frouo commented
Added new features:

![new tab + search + custom filtering](https://user-images.githubusercontent.com/2499356/147358481-68f96dbc-e3a4-4bc2-97eb-cca976e38fef.png)

![preferences](https://user-images.githubusercontent.com/2499356/147358506-0a259166-d158-4aaf-82a0-85cf23a9c290.png)

2021-12-27 07:09 UTC, pernielsentikaer requested changes
Hi @frouo 👋 

Tried the new features out and they work as expected 💯 

I left you a few comments to look into, we're so close to merge 💎 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2021-12-27 07:09 UTC, pernielsentikaer commented on extensions/google-chrome-profiles/README.md
> +This is where this extensions comes in.
```suggestion
This is where this extensions come in.
```

2021-12-27 07:09 UTC, pernielsentikaer commented on extensions/google-chrome-profiles/README.md
> +| open and close raycast main window | `↵`   |
```suggestion
| open and close Raycast main window | `↵`   |
```

2021-12-27 07:09 UTC, pernielsentikaer commented on extensions/google-chrome-profiles/README.md
> +| open and keep raycast opened       | `⌘ ↵` |
```suggestion
| open and keep Raycast opened       | `⌘ ↵` |
```

2021-12-28 07:08 UTC, pernielsentikaer approved these changes
Hi @frouo 👋 

Thank you for the latest update, it works as expected 💪 

I'm going to accept it and then will my colleague do a final review before it's finally merged 💯

2021-12-30 11:22 UTC, mattisssa commented
Hey! Let's get it merged 👏 
I have one question, what is the difference between simple "Open" and "Open in Background" here? For me it just always opens Google Chrome and makes it in focus.

<img width="366" alt="CleanShot 2021-12-30 at 14 21 17@2x" src="https://user-images.githubusercontent.com/15333662/147747490-362299a7-6724-423c-8240-baeaf8ad1271.png">

2021-12-30 11:22 UTC, merged

2021-12-30 13:11 UTC, frouo commented
@mattisssa 

> what is the difference between simple "Open" and "Open in Background" here?

"Open in google chrome" does launch google chrome + call `showHUD` (which should close the Raycast main window). 

"Open in Background" does launch google chrome + call `showToast` (which should keep open the Raycast main window if I am correct). That is not what you are experiencing?