Swap description and info to ease experience
raycast/extensions pull request #5378
Opened 2023-03-15 15:45 UTC by aromeronavia

## Description
When creating a quick task, I normally just want to add a title and the time I want to execute it.
The thing is that the current order of params is the `name`, `description`, and `info`. This causes some troubles because if one doesn't want to fill a description, they would need to tab twice to get to add the `info` which in my case is adding the time.

This is a highly opinionated PR based on an **hypothesis that adding the time of an event is highly more important than adding a description to a task**, and I would totally understand if this is not the direction you wanna follow @thomaslombart, just wanted to bring this up to discussion to see if this resonates with you.

## Screencast

https://user-images.githubusercontent.com/13922607/225363358-a08669ef-5c46-4a28-bf69-22a6b59d8e94.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension) (ran the build)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-03-20 09:00 UTC, thomaslombart requested changes
As said in the community, changing this could impact users who are used to adding a task this way. I, for example, don't often use time because my workflow isn't made that way. However, I get the use-case behind it. What would you think of merging the title and info fields instead? That way you can write all your tasks info in one go and you still have to `tab` once to add a description.

2023-03-23 21:10 UTC, aromeronavia commented on extensions/todoist/src/quick-add-task.tsx
> -
My bad, totally need to revive that chunk of code 🙏  I was experimenting with the first approach of making arguments optional via a configuration but then I realized that's not doable

2023-03-23 21:10 UTC, aromeronavia commented
> What would you think of merging the title and info fields instead? That way you can write all your tasks info in one go and you still have to tab once to add a description.
That would totally work @thomaslombart, appreciate the feedback. I'll experiment with this one and ping you when it's done

2023-03-25 19:13 UTC, aromeronavia commented
## Changes added
- Merged title and info parameters, I called the merge of both of them just "text".
- Fixed your comment about the description @thomaslombart 

## Things to consider
Arguments for quick tasks are a bit small, and it's pretty evident now that `text` and `info` are merged, notice that typing a task text is now a longer string that doesn't fit the input's container. Not a big deal as it's not part of this task, but just worth noticing.

## Evidence
https://user-images.githubusercontent.com/13922607/227736630-798e9f12-766b-4964-896c-a0f81b802646.mov

Any thoughts on this approach @thomaslombart? Appreciate you took the time to review and give some good feedback on this

2023-03-27 07:53 UTC, thomaslombart commented
Looks good to me! Maybe let's put some info in the title's placeholder to let users know they can enter some of them: `Task title and info (today 5pm p2)`

2023-03-28 17:58 UTC, aromeronavia commented
I like that! Will make the changes later today or tomorrow. Appreciate it @thomaslombart

2023-04-07 17:54 UTC, aromeronavia commented
I made some iterations to the placeholder because the input container does not expand with the content. This is the text that read completely without getting trimmed. Hopefully it makes sense @thomaslombart 

<img width="739" alt="image" src="https://user-images.githubusercontent.com/13922607/230654839-5c1c763a-054e-4843-90a8-34abb92d82de.png">

2023-04-07 17:55 UTC, aromeronavia commented
FWIW I've been using my local env Quick Add Task command a lot these days, I can really feel the ease and excitement of creating a quick task

2023-04-11 06:35 UTC, thomaslombart approved these changes
Awesome, then let's ship it! 🚀

2023-04-11 06:35 UTC, merged