Add optional preference FORM_FIELDS
raycast/extensions pull request #546
Opened 2021-12-18 07:37 UTC by sestanley13

## Description

## Type of change

Improvement for somebody else's extension. Extension author: @honzatmn

## Screencast

<img width="316" alt="Screen Shot 2021-12-17 at 11 31 01 PM" src="https://user-images.githubusercontent.com/29286627/146633435-e1d30aab-5706-4de9-a31f-be763139d29d.png">
<img width="770" alt="Screen Shot 2021-12-17 at 11 32 22 PM" src="https://user-images.githubusercontent.com/29286627/146633437-7c909d70-2482-47ff-9ea4-8c54d7b03af0.png">
<img width="737" alt="Screen Shot 2021-12-17 at 11 33 02 PM" src="https://user-images.githubusercontent.com/29286627/146633439-0fcab858-b6eb-44c8-aad0-c0de49a3b5e1.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2021-12-21 10:23 UTC, fe9lix commented
@honzatmn Would you mind also reviewing those changes?

2021-12-21 12:45 UTC, honzatmn requested changes
Hi Scott, thanks for your contribution, this is a great new feature! I added two small comments, otherwise it looks good.

2021-12-21 12:45 UTC, honzatmn commented on extensions/productboard/src/index.tsx
> +      content += `<b>${field}:</b> ${values[index.toString()]} <br />`;
Wouldn't it be better to format content here with markdown syntax, and let markdown converter in `handleSubmit` take care of the conversion to HTML? 

Also, have you tested markdown syntax in custom fields? Will it get converted properly?

2021-12-21 12:45 UTC, honzatmn commented on extensions/productboard/src/index.tsx
> +  if (!FORM_FIELDS) return (
There is a lot of repeated code with this approach. Would it be possible to clean it up a bit, so e.g. title, tags and saidBy fields are not defined twice?

2021-12-27 06:49 UTC, pernielsentikaer commented
@sestanley13 could you look into the suggestion above?

2022-01-07 05:19 UTC, pernielsentikaer commented
Hi @sestanley13 – are you able to look into the suggestions made by @honzatmn, so we can get this PR closed?

2022-03-17 23:56 UTC, mattisssa commented
Hey @sestanley13! What is the status of this PR? It seems like it's been here for a long time unfinished. Shall we probably close this one and once you're ready – open another PR?

2022-03-22 00:01 UTC, closed without merging