feat: delete bookmarks in raindrop
raycast/extensions pull request #5480
Opened 2023-03-21 04:48 UTC by ShubhamVerma1811

2023-03-21 05:49 UTC, pernielsentikaer commented
Hi @ShubhamVerma1811 🔥  Thanks for your contribution 💯 

@lardissone do you mind checking this 😊

2023-03-21 13:05 UTC, lardissone approved these changes
Awesome work! 
Just a small nit in a text :)

2023-03-21 14:24 UTC, ShubhamVerma1811 commented
Thank you for the review @lardissone!
And thanks for pushing the commit @pernielsentikaer!

2023-03-22 13:12 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* I don't see any way to submit this form
<img width="1000" alt="raindrop-io 2023-03-22 at 14 10 08" src="https://user-images.githubusercontent.com/38033107/226914625-d627906d-06b3-4f41-8821-96a545e67595.png">

* When deleting a link there is no refresh of the list, you need to go out/in again before it's gone from the list

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-03-22 13:41 UTC, ShubhamVerma1811 commented
>  I don't see any way to submit this form
Weird, I am able to see it. Can it be some versioning issue?

<img width="859" alt="Screenshot 2023-03-22 at 19 09 57" src="https://user-images.githubusercontent.com/25576658/226922290-25440394-be97-4351-b9ca-ab88aca70cdb.png">

> When deleting a link there is no refresh of the list, you need to go out/in again before it's gone from the list
Is this something that needs to be implemented? I am not sure how it can be done. Couldn't find any Raycast docs on Navigating b/w command views..

2023-03-23 09:20 UTC, pernielsentikaer commented
Hi 👋 

Check the new code from my PR, it's not done yet but fixed and enhanced multiple aspects of the extensions

- Added destructive style for `Delete Bookmark`
- Added hotkeys
- Added confirmAlert when deleting bookmark
- Fixed the add action, since the code was wrong
- Added validation for the add form
- Added more things

What is still left is the redraw of the list, I can maybe add this later today

Do you mind checking my corrections, feel free to modify 😊

2023-03-23 14:46 UTC, lardissone approved these changes
Awesome work @pernielsentikaer ! Thank you!
Just left a small nit.

2023-03-23 14:46 UTC, lardissone commented on extensions/raindrop/src/add.tsx
> +            console.log(await res.json());
nit: remove `console.log`

2023-03-28 08:43 UTC, pernielsentikaer requested changes
We could indeed do this better with [optimisticUpdate](https://developers.raycast.com/utilities/react-hooks/useexec#mutation-and-optimistic-updates) but it works now.

Seems like there is a bug when you switch in the dropdown, could you look into that?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-04-11 05:05 UTC, ShubhamVerma1811 commented
Hey @pernielsentikaer, Are we waiting for any changes on this?

2023-04-11 12:49 UTC, pernielsentikaer approved these changes
Let's merge this one 🧑‍🚒

2023-04-11 12:51 UTC, merged