zotero extension for searching zotero database directly from raycast
raycast/extensions pull request #55
Opened 2021-10-16 03:27 UTC by sadanand-singh

## Description

A simple extension to search your zotero database directly from Raycast

## Type of change

- New extension

## Screencast

![](images/search.png)

## Checklist

- [x ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2021-10-18 20:26 UTC, fe9lix requested changes
Hey @sadanand-singh , thanks for your contribution!

Is the extension still WIP? If so, you might want to set this PR to a "Draft" and then request a review once you're ready.

Unfortunately I can't fully test the extension since I run into a JSON parsing error when loading the list: 

```
runQuery error SyntaxError: Unexpected token A in JSON at position 0
    at JSON.parse (<anonymous>)
```
    
Can you double check? Chances are other users might run into the same issue (not sure if it has something to do with the fact that I've created a new account and test token...)

I've also left some inline comments.

2021-10-18 20:26 UTC, fe9lix commented on extensions/zotero/package.json
> +  "description": "Search Zotero Databae from Raycast",
Typo: Databae

2021-10-18 20:26 UTC, fe9lix commented on extensions/zotero/tsconfig.json
> +    // "strict": true,
Is there a specific reason you want to disable this?

2021-10-18 20:53 UTC, fe9lix commented
> Here is a test account:
> 
> key: `MnnQ8wKPuu2noKmnJk48PCoH` user id: `8623690`

Thanks! Please make sure to disable that test account again after the initial review since the credentials are public here.

2021-10-18 21:01 UTC, fe9lix approved these changes
Thanks for your updates. I'm going to merge this first version. It would still be cool if you improved the error handling a bit and present a human-readable message in the toast (not sure if the error might happen when the database is empty and doesn't return any results...)

2021-10-18 21:01 UTC, merged

2021-10-19 09:37 UTC, gumadeiras commented
would it make sense to search a local zotero database (json or bibtex) as an alternative to the API? that way you don't need internet access and searching should be much faster