Feedly(QoL changes): List Dropdown for Collections and Read Later
raycast/extensions pull request #5512
Opened 2023-03-22 13:47 UTC by ShubhamVerma1811

## Description

- Moved from using List.section to List.Dropdown
- Add a Save to Read later form action.

## Screencast

<img width="868" alt="Screenshot 2023-03-22 at 19 13 31" src="https://user-images.githubusercontent.com/25576658/226924106-9745b6ca-c6b7-4be7-b607-0d7013304df8.png">

<img width="839" alt="Screenshot 2023-03-22 at 19 14 28" src="https://user-images.githubusercontent.com/25576658/226924073-398fa26c-6ef9-4577-9b40-af94a5538c30.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-03-23 09:45 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you 😊  

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-03-23 09:45 UTC, pernielsentikaer commented on extensions/feedly/src/components/Feed.tsx
> +                            <Action.SubmitForm
You don't have a `Form`, you should go with `<Action>` instead

2023-03-23 09:45 UTC, pernielsentikaer commented on extensions/feedly/src/components/Feed.tsx
> +                  <Action.SubmitForm
You don't have a `Form`, you should go with `<Action>` instead

2023-03-28 08:07 UTC, pernielsentikaer requested changes
Hi 👋 

It seems like there is something wrong with the initial load, can you look into that?

https://user-images.githubusercontent.com/38033107/228170917-004b284d-518b-4a19-9183-3b09ba8255d3.mp4

2023-04-02 07:30 UTC, ShubhamVerma1811 commented
Hi,
I don't see the actions that is in the video.
I was not able to reproduce it.

2023-04-11 05:06 UTC, ShubhamVerma1811 commented
Hey @pernielsentikaer, Are we waiting for any changes on this?
As of the issue you mentioned, I wasn't able to repro it.

2023-04-11 12:48 UTC, pernielsentikaer commented
Try to run it with `npm run dev` and do as above, I can still reproduce it

2023-04-13 04:29 UTC, ShubhamVerma1811 commented
Fixed it! 🕺 

@pernielsentikaer, Please review it for any other changes

2023-04-13 05:19 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-04-13 05:22 UTC, merged