Update file-manager extension
raycast/extensions pull request #5687
Opened 2023-03-31 10:11 UTC by BalliAsghar

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-04-03 21:42 UTC, es183923 commented
I'm not sure that the delete forever option is a good idea. I think just having the move to trash option is enough.

2023-04-04 06:55 UTC, BalliAsghar commented
> I'm not sure that the delete forever option is a good idea. I think just having the move to trash option is enough.

I understand your concern. In the updated implementation, the Delete action is optional and controlled by the showDeleteOption preference. By setting it to false, only the "Move to Trash" option will be available. Users who want the Delete action can enable it by setting showDeleteOption to true. This ensures a safer default while still providing the option for those who need it.

2023-04-06 13:58 UTC, thomaslombart requested changes
Thanks for this PR. I've reviewed it and have some feedback.

Please, request a new review when you are ready. Feel free to contact me here or in the [Slack community](https://www.raycast.com/community) if you have any questions.Thanks for this PR 😊
I've reviewed it and have some feedback:



Please, request a new review when you are ready. Feel free to contact me here or in the [Slack community](https://www.raycast.com/community) if you have any questions.

2023-04-06 13:58 UTC, thomaslombart commented on extensions/file-manager/src/utils.tsx
> +}
Given the delete actions are permanent, it'd be better to let users know what they're doing is irreversible.

```suggestion
export async function deleteFile(filePath: string, fileName: string, refresh: () => void) {
  const options: Alert.Options = {
    title: "Permanently Delete File?",
    message: `Are you sure you want to delete ${fileName}? This action cannot be undone.`,
    icon: Icon.Eraser,
    primaryAction: {
      title: "Delete",
      style: Alert.ActionStyle.Destructive,
      onAction: async () => {
        await runShellScript(`rm -rf "${filePath}"`);
        refresh();
        showToast(Toast.Style.Success, "File Deleted", `${fileName}`);
      },
    },
  };

  await confirmAlert(options);

  return;
}
```

2023-04-06 13:58 UTC, thomaslombart commented on extensions/file-manager/src/utils.tsx
> +}
```suggestion
export async function deleteDirectory(folderPath: string, folderName: string, refresh: () => void) {
  const options: Alert.Options = {
    title: "Permanently Delete Directory?",
    message: `Are you sure you want to delete ${folderName}? This action cannot be undone.`,
    icon: Icon.Eraser,
    primaryAction: {
      title: "Delete",
      style: Alert.ActionStyle.Destructive,
      onAction: async () => {
        await runShellScript(`rm -rf "${folderPath}"`);
        refresh();
        showToast(Toast.Style.Success, "Directory Deleted", `${folderName}`);
      },
    },
  };

  await confirmAlert(options);

  return;
}
```

2023-04-06 13:58 UTC, thomaslombart commented on extensions/file-manager/src/utils.tsx
> +  showDeleteOption: boolean;
```suggestion
  showDeleteActions: boolean;
```

2023-04-06 13:58 UTC, thomaslombart commented on extensions/file-manager/src/utils.tsx
> +          {preferences.showDeleteOption && (
```suggestion
          {preferences.showDeleteActions && (
```

2023-04-06 13:58 UTC, thomaslombart commented on extensions/file-manager/src/utils.tsx
> +          {preferences.showDeleteOption && (
```suggestion
          {preferences.showDeleteActions && (
```

2023-04-06 13:58 UTC, thomaslombart commented on extensions/file-manager/src/utils.tsx
> +            {preferences.showDeleteOption && (
```suggestion
            {preferences.showDeleteActions && (
```

2023-04-06 13:58 UTC, thomaslombart commented on extensions/file-manager/src/utils.tsx
> +            {preferences.showDeleteOption && (
```suggestion
            {preferences.showDeleteActions && (
```

2023-04-06 15:24 UTC, thomaslombart approved these changes
Looks good to go! 🚀

2023-04-06 15:25 UTC, merged