Add doccheck extension
raycast/extensions pull request #5707
Opened 2023-04-01 11:02 UTC by justspacedog

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-04-13 12:34 UTC, justspacedog commented
Permission to use the Logo of the site was granted by Dr. med. Frank Antwerpes via mail.

2023-04-13 15:41 UTC, sxn requested changes
hi @justspacedog, thanks for the PR! Overall looks good, I just left a couple of suggestions for improvements 😸

Ping me once you've had a chance to look over them, or if something's unclear. 😉

2023-04-13 15:41 UTC, sxn commented on extensions/doccheck/CHANGELOG.md
> +- NEW: Open article directly in Raycast using deeplinks (you can even go back one time!)
why are some changelog entries in english and some in german? 🤔

2023-04-13 16:31 UTC, justspacedog commented on extensions/doccheck/src/doccheck-flexikon.tsx
> +  }, [query]);
Thank you for this one too!

2023-04-18 09:37 UTC, justspacedog reviewed
I finally had a chance to skim the `useEffect` documentation - the suggestions look like best practice. Thank you for your code review!

2023-04-18 19:29 UTC, sxn approved these changes

2023-04-18 19:29 UTC, merged