Update sips extension
raycast/extensions pull request #5743
Opened 2023-04-03 19:09 UTC by arronhunt

## Description

This change updates Stephen Kaplan's (@SKaplanOfficial) [Image Modification extension](https://www.raycast.com/HelloImSteven/sips) to show real previews of image filters. Currently only a list with descriptions is displayed, and adding a visual preview can help users make better decisions and see a preview of the output before committing to a change. 

## Screencast

<img width="912" alt="image" src="https://user-images.githubusercontent.com/298336/229604706-e7ae3b39-015e-4203-a60b-da8765179a21.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-04-03 19:54 UTC, SKaplanOfficial requested changes
Really good change! Just some minor problems with the package.json, otherwise looks good!

2023-04-03 19:54 UTC, SKaplanOfficial commented on extensions/sips/package.json
> -      ]
I think the arguments were removed by mistake? They're needed for the command to be useful.

2023-04-03 19:54 UTC, SKaplanOfficial commented on extensions/sips/package.json
> -      ]
Same as above

2023-04-03 19:54 UTC, SKaplanOfficial commented on extensions/sips/package.json
> -      ]
Same as above

2023-04-03 19:54 UTC, SKaplanOfficial commented on extensions/sips/package.json
> -      ]
Same as above

2023-04-03 21:09 UTC, arronhunt commented
Thanks @SKaplanOfficial, I didn't touch package.json myself so something must have happened during the fork 😟. Should be an easy fix though.

2023-04-04 00:01 UTC, SKaplanOfficial approved these changes

2023-04-06 14:15 UTC, thomaslombart approved these changes
Nice changes! Let's ship it 🚢

2023-04-06 14:15 UTC, merged