Add 1password7 extension
raycast/extensions pull request #58
Opened 2021-10-16 12:23 UTC by khasbilegt

## Description

**This extension is based on @tdwesten 's original alpha codebase. Thank you for allowed me to port it to the public API.**

1Password 7 extension that allows you to view, edit and open & fill your passwords from Raycast. It consists of single command which lists all the passwords the user currently have. 

## Type of change

- New extension

## Screencast

![output](https://user-images.githubusercontent.com/9023312/137586716-9156d068-f2dc-4291-9cc9-09448da83bb9.gif)

## Checklist

- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2021-10-16 13:59 UTC, tdwesten commented
Thanks for upgrading my code!

2021-10-19 07:42 UTC, PitNikola requested changes
Thanks for your contribution! Looks pretty good 👏, I only have few small minor suggestions we'll need to address before merging.

Also please use 512x512 icon, right now you have 256x256

2021-10-19 07:42 UTC, PitNikola commented on extensions/1password7/package.json
> +  "title": "1Password 7 for Raycast",
No need to specify "for Raycast", it's implied. Let's just leave "1Password 7".

2021-10-19 07:42 UTC, PitNikola commented on extensions/1password7/package.json
> +      "subtitle": "Command",
```suggestion
      "subtitle": "1Password",
```

2021-10-19 07:42 UTC, PitNikola commented on extensions/1password7/src/list.tsx
> +1. Make sure you have te right 1Password app version, it should be 7.
```suggestion
1. Make sure you have the right 1Password app version, it should be 7.
```

2021-10-19 12:27 UTC, khasbilegt commented
@PitNikola , I made the changes that you suggested 😎

2021-10-25 08:27 UTC, merged