Add remove-decorators extension
raycast/extensions pull request #5830
Opened 2023-04-08 20:00 UTC by Pawel-Kica

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-04-08 20:26 UTC, Pawel-Kica commented
Simple extension to replace 
```@ObjectType()
@Entity(tableNames.users)
export class User {
    @Field()
    @PrimaryGeneratedColumn('uuid')
    user_id: string;

    @Field()
    @Column({ unique: true })
    username: string;
}
```
with this
```
export class User {
    user_id: string;

    username: string;
}
```
useful for NestJS types sharing

2023-04-08 20:27 UTC, Pawel-Kica commented
based on json-format existing extension https://github.com/raycast/extensions/tree/59087c124218d0aa70034caa193aaa6d15a905a7/extensions/json-format/

2023-04-14 13:03 UTC, sxn commented on extensions/remove-decorators/src/removeDecoratorsClipboard.tsx
> +  await removeDecorators((await Clipboard.readText()) || "");
you could also use [getSelectedText](https://developers.raycast.com/api-reference/environment#getselectedtext) – should improve UX 😃

2023-04-14 13:04 UTC, sxn commented on extensions/remove-decorators/README.md
> +# Everything
mind adding something to the readme?

2023-04-14 13:07 UTC, sxn requested changes
hey @Pawel-Kica, thanks for the PR! I left a couple of suggestions for improvements, let me know when you've had time to address them 😺

2023-04-14 13:07 UTC, sxn commented on extensions/remove-decorators/CHANGELOG.md
> +## [Initial Version] - 2022-10-23
this date is about 6 months in the past 😅

2023-04-14 13:07 UTC, sxn commented on extensions/remove-decorators/src/removeDecoratorsClipboard.tsx
> +  await removeDecorators((await Clipboard.readText()) || "");
you could also use [getSelectedText](https://developers.raycast.com/api-reference/environment#getselectedtext) – should improve UX 😃

2023-04-14 13:09 UTC, Pawel-Kica commented
Thank you, will review it!!!

2023-05-05 16:03 UTC, closed without merging