WIP: debank client
raycast/extensions pull request #587
Opened 2022-01-01 13:48 UTC by Yukaii

## Description

## Type of change

- New extension
- Bug fix / improvement for my extension
- Bug fix / improvement for somebody else's extension. Extension author: @GH-handle
- Documentation update
- Other (Specify)

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2022-01-02 13:57 UTC, pernielsentikaer requested changes
Hi @Yukaii 👋 

It looks nice, even though I don't have a way to fully test it I guess 😄 Could you remove the `command-icon.png` icon from assets, no need to have it there 😄 

When it's removed, I think we're ready to get it merged 💯 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-02 18:39 UTC, pernielsentikaer approved these changes
Hi @Yukaii 👋 

Thank you for the existing extension, I'm sure it's possible to extend further later on 💪 

I'm going to accept it and then will my colleague do a final review before it's finally merged 🚀

2022-01-04 11:56 UTC, mathieudutour requested changes
Looking good, but the UX for loading Lists could be improved (see comments)

2022-01-04 11:56 UTC, mathieudutour commented on extensions/debank/src/index.tsx
> +    <List onSearchTextChange={onChange}>
What do you think about setting the `isLoading` prop when you are loading the address?

2022-01-04 11:56 UTC, mathieudutour commented on extensions/debank/src/index.tsx
> +        <List.Item key="1" title="Loading..." />
the recommended UX when loading a list content is to render an empty List with `isLoading` set to true (https://developers.raycast.com/api-reference/user-interface/list#list)

2022-01-04 11:56 UTC, mathieudutour commented on extensions/debank/src/index.tsx
> +        <List.Item key="1" title="Loading..." />
same as above

2022-01-05 08:39 UTC, mathieudutour approved these changes
Looks good, thanks!

2022-01-05 08:39 UTC, merged