Add biaodian - the chinese punctuation marks extension
raycast/extensions pull request #588
Opened 2022-01-01 14:08 UTC by gasolin

## Description

Add the Chinese punctuation marks (中文標點符號, `biaodian` is the spell of `標點` in chinese)
http://www.tdtb.org/information_nvda_view.aspx?nid=20150508093617

some common punctuation marks (ex: ，。 )are able to type via keyboard with input method (IME), but some (ex:、「」) are not that easy.

With this extension you can list or search via english punctuation marks (ex: . , [ ]) to find the chinese punctuation marks (。，『』)

## Type of change

- New extension

## Screencast

![](http://g.recordit.co/xCV13mtqjU.gif)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2022-01-02 14:03 UTC, pernielsentikaer requested changes
Hi @gasolin 👋 

I only have a single suggestion before it should be fine to ship 🚢 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-02 14:03 UTC, pernielsentikaer commented on extensions/biaodian/package.json
> +      "title": "Biaodian (Chinese Punctuation Marks)",
```suggestion
      "title": "Biaodian",
```

2022-01-03 00:09 UTC, gasolin commented
@pernielsentikaer updated, thanks

2022-01-03 06:26 UTC, pernielsentikaer requested changes
Hi @gasolin 👋 

Forgot that there was no subtitle, could you add suggested 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-03 06:26 UTC, pernielsentikaer commented on extensions/biaodian/package.json
> +      "title": "Biaodian",
```suggestion
      "title": "Biaodian",
      "subtitle": "Chinese Punctuation Marks",
```
Sorry I forgot to add the subtitle, could you add?

2022-01-03 12:18 UTC, gasolin commented
@pernielsentikaer added, please kindly review again

2022-01-03 18:07 UTC, pernielsentikaer approved these changes
hi @gasolin 👋 

Much better 💯  I'm going to accept it and then will my colleague do a final review before it's finally merged 💎

2022-01-04 08:18 UTC, mathieudutour approved these changes
Looking good, well done :+1:

2022-01-04 08:18 UTC, merged