Add random email extension
raycast/extensions pull request #592
Opened 2022-01-03 12:09 UTC by rkjaer

## Description

A configurable extension for generating "random" (time-based) emails and copying/pasting them afterwards.

## Type of change

- New extension

## Screencast

![CleanShot 2022-01-03 at 12 56 18](https://user-images.githubusercontent.com/208038/147928517-9709dbf0-2f27-4055-8302-193ba90f0753.png)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2022-01-07 20:45 UTC, pernielsentikaer requested changes
Hi @rkjaer 🇩🇰 

Thanks for your contribution, I only have two small suggestion for you before I think we're ready to proceed 🔥 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-07 20:45 UTC, pernielsentikaer commented on extensions/random-email/package.json
> +      "title": "Paste random email",
```suggestion
      "title": "Paste Random Email",
```

2022-01-07 20:45 UTC, pernielsentikaer commented on extensions/random-email/package.json
> +      "title": "Copy random email",
```suggestion
      "title": "Copy Random Email",
```

2022-01-08 13:09 UTC, pernielsentikaer approved these changes
Hi @rkjaer 👋 

Thanks for the update 🇩🇰 🔥 I'm going to accept it and then will my colleague do a final review before it's finally merged. Thanks again for your contribution 🚀

2022-01-08 13:18 UTC, rkjaer commented
Thanks a lot @pernielsentikaer 🥳🇩🇰🍻

2022-01-10 21:37 UTC, merged