Adding BTTV Emotes Extension
raycast/extensions pull request #600
Opened 2022-01-04 13:20 UTC by Aayush9029

## Description

Lets you browse [BTTV Emote library](https://betterttv.com/emotes/top) and copy gif, image url directly to clipboard!

## Type of change

- New extension

## Screencast
![AShot-2022 01 04-08 12 30](https://user-images.githubusercontent.com/43297314/148065092-971d6760-89e7-4a47-8d2c-cc4bdceca8a4.gif)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2022-01-04 13:25 UTC, Aayush9029 commented
🖐️ Hi there!

Here are some popular emote names for you to try

- catJAM
- GIGACHAD
- HYPERS
- peped

These are not case sensitive :)

2022-01-08 21:00 UTC, pernielsentikaer requested changes
Hi @Aayush9029 🧇 

Thanks for the extension 🔥 I left a few suggestions and comments for you to work on

- You could also make “Top Emotes” and “Trending Emotes” commands

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-08 21:00 UTC, pernielsentikaer commented on extensions/bttv-emote/package.json
> +        "subtitle": "BTTV Emotes Search",
```suggestion
        "title": "Search Emote",
        "subtitle": "BetterTTV",
```

2022-01-08 21:00 UTC, pernielsentikaer commented on extensions/bttv-emote/src/index.tsx
> +              title="Copy emote"
```suggestion
              title="Copy Emote"
```

2022-01-08 21:00 UTC, pernielsentikaer commented on extensions/bttv-emote/src/index.tsx
> +              title="Paste emote"
```suggestion
              title="Paste Emote"
```

2022-01-08 21:00 UTC, pernielsentikaer commented on extensions/bttv-emote/src/index.tsx
> +              title="Open in Browser"
```suggestion
```
This is redundant since it's the default title.

2022-01-08 21:00 UTC, pernielsentikaer commented on extensions/bttv-emote/src/index.tsx
> +async function performSearch(searchText: string, signal: AbortSignal): Promise<Emote[]> {
When searching for less than three characters, it still makes a fetch call, that's unnecessary. It should not make any calls when it's not possible.

2022-01-20 21:43 UTC, pernielsentikaer commented
Hi @Aayush9029 👋 

It looks like the formatting of this extension needs to be run through Prettier in order to match the right style, could you do that? Reach out to me in the extension channel in Slack if you need help 💯

2022-01-21 21:19 UTC, Aayush9029 commented
@pernielsentikaer Everything is properly formatted now 💪

*imho* Top/Trending Emotes isn't that useful, you can think of Emotes as Emojis  ~~on Steroids~~
![peped](https://cdn.betterttv.net/emote/61e9ee1a06fd6a9f5be17d34/2x.gif) ![peped](https://cdn.betterttv.net/emote/61e9ee1a06fd6a9f5be17d34/2x.gif) ![peped](https://cdn.betterttv.net/emote/61e9ee1a06fd6a9f5be17d34/2x.gif) ![peped](https://cdn.betterttv.net/emote/61e9ee1a06fd6a9f5be17d34/2x.gif)

2022-01-21 22:01 UTC, pernielsentikaer requested changes
Hi @Aayush9029 👋 

Just a single correction, could we do this? When it's done, then we're ready to merge 💯 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-21 22:01 UTC, pernielsentikaer commented on extensions/bttv-emote/package.json
> +      "subtitle": "BTTV Emotes Search",
```suggestion
      "title": "Search Emote",
      "subtitle": "BTTV Emotes",
```

2022-01-22 01:56 UTC, Aayush9029 commented
@pernielsentikaer Done 😊 🎉

2022-01-22 06:05 UTC, pernielsentikaer approved these changes
Hi @Aayush9029 👋 

Thanks! I'm going to accept it and then will my colleague do a final review before it's finally merged.

2022-01-24 17:05 UTC, mathieudutour approved these changes

2022-01-24 17:05 UTC, merged