Add laravel-vapor extension
raycast/extensions pull request #6026
Opened 2023-04-19 02:43 UTC by tcampbPPU

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-04-24 12:34 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-04-24 12:34 UTC, pernielsentikaer commented on extensions/laravel-vapor/src/list-domains.tsx
> +      {isLoading && <List.Item title="Loading..." />}
You should add `isLoading` property to the `<List>` instead of having it as an item, this is the same for all commands.

2023-04-24 13:53 UTC, tcampbPPU commented
hey @pernielsentikaer thanks for the review! I've updated each of those command components.

2023-04-25 14:33 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-04-25 14:34 UTC, merged