Add qotp extension
raycast/extensions pull request #6027
Opened 2023-04-19 03:51 UTC by ariesly15

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-04-24 12:40 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* You can use [getProgressIcon](https://developers.raycast.com/utilities/icons/getprogressicon) instead of the images

* At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.  

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-04-25 07:56 UTC, pernielsentikaer reviewed
Could you please remove all the icons not needed anymore 😊

2023-04-27 05:20 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* The logo is not a good extension icon due to the transparency, you can maybe use [icon.ray.so](https://icon.ray.so/) to generate one 😊 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-04-27 05:20 UTC, pernielsentikaer commented on extensions/qotp/README.md
> +## [secret 获取教程](https://sourl.cn/4NfR9x)
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2023-04-27 05:20 UTC, pernielsentikaer commented on extensions/qotp/package.json
> +      "placeholder": "qotp.corp 平台中用户设置的6位密码"
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2023-04-27 05:20 UTC, pernielsentikaer commented on extensions/qotp/package.json
> +      "description": "跳板机登录线上机器的密码"
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2023-04-27 05:20 UTC, pernielsentikaer commented on extensions/qotp/package.json
> +      "placeholder": "请填写数字"
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2023-04-27 05:20 UTC, pernielsentikaer commented on extensions/qotp/plugins.json
> +  "description": "生成 OTP 六位动态码",
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2023-04-27 05:20 UTC, pernielsentikaer commented on extensions/qotp/src/menu-bar-qotp.tsx
> +    <MenuBarExtra icon="otp.png" tooltip="点击查看OTP">
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2023-04-27 11:42 UTC, pernielsentikaer commented
Should I help you with a proper logo?

2023-04-27 11:52 UTC, ariesly15 commented
> Should I help you with a proper logo?

Yes, I do. Thank you👏

2023-04-28 07:08 UTC, pernielsentikaer commented
What do you think about this one?

![qotp](https://user-images.githubusercontent.com/38033107/235078820-a8e1fd75-2c5d-4bb1-8c64-b71e1d75e7f3.png)

2023-04-28 07:22 UTC, ariesly15 commented
> What do you think about this one?
> 
> ![qotp](https://user-images.githubusercontent.com/38033107/235078820-a8e1fd75-2c5d-4bb1-8c64-b71e1d75e7f3.png)

I think it's great.

2023-04-28 09:47 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-04-28 09:47 UTC, merged