🏏 Add CricketCast Extension
raycast/extensions pull request #616
Opened 2022-01-06 05:25 UTC by sampoder

## Description

Allows you to check the cricket scores of ongoing games.

## Type of change

**New extension**

## Screencast

https://user-images.githubusercontent.com/39828164/148332824-128ce014-35aa-4acf-8aea-a3ea365eea6c.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2022-01-09 20:57 UTC, pernielsentikaer requested changes
Hi @sampoder 👋 

Thanks for the contribution, I left a few suggestions and comments, could you look into them?

There is also an image in the root on the extension (command-icon.png) seems like it should be removed to?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-09 20:57 UTC, pernielsentikaer commented on extensions/cricketcast/package.json
> +      "title": "Show The Cricket Scores",
```suggestion
      "title": "Cricket Scores",
```

2022-01-09 20:57 UTC, pernielsentikaer commented on extensions/cricketcast/src/index.jsx
> +    </ActionPanel>
Better only having one ActionPanel.Section, then will the second item automatically get a modifier

2022-01-09 20:57 UTC, pernielsentikaer commented on extensions/cricketcast/src/index.jsx
> +        let JSONdata = JSON.parse(await convert.xml2json(XMLdata, { compact: true, spaces: 4 }));
```suggestion
        let JSONdata = JSON.parse(convert.xml2json(XMLdata, {compact: true, spaces: 4}));
```
Unnecessary await removed

2022-01-09 20:57 UTC, pernielsentikaer commented on extensions/cricketcast/src/index.jsx
> +          id: match.guid["_text"].replace("http://www.cricinfo.com/ci/engine/match/", "").replace(".html", ""),
```suggestion
          id: match.guid["_text"].replace( /\D+/g, ''),
```
Could be replaced with this instead, the current format is always the same.

2022-01-09 23:46 UTC, sampoder commented
Thanks @pernielsentikaer, just committed some fixes!

2022-01-10 21:03 UTC, pernielsentikaer approved these changes
Hi @sampoder 👋 

Thanks for the corrections, I can't find anything else that should be corrected 🔥 I'm going to accept it and then will my colleague do a final review before it's finally merged.

2022-01-10 21:50 UTC, merged