Add Markdown Reference extension
raycast/extensions pull request #622
Opened 2022-01-06 20:42 UTC by codedbyjordan

## Description

This extension allows you to quickly search Markdown syntax if you're like me and forget it a lot

## Type of change

New extension

## Screencast

![](https://media1.giphy.com/media/i7q6ZfztnIES4gsRjL/giphy.gif?cid=790b7611384608977e5cad9cc19ccf6f28e4a754ffe05527&rid=giphy.gif&ct=g)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2022-01-09 21:21 UTC, pernielsentikaer requested changes
Hi @codedbyjordan 👋 

Congratulations on your first contribution here, awesome extensions!

I left some comments for you to look into 🔥 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-09 21:21 UTC, pernielsentikaer commented on extensions/markdown-reference/package.json
> +      "title": "Markdown Reference - Search Markdown Syntax",
```suggestion
      "title": "Search Reference",
      "subtitle": "Markdown Syntax",
```

2022-01-09 21:21 UTC, pernielsentikaer commented on extensions/markdown-reference/src/markdown-escape.ts
> +  [/\]/g, "\\]", "square brackets"],
```suggestion
  [/]/g, "\\]", "square brackets"],
```
Removed unnecessary escape

2022-01-10 01:56 UTC, codedbyjordan commented
> Hi @codedbyjordan 👋
> 
> Congratulations on your first contribution here, awesome extensions!
> 
> I left some comments for you to look into 🔥
> 
> Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

Ready!

2022-01-10 21:11 UTC, pernielsentikaer approved these changes
hi @codedbyjordan 👋 

Awesome, thanks for the corrections 🔥 I'm going to accept it and then will my colleague do a final review before it's finally merged 🚢

2022-01-10 22:00 UTC, fe9lix commented
Hey @codedbyjordan, one suggestion from my side: how about showing aa reference list items when opening the command? (The default "No results" right after opening the commands is not so nice for end users...)

2022-01-11 04:54 UTC, pernielsentikaer commented
That makes totally sense, we should 100% do that 😄

2022-01-12 04:26 UTC, codedbyjordan commented
> That makes totally sense, we should 100% do that 😄

Added!

2022-01-12 04:27 UTC, codedbyjordan commented
> Hey @codedbyjordan, one suggestion from my side: how about showing a reference list items when opening the command? (The default "No results" right after opening the command is not so nice for end users...)

Good suggestion! Added that in :)

2022-01-12 11:30 UTC, fe9lix commented
One more nit: "Markdown Reference - Search Markdown Syntax" as command title feels too long. I would shorten this to just "Search Markdown Syntax" (you could add  "Markdown Reference" as subtitle but it doesn't seem to add much to the command title so I would rather leave that empty).

2022-01-12 13:56 UTC, codedbyjordan commented
> One more nit: "Markdown Reference - Search Markdown Syntax" as command title feels too long. I would shorten this to just "Search Markdown Syntax" (you could add "Markdown Reference" as subtitle but it doesn't seem to add much to the command title so I would rather leave that empty).

Got it :) Thank you !!

2022-01-12 14:06 UTC, pernielsentikaer commented
Much better @codedbyjordan 🔥

2022-01-12 14:24 UTC, merged