Laravel Livewire documentation extension
raycast/extensions pull request #625
Opened 2022-01-06 23:43 UTC by tafhyseni

## Description

Adds Laravel Livewire Documentation to Raycast

- New extension

## Screencast

Included within extension's readme
## Checklist

- [ Done ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ Done ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2022-01-11 21:01 UTC, pernielsentikaer requested changes
Hi @tafhyseni 👋 

Awesome extension 🔥 – I have a few ideas, suggestions, and corrections for you to work on:

- Could be awesome if the icon had transparent background
- Could be cool to add versions like it's done in #607 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-11 23:20 UTC, tafhyseni commented
Hello @pernielsentikaer 🤙

Thank you so much!
I have already made two changes:

- - Added versions via json files which get pulled by selected preference
- - Replaced current icon with a new icon without transparent

Please, let me know if you propose further changes and/or addons!

2022-01-12 12:59 UTC, pernielsentikaer requested changes
Wow, @tafhyseni! 🚀 

It looks so gorgeous with the new corrections, MUCH better!

I left a few comments for you to work with before we're ready to merge 💎 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-12 12:59 UTC, pernielsentikaer commented on extensions/laravel-livewire/package.json
> +          "default": "1.x",
```suggestion
          "default": "2.x",
```
Wouldn't it make more sense to have the newest as default?

2022-01-12 12:59 UTC, pernielsentikaer commented on extensions/laravel-livewire/src/documentation/1.x.json
> +    { "url": "https://laravel-livewire.com/docs/1.x/quickstart", "title": "Quickstart1" },
```suggestion
    { "url": "https://laravel-livewire.com/docs/1.x/quickstart", "title": "Quickstart" },
```
Remove debug number 😄

2022-01-12 12:59 UTC, pernielsentikaer commented on extensions/laravel-livewire/src/documentation/2.x.json
> +    { "url": "https://laravel-livewire.com/docs/2.x/quickstart", "title": "Quickstart2" },
```suggestion
    { "url": "https://laravel-livewire.com/docs/2.x/quickstart", "title": "Quickstart" },
```
Remove debug number 😄

2022-01-12 21:58 UTC, tafhyseni commented
Hey @pernielsentikaer 

I think we are READY 🤩

2022-01-13 05:51 UTC, pernielsentikaer approved these changes
Yeah, @tafhyseni! 🔥 

I also think we're ready 🚀  I'm going to accept it and then will my colleague do a final review before it's finally merged. Thanks for your contribution

2022-01-13 12:04 UTC, mattisssa approved these changes

2022-01-13 12:04 UTC, merged