Add one-time-password extension
raycast/extensions pull request #6338
Opened 2023-05-04 23:25 UTC by lacherogwu

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-05-04 23:32 UTC, lacherogwu commented
@Aayush9029 Did my best here 🤓 hope you will like the changes

btw why lint complains?
![CleanShot 2023-05-05 at 02 30 44](https://user-images.githubusercontent.com/49835614/236351336-260a9664-8741-4f2d-99de-cc9703a95334.png)

I've used the `Raycast Window Capture`

2023-05-05 01:02 UTC, Aayush9029 commented
> Did my best here 🤓 hope you will like the changes

love it

2023-05-05 06:02 UTC, lacherogwu commented
> 

Yeah I am using external monitor, Okay let me re-take them

2023-05-07 12:14 UTC, lacherogwu commented
I added support to import accounts from Google Authenticator, but encountered an issue while trying to save the `﻿migrationPayload` (in `google-authenticator.ts`) string in a dedicated file called `﻿migration.proto`. My plan was to load the file using ﻿`protofuf.load()` with a path parameter. However, when I provided the path parameter, the file couldn’t be found. I realized that the extension was saved in the build code, which doesn’t have the ﻿src directory, only the ﻿assets directory. 
The path to the file was `﻿/Users/asaf/.config/raycast/extensions/one-time-password`. I’m unsure if the ﻿assets directory is the appropriate place for other files.

2023-05-15 11:43 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-05-15 11:43 UTC, pernielsentikaer commented on extensions/one-time-password/src/one-time-password.tsx
> +  }
Could be better to rely on Color.Green / Color.Red from Raycast?

2023-05-17 20:56 UTC, pernielsentikaer commented
Hi @lacherogwu 👋 

You should use [supportPath](https://developers.raycast.com/api-reference/environment#properties) for your files - could you try that 🙂

2023-05-18 11:59 UTC, lacherogwu commented
> Hi @lacherogwu 👋
> 
> You should use [supportPath](https://developers.raycast.com/api-reference/environment#properties) for your files - could you try that 🙂

I think that doesn't help.
I want the file to be stored in the source code somewhere and then to read it in runtime

2023-05-19 06:45 UTC, pernielsentikaer commented
And you already tried adding it to the `assetsPath` folder? I'm not sure what you're trying to achieve, is there no way to load from a node_module?

2023-05-19 06:46 UTC, lacherogwu commented
No I haven’t try, I was just asking if assets will be the right place for
this file

On Fri, 19 May 2023 at 9:45 AM, Per Nielsen Tikær ***@***.***>
wrote:

> And you already tried adding it to the assetsPath folder? I'm not sure
> what you're trying to achieve, is there no way to load from a node_module?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/raycast/extensions/pull/6338#issuecomment-1554086437>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AL4G4XSZLB4NPJKD7KTKS53XG4JJPANCNFSM6AAAAAAXWNRNOI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-19 06:47 UTC, lacherogwu commented
No I haven’t try, I was just asking if assets will be the right place for this file

2023-05-19 06:49 UTC, pernielsentikaer commented
We have other extension that have some files in the `assets` folder

2023-05-19 06:50 UTC, lacherogwu commented
Okay so I guess it's the right place, let me add it there

2023-05-19 07:10 UTC, lacherogwu commented
@pernielsentikaer You can now review all at once

2023-05-19 11:33 UTC, pernielsentikaer commented on extensions/one-time-password/src/store.ts
> +  const accounts = await getAccounts();
I would add a [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert#confirmalert) here 🙂

2023-05-22 08:30 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-05-22 08:30 UTC, merged