add: dockerhub extension
raycast/extensions pull request #637
Opened 2022-01-10 00:42 UTC by k8scat

## Description

Search images in DockerHub, only this now.

## Type of change

New extension

## Screencast

![image](https://user-images.githubusercontent.com/55872984/148707831-374b5ed9-7d01-474c-b5be-5fe2ba706a2e.png)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2022-01-12 22:25 UTC, fe9lix requested changes
Hey @k8scat, thanks for the contribution! I've left a comment re command title and subtitle. 
Another suggestion: is there a default list you could load (latest, most popular, ...)? Currently the default state is an empty list, which is not the nicest experience for end users.

2022-01-12 22:25 UTC, fe9lix commented on extensions/dockerhub/package.json
> +      "description": "Search images on Docker Hub",
I'd suggest to use "Search Docker Images" as title and leave the subtitle empty. Also see our store guidelines: https://developers.raycast.com/basics/prepare-an-extension-for-store

2022-01-14 02:44 UTC, k8scat commented
Is there a best practice for the list pagination instead showing all items?

2022-01-14 08:15 UTC, fe9lix commented
> Is there a best practice for the list pagination instead showing all items? @fe9lix

Nope, list pagination is not yet supported. You can group items into sections in a list. For now, it's best to only load a subset (list should not contain more than 1000 entries) and then use search to narrow it down. If you want to support different lists, the best way is to create a separate command for it.

2022-01-14 08:45 UTC, fe9lix commented
Thanks for the updates. Just tested again and I run into an error when I open the command and then type "u" into the search bar. I get a Toast with "Search failed" and "Cannot read properties of null (reading 'map')"

2022-01-17 02:41 UTC, k8scat commented
> Thanks for the updates. Just tested again and I run into an error when I open the command and then type "u" into the search bar. I get a Toast with "Search failed" and "Cannot read properties of null (reading 'map')"

Fixed. And this pr is done if there is no problem.

2022-01-17 11:48 UTC, fe9lix commented
Thanks for the update! Two more things I've noticed:
- I get duplicate keys warnings in the console from React – probably coming from the key property of some list items (key should have a stable identity and be assigned to the top-level component in case the list item is wrapped in another component)
- Please use the action form for action panel items, i.e. "Tags" should be "Show Tags"...

2022-01-17 12:23 UTC, k8scat commented
> * use the action form for action panel items

What does `use the action form for action panel items` mean? Is that suggest to use `SubmitFormAction` instead of `PushAction`?

2022-01-17 12:57 UTC, fe9lix commented
> > * use the action form for action panel items
> 
> What does `use the action form for action panel items` mean? Is that suggest to use `SubmitFormAction` instead of `PushAction`?

Sorry, no, I meant grammatically: "Show Tags" (action) instead of just "Tags" (Noun), also see the store guidelines on this: https://developers.raycast.com/basics/prepare-an-extension-for-store

2022-01-17 13:12 UTC, k8scat commented
> > > * use the action form for action panel items
> > 
> > 
> > What does `use the action form for action panel items` mean? Is that suggest to use `SubmitFormAction` instead of `PushAction`?
> 
> Sorry, no, I meant grammatically: "Show Tags" (action) instead of just "Tags" (Noun), also see the store guidelines on this: https://developers.raycast.com/basics/prepare-an-extension-for-store

Already fixed.

2022-01-17 13:14 UTC, fe9lix approved these changes

2022-01-17 13:14 UTC, merged