feat: support custom lark domain
raycast/extensions pull request #6444
Opened 2023-05-10 04:16 UTC by xiacongling

## Description

support custom domain names for Lark extension.

This patch fixes #6443  

## Screencast

![screenshot-20230510-120824](https://github.com/raycast/extensions/assets/4011997/ff6ccf0b-2a15-4955-a3b1-d76ef6e5e04d)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-05-10 04:25 UTC, tmkx commented
looks good, but I'm worried that it raises the threshold for users who don't understand technology to use it

2023-05-10 05:57 UTC, tmkx commented
can we add a `"Self-Hosted"` type and a new optional `selfHostedDomain` in the config? so that it won't affect current users and they won’t need to learn how to choose between "feishu.cn" and "larksuite.com"

2023-05-12 16:32 UTC, tmkx commented
@xiacongling hi there, it looks like there haven't been any updates recently, would you like me to lend a hand?

2023-05-12 16:45 UTC, xiacongling commented
hi, @tmkx . It would be great if you could help! Since the optional field will not be displayed on the extension initialization page, the domain information cannot be entered when type is self-hosted. I wonder if we need to add an additional form to enter the domain name instead of going to raycast's extension preferences page to set it manually.

2023-05-16 11:42 UTC, tmkx requested changes

2023-05-16 11:42 UTC, tmkx commented on extensions/lark/package.json
> +      "name": "domain",
```suggestion
      "name": "type",
```

2023-05-16 11:48 UTC, tmkx commented
@pernielsentikaer This PR is ready for review, thanks!

2023-05-16 12:11 UTC, merged