Update imessage-2fa extension
raycast/extensions pull request #6446
Opened 2023-05-10 05:19 UTC by fengtianze

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-05-11 14:22 UTC, fengtianze commented
@thomaspaulmann Please help me review this PR. Thank you.

2023-05-12 02:06 UTC, yuercl approved these changes

2023-05-17 07:54 UTC, fengtianze commented
@pernielsentikaer could you check this PR please?

2023-05-17 09:23 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-05-17 09:23 UTC, pernielsentikaer commented on extensions/imessage-2fa/package.json
> +      "name": "view-2fa-codes",
Please don't change the name - this will remove the ranking and alias/hotkeys if possible

2023-05-17 09:23 UTC, pernielsentikaer commented on extensions/imessage-2fa/src/paste-latest-2fa-code.tsx
> +};
Should be a no-view command

2023-05-17 10:39 UTC, pernielsentikaer commented on extensions/imessage-2fa/package.json
> +      "mode": "view"
That's correct that it won't work

You can check how we did it in a `no-view` command [here](https://github.com/raycast/extensions/blob/main/extensions/browser-bookmarks/src/hooks/useFirefoxBookmarks.ts#L145-L147)

2023-05-17 12:43 UTC, fengtianze commented on extensions/imessage-2fa/package.json
> +      "mode": "view"
Thanks. I thought there would only be access to user data via built-in APIs due to security issues, and I'll try to modify it later.

2023-06-13 09:03 UTC, closed without merging