feat(Must): create extension
raycast/extensions pull request #658
Opened 2022-01-12 16:59 UTC by eggsy

## Description

Created an extension for [Must](https://mustapp.com/), a great app to keep track of the movies/series you watched, and the ones you will watch in the future.

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/13917975/149185404-b20a463d-d0e4-48e4-b8c8-abe19795c684.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2022-01-12 23:39 UTC, CanCodes approved these changes
LGTM! Looking forward to using this extension!

2022-01-12 23:40 UTC, Merloss commented
hmm, lgtm

2022-01-13 22:53 UTC, pernielsentikaer requested changes
Hi @eggsy 👋 

Awesome addition, looking forward to use it 🔥 

If I insert a username that don’t exists, it loads forever - here it should show a Failure Toast with a reason and the loader should be stopped with empty array.

Can you look into this?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-13 22:53 UTC, pernielsentikaer commented on extensions/must/package.json
> +      "title": "Must",
```suggestion
      "title": "Watch list",
      "subtitle": "Must",
```

2022-01-13 22:53 UTC, pernielsentikaer commented on extensions/must/package.json
> +      "subtitle": "Your want to watch list on Must.",
```suggestion
```

2022-01-14 00:22 UTC, eggsy commented
Hey @pernielsentikaer, sorry I had to commit via GitHub web because I have other files (extension) that are waiting to be pushed and I didn't want to include them in this PR 😅. It works as you requested now. You can take a look at it again!

2022-01-14 06:20 UTC, pernielsentikaer approved these changes
Hi @eggsy 👋 

MUCH better 🔥 I'm going to accept it and then will my colleague do a final review before it's finally merged – well done! 💎

2022-01-14 08:56 UTC, merged