feat(Last.fm): create extension
raycast/extensions pull request #672
Opened 2022-01-14 14:02 UTC by eggsy

## Description

Must extension to display **Top Songs**, **Recent Songs**, **Top & Recent Songs**, **Top Albums** and **Top Artists** using [Last.fm](https://last.fm)'s API.

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/13917975/149525948-9b23ae6c-ed08-4fb7-99c5-c8376f40d59f.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2022-01-14 14:11 UTC, eggsy commented
> Also updated the typo/grammar issue in Must extension's description

2022-01-14 19:46 UTC, pernielsentikaer requested changes
Hi @eggsy 👋 

I left a few things for you to address, also, could you move the  `types` folder inside `src`.

It's also a bad idea to change other folders within another PR, in this case I will allow it, but next time we need to have it separated.

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-14 19:46 UTC, pernielsentikaer commented on extensions/lastfm/src/albums.tsx
> +            album.image?.find((image) => image.size === "large")?.["#text"] || "https://i.imgur.com/ekASTF4.jpg";
The fallback image should be added as an asset instead

2022-01-14 19:46 UTC, pernielsentikaer commented on extensions/lastfm/src/hooks/useLastfm.ts
> +      `http://ws.audioscrobbler.com/2.0/?method=user.${method}&user=${props.username}&api_key=${
```suggestion
      `https://ws.audioscrobbler.com/2.0/?method=user.${method}&user=${props.username}&api_key=${
```

2022-01-14 19:46 UTC, pernielsentikaer commented on extensions/lastfm/src/hooks/useTopAlbums.ts
> +      `http://ws.audioscrobbler.com/2.0/?method=user.gettopalbums&user=${props.username}&api_key=${
```suggestion
      `https://ws.audioscrobbler.com/2.0/?method=user.gettopalbums&user=${props.username}&api_key=${
```

2022-01-14 19:46 UTC, pernielsentikaer commented on extensions/lastfm/src/hooks/useTopArtists.ts
> +      `http://ws.audioscrobbler.com/2.0/?method=user.gettopartists&user=${props.username}&api_key=${
```suggestion
      `https://ws.audioscrobbler.com/2.0/?method=user.gettopartists&user=${props.username}&api_key=${
```

2022-01-15 15:50 UTC, eggsy commented
All right, created a new branch for the Must update, opened another PR for it and reverted all the changes from this branch so there will not be any confusion here!

2022-01-16 10:45 UTC, pernielsentikaer approved these changes
Hi @eggsy 👋 

Thanks for the update and thanks for seperating the two extensions ❤️ 

I'm going to accept it and then will my colleague do a final review before it's finally merged.

2022-01-17 13:09 UTC, mattisssa approved these changes

2022-01-17 13:09 UTC, merged