Add Node Development Projects Extension
raycast/extensions pull request #678
Opened 2022-01-14 22:10 UTC by grantvanhorn

## Description
Set a node development directory. Node Dev command then allows users to see a list of their node projects. There are two actions to take on each project listed.
1. Open in VSCode
2. Open project file path in Hyper Terminal

## Type of change
- New extension

## Screencast
https://youtu.be/tOBOsMrEPsI

## Checklist

- [ x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2022-01-17 13:17 UTC, mattisssa reviewed
Hey! Thanks for the contribution, I left a small comment about naming. Leaving the main review to @pernielsentikaer now

2022-01-17 13:17 UTC, mattisssa commented on extensions/node-development-projects/package.json
> +      "title": "Node Dev",
```suggestion
      "title": "Search Node Project",
```

2022-01-17 21:24 UTC, pernielsentikaer requested changes
Hi @grantvanhorn 👋 

Awesome extension, I see a lot of potential in it 💪 We left some feedback for you to address

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-17 21:24 UTC, pernielsentikaer commented on extensions/node-development-projects/src/node-dev.tsx
> +            />
I don't have Visual Code or Hyper, so these two actions won't work for me – can you come up with a way to test if it's installed before showing them?

You could also use the below actions:

<ShowInFinderAction path={target} />
<OpenWithAction path={filePath} />

2022-01-17 21:24 UTC, pernielsentikaer commented on extensions/node-development-projects/package.json
> +      "title": "Node Dev",
Plural, with s 😄

2022-01-17 21:24 UTC, pernielsentikaer commented on extensions/node-development-projects/package.json
> +  "description": "Perform actions on Node projects in your development directory. Open projects in VSCode or Hyper Terminal.",
This should maybe be modified after we find a better solution for the actions

2022-02-14 13:41 UTC, mattisssa commented
Hello @grantvanhorn! What is the status of this PR? Can you please take a look at the comments above?

2022-03-07 13:58 UTC, fe9lix commented
Guys, I'm closing this because of inactivity. Feel free to re-open later again!

2022-03-07 13:58 UTC, closed without merging