Home Assistant: Fix connection error when instance url contains a trailing slash
raycast/extensions pull request #682
Opened 2022-01-15 13:25 UTC by tonka3000

## Description

Fix connection error when instance url contains a trailing slash.

Home Assistant websocket based library could not handle trailing slashes, so the PR clean the url before hand it over to the Home Assistant library.

Bug reported via Twitter https://twitter.com/jacoblo/status/1481574977895870464?s=20

## Type of change

- Bug fix / improvement for my extension

## Screencast

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2022-01-18 10:18 UTC, pernielsentikaer requested changes
HI @tonka3000 👋 

One thing I stumbled on is that when preferences are wrong, it's only showing the toast, it would be awesome to have the loader stopped also 😄 

![X7SxLwNmINi9Eh31](https://user-images.githubusercontent.com/38033107/149917874-a60c2dcc-569e-48c7-85eb-50161cdc017c.png)

Besides that, It seems like a nice update 💯 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-19 05:19 UTC, pernielsentikaer requested changes
Hi @tonka3000 👋 

Beautiful! 💪 I can see that it's still a problem with `Batteries`and `All entities with attributes` – could you add it to the two remaining commands?

When it's done, I think we're ready 💯 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-19 07:52 UTC, pernielsentikaer approved these changes
Hi @tonka3000 👋 

Much better 💣  I'm going to accept it and then will my colleague do a final review before it's finally merged.

2022-01-19 15:28 UTC, merged

2022-02-08 23:12 UTC, chen-ye commented
hey, just an FYI, it looks like actual commands are still failing when a trailing slash is present

2022-02-08 23:33 UTC, tonka3000 commented
Hi @chen-ye ,

Can you explain the exact scenario when this happens. Could you not start a command? Or does an action/shortcut does not work?

Thanks in advance
Michael

2022-02-09 04:25 UTC, chen-ye commented
Hi @tonka3000, here is the behavior I'm seeing:

With a trailing slash, the extension can read entity state just fine, but will signal a 404 error when attempting to toggle a light, or a switch (I didn't try any other commands):

Here, I see a 404 error (and the light does not toggle) if I press enter:

![Screen Shot 2022-02-08 at 8 19 21 PM](https://user-images.githubusercontent.com/1904031/153121600-f419fc7e-d703-4ad6-98e3-6868cd8413bc.png)

If I remove the trailing slash in the configuration, the 404 error does not occur.

2022-02-09 04:59 UTC, chen-ye commented
It looks like it's because the API client is still being created with a trailing slash here:
https://github.com/raycast/extensions/blob/f5e38ef00fdd9ddb87b0fa89df80ebaf9dc12afc/extensions/homeassistant/src/common.ts#L18

2022-02-09 05:17 UTC, chen-ye commented
^ I opened a PR to fix

2022-02-09 05:54 UTC, tonka3000 commented
@chen-ye Thanks for the PR