Add sncftraintimes extension
raycast/extensions pull request #6823
Opened 2023-05-28 06:58 UTC by Pierrad

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-06-02 05:09 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Is there a way to check for wrong credentials?

- Missing icon

<img width="1000" alt="sncftraintimes 2023-06-02 at 07 06 59" src="https://github.com/raycast/extensions/assets/38033107/a05e032a-9515-435b-ae5b-90e3ec7dac53">

- No validation here, you could use useForm or validation for this

<img width="1000" alt="sncftraintimes 2023-06-02 at 07 07 27" src="https://github.com/raycast/extensions/assets/38033107/385852be-ef55-4d52-9eb7-8a9d8986e290">

- Because of the missing validation I was able to add blank items to the list (also could be nice with some icons here too)

<img width="1000" alt="sncftraintimes 2023-06-02 at 07 08 02" src="https://github.com/raycast/extensions/assets/38033107/299c91bc-387f-401b-a5f2-86e9cd227579">

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-06-05 12:51 UTC, Pierrad commented
Hi,

I worked on your feedback and committed my changes to my repo (https://github.com/Pierrad/SncfTrainTimes).
But when I run `npm run publish` to sync my changes with this PR it throws the following error : 

```
❯ npm run publish

> publish
> npx @raycast/api@latest publish

ready -  validate git repository
error -  getting fork
fork extensions repo: Error Body: {"message":"There was a problem updating the branch","documentation_url":"https://docs.github.com/rest/branches/branches#sync-a-fork-branch-with-the-upstream-repository"}
```

Do you know how can I fix this error ? 

Thanks

2023-06-05 14:02 UTC, Pierrad commented
From this page : https://github.com/Pierrad/raycast-extensions/tree/ext/sncftraintimes I have been able to manually sync as you proposed. 

Thanks :)

2023-06-06 07:26 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-06-06 07:39 UTC, merged