Update raycast-system-monitor extension
raycast/extensions pull request #6871
Opened 2023-05-31 07:23 UTC by pernielsentikaer

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-05-31 08:32 UTC, madza91 requested changes

2023-05-31 08:32 UTC, madza91 commented on extensions/system-monitor/CHANGELOG.md
> +- Addded Open Activity Monitor action
Typo in "Addded" 🥲

2023-05-31 10:57 UTC, pernielsentikaer commented on extensions/system-monitor/CHANGELOG.md
> +- Addded Open Activity Monitor action
Good spotted 🔥

2023-05-31 15:45 UTC, lucasmezencio approved these changes
LGTM.

2023-05-31 23:08 UTC, madza91 approved these changes

2023-06-01 05:07 UTC, pernielsentikaer commented
Can you approve @hossammourad 🙂

2023-06-01 13:43 UTC, hossammourad approved these changes

2023-06-01 16:34 UTC, merged