Add px-to-tailwind extension
raycast/extensions pull request #6911
Opened 2023-06-02 10:30 UTC by kemiljk

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-06-06 07:58 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- What about copying `--tw-6` to the clipboard rather than just 6 (Maybe for them both)
 
<img width="1000" alt="px-to-tailwind 2023-06-06 at 09 50 45" src="https://github.com/raycast/extensions/assets/38033107/6ef37cbc-fe94-4d46-bbb1-cdf6df4bfc08">

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-06-06 07:58 UTC, pernielsentikaer commented on extensions/px-to-tailwind/package.json
> +  "title": "Px to Tailwind",
```suggestion
  "title": "Tailwind Size Conversion",
```
Could this be a better naming?

2023-06-06 07:58 UTC, pernielsentikaer commented on extensions/px-to-tailwind/package.json
> +  "description": "Converts pixels to Tailwind class values",
```suggestion
  "description": "Converts pixels to Tailwind class values and vice versa",
```

2023-06-06 07:58 UTC, pernielsentikaer commented
Also a [metadata image](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) would be nice

2023-06-15 08:24 UTC, kemiljk commented
Thanks @pernielsentikaer! I’ve made all of the tweaks except the tailwind class copying. Because a Tailwind class prefix can be one of many things, and never actually `—tw-` I thought it was best to just copy the arbitrary value. Showing `—tw-` in the UI is more a way to show that it would be prefixed with a Tailwind class and mirrors how they appear when you view the inspector on a web project.

2023-06-22 19:43 UTC, kemiljk reviewed
Changes should be all addressed!

2023-06-23 14:34 UTC, pernielsentikaer approved these changes

2023-06-23 14:44 UTC, merged