Add performance-hud extension
raycast/extensions pull request #6919
Opened 2023-06-03 00:11 UTC by say4n

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-06-06 08:23 UTC, pernielsentikaer requested changes
Seems to be toggle as expected, but how can I see that it's working - would be nice with some more information about this in the README

2023-06-07 03:37 UTC, say4n commented
The only way to see it in action would be to launch an app that uses Metal API to render things onto the screen (most likely a game). An overlay shows up on the top right of the screen as follows:

<img width="2078" alt="image" src="https://github.com/raycast/extensions/assets/8839504/88bb31bc-34e6-4562-97e5-671b64eb1e45">

Updating the readme to make this obvious is a sensible suggestion, will make the changes -- appreciate the review, cheers!

2023-06-07 06:31 UTC, pernielsentikaer requested changes
When the README is corrected we can merge it 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-06-08 07:01 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-06-08 07:10 UTC, merged