Add putio extension
raycast/extensions pull request #6936
Opened 2023-06-04 13:29 UTC by altaywtf

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-06-04 13:37 UTC, altaywtf commented on extensions/putio/package.json
> +  "title": "put.io",
this is our branding

2023-06-06 08:55 UTC, pernielsentikaer commented
Since you're working for put.io @altaywtf, it might be better to go with this instead of #5979 - what do you think @EpaL 🙂

2023-06-12 02:45 UTC, EpaL commented
Sure, @PernielsenTikaer. The work by @AltayWTF looks great! I appreciate that it includes several features I hadn't incorporated into mine. However, I believe it would greatly benefit from having configurable commands to process files. This is particularly crucial for me, given my custom workflow for downloading files from put.io. I imagine other users might find this useful as well. If you're open to it, I could contribute this through a pull request.

2023-06-12 13:10 UTC, pernielsentikaer commented
That sounds like a really good idea @altaywtf 🔥 

Is this ready for the hopefully last review?

2023-06-12 14:12 UTC, altaywtf commented
yes sir @pernielsentikaer! 😊

2023-06-12 20:15 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Take a look at what I added, you can maybe do this for the other commands too.

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-06-15 16:27 UTC, altaywtf commented
@pernielsentikaer I guess we're ready for anothoer review.

2023-06-20 09:51 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-06-20 10:08 UTC, merged