Update kill-process extension
raycast/extensions pull request #6942
Opened 2023-06-05 07:49 UTC by zhenpewu

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-06-05 07:50 UTC, zhenpewu commented
#6941

2023-06-08 12:45 UTC, pernielsentikaer requested changes
Thanks for your contribution @zhenpewu 🔥

I gave it a quick spin and it works as expected

Two things:

- Maybe make this optional with a checkbox in preferences?
- Could you add a changelog entry

@rolandleth do you mind checking this too?

2023-06-08 14:12 UTC, zhenpewu commented on extensions/kill-process/src/index.tsx
> +  const refreshDuration = +preferences.refreshDuration;
sure, make sense to me.

2023-06-08 14:12 UTC, zhenpewu commented
> Maybe make this optional with a checkbox in preferences?

Can I use -1 as disable ?

2023-06-12 15:02 UTC, rolandleth requested changes

2023-06-12 16:02 UTC, zhenpewu commented on extensions/kill-process/package.json
> +      "description": "Refresh duration in milliseconds. The minimum value is 1000ms and to disable auto-refresh, set it to -1.",
okay.

2023-06-12 16:53 UTC, zhenpewu commented on extensions/kill-process/src/index.tsx
> +  refreshEnabled ? useInterval(fetchProcesses, refreshDuration) : useEffect(fetchProcesses, []);
agree, updated useInterval.

2023-06-13 11:28 UTC, pernielsentikaer commented on extensions/kill-process/src/index.tsx
> +  const refreshEnabled = +preferences.refreshDuration >= 0;
The ﻿+ in front of a string is a unary operator that can be used to convert a string to a number. For example, ﻿+'42' would evaluate to the number ﻿42. If the string cannot be converted to a number, the result will be ﻿NaN (Not a Number).

2023-06-13 11:35 UTC, pernielsentikaer commented
Still works as expected for me , could you verify @rolandleth

2023-06-13 12:32 UTC, rolandleth commented
Code-wise looks good, so if it also works good, we're good to go. Good, right? 😅

2023-06-13 12:44 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-06-13 12:49 UTC, merged