Add todo extension
raycast/extensions pull request #6977
Opened 2023-06-07 16:42 UTC by ThomasPinna

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-06-12 09:23 UTC, pernielsentikaer requested changes
- I would call it Todo instead of To-do 🙂

- Here it should show e.g. `Mark Quick`

<img width="210" alt="Raycast-2LHFMenh@2x" src="https://github.com/raycast/extensions/assets/38033107/0c7f0724-b14b-4d60-b6b8-bbf6a5cb42cb">

- The colors in accessory icons are hard to see on dark background

<img width="1000" alt="todo 2023-06-12 at 11 22 15" src="https://github.com/raycast/extensions/assets/38033107/575dde79-6aa4-4dee-802d-73fdd889def5">

2023-06-12 09:23 UTC, pernielsentikaer commented on extensions/todo/src/todo.ts
> +  if (todo.important) score += 2;
``` suggestion
  else if (todo.important) score += 2;
```

2023-06-12 09:23 UTC, pernielsentikaer commented on extensions/todo/src/todo.ts
> +  if (todo.urgent) score += 3;
```suggestion
  else if (todo.urgent) score += 3;
```

2023-06-12 09:23 UTC, pernielsentikaer commented on extensions/todo/.prettierrc
> +}
{
  "printWidth": 120,
  "singleQuote": false
}

2023-06-12 09:23 UTC, pernielsentikaer commented on extensions/todo/src/backup-actions.component.tsx
> +      title='Show Backups in finder'
```suggestion
      title='Show Backups in Finder'
```

2023-06-15 08:07 UTC, ThomasPinna commented
I had a discussion with my wife about Todo vs to-do, she argued that to-do is actually the more correct choice. A quick google resulted in this thread: [word choice - "Todo list" or "to-do list" - English Language & Usage Stack Exchange](https://english.stackexchange.com/questions/46217/todo-list-or-to-do-list#:~:text=You%20can%20use%20whichever%20you,off%20sticking%20to%20to%2Ddo.)


About the colours, do you have any suggestions? Or are you talking about the grey colours, because these are hard to see by design, since they are "inactive".

2023-07-04 14:13 UTC, thomaslombart requested changes
Congrats on the extension! I have some feedback:

- Could you find a differentiating name for your extension. `todo` sounds too generic and we already have a simple to-do list extension in the store?
- Could you add a screencast of your extension?
- Could you [adjust your icon](https://developers.raycast.com/basics/prepare-an-extension-for-store#extension-icon) so that there's no extra whitespace on the borders?
- Could you title-case your actions' titles as well as adding colors to the different icons?
- Could you use symbols? (`⌘` instead of `cmd`)

2023-07-04 14:13 UTC, thomaslombart commented on extensions/todo/.eslintrc.json
> +}
You can use `npx ray migrate` to make use of our latest ESLint config.

2023-07-04 14:13 UTC, thomaslombart commented on extensions/todo/src/index.tsx
> +  const [loading, setLoading] = useState<boolean>(true);
Note that you can use `useCachedPromise` from `@raycast/utils` for something like that.

2023-07-25 14:18 UTC, closed without merging