Add a new extension to search confluence wiki
raycast/extensions pull request #699
Opened 2022-01-17 19:42 UTC by daviddkkim

## Description

This is a new extension that allows users to search Confluence Wiki.
They would authenticate by specifying their domain, username and api token. Afterwards, they can search pages as if they are on the browser. 

You can either navigate to the page or copy URL to clipboard.

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/12561526/149828901-04b39c07-53b2-499e-88a7-cff25fdf8f5f.mp4

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2022-01-19 05:50 UTC, pernielsentikaer requested changes
Hi @daviddkkim 👋 

Thanks for your contribution 💯 

I don't have credentials to test it fully, do you by any chance have some credentials I could borrow a few minutes?

One thing I noticed is that when wrong credentials are present, it doesn't die gracefully (showing a toast and stopping the loader with an empty array) – Can you look into this?

![v6zs1oQBhRdViP1J](https://user-images.githubusercontent.com/38033107/150071849-74a6079c-4cbc-4e27-88b2-640a261d72a5.png)

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-19 05:50 UTC, pernielsentikaer commented on extensions/confluence-search/package.json
> +      "title": "Search Confluence Wiki",
```suggestion
      "title": "Search Wiki",
      "subtitle": "Confluence",
```

2022-01-23 19:58 UTC, daviddkkim commented
Screen capture including the authentication

https://user-images.githubusercontent.com/12561526/150695809-0132ed52-5380-4910-81c3-1631c51a46bc.mp4

2022-01-23 22:50 UTC, daviddkkim commented
@pernielsentikaer 

Made changes based on our slack convo:
- removed unecessary await 
- added in proper loading state based on whether the API call has returned rather than list item length
- changed pref field name from domain url to domain.


The empty list is there to show empty list in case API call response status was not OK. (fail state).

2022-01-24 22:02 UTC, pernielsentikaer commented
I sent you some more feedback in our conversation in Slack, let me know if you need anything 😄

2022-01-29 01:58 UTC, daviddkkim commented
@pernielsentikaer changed made !

2022-01-29 06:49 UTC, pernielsentikaer requested changes
Hi @daviddkkim 👋 

Awesome, thanks for the corrections 💯  Only two small NITs back and we're ready to proceed 💪

2022-01-29 06:49 UTC, pernielsentikaer commented on extensions/confluence-search/src/index.tsx
> +
```suggestion
```
Unused enum status

2022-01-29 06:49 UTC, pernielsentikaer commented on extensions/confluence-search/src/index.tsx
> +        </ActionPanel>
```suggestion
        <ActionPanel>
          <ActionPanel.Section>
            <OpenInBrowserAction title="Open in Browser" url={confluenceUrl + "/wiki" + searchResult.url} />
            <CopyToClipboardAction
              title="Copy URL"
              content={confluenceUrl + "/wiki" + searchResult.url}
              shortcut={{ modifiers: ["cmd"], key: "." }}
            />
          </ActionPanel.Section>
        </ActionPanel>
```
You could put it in the same section

2022-01-29 19:04 UTC, daviddkkim commented
> Hi @daviddkkim 👋
> 
> Awesome, thanks for the corrections 💯 Only two small NITs back and we're ready to proceed 💪

Thanks Per!

2022-01-29 19:48 UTC, pernielsentikaer approved these changes
Awesome @daviddkkim 💪 

Thanks for your contribution 💯 I'm going to accept it and then will my colleague do a final review before it's finally merged.

2022-01-31 12:58 UTC, merged

2022-01-31 12:58 UTC, sxn commented
🎉