Add Ulysses Extension
raycast/extensions pull request #702
Opened 2022-01-18 11:13 UTC by praveenjuge

## Description

This is an extension for [Ulysses](http://ulysses.app) app. Currently it has one command to open a new new empty sheet in Ulysses.

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/13696888/149926435-f81d8cf9-b094-421e-bf74-9d48bb138932.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2022-01-18 12:44 UTC, pernielsentikaer requested changes
Hi @praveenjuge 👋 

Only a single correction before its ready 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-18 12:44 UTC, pernielsentikaer commented on extensions/ulysses/package.json
> +      "title": "New Empty Sheet",
```suggestion
      "title": "New Empty Sheet",
      "subtitle": "Ulysses",
```

2022-01-19 21:11 UTC, pernielsentikaer approved these changes
Hi @praveenjuge 👋 

Thanks for your contribution 💯 I'm going to accept it and then will my colleague do a final review before it's finally merged.

2022-01-20 10:57 UTC, mattisssa requested changes
Hey! Thanks for the contribution.

For some reason, I got the error, but as you can see I have the app installed and even opened:

![CleanShot 2022-01-20 at 13 53 59@2x](https://user-images.githubusercontent.com/15333662/150325390-ce31ad20-da3d-46e1-86da-de8e7794279d.png)

And I also don't think the error has a nice text description showing the details. Probably something like "Install it from: https:..." would be better. 

I'm not sure if something wrong with my set up, didn't do anything special. Let me know how can I help

2022-01-20 11:00 UTC, praveenjuge commented
@mattisssa I'll take a look on what might have on wrong and update the error message 👍

2022-01-20 11:12 UTC, pernielsentikaer commented
Strange, I had no issues at all, it opened the app just fine without any problems at all here

2022-01-20 13:44 UTC, mattisssa commented
@pernielsentikaer @praveenjuge 
>➜  ~ mdls -name kMDItemCFBundleIdentifier -r /System/Volumes/Data/Applications/Setapp/Ulysses.app                                              
com.soulmen.ulysses-setapp% 

A good point I have is that I installed it from [Setapp](https://setapp.com), and the Ulysses is located in the folder inside Setapp one.

2022-01-20 14:05 UTC, pernielsentikaer commented
Makes sense, now it should be easier for @praveenjuge to adjust 😄

2022-01-20 14:13 UTC, praveenjuge commented
Yes, I will adjust it to see look from both app store and set app version 👍

2022-01-20 14:16 UTC, pernielsentikaer commented
Sounds like the right plan, awesome! That and the suggestions for the toast, and we're about being there!

2022-01-21 07:20 UTC, pernielsentikaer approved these changes
Hi @praveenjuge 

Much better, should be good to go now 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-21 08:26 UTC, mattisssa approved these changes
Now it works, thanks for adding Setapp's bundle 👏 
@pernielsentikaer Thanks for pinging 🚀

2022-01-21 08:27 UTC, merged