Add Timeular extension
raycast/extensions pull request #705
Opened 2022-01-18 16:44 UTC by kudrykv

## Description

The extension lets you control your time tracking in [Timeular](https://timeular.com/).

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/12697803/149980015-38d5340a-2bed-43cf-b642-17b4894c00a3.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2022-01-20 07:30 UTC, pernielsentikaer requested changes
Hi @kudrykv 👋 

Thanks for the contribution 💯 

There is a few conflicts:

 - When stopping a timer gives an error toast saying either "Bad Request" or "Conflict" and after stopping it's not possible to start a new

![t0jkubgBbqoEYUPJ](https://user-images.githubusercontent.com/38033107/150292720-0f6d1bec-8958-447d-aa8a-5f40b9650032.png)

 - When starting a timer, it's still possible to open "Start Timer" (which now is empty)

 - Icons is missing
 
![k0xfO1XcTgoCtBWQ](https://user-images.githubusercontent.com/38033107/150292663-f790d2c7-d6a7-4eea-95cf-322a6eb7f364.png)

Can you start by looking into above? Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-20 08:44 UTC, kudrykv commented
Hi @pernielsentikaer!

Thank you for the review!
I will address these.

2022-01-20 20:43 UTC, pernielsentikaer requested changes
Hi @kudrykv 👋 

That's much better, now I can't reproduce the errors from earlier! Only a few suggestions left, can you address them?


Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-20 20:43 UTC, pernielsentikaer commented on extensions/timeular/src/command-status.tsx
> +        title={"Edit note"}
```suggestion
        title={"Edit Note"}
```

2022-01-20 20:43 UTC, pernielsentikaer commented on extensions/timeular/src/command-status.tsx
> +      <ActionPanel.Submenu icon={"▶️"} title="Start Tracking..." shortcut={{ key: "n", modifiers: ["cmd"] }}>
```suggestion
      <ActionPanel.Submenu icon={"▶️"} title="Start Tracking" shortcut={{ key: "n", modifiers: ["cmd"] }}>
```

2022-01-21 21:54 UTC, pernielsentikaer approved these changes
Hi @kudrykv 👋 

Thanks for your contribution! Every work as expected 💪 I'm going to accept it and then will my colleague do a final review before it's finally merged.

2022-01-23 20:33 UTC, merged