An extension to quickly create latex for your documents
raycast/extensions pull request #7084
Opened 2023-06-13 21:56 UTC by Noamko

## Description

This extension enables users to input any LaTeX text, which will be parsed into a LaTeX image and copied to the clipboard.

## Screencast

 [New Recording - 6/14/2023, 12:52:54 AM](https://vimeo.com/835964536/cba96d909d)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder
 [New Recording - 6/14/2023, 12:52:54 AM](https://vimeo.com/835964536/cba96d909d)

2023-06-15 12:30 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- `state.items` seems to be always empty, or? 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-06-15 12:30 UTC, pernielsentikaer commented on extensions/quick-latex/src/quick-latex.tsx
> +const latexUrlDark = "https://latex.codecogs.com/png.image?" + encodeURIComponent("\\dpi{512}\\bg{white}");
```suggestion
const latexUrlDark = "https://latex.codecogs.com/png.image?" + encodeURIComponent("\\dpi{512}\\bg{black}\\fg{white}");
```
Maybe change it a bit like this

2023-06-15 19:32 UTC, Noamko commented
It appears that ﻿state.items is always empty, if my memory serves me correctly. I used a ﻿List initially as it seemed to be the most suitable container for the image. I'm not certain if there is a better solution now. any suggestions?

2023-06-19 10:59 UTC, pernielsentikaer commented
I can't find a better solution that using a [List.EmptyView](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview) for this, it seems like the right now that only an image will be shown

2023-06-19 19:03 UTC, pernielsentikaer approved these changes

2023-06-19 19:21 UTC, merged