Update youtube extension
raycast/extensions pull request #7144
Opened 2023-06-16 18:35 UTC by madza91

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-06-19 19:25 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Do you mind adding a changelog entry too

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-06-19 19:25 UTC, pernielsentikaer commented on extensions/youtube/src/components/video.tsx
> -      title="Show Details"
This looks like some debug data?

2023-06-19 22:32 UTC, madza91 commented
> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I have now tested your extension, and I have some feedback ready for you:
> 
> * Do you mind adding a changelog entry too
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

Added! 👍 
Thanks for your reply!

2023-06-20 05:23 UTC, pernielsentikaer commented
Can you approve this @tonka3000 🙂

2023-06-20 05:24 UTC, tonka3000 approved these changes
Sure @pernielsentikaer 😀

2023-06-20 05:33 UTC, merged