[NEW EXTENSION] Search Google Books
raycast/extensions pull request #715
Opened 2022-01-20 14:19 UTC by Ali-Parandeh

## Description

Search Google Books

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/43654026/150356085-aa767041-87ae-4ff6-a5eb-4001c154fb95.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

2022-01-20 20:55 UTC, pernielsentikaer requested changes
Hi @Ali-Parandeh 👋 

Awesome extension 💪 I left some feedback for you to address 🚀 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-20 20:55 UTC, pernielsentikaer commented on extensions/google-books/README.md
> +Plugin for Raycast to search [Google Books](https://books.google.co.uk/).
```suggestion
Extension for Raycast to search [Google Books](https://books.google.co.uk/).
```

2022-01-20 20:55 UTC, pernielsentikaer commented on extensions/google-books/README.md
> +Make sure RayCast is installed and go to https://github.com/Ali-Parandeh/raycast-google-books-extension
```suggestion
Make sure Raycast is installed and go to https://github.com/Ali-Parandeh/raycast-google-books-extension
```

2022-01-20 20:55 UTC, pernielsentikaer commented on extensions/google-books/src/index.tsx
> +                        title="Show Book Details"
```suggestion
                        title="Show Book Details"
                        icon={Icon.List}
```
Missing icon

2022-01-20 20:55 UTC, pernielsentikaer commented on extensions/google-books/package.json
> +      "title": "Search Google Books",
```suggestion
      "title": "Search Books",
      "subtitle": "Google Books",
```

2022-01-20 22:56 UTC, Ali-Parandeh commented
@pernielsentikaer Thanks for the improvements! 💪 All committed :)

2022-01-21 06:51 UTC, pernielsentikaer requested changes
Hi @Ali-Parandeh 👋 

Found three more, didn't see the copy action was for the link 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-21 06:51 UTC, pernielsentikaer commented on extensions/google-books/src/index.tsx
> +                                <CopyToClipboardAction icon={Icon.Clipboard} content={item.volumeInfo.infoLink} />
```suggestion
                                <CopyToClipboardAction title="Copy URL to Clipboard" icon={Icon.Clipboard} content={item.volumeInfo.infoLink} />
```

2022-01-21 06:51 UTC, pernielsentikaer commented on extensions/google-books/src/index.tsx
> +                      <CopyToClipboardAction icon={Icon.Clipboard} content={item.volumeInfo.infoLink} />
```suggestion
                      <CopyToClipboardAction icon={Icon.Clipboard} title="Copy URL to Clipboard" content={item.volumeInfo.infoLink} />
```

2022-01-21 06:51 UTC, pernielsentikaer commented on extensions/google-books/src/index.tsx
> +                            markdown={`${item?.volumeInfo?.subtitle ?? "" + "\n\n"} ${
```suggestion
                            markdown={`## ${item.volumeInfo.title} ${item?.volumeInfo?.subtitle ?? "" + "\n\n"} ${
```
Just a suggestion to add the title as header

2022-01-21 12:56 UTC, Ali-Parandeh commented
@pernielsentikaer  New feature!

Added Thumbnails to book lists, and properly formatted book details page

![Screenshot 2022-01-21 at 12 55 41](https://user-images.githubusercontent.com/43654026/150530612-89d9787b-fbf5-4d40-a509-2ba00c231b6e.png)

![Screenshot 2022-01-21 at 12 55 56](https://user-images.githubusercontent.com/43654026/150530624-151ee0c7-611f-446b-9707-b102a3770eea.png)

![Screenshot 2022-01-21 at 12 56 01](https://user-images.githubusercontent.com/43654026/150530637-c02c4efe-73bc-434b-89cb-8120847007c7.png)

2022-01-21 21:58 UTC, pernielsentikaer commented
Much better @Ali-Parandeh – Very awesome! 

You forgot to add `icon={Icon.List}` (or another icon to `Show Book Details` action item, can you add that? After that, we're ready 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-22 00:35 UTC, Ali-Parandeh commented
All Done @pernielsentikaer :)

2022-01-22 06:22 UTC, pernielsentikaer approved these changes
Awesome @Ali-Parandeh 🚀 

Thanks for an awesome contribution 💪 

I'm going to accept it and then will my colleague do a final review before it's finally merged.

2022-01-24 17:28 UTC, mathieudutour approved these changes

2022-01-24 17:28 UTC, merged