Add GraphCDN extension
raycast/extensions pull request #720
Opened 2022-01-21 13:09 UTC by mathieudutour

## Description

List your [GraphCDN](https://graphcdn.io) services and inspect their configuration

## Type of change

- New extension

## Screencast

![](https://raw.githubusercontent.com/raycast/extensions/dcd0fcab8fee6b09dc19f9dd7bac83700c100abf/extensions/graphcdn/Screenshot.png)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-01-22 07:14 UTC, pernielsentikaer requested changes
Hi @mathieudutour 🚀 

Awesome extensions, I left a few minor suggestions for you to check 💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-22 07:14 UTC, pernielsentikaer commented on extensions/graphcdn/package.json
> +      "title": "Search GraphCDN Services",
```suggestion
      "title": "Search Services",
      "subtitle": "GraphCDN",
```

2022-01-22 07:14 UTC, pernielsentikaer commented on extensions/graphcdn/package.json
> +      "type": "textfield",
Could be a password field

2022-01-22 07:14 UTC, pernielsentikaer commented on extensions/graphcdn/src/search.tsx
> +          actions={<ActionPanel></ActionPanel>}
```suggestion
          actions={<ActionPanel/>}
```
Could be collapsed or removed

2022-01-24 10:45 UTC, pernielsentikaer requested changes
Hi @mathieudutour 🚀 

Much better 💪 !

Just a single question left:
Is it supposed to be able to create an organization, I can see some functions that's intended to do this, but not in use – Just wanted to be sure that nothing is missing 😄

2022-01-24 10:47 UTC, mathieudutour commented
Not yet no, Just added the functions to do so if I (or someone else) want to add this functionality

2022-01-24 11:04 UTC, pernielsentikaer approved these changes
Awesome 💪  Good idea to keep it, just wanted to make sure we didn't lose anything 😄 

I can't find anything else that should be addressed!

2022-01-24 11:05 UTC, merged