Add ruler extension
raycast/extensions pull request #7255
Opened 2023-06-23 16:50 UTC by anwarulislam

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-06-27 14:34 UTC, mil3na commented
Hi! Thank you so much for your contribution to Raycast!
My name is Milena and I will be reviewing your extension today :)

I'm having a bit of trouble using your extension. Here's a video:

https://github.com/raycast/extensions/assets/611002/3b7676f8-8881-49d5-93ba-64c866efb208

Could you please check what happened?

2023-06-27 15:41 UTC, anwarulislam commented
Hi @mil3na,

I have patched a few lines of code. And pushed the latest codes. Could you please check with the latest changes?

If still the issue exists:
I would request you to run the swift file from the sources directory of the extension: 

`swift Sources/ruler/main.swift`

I would like to see if the error is device-specific or not.

2023-06-28 11:27 UTC, mil3na requested changes
Hi! Thanks for fixing it. It works fine here and I find it so cool! Thanks for building it!

I've made a few code comments, could you please address those? If all goes well, after that, we will be able to merge your extension :)

2023-06-28 11:27 UTC, mil3na commented on extensions/ruler/Sources/ruler/main.swift
> +    // guard let screen = screen else {
Unused code, please remove.

2023-06-28 11:27 UTC, mil3na commented on extensions/ruler/.vscode/settings.json
I think this can be added to your `.gitignore`

2023-06-28 11:27 UTC, mil3na commented on extensions/ruler/.vscode/launch.json
Does the extension functionality depend on this? Otherwise, I'd suggest adding this to your `.gitignore`

2023-06-28 11:27 UTC, mil3na commented on extensions/ruler/Sources/ruler/main.swift
> +      // print("First point selected. Now select the second point.")
Unused code, please delete.

2023-06-28 11:27 UTC, mil3na commented on extensions/ruler/src/ruler.ts
> +
please remove the `console.log`s

2023-06-28 11:27 UTC, mil3na commented on extensions/ruler/assets/ruler
where is this file used and why it doesn't have an extension?

2023-06-28 15:06 UTC, anwarulislam commented
Hi, @mil3na!
I have updated all changes accordingly. Now you can re-review it 🚀

2023-06-29 11:12 UTC, mil3na commented
Hey @anwarulislam, as we talked on Slack, I believe the swift-generated file is needed. Do you mind adding it back? Also the contrast adjustment, do you think you can include it here? Other than that, I think your extension is good to go.

2023-06-29 13:23 UTC, anwarulislam commented
@mil3na I have added the binary file. I'll add a contrast feature in the next update along with many others. So, I think now it's good to go from my side

2023-06-29 15:02 UTC, mil3na approved these changes
Awesome. Looks good to me :)

2023-06-29 15:06 UTC, merged