time traveling world clock extension
raycast/extensions pull request #7357
Opened 2023-07-02 09:46 UTC by himarky

## Description

tl;dr it's a different take on a world clock that allows the user to use cmd+arrow keys to "scrub" backwards and forwards through time to coordinate meetings.

## Screencast

https://github.com/raycast/extensions/assets/1624703/e1bb46fc-f13f-47bb-b7a0-277a172bbf01

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-07-02 10:16 UTC, Ek2100 commented
Raycast does already do this built in however it is a bit finikey with what you have to type
<img width="793" alt="image" src="https://github.com/raycast/extensions/assets/113011003/792801c0-81c4-489d-9da2-1fe4aa4205a9">

2023-07-03 09:22 UTC, himarky commented
I'm familiar and a big fan of the above functionality, however my extension aims to provide a view across multiple timezones.

<img width="801" alt="Screenshot 2023-07-03 at 4 21 58 PM" src="https://github.com/raycast/extensions/assets/1624703/a81b3bbe-2cf8-4bd0-8158-d4bf5fa83343">

2023-07-03 09:24 UTC, Ek2100 commented
That is true, this is actually really cool, now that i think about it. Have you considered adding a menu-bar command?

2023-07-03 09:27 UTC, himarky commented
Thanks @Ek2100 ☺️ that could be an equally cool option, I'm just personally not a menu bar fan.

2023-07-04 09:44 UTC, thomaslombart requested changes
Congrats on the extension! I have some feedback on it.

## Action Icons

The actions could use icons to make them more scannable. For example, `+1hr` could have the `Icon.Plus` icon and be named `Add 1 hour`

<img width="794" alt="CleanShot 2023-07-04 at 11 35 52@2x" src="https://github.com/raycast/extensions/assets/16003285/e5085833-4009-455a-a2d9-5649efde031d">

## Search Placeholder

The search placeholder is meant to search among list results or filter them. It's a bit unintuitive to put instructions about actions in the search bar placeholder.

Maybe you could have some kind of onboarding by displaying a `List.Item` on top of the list view that can be dismissed. Something like that:

```tsx
<List.Item
  title="You can adjust hour with ⌘ + ← and ⌘ + →"
  icon={Icon.Info}
  actions={
    <ActionPanel>
      <Action icon={Icon.XMarkCircle} title="Dismiss Message" onAction={...} />
    </ActionPanel>
  }
/>
```

2023-07-04 09:44 UTC, thomaslombart commented on extensions/time-traveling-world-clock/src/index.tsx
> +  if (h >= 17 && h < 20) {
Maybe it's up for debate but I'd argue that `17` is still the day 😬 

Isn't there a way to know the sunrise/sunset hours for each city to return more accurate icons?

2023-07-06 13:12 UTC, himarky commented
@thomaslombart thanks for the UX guidance. :)

I got rid of the placeholder, added some icons, and cleaned up the action names.  PTAL!

2023-07-06 13:23 UTC, thomaslombart reviewed
That's better. One last thing though: Could you add an empty list view with actions so that the user is able to add a city if they try to filter the current list?

<img width="794" alt="CleanShot 2023-07-06 at 15 17 21@2x" src="https://github.com/raycast/extensions/assets/16003285/2840866f-0591-4426-a734-5652827564c2">

Also, the placeholder could be a bit more detailed (e.g `Search cities` instead of just `Search`)

2023-07-07 08:38 UTC, himarky commented
@thomaslombart love it.  Boom, done, PTAL

2023-07-10 05:36 UTC, thomaslombart approved these changes

2023-07-10 05:36 UTC, merged