Add Solana Explorer extension
raycast/extensions pull request #736
Opened 2022-01-23 21:39 UTC by TrGiLong

## Description

Look up transactions and accounts on the various Solana clusters.

## Type of change

- New extension

## Screencast

![](https://github.com/TrGiLong/extensions/raw/f/solana-explorer/extensions/solana-explorer/docs/screenshots-1.png)
![](https://github.com/TrGiLong/extensions/raw/f/solana-explorer/extensions/solana-explorer/docs/screenshots-2.png)
![](https://github.com/TrGiLong/extensions/raw/f/solana-explorer/extensions/solana-explorer/docs/screenshots-3.png)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-01-29 18:40 UTC, pernielsentikaer requested changes
Hi @TrGiLong 👋 

Interesting extensions, even though I don't really know what I'm looking at 😄 

Besides the suggestions, I have some feedback:
- Move docs folder to assets and update README
- When emptying the search, it could show “No Results” again

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-29 18:40 UTC, pernielsentikaer commented on extensions/solana-explorer/package.json
> +      "subtitle": "Look up transactions and accounts on the Solana clusters.",
```suggestion
```
I think we should remove subtitle, It's usually this is the service or domain that your command is associated with.

2022-01-29 18:40 UTC, pernielsentikaer commented on extensions/solana-explorer/src/blockchain/model/search-result.ts
> +import { BlockchainConfig } from "../config";
```suggestion
```
Unused import

2022-01-29 18:40 UTC, pernielsentikaer commented on extensions/solana-explorer/src/blockchain/repository.ts
> +import { Account } from "./model/account";
```suggestion
import * as splTokensRegister from "@solana/spl-token-registry";
```
Unused imports

2022-01-29 18:40 UTC, pernielsentikaer commented on extensions/solana-explorer/src/blockchain/repository.ts
> +
Leftover or forgotten? Should be removed if old code

2022-01-29 18:40 UTC, pernielsentikaer commented on extensions/solana-explorer/src/solana-explorer.tsx
> +    <List isLoading={isLoading || !isReady} onSearchTextChange={queryOnChange}>
```suggestion
    <List isLoading={isLoading || !isReady} onSearchTextChange={queryOnChange} throttle={true}>
```
Add throttle

2022-02-08 20:27 UTC, TrGiLong commented
Hi @pernielsentikaer 

This extension should help other devs to quickly open transaction and see some useful information in Solana Blockchain. I will take. 

Thank for your review. I have changed all your requests :D

2022-02-09 21:15 UTC, pernielsentikaer requested changes
Hi @TrGiLong 👋 

Thanks for taking your time updating the extension, It's turning out quite nice 💯 

We just released 1.28.0 of the API today, which also add support for [fallback image](https://developers.raycast.com/api-reference/user-interface/icons-and-images#image) if the requested image fails – maybe it could be an idea to implement?

To keep the extension size down, we now try to remove screenshots, would it be okay to remove them from the extension?

Again, thanks for your time 💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-09 21:17 UTC, pernielsentikaer commented on extensions/solana-explorer/package.json
> +      "title": "Solana Explorer",
```suggestion
      "title": "Search Blockchain",
      "subtitle": "Solana Explorer",
```
This could also improve the UX, what do you think?

2022-02-10 22:18 UTC, pernielsentikaer approved these changes
Awesome @TrGiLong 🔥 

We're ready to proceed to the final stage, last review and merge 💪 

It has been a pleasure to work with you! 💯

2022-02-11 08:24 UTC, merged