add chakra ui docs extension
raycast/extensions pull request #737
Opened 2022-01-24 07:51 UTC by pgvr

## Description

This is a new extension that provides short links to the Chakra UI documentation. This saves me some time instead of opening the website first and then searching.

## Type of change

- New extension

## Screencast

![image](https://user-images.githubusercontent.com/17068372/150742370-50be6105-d825-4af6-a262-0643db61dbf9.png)

![image](https://user-images.githubusercontent.com/17068372/150742396-eb68bc6e-3926-4ea1-bb76-95460b4491a2.png)

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-01-29 20:29 UTC, pernielsentikaer requested changes
Hi @pgvr 👋 

Thanks for your contribution 💯 I left a few suggestions for you to address 💪 

I have some feedback:
- I think the need of UUID is overkill, you could use the title as key instead
- Remove the .svg icon, since it's not in use

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-29 20:29 UTC, pernielsentikaer commented on extensions/chakra-ui-docs/package.json
> +  "title": "Chakra UI Docs",
```suggestion
  "title": "Chakra UI Documentation",
```

2022-01-29 20:29 UTC, pernielsentikaer commented on extensions/chakra-ui-docs/package.json
> +      "title": "Browse Components",
```suggestion
      "title": "Browse Components",
      "subtitle": "Chakra UI",
```

2022-02-15 10:20 UTC, pgvr commented
Hi @pernielsentikaer, I'm sorry about the radio silence. Thank you for your feedback! Let me know whether there is anything else.

2022-02-15 21:51 UTC, pernielsentikaer approved these changes
Hi @pgvr 👋 

Awesome, thanks for the correction 💯 

We're ready to move to the next stage, awesome! Good job, mate 💪

2022-02-17 09:59 UTC, merged