add Emoji extension
raycast/extensions pull request #742
Opened 2022-01-25 12:46 UTC by FezVrasta

## Description

Allows to convert currencies using the "Banca d'Italia" exchange rates. This can be useful in case an Italian company needs to emit an invoice that will be paid in a currency different than euro, since it's often easier to emit the invoice in euro, converted from the non-euro currency, and if this happens, the "Banca d'Italia" exchange rates are the ones that must be used.

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/5382443/150979245-9e6b6f3a-8d02-406e-b8f4-307cdd252af6.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-01-25 12:49 UTC, FezVrasta commented on extensions/banca-d-italia-currency-converter/src/index.tsx
> +  "https://tassidicambio.bancaditalia.it/terzevalute-wf-web/rest/v1.0/dailyRates?currencyIsoCode=EUR&lang=en";
I'm using the same endpoint used by the official web-based conversion tool (https://tassidicambio.bancaditalia.it/terzevalute-wf-ui-web/converter). Unfortunately they use CSV as format... 🤷‍♂️

2022-02-02 20:33 UTC, pernielsentikaer requested changes
Hi @FezVrasta 👋 

Thanks for your contribution, I left some feedback for you to address 💪 

You could consider showing something else than “NaN” when you delete the value from Amount?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-02 20:33 UTC, pernielsentikaer commented on extensions/banca-d-italia-currency-converter/package.json
> +      "title": "Convert Currency",
```suggestion
      "title": "Convert Currency",
      "subtitle": "Banca d'Italia",
```

2022-02-02 20:33 UTC, pernielsentikaer commented on extensions/banca-d-italia-currency-converter/src/index.tsx
> +          <ActionPanel.Item
You're missing an icon for this action

2022-02-05 06:14 UTC, pernielsentikaer requested changes
Hi @FezVrasta 👋 

Now when opening the extension there is an error, also the dropdown is only showing EUR, can you look into this?

![vy8rKT5XW0WvT061](https://user-images.githubusercontent.com/38033107/152630985-c14b9178-0f03-46cf-a0c1-bdef09957c7a.png)

![le6Doyt9c5H0CvWn](https://user-images.githubusercontent.com/38033107/152630988-ffd52b11-e272-4a2f-bde6-50dda172671e.png)

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-05 07:13 UTC, FezVrasta commented
Notice the popup on the bottom? There aren't conversion rates for the specified date

2022-02-05 07:29 UTC, pernielsentikaer commented
lHi @FezVrasta 🔥 

Touché! I just thought that it was an error since the rates should be able for today, or is that normal? Expect me to be the end user using it 😄 

I'm not sure if it makes any sense, but you could hide the form field when the selected date is not able to find rates and use a `Form.Description` (added in ^1.27.1)

2022-02-05 08:15 UTC, FezVrasta commented
I want to avoid the jarring experience of having the field appear and disappear as the user changes dates

2022-02-05 08:56 UTC, pernielsentikaer approved these changes
Hi @FezVrasta 👋 

Thanks for your contribution, let's get to the last stage 🚢  🔥

2022-02-07 13:28 UTC, merged