Add real-debrid-manager extension
raycast/extensions pull request #7438
Opened 2023-07-08 23:44 UTC by YamenSharaf

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-07-14 12:12 UTC, mil3na requested changes
Hi! Thank you so much for your contribution to Raycast!
My name is Milena and I will be reviewing your extension today :)

Other than the things I pointed out on the code, I have a couple more comments:

![CleanShot 2023-07-14 at 14 02 56@2x](https://github.com/raycast/extensions/assets/611002/2e1849d2-242f-48cd-b01f-cd7da149b20c)

Error messages are not very friendly. I suggest that they should be mapped to real copy, instead of just spilling out what the API gives you.

Is there a way to have a RealDebrid URL without needing to subscribe? I'd like to test the download feature, but I've only got invalid URLs.

2023-07-15 00:09 UTC, YamenSharaf commented on extensions/real-debrid-manager/README.md
> +Some ideas for further improvements:
Removed! Probably no need for the announcement

2023-07-15 00:09 UTC, YamenSharaf commented on extensions/real-debrid-manager/package.json
> +      "description": "You can find your token at https://real-debrid.com/apitoken",
Removed

2023-07-15 00:17 UTC, YamenSharaf commented
> Hi! Thank you so much for your contribution to Raycast! My name is Milena and I will be reviewing your extension today :)
> 
> Other than the things I pointed out on the code, I have a couple more comments:
> 
> ![CleanShot 2023-07-14 at 14 02 56@2x](https://user-images.githubusercontent.com/611002/253566824-2e1849d2-242f-48cd-b01f-cd7da149b20c.png)
> 
> Error messages are not very friendly. I suggest that they should be mapped to real copy, instead of just spilling out what the API gives you.

I've worked on cleaning up error messages so they don't show duplicate `Error` for example. Unfortunately, I don't have access to all possible errors from real-debrid's side and would like to give an indication to what exactly went wrong.

> 
> Is there a way to have a RealDebrid URL without needing to subscribe? I'd like to test the download feature, but I've only got invalid URLs.

Unfortunately, all of RD's functionality is gated behind a paid subscription. I could take a screen recording with more functionality if needed.
Just to clarify, the Downloads section doesn't download files to the disk, but these download items are actually listed from a remote server. The idea is that a user can open one of these direct links in the browser to initiate a download or send them to a locally installed media player to stream them directly.



Finally. I'm so sorry about the bulk of new changes since the review. I've been working over the past couple of days on some quality-of-life improvements as well as some refactoring. I wasn't aware that a review process had started when I pushed the changes 🙏🏻

2023-07-17 12:59 UTC, mil3na commented
Hi!
In general, it looks good to me. Do you mind sharing a video of a common workflow for using this extension? Showing the QoL changes, if possible. As I don't have access to the service, that would be very helpful!

2023-07-17 18:47 UTC, YamenSharaf commented
Thanks @mil3na for the review. RD is a service that makes it easy to download files from torrents or from hoster links like `mega.nz`or even YouTube. It uploads the content to a remote server and from there the download process becomes painless.

## Examples
### [Torrent file OR magnet](https://share.cleanshot.com/2GSMdzhQ)
- A user selects a torrent file or submits a magnet link
- They see a screen to confirm which file(s) from within the torrent they want to store on the server.
- After confirmation, the torrent is added to the torrent list where it's downloaded remotely (sometimes it's already cached d at a RD server).
- The list of torrents can be viewed. When complete, the selected torrent can be added to the download list to be downloaded and/or streamed.

### [Hoster or YouTube Link](https://share.cleanshot.com/qSzw6FgY)
- A user adds a YouTube Link from clipboard or the main add link commmand
- The link is added to the Downloads directly. Where it can be selected and information about it can be viewed.
- User has the choice to
  - Open in browser (download)
  - OR Stream in a local video player
  - OR stream in a web player made by RD
  - OR copy a direct download link

### [User can delete link or torrent from the list](https://share.cleanshot.com/Fmqnx88p)

## The improvements that were recently added
- Move the information of the torrent/download item to the metadata section as conventional
- Add new icons to the right-hand side of the list to indicate torrent status for torrents and file type for downloads
![Screenshot 17 07 2023-8 42 52](https://github.com/raycast/extensions/assets/25423453/3eea09d0-992c-4da9-b3e3-dce2567f2a31)
![Screenshot 17 07 2023-8 42 26](https://github.com/raycast/extensions/assets/25423453/20efaf8a-bd7e-4f91-b8e5-aa7701ce4d19)

- Special handling for YouTUbe links where the thumbnail for the video is rendered 
![Screenshot 17 07 2023-8 44 27](https://github.com/raycast/extensions/assets/25423453/09b89844-c263-4f23-ae0c-5bc7a388183c)

- Special handling for TV shows and movies where some more information is fetched and rendered
![Screenshot 17 07 2023-8 47 00](https://github.com/raycast/extensions/assets/25423453/fe5cb449-71ef-4d75-930b-77ac4d7e93f6)

2023-07-18 09:15 UTC, mil3na approved these changes
Thanks for your effort and the detailed explanation about your extension! LGTM!

2023-07-18 09:16 UTC, merged