Add reqbin-zip extension
raycast/extensions pull request #7446
Opened 2023-07-09 18:18 UTC by rupert648

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-07-14 12:34 UTC, mil3na requested changes
Hi! Thank you so much for your contribution to Raycast!
My name is Milena and I will be reviewing your extension today :)

I'm trying to create a reqBin with some Loren Ipsum - as a regular dev does - and I'm getting both the error below and it failing silently:
![CleanShot 2023-07-14 at 14 30 41@2x](https://github.com/raycast/extensions/assets/611002/cee5b19c-8072-4026-bc5d-4ce44e3474cb)

![CleanShot 2023-07-14 at 14 30 12@2x](https://github.com/raycast/extensions/assets/611002/f5cd2a3e-f4c6-459c-8eb6-3aa86a79cff4)

It works on your website tho: https://www.reqbin.zip/clk2k6p060000mg08ccdh4mfw

However, entering this same URL on the `Copy Contents` command gives me the following error.
![CleanShot 2023-07-14 at 14 32 27@2x](https://github.com/raycast/extensions/assets/611002/4eb073de-59b4-45e8-9936-070077962a96)

Could you please take a look?

2023-07-14 12:34 UTC, mil3na commented on extensions/reqbin-zip/src/constants/url.ts
> +export const url = process.env.NODE_ENV === "development" ? "http://localhost:3000" : "https://reqbin.zip";
Other than you, would any user benefit from having localhost here? It seems a bit odd having it in prod.

2023-07-31 09:46 UTC, mil3na commented
Hi! Any updates on my comments? Anything I can help you with?

2023-07-31 10:18 UTC, rupert648 commented
> Hi! Any updates on my comments? Anything I can help you with?

Hi! I unfortunately haven't had any time recently to revisit this, but thank you for your review. I'll close the PR for now to avoid clutter and will return to it at some point if I find time.

2023-07-31 10:18 UTC, closed without merging