Add nsis-reference extension
raycast/extensions pull request #745
Opened 2022-01-26 16:16 UTC by idleberg

## Description

Adds actions to look up the NSIS documentation

## Type of change

- New extension

## Screencast

Uploading nsis-reference.mp4…

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-01-26 21:37 UTC, pernielsentikaer requested changes
Hi @idleberg 👋 

Looks like an awesome extension you're building 💪 I left some feedback for you to work with, also, it looks like you haven't formatted it with prettier, could you also look into this?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-26 21:37 UTC, pernielsentikaer commented on extensions/nsis-reference/package.json
> +  "description": "",
```suggestion
  "description": "Search NSIS references",
```

2022-01-26 21:37 UTC, pernielsentikaer commented on extensions/nsis-reference/package.json
> +      "title": "NSIS Reference",
```suggestion
      "title": "Search References",
      "subtitle": "NSIS",
```

2022-01-26 22:54 UTC, idleberg commented
Thanks @pernielsentikaer. I made the requested changes.

2022-01-27 21:09 UTC, pernielsentikaer approved these changes
Hi @idleberg 👋 

Thanks for your contribution, much appreciated 💪 I'm going to accept it and then my colleague will do a final review before it's finally merged.

2022-01-31 16:40 UTC, sxn commented
🎉

2022-01-31 16:40 UTC, merged