Add "Kaomoji Search" extension
raycast/extensions pull request #746
Opened 2022-01-27 00:30 UTC by allexks

## Description

This PR aims to add a new extension called Kaomoji Search. It allows to people to search for an ascii/unicode emote and copy it to the clipboard.

## Type of change

- New extension

## Screencast

![demo](https://user-images.githubusercontent.com/8430129/151269184-135436db-4f7a-4181-8a1c-50cf5c32e885.gif)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

# Note

I currently added the extension as a submodule as I had it initially hosted as a repo in my GitHub profile. If that is not desired, I have no problem just copying the project into the `extensions` directory instead.

2022-01-27 00:42 UTC, allexks commented
Alright, sorry for the failing pipeline, I will just copy it into the project. Just to ask though, is it on purpose that submodules are not supported?

2022-01-30 21:28 UTC, pernielsentikaer requested changes
Hi @allexks 👋 

Thanks for your contribution 💪 

Some feedback for you to address:
- If searching for, e.g., “Bear”, no matches found, only “bear” works.
- Move folder with preview to assets

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-31 12:36 UTC, pernielsentikaer requested changes
Hi @allexks 👋 

Much better 💪!

Now it's possible to search a bit better, however, when using space it all breaks. Shouldn't it be possible to search for, e.g., “Flower girl”?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-01-31 16:28 UTC, allexks commented
Thanks for the feedback! I reimplemented the searching algorithm now, results should be better.

2022-01-31 21:20 UTC, pernielsentikaer approved these changes
Hi @allexks 👋 

Thanks, MUCH better! Let's proceed to the last stage 🚀 I'm going to accept it now, my colleague will do a final review before merging 💎

2022-02-01 07:11 UTC, pernielsentikaer commented
Hi @allexks 👋 

Just found a minor thing. Can you provide a light/dark icon? Otherwise, this won't look good in different themes. You can find more info [here](https://developers.raycast.com/information/manifest).

2022-02-01 12:46 UTC, allexks commented
Thanks, I added a brighter version for the dark theme. I don't quite like the way this icon looks like when small, to be honest, but maybe in the future it can be improved, I just don't have the skills to come up with and create something better for now.

2022-02-01 17:33 UTC, sxn commented on extensions/kaomoji-search/src/index.tsx
> +  console.log("searching for", searchText);
```suggestion
```

2022-02-01 17:33 UTC, sxn commented on extensions/kaomoji-search/src/index.tsx
> +  console.log("results count", results.length);
```suggestion
```

2022-02-01 17:39 UTC, sxn commented
thanks for the work @allexks! 🎉 

Playing around with the extension, I kept wanting to be able to paste a kaomoji instead of copying to clipboard. Do you think it makes sense to add a [PasteAction](https://developers.raycast.com/api-reference/user-interface/actions#pasteaction) in addition to [CopyToClipboardAction](https://developers.raycast.com/api-reference/user-interface/actions#copytoclipboardaction)? 🤔

2022-02-01 17:45 UTC, pernielsentikaer commented
I could have sworn that I asked the same question earlier, but I guess I only dreamt it! I think Paste would be awesome 💪

2022-02-01 18:55 UTC, allexks commented
@sxn @pernielsentikaer Oh, absolutely, I thought the same while creating it but for some reason didn't think that it was a builtin action 😄  I made it the default now, thanks for the suggestion.

2022-02-02 10:16 UTC, merged