password-generator extension from @joshuaiz
raycast/extensions pull request #752
Opened 2022-01-28 00:28 UTC by joshuaiz

## Description

A simple password generator extension with options:
- number of characters (5–32)
- use numbers
- use special characters

When run, it generates the password and copies it to the clipboard.

## Type of change

- New extension

## Screencast

<img width="828" alt="CleanShot 2022-01-27 at 18 27 19@2x" src="https://user-images.githubusercontent.com/1096738/151465791-f6f4c120-7821-4660-adde-c8f029c53f5a.png">

<img width="794" alt="CleanShot 2022-01-27 at 18 27 33@2x" src="https://user-images.githubusercontent.com/1096738/151465801-e168eb19-7a94-4c35-9ff3-68f470e043dc.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

Thank you and thanks for the help on Slack!

2022-02-01 15:01 UTC, pernielsentikaer requested changes
Hi @joshuaiz 👋 

Thanks for your contribution 💪 

I have some feedback:

- Is there a reason 32 is the longest possible password?
- instead of showing a `<Detail/>` I would just show a toast, with style accordingly, like: `showToast(ToastStyle.Success, "Copied Password", generatedPassword);` which will make it faster to shuffle to a “new” one.
- You could add an action, so it's possible to Copy And Paste.
- With above, you could add a preference to set the default (Let me know if you need an example)
- Consider using a NPM package to allow more settings.

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-01 15:26 UTC, joshuaiz commented
Thanks for this.

- reason 32 is the longest: many sites max out at this number but can certainly go higher e.g. 64
- Can definitely show a Toast. Just FYI this was my first attempt and the docs never explain clearly what a “Toast” is so it was a bit confusing at first. A simple 2-3 sentence explaining what a Toast is with pictures and what the options are in the docs would be super helpful for newbies like me.
- Can add copy and paste actions
- Yes can you provide an example of setting the default action?
- Not sure what you mean by using an NPM package to allow more settings - can you explain? 

Best,

Joshua



> On Feb 1, 2022, at 09:01, Per Nielsen Tikær ***@***.***> wrote:
> 
> 
> @pernielsentikaer requested changes on this pull request.
> 
> Hi @joshuaiz <https://github.com/joshuaiz> 👋
> 
> Thanks for your contribution 💪
> 
> I have some feedback:
> 
> Is there a reason 32 is the longest possible password?
> instead of showing a <Detail/> I would just show a toast, with style accordingly, like: showToast(ToastStyle.Success, "Copied Password", generatedPassword); which will make it faster to shuffle to a “new” one.
> You could add an action, so it's possible to Copy And Paste.
> With above, you could add a preference to set the default (Let me know if you need an example)
> Consider using a NPM package to allow more settings.
> Request a new review when you are ready, feel free to contact me here or at Slack <https://raycastcommunity.slack.com/> if you have any questions.
> 
> In extensions/password-generator/package.json <https://github.com/raycast/extensions/pull/752#discussion_r796684192>:
> 
> > @@ -0,0 +1,37 @@
> +{
> +  "$schema": "https://www.raycast.com/schemas/extension.json",
> +  "name": "password-generator",
> +  "title": "Password Generator",
> +  "description": "Generates a password from 5–32 characters with options for case, special characters, and more",
> +  "icon": "password-generator-icon.png",
> +  "author": "joshuaiz",
> +  "license": "MIT",
> +  "commands": [
> +    {
> +      "name": "generate-password",
> +      "title": "Generate Password",
> +      "subtitle": "Quickly generate a password with options",
> ⬇️ Suggested change
> -      "subtitle": "Quickly generate a password with options",
> In extensions/password-generator/src/generate-password.tsx <https://github.com/raycast/extensions/pull/752#discussion_r796685233>:
> 
> > +        errorMessage = "Password length must be greater than 4";
> +      } else if (lengthNumber > 32) {
> +        errorMessage = "Password length must be less than 33";
> +      } else if (!Number.isFinite(lengthNumber)) {
> +        errorMessage = "Password length must be a number";
> +      }
> +    }
> +  };
> +
> +  return (
> +    <Fragment>
> +      <Form
> +        navigationTitle="Password Generator"
> +        actions={
> +          <ActionPanel>
> +            <SubmitFormAction title="Generate Password (⌘ + ↵)" onSubmit={(values) => handleGeneratePassword(values)} />
> ⬇️ Suggested change
> -            <SubmitFormAction title="Generate Password (⌘ + ↵)" onSubmit={(values) => handleGeneratePassword(values)} />
> +            <SubmitFormAction title="Generate Password" onSubmit={(values) => handleGeneratePassword(values)} />
> —
> Reply to this email directly, view it on GitHub <https://github.com/raycast/extensions/pull/752#pullrequestreview-869255205>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAILYIT2XRWS265KHJEXNIDUY7YVZANCNFSM5M7M56WA>.
> You are receiving this because you were mentioned.
>

2022-02-01 15:56 UTC, pernielsentikaer commented
> Thanks for this. - reason 32 is the longest: many sites max out at this number but can certainly go higher e.g. 64

I think that would better yes 😄 

> Can definitely show a Toast. Just FYI this was my first attempt and the docs never explain clearly what a “Toast” is so it was a bit confusing at first. A simple 2-3 sentence explaining what a Toast is with pictures and what the options are in the docs would be super helpful for newbies like me.

Check out this [example extension repo](https://github.com/raycast/extensions/tree/main/examples/api-examples) – in here you can test almost every component 💪

 > Yes can you provide an example of setting the default action?
 
It's done in the Twitch extension [with primaryaction preference].(https://github.com/raycast/extensions/pull/593/files)

> Not sure what you mean by using an NPM package to allow more settings - can you explain? 

I haven't checked if there are any cool packages at https://www.npmjs.com that could add more cool features in the long term, but I think it's good as it is 😄 💪

2022-02-01 16:12 UTC, joshuaiz commented
Awesome - thanks so much for the feedback - super helpful. I’ll make some updates and then submit a new PR when ready.

And thanks for supporting the Recast community as you do - I know it is part of your job but you are doing a great job making it inclusive, helpful, and generous!

J



> On Feb 1, 2022, at 09:56, Per Nielsen Tikær ***@***.***> wrote:
> 
> 
> Thanks for this. - reason 32 is the longest: many sites max out at this number but can certainly go higher e.g. 64
> 
> I think that would better yes 😄
> 
> Can definitely show a Toast. Just FYI this was my first attempt and the docs never explain clearly what a “Toast” is so it was a bit confusing at first. A simple 2-3 sentence explaining what a Toast is with pictures and what the options are in the docs would be super helpful for newbies like me.
> 
> Check out this example extension repo <https://github.com/raycast/extensions/tree/main/examples/api-examples> – in here you can test almost every component 💪
> 
> Yes can you provide an example of setting the default action?
> 
> It's done in the Twitch extension [with primaryaction preference].(https://github.com/raycast/extensions/pull/593/files <https://github.com/raycast/extensions/pull/593/files>)
> 
> Not sure what you mean by using an NPM package to allow more settings - can you explain?
> 
> I haven't checked if there are any cool packages at https://www.npmjs.com <https://www.npmjs.com/> that could add more cool features in the long term, but I think it's good as it is 😄 💪
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/raycast/extensions/pull/752#issuecomment-1026999101>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAILYIQD2C3A7QQ73JHXUULUY77ELANCNFSM5M7M56WA>.
> You are receiving this because you were mentioned.
>

2022-02-01 16:58 UTC, pernielsentikaer commented
> Awesome - thanks so much for the feedback - super helpful. I’ll make some updates and then submit a new PR when ready.

You don't need to make a new PR, you should just push to this PR (as you did when you fixed the linting problems) 💎 

> And thanks for supporting the Recast community as you do - I know it is part of your job but you are doing a great job making it inclusive, helpful, and generous!

Thanks a lot, It means a lot to me 😍 If you have any questions at all, catch me here or in [Slack](https://raycastcommunity.slack.com/) 😄 💯

2022-02-20 04:21 UTC, joshuaiz commented
Hi @pernielsentikaer I think I'm almost ready to push again but I have one question. How can I capture the input of the text field for the number of characters using `Enter`? 

The only way I can find to do it is using the `SubmitFormAction` or `Action.SubmitForm` but both of those use Command-Enter which is not intuitive. Is there another way to capture this input?

2022-02-20 21:26 UTC, pernielsentikaer commented
Hi @joshuaiz 👋 

The default behavior within Raycast would be `cmd+enter`, so I think we should keep it this way – looking forward for your push 💯

2022-03-17 23:58 UTC, mattisssa commented
Hey @joshuaiz! What is the status of this PR? It seems like it's been here for a long time unfinished. Shall we probably close this one and once you're ready – open another PR?

2022-03-18 01:46 UTC, joshuaiz commented
@mattisssa Hi! Sorry been busy with other projects but I'm ready to submit again...I'll push tonight.

2022-03-18 10:14 UTC, mattisssa commented
No rush, just wanted to ensure that the PR is still alive 😉

2022-03-25 05:36 UTC, pernielsentikaer requested changes
Hi @joshuaiz 👋 

Thanks for taking your time to finish the extension 🔥 

I have some feedback and suggestions for you to address 💪  

- I'm still not happy about the `<Detail />` change, it feels unnecessary, our Bitwarden extension have password generator integrated, maybe you can get some ideas?

![MqZwGRPdu93zGA8e](https://user-images.githubusercontent.com/38033107/160060189-8304f640-b218-4733-8dc9-b660d5a2c3ea.png)

Let me know what you think 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-25 05:36 UTC, pernielsentikaer commented on extensions/password-generator/src/generate-password.tsx
> +  SubmitFormAction,
Deprecated, use [Action.SubmitForm](https://developers.raycast.com/api-reference/user-interface/actions#action.submitform) instead.

2022-03-25 05:36 UTC, pernielsentikaer commented on extensions/password-generator/src/generate-password.tsx
> +  copyTextToClipboard,
Deprecated, use [Clipboard.copy](https://developers.raycast.com/api-reference/clipboard#copy) instead.

2022-03-25 05:36 UTC, pernielsentikaer commented on extensions/password-generator/src/generate-password.tsx
> +  ToastStyle,
Deprecated, use [Toast.Style](https://developers.raycast.com/api-reference/feedback/toast#toast.style) instead.

2022-03-25 05:36 UTC, pernielsentikaer commented on extensions/password-generator/src/generate-password.tsx
> +    const useChars = values.usechars === 1 ? true : false;
```suggestion
    const useNumbers = values.usenumbers === 1;
    const useChars = values.usechars === 1;
```
Simplified a bit 😄

2022-03-25 05:36 UTC, pernielsentikaer commented on extensions/password-generator/src/generate-password.tsx
> +    }
Most of this seems dead

2022-04-05 20:09 UTC, sxn commented
hi @pernielsentikaer @joshuaiz - I took the liberty to fix the deprecations and clean the extension up a bit. If you're fine with the changes, I think we can merge it 😸

2022-04-05 21:45 UTC, joshuaiz commented
I'm all or it...what do I need to do next? Pull changes down then push up again?

2022-04-07 14:08 UTC, pernielsentikaer approved these changes
Approved 😄

2022-04-07 14:14 UTC, merged