Add SSH manager extension
raycast/extensions pull request #755
Opened 2022-01-28 08:46 UTC by scopsy

## Description
A new extension to manage ssh connection and easily create a new ssh session.

## Type of change
- New extension

## Screencast
[Loom](https://www.loom.com/share/01f8ce1f0b824806a7e6b6edb04daa44)

## Checklist
- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-02-01 21:20 UTC, pernielsentikaer requested changes
Hi @scopsy 👋 

Thanks for your contribution 💯 💪 

Besides the suggestions, I have some feedback:
- In the newest version of Raycast API (^1.27.1) it's possible to make an “Open with preference” – could that work somehow to make it work with other terminals? 
- Your extension have [empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) – could you look into this?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-01 21:20 UTC, pernielsentikaer commented on extensions/ssh-manager/package.json
> +      "title": "Create New SSH Connection",
```suggestion
      "title": "Create New Connection",
      "subtitle": "SSH Connection Manager",
```

2022-02-01 21:20 UTC, pernielsentikaer commented on extensions/ssh-manager/package.json
> +      "title": "Show SSH Connections",
```suggestion
      "title": "Show Connections",
      "subtitle": "SSH Connection Manager",
```

2022-02-01 21:20 UTC, pernielsentikaer commented on extensions/ssh-manager/package.json
> +    "@raycast/api": "^1.27.0",
```suggestion
    "@raycast/api": "^1.27.1",
```

2022-02-01 21:20 UTC, pernielsentikaer commented on extensions/ssh-manager/src/create.tsx
> +import { ActionPanel, Form, showHUD, SubmitFormAction, useNavigation } from "@raycast/api";
```suggestion
import { ActionPanel, Form, showHUD, SubmitFormAction, useNavigation, randomId } from "@raycast/api";
```
You could use randomId from Raycast API instead

2022-02-01 21:20 UTC, pernielsentikaer commented on extensions/ssh-manager/src/create.tsx
> +import { createId } from "./utils";
```suggestion
import { createId } from "./utils";
```
Could be unused if you change

2022-02-01 21:20 UTC, pernielsentikaer commented on extensions/ssh-manager/src/create.tsx
> +    existingConnections.push({ ...connection, id: createId() });
```suggestion
    existingConnections.push({ ...connection, id: randomId() });
```

2022-02-01 21:20 UTC, pernielsentikaer commented on extensions/ssh-manager/src/create.tsx
> +      <Form.TextField id="name" title="Connection name" />
```suggestion
      <Form.TextField id="name" title="Connection Name" />
```

2022-02-01 21:20 UTC, pernielsentikaer commented on extensions/ssh-manager/src/create.tsx
> +        title="SSH Key location (optional)"
```suggestion
        title="SSH Key Location (optional)"
```

2022-02-02 12:46 UTC, scopsy commented
Thanks @pernielsentikaer pushed the changes.
I'm not sure about what do you mean when saying Open with preference, couldn't find it anywhere in the docs

2022-02-02 19:22 UTC, pernielsentikaer commented
> Thanks @pernielsentikaer pushed the changes. I'm not sure about what do you mean when saying Open with preference, couldn't find it anywhere in the docs

Check out the examples, [right around here](https://github.com/raycast/extensions/blob/main/examples/api-examples/package.json#L162) - maybe it can be used to set default terminal somehow 😄

2022-03-07 14:05 UTC, fe9lix commented
Hey @scopsy, what's the status of this PR? It's been stale for a while...

2022-03-07 14:07 UTC, scopsy commented
Hi, @fe9lix on my end I think I've done all the necessary changes needed. Apart from the open with preference part which I'm not sure how to implement and why it's needed. The current version works great locally.

2022-03-07 15:56 UTC, fe9lix commented
@pernielsentikaer Could you do a re-review on this?

2022-03-08 19:14 UTC, pernielsentikaer requested changes
Hi @scopsy 👋 

I asked because it's opening in “terminal” which is not my default terminal, so it would be cool if other terminal would work, of course, it's not required at all 😄 

I did a new review and found a thing not working, could you address this?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-08 19:14 UTC, pernielsentikaer commented on extensions/ssh-manager/src/create.tsx
> +        id="key"
```suggestion
        id="sshKey"
```
Looks like it has the wrong name and won't work without this

2022-04-05 20:19 UTC, sxn commented
@pernielsentikaer @scopsy I've fixed the error you pointed out & updated the extension to the latest API version. Mind re-reviewing? 😸

2022-04-05 20:36 UTC, pernielsentikaer commented
Awesome, works as expected 🔥

2022-04-05 20:36 UTC, merged