Don't rely on Warp always being in /Applications, use bundle identifi…
raycast/extensions pull request #7558
Opened 2023-07-18 23:55 UTC by schwa

## Description

Don't rely on Warp always being in /Applications, use bundle identifiier instead. Fixes #7555.

2023-07-25 06:57 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Add a changelog entry

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-07-25 06:57 UTC, pernielsentikaer commented on extensions/terminalfinder/src/clipboardToWarp.tsx
> -      set command to "open -a /Applications/Warp.app " & "${directory}"
Is this correct? It looks like a wrong path to me 🙂

2023-07-26 17:17 UTC, schwa commented
Well if you don't want this PR you only had to say.

2023-07-26 17:17 UTC, closed without merging

2023-07-27 04:59 UTC, pernielsentikaer commented
@schwa why did you close the PR? I was referring to the wrong path that seems wrong.

![Raycast-6wkPBEwg@2x](https://github.com/raycast/extensions/assets/38033107/1ea7412c-3aba-45d3-96c9-7371a9652f52)