Add sort-mentions extension
raycast/extensions pull request #7564
Opened 2023-07-19 08:29 UTC by YamenSharaf

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-07-25 07:50 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-07-25 07:50 UTC, pernielsentikaer commented on extensions/sort-mentions/package.json
> +      "subtitle": "Sort usernames alphabetically",
```suggestion
      "title": "Sort Usernames",
```

2023-07-25 07:50 UTC, pernielsentikaer commented on extensions/sort-mentions/package.json
> +      "subtitle": "Custom sort alphabetically",
```suggestion
      "title": "Sort Channels",
```

2023-07-25 07:50 UTC, pernielsentikaer commented on extensions/sort-mentions/src/utils.ts
> +  const selectedText = await getSelectedText();
If not selecting any text it crashes, could you handle this gracefully? You can see an [example here](https://developers.raycast.com/api-reference/environment#example-3)

![sort-mentions 2023-07-25 at 09 42 58](https://github.com/raycast/extensions/assets/38033107/0f34b560-7901-4493-aab0-0e059a73e641)

2023-07-25 15:44 UTC, YamenSharaf commented
Thank you @pernielsentikaer for taking the time to review. I've committed new changes to address the issues you mentioned.

Please feel free to take a second look and let me know if there's something I can improve 🙏🏻

2023-07-26 06:11 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-07-26 06:34 UTC, merged