Add rusbase extension
raycast/extensions pull request #7566
Opened 2023-07-19 09:50 UTC by khlebobul

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-07-26 07:13 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-07-26 07:13 UTC, pernielsentikaer commented on extensions/rusbase/package.json
> +      "title": "Sections",
Can we add something like Search/View/List before?

2023-07-26 07:13 UTC, pernielsentikaer commented on extensions/rusbase/package.json
> +      "title": "Markets",
Can we add something like Search/View/List before?

2023-07-26 15:20 UTC, khlebobul commented
@pernielsentikaer Good evening, it's just a media resource in a different language. You mean I need to translate the searchBar items into English?

2023-07-27 04:56 UTC, pernielsentikaer commented
Yes, that's not allowed according to the [documentation](https://developers.raycast.com/basics/prepare-an-extension-for-store#localization-language)

2023-07-27 05:28 UTC, khlebobul commented
Okay, I'll fix it soon, thank you

2023-07-28 06:27 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-07-30 10:02 UTC, khlebobul commented
Hello, for some reason there is another file package-lock.json outside the extension folder. I can't delete it. Could you please help me with this problem to get the extension into the store?

2023-07-31 09:00 UTC, pernielsentikaer commented on extensions/rusbase/src/markets.tsx
> +          defaultValue={"Беспилотные аппараты"}
Not sure what this is, can you correct that too?

2023-08-01 11:41 UTC, pernielsentikaer approved these changes

2023-08-01 11:51 UTC, merged