[todo-list] Implement sorting
raycast/extensions pull request #7636
Opened 2023-07-24 21:36 UTC by bkeys818

## Description

Creates a new preference that allows the user to choose how tasks are sorted (closes #7512).

Adds priority to tasks, allowing the user to take more control of the order of tasks.

## Screencast

<img width="862" alt="Screencast Example" src="https://github.com/raycast/extensions/assets/65252963/220cf423-463c-40e5-87ce-3665675f1fd3">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-07-25 06:20 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- When changing the priority it changes sorting, seems like it's sorting by last updated instead of creation date (as expected)

- You can use [autoFocus](https://developers.raycast.com/api-reference/user-interface/action-panel#props-2) for having the selected priority when opening the submenu

- Could you add a changelog entry

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-07-25 14:00 UTC, bkeys818 commented
I admit that priorities is a feature that most people won't use.

I could disable it by default, and create a preference to enable it.

2023-07-26 06:51 UTC, pernielsentikaer commented
I updated the autofocus to match the current element and added a better tooltip for the accessory - do you mind checking it @bkeys818 and what do you think @maggie-j-liu

2023-07-26 11:23 UTC, bkeys818 commented
Looks good to me!

2023-07-27 06:38 UTC, pernielsentikaer commented
Let's hear what @maggie-j-liu says 🙂

2023-08-10 08:15 UTC, pernielsentikaer commented
@maggie-j-liu are you still around?

2023-08-11 09:25 UTC, pernielsentikaer commented
Let's add it, also, you don't have to use priorities at all 🙂

2023-08-11 09:28 UTC, merged