Add "Colors" extension
raycast/extensions pull request #768
Opened 2022-01-29 19:16 UTC by linuz90

## Description

This extension uses the `tinycolor` library to convert your provided color into various formats. It's very handy for designers and developers that need to do quick conversions.

For example, I often prefer HSL to RGB or HEX since it lets me change saturation and luminance more easily.

You can press enter on a converted color to copy it, or Command + Enter to insert it inline.

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/9629188/151674382-e431c38a-204b-4d36-b2ab-045cf14b6979.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-01-29 19:18 UTC, linuz90 commented
Forgot to showcase that invalid colors will throw an error:

![CleanShot 2022-01-29 at 19 17 45@2x](https://user-images.githubusercontent.com/9629188/151674542-87e715ff-a6ac-48c4-be7b-4765bf059870.png)

2022-02-01 22:22 UTC, pernielsentikaer requested changes
Hi @linuz90 👋 

Thanks for your contribution 💪 

I left some suggestions for you to work with, also, it could be cool with:
- A way to select default action, if copy or paste should be default ([Like done in this extension](https://github.com/raycast/extensions/pull/593/files))

- A new command that takes selection as color value (idea)

- A new command that takes clipboard as color value (idea)

Looking forward to testing this out again 💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-01 22:22 UTC, pernielsentikaer commented on extensions/colors/src/index.tsx
> +} from "@raycast/api";
```suggestion
import {
  ActionPanel,
  ActionPanelItem,
  CopyToClipboardAction,
  Form,
  Icon,
  List,
  PasteAction,
  showToast,
  SubmitFormAction,
  ToastStyle,
  useNavigation,
} from "@raycast/api";
```

2022-02-01 22:22 UTC, pernielsentikaer commented on extensions/colors/src/index.tsx
> +
```suggestion
```

2022-02-01 22:22 UTC, pernielsentikaer commented on extensions/colors/src/index.tsx
> +      toast.show();
```suggestion
      showToast(ToastStyle.Failure, "Please enter a color");
```

2022-02-01 22:22 UTC, pernielsentikaer commented on extensions/colors/src/index.tsx
> +      toast.show();
```suggestion
      showToast(ToastStyle.Failure, "This is not a valid color");
```

2022-02-01 22:22 UTC, pernielsentikaer commented on extensions/colors/src/index.tsx
> +      navigationTitle="Insert color to convert"
```suggestion
      navigationTitle="Insert Color to Convert"
```

2022-02-01 22:22 UTC, pernielsentikaer commented on extensions/colors/src/index.tsx
> +    <List navigationTitle="Converted colors">
```suggestion
    <List>
```
Redundant

2022-02-01 22:22 UTC, pernielsentikaer commented on extensions/colors/src/index.tsx
> +          title="Convert new color"
```suggestion
          title="Convert New Color"
```

2022-02-01 22:22 UTC, pernielsentikaer commented on extensions/colors/src/index.tsx
> +              <ActionPanelItem title="New color" onAction={() => navigation.pop()} />
```suggestion
              <ActionPanelItem title="New Color" onAction={() => navigation.pop()} />
```

2022-02-01 22:22 UTC, pernielsentikaer commented on extensions/colors/src/index.tsx
> +      <List.Section title="Converted colors">
```suggestion
      <List.Section title="Converted Colors">
```

2022-02-01 22:22 UTC, pernielsentikaer commented on extensions/colors/src/index.tsx
> +          description="Perceived brightness"
```suggestion
          description="Perceived Brightness"
```

2022-02-01 22:22 UTC, pernielsentikaer commented on extensions/colors/src/index.tsx
> +      <CopyToClipboardAction title="Copy to clipboard" content={content} />
```suggestion
      <CopyToClipboardAction title="Copy to Clipboard" content={content} />
```

2022-02-01 22:22 UTC, pernielsentikaer commented on extensions/colors/src/index.tsx
> +      <PasteAction title="Insert" content={content} shortcut={{ modifiers: ["cmd"], key: "enter" }} />
```suggestion
      <PasteAction title="Paste" content={content} shortcut={{ modifiers: ["cmd"], key: "enter" }} />
```

2022-03-07 14:08 UTC, fe9lix commented
Hey @linuz90, what's the status of this PR? Are you planning on addressing the feedback from @pernielsentikaer?

2022-03-09 10:54 UTC, linuz90 commented
> Hey @linuz90, what's the status of this PR? Are you planning on addressing the feedback from @pernielsentikaer?

Hey, I'd love to but I'm just too busy working on Typefully now, so I'll likely won't have time for this for a few weeks.

2022-03-09 10:59 UTC, fe9lix commented
Are you fine with closing this for now and then re-opening a new PR with the feedback addressed, once you've found time?

2022-03-10 16:04 UTC, linuz90 commented
Sure, no problem!

2022-03-11 08:17 UTC, pernielsentikaer commented
Closing as agreed

2022-03-11 08:17 UTC, closed without merging