Add storybook-launcher extension
raycast/extensions pull request #7934
Opened 2023-08-14 14:27 UTC by winkerVSbecks

## Description

## Screencast

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-08-17 07:56 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-08-17 07:56 UTC, pernielsentikaer commented on extensions/storybook-launcher/src/components/DeleteStorybookAction.tsx
> +      shortcut={{ modifiers: ["ctrl"], key: "x" }}
```suggestion
      shortcut={{ modifiers: ["ctrl"], key: "x" }}
      style={Action.Style.Destructive}
```

2023-08-17 07:56 UTC, pernielsentikaer commented on extensions/storybook-launcher/src/components/DeleteStorybookAction.tsx
> +        if (await confirmAlert({ title: "Are you sure?" })) {
You can add [style and icon](https://developers.raycast.com/api-reference/feedback/alert#properties) here

2023-08-18 17:25 UTC, winkerVSbecks commented
@pernielsentikaer thanks for the feedback. Updated.

2023-08-22 09:25 UTC, pernielsentikaer approved these changes

2023-08-22 09:40 UTC, merged