Add convertible-bond-reminder extension
raycast/extensions pull request #7948
Opened 2023-08-15 13:10 UTC by toxic-johann

## Description

Create a menu icon to query Chinese convertible bond data. That could remind people to buy the bonds.

## Screencast

<img width="1706" alt="image" src="https://github.com/raycast/extensions/assets/2577157/d4f56b10-a5c9-4cee-8ac2-ed62ac25dd5a">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-08-17 09:42 UTC, pernielsentikaer requested changes
Hi 👋 

I'm just getting this error when opening the menubar, can you look into this?

![convertible-bond-reminder 2023-08-17 at 11 41 33](https://github.com/raycast/extensions/assets/38033107/04a7c4b8-ba65-4071-9907-fd37edd4313e)

At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

2023-08-17 09:44 UTC, toxic-johann commented
Gotcha. I will check tonight

2023-08-18 13:48 UTC, toxic-johann commented
<img width="1239" alt="image" src="https://github.com/raycast/extensions/assets/2577157/d249ed76-50ab-491f-8b8d-44cd296df1b1">

2023-08-21 06:55 UTC, pernielsentikaer commented
Still getting an error

![convertible-bond-reminder 2023-08-21 at 08 55 08](https://github.com/raycast/extensions/assets/38033107/0b8aa950-173d-45d7-b913-7a007a7447d4)

2023-08-21 06:58 UTC, toxic-johann commented
Oh. Sorry. Let me check

2023-08-21 07:02 UTC, toxic-johann commented
Fixed.

2023-08-31 05:33 UTC, toxic-johann commented
@pernielsentikaer It would be awesome if you had time to review it again. Thanks

2023-08-31 11:51 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- The menubar icon is not looking good with a light background - you can see how I did in my [extension](https://github.com/raycast/extensions/blob/27c2a239b89bf6d5ad5ecec8a29ad6a1d5dc4714/extensions/tableplus/src/menubar.tsx#L21)

- What does it look like when there is data? Some more information about the extension in the README would be nice

- Uoi can remove the default Raycast icon

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-08-31 11:51 UTC, pernielsentikaer commented on extensions/convertible-bond-reminder/package.json
> +      "title": "convertible bond",
```suggestion
      "title": "Convertible Bond",
```

2023-08-31 11:51 UTC, pernielsentikaer commented on extensions/convertible-bond-reminder/package.json
> +      "subtitle": "convertible bond",
```suggestion
```

2023-08-31 11:51 UTC, pernielsentikaer commented on extensions/convertible-bond-reminder/src/convertible-bond.tsx
> +      <MenuBarExtra.Item title={`Last Background Sync Time：${cache.get("backgroundLaunchTime")}`} />
This feels a bit clumpsy

2023-09-18 11:29 UTC, toxic-johann commented
Still working on this.

2023-10-11 11:03 UTC, closed without merging