Add KeepassXC Extension
raycast/extensions pull request #803
Opened 2022-02-04 06:10 UTC by zkytech

## Description

Add KeepassXC Extension to access KeePass Database

## Type of change

- New extension

## Screencast
![example](https://user-images.githubusercontent.com/30063898/152480673-51e55d41-f21a-494c-927e-644bd8166e03.gif)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-02-05 06:31 UTC, pernielsentikaer requested changes
Hi @zkytech 👋 

Cool you look into your README – I was not able to test the extension by reading it - maybe a step by step guide from scratch (Just installed [KeePassXC](https://keepassxc.org/))

2022-02-05 08:56 UTC, zkytech commented
> `Test Guide.md` has been added.

2022-02-07 05:51 UTC, pernielsentikaer requested changes
Hi @zkytech 👋 

I have some feeedback for you 🔥 

- When both app location/file location or password is wrong, all three states should show the failure toast

- Is it keepass, KeePass, KeepassXC, some more consistent naming would be nice.

- Remove command-icon.png from assets since it's redundant

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-07 05:51 UTC, pernielsentikaer commented on extensions/keepassxc/README.md
> +# Keepass Extension for Raycast
```suggestion
# KeepassXC Extension for Raycast
```

2022-02-07 05:51 UTC, pernielsentikaer commented on extensions/keepassxc/README.md
> +This is a raycast extension to access keepass database.
```suggestion
This is a Raycast extension to access keepass database.
```

2022-02-07 05:51 UTC, pernielsentikaer commented on extensions/keepassxc/README.md
> +### Short Cuts
```suggestion
### Shortcuts
```

2022-02-07 05:51 UTC, pernielsentikaer commented on extensions/keepassxc/package.json
> +      "subtitle": "Search Password in KeepassXC",
```suggestion
      "title": "Search Passwords",
      "subtitle": "KeepassXC",
```

2022-02-07 14:08 UTC, zkytech commented
> Hi @zkytech 👋
> 
> I have some feeedback for you 🔥
> 
> * When both app location/file location or password is wrong, all three states should show the failure toast
> * Is it keepass, KeePass, KeepassXC, some more consistent naming would be nice.
> * Remove command-icon.png from assets since it's redundant
> 
> Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

@pernielsentikaer 

Thanks for your suggestion.

- [x] An error handler has been added to handle different error messages.
- [x] Your commits has been accepted to update words in `README.md` and `package.json`.
- [x] Redundant assets has been removed.

2022-02-09 06:40 UTC, pernielsentikaer requested changes
Hi @zkytech 👋 

We're getting pretty close, found a few more things, and then we're ready to move on!

- Can you also provide a light icon for a dark background? Otherwise, this won't look good in different themes. You can find [more info here](https://developers.raycast.com/basics/prepare-an-extension-for-store#extension-icon).

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-09 06:40 UTC, pernielsentikaer commented on extensions/keepassxc/src/index.tsx
> +import { ActionPanel, closeMainWindow, List, showToast, ToastStyle } from "@raycast/api";
```suggestion
import { ActionPanel, closeMainWindow, Icon, List, showToast, ToastStyle } from "@raycast/api";
```

2022-02-09 06:40 UTC, pernielsentikaer commented on extensions/keepassxc/src/index.tsx
> +                title="Copy and Paste Password"
```suggestion
                title="Paste"
                icon={Icon.TextDocument}
```
Would make more sense to have it only paste with this action (rewrite logic of copyAndPastePassword)

2022-02-09 06:40 UTC, pernielsentikaer commented on extensions/keepassxc/src/index.tsx
> +                title="Copy Password"
```suggestion
                title="Copy Password"
                icon={Icon.Clipboard}
```

2022-02-09 06:40 UTC, pernielsentikaer commented on extensions/keepassxc/src/index.tsx
> +                title="Copy Username"
```suggestion
                title="Copy Username"
                icon={Icon.Clipboard}
```

2022-02-09 06:40 UTC, pernielsentikaer commented on extensions/keepassxc/package.json
> +      "title": "Keepass Database File",
```suggestion
      "title": "Path of Keepass Database File",
```

2022-02-09 13:40 UTC, zkytech commented
> Hi @zkytech 👋
> 
> We're getting pretty close, found a few more things, and then we're ready to move on!
> 
> * Can you also provide a light icon for a dark background? Otherwise, this won't look good in different themes. You can find [more info here](https://developers.raycast.com/basics/prepare-an-extension-for-store#extension-icon).
> 
> Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

@pernielsentikaer 
Dark icon has been replaced by a light one.

2022-02-09 21:44 UTC, pernielsentikaer approved these changes
Hi @zkytech 👋 

Thanks for taking your time improving the UX ❤️ I think we're ready to proceed to the final step with the last review before shipping it 🚢

2022-02-10 07:35 UTC, fe9lix commented
Hey @zkytech – would you mind putting all supporting media files in a top-level "media" folder in your extension? (runtime assets should stay in assets since they will be bundled into the extension)

2022-02-11 04:37 UTC, zkytech commented
> Hey @zkytech – would you mind putting all supporting media files in a top-level "media" folder in your extension? (runtime assets should stay in assets since they will be bundled into the extension)

@fe9lix 

Done.

2022-02-11 08:22 UTC, merged

2022-02-11 09:03 UTC, fe9lix commented
@zkytech and @pernielsentikaer Fy, I've fixed/update the title and description on master: https://github.com/raycast/extensions/commit/a69d15c6b57430234fb8cacc383502118934969e

The spelling of KeePassXC seemed to be wrong and descriptions should not be title-cased.

2022-04-07 23:07 UTC, rickysullivan-gallagher commented
It would be nice to be able to supply a **--key-file** param.