Add grammari-x extension
raycast/extensions pull request #8049
Opened 2023-08-22 21:32 UTC by hakob8956

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-08-28 11:32 UTC, pernielsentikaer requested changes
What do you say about the following corrections?

2023-08-28 11:32 UTC, pernielsentikaer commented on extensions/grammari-x/package.json
> +  "title": "Your Writing's Best Friend",
```suggestion
  "title": "GrammariX",
```

2023-08-28 11:32 UTC, pernielsentikaer commented on extensions/grammari-x/package.json
> +      "title": "GrammariX",
```suggestion
      "title": "Improve Writing",
```

2023-08-28 11:32 UTC, pernielsentikaer commented on extensions/grammari-x/package.json
> +  "description": "In this extension, you can fix your grammar and paraphrase your sentences more effectively.",
```suggestion
  "description": "Your Writing's Best Friend. In this extension, you can fix your grammar and paraphrase your sentences more effectively.",
```

2023-08-28 12:08 UTC, hakob8956 commented
> What do you say about the following corrections?

It seems reasonable. I'll commit to it ;)

2023-08-28 12:14 UTC, hakob8956 commented
@pernielsentikaer 
For future implementation, as you can see in the upper right-hand corner, there is a dropdown that is specifically related to the 'tone changer.' However, it appears that there is no feature available to create a dropdown-like list item. Due to this limitation, I have positioned it globally after the search bar. It would be preferable if I could trigger this dropdown when the 'tone changer' list item is selected. Unfortunately, there is no implemented event for such an action. I am aware that I could create separate commands for each list item, but this doesn't seem like an optimal solution. I would prefer to have a single command for all list items due to certain reasons. If you have any valuable suggestions in this context, I am open to listening.

2023-08-31 15:54 UTC, hakob8956 commented
@pernielsentikaer 
Added history and saved answer functionality

2023-09-06 08:50 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-09-06 08:54 UTC, pernielsentikaer approved these changes

2023-09-06 09:10 UTC, merged