Update spotify-controls extension
raycast/extensions pull request #8095
Opened 2023-08-26 08:56 UTC by stevensd2m

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-08-29 12:57 UTC, mil3na requested changes
Hi! 
Thanks for your contribution! My name is Milena and I will be reviewing your changes today.
I feel like adding Discovery Weekly (or playing any playlist for that matter) is a bit out of scope for a commands extension. I think the goal here is to control Spotify without adding anything specific. 
Maybe something that would make more sense on the spotify-player extension?

2023-08-29 12:57 UTC, mil3na commented on extensions/spotify-controls/.gitignore
This file should not be needed.

2023-08-29 16:40 UTC, stevensd2m commented
@mil3na thanks for the review 😄  given your feedback I'll close the PR then and open it on the player instead

2023-08-30 06:51 UTC, pernielsentikaer commented
Closing as requested

2023-08-30 06:51 UTC, closed without merging