Add new extension: Word Search
raycast/extensions pull request #810
Opened 2022-02-05 07:58 UTC by RishabSwift

## Description

Word Search allows you to search for synonyms, antonyms, and rhymes given a word. It allows you to quickly look up words that fit your use case and can help your writing immensly.

## Type of change

- New extension

## Screencast

[Screencast Recording](https://cln.sh/rttkUH)

### Screenshots

Available on the [readme page](https://github.com/RishabSwift/extensions/tree/main/extensions/word-search): 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-02-05 09:14 UTC, pernielsentikaer requested changes
Hi @RishabSwift 👋 

Thanks for your contribution 💪 Thanks for the chat in Slack about your extension 💯 

I left some feedback for your PR that you can look into 🔥 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-05 09:14 UTC, pernielsentikaer commented on extensions/word-search/package.json
> +      "subtitle": "Search for synonyms",
```suggestion
      "subtitle": "Datamuse",
```

2022-02-05 09:14 UTC, pernielsentikaer commented on extensions/word-search/package.json
> +      "subtitle": "Search for antonyms",
```suggestion
      "subtitle": "Datamuse",
```

2022-02-05 09:14 UTC, pernielsentikaer commented on extensions/word-search/package.json
> +      "subtitle": "Search for rhymes",
```suggestion
      "subtitle": "Datamuse",
```

2022-02-05 09:14 UTC, pernielsentikaer commented on extensions/word-search/src/search-results.tsx
> +                title="Copy & Insert Word"
```suggestion
                title="Paste Word"
```
Also, you could also add [CopyToClipboardAction](https://developers.raycast.com/api-reference/user-interface/actions#copytoclipboardaction)

2022-02-05 09:28 UTC, RishabSwift reviewed
Resolve suggested feedback

2022-02-05 09:36 UTC, pernielsentikaer requested changes
Just found a few more to correct 🔥

2022-02-05 09:36 UTC, pernielsentikaer commented on extensions/word-search/package.json
> +      "title": "Word Rhyme search",
```suggestion
      "title": "Search Word Rhyme",
```

2022-02-05 09:36 UTC, pernielsentikaer commented on extensions/word-search/package.json
> +      "title": "Word Synonym Search",
```suggestion
      "title": "Search Word Synonym",
```

2022-02-05 09:36 UTC, pernielsentikaer commented on extensions/word-search/package.json
> +      "title": "Word Antonym Search",
```suggestion
      "title": "Search Word Antonym",
```

2022-02-05 09:39 UTC, RishabSwift reviewed
Updated suggested titles

2022-02-05 09:43 UTC, pernielsentikaer approved these changes
Hi @RishabSwift 👋 

Thanks for your contribution 🔥

2022-02-05 11:40 UTC, sxn commented
hi @RishabSwift - nice extension! Just one small change and then we can merge it: could you move the screenshots out of the `assets` folder and into a `media/` folder in the root of the extension? The `assets/` folder is meant for files that need to be included with the extension, which for screenshots is not the case. 😸

2022-02-05 11:57 UTC, pernielsentikaer commented
Are you sure? They are referenced in the README ☺

2022-02-05 11:57 UTC, pernielsentikaer commented
> hi @RishabSwift - nice extension! Just one small change and then we can merge it: could you move the screenshots out of the `assets` folder and into a `media/` folder in the root of the extension? The `assets/` folder is meant for files that need to be included with the extension, which for screenshots is not the case. 😸 

Are you sure? They are referenced in the README ☺

2022-02-05 21:49 UTC, RishabSwift commented
Hello @sxn 
Thanks for the feedbacak, I've moved the screenshots into a `media` folder and pushed it 😄

2022-02-06 18:59 UTC, merged

2022-02-06 18:59 UTC, sxn commented
🎉