[UPDATE] fix crashing bug, typo in settings, error handling
raycast/extensions pull request #812
Opened 2022-02-05 22:20 UTC by marcjulianschwarz

## Description 

Fixed a bug that caused crashes when extension was newly installed. More details can be found in [this discussion about the issue](https://github.com/marcjulianschwarz/obsidian-raycast/issues/10).

*Short summary:* A preference setting wasn't checked for undefined before use.
*Fix:* Added undefined check. More error handling.

And a small typo fix.

## Type of change

- Bug fix / improvement for my extension

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-02-07 22:19 UTC, pernielsentikaer requested changes
Hi @marcjulianschwarz 👋 

Thanks for your fix, everything seems to work as expected 💪 

I left a few NITs, could you correct them to before merging?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-07 22:19 UTC, pernielsentikaer commented on extensions/obsidian/src/createnote.tsx
> +        showToast(ToastStyle.Failure, "Couldnt create folder structure for the given path.");
```suggestion
        showToast(ToastStyle.Failure, "Couldn't create folder structure for the given path.");
```

2022-02-07 22:19 UTC, pernielsentikaer commented on extensions/obsidian/src/createnote.tsx
> +        showToast(ToastStyle.Failure, "Couldnt write the file: " + notePath + "/" + name + ".md");
```suggestion
        showToast(ToastStyle.Failure, "Couldn't write the file: " + notePath + "/" + name + ".md");
```

2022-02-09 09:15 UTC, marcjulianschwarz commented
Hi @pernielsentikaer 👋
thank you, corrected them.

2022-02-09 21:35 UTC, pernielsentikaer approved these changes
Awesome @marcjulianschwarz 🔥 

I think we're ready to proceed to the next stage 🚀 

Once again, thanks for your time maintaining the extension 💪

2022-02-10 07:41 UTC, merged

2022-02-10 07:43 UTC, marcjulianschwarz commented
@pernielsentikaer 

No Problem and thank you for the quick review processes.