Update metronome extension
raycast/extensions pull request #8133
Opened 2023-08-29 15:02 UTC by Visual-Studio-Coder

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-08-30 06:42 UTC, pernielsentikaer commented
Seems like you are pushing the complete extension again, could you look into only pushing the new changes @Visual-Studio-Coder

2023-08-30 13:23 UTC, Visual-Studio-Coder commented
@pernielsentikaer i actually HAVE made some changes. I mean, the change I made IS pretty small because I was just fixing a typo I had noticed

2023-08-30 13:34 UTC, Visual-Studio-Coder commented
How do I fix the merge conflicts?

2023-08-30 13:50 UTC, pernielsentikaer commented
Maybe if it's just a small correction you delete the local version of the extension and fork it again

2023-08-30 14:51 UTC, Visual-Studio-Coder commented
Alright, I fixed it.

2023-08-31 10:25 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Make `Accents` optional and let the user add a preference for the default (could be 4)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-08-31 10:25 UTC, pernielsentikaer commented on extensions/metronome/src/index.tsx
>        <List searchBarPlaceholder="" searchText="">
```suggestion
      <List searchBarPlaceholder="">
```

2023-09-14 12:55 UTC, pernielsentikaer commented
What do you think @Visual-Studio-Coder

2023-09-18 01:24 UTC, Visual-Studio-Coder commented
@pernielsentikaer I finished it after a long time!

2023-09-20 10:36 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-09-20 10:45 UTC, merged