Update word-count extension
raycast/extensions pull request #8351
Opened 2023-09-12 08:51 UTC by danulqua

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-09-12 20:04 UTC, itsmingjie commented on extensions/word-count/src/count.tsx
> +        setText(clipboard);
Not a huge fan of blending the two steps into the same try-catch block. Would something like this make the steps easier to comprehend? 

```ts
      let content = "";

      try {
        const selectedText = await getSelectedText();
        if (selectedText) {
          content = selectedText.trim();
        }
      } catch {
        // ignore error, fallback to clipboard
      }

      if (!content) {
        content = await readFromClipboard();
      }

      setText(content);
```

2023-09-12 20:05 UTC, itsmingjie commented
Thanks for the contribution! Left one comment, open to discussions

2023-09-14 00:36 UTC, itsmingjie requested changes
Apologies, some more consistency changes! (Please test before submitting for approval because I wrote some changes inline). Thanks so much!

2023-09-14 00:36 UTC, itsmingjie commented on extensions/word-count/src/utils.ts
> +import { Clipboard, Toast, showToast } from "@raycast/api";
```suggestion
import { Clipboard, Toast, getSelectedText, showToast } from "@raycast/api";
```

2023-09-14 00:36 UTC, itsmingjie commented on extensions/word-count/src/utils.ts
> +import { Clipboard, Toast, showToast } from "@raycast/api";
```suggestion
import { Clipboard, Toast, getSelectedText, showToast } from "@raycast/api";
```

2023-09-14 00:36 UTC, itsmingjie commented on extensions/word-count/src/utils.ts
> +}
```suggestion
}

export async function readFromSelection() {
  try {
    const selectedText = await getSelectedText();
    if (selectedText) {
      showToast({
        style: Toast.Style.Success,
        title: `Text loaded from selected text`,
        message: `[⌘ + E] to reset`,
      });
      return selectedText.trim();
    }
  } catch {
    // ignore error, fallback to an empty string
  }

  return "";
}

```

2023-09-14 00:36 UTC, itsmingjie commented on extensions/word-count/src/count.tsx
> +import { Action, ActionPanel, Form, getSelectedText, Icon } from "@raycast/api";
```suggestion
import { Action, ActionPanel, Form, Icon } from "@raycast/api";
```

2023-09-14 00:36 UTC, itsmingjie commented on extensions/word-count/src/count.tsx
> +import { readFromClipboard } from "./utils";
```suggestion
import { readFromClipboard, readFromSelection } from "./utils";
```

2023-09-14 00:36 UTC, itsmingjie commented on extensions/word-count/src/count.tsx
> +
```suggestion
```

2023-09-14 00:36 UTC, itsmingjie commented on extensions/word-count/src/count.tsx
> +      let content = "";
```suggestion
      let content = await readFromSelection();

      if (!content) {
        content = await readFromClipboard();
      }
```

2023-09-14 06:51 UTC, danulqua commented
@itsmingjie Okay, yes, it's a good idea to move the reading from selection function also to the utils. I was thinking about that but for some reason I thought "let it be here, it's called only once" 😅

2023-09-14 11:09 UTC, itsmingjie approved these changes
Looking good!

2023-09-14 11:10 UTC, itsmingjie commented
@raycastbot approve

(?... is this a thing yet?)

2023-09-14 11:31 UTC, danulqua commented
@itsmingjie Someone from Raycast has to take a look and merge the changes. You only need to approve what you've already done. 🙂

2023-09-21 08:22 UTC, pernielsentikaer approved these changes

2023-09-21 08:22 UTC, merged