Add Pokédex extension
raycast/extensions pull request #840
Opened 2022-02-09 04:52 UTC by anhthang

## Description

Search for a Pokémon by name or using its National Pokédex number.

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/10458061/153123849-9e9dcf4f-bd42-4f05-8d65-859db3ecd498.mov

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-02-10 21:15 UTC, pernielsentikaer requested changes
Hi @anhthang 👋 

Thanks for your contribution, I don't have so much feedback for you 🔥 

Could you also move example.png to a folder called `media` instead 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-11 02:50 UTC, anhthang commented on extensions/pokedex/src/api/index.ts
> +    ? `{name: {_eq: ${nameOrId}}}`
Thanks for letting me know about this. I have fixed it in latest commit.

> Can't search for “Pikachu”, only “pikachu”

2022-02-11 02:51 UTC, anhthang commented
Hi @pernielsentikaer

Thank you for your suggestions. I have moved to `media` folder. Please help me review again.

2022-02-11 05:27 UTC, pernielsentikaer requested changes
Hi @anhthang 👋 

You added the .toLowerCase() to `id`, not the `name`

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-11 06:10 UTC, anhthang commented
Hi @pernielsentikaer 

I have fixed. It's my mistaken when sync from my repository to raycast/extensions

2022-02-11 06:53 UTC, pernielsentikaer reviewed
Hi @anhthang 👋 

Thanks for the correction 💯 After testing it out, I keep getting `not a valid graphql query` both when searching for number or name – even if I revert the latest push 

Do you know if anything changed in the other end?

2022-02-11 09:54 UTC, anhthang commented
Hi @pernielsentikaer 

Thanks for letting me know. I will do more test again to figure out what is error with graphql query as I haven't get this issue before.

2022-02-11 11:57 UTC, pernielsentikaer reviewed
Thanks @anhthang 🔥 

It works much nicer now!

A wild though (no need to be added now), would it be possible to list all Pokémon's when loading the extension and then filter in them – then when selection one, it pushes to another view?

2022-02-11 12:13 UTC, anhthang commented
Hi @pernielsentikaer 

Yes, it will be really nice. I also have some to do items to improve the extension that I will do later.

Thanks for your help.

2022-02-11 17:16 UTC, anhthang commented
Hi @pernielsentikaer 

I have done your suggestion and updated. Could you please review again? 😊

Also, is there any way to disable search box in the List?

<img width="862" alt="Screen Shot 2022-02-12 at 12 09 16 AM" src="https://user-images.githubusercontent.com/10458061/153637665-4937bc93-5c6c-4d20-9a57-f2dd00c458fa.png">

2022-02-11 21:10 UTC, pernielsentikaer commented
Hi @anhthang 👋 

It works much better now, thanks for the update 🔥 

The only way to avoid the search in top is to use a [Detail view with Markdown](https://developers.raycast.com/api-reference/user-interface/detail#detail) - something like this:

https://user-images.githubusercontent.com/38033107/153670163-2b1e0efb-1a0f-49bf-b9b7-f9629bdbed71.mp4

I'm not sure the list with attributes looks as smooth as when it's a list, let me know what you think - it's kinda also awesome as detail with the image

Right now, when you change from one list to the next, you have [empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) that we need to address

2022-02-12 01:52 UTC, anhthang commented
Hi @pernielsentikaer 👋 

Yeah, It's much better when we use markdown to render and show image. So I changed it. But it seems CommonMark is not support table, that would be better a lots.

<img width="862" alt="image" src="https://user-images.githubusercontent.com/10458061/153691703-3f9d1443-6276-4489-aeaf-ccb7f5a3364e.png">

Loading state added already but I'm not sure that the flicker still there. Please help me double check on it.

2022-02-13 07:28 UTC, pernielsentikaer commented
That turned out quite nice @anhthang 💪 

In your surprise me, I would push the PokemonDetail directly, do you think you can work that out? That would improve the UX a lot 🚀

2022-02-13 11:15 UTC, anhthang commented
Hi @pernielsentikaer 

Thanks for the idea, I forgot that we can do it 😄 The extension updated just now.

2022-02-13 21:59 UTC, pernielsentikaer requested changes
Hi @anhthang 👋 

I think we're about being there, It's turning out quite nice – what a UX!

Check the latest comments, could be an idea to add fallback image just in case :)

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-13 21:59 UTC, pernielsentikaer commented on extensions/pokedex/package.json
> +    "@raycast/api": "^1.27.1",
```suggestion
    "@raycast/api": "^1.28.0",
```

2022-02-13 21:59 UTC, pernielsentikaer commented on extensions/pokedex/src/index.tsx
> +                  source: pokemon.artwork,
```suggestion
                  source: pokemon.artwork,
                  fallback: "icon.png"
```
Fallback if image fails to load

2022-02-13 21:59 UTC, pernielsentikaer commented on extensions/pokedex/src/index.tsx
> +                      title="Show Details"
```suggestion
                      title="Show Details",
                      icon={Icon.MagnifyingGlass},
```
Or another icon

2022-02-14 22:31 UTC, pernielsentikaer requested changes
Hi @anhthang 👋 

After last review, I'm not able to load almost any Detail views, somehow only 001 opens, the rest keeps spinning forever (the same with surprise me) – can you check if anything is wrong?

When setting a `console.log` in `PokemonDetail` – I can see that Bulbasaur logs 4 times, rest only two, I'm not sure it has anything to do with it?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-15 00:49 UTC, anhthang commented
Hi @pernielsentikaer 👋 

I have tested again and got different Pokemon every times. I'm not sure why it happens to you, maybe it's just a coincidence.

Regarding to the loading, I think the API is unstable at that time and keeping the connection. IMO, we can set a timeout and show no results view for this in the next PR for this case.

2022-02-15 12:46 UTC, pernielsentikaer commented
Hi @anhthang 👋 

I think you're right! Everything seems to work as expected right now 💪

Do you have an idea to show a failure toast when it takes too long time to get the response, it sounds like an awesome idea 🚀

2022-02-15 13:52 UTC, anhthang commented
Hi @pernielsentikaer 

I think it just a toast with message like: "Unable to get Pokémon details." for all the error from PokéAPI and a page with no results image. Do we have a thing like that for Detail API?

And, how long do you think it's good to wait? Is it 10s is enough as it usually getting result within 1-2s.

2022-02-15 22:05 UTC, pernielsentikaer commented
If it's possible, I think it should time out after around 5 seconds, as you says it shouldn't take that long time.

The message could be something with “…try again later”

2022-02-16 06:57 UTC, anhthang commented
Hi @pernielsentikaer 

What do you think about showing a failure toast, then back to the listing page if error?

2022-02-17 20:09 UTC, pernielsentikaer approved these changes
Hi @anhthang 🔥 

Awesome!!! Wow, it turned out even more awesome that I expected, well done 💪

2022-02-17 21:26 UTC, merged