feat(helm): add helm documentation support
raycast/extensions pull request #847
Opened 2022-02-09 23:56 UTC by tiagomichaelsousa

## Description

This extension will allow to easily go through the Helm docs directly from Raycast. 
It will also allow searching within the documentation with algolia support and integration.
While developing the extension I tried to followed the same conventions as:

- [algolia](https://github.com/tiagomichaelsousa/extensions/tree/main/extensions/algolia)
- [laravel-docs](https://github.com/tiagomichaelsousa/extensions/tree/main/extensions/laravel-docs)
- [spatie-documentation](https://github.com/tiagomichaelsousa/extensions/tree/main/extensions/spatie-documentation)

## Type of change

- New extension

## Screencast

### Setup screenshot
<img width="801" alt="setup" src="https://user-images.githubusercontent.com/28356381/153310566-aafe9a34-ec6d-4b4c-b02a-97a38ecf6542.png">

### List Documentation
<img width="793" alt="list" src="https://user-images.githubusercontent.com/28356381/153310582-69d949e0-a27c-4ac2-917e-fbab31948e3f.png">

### Search in Documentation with Algolia
<img width="790" alt="search" src="https://user-images.githubusercontent.com/28356381/153310584-bbdf96c5-6fc1-4abe-8719-16fda297eba2.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-02-11 05:36 UTC, pernielsentikaer requested changes
Hi @tiagomichaelsousa 🧇 

Awesome extension, thanks for your contribution 🔥 

Can you also provide a light icon? Otherwise, this won't look good with dark theme.

You can find [more info here](https://developers.raycast.com/basics/prepare-an-extension-for-store#extension-icon).

Besides that, well done 💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-11 05:36 UTC, pernielsentikaer commented on extensions/helm-docs/src/documentation/v3.8.0.json
> +      "url": "https://helm.sh/docs/intro/quickstart"
```suggestion
      "url": "https://helm.sh/docs/intro/quickstart/"
```
NIT 😄

2022-02-11 11:48 UTC, pernielsentikaer commented
@tiagomichaelsousa I just checked here: https://github.com/cncf/artwork/tree/master/projects/helm/icon – having it white for dark appearance could solve it, or?

2022-02-11 12:25 UTC, tiagomichaelsousa commented
Having it white for the dark appearance would result in something like this (bellow) but if we can change the icon based on the theme we will still have a problem with the icon that is defined for the command in the `package.json`. 

![Screenshot 2022-02-11 at 12 17 20](https://user-images.githubusercontent.com/28356381/153590846-e9745ad1-5488-4406-a8ab-e5a3850cd16c.png)

I tried to create an icon based on the [Extensions Icon Template](https://www.figma.com/community/file/1030764827259035122) and it resulted in something like this which i think it's the best solution as it works both for raycast light and dark team 😎  wdyt ?

![Screenshot 2022-02-11 at 12 16 58](https://user-images.githubusercontent.com/28356381/153590871-51704f41-bfd3-4ec3-81af-cd31611245d7.png) ![Screenshot 2022-02-11 at 12 24 20](https://user-images.githubusercontent.com/28356381/153590998-3ea2c7d8-f192-4600-add2-937ae025c140.png)

2022-02-11 15:51 UTC, pernielsentikaer commented
Hi @tiagomichaelsousa 🔥 🔥 

Did you know you can add an icon for darkmode?

![bgO6KgQQGcKMb4Ok](https://user-images.githubusercontent.com/38033107/153623336-b5ea1027-5f74-4f49-85d1-e8b89cc2ca63.png)

![G1vRayvWgUGAiMQY](https://user-images.githubusercontent.com/38033107/153623365-e08eee67-4343-4bca-a2ae-6bb15a66ead0.png)

Just add @dark as you can see in the screenshots 🔥

2022-02-11 21:19 UTC, pernielsentikaer commented on extensions/helm-docs/package.json
> +  "description": "Helm documentation",
```suggestion
  "description": "Quickly search Helm documentation",
```

2022-02-11 21:20 UTC, pernielsentikaer approved these changes
Haha, @tiagomichaelsousa! 👋 

with Raycast you always have to expect the unexpected 😄 

I'll share your kudos with the team, I'm very glad that you like it 💪

2022-02-11 21:23 UTC, tiagomichaelsousa commented
Let's see if another idea cross my mind so that I can contribute again

Thank you @pernielsentikaer 🙏

2022-02-14 12:47 UTC, mattisssa approved these changes

2022-02-14 12:47 UTC, merged