Add linkinize extension
raycast/extensions pull request #8531
Opened 2023-09-23 11:20 UTC by hazaveh

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-10-05 11:01 UTC, pernielsentikaer requested changes
- Is there a reason why you don't use preferences for the username and password?

![linkinize 2023-10-05 at 12 48 01](https://github.com/raycast/extensions/assets/38033107/6d319730-e22a-4f3a-a431-a696acafaec5)

- The toast should be with `Failure` style instead

![linkinize 2023-10-05 at 12 48 51](https://github.com/raycast/extensions/assets/38033107/2852f989-c1fb-4e82-956e-55db316fc6d8)

- You should use [metadata image tool](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) to generate metadata

2023-10-05 15:54 UTC, hazaveh commented on extensions/linkinize/package.json
> +      "title": "Linkinize",
Done ✅

2023-10-05 15:54 UTC, hazaveh commented on extensions/linkinize/package.json
> +      "subtitle": "Search through your Bookmarks",
Done ✅

2023-10-09 11:41 UTC, pernielsentikaer requested changes
The login system feels a bit overengineered to me, maybe it's easier just to try with the current cached token, and if there is an error unset it and give the user a failure toast

2023-10-09 11:45 UTC, hazaveh commented
> The login system feels a bit overengineered to me, maybe it's easier just to try with the current cached token, and if there is an error unset it and give the user a failure toast

@pernielsentikaer do you mean getting rid of the AuthComponent that displays the login issue completely? I'm afraid some users do not know how to set their credentials in the preferences.

2023-10-16 11:14 UTC, pernielsentikaer requested changes
It's still lacking a bit since you can also disable commands in preferences, so it might not call the other commands.

Maybe you can use [useFetch](https://developers.raycast.com/utilities/react-hooks/usefetch), which also caches and gives you `isLoading` and `error` out of the box.

In case something goes wrong, I would simply show a toast and tell the user to correct the credentials instead.

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-11-06 11:22 UTC, closed without merging