Add summarize-long-text extension
raycast/extensions pull request #8552
Opened 2023-09-24 17:46 UTC by ajk68

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-09-24 17:48 UTC, ajk68 commented
Not an experienced developer and first Typescript/React project. Looking forward to your feedback.

2023-10-10 07:15 UTC, pernielsentikaer commented
Thanks for taking the time to contribute! 🔥

How does this compare to the other extensions that do the same?

2023-10-10 07:34 UTC, ajk68 commented
This summarizes text that is too long for the context window of gpt. It
summarizes recursively. It is like the summarizes youtube plugin but then
for text in general.

I’m not aware of a plugin that does the same, but lmk if i missed something

Bye, arthur




Sent from my iPhone


On Tue, 10 Oct 2023 at 09:15, Per Nielsen Tikær ***@***.***>
wrote:

> Thanks for taking the time to contribute! 🔥
>
> How does this compare to the other extensions that do the same?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/raycast/extensions/pull/8552#issuecomment-1754560199>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOOWX2V2IQRJOFGG4TZS3ILX6TY23AVCNFSM6AAAAAA5FCRBUGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONJUGU3DAMJZHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-16 11:17 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- This is no toast when there are wrong (or none) credentials

![summarize-long-text 2023-10-16 at 13 16 37](https://github.com/raycast/extensions/assets/38033107/c3d4f0ea-57bc-425a-9b60-195eda1f367c)


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-10-16 11:17 UTC, pernielsentikaer commented on extensions/summarize-long-text/package.json
> +      "required": false
```suggestion
      "required": true
```

2023-10-31 12:14 UTC, ajk68 commented
Hi Per,

Sorry for delay. Was abroad in very remote place. Thanks for your feedback.

I didn't add a toast for this case as i thought it was too much information
for the small and temporary toast, but there is this screen when there is
no openai api token. Didn't you see this?

I didn't want to make the opanai key mandatory as you suggested, because
the default is using Raycast AI, and i didn't want to force users who
already paid for raycast AI to also pay for an openai key.

Can you let me know what you think?

Bye, Arthur


[image: Screenshot 2023-10-31 at 13.06.28.png]

On Mon, Oct 16, 2023 at 1:17 PM Per Nielsen Tikær ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi 👋
>
> Thanks for your contribution 💪
>
> I have now tested your extension, and I have some feedback ready for you:
>
>    - This is no toast when there are wrong (or none) credentials
>
> [image: summarize-long-text 2023-10-16 at 13 16 37]
> <https://user-images.githubusercontent.com/38033107/275485854-c3d4f0ea-57bc-425a-9b60-195eda1f367c.png>
>
> I'm looking forward to testing this extension again 🔥
>
> Request a new review when you are ready. Feel free to contact me here or
> at Slack <https://www.raycast.com/community> if you have any questions.
> ------------------------------
>
> In extensions/summarize-long-text/package.json
> <https://github.com/raycast/extensions/pull/8552#discussion_r1360502731>:
>
> > +          "title": "Very High (1.5)"
> +        },
> +        {
> +          "value": "2",
> +          "title": "Maximum"
> +        }
> +      ],
> +      "required": false
> +    },
> +    {
> +      "name": "openaiApiToken",
> +      "title": "OpenAI API Token",
> +      "description": "Your OpenAI API Token. Required if you choose ChatGPT as your AI.",
> +      "type": "password",
> +      "default": "",
> +      "required": false
>
> ⬇️ Suggested change
>
> -      "required": false
> +      "required": true
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/raycast/extensions/pull/8552#pullrequestreview-1679721683>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOOWX2WJOQ5QYFEHWS3AGGTX7UJUVAVCNFSM6AAAAAA5FCRBUGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMNZZG4ZDCNRYGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-26 10:10 UTC, pernielsentikaer commented on extensions/summarize-long-text/src/summarizeBlocks.tsx
> +      markdown={summary}
In both commands, maybe you can show some other content in <Detail /> if an error occurs, it feels a bit empty 🙂

2023-12-17 11:31 UTC, closed without merging