Add commit-message-generator extension
raycast/extensions pull request #8555
Opened 2023-09-24 21:34 UTC by rokartur

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-10-10 07:21 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-10-10 07:21 UTC, pernielsentikaer commented on extensions/commit-message-generator/README.md
> +whatthecommit.com
Could you add a bit more context here since there is no metadata due to no-view command 🙂

2023-10-10 07:21 UTC, pernielsentikaer commented on extensions/commit-message-generator/package.json
> +    "Developer Tools"
```suggestion
    "Developer Tools",
    "Fun"
```

2023-10-10 07:21 UTC, pernielsentikaer commented on extensions/commit-message-generator/src/generate-random-commit-message.tsx
> +import { setTimeout } from "timers/promises";
```suggestion
import { Clipboard, showHUD, closeMainWindow } from "@raycast/api";
```

2023-10-12 17:48 UTC, rokartur commented
@pernielsentikaer I've made changes

2023-10-16 11:29 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-10-16 11:36 UTC, merged