[Update] [World Clock] Add memo icon
raycast/extensions pull request #8587
Opened 2023-09-27 06:42 UTC by koinzhang

## Description

- Now the Grid view will show the memo icon

## Screencast

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-10-03 10:38 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

Seems like the list and grid don't agree on America/Anchorage - also the list icon shows day but in details it says night 

![world-clock 2023-10-03 at 12 37 00](https://github.com/raycast/extensions/assets/38033107/46bd1f1a-f5ad-48ea-9634-fab5cc7cb75d)
![world-clock 2023-10-03 at 12 36 32](https://github.com/raycast/extensions/assets/38033107/b601d247-c137-4d95-88f9-c2dce0f829c1)


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-10-06 06:00 UTC, koinzhang commented
Hi @pernielsentikaer. The reason for this problem is because you **star** this timezone when the details has not finished loading. The solution is to cancel the **star**, and then **star** again when the detail for this timezone finishes loading.

2023-10-06 06:07 UTC, koinzhang commented
Hi @pernielsentikaer. BTW, I submitted a commit to avoid this issue for now:
Hide actions such as Copy TimeInfo/Star TimeZone when the detailed timezone information has not been loaded

2023-10-16 11:34 UTC, pernielsentikaer approved these changes

2023-10-16 11:42 UTC, merged