Bible extension: Add options to disable references and copyright in the copied results
raycast/extensions pull request #8608
Opened 2023-09-28 17:46 UTC by mskelton

## Description

Adds two new options to the Bible extension to remove references or copyright from the copied results.

## Screencast

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-09-30 15:31 UTC, pernielsentikaer commented
Thanks for your contribution @mskelton 🔥 

Do you mind checking this @josmithua

2023-09-30 19:19 UTC, josmithua commented
Hey @mskelton! Thanks for contributing! I was actually thinking of doing this myself, but never got round to it.

Great changes. I think that either the markdown shown in the view should also reflect the new settings, or the settings should be more clear that they only apply when copying to the clipboard. I'm inclined to do the former, so users know that what they see in the view is what gets copied to the clipboard. Do you agree? If so, could you implement this in `createMarkdown`?

2023-09-30 21:10 UTC, mskelton commented
@josmithua I wasn't sure myself which would be preferred, but I'm fine with doing the same in the markdown as in the clipboard. Updated.

2023-10-03 08:50 UTC, pernielsentikaer commented
Looks like you added the CHANGELOG entry in another extension 🙂

2023-10-04 03:02 UTC, mskelton commented
> Looks like you added the CHANGELOG entry in another extension 🙂

Oops! Thanks for noticing, that's fixed

2023-10-04 05:39 UTC, josmithua requested changes
The changelog should be updated to reflect the changes apply to the search results as well. I put a couple suggestions, feel free to make your own changes. Cheers!

2023-10-04 05:39 UTC, josmithua commented on extensions/bible/CHANGELOG.md
> +- Add options to disable references and copyright in the copied results
```suggestion
- Add options to disable references and copyright in the search results and copied results
```

2023-10-04 05:39 UTC, josmithua commented on extensions/bible/CHANGELOG.md
> +## [Options for copied text] - {PR_MERGE_DATE}
```suggestion
## [Options for results and copied text] - {PR_MERGE_DATE}
```

2023-10-04 13:44 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-10-04 13:44 UTC, merged