feat(extensions): add 1loc
raycast/extensions pull request #863
Opened 2022-02-10 18:05 UTC by kud

## Description

Browse https://1loc.dev/

## Type of change

- New extension

## Screencast

https://cln.sh/Dqva1V9J7SJXGLskWGpe

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-02-11 05:51 UTC, pernielsentikaer requested changes
Hi @kud 💣 

Thanks for an awesome extension, looking forward to use it myself 💯 

Your extensions suffers of [Empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) - could you address this?

I'll do another review when this is corrected 💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-11 05:51 UTC, pernielsentikaer commented on extensions/1loc/package.json
> +      "title": "1loc",
```suggestion
      "title": "Search Javascript Utilities",
      "subtitle": "1LOC",
```
I'm not sure about the title, but something like that should be changed 😄

2022-02-11 05:51 UTC, pernielsentikaer commented on extensions/1loc/package.json
> +      "description": "Browsing 1loc.dev",
```suggestion
      "description": "Browse Favorite JavaScript Utilities from 1LOC - single line of code! No more!",
```

2022-02-11 05:51 UTC, pernielsentikaer commented on extensions/1loc/package.json
> +  "description": "Browsing 1loc.dev",
```suggestion
  "description": "Browsing 1LOC - Favorite JavaScript Utilities in single line of code! No more!",
```

2022-02-15 18:16 UTC, kud commented
Fixed @pernielsentikaer

2022-02-15 20:24 UTC, pernielsentikaer requested changes
Hi @kud 👋 

I think you changed too much 😄 

Could you look into something like the suggested?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-15 20:24 UTC, pernielsentikaer commented on extensions/1loc/package.json
> +  "title": "1loc - JavaScript Utilities in single line of code",
```suggestion
  "title": "1 LOC - JavaScript Utilities in single line of code",
```

2022-02-15 20:24 UTC, pernielsentikaer commented on extensions/1loc/package.json
> +      "title": "1loc - JavaScript Utilities in single line of code",
```suggestion
      "title": "Search JavaScript Utilities",
      "subtitle": "1 LOC"
```

2022-04-05 17:30 UTC, merged

2022-04-05 17:31 UTC, kud commented
Thank you @sxn  :)