WhiteBIT Exchange Extension
raycast/extensions pull request #8647
Opened 2023-10-02 18:36 UTC by marco-whitebit

## Description
WhiteBIT exchange extension for Raycast which uses private API for transfers, code applying, etc and public API for displaying market activity.  

## Screencast
![Screencast](https://github.com/raycast/extensions/assets/146077037/c3c5a29d-916a-45fb-9fcf-b149baab9629)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-10-11 06:46 UTC, pernielsentikaer commented
Hi @marco-whitebit! 👋 

Is there a way to test this extension? Do you have any demo credentials? 🙂

2023-10-11 07:15 UTC, marco-whitebit commented
Hello, you can create account using any email, no KYC required to test extension, you can claim demo token to test Codes or balances. 

After registration you can go to this page and claim it https://whitebit.com/codes/all?demo=true.

Let me know if it makes sense

2023-10-11 08:54 UTC, pernielsentikaer commented
I think it does, I got the token from here, I used the first one

![Raycast-rpeFRtdl@2x](https://github.com/raycast/extensions/assets/38033107/fbfc292d-f7fd-4180-9323-d5619400f509)

And then I got the secret key from here

![Raycast-pPeBKGio@2x](https://github.com/raycast/extensions/assets/38033107/6e221d59-86f9-424c-8864-19e810d97974)

but it seems like it's not working as expected

![whitebit 2023-10-11 at 10 34 43](https://github.com/raycast/extensions/assets/38033107/75524f35-22a1-4c55-bd11-b514b7168ae4)

Also, we should aim to die gracefully instead of crashing 🙂

Are you working at whitebit, feel free to DM me to help 🙂

2023-10-11 08:56 UTC, pernielsentikaer commented on extensions/whitebit/package.json
> +      "title": "Sercey Key",
```suggestion
      "title": "Sercet Key",
```

2023-10-11 09:54 UTC, marco-whitebit commented
Thank you for your review, will add try..catch for HTTP exception. 

Can you please confirm that you enabled all endpoints described in README file and put the secret key and public key correctly? Currently it's a little bit confusing on our UI, firstly you will see a secret key and second is public, we gonna change the order of fields soon to make it more friendly :)

2023-10-11 20:44 UTC, marco-whitebit commented
@pernielsentikaer sure, i will DM you in slack asap

2023-10-16 09:34 UTC, marco-whitebit commented
@pernielsentikaer i sent DM in Slack

2023-10-16 11:44 UTC, pernielsentikaer commented
Still struggling here, DM'ed you 🙂

2023-10-17 09:54 UTC, marco-whitebit commented
Hello, @pernielsentikaer, added `catch` to avoid throwing errors and handle it with alert.

2023-10-23 09:47 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Apply Codes command should probably be a no-view command instead

#### General
 - Lists should have an `isLoading` property, maybe you can use [useCachedPromise](https://developers.raycast.com/utilities/react-hooks/usecachedpromise) - this also gives you {`data`, `isLoading`, `error`} out of the box
 - Don't change the navigationTitle in the root command - it will be automatically set to the command name. Use navigationTitle only in nested screens to provide additional context.

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-10-24 07:26 UTC, marco-whitebit commented
Hello, @pernielsentikaer. Thank you for review, i made all requested changes.

2023-10-25 08:20 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-10-25 15:01 UTC, merged