datadog notebooks, monitors and customizable domain
raycast/extensions pull request #865
Opened 2022-02-10 23:35 UTC by aexvir

## Description

This merge request adds two new commands, allowing to list [notebooks](https://docs.datadoghq.com/notebooks/) and [monitors](https://docs.datadoghq.com/monitors/) along with their status; as well as allowing custom domains for generating the link to view resources in the browser, which is part of some enterprise plans.

## Type of change

- Bug fix / improvement for somebody else's extension. Extension author: @kudrykv

## Screencast

<img width="862" alt="Screenshot 2022-02-11 at 00 33 01" src="https://user-images.githubusercontent.com/8055505/153514929-5f0650eb-237e-441e-8d27-8c6442ebd990.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-02-11 12:14 UTC, pernielsentikaer commented
Awesome @aexvir 🔥 

 Could you test it out @kudrykv and give some feedback?

2022-02-11 13:36 UTC, kudrykv commented
## Monitors
Monitors are weird — some tags work, some don't. I wonder whether this is an issue of Datadog itself. Here, it shows results for the given tag:
![CleanShot 2022-02-11 at 15 22 21@2x](https://user-images.githubusercontent.com/12697803/153599541-ab34692e-eef1-40b2-94e2-ddfa60604446.png)

And here it doesn't:
![CleanShot 2022-02-11 at 15 23 03@2x](https://user-images.githubusercontent.com/12697803/153599808-083733ee-1419-4eeb-8c8b-33174aa6a57d.png)

## Notebooks
Notebooks don't work for me for some reason:
<img width="862" alt="CleanShot 2022-02-11 at 15 30 59@2x" src="https://user-images.githubusercontent.com/12697803/153600158-6c4b5f87-4211-4aea-a347-6bb3e1f470f4.png">
In console I get tons of `could not deserialize` errors.
<details>
<summary>Errors snippet</summary>

```
...
2022-02-11 15:17:08.305 Db Raycast[22145:d30b31] [com.raycast.extensions.raycast-datadog:command-list-notebooks] could not deserialize NotebookRelativeTime (Error: missing required property 'liveSpan')
2022-02-11 15:17:08.306 Db Raycast[22145:d30b31] [com.raycast.extensions.raycast-datadog:command-list-notebooks] could not deserialize NotebookRelativeTime (Error: missing required property 'liveSpan')
2022-02-11 15:17:08.306 Db Raycast[22145:d30b31] [com.raycast.extensions.raycast-datadog:command-list-notebooks] could not deserialize NotebookRelativeTime (Error: missing required property 'liveSpan')
2022-02-11 15:17:08.306 Db Raycast[22145:d30b31] [com.raycast.extensions.raycast-datadog:command-list-notebooks] could not deserialize NotebookMarkdownCellAttributes (Error: missing required property 'text')
2022-02-11 15:17:08.306 Db Raycast[22145:d30b31] [com.raycast.extensions.raycast-datadog:command-list-notebooks] could not deserialize FormulaAndFunctionApmDependencyStatsQueryDefinition (Error: missing required property 'env')
2022-02-11 15:17:08.306 Db Raycast[22145:d30b31] [com.raycast.extensions.raycast-datadog:command-list-notebooks] could not deserialize FormulaAndFunctionApmResourceStatsQueryDefinition (Error: missing required property 'env')
2022-02-11 15:17:08.306 Db Raycast[22145:d30b31] [com.raycast.extensions.raycast-datadog:command-list-notebooks] could not deserialize FormulaAndFunctionEventQueryDefinition (Error: missing required property 'compute')
...
```

</details>

Missing required property 'id' error:
```
Error: missing required property 'id'
    at Function.ObjectSerializer2.deserialize (/Users/bgnfu7re/develop/projects/raycast-extensions/extensions/datadog/node_modules/@datadog/datadog-api-client/packages/datadog-api-client-v1/models/ObjectSerializer.ts:1753:17)
    at Function.ObjectSerializer2.deserialize (/Users/bgnfu7re/develop/projects/raycast-extensions/extensions/datadog/node_modules/@datadog/datadog-api-client/packages/datadog-api-client-v1/models/ObjectSerializer.ts:1692:28)
```

2022-02-11 13:41 UTC, aexvir commented
hmm... I wonder if it has something to do with the scope of the tokens... both features work fine for me 🤔 
btu yeah, good point, I didn't really add any graceful handling to these features, I was just relying on the datadog client's error handling 😅 

will take a look and fix this a bit later
thanks for checking!

2022-02-11 14:51 UTC, kudrykv commented
@aexvir, thank you!
I've just realized another point. It would be great to cache the notebook response for a while, like 1-5 minutes or so. They don't change frequently, and it would be nice to have them in an instant. After the cache expires, you can still show it until a new fetch happens, and refresh it afterward.

2022-02-11 15:25 UTC, aexvir commented
funny enough I was thinking about exactly that as my next contribution, but for dashboards 😄️ 
no sure what's the usage pattern for notebooks, but I personally use them *a lot* so they do change quite often on my case
but yeah, a couple minutes latency shouldn't be that bad (maybe configurable?) I need to check how caching works on raycast either way

but I'd definitely keep that outside of this pr if you don't mind, let's keep this one small

2022-02-11 18:37 UTC, aexvir commented
small screenshot for the notebooks as well, just to show how does it look
I'd like to put more screenshots but it's annoying to have to blur so much data 😅 

<img width="862" alt="Screenshot 2022-02-11 at 19 34 10" src="https://user-images.githubusercontent.com/8055505/153649829-197f6007-ed5c-4e7e-b9fe-ad41f9922ad9.png">

2022-02-11 21:52 UTC, pernielsentikaer commented
Awesome @aexvir 💪 

Sorry to bother you all the time @kudrykv – could you take a new look?

2022-02-12 07:39 UTC, kudrykv commented
No problem checking at all 🙂
Yesterday was a busy day. Going to check it sometime today

2022-02-12 10:35 UTC, kudrykv approved these changes
Awesome ❤️
Thank you @aexvir, it is great!

2022-02-12 10:38 UTC, kudrykv commented
> no sure what's the usage pattern for notebooks, but I personally use them a lot so they do change quite often on my case

Do you create notebooks often?

> funny enough I was thinking about exactly that as my next contribution, but for dashboards 😄️ those are really static on our case

Yeah, that makes sense, too!

2022-02-14 17:43 UTC, aexvir commented
> Do you create notebooks often?
yep! 😅 maybe I'm overusing them, but I make a notebook pretty much every time I need to check a metric, as I find it much better than the metrics page

@pernielsentikaer anything else missing in order to get this merged?

2022-02-15 20:38 UTC, pernielsentikaer requested changes
Hi @aexvir 👋 

Now that @kudrykv accepted, we only some naming convention left, and then I think we're ready to proceed to final stage 🚀

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-15 20:38 UTC, pernielsentikaer commented on extensions/datadog/package.json
> +      "title": "List notebooks",
```suggestion
      "title": "List Notebooks",
```

2022-02-15 20:38 UTC, pernielsentikaer commented on extensions/datadog/package.json
> +      "title": "List monitors",
```suggestion
      "title": "List Monitors",
```

2022-02-17 14:28 UTC, aexvir commented
addressed and re-requested review

2022-02-17 20:48 UTC, pernielsentikaer commented
For me it looks awesome 🔥 , can you give it a last spin @kudrykv (Since a new preference is added) - Could you help me verify that it works as expected?

2022-02-18 08:37 UTC, aexvir commented
@kudrykv yep, more or less

our enteprise plan has a custom subdomain domain where our engineers access datadog's ui, you can read more about it on [datadog's documentation](https://docs.datadoghq.com/account_management/multi_organization/), and indeed, the api servers are the same ones as for everyone else

so while I can fetch data from our organization via api, when opening the links in the background I need to add the custom domain, otherwise I won't be able to log in and view the resources straight away

2022-02-18 08:39 UTC, kudrykv commented
Ah, cool! Thank you for explaining it!

2022-02-18 08:39 UTC, kudrykv approved these changes

2022-02-19 07:21 UTC, pernielsentikaer approved these changes
Hi @aexvir 👋 

I'm also going to approve it, let's await final review 💪

2022-02-21 08:28 UTC, mathieudutour approved these changes
👏

2022-02-21 08:28 UTC, merged