[word-search] Capitalize output when search text is capitalize
raycast/extensions pull request #8705
Opened 2023-10-06 19:20 UTC by bkeys818

## Description

When the search text is capitalized, the copied/pasted word will also be capitalized.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-10-11 10:26 UTC, pernielsentikaer commented
Hi @bkeys818 👋 

Thanks for your contribution 🔥 

Wouldn't it make sense to uppercase in the list too, now that it's done in the actions?

@RishabSwift do you mind checking this

2023-10-12 12:21 UTC, bkeys818 commented
@pernielsentikaer, Can't hurt

2023-10-12 14:19 UTC, pernielsentikaer commented
@RishabSwift  do you have time to check?

2023-10-12 14:21 UTC, RishabSwift commented
Thanks for the feature! Will check it out in a few hours

2023-10-15 22:08 UTC, RishabSwift commented
@bkeys818 I just tried it out.

Doesn't seem to work?

![Screenshot 2023-10-15 at 18 04 31@2x](https://github.com/raycast/extensions/assets/15897093/6c721bf6-1ac2-4bbe-a5ff-5498ee29f40c)

It is not capitalizing the list nor the actions for me (like when I copy or paste in active app).

2023-10-15 22:14 UTC, RishabSwift requested changes

2023-10-15 22:14 UTC, RishabSwift commented on extensions/word-search/src/search-results.tsx
> +          const wordString = searchIsCapitalized ? word.word[0] + word.word.slice(1) : word.word;
This logic is not capitalizing the word.

Try this instead:

    const wordString = searchIsCapitalized ? word.word.charAt(0).toUpperCase() + word.word.slice(1) : word.word;

2023-10-15 22:17 UTC, RishabSwift commented on extensions/word-search/src/search-results.tsx
> +          const wordString = searchIsCapitalized ? word.word[0] + word.word.slice(1) : word.word;
```suggestion
          const wordString = searchIsCapitalized ? word.word.charAt(0).toUpperCase() + word.word.slice(1) : word.word;
```

2023-10-18 16:55 UTC, frntline-dev commented
@bkeys818, I think it's preferable to capitalize the words as they are extracted from the request response in the API file rather than in the search results. This approach keeps everything consolidated in one location and avoids the need to manipulate the render method. 

What do you think?

2023-10-19 14:43 UTC, bkeys818 commented
@frntline-dev, I'd probably help to explain why I suggested this change.

I use to use [Alfred 5](https://www.alfredapp.com), which had "[spell](https://www.alfredapp.com/help/features/dictionary/#spell)", a similar functionally to this extension. One of my favorite features was that it would match the case of the original word.

When I use this extension, I'll copy a word I'm unsure is spelled right and call the extension. Then, I select the correct word which replaces the original. When the misspelled is the first word in a sentence (aka. capitalized), the corrected spelling always appears all lowercase. That means I have to go back and re-capitalize it every time.

I acknowledge that it's a minor annoyance, but I think the fix is justified since it's insignificant. That's just my opinion. I'd love to hear what other people think.

2023-10-23 05:16 UTC, pernielsentikaer commented
We could also make it a preference if it should happen or not and then lease default behavior as today and make a toggle for it 🙂

2023-10-23 07:09 UTC, RishabSwift commented
@bkeys818 I think there's a better way to achieve the capitalization of the first letter.

For example, in the `api.ts`, you could simply do the following at the last block of code that parses the definition of each word search result (`line 28`)

```
words.forEach((word) => {
   ...

    // if wordToSearch is capitalized, capitalize the first letter of the word
    if (wordToSearch[0] === wordToSearch[0].toUpperCase()) {
        word.word = word.word[0].toUpperCase() + word.word.slice(1);
    }

   ...
});
```

This centralizes the logic, ensuring the `tsx` file remains clean and focused on rendering.

I think this is a better way to go about it, don't you think?

2023-10-23 14:15 UTC, bkeys818 commented
@RishabSwift, that is an excellent idea. I'll get it done right now.

2023-10-25 08:02 UTC, pernielsentikaer commented
Can you check it again @RishabSwift

2023-10-26 05:56 UTC, RishabSwift commented
Looks great @bkeys818! Thanks for taking the time 💯

2023-10-26 05:56 UTC, RishabSwift commented
> Can you check it again @RishabSwift

All looks well!

2023-10-30 09:09 UTC, pernielsentikaer commented
Awesome, thanks 🔥

2023-10-30 09:24 UTC, merged