✨roblox-games: added
raycast/extensions pull request #871
Opened 2022-02-11 11:53 UTC by TayIorRobinson

## Description

Add the Roblox Places plugin: Allows users to launch the Roblox platform from Raycast.

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/74316107/153586557-feda6393-91ad-445a-8ffe-380db5acb641.mov

)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-02-14 14:12 UTC, mattisssa requested changes
Hey! I got an issue when I tried to run your extension.

1) Can we make a more proper text here in the error so users can understand what has happened?
2) Once the error happens, the loading indicator should be stopped 😉 
![CleanShot 2022-02-14 at 14 05 38@2x](https://user-images.githubusercontent.com/15333662/153879043-e5c94883-ec7b-4769-a245-9938ee2e5e14.png)

I also left a few suggestions below, please take a look at them

2022-02-14 14:12 UTC, mattisssa commented on extensions/roblox-games/package.json
> +      "title": "Launch Roblox",
Judging by the screencast it seems like the command is more about games and searching for it. Should it be called something like
```suggestion
      "title": "Search Games",
```
?

2022-02-14 14:12 UTC, mattisssa commented on extensions/roblox-games/package.json
> +      "description": "Searches for & launches Roblox places",
```suggestion
      "subtitle": "Roblox",
      "description": "Searches for & launches Roblox places",
```

2022-02-14 14:12 UTC, mattisssa commented on extensions/roblox-games/package.json
> +      "title": "Accessory displays",
```suggestion
      "title": "Accessory Displays",
```

2022-02-14 14:12 UTC, mattisssa commented on extensions/roblox-games/src/auth.ts
> +const configPath = homedir() + "/Library/Preferences/com.roblox.RobloxStudioBrowser.plist";
My main issue is that I don't have this file 😉

2022-02-15 13:46 UTC, mattisssa approved these changes

2022-02-15 13:55 UTC, mattisssa commented
Hey @TayIorRobinson, seems like you have some prettier issues with your extension, could you please take a look at that?

Try to use this in `.eslintrc.json`:
```
{
  "root": true,
  "env": {
    "es2020": true,
    "node": true
  },
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint"],
  "extends": ["eslint:recommended", "plugin:@typescript-eslint/recommended", "prettier"]
}
```

You have also a wrong Promise usage in the search file, at the place where you have `async`.

2022-02-15 13:57 UTC, mattisssa requested changes
Hey! I got a few issues during the review, please take a look at my comments below

2022-02-15 13:57 UTC, mattisssa commented on extensions/roblox-games/.eslintrc.json
> +}
```suggestion
{
  "root": true,
  "env": {
    "es2020": true,
    "node": true
  },
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint"],
  "extends": ["eslint:recommended", "plugin:@typescript-eslint/recommended", "prettier"]
}
```

2022-02-15 13:57 UTC, mattisssa commented on extensions/roblox-games/src/search.ts
> +  return (sortToken = new Promise(async (resolve, reject) => {
I got the issue here for `async` usage. Could you take a look at this?

2022-02-17 23:45 UTC, merged

2022-02-17 23:47 UTC, TayIorRobinson commented
🚀 🎉 

Thanks for all your help @mattisssa!