add BetterDiscord-Store
raycast/extensions pull request #881
Opened 2022-02-12 08:28 UTC by TheCommieAxolotl

## Description

An extension to search through the [BetterDiscord](https://betterdiscord.app/) store
(partially based off elm-search extension)

## Screencast

https://user-images.githubusercontent.com/87679354/153703579-4a698ad9-cd3d-4227-811f-769a49c34b5a.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-02-14 22:24 UTC, pernielsentikaer requested changes
Hi @TheCommieAxolotl 👋 

Thanks for your contribution 💪 

I have some feedback ready for you to address:

- Avoid having a list of actions where some have icons and some don't

- An idea could be to add a bit more data to the list, maybe like this:

![k3YHEl12b1EAv6Eh](https://user-images.githubusercontent.com/38033107/153955958-b62c180b-5a2c-4772-9cc0-e813c481cddd.png)

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-14 22:24 UTC, pernielsentikaer commented on extensions/betterdiscord-search/package.json
> +  "description": "Allows you to search and view BetterDiscord Addons inside Raycast",
```suggestion
  "description": "Allows you to search and view BetterDiscord addons inside Raycast",
```

2022-02-14 22:24 UTC, pernielsentikaer commented on extensions/betterdiscord-search/package.json
> +      "description": "Search for a BetterDiscord Addon by Name",
```suggestion
      "description": "Search for a BetterDiscord addon by name",
```

2022-02-14 22:24 UTC, pernielsentikaer commented on extensions/betterdiscord-search/src/index.tsx
> +import { Detail, showToast, Toast, Image, Icon, useNavigation, Action, ActionPanel, List } from "@raycast/api";
```suggestion
import { Detail, showToast, Toast, Icon, useNavigation, Action, ActionPanel, List } from "@raycast/api";
```

2022-02-14 22:24 UTC, pernielsentikaer commented on extensions/betterdiscord-search/src/index.tsx
> +  const { state, search } = useSearch();
```suggestion
  const { push } = useNavigation();
  const { state } = useSearch();
```
Unused constants?

2022-02-14 22:24 UTC, pernielsentikaer commented on extensions/betterdiscord-search/src/index.tsx
> +  const params = new URLSearchParams();
```suggestion
  const params = new URLSearchParams();
```
Leftover or forgotten?

2022-02-14 22:56 UTC, TheCommieAxolotl commented
Thanks for the review!

Would this list/action be better?

<img width="757" alt="1" src="https://user-images.githubusercontent.com/87679354/153960511-e49f6470-8b9b-483e-a915-f0b36edbd02c.png">

2022-02-15 21:22 UTC, pernielsentikaer commented
Hi @TheCommieAxolotl 👋 

It seems like you have a Prettier code style error, can you please format the code with Prettier?

The icon look very nice, let's use that (and the download part) 😄 💪

2022-02-17 08:53 UTC, pernielsentikaer requested changes
Awesome, it turned out very nice 🔥 

Last correction and we're good to go, very nice @TheCommieAxolotl 💪

2022-02-17 08:53 UTC, pernielsentikaer commented on extensions/betterdiscord-search/src/index.tsx
> +        }
I think this should be removed, everywhere is escape used, and we would like to keep it simple and the same – would you mind removing this?

2022-02-17 21:08 UTC, TheCommieAxolotl commented
Thanks, i've removed the action so it should all be good now 👍🏻

2022-02-18 05:04 UTC, pernielsentikaer approved these changes
Thanks for the update @TheCommieAxolotl 🔥 

I'm going to accept it right away! 💪 

Thanks for your contribution 💯

2022-02-21 08:30 UTC, mathieudutour approved these changes

2022-02-21 08:30 UTC, merged