Add mailtrap-subject-copier extension
raycast/extensions pull request #8819
Opened 2023-10-16 11:08 UTC by samjwillis97

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-10-18 10:17 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you

Is there a reason why this only focuses on the subject? Wouldn't it be nice if it were a MailTrap extension instead?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-10-18 10:17 UTC, pernielsentikaer commented on extensions/mailtrap-subject-copier/src/views/list-inboxs.tsx
> +              <Action.Push title="Open Inbox" target={<ListEmailsView inboxId={inbox.id} />} />
Missing an icon 🙂

2023-10-19 09:35 UTC, samjwillis97 commented
Thanks for the review 😊 I'll get those changes sorted very soon.

Also, I do agree this would ideally be a more general Mailtrap extension and that was my intentions when starting this, though as I was building I realised the only use I had was copying the subject and wasn't entirely sure what other commands would be useful to people 😅

I just really wanted to get something published and I'm more than happy to take on suggestions to expand this further!

2023-10-23 08:57 UTC, pernielsentikaer commented
We can indeed make an initial version that can be expanded later on, but I would think we should add the correct name from start and maybe in the README describe what would be added later on (or missing)

2023-10-24 10:39 UTC, samjwillis97 commented
Sounds good, so should I go with the name Mailtrap then? and explain reasoning etc. in the README?

2023-10-25 11:16 UTC, pernielsentikaer commented
I would do that, it's okay that features are missing 🙂

2023-10-29 21:45 UTC, samjwillis97 commented
Thanks for fixing up that API key field, is the updated README alright?

2023-10-30 09:41 UTC, merged