jing-dong-code: add new extension
raycast/extensions pull request #884
Opened 2022-02-12 16:54 UTC by zooPanda

## Description
For generation or parsing the JD code

## Screencast
![](https://github.com/zooPanda/extensions/raw/main/extensions/jing-kou-ling/media/enjcode.png)

![](https://github.com/zooPanda/extensions/raw/main/extensions/jing-kou-ling/media/dejcode.png)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-02-14 22:40 UTC, pernielsentikaer requested changes
Hi @zooPanda 👋 

Thanks for your contribution 💪 

At the moment, Raycast doesn't support localization and only supports US English – could you please correct this, so everything inside the extension is US English

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-15 07:05 UTC, zooPanda commented
> Hi @zooPanda 👋
> 
> Thanks for your contribution 💪
> 
> At the moment, Raycast doesn't support localization and only supports US English – could you please correct this, so everything inside the extension is US English
> 
> Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

it  was parsed into US English .

2022-02-15 21:35 UTC, pernielsentikaer requested changes
Hi @zooPanda 👋 

I have some feedback ready for you to address 💪 

- The panda is pretty hard to spot, could you enlarge the panda a bit, so it's possible to see? I think the logo works with both with and dark background, but let's see when you enhance it.

- Tried to encode something but only gets errors, do you have something I can try to input that works?

- Could you update(translations) and move screenshots to a folder in the root called `media`

- Consider adding a README 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-15 21:35 UTC, pernielsentikaer commented on extensions/jing-kou-ling/package.json
> +      "subtitle": "generate JD code",
Use subtitles to add context to your command. Usually, it's an app or service name that you integrate with. It makes command names more lightweight and removes the need to specify a service name in the command title.

2022-02-15 21:35 UTC, pernielsentikaer commented on extensions/jing-kou-ling/package.json
> +      "subtitle": "parse JD code",
Use subtitles to add context to your command. Usually, it's an app or service name that you integrate with. It makes command names more lightweight and removes the need to specify a service name in the command title.

2022-02-15 21:35 UTC, pernielsentikaer commented on extensions/jing-kou-ling/src/dejcode.tsx
> +          <Action.CopyToClipboard title="复制到剪贴板" content={`${value}`} />
Needs to be translated to US English too

2022-02-15 21:35 UTC, pernielsentikaer commented on extensions/jing-kou-ling/src/enjcode.tsx
> +            <Action.SubmitForm onSubmit={handleSubmit} title="生成" />
Needs to be translated to US English too

2022-02-17 18:43 UTC, pernielsentikaer requested changes
Hi @zooPanda 👋 

Thanks for the updates 🔥 

I have some questions and suggestions for you 🐼 

1) What is a JD code, I simply don't understand it and I can't figure out what to search for
2) When generation of a JD succeed, you could consider popping to [root](https://developers.raycast.com/api-reference/window-and-search-bar#poptoroot)

Maybe a few more questions will follow when I fully understand what's happening 😄

2022-02-17 18:43 UTC, pernielsentikaer commented on extensions/jing-kou-ling/package.json
> +      "title": "generate JD code",
```suggestion
      "title": "Generate JD Code",
```

2022-02-17 18:43 UTC, pernielsentikaer commented on extensions/jing-kou-ling/package.json
> +      "description": "use your custom title and url to generate JD code",
```suggestion
      "description": "Generate a JD code using your custom title and url",
```

2022-02-17 18:43 UTC, pernielsentikaer commented on extensions/jing-kou-ling/src/enjcode.tsx
> +        <Form.TextField id="title" title="title" placeholder="please enter your title " />
```suggestion
        <Form.TextField id="title" title="title" placeholder="Please enter your title " />
```

2022-04-05 18:46 UTC, fe9lix commented
Hey guys, I'm closing this because of inactivity. Feel free to reopen later and address the feedback.

2022-04-05 18:46 UTC, closed without merging