add facetime extension
raycast/extensions pull request #890
Opened 2022-02-13 19:54 UTC by ron-myers

## Description

Add Facetime extension that can setup calls in Facetime.  Per #869 

## Screencast

https://user-images.githubusercontent.com/10678906/153772266-9745e451-dc8b-4412-8f85-19384a33dd6d.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-02-13 21:56 UTC, ron-myers commented
I have the start of a contact search to add to this but will wait until after this is reviewed / accepted to layer in that feature.

2022-02-15 19:59 UTC, pernielsentikaer requested changes
Hi @ron-myers 👋 

I have now checked your contribution and I have some feedback for you:

- The provided logo in the extension is not provided in 512×512 pixels. Please modify this according to [Extension Icon guideline](https://developers.raycast.com/basics/prepare-an-extension-for-store#extension-icon)

- Instead of a form with a default value, it would be cool if was a list instead where it was possible to add/remove “contacts” 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-15 19:59 UTC, pernielsentikaer commented on extensions/facetime/package.json
> +      "subtitle": "Facetime",
```suggestion
```
Redundant subtitle

2022-02-16 06:47 UTC, pernielsentikaer requested changes
Hi @ron-myers 👋 

Sounds like a plan, and yes, we can add more functionality in a later version for sure 💪 

What I would like to get added in this version is a preference to set a default number instead, then it's possible to leave blank too 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-16 06:47 UTC, pernielsentikaer commented on extensions/facetime/package.json
> +  "title": "Facetime",
```suggestion
  "title": "FaceTime",
```

2022-02-16 06:47 UTC, pernielsentikaer commented on extensions/facetime/package.json
> +  "description": "Make Facetime calls with Raycast",
```suggestion
  "description": "Make FaceTime calls with Raycast",
```

2022-02-16 06:47 UTC, pernielsentikaer commented on extensions/facetime/package.json
> +      "title": "Facetime Call",
```suggestion
      "title": "FaceTime Call",
```

2022-02-16 06:47 UTC, pernielsentikaer commented on extensions/facetime/package.json
> +      "description": "Opens Facetime ready to make a call",
```suggestion
      "description": "Opens FaceTime ready to make a call",
```

2022-02-17 05:11 UTC, pernielsentikaer requested changes
Hi @ron-myers 👋 

Last one to change before we can accept the first version 🔥 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-17 05:11 UTC, pernielsentikaer commented on extensions/facetime/src/call.tsx
> +      <Form.TextField id="number" title="Number" placeholder="Enter text" defaultValue="" />
```suggestion
      <Form.TextField id="number" title="Number" placeholder="Enter number" defaultValue="" />
```

2022-02-17 13:09 UTC, ron-myers commented
Appreciate all of your feedback @pernielsentikaer

2022-02-17 20:38 UTC, pernielsentikaer approved these changes
Hi @ron-myers 🔥 

Thanks for the corrections, it's a very nice first version—already looking forward to the next version 😄 

Accepted! 🚀

2022-02-21 08:31 UTC, mathieudutour approved these changes
Looking good :+1:

2022-02-21 08:32 UTC, merged

2022-02-24 15:56 UTC, afanjul commented
Hi @ron-myers , I have tested the app you did (catching my suggestion) but my problem is that the Call is not made using my iPhone, but using FaceTime... My first intention (and suggestion) was to have an easy way to call somebody with a "normal voice call" using my iPhone (and Handoff technology). I suggested that, because in deed it's pretty awful (poor UX) to make it through FaceTime.
Time ago I had a "dial pad" app that worked pretty well: https://www.theverge.com/2014/10/21/7028427/the-phone-dialer-apple-should-have-included-with-yosemite but now I think it's outdated, and I only can easily take calls from my Mac, but not make them...

could you add that feature?
thanks

2022-02-26 20:54 UTC, pernielsentikaer commented
Hi @afanjul 👋 

Could you please add it as an [API Feature Request](https://github.com/raycast/extensions/issues/new?assignees=&labels=api%2C+feature+request&template=api_feature_request.md&title=), so it's not left just here 😄