Add outline-page extension
raycast/extensions pull request #8925
Opened 2023-10-23 18:31 UTC by praveenjuge

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-10-25 09:35 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- metadata images don't support `gifs`, and the other metadata image doesn't bring any contextual value - the GIF can be added in README but I would skip the other image

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-10-25 12:57 UTC, praveenjuge commented
@pernielsentikaer Update the images!

2023-11-15 13:08 UTC, pernielsentikaer commented
Checking again now @praveenjuge

2023-11-15 13:14 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-11-15 13:25 UTC, merged