Add uk-bank-holidays extension
raycast/extensions pull request #8938
Opened 2023-10-24 18:03 UTC by kud

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-11-08 11:24 UTC, kud commented
@pernielsentikaer :D

2023-11-22 11:44 UTC, pernielsentikaer requested changes
What! Sorry @kud - I forgot to hit the submit review button here 😞

2023-12-06 13:30 UTC, kud commented
Yeah yeah, did not have time to do it yet :D

2023-12-28 00:20 UTC, kud commented on extensions/uk-bank-holidays/package.json
> +      "mode": "view"
@pernielsentikaer I'm not sure to understand what you actually mean?

2024-02-01 15:15 UTC, kud commented
Yeah need to work on this :D

2024-02-09 23:24 UTC, kud commented
poke @pernielsentikaer

2024-02-12 07:12 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-02-12 07:25 UTC, merged

2024-02-12 16:14 UTC, kud commented
🎉