Add naver-search extension
raycast/extensions pull request #895
Opened 2022-02-14 03:57 UTC by kw-lee

## Description

An extension for [Naver](https://naver.com) search with autosuggestions.
This extension is inspired by [alfnaversearch : Naver Search Workflow for Alfred](https://github.com/Kuniz/alfnaversearch).

## Screencast

<img width="862" alt="search" src="https://user-images.githubusercontent.com/17693194/153797434-248d3007-c8ef-4274-83a7-e68f6bd5025b.png">
<img width="862" alt="shopping" src="https://user-images.githubusercontent.com/17693194/153797442-ae1e8111-9cbb-429e-8990-8b5c8bfdbe4a.png">
<img width="862" alt="endic" src="https://user-images.githubusercontent.com/17693194/153797455-376a186b-f6a3-4d98-88ff-e9a2beaff7fc.png">
<img width="862" alt="krdic" src="https://user-images.githubusercontent.com/17693194/153797465-1ff5ad48-47fd-4aa0-a32a-1be1c785fee1.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-02-15 20:15 UTC, pernielsentikaer requested changes
Hi @kw-lee 👋 

Thanks for your contribution 💪 

I have some feedback ready for you to address:

- Could you move all screenshots to a folder called `media` in the root and update the README.

- The commands should have `"subtitle": "Naver",` but struggling a bit with matching titles, can you look into this?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-15 20:15 UTC, pernielsentikaer commented on extensions/naver-search/src/search-api.ts
> +    url = `http://ac.search.naver.com/nx/ac?q_enc='utf-8'&q=${wordToSearch}&st=100&r_lt=100`;
```suggestion
    url = `https://ac.search.naver.com/nx/ac?q_enc='utf-8'&q=${wordToSearch}&st=100&r_lt=100`;
```

2022-02-15 20:15 UTC, pernielsentikaer commented on extensions/naver-search/src/search-dict-results.tsx
> +    baseurl = `http://endic.naver.com/search.nhn?ie=utf8&query=`;
```suggestion
    baseurl = `https://endic.naver.com/search.nhn?ie=utf8&query=`;
```

2022-02-15 20:15 UTC, pernielsentikaer commented on extensions/naver-search/src/search-dict-results.tsx
> +    baseurl = `http://krdic.naver.com/search.nhn?kind=all&query=`;
```suggestion
    baseurl = `https://krdic.naver.com/search.nhn?kind=all&query=`;
```

2022-02-16 03:15 UTC, kw-lee commented
Thanks for your feedback!
I reflect the feedback you sent, and add Chinese character dictionary.

2022-02-17 18:24 UTC, pernielsentikaer reviewed
Hi @kw-lee 👋 

Much better 🔥 It's shaping out really nice 🚀 

I have some comments for you:

- The “Search” command, can we add `word` to the title, or what does it search for?

- At least “Shopping” is not encoding spaces (as “Search” does)  could you check it out?

- What can I search for with "Krdic" "Handic" and "Endic" to get a match?

2022-04-05 18:52 UTC, fe9lix commented
Hey guys, I'm closing this because of inactivity. Feel free to reopen later again and address the feedback.

2022-04-05 18:52 UTC, closed without merging