Add time-logger extension
raycast/extensions pull request #9069
Opened 2023-11-02 06:15 UTC by aramikuto

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-11-03 13:40 UTC, pernielsentikaer requested changes
How do you use this, could you make a screencast for a better understanding about why it's adding hours to a google calendar event 🙂

2023-11-03 13:40 UTC, pernielsentikaer commented on extensions/time-logger/src/gcalTimeLogger.tsx
> +                        title="Delete This Epic"
```suggestion
                        title="Delete This Epic"
                        style={Action.Style.Destructive}
```

2023-11-03 13:40 UTC, pernielsentikaer commented on extensions/time-logger/src/gcalTimeLogger.tsx
> +                        title="Delete This Epic"
You can also combine it with a [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert#confirmalert)

2023-11-03 13:40 UTC, pernielsentikaer commented on extensions/time-logger/src/gcalTimeLogger.tsx
> +                  />
Hide this when there is nothing in the search bar

2023-11-03 13:40 UTC, pernielsentikaer commented on extensions/time-logger/src/gcalTimeLogger.tsx
> +                  />
What does this do? Nothing happens

2023-11-03 13:40 UTC, pernielsentikaer commented on extensions/time-logger/src/gcalTimeLogger.tsx
> +                      />
Not sure what this does?

2023-11-06 02:50 UTC, aramikuto commented
@pernielsentikaer Thank you very much for the review. I have addressed the code review problems and reworked logic to make the interface more easy to understand.

I also added extension general information to the readme file:

> This extension is designed to help you log your work on specific epics in Google Calendar. It creates events with the activity name, start time, and end time.
> 
> 1. Register the names of the epics or activities you are working on. To add a new epic, press `⌘ + N`.
> 2. Before starting work on an activity you want to log in Google Calendar, press Enter on that activity in the list. The start time will appear on the right.
> 3. Once you're done with the work, press Enter on the activity you were working on. This action will open the Google Calendar event creation with necessary information filled in.

2023-11-06 11:13 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-11-06 11:26 UTC, merged