jjhok-parcel-tracker extension
raycast/extensions pull request #920
Opened 2022-02-16 08:23 UTC by jjhok

## Description

This extension is tracker packages by tracking number
(송장번호를 통한 택배 추적용 익스텐션입니다.)

## Screencast

![image](https://user-images.githubusercontent.com/13160786/154224039-c093c47a-5b5c-452c-b48d-4d1ea89c8d34.png)
![image](https://user-images.githubusercontent.com/13160786/154224088-a78c5af3-1ab5-4318-a85a-864018efb105.png)
![image](https://user-images.githubusercontent.com/13160786/154224169-d03ebd30-f8c0-42f5-b6fa-1616dfea9013.png)

## Checklist

- [✅] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [✅] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [✅] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-02-17 09:04 UTC, unnamedd requested changes
Hello @jjhok, 
thanks for your contribution to our repository, however, giving a quick review, I noticed you used your native language (I can't say if Japanese or Chinese, sorry) to write the extension, and based on the guidelines of this repository, you must use English, due to the non-localisation support by Raycast.

Please, give a read on the page [Prepare an Extension for Store](https://developers.raycast.com/basics/prepare-an-extension-for-store), in special in the section [Localization / Language](https://developers.raycast.com/basics/prepare-an-extension-for-store#localization-language).

2022-02-17 23:57 UTC, jjhok commented
Hello 
Thank you for the review. 🙂

I changed all the Korean guide comments to English a while ago.

However, please understand that the delivery company's name cannot be changed because it is a unique name.

2022-03-02 05:25 UTC, pernielsentikaer requested changes
Hi @jjhok 👋 

Sorry for the ultra late response, I'm not sure, but somehow I lost track of it, I'm so sorry!

Do you have some package numbers I can try to search for?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-08 06:38 UTC, jjhok commented on extensions/parcel-tracker/package.json
> +  "description": "for track packages (only available for South Korea)",
Thank you for your suggestion

2022-03-08 06:40 UTC, jjhok commented
@pernielsentikaer 👋
the sample tracking item is.. 
- vendor : "한진택배"
- invoice number : 800390692776

thank you!

2022-03-08 19:49 UTC, pernielsentikaer requested changes
**Hi @jjhok 👋 

Thanks for the item to test with, however, it seems like it's not working for me.

![50E8Ty4mUqqSCbUZ](https://user-images.githubusercontent.com/38033107/157313281-e565e27f-8633-4228-8726-c97bc9d83305.png)

![8wy5oPgIwEyGkjyd](https://user-images.githubusercontent.com/38033107/157313298-4440f536-1cb0-48f7-8a20-b5f5b9fe2337.png)

Another suggestion, when using “next” it would be awesome if the default text was something else than `Couldn't find your package information` – maybe something like `Insert your invoice number` – or something like that, so it's easier to understand what's happening

![swQTPRdeIhqexrqu](https://user-images.githubusercontent.com/38033107/157313664-b7b88075-b692-467e-a756-d12aeca1391d.png)

You're also allowed to change the navigationTitle to something like `Track Package: {vendor}`

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.**

2022-04-06 21:57 UTC, sxn commented
hi @jjhok  - any updates? I've tried the test data you provided and got the same as @pernielsentikaer. Adding some logging to see what's happening

<img width="712" alt="image" src="https://user-images.githubusercontent.com/1155589/162076352-3359230b-2448-4263-b31c-aafe2e8b8b83.png">

I got the following:

```
00:39:17.878 800390692776 { message: { error: '유효한 키가 아닙니다.' } }
```

My Korean's unfortunately not great, so unless Google Translate is pranking me, that error seems to say `This key is not valid` - I'm guessing it's referring to the tracking key? Regardless, it looks like the error handling isn't working properly, as the code path that is getting executed assumes no error. 😅 

PS: I've taken the libery to rebase your and migrate the code to the latest version of the API, hope you don't mind. 😸

2022-04-07 02:17 UTC, jjhok commented
@sxn hi, 👋
I'm very very late because of my main job and api server issue.
so, sorry. 

I made a commitment after revising it a little while ago.

You can test by example parcel package.
 - vendor : CJ대한통운
 - invoiceNo. : 843085731224

![Apr-07-2022 11-16-14](https://user-images.githubusercontent.com/13160786/162107133-ba3b5b57-ebcb-4ecd-a9b6-7286f5b9467e.gif)

2022-04-07 02:25 UTC, jjhok commented
@sxn hi, 👋
I'm very very late because of my main job and api server issue.
I was so busy that I was out of my mind.
so, sorry.

I made a commitment after revising it a little while ago.

You can test by example parcel package.

vendor : CJ대한통운
invoiceNo. : 843085731224

![Apr-07-2022 11-16-14](https://user-images.githubusercontent.com/13160786/162108005-b3062cb6-d6e6-439a-8ec1-39c9d888693d.gif)

2022-04-07 11:19 UTC, sxn commented
hi @jjhok - no worries! thanks for fixing the issue 😄

I've done a couple more changes:
- added/fixed `isLoading` behaviour to resolve some empty state flickering issues
- call `encodeURIComponent` before creating the API endpoint URLs
- added some helpful empty views to guide users
- updated the list's `navigationTitle` when a vendor is selected

Here's it in action:

https://user-images.githubusercontent.com/1155589/162186803-1463ef0f-ebe1-481c-99a5-8d6c8a67314c.mov

2022-04-07 14:00 UTC, jjhok commented
@sxn hi!
Wow!🤩  I checked the code that you supplemented. 
Extension completion is much higher.
I will also look at the official documents carefully and improve them from now on.

I hope it's released as the current version.
Thank you so much. 👍

2022-04-08 07:44 UTC, merged