add: dropbox
raycast/extensions pull request #921
Opened 2022-02-16 14:03 UTC by chyroc

## Description

## Screencast

![save](https://user-images.githubusercontent.com/15604894/154280460-00060a3b-e69f-448f-825d-b2feda5e6ddb.png)

![config](https://user-images.githubusercontent.com/15604894/154280486-a4f91328-f025-4ad3-a947-3a23a015f0cc.png)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-02-18 05:03 UTC, pernielsentikaer requested changes
Hi @chyroc 👋 

Thanks for taking your time to contribute 🔥 

Before going to the review state, could you update the README with a step-by-step guide on how to achieve the token – it was not possible for me to locate it 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-18 07:31 UTC, chyroc commented
@pernielsentikaer hi, i fix my pr, please review it again, thanks.

2022-02-19 07:09 UTC, pernielsentikaer reviewed
Hi @chyroc 👋 

We might have a problem, I'm not sure how it handles when it's downloading a large file and the extension window loses focus, when that happens, everything will be terminated.

This is not ideal, since we can't force end-users to have the extension open at all times in order to get the file downloaded.

I'm not able to test it out myself yet since I keep getting 401 with wrong permissions, but if it's the case, then we have to set it on hold until it's possible to have background processes.

Suggested feedback was added before above was written, I'm letting it be 😄 

Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-21 01:27 UTC, chyroc commented on extensions/dropbox/package.json
> +  "description": "dropbox extensions",
hi, this extension is for all dropbox feature, save url is one of features(example: view file, upload file, save file, ...)

2022-02-21 01:27 UTC, chyroc commented on extensions/dropbox/package.json
> +  "description": "dropbox extensions",
i change it to `Dropbox Extensions`

2022-02-21 01:27 UTC, chyroc commented
@pernielsentikaer hi, i fix this pr, please review it again , thanks.

2022-02-21 14:35 UTC, pernielsentikaer commented
Hi @chyroc 👋 

I'm not sure why it didn't work the first time, but now I'm able to test it out.

It seems to do the job as expected with smaller files, however, if I download larger files and the extension looses focus, it dies.

As stated earlier, we don't have support for background processes, until then we have to set it on hold since we don't want bad user experience.

Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-21 14:41 UTC, chyroc commented
@pernielsentikaer hi:

If I use this api ( https://developers.raycast.com/api-reference/storage ) to store and reload data, is there no need for a long running background process?
And, you can do a job list function locally.

If you think this note is ok I will revise my pr

2022-02-23 21:32 UTC, pernielsentikaer commented
Hi @chyroc 👋 

I'm not sure what you have in mind, are you thinking about splitting it up in a list with jobs and a command to add? I would like to hear a bit more of what you have in your mind 😄

2022-04-05 19:02 UTC, fe9lix commented
Hey guys, I'm closing this PR because of inactivity. Feel free to reopen it again later and address the feedback.

2022-04-05 19:02 UTC, closed without merging