Add copyq-clipboard-manager extension
raycast/extensions pull request #9224
Opened 2023-11-13 02:26 UTC by andrewcincotta

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-11-14 04:26 UTC, pernielsentikaer commented
Hi 👋

Should we close #9139 in favor of this one?

2023-11-14 19:00 UTC, andrewcincotta commented
> Hi 👋
> 
> Should we close #9139 in favor of this one?

Sure, my fault.

2023-11-15 13:32 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- It's weird that there are more entries in the list than there are items. Could you look into this?

![copyq-clipboard-manager 2023-11-15 at 14 28 07](https://github.com/raycast/extensions/assets/38033107/b5909807-6f2d-448a-895d-385046084b5c)

- You can maybe check the default installation paths, [something like here](https://github.com/raycast/extensions/commit/2065b9507ca92d5ad8df480d4d66385cbc0ef16d#diff-1c06f6551afb8db75ccba4044926a86af349f4971d3d27098a5db706ec9b9315R24-R29)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-11-15 13:32 UTC, pernielsentikaer commented on extensions/copyq-clipboard-manager/README.md
> +Lists CopyQ clipboard entries and allows user to select/paste them.
Could you write a bit about CopyQ and a guide for how to install it

2023-11-15 19:35 UTC, andrewcincotta commented
@pernielsentikaer I fixed the issue with empty clipboard entries forming. It occurs when the default number of items preference is larger than the number of clipboard entries in the chosen CopyQ tab. Also revised the README to include a description of CopyQ and where to go to install it.

2023-11-16 08:19 UTC, pernielsentikaer commented
What about adding the default paths so we could prompt the user as little as possible, not all know how to find the paths, and maybe raise the limit to 25?

2023-11-16 22:23 UTC, andrewcincotta commented
> What about adding the default paths so we could prompt the user as little as possible, not all know how to find the paths, and maybe raise the limit to 25?

While I've been waiting for version 1 to be listed on the store I've been overhauling the code to provide a faster display of clipboard contents. In the next version, you can choose a tab before displaying clipboard contents, and all clipboard contents will appear instantly (even on my Mac tab which contains over 1300 items!) 
Can I work on the default path issue in the second version I plan on publishing shortly after?

2023-11-17 04:48 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-11-17 04:57 UTC, merged