Add shortcuts-search extension
raycast/extensions pull request #9235
Opened 2023-11-14 01:32 UTC by solomkinmv

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-11-14 15:40 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

When checking an application that's not added, it just shows the empty view. Maybe you could tweak it to show an error?

![shortcuts-search 2023-11-14 at 16 08 36](https://github.com/raycast/extensions/assets/38033107/1a14efd3-518c-460b-beb7-95dee065c120)


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-11-15 02:34 UTC, solomkinmv commented on extensions/shortcuts-search/src/current-app.ts
> +    await Clipboard.copy(frontmostApplication.bundleId, { concealed: true });
No major reasons for concealed. I tried to keep clipboard history clean, but I guess that's redundant. Removed concealed property

2023-11-15 02:37 UTC, solomkinmv commented on extensions/shortcuts-search/src/current-app.ts
> +    await Clipboard.copy(frontmostApplication.bundleId, { concealed: true });
Updated extension to close itself and show error HUD if no shortcuts available.
<img width="536" alt="image" src="https://github.com/raycast/extensions/assets/9872823/7a9845fb-9411-4dae-9d6b-4fad33c3bd49">

2023-11-15 02:43 UTC, solomkinmv commented
Updated extension to close itself and show error HUD if no shortcuts available.
<img width="536" alt="image" src="https://github.com/raycast/extensions/assets/9872823/bc0a60f4-6210-4f86-8db5-92dd6f0acb48">

2023-11-15 06:31 UTC, pernielsentikaer commented
There are a bit of [empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) in the `All Shortcuts` command, can you look into this?

2023-11-16 02:52 UTC, solomkinmv commented
> There is a bit of [empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) in the `All Shortcuts` command, can you look into this?

Could you please check out latest version? I've fixed it in [this](https://github.com/raycast/extensions/pull/9235/commits/2e1bffe09df4b3d51efd5e173b9ab1fe5dc03c8e) commit. Double checked that it's still good after your improvements [here](https://github.com/raycast/extensions/pull/9235/commits/0a6aae6d52266adcd971efa5b36b446b99f5982f).

Here's slow motion recording of `List All Shortcuts` command after clearing caches and local storage.
![Screen Recording 2023-11-15 at 21 39 25](https://github.com/raycast/extensions/assets/9872823/83fb2a93-6956-4fcd-8316-283a69f30c12)

2023-11-17 11:32 UTC, pernielsentikaer commented
it's also when you go from `All shortcuts` and then click Open on an application, then you can see the flicker too - can you fix that too, otherwise let me know 🙂

2023-11-18 05:56 UTC, solomkinmv commented
I've tried to fix that flickering "No results", but looks likethe problem is on the RayCast side.

To test this case I've created new extension with `useNavigation` and static list. This small  extension also has flickering "No results" and I can't control this. Even adding `isLoading={true}` doesn't prevent from flickering. 

![Screen Recording 2023-11-18 at 00 50 57](https://github.com/raycast/extensions/assets/9872823/46eddefd-6ca5-4d8c-adab-b420ada06c47)


```
import { Action, ActionPanel, List, useNavigation } from "@raycast/api";

export default function Command() {
  const { push } = useNavigation();
  return (
    <List>
      <List.Item
        key={"key"}
        title={"title"}
        actions={
          <ActionPanel>
            <Action title={"open"} onAction={() => push(<Command2 />)} />
          </ActionPanel>
        }
      /> </List>
  );
}

export function Command2() {
  return (
    <List>
      <List.Item
        key={"key"}
        title={"title2"}
      />
    </List>
  );
}
```

2023-11-20 13:00 UTC, pernielsentikaer commented
You're right! We'll look into a fix 🙂

2023-11-20 13:05 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-11-21 03:29 UTC, merged