Add stand-up extension
raycast/extensions pull request #9247
Opened 2023-11-14 18:39 UTC by theomjones

## Description

## Screencast

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-11-15 07:18 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- What about having a title field as textfield and a Note field as textarea so, there is more space available?

- Maybe you can add [Draft](https://developers.raycast.com/api-reference/user-interface/form#drafts) support, but it might only work for `Take Note`

- Add support for creating new labels

- Add so it’s possible to edit a note

- Add [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert#confirmalert) before deleting all items

- use [useSql](https://developers.raycast.com/utilities/react-hooks/usesql) instead of `lowdb`, this way we can also tweak useSql if something pops up (should be possible)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-11-15 21:21 UTC, theomjones commented
> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I have now tested your extension, and I have some feedback ready for you:
> 
> * What about having a title field as textfield and a Note field as textarea so, there is more space available?
> * Maybe you can add [Draft](https://developers.raycast.com/api-reference/user-interface/form#drafts) support, but it might only work for `Take Note`
> * Add support for creating new labels
> * Add so it’s possible to edit a note
> * Add [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert#confirmalert) before deleting all items
> * use [useSql](https://developers.raycast.com/utilities/react-hooks/usesql) instead of `lowdb`, this way we can also tweak useSql if something pops up (should be possible)
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

👋 Hi, thanks for feeding back 

I've address some of your comments and have some comments for others:

- [x] Added description field for more information
- [ ] Draft support, I'm not sure this needs drafts as it's supposed to be very quick, like just a thought during the day that needs logging.
- [ ] I'll iterate after first release for adding labels unless you think it's essential for first release 
- [x] Added edit functionality
- [x] Added confirm for deleting all notes in a day
- [ ] I'm not sure the overhead of adding sql and the implications it brings (migrations, potential ORM inclusion) is worth it

I'm happy to address the unchecked points if you think it's worth it 😃 

Thanks very much

2023-11-16 11:48 UTC, pernielsentikaer requested changes
Just checked it again and you might want to use something like [useCachedPromise](https://developers.raycast.com/utilities/react-hooks/usecachedpromise) instead of `useAsync`, there you get `cache` and `loading` property directly - the current way also produces [empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) when loading notes

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-11-16 11:48 UTC, pernielsentikaer commented on extensions/stand-up/src/components/note-form.tsx
> +      <Form.Dropdown title="Note type" id={"type"} defaultValue={initialData.type}>
```suggestion
      <Form.Dropdown title="Note Type" id={"type"} defaultValue={initialData.type}>
```

2023-11-16 12:23 UTC, theomjones commented
Hey, I've amended this to use the cached promise hook and removed the react-use dependency!

Thanks for your feedback 😃

2023-12-01 08:43 UTC, pernielsentikaer commented
Checking this out now 🙂

2024-01-04 09:54 UTC, pernielsentikaer commented on extensions/stand-up/src/components/edit-note.tsx
> +      title={"Edit Note"}
Missing an icon

2024-01-04 09:55 UTC, pernielsentikaer commented on extensions/stand-up/src/show-notes.tsx
> +          <List.Dropdown.Item title="Show all" value="all" />
```suggestion
          <List.Dropdown.Item title="Show All" value="all" />
```

2024-01-04 09:55 UTC, pernielsentikaer commented on extensions/stand-up/src/show-notes.tsx
> +        <List.Dropdown onChange={setFilter} tooltip="Filter by day">
```suggestion
        <List.Dropdown onChange={setFilter} tooltip="Filter by Day">
```

2024-01-04 09:56 UTC, pernielsentikaer requested changes
I added a note today and then I changed it for tomorrow, it still says today here

![Raycast-sQPL2mc6@2x](https://github.com/raycast/extensions/assets/38033107/db8b5ea1-1b1d-497a-91ed-559c4989f91d)

I'm looking forward to testing this extension again 🔥

2024-01-29 06:32 UTC, closed without merging