Added urban dictionary extension
raycast/extensions pull request #926
Opened 2022-02-16 20:38 UTC by naman1-gupta

## Description
An extension to search [urban dictionary](https://urbandictionary.com) for a term

## Screencast

https://user-images.githubusercontent.com/23036464/154352819-825beb76-158e-4168-9430-2d011617c4a9.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-02-18 05:22 UTC, pernielsentikaer requested changes
Hi @naman1-gupta 👋 

Awesome! Thanks for taking your time to contribute 🔥 

I left some suggestions and feedback for you to address:

* No fallback if the items like author (used in the list) – seems like there is more.
* Please run `npm run lint` and fix the errors mentioned
* Seems like you're using an older version of NPM

```
💥 error - validate package-lock.json file
wrong 'lockfileVersion' in package-lock.json. Found version 1, expected: 2. Update npm to v7.x
Error: wrong 'lockfileVersion' in package-lock.json. Found version 1, expected: 2. Update npm to v7.x
Error: Process completed with exit code 1.
```

Looking forward for the next version 🔥 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-18 05:22 UTC, pernielsentikaer commented on extensions/urban-dictionary/package.json
> +  "description": "Search urban dictionary for a term",
```suggestion
  "description": "Search urban dictionary for a word",
```

2022-02-18 05:22 UTC, pernielsentikaer commented on extensions/urban-dictionary/src/index.tsx
> +       url: `http://api.urbandictionary.com/v0/define?term=${term}`,
```suggestion
       url: `https://api.urbandictionary.com/v0/define?term=${term}`,
```

2022-02-18 05:22 UTC, pernielsentikaer commented on extensions/urban-dictionary/src/index.tsx
> +                setTerms(res);
```suggestion
                setTerms(res);
                setIsLoading(false)
```

2022-02-18 05:22 UTC, pernielsentikaer commented on extensions/urban-dictionary/src/index.tsx
> +            searchBarPlaceholder='Enter term to search UD...'
```suggestion
            searchBarPlaceholder='Enter word to search...'
```

2022-02-18 05:22 UTC, pernielsentikaer commented on extensions/urban-dictionary/package.json
> +      "title": "Urban Dictionary",
```suggestion
      "title": "Search Word",
      "subtitle": "Urban Dictionary",
```

2022-02-18 05:22 UTC, pernielsentikaer commented on extensions/urban-dictionary/package.json
> +      "description": "Search Urban Dictionary",
```suggestion
      "description": "Search Urban Dictionary a word",
```

2022-02-18 05:22 UTC, pernielsentikaer commented on extensions/urban-dictionary/src/index.tsx
> +       url: `http://api.urbandictionary.com/v0/define?term=${term}`,
```suggestion
       url: `https://api.urbandictionary.com/v0/define?term=${term}`,
```

2022-02-20 11:20 UTC, naman1-gupta commented
Hi @pernielsentikaer, 

Thank you for spending the time to review my code.

> - No fallback if the items like author (used in the list) – seems like there is more.
> - Please run npm run lint and fix the errors mentioned
> - Seems like you're using an older version of NPM

I've implemented a fix to all of these issues along with a few other suggestions. I don't agree with replacing `term` with `word` particularly because the search query could be a phrase as well and not necessarily a single word.

What do you think?

2022-02-20 21:00 UTC, pernielsentikaer requested changes
Hi @naman1-gupta 👋 

The update is doing the job as expected, only reason I wanted to change it is because that's what urban dictionary call it – I'll leave it up to you with this one :)

![dqLVCTJjvZEKR9ZF](https://user-images.githubusercontent.com/38033107/154864138-74be648f-183a-4da2-ae85-d44957c4328d.png)

Request a new review when you are ready (whatever you decide), feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-02-24 05:42 UTC, naman1-gupta commented
> Hi @naman1-gupta 👋
> 
> The update is doing the job as expected, only reason I wanted to change it is because that's what urban dictionary call it – I'll leave it up to you with this one :)
> 
> ![dqLVCTJjvZEKR9ZF](https://user-images.githubusercontent.com/38033107/154864138-74be648f-183a-4da2-ae85-d44957c4328d.png)
> 
> Request a new review when you are ready (whatever you decide), feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

Makes sense @pernielsentikaer . I've changed it to word to be consistent with the website.

2022-02-24 07:04 UTC, pernielsentikaer requested changes
Hi @naman1-gupta 👋 

Awesome! 💪 One last correction that would improve the UX a bit is to return an empty array when you clear the search – right now it's possible to have a list of result and nothing in the search bar

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-04-05 19:05 UTC, fe9lix commented
Hey guys, I'm closing this PR because of inactivity. Feel free to reopen it again later and address the feedback.

2022-04-05 19:05 UTC, closed without merging