Add pile-raycast extension
raycast/extensions pull request #9282
Opened 2023-11-16 14:43 UTC by cr34t1ve

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-11-21 04:31 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- The extensions suffer from [Empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states)

- Remove `metadata/pile-raycast-3.png`

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-11-21 04:31 UTC, pernielsentikaer commented on extensions/pile-raycast/CHANGELOG.md
> +# pile-raycast Changelog
```suggestion
# Pile Changelog
```

2023-11-21 04:31 UTC, pernielsentikaer commented on extensions/pile-raycast/src/index.tsx
> +              <Action.Push title="Open Post" target={<Detail markdown={post?.excerpt || ""} />} />
missing an icon

2023-11-21 04:31 UTC, pernielsentikaer commented on extensions/pile-raycast/package.json
> +  "description": "A raycast extension for the Pile journaling app",
```suggestion
  "description": "A Raycast extension for the Pile journaling app",
```

2023-11-21 04:31 UTC, pernielsentikaer commented on extensions/pile-raycast/package.json
> +  "title": "Pile-Raycast",
```suggestion
  "title": "Pile",
```

2023-11-21 04:31 UTC, pernielsentikaer commented on extensions/pile-raycast/package.json
> +      "title": "Create Post",
```suggestion
      "title": "Create Post",
      "subtitle": "Pile",
```

2023-11-21 04:31 UTC, pernielsentikaer commented on extensions/pile-raycast/package.json
> +      "description": "Template for creating a post",
```suggestion
      "description": "Creates a post in Pile journaling application",
```

2023-11-21 13:45 UTC, closed without merging

2023-11-23 09:12 UTC, cr34t1ve commented
Closed PR because the name of the extension was changed to **Mound**.
New PR can be found [here](https://github.com/raycast/extensions/pull/9351)