Add code-saver extension
raycast/extensions pull request #9340
Opened 2023-11-21 06:08 UTC by Gnosnay

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-11-27 08:51 UTC, pernielsentikaer requested changes
Hi 👋

I gave it a new spin and couldn't pass `Library` field, no options - I'm not sure what to do here.

![code-saver 2023-11-27 at 09 49 58](https://github.com/raycast/extensions/assets/38033107/5ead0fb0-54fe-4a92-88d3-59106dba6395)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-11-27 11:49 UTC, Gnosnay commented
> Hi 👋
> 
> I gave it a new spin and couldn't pass `Library` field, no options - I'm not sure what to do here.
> 
> ![code-saver 2023-11-27 at 09 49 58](https://private-user-images.githubusercontent.com/38033107/285783663-5ead0fb0-54fe-4a92-88d3-59106dba6395.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODU5ODUsIm5iZiI6MTcwMTA4NTY4NSwicGF0aCI6Ii8zODAzMzEwNy8yODU3ODM2NjMtNWVhZDBmYjAtNTRmZS00YTkyLTg4ZDMtNTkxMDZkYmE2Mzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDExNDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZjBmMTdmZmVmOTFmYTFjYWRjYTNmMGQ3ZDU4NjZmZTBiMDRmOTZjNzkxOGRiZTkwMDM2NGU1MzE1YzcxNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TX03Wq14nAMClxvNOmLlS1kB5A5KDnBP92DrTeIWurg)
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

@pernielsentikaer hi in this page, can press `cmd + k` to add label and library.
i think i can add one more tooltip here to advise user to help themsleves

2023-11-27 12:24 UTC, pernielsentikaer requested changes
Ah, that makes sense! I guess others might be confused too.

Regarding the labels, I selected #006699 for both of them, but when I wanted to add them to the snippet, they appeared in two random colors. Is that intended?

https://github.com/raycast/extensions/assets/38033107/00c398dd-7fe0-41ac-bed2-1228f1ac46e0

2023-11-27 13:01 UTC, Gnosnay commented
> Ah, that makes sense! I guess others might be confused too.
> 
> Regarding the labels, I selected #6699 for both of them, but when I wanted to add them to the snippet, they appeared in two random colors. Is that intended?
> 
>  Raycast-FlC7hFOZ.mp4

no it is one bug. thx for pointing it out.  thank you so much

2023-11-28 05:58 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- There is flicker in both command when you enters them, is there a way not to have this flicker?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-11-28 05:58 UTC, pernielsentikaer commented on extensions/code-saver/src/components/search-snippet/item-actions.tsx
> +        title="Delete This Snippet"
```suggestion
        title="Delete This Snippet"
        style={Action.Style.Destructive}
```

2023-11-28 05:58 UTC, pernielsentikaer commented on extensions/code-saver/src/components/creation/label-entry.tsx
> +        title="Label title"
```suggestion
        title="Label Title"
```

2023-11-28 06:36 UTC, Gnosnay commented
> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I have now tested your extension, and I have some feedback ready for you:
> 
> * There is flicker in both command when you enters them, is there a way not to have this flicker?
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

hmm actually the flicker is one loading page how db schema upgrading or dependency downloading.

it is too fast so that the loading page is like one flicker.

do you have any recommendation about this?

2023-11-30 04:04 UTC, pernielsentikaer approved these changes
I'd say we go with this and see if we can improve it in v2(or 3) 🙂

2023-11-30 04:26 UTC, merged