Add aliyundrive
raycast/extensions pull request #937
Opened 2022-02-18 07:13 UTC by chyroc

## Description

for: https://www.aliyundrive.com

## Screencast

![image](https://user-images.githubusercontent.com/15604894/154635083-eefd93d9-ece5-4368-9db2-23976e7c7b13.png)

list files:

![image](https://user-images.githubusercontent.com/15604894/154635106-2661ed5c-c87e-4b86-961f-91374aa049d5.png)

share file:
![image](https://user-images.githubusercontent.com/15604894/154635141-05e12522-e43f-4082-a50c-cee68f6a09e5.png)

create folder:

![image](https://user-images.githubusercontent.com/15604894/154635176-560cad63-78de-4e2f-8ed6-9e78e0b9e7b7.png)

rename:

![image](https://user-images.githubusercontent.com/15604894/154635210-15a1ee8e-84db-498b-a99f-b4fce25b9742.png)

delete:

![image](https://user-images.githubusercontent.com/15604894/154635246-c711ddce-1f14-4966-8358-8f4d22600041.png)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-03-01 04:51 UTC, pernielsentikaer requested changes
Hi @chyroc 👋 

Thanks for your contribution! 💪 

I'm not quite sure how to test/(and use) it, could you maybe provide a README so it's possible to understand what's happening, there are no preferences at all.

The extension suffers from [Empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) - could you resolve this also?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-01 04:51 UTC, pernielsentikaer commented on extensions/aliyundrive/package.json
> +      "title": "AliyunDrive My Files",
```suggestion
      "title": "My Files",
      "subtitle": "AliyunDrive",
```

2022-03-01 04:51 UTC, pernielsentikaer commented on extensions/aliyundrive/package.json
> +      "title": "AliyunDrive Search Files",
```suggestion
      "title": "Search Files",
      "subtitle": "AliyunDrive",
```

2022-04-05 19:06 UTC, fe9lix commented
Hey guys, I'm closing this PR because of inactivity. Feel free to reopen it again later and address the feedback.

2022-04-05 19:06 UTC, closed without merging