Add leafcast extension
raycast/extensions pull request #9418
Opened 2023-11-25 20:44 UTC by syropian

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-11-28 09:16 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution, and happy Movember 🧔‍♂️ 💪 

I have now tested your extension, and I have some feedback ready for you:

- Could you add a [metadata image](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-11-28 09:16 UTC, pernielsentikaer commented on extensions/leafcast/src/components/SetDeviceAddressForm.tsx
> +          <Action.SubmitForm onSubmit={handleSetDeviceAddress} title="Save Device Address" />
Missing an icon

2023-11-28 09:16 UTC, pernielsentikaer commented on extensions/leafcast/src/pair-device.tsx
> +          <Action title="Reset Device Address" style={Action.Style.Destructive} onAction={resetDeviceAddress} />
Missing icons

2023-11-29 01:15 UTC, syropian commented
@pernielsentikaer Thanks for the review! I tried using Raycast's screenshot tool to generate my metadata assets but it seemed to only output the image at half the required dimensions. Is this a known issue? It's causing the linter to fail 😢

2023-11-29 08:35 UTC, pernielsentikaer commented
Hi @syropian 👋 

You might need to take it on our retina display on the mac, could you try that? Otherwise I'm happy to help :)

2023-12-05 06:20 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-12-05 06:32 UTC, merged