Add "CloudFormation Stacks" command to AWS extension
raycast/extensions pull request #950
Opened 2022-02-19 19:44 UTC by JonathanWbn

## Description

This adds a fifth AWS command that lists the CloudFormation stacks of the user.

## Screencast

https://user-images.githubusercontent.com/19997520/154816575-7fff72fe-0c51-47f8-acda-9089d5a240fb.mov

FYI @victor-falcon

2022-03-01 22:51 UTC, pernielsentikaer requested changes
Hi @JonathanWbn 👋 

Thanks for your contribution, it's awesome when the community keeps improving the extensions 💎 

You should add yourself as contributor in the [package.json file](https://developers.raycast.com/information/manifest#extension-properties)

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-02 11:27 UTC, JonathanWbn commented
> You should add yourself as contributor in the [package.json file](https://developers.raycast.com/information/manifest#extension-properties)


@pernielsentikaer Can you help me figure out how I create a Raycast developer account? I couldn't find this information in the docs.

2022-03-02 11:39 UTC, pernielsentikaer commented
> > You should add yourself as contributor in the [package.json file](https://developers.raycast.com/information/manifest#extension-properties)
> 
> @pernielsentikaer Can you help me figure out how I create a Raycast developer account? I couldn't find this information in the docs.

When you use the `Store` command in Raycast, it should prompt you to login/create - you should also be able to do both here: https://www.raycast.com/developers 😄

2022-03-02 13:02 UTC, pernielsentikaer approved these changes
Awesome @JonathanWbn 🔥 

Thanks for your contribution 💯

2022-03-02 15:05 UTC, sxn commented
🎉

2022-03-02 15:05 UTC, merged