Add raytyping extension
raycast/extensions pull request #9515
Opened 2023-12-03 06:12 UTC by louishuyng

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-12-07 04:25 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Missing [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)

- I'm not sure about the loading indicator, it kinda steals the focus

- Is there a way to load real sentences instead of just words, it might be easier to type 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-12-07 04:25 UTC, pernielsentikaer commented on extensions/raytyping/package.json
> +      "title": "Raytyping",
```suggestion
      "title": "Start Raytyping",
```

2023-12-07 04:25 UTC, pernielsentikaer commented on extensions/raytyping/src/raytype.tsx
> +          tooltip="Word amount"
```suggestion
          tooltip="Word Amount"
```

2023-12-07 04:25 UTC, pernielsentikaer commented on extensions/raytyping/src/raytype.tsx
> +            <Action title="Reload" onAction={() => reloadGame()} />
Could add an icon here

2023-12-07 04:46 UTC, louishuyng commented
> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I have now tested your extension, and I have some feedback ready for you:
> 
>     * Missing [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)
> 
>     * I'm not sure about the loading indicator, it kinda steals the focus
> 
>     * Is there a way to load real sentences instead of just words, it might be easier to type 🙂
> 
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

I'm not sure about the loading indicator, it kinda steals the focus
=> After testing and playing many times, I don't think it distracts us when typing. It also helps to indicate the typing now recording

Is there a way to load real sentences instead of just words, it might be easier to type 🙂
=> I want to keep monkey type experience, so I read their open source https://github.com/monkeytypegame/monkeytype  here and try to replicate the same experience as they did when typing

2023-12-19 13:23 UTC, louishuyng commented
Hi @pernielsentikaer Do i need any update on this PR to make it releasable? It has been reviewed 2 weeks ago

2024-01-02 12:40 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-01-02 12:52 UTC, merged