feat(kubernetes) add kubernetes official docs support
raycast/extensions pull request #953
Opened 2022-02-20 14:49 UTC by rpvsilva

## Description

This extension allows searching in the Kubernetes official documentation through the raycast.

## Screencast

### Extention Screenshot
<img width="779" alt="Screenshot 2022-02-20 at 14 43 08" src="https://user-images.githubusercontent.com/25325644/154848272-91fc6a7e-313c-4287-974e-58d21b1fda0f.png">

### Search List
<img width="800" alt="Screenshot 2022-02-20 at 14 43 33" src="https://user-images.githubusercontent.com/25325644/154848266-76beb1e5-c43f-4c65-8981-bcf8e3b3462c.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-03-02 04:22 UTC, pernielsentikaer requested changes
Hi @rpvsilva 👋 

Thanks for your contribution 💪 

I have some feedback for you to address 💯 

Is there a way to add a list of “default” elements, so the list is not empty, like many other documentation extensions:

![wQ9pVXSRyzzy7Izn](https://user-images.githubusercontent.com/38033107/156294503-f407f4ce-f8f9-4645-ad62-f31a1d93dbe4.png)

Just trying to see if we can find a way to spice the UX a little bit 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-02 04:22 UTC, pernielsentikaer commented on extensions/kube-docs/package.json
> +  "name": "kubernetes-docs",
Could the folder renamed to `kubernetes-docs`?

2022-03-02 04:22 UTC, pernielsentikaer commented on extensions/kube-docs/package.json
> +  "description": "Get kubernetes official documentation",
```suggestion
  "description": "Search kubernetes official documentation",
```

2022-03-02 04:22 UTC, pernielsentikaer commented on extensions/kube-docs/package.json
> +      "description": "Kubernetes Documentation",
```suggestion
      "description": "Search in Kubernetes documentation",
```

2022-03-02 04:22 UTC, pernielsentikaer commented on extensions/kube-docs/src/index.tsx
> +  const debounceCallback = useCallback(debounce(DEBOUNCE_DELAY, onQueryChange), []);
```suggestion
```
You shouldn't use a “custom” debounce, there is one handling this directly in Raycast, you can add `throttle` directly to the [<List> element](https://developers.raycast.com/api-reference/user-interface/list#list)

2022-03-02 04:22 UTC, pernielsentikaer commented on extensions/kube-docs/src/index.tsx
> +const DEBOUNCE_DELAY = 300;
```suggestion
```

2022-03-14 15:14 UTC, pernielsentikaer approved these changes
Hi @rpvsilva 👋 

Thanks for the update, much better 🔥

2022-03-14 15:16 UTC, rpvsilva commented
> Hi @rpvsilva 👋
> 
> Thanks for the update, much better 🔥

Thank you for your review and your suggestions! I think the extension is more complete now

2022-03-14 22:38 UTC, merged