Added Flutter Documentation extension
raycast/extensions pull request #955
Opened 2022-02-20 21:32 UTC by MattisBrizard

## Description

This extension lets you search in the Flutter documentation and open the researched element on https://api.flutter.dev

## Screencast

https://user-images.githubusercontent.com/26067909/154865106-62dc1e9f-a94e-43a3-8ae4-a2e1ec0f5e66.mov

## Checklist

- [ x ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ x ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ x ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-03-02 04:48 UTC, pernielsentikaer requested changes
Hi @MattisBrizard 💪 

Thanks for your contribution, it's always nice to get more documentation extensions 💯 

I left some feedback for you to address 😄 

Is there a way to show some default elements, like doing in the Helm documentation, I'm not sure if it's that easy with Flutter, just trying to see if there is a way to notch up the UX a bit 😄 

![image](https://user-images.githubusercontent.com/38033107/156296887-8eba6813-052e-447b-b568-c4614215cd56.png)

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-09 10:18 UTC, MattisBrizard commented
Hi @pernielsentikaer, I've applied the suggestion you made and added an initial state showing more documentation links (Taken from https://api.flutter.dev/).
Tell me if you want me to add something else.

2022-03-09 21:39 UTC, pernielsentikaer requested changes
Hi @MattisBrizard 👋 

Only one question left, maybe I'm just too old to understand what it stands for 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-09 21:39 UTC, pernielsentikaer commented on extensions/flutter-documentation-search/src/index.tsx
> +      searchBarPlaceholder="Search in ddze Flutter documentation..."
What is `ddze` here?

2022-03-10 09:49 UTC, MattisBrizard commented
Hi @pernielsentikaer, oops a typo, removed it 😅

2022-03-10 09:54 UTC, pernielsentikaer commented
Ah thanks @MattisBrizard - I was feeling old for now knowing that 😄 

One last thing before merging, would it make sense to use the list.item icon in the searches (as the initial items have)

2022-03-10 10:02 UTC, MattisBrizard commented
@pernielsentikaer, as some of the APIs shown are directly from the Dart SDK (Flutter embed the Dart SDK) showing a Flutter Icon for a Dart method wouldn't make sense for me.

2022-03-10 10:42 UTC, pernielsentikaer commented
Got it, agree, thanks for the clarification 😄

2022-03-10 10:42 UTC, pernielsentikaer approved these changes
Approved! 💣

2022-03-10 11:18 UTC, merged