adding initial attempt at reddit search extension
raycast/extensions pull request #959
Opened 2022-02-21 20:56 UTC by ewlcheng

## Description

Searches and displays results from reddit.

## Screencast

<img width="763" alt="Screen Shot 2022-02-21 at 1 52 57 PM" src="https://user-images.githubusercontent.com/25830486/155025159-f761de18-dc9d-4725-bfe3-602c5ea643cc.png">

## Checklist

- [ x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-03-02 05:16 UTC, pernielsentikaer requested changes
Wow @ewlcheng 🔥 

What an extension, it's massive! 

Some feedback and suggestions for you:

- Is there a way to show 20 items when entering a favorite Subreddit?

- Is there a way to indicate what `sort` that's active?

![HENCZrdufP982bmi](https://user-images.githubusercontent.com/38033107/156299620-fe2f7102-9837-414e-98b9-660640ec7a4d.png)

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-02 05:16 UTC, pernielsentikaer commented on extensions/reddit-search/src/Home.tsx
> +                    title="Search subreddits"
```suggestion
                    title="Search Subreddits"
```

2022-03-02 05:16 UTC, pernielsentikaer commented on extensions/reddit-search/src/PostList.tsx
> +              <Action title="Sort by latest" onAction={() => doSearch(redditSort.latest)} />
```suggestion
              <Action title="Sort by Latest" onAction={() => doSearch(redditSort.latest)} />
```

2022-03-02 05:16 UTC, pernielsentikaer commented on extensions/reddit-search/src/PostList.tsx
> +              <Action title="Sort by top" onAction={() => doSearch(redditSort.top)} />
```suggestion
              <Action title="Sort by Top" onAction={() => doSearch(redditSort.top)} />
```

2022-03-02 05:16 UTC, pernielsentikaer commented on extensions/reddit-search/src/PostList.tsx
> +              <Action title="Sort by comments" onAction={() => doSearch(redditSort.comments)} />
```suggestion
              <Action title="Sort by Comments" onAction={() => doSearch(redditSort.comments)} />
```

2022-03-02 05:16 UTC, pernielsentikaer commented on extensions/reddit-search/src/SubredditList.tsx
> +                    title="Favorite"
```suggestion
                    title="Add to Favorites"
```

2022-03-02 20:10 UTC, ewlcheng commented on extensions/reddit-search/src/Home.tsx
> +                    title="Search subreddits"
Done. 👍

2022-03-02 20:10 UTC, ewlcheng commented on extensions/reddit-search/src/PostList.tsx
> +              <Action title="Sort by latest" onAction={() => doSearch(redditSort.latest)} />
Done. 👍

2022-03-02 20:10 UTC, ewlcheng commented on extensions/reddit-search/src/PostList.tsx
> +              <Action title="Sort by top" onAction={() => doSearch(redditSort.top)} />
Done. 👍

2022-03-02 20:10 UTC, ewlcheng commented on extensions/reddit-search/src/PostList.tsx
> +              <Action title="Sort by comments" onAction={() => doSearch(redditSort.comments)} />
Done. 👍

2022-03-02 20:10 UTC, ewlcheng commented on extensions/reddit-search/src/SubredditList.tsx
> +                    title="Favorite"
Done. 👍

2022-03-02 20:54 UTC, pernielsentikaer reviewed
Hi @ewlcheng 👋 

You're on fire 🔥 

Do you think it's possible to show a list of items when entering a Subreddit? I'd like to see a list like when I use my phone and entering a Subreddit?

2022-03-02 23:30 UTC, ewlcheng commented
> Hi @ewlcheng 👋
> 
> You're on fire 🔥
> 
> Do you think it's possible to show a list of items when entering a Subreddit? I'd like to see a list like when I use my phone and entering a Subreddit?

That's a great idea, I like it! Implemented.

2022-03-03 05:19 UTC, pernielsentikaer requested changes
Wow, @ewlcheng! 🔥 

You keep surprising! I have some more feedback for you to address, we're so close!

- It seems like there is [Empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) when entering a `Favorite subreddit` – can you look into this?
- Seems like you had an idea about using a preference value to let the user select the amount of results but didn't finish – is it forgotten or a leftover?
- When entering a favorite subreddit, then it does not make sense to show the subreddit name, does it?

![p9YORduWtwbUqc4t](https://user-images.githubusercontent.com/38033107/156501220-1d4dc802-f532-4b46-bb9b-200ef5a98f43.png)

Thanks for creating a very awesome plugin, I'm already using it all the time 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-03 05:19 UTC, pernielsentikaer commented on extensions/reddit-search/src/Home.tsx
> +                    title="Search subreddits"
I think you forgot this one 😄

2022-03-03 05:19 UTC, pernielsentikaer commented on extensions/reddit-search/src/SubredditList.tsx
> +                    icon={Icon.Star}
```suggestion
                    icon={Icon.Star}
                    shortcut={{ modifiers: ["cmd"], key: "f" }}
```

2022-03-03 05:19 UTC, pernielsentikaer commented on extensions/reddit-search/src/SubredditList.tsx
> +                    title="Remove from Favorites"
```suggestion
                    title="Remove From Favorites"
                    shortcut={{ modifiers: ["cmd"], key: "f" }}
```
Then it's a toggle function 🔥

2022-03-03 15:10 UTC, ewlcheng commented
Good catches @pernielsentikaer. Let's see if I squashed all the bugs this time. :)

2022-03-04 05:15 UTC, pernielsentikaer approved these changes
Awesome @ewlcheng 🔥 

I think we're ready to proceed, let's get it merged, so everyone can use this extension! I'm going to use it a lot myself 👏 

Thanks for your contribution 💯

2022-03-04 08:45 UTC, sxn commented
🎉 nice work

2022-03-04 08:45 UTC, merged