Add macosicons extension
raycast/extensions pull request #9594
Opened 2023-12-07 18:38 UTC by shldk

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-12-12 09:16 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

– Add a [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert#confirmalert) for setting the icon and include information on how to revert it back, I couldn't find an easy way to do that.

- Remove /command-icon.png

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-12-12 09:16 UTC, pernielsentikaer commented on extensions/macosicons/package.json
> +  "title": "MacOSIcons.com",
```suggestion
  "title": "MacOSIcons",
```
Could we use this name instead?

2023-12-12 09:16 UTC, pernielsentikaer commented on extensions/macosicons/src/components/actions/icon-actions.tsx
> +    <ActionPanel.Submenu title="Save As New Icon For" icon={Icon.Highlight}>
```suggestion
    <ActionPanel.Submenu title="Save as New Icon For" icon={Icon.Highlight}>
```

2024-01-22 06:04 UTC, closed without merging

2024-01-29 07:32 UTC, Visual-Studio-Coder commented
hmm. I really was looking forward to this extension. (did you possibly forget to click the request re-review button?)

2024-02-14 15:06 UTC, 3llomi commented
Is there any chance for this to get reviewed?

2024-02-14 15:41 UTC, Visual-Studio-Coder commented
Yeah, just request rereview by clicking that button 🙏🏼  🙏🏼  🙏🏼  🙏🏼  dude I seriously need this extension

2024-02-15 10:30 UTC, pernielsentikaer commented
It's still awaiting @shldk to make the corrections, and we have to figure out some things. Nothing has changed since my last review, as far as I can see.