Update anonaddy extension
raycast/extensions pull request #9621
Opened 2023-12-09 00:08 UTC by mormubis

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-12-12 09:42 UTC, pernielsentikaer requested changes
Hi @mormubis 👋 

Thanks for your contribution 🔥

@httpjamesm do you mind checking this?

2023-12-12 09:42 UTC, pernielsentikaer commented on extensions/anonaddy/package.json
> +    "@raycast/api": "^1.39.3",
Should we bump this?

2023-12-12 09:42 UTC, pernielsentikaer commented on extensions/anonaddy/CHANGELOG.md
> +## [Unreleased] - 2023-12-03
You can use write [Enhancements]

2023-12-12 17:08 UTC, httpjamesm commented
> Hi @mormubis 👋 
> 
> Thanks for your contribution 🔥
> 
> @httpjamesm do you mind checking this?

Looks ok to me

2023-12-13 09:01 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2023-12-13 09:13 UTC, merged