Add web3bio extension
raycast/extensions pull request #9623
Opened 2023-12-09 07:26 UTC by picturepan2

## Description

## Screencast

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-12-12 09:47 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you 🙂

- Can you give me a few example on profiles I can search for?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2023-12-12 09:47 UTC, pernielsentikaer commented on extensions/web3bio/src/web3bio.tsx
> +      }
Is this necessary?

2023-12-12 13:43 UTC, picturepan2 commented on extensions/web3bio/src/web3bio.tsx
> +      }
No. Removed.

2023-12-12 13:52 UTC, picturepan2 commented
Hi @pernielsentikaer Thanks for your review. [Web3.bio](https://web3.bio) is the Identity Explorer for Web3. You could try `vitalik.eth`, one of the founders of Ethereum, in the Raycast searchbox and the search results are all profiles that connected to his Web3 identity. Also, you can try searching for`nick.eth` or `brantly.eth` to see what profiles are connected to their Web3 identities. In the profile detail panel, you will see all their bio, contact info and social links there.

2024-01-02 13:56 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-01-02 14:19 UTC, merged