Add 'Verify Number' extension
raycast/extensions pull request #9636
Opened 2023-12-10 12:57 UTC by xmok

## Description

This is a Raycast extension for [Number Verification API](https://apilayer.com/marketplace/number_verification-api) by [APILayer](https://apilayer.com/). With this extension you can perform lookup for a total of 232 countries around the world and verify the validity of phone numbers.

## Screencast

https://github.com/raycast/extensions/assets/30526133/d8cf9bf6-2c41-4c81-8385-5be0ade20171

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2023-12-12 09:58 UTC, pernielsentikaer requested changes
Thanks for your contribution 🔥 I left a few comments for you 🙂

2023-12-12 09:58 UTC, pernielsentikaer commented on extensions/verify-number/package.json
> +          "placeholder": "NUMBER"
```suggestion
          "placeholder": "Number"
```

2023-12-12 11:28 UTC, xmok commented
Resolved and updated `package.json` 🫡.

2024-01-04 10:12 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-01-04 10:25 UTC, merged