New Extension: Nativebase Documentation
raycast/extensions pull request #967
Opened 2022-02-23 00:50 UTC by ShubhamVerma1811

## Description

This extensions helps to search the nativebase.io documentation from within the Raycast. It also support different versions of Nativebase documentations.

## Screencast

<img width="862" alt="ss-versions" src="https://user-images.githubusercontent.com/25576658/155244435-86d54879-ee80-4944-9c6a-e05f28a71f92.png">
<img width="862" alt="ss-pages" src="https://user-images.githubusercontent.com/25576658/155244443-6af98aed-65a4-42ac-b545-bbdb20219ad7.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-02-23 08:14 UTC, ShubhamVerma1811 commented
Found a bug, fixing it.

2022-03-04 19:25 UTC, pernielsentikaer requested changes
Hi @ShubhamVerma1811 👋 

Thanks for your contribution 💯 What does the most of the users do here? Are they using different versions at the same time?

Could you move everything related to the README to a folder in the root called `media` instead, icons used in the extension is in the right folder 💪 

 There are a few approaches that could fit:
- The way it is now, but it makes an extra step before its “ready” to use
- Create a preference dropdown with the versions (so only one version is in use)
- Create each version as a separate commands (So the users can “disable” and even bind hotkeys and alias)

Could one of the last two fit in instead? 

Another approach about the rate limit could be to cache the result for an hour, this way it's possible to remove the GitHub Personal Token part completely!

Let me know what you think 😄 Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-06 10:53 UTC, ShubhamVerma1811 commented
Hey @pernielsentikaer, Thank you for the feedback!
- I could move README assets in `media`
-  Also look into caching the results

> Create a preference dropdown with the versions (so only one version is in use)

I personally feel like as a user I would switch between the versions for checking the docs if something was updated or added in the docs that was not documented in other versions. And having a set preference version won't be helping with that.

> Create each version as a separate commands (So the users can “disable” and even bind hotkeys and alias)

I am unclear what you meant here. Did you something like this?
If not, Could you please share some example of what you meant?

<img width="862" alt="Screenshot 2022-03-06 at 16 19 49" src="https://user-images.githubusercontent.com/25576658/156919905-b580af24-3b6a-44f6-9783-223fc467d5c2.png">

2022-03-06 21:25 UTC, pernielsentikaer commented
We could do something like this:

![2to6HpKWVcWAhAUQ](https://user-images.githubusercontent.com/38033107/156942766-f8e41e32-4de4-450e-b48d-fe24a2f39c37.png)

Then it's possible to bind alias or hotkey to each version, even disable a version, does it make any sense?

2022-03-07 04:47 UTC, ShubhamVerma1811 commented
I see.
But this would require to add the commands in the package.json
But the versions would be dynamic, coming from the github

2022-03-07 14:18 UTC, pernielsentikaer requested changes
Hi @ShubhamVerma1811 👋 

Most of the documentation packages created at the moment is maintained manually, there is no way to programmatic create commands, but it's suggested in #939 – give your feedback in the thread 😄 

If you want to keep it as it is, then I think it's okay.

Did you consider removing the GitHub PAT in favor of cache?

I left some feedback for you to address 💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-07 14:18 UTC, pernielsentikaer commented on extensions/nativebase-docs/package.json
> +      "title": "NativeBase Documention",
```suggestion
      "title": "Search Documention",
      "subtitle": "NativeBase",
```

2022-03-07 14:18 UTC, pernielsentikaer commented on extensions/nativebase-docs/src/index.tsx
> +    <List navigationTitle="Select documentation version" isLoading={loading}>
```suggestion
    <List navigationTitle="Select Documentation Version" isLoading={loading}>
```

2022-03-07 14:18 UTC, pernielsentikaer commented on extensions/nativebase-docs/src/index.tsx
> +        {versions.map((version, index) => (
Shouldn't the list be “inverted” – showing the newest first?

2022-03-07 14:18 UTC, pernielsentikaer commented on extensions/nativebase-docs/src/index.tsx
> +                  title={`Open Docs for ${version}`}
Could be visually a bit more awesome with an icon here too 😄

2022-03-08 05:19 UTC, pernielsentikaer requested changes
Hi @ShubhamVerma1811 👋 

Much better 🔥 Found one last thing before we're ready to merge 🚀 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-08 05:19 UTC, pernielsentikaer commented on extensions/nativebase-docs/src/components/Docs.tsx
> +      navigationTitle={`NB Docs for version ${props.version}`}
```suggestion
      navigationTitle={`NativeBase ${props.version} Documentation`}
```

2022-03-08 05:22 UTC, ShubhamVerma1811 commented
Sure!
Looking into how to cache the results.

2022-03-08 05:23 UTC, pernielsentikaer commented
Awesome @ShubhamVerma1811 🔥

2022-03-12 09:22 UTC, ShubhamVerma1811 commented
Hey @pernielsentikaer 
Made the necessary changes!

2022-03-14 05:21 UTC, pernielsentikaer commented
Awesome @ShubhamVerma1811 🔥 🔥 

Could you change in the README also, so it don't say anything about PAT? 😄

2022-03-14 05:25 UTC, ShubhamVerma1811 commented
> Awesome @ShubhamVerma1811 🔥 🔥
> 
> Could you change in the README also, so it doesn't say anything about PAT? 😄

Done!

2022-03-14 08:44 UTC, pernielsentikaer approved these changes
Hi @ShubhamVerma1811 👋 

Much better, thanks! 🔥

2022-03-14 22:54 UTC, mattisssa approved these changes

2022-03-14 22:54 UTC, merged

2022-03-14 23:01 UTC, mattisssa commented
Hey @ShubhamVerma1811! Thanks for the contribution, you added some screenshots for your extension but the folder name you used was wrong, I've updated that but missed that the screenshots are actually doesn't match our [guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store#adding-screenshots). As far as I guess these are the screenshot sizes. 

Could you please take a look at that and update it?

2022-03-15 01:12 UTC, ShubhamVerma1811 commented
Yay! ❤️