A new way to upload pictures to oss.
raycast/extensions pull request #972
Opened 2022-02-23 15:11 UTC by yangxyo

## Description
OSS is An object storage service provided by Alibaba.

This extension is a easy way for you to upload a picture to OSS,

and return the url.

Just copy a image type file or screen capture successfully,

then open Raycast and typing oss.

## Screencast
<img width="753" alt="upload-success" src="https://user-images.githubusercontent.com/32320149/155352248-5033cca3-1c92-4a38-8a1a-12a78657c854.png">

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-03-02 21:20 UTC, pernielsentikaer requested changes
Hi @yangxyo 👋 

Thanks for your contribution, I have some comments and feedback for you to address

- The extension needs a proper icon which is not the default example icon
- Since It's not possible to test for me, can you record a screencast of the flow

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-02 21:20 UTC, pernielsentikaer commented on extensions/oss/README.md
> +![upload-success screenshots](./images/upload-success.png)
Could you rename the folder `images` to `media` instead

2022-03-02 21:20 UTC, pernielsentikaer commented on extensions/oss/package.json
> +  "description": "Publish the picture in your clipboard to aliyun oss, and return url.",
```suggestion
  "description": "Publish the picture in your clipboard to Aliyun OSS, and return the URL.",
```

2022-03-02 21:20 UTC, pernielsentikaer commented on extensions/oss/package.json
> +      "title": "Pic Upload",
```suggestion
      "title": "Upload Picture",
      "subtitle": "Aliyun OSS",
```

2022-03-02 21:20 UTC, pernielsentikaer commented on extensions/oss/package.json
> +      "description": "Upload the most top picture in your clipboard.",
```suggestion
      "description": "Upload picture from the clipboard.",
```

2022-03-03 03:24 UTC, yangxyo commented
@pernielsentikaer 
I have solved all the problems you raised.
Please...

2022-03-04 04:55 UTC, pernielsentikaer commented
Thanks, @yangxyo 💪 

Can you create video showing the extension, so I have a better idea of what's going on? 😄

2022-03-04 06:19 UTC, yangxyo commented
https://user-images.githubusercontent.com/32320149/156487976-94ec9ec1-cb5f-4c90-af60-792314daecd0.mov

2022-03-04 06:57 UTC, pernielsentikaer requested changes
Hi @yangxyo 👋 

Thanks for the video, it helped with the understanding 😄 

I have some feedback and comments for you to address:

- I would show a failure toast if clipboard is empty (lack image)
- Maybe rename the extension folder to something like`aliyun-oss`

We're getting closer, looking forward to testing it out again 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-04 06:57 UTC, pernielsentikaer commented on extensions/oss/src/index.tsx
> +    <List isLoading={!pic.url}>
```suggestion
    <List isLoading={pic.url !== ""}>
```

2022-03-04 07:38 UTC, yangxyo commented
<img width="845" alt="image" src="https://user-images.githubusercontent.com/32320149/156719786-488ea333-8097-4bb5-a7b5-b656419acb7d.png">

Why do you would like to change `{!pic.url}` to `{pic.url !== ""}`?

2022-03-04 07:40 UTC, yangxyo commented
I've changed oss to 阿里云-oss

2022-03-04 12:47 UTC, pernielsentikaer commented
> Why would you like to change `{!pic.url}` to `{pic.url !== ""}`?

I'm not at my machine right now, but yeah, I'm totally wrong there 😄 

What you need to look into is when anything goes wrong, it never stops the loader:

https://user-images.githubusercontent.com/38033107/156766140-7b02d07a-9c79-4b33-8ebb-5c990fc14d4f.mp4

2022-03-04 13:18 UTC, yangxyo commented
@pernielsentikaer 
Fixed.
<img width="277" alt="image" src="https://user-images.githubusercontent.com/32320149/156770302-3680d54e-7b0f-40a0-b5d9-572738bd00fa.png">

2022-03-04 14:32 UTC, pernielsentikaer requested changes
Much better @yangxyo 🔥 

Last feedback before merging 😄 

- Would be nice with a better toast when `pngpaste` is not installed, maybe check if path exists?
- No need to title case in toasts, could you write it like “Copy image failed”

When this is corrected, then I'm sure we're ready to ship 🚢

2022-03-05 06:43 UTC, yangxyo commented
@pernielsentikaer 
🚀

2022-03-05 07:18 UTC, pernielsentikaer requested changes
Hi @yangxyo 👋 

I have left some more feedback, we're getting pretty close now 💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-05 07:18 UTC, pernielsentikaer commented on extensions/aliyun-oss/package.json
> +      "placeholder": "http://raycast.com",
```suggestion
      "placeholder": "https://raycast.com",
```

2022-03-05 07:18 UTC, pernielsentikaer commented on extensions/aliyun-oss/src/index.tsx
> +              handleShowToast("Convert URL Failed.");
```suggestion
              handleShowToast("Convert URL failed.");
```

2022-03-05 07:18 UTC, pernielsentikaer commented on extensions/aliyun-oss/src/index.tsx
> +        handleShowToast("Copy Image Failed.");
```suggestion
        handleShowToast("Copy image failed.");
```

2022-03-05 07:18 UTC, pernielsentikaer commented on extensions/aliyun-oss/src/index.tsx
> +      handleShowToast("The Path Of Pngpaste Is Wrong.");
```suggestion
      handleShowToast("The path ff pngpaste is wrong.");
```

2022-03-05 07:18 UTC, pernielsentikaer commented on extensions/aliyun-oss/src/index.tsx
> +      title: title,
```suggestion
      title: "An error occurred",
```

2022-03-05 08:57 UTC, yangxyo commented
@pernielsentikaer 
Ok.

2022-03-06 20:02 UTC, pernielsentikaer approved these changes
Hi @yangxyo 👋 

I think were ready to get it merged, and then we take eventually issues later on if anything arrives 💪 

Approved! 💯

2022-03-07 13:31 UTC, fe9lix commented
Hey @yangxyo, the PR still contains the (old?) oss folder, in addition to the renamed folder. I guess that's a leftover and should be removed?

2022-03-07 15:16 UTC, yangxyo commented
@fe9lix Sorry, I removed it.

2022-03-07 16:03 UTC, merged