New Extension: Raynab
raycast/extensions pull request #982
Opened 2022-02-24 16:45 UTC by gogocharli

## Description

With the help of the YNAB API, Raynab allows users of Raycast to manage their budgets completely from inside the application. The main commands of the extensions are:

- Select Active Budget
- View Active Budget
- List Transactions
- Create Transaction
- List Accounts

## Screencast

https://cln.sh/zpT95y

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-03-04 20:39 UTC, pernielsentikaer requested changes
Wow, @gogocharli! 🚀 

What an extension, it's hard to test it fully – also, never tried YNAB before but everything I've tested is working 😄 

I gave it a good long spin but couldn't really find anything in the first run 🔥 

- One thing I noticed is that all amounts in the extension is in USD, I think we should remove that – or if possible (maybe too hard?), get the currency from the app and show (then it's not localization) 

What do you think? 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you want to discuss if you have any questions.

2022-03-04 20:39 UTC, pernielsentikaer commented on extensions/raynab/package.json
> +      "title": "Select Active Budget",
```suggestion
      "title": "Select Active Budget",
      "subtitle": "YNAB",
```

2022-03-04 20:39 UTC, pernielsentikaer commented on extensions/raynab/package.json
> +      "title": "List Transactions",
```suggestion
      "title": "List Transactions",
      "subtitle": "YNAB",
```

2022-03-04 20:39 UTC, pernielsentikaer commented on extensions/raynab/package.json
> +      "title": "Create Transaction",
```suggestion
      "title": "Create Transaction",
      "subtitle": "YNAB",
```

2022-03-04 20:39 UTC, pernielsentikaer commented on extensions/raynab/package.json
> +      "title": "List Accounts",
```suggestion
      "title": "List Accounts",
      "subtitle": "YNAB",
```

2022-03-04 20:39 UTC, pernielsentikaer commented on extensions/raynab/package.json
> +      "title": "View Active Budget",
```suggestion
      "title": "View Active Budget",
      "subtitle": "YNAB",
```

2022-03-04 21:23 UTC, gogocharli commented
Hello @pernielsentikaer, thank you for the review!

> One thing I noticed is that all amounts in the extension is in USD, I think we should remove that – or if possible (maybe too hard?), get the currency from the app and show (then it's not localization)

This is already possible. But YNAB defaults that setting to USD by default for the budgets.

See below when I change my test account to Euros.

![CleanShot 2022-03-04 at 16 22 22](https://user-images.githubusercontent.com/49351279/156843412-7b91bda9-9a28-4da2-9e15-2ba3e0ab229d.png)
![CleanShot 2022-03-04 at 16 23 14](https://user-images.githubusercontent.com/49351279/156843500-3dcf8c61-0a6f-41d3-b1f7-5a150e522f8c.png)
![CleanShot 2022-03-04 at 16 23 23](https://user-images.githubusercontent.com/49351279/156843506-0d75d2ca-04a9-4d75-b8a5-16dc58678a98.png)

2022-03-05 05:53 UTC, pernielsentikaer requested changes
Hi @gogocharli 👋 

You're on 🔥 What an extension! For me, it's such a powerful showcase you're doing here!

I think I've missed the that part, after changing the currency I had to “Set Active Budget” again in order to get the right values within the extension 😄 

Is there a way to add the currency to `List Transactions`, seems like it's one of the few places where it's not present?

I'm not sure if it's possible, but it could be cool if `Currency Placement` from YNAB was used within the extension, but it's a NIT

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-05 15:23 UTC, gogocharli commented
Hi again @pernielsentikaer, thank you for the suggestion!

I had previously decided not to show the transactions list because it seemed too distracting in the list view. But, you're right, it is more consistent with the app.

I have used the `CurrencyFormat` setting within YNAB to make the changes as suggested 😄 

**Symbol after amount**

<img width="762" alt="CleanShot 2022-03-05 at 09 49 57@2x" src="https://user-images.githubusercontent.com/49351279/156889538-5c653a6b-4ff8-4fdc-a7a4-dcd05b0a241f.png">

**Symbol before amount**

<img width="770" alt="CleanShot 2022-03-05 at 09 48 42@2x" src="https://user-images.githubusercontent.com/49351279/156889545-c8854df3-4140-483e-9c33-ccb0f64aae74.png">

**Symbol before amount (negative)**

<img width="767" alt="CleanShot 2022-03-05 at 10 04 53@2x" src="https://user-images.githubusercontent.com/49351279/156889542-087f0a02-7113-4fbf-99be-793cbab3aaeb.png">

**No Symbol**

<img width="781" alt="CleanShot 2022-03-05 at 09 48 01@2x" src="https://user-images.githubusercontent.com/49351279/156889547-de6b5063-df57-4112-802d-f840d8c0b759.png">

2022-03-06 20:45 UTC, pernielsentikaer requested changes
Another great update @gogocharli 🔥 

We're close to merging, I have the last feedback before we're ready to ship it 💪

- When selecting an active budget, it would then be nice with a Toast showing a status, right now it feels like it doesn't work 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-06 23:20 UTC, gogocharli commented
Thank you for another great suggestion, @pernielsentikaer.

This is now updated!

2022-03-07 14:06 UTC, pernielsentikaer approved these changes
Hi @gogocharli 👋 

This extension is another great example of what's possible to archive with the API – well done! I'm out of ideas, but still a bit blown about the extension 😄 

Approved, it has been a pleasure working with you 🔥

2022-03-07 14:15 UTC, merged