Add Laracasts search as extension
raycast/extensions pull request #990
Opened 2022-02-25 12:59 UTC by danyelkeddah

## Description

Add [Laracasts](https://laracasts.com/) search as extension to raycast.

## Screencast

<img width="935" alt="raycast-laracasts" src="https://user-images.githubusercontent.com/14123621/155719095-efdb9eb3-47cc-4081-899e-d28647b321ad.png">

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-03-04 20:54 UTC, pernielsentikaer requested changes
Hi @danyelkeddah 👋 

Thanks for another contribution 💯 

I have some feedback ready for you to address 💪 

- Could you move the screenshot to `media` folder

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-04 20:54 UTC, pernielsentikaer commented on extensions/laracasts/package.json
> +      "title": "Search Laracasts",
```suggestion
      "title": "Search Course",
```
Could that go?

2022-03-05 05:42 UTC, pernielsentikaer requested changes
Hi @danyelkeddah 👋 

Just found one more to be corrected, when this is done, then we're ready to take it to the next level 💯 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-05 05:42 UTC, pernielsentikaer commented on extensions/laracasts/src/laracasts.tsx
> +  const [isLoading, setIsLoading] = useState(false);
```suggestion
  const [isLoading, setIsLoading] = useState(true);
```
We need this to remove [empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states)

2022-03-05 05:52 UTC, danyelkeddah commented
Thanks @pernielsentikaer 👍🏻 , Just applied the fixes and ready for your review.

2022-03-05 06:08 UTC, pernielsentikaer requested changes
Hi @danyelkeddah 👋 

Thanks for the update, it does however seem like there is a bit more [empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) that we didn't catch!

When logging, I see this:

```
07:06:21.107 isLoading: true | items found: undefined
07:06:21.517 isLoading: false | items found: undefined
07:06:21.519 isLoading: false | items found: 1
```

Seems like it still stops the loader before it's ready, can you address this?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-06 19:48 UTC, pernielsentikaer approved these changes
Awesome @danyelkeddah 💪 Much appreciated 💯 

I'm going to approve it, well done 🚀

2022-03-07 13:34 UTC, merged