Add collected-notes extension
raycast/extensions pull request #9915
Opened 2023-12-29 14:43 UTC by txemaleon

## Description

Collected Notes is an online notes system which lets you publish as a blog. It offers an API which this extension connects to and let's you manage your notes, edit, set visibility, or delete them entirely.

## Screencast

All the functionality is covered on the metadata screenshots.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

2024-01-09 12:24 UTC, pernielsentikaer requested changes
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- If using wrong credentials it never stops loading, it should stop loading and let the user know if possible.

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

2024-01-15 11:28 UTC, txemaleon commented
Good morning.

I've added validation to every command, now it checks wether you're properly logged in.

I've also pulled your contributions properly, I feel the subtitle in one of the commands does not fit well since it's the same as the title.

![Raycast 2024-01-15 at 08 26 21](https://github.com/raycast/extensions/assets/5676055/4cc4b508-c7b8-43a2-991a-65e712e0d6f9)

Hope it fits the store.

2024-01-15 11:34 UTC, pernielsentikaer commented
You're right about the subtitle, you could also remove it from the second again and call it `Create Collected Note` instead 🙂

It would be okay if it just failed when you tried to create the note, right not I get almost 2 seconds before the validation for that command show up 🙂

Awesome work 🔥

2024-01-15 11:34 UTC, pernielsentikaer requested changes
As stated above 🙂

2024-01-15 14:21 UTC, txemaleon commented
I've renamed both commands and removed the subtitles -which still shows the command name-.

I've also removed the validation in the create-note command but instead made it to show a toast if there is any problem.

Validation also must complete before creating the note.

2024-01-16 08:14 UTC, pernielsentikaer requested changes
Thanks for the corrections 🔥

While being in development mode it might show the name in subtitle, when it's build it shoildn't

I left a few comments for you 🙂

- Could you make sure that actions panel items all have icons 🙂

- Check my suggestions

2024-01-16 08:14 UTC, pernielsentikaer commented on extensions/collected-notes/src/layouts/InvalidCredentials.tsx
> +					<Action title="Open Extension Preferences" onAction={openExtensionPreferences} />
```suggestion
					<Action title="Open Extension Preferences" icon={Icon.Gear} onAction={openExtensionPreferences} />
```

2024-01-16 08:14 UTC, pernielsentikaer commented on extensions/collected-notes/src/layouts/InvalidCredentials.tsx
> +import { Action, ActionPanel, Detail, openExtensionPreferences } from "@raycast/api";
```suggestion
import { Action, ActionPanel, Detail, Icon, openExtensionPreferences } from "@raycast/api";
```

2024-01-16 08:14 UTC, pernielsentikaer commented on extensions/collected-notes/.prettierrc
> +	"useTabs": true
```suggestion
```
Could you remove this so we have the same settings for all extensions, it might require a fix-lint to be ran from package.json 🙂

2024-01-16 10:50 UTC, txemaleon commented
I've merged your changes and also made a little adjustment to the `Create Note` Action to have an icon an a proper title whenever you want to send the note.

I've also run a `fix-lint` with no tabs.

2024-01-17 13:21 UTC, pernielsentikaer approved these changes
Hi 👋 

Looks good to me, approved 🔥

2024-01-17 13:35 UTC, txemaleon commented
Wondeful! Thanks!

2024-01-17 13:44 UTC, merged

2024-04-15 06:17 UTC, alex-cory commented
Would be super cool if you could sync up a Notion db for this