Fix a security issue of KeepassXC extension
raycast/extensions pull request #996
Opened 2022-02-26 05:24 UTC by zkytech

## Description

1.Replace `echo` with `stdin.write` . #983 
2.Show HUD when copy password or  username 
 
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-03-02 21:59 UTC, pernielsentikaer requested changes
Hi @zkytech 👋 

Thanks for the update! 💎 

I corrected some description/placeholders – could you correct the rest?

I tested the extension, and it still works as expected, awesome 💣 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-02 21:59 UTC, pernielsentikaer commented on extensions/keepassxc/package.json
> +      "description": "Password of Keepass Database. For More Information about Security, Please Visit README on Github",
```suggestion
      "description": "Password of Keepass database. For more information about security, please visit README on GitHub",
```

2022-03-02 21:59 UTC, pernielsentikaer commented on extensions/keepassxc/package.json
> +      "placeholder": "Please Input Password of Keepass Database."
```suggestion
      "placeholder": "Please input password of Keepass database."
```

2022-03-03 08:48 UTC, zkytech commented
@pernielsentikaer  Done.

2022-03-03 10:55 UTC, pernielsentikaer approved these changes
Awesome @zkytech 🔥 

Thanks for the corrections, approved! 👏

2022-03-03 13:07 UTC, sxn commented
🎉

2022-03-03 13:08 UTC, merged