Add „Karabiner Profile Switcher“ extension
raycast/extensions pull request #998
Opened 2022-02-26 15:20 UTC by lucaschultz

## Description

The extension allow switching between profiles of [Karabiner Elements](https://karabiner-elements.pqrs.org) and opening the app. The code is largely based on the Keyboard Layout Switcher extension for which I opened a [pull request](https://github.com/raycast/extensions/pull/993) but does not have any dependencies (binary or otherwise) aside from the Raycast API. It uses the [Karabiner CLI](https://karabiner-elements.pqrs.org/docs/manual/misc/command-line-interface/) to switch between the profiles.

## Screencast

https://user-images.githubusercontent.com/45899273/155848454-3a5dc023-6843-4b49-8930-e1ac193fce13.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

2022-03-02 22:18 UTC, pernielsentikaer requested changes
Hi @lucaschultz 👋 

Awesome extension 🔥 I have some feedback for you:

- When Karabiner Elements CLI is not installed, then it should stop the `loading` and return empty array to the list, so it shows “No Results” – right now it keeps loading. 

I tested it, and it does work as expected, good job 💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

2022-03-02 22:18 UTC, pernielsentikaer commented on extensions/karabiner-profile-switcher/src/index.tsx
> +    title: "An Error Occured",
```suggestion
    title: "An error occurred",
```

2022-03-02 22:18 UTC, pernielsentikaer commented on extensions/karabiner-profile-switcher/src/index.tsx
> +            ...toastErrorOptions("Karabiner Elements CLI Not Available", `${e}`),
```suggestion
            ...toastErrorOptions("Karabiner Elements CLI not available", `${e}`),
```

2022-03-02 22:18 UTC, pernielsentikaer commented on extensions/karabiner-profile-switcher/src/index.tsx
> +          await showToast(toastErrorOptions("Couldn't Get Profiles", `${e}`));
```suggestion
          await showToast(toastErrorOptions("Couldn't get profiles", `${e}`));
```

2022-03-02 22:18 UTC, pernielsentikaer commented on extensions/karabiner-profile-switcher/src/index.tsx
> +    <List isLoading={profiles.length === 0} searchBarPlaceholder="Search available layout...">
```suggestion
    <List isLoading={profiles.length === 0} searchBarPlaceholder="Search available layouts...">
```

2022-03-02 22:18 UTC, pernielsentikaer commented on extensions/karabiner-profile-switcher/src/model/KarabinerManager.ts
> +      throw new Error(`Karabiner Profile "${this.title}" Not Found`);
```suggestion
      throw new Error(`Karabiner Profile "${this.title}" not found`);
```

2022-03-03 12:01 UTC, lucaschultz commented
@pernielsentikaer Good catch! The`loading` is now interrupted when the `Karabiner Elements CLI not available` error `Toast` is shown.

2022-03-03 13:39 UTC, pernielsentikaer approved these changes
Hi @lucaschultz 👋 

Awesome update 🔥 it works as expected – well done! 💣

2022-03-03 15:49 UTC, sxn commented
nice work! While testing, I found an issue when you have multiple profiles with the same name:

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/1155589/156599792-8a861ebc-22f7-4f35-95c2-23c3cba3bf11.png">

<img width="929" alt="image" src="https://user-images.githubusercontent.com/1155589/156599972-d4ece98c-67ab-4764-90e5-b1e599a9c3b1.png">

Since this seems to be a limitation of [karabiner_cli](https://karabiner-elements.pqrs.org/docs/manual/misc/command-line-interface/) though & this is an edge case, I'll merge the PR anyway.

🎉

2022-03-03 15:49 UTC, merged